### ISSUE TITLE
error in the latest code

### ISSUE THREAD

**Issue by lan2720** [allenai/allennlp#1015]
I use `pip install git+https://github.com/allenai/allennlp.git` to get the latest code (allennlp-0.4.1-unreleased).
And run 
```
echo '{"sentence": "Did Uriah honestly think he could beat the game in under three hours?"}' > examples.jsonl
python -m allennlp.run predict \
    https://s3-us-west-2.amazonaws.com/allennlp/models/srl-model-2017.09.05.tar.gz  \
    examples.jsonl
```
Then I get the error
```
Traceback (most recent call last):
  File "/Users/Lan/.pyenv/versions/3.6.4/lib/python3.6/site-packages/allennlp/common/params.py", line 94, in pop
    value = self.params.pop(key)
KeyError: 'encoder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Lan/.pyenv/versions/3.6.4/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/Lan/.pyenv/versions/3.6.4/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/Lan/.pyenv/versions/3.6.4/lib/python3.6/site-packages/allennlp/run.py", line 18, in <module>
    main(prog="python -m allennlp.run")
  File "/Users/Lan/.pyenv/versions/3.6.4/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 64, in main
    args.func(args)
  File "/Users/Lan/.pyenv/versions/3.6.4/lib/python3.6/site-packages/allennlp/commands/predict.py", line 158, in _predict
    predictor = _get_predictor(args)
  File "/Users/Lan/.pyenv/versions/3.6.4/lib/python3.6/site-packages/allennlp/commands/predict.py", line 104, in _get_predictor
    overrides=args.overrides)
  File "/Users/Lan/.pyenv/versions/3.6.4/lib/python3.6/site-packages/allennlp/models/archival.py", line 149, in load_archive
    cuda_device=cuda_device)
  File "/Users/Lan/.pyenv/versions/3.6.4/lib/python3.6/site-packages/allennlp/models/model.py", line 233, in load
    model = Model.from_params(vocab, model_params)
  File "/Users/Lan/.pyenv/versions/3.6.4/lib/python3.6/site-packages/allennlp/models/model.py", line 184, in from_params
    model = cls.by_name(choice).from_params(vocab, params)
  File "/Users/Lan/.pyenv/versions/3.6.4/lib/python3.6/site-packages/allennlp/models/semantic_role_labeler.py", line 207, in from_params
    encoder = Seq2SeqEncoder.from_params(params.pop("encoder"))
  File "/Users/Lan/.pyenv/versions/3.6.4/lib/python3.6/site-packages/allennlp/common/params.py", line 96, in pop
    raise ConfigurationError("key \"{}\" is required at location \"{}\"".format(key, self.history))
allennlp.common.checks.ConfigurationError: 'key "encoder" is required at location "model."'
```

**Comment by joelgrus** [comment]
sorry, we made changes to the SRL model, and the archive you're pointing at is designed for the released version.

if you're using the latest code, point at 

https://s3-us-west-2.amazonaws.com/allennlp/models/srl-model-2018.02.27.tar.gz 

instead

**Comment by amandalmia14** [comment]
@joelgrus Still I am getting the same issue...

**Comment by Shujian2015** [comment]
Same here.
