### ISSUE TITLE
allennlp or pytorch problem

### ISSUE THREAD

**Issue by LeoLiu1998** [allenai/allennlp#1019]
While I am using the simple_seq2seq to train my model, after tokenize and add words into vocabulary set, the trainer throws a RunTime error. I am not sure if this is due to implementation in allennlp. 
**P.S.** my allennlp is up-to-date
 
```
2018-03-22 16:50:15,767 - INFO - allennlp.training.trainer - Beginning training.
2018-03-22 16:50:15,767 - INFO - allennlp.training.trainer - Epoch 0/4
2018-03-22 16:50:15,768 - INFO - allennlp.training.trainer - Peak CPU memory usage MB: 165.203968
  0%|          | 0/1 [00:00<?, ?it/s]2018-03-22 16:50:15,780 - INFO - allennlp.training.trainer - Training
Traceback (most recent call last):
  File "/Users/leoliu/anaconda3/envs/WebQA/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/leoliu/anaconda3/envs/WebQA/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/leoliu/anaconda3/envs/WebQA/lib/python3.6/site-packages/allennlp/run.py", line 18, in <module>
    main(prog="python -m allennlp.run")
  File "/Users/leoliu/anaconda3/envs/WebQA/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 67, in main
    args.func(args)
  File "/Users/leoliu/anaconda3/envs/WebQA/lib/python3.6/site-packages/allennlp/commands/train.py", line 113, in train_model_from_args
    train_model_from_file(args.param_path, args.serialization_dir, args.overrides, args.file_friendly_logging)
  File "/Users/leoliu/anaconda3/envs/WebQA/lib/python3.6/site-packages/allennlp/commands/train.py", line 138, in train_model_from_file
    return train_model(params, serialization_dir, file_friendly_logging)
  File "/Users/leoliu/anaconda3/envs/WebQA/lib/python3.6/site-packages/allennlp/commands/train.py", line 290, in train_model
    metrics = trainer.train()
  File "/Users/leoliu/anaconda3/envs/WebQA/lib/python3.6/site-packages/allennlp/training/trainer.py", line 649, in train
    train_metrics = self._train_epoch(epoch)
  File "/Users/leoliu/anaconda3/envs/WebQA/lib/python3.6/site-packages/allennlp/training/trainer.py", line 432, in _train_epoch
    loss = self._batch_loss(batch, for_training=True)
  File "/Users/leoliu/anaconda3/envs/WebQA/lib/python3.6/site-packages/allennlp/training/trainer.py", line 369, in _batch_loss
    output_dict = self._model(**batch)
  File "/Users/leoliu/anaconda3/envs/WebQA/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/leoliu/anaconda3/envs/WebQA/lib/python3.6/site-packages/allennlp/models/encoder_decoders/simple_seq2seq.py", line 125, in forward
    embedded_input = self._source_embedder(source_tokens)
  File "/Users/leoliu/anaconda3/envs/WebQA/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/leoliu/anaconda3/envs/WebQA/lib/python3.6/site-packages/allennlp/modules/text_field_embedders/basic_text_field_embedder.py", line 52, in forward
    token_vectors = embedder(tensor)
  File "/Users/leoliu/anaconda3/envs/WebQA/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/leoliu/anaconda3/envs/WebQA/lib/python3.6/site-packages/allennlp/modules/token_embedders/embedding.py", line 118, in forward
    sparse=self.sparse)
  File "/Users/leoliu/anaconda3/envs/WebQA/lib/python3.6/site-packages/torch/nn/functional.py", line 923, in embedding
    scale_grad_by_freq, sparse
  File "/Users/leoliu/anaconda3/envs/WebQA/lib/python3.6/site-packages/torch/nn/_functions/thnn/sparse.py", line 59, in forward
    output = torch.index_select(weight, 0, indices.view(-1))
RuntimeError: index out of range at /Users/soumith/minicondabuild3/conda-bld/pytorch_1518385717421/work/torch/lib/TH/generic/THTensorMath.c:277
```

**Comment by matt-gardner** [comment]
Can you also post your configuration file?  It looks like this error is due to a mismatch between the vocabulary you're specifying for data processing and the vocabulary that your model is using.

**Comment by LeoLiu1998** [comment]
Yes, this is the config file:
```
{
  "dataset_reader":{
    "type":"seq2seq",

    "source_token_indexers": {
      "tokens": {
        "type": "single_id",
        "namespace": "source_tokens"
      }
    },

    "target_token_indexers": {
      "tokens": {
        "type": "single_id",
        "namespace": "target_tokens"
      }
    }
  },


  "train_data_path": "/Users/leoliu/hyak-package/WebQA/WebQA/corpus_max_350/demo_train.tsv",
  "validation_data_path": "/Users/leoliu/hyak-package/WebQA/WebQA/corpus_max_350/demo_dev.tsv",
  "test_data_path": "/Users/leoliu/hyak-package/WebQA/WebQA/corpus_max_350/demo_test.tsv",

  "model": {
    "type": "simple_seq2seq",
    "source_embedder": {
      "tokens": {
        "type": "embedding",
        "embedding_dim":300,
        "vocab_namespace": "target_tokens",
        "trainable": true
      },
    },

    "encoder": {
      "type": "lstm",
      "input_size": 300,
      "hidden_size": 300,
      "num_layers": 3
    },
    "scheduled_sampling_ratio": 1.0,
    "max_decoding_steps": 350,
    "target_namespace": "target_tokens",
    "attention_function": {"type": "dot_product"}
  },

  "iterator": {
    "type": "bucket",
    "batch_size" : 32,
    "sorting_keys": [["source_tokens", "num_tokens"], ["target_tokens", "num_tokens"]]
  },

  "trainer": {
    "num_epochs": 5,
    "patience": 4,
    "cuda_device": -1,
    "optimizer": {
      "type": "adam",
      "lr": 0.01
    }
  }
}
```

**Comment by matt-gardner** [comment]
Yes, this is a problem with your configuration file.  You have two separate vocabularies, one for input tokens, and one for output tokens:

```json
"source_token_indexers": {
      "tokens": {
        "type": "single_id",
        "namespace": "source_tokens"
      }
    },

    "target_token_indexers": {
      "tokens": {
        "type": "single_id",
        "namespace": "target_tokens"
      }
    }
```

But then you're using the _target_ vocabulary to embed your _source_ tokens:

```json
    "source_embedder": {
      "tokens": {
        "type": "embedding",
        "embedding_dim":300,
        "vocab_namespace": "target_tokens",
        "trainable": true
      },
    },
```

Change the `vocab_namespace` argument there to be `source_tokens`, and you should be fine.

**Comment by matt-gardner** [comment]
Closing this now; if you run into other issues, feel free to re-open this or open a new issue.

**Comment by LeoLiu1998** [comment]
No, I change the config, but the problem persists

**Comment by matt-gardner** [comment]
You're going to have to give more detail than that for us to help you.  What's your new config file?  What's the stack trace?

**Comment by LeoLiu1998** [comment]
Oh, I am sorry, I made a typo; the model is running.
