### ISSUE TITLE
AssertionError when training bidaf

### ISSUE THREAD

**Issue by lan2720** [allenai/allennlp#1072]
Hi, when I train the BiDAF using allennlp, something goes wrong.
```
...
2018-04-10 13:47:35,123 - INFO - allennlp.common.params - trainer.num_epochs = 20
2018-04-10 13:47:35,123 - INFO - allennlp.common.params - trainer.cuda_device = 0
2018-04-10 13:47:35,123 - INFO - allennlp.common.params - trainer.grad_norm = 5.0
2018-04-10 13:47:35,123 - INFO - allennlp.common.params - trainer.grad_clipping = None
Traceback (most recent call last):
  File "/home/wangjianan/anaconda2/envs/allennlp/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/wangjianan/anaconda2/envs/allennlp/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/wangjianan/allennlp/allennlp/run.py", line 18, in <module>
    main(prog="python -m allennlp.run")
  File "/home/wangjianan/allennlp/allennlp/commands/__init__.py", line 65, in main
    args.func(args)
  File "/home/wangjianan/allennlp/allennlp/commands/train.py", line 99, in train_model_from_args
    args.recover)
  File "/home/wangjianan/allennlp/allennlp/commands/train.py", line 129, in train_model_from_file
    return train_model(params, serialization_dir, file_friendly_logging, recover)
  File "/home/wangjianan/allennlp/allennlp/commands/train.py", line 285, in train_model
    trainer_params)
  File "/home/wangjianan/allennlp/allennlp/training/trainer.py", line 892, in from_params
    model = model.cuda(cuda_device)
  File "/home/wangjianan/anaconda2/envs/allennlp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 216, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/wangjianan/anaconda2/envs/allennlp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 146, in _apply
    module._apply(fn)
  File "/home/wangjianan/anaconda2/envs/allennlp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 146, in _apply
    module._apply(fn)
  File "/home/wangjianan/anaconda2/envs/allennlp/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 123, in _apply
    self.flatten_parameters()
  File "/home/wangjianan/anaconda2/envs/allennlp/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 111, in flatten_parameters
    params = rnn.get_parameters(fn, handle, fn.weight_buf)
  File "/home/wangjianan/anaconda2/envs/allennlp/lib/python3.6/site-packages/torch/backends/cudnn/rnn.py", line 165, in get_parameters
    assert filter_dim_a.prod() == filter_dim_a[0]
AssertionError
```

The command I use is `python -m allennlp.run  train training_config/bidaf.json --serialization-dir /tmp/bidaf`. So, how can I fix it?

**Comment by lan2720** [comment]
@DeNeutoy Yep, you're right. I reinstall pytorch and then it returns to normal.
