### ISSUE TITLE
Predict Input Format

### ISSUE THREAD

**Issue by ryanp97** [allenai/allennlp#1095]
I trained a seq2seq model and I'm trying to make predictions using the model, but the prediction command requires a different input format than the training command. Is it possible for the predictor to take the same input format (`<input> \t <expected>`) as the dataloader? For reference, I've included the command and the traceback.

Command:
```
allennlp predict models/baseline/model.tar.gz data/tanaka/simplified/featureless/tanaka-test-eng.txt --batch-size 32 --cuda-device 0 --output-file outputs/baseline.txt --predictor simple_seq2seq
```

Traceback:
```
2018-04-17 04:24:14,529 - INFO - allennlp.common.params - dataset_reader.target_token_indexers.tokens.lowercase_tokens = False
2018-04-17 04:24:14,529 - INFO - allennlp.common.params - dataset_reader.lazy = False
Traceback (most recent call last):
  File "/home/ryanp97/miniconda3/envs/cap/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ryanp97/miniconda3/envs/cap/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ryanp97/miniconda3/envs/cap/lib/python3.6/site-packages/allennlp/run.py", line 18, in <module>
    main(prog="python -m allennlp.run")
  File "/home/ryanp97/miniconda3/envs/cap/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 63, in main
    args.func(args)
  File "/home/ryanp97/miniconda3/envs/cap/lib/python3.6/site-packages/allennlp/commands/predict.py", line 177, in _predict
    args.cuda_device)
  File "/home/ryanp97/miniconda3/envs/cap/lib/python3.6/site-packages/allennlp/commands/predict.py", line 145, in _run
    json_data = predictor.load_line(line)
  File "/home/ryanp97/miniconda3/envs/cap/lib/python3.6/site-packages/allennlp/service/predictors/predictor.py", line 25, in load_line
    return json.loads(line)
  File "/home/ryanp97/miniconda3/envs/cap/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/ryanp97/miniconda3/envs/cap/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/ryanp97/miniconda3/envs/cap/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by joelgrus** [comment]
unfortunately, there's not a way to do that right now. But you're not the first person to ask for it, so let us think about the best way to make that happen. I created #1096 to track it.

In the meantime, you have two options.

(1) write a quick script to transform your inputs into the expected JSON format:

```json
{"source": "..."}
{"source": "..."}
...
```

that's probably the easiest and what I would do.

(2) the predictor expects one input per line, but you can override the JSONL aspect, so if your inputs are just tab-delimited lines, you could create your own `Predictor` subclass that overrides `load_line`:

```python
def load_line(self, line: str) -> JsonDict:
    """you should probably use csv.reader here, but ¯\_(ツ)_/¯"""
    return {"source": line.split("\t")[0]}
```

but then you have all the extra "using allennlp in your library" steps, so I would really do (1) unless it's not feasible for some reason

**Comment by TheresaSchmidt** [comment]
(1) Doesn't work for  me. They key that predict exects is "sentence" and not "source". Also, the number of lines in the input file is determined by the batch size of the model.

**Comment by nadia-felix** [comment]
Is it possible do this?

allennlp predict /home/model.tar.gz /home/teste.json --batch-size 32 --cuda-device 0 --output-file /home/results_seed1000/output.txt
