### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by weronica** [allenai/allennlp#1099]
When I try to run `from allennlp.commands.serve import DEFAULT_MODELS` (from [this test](https://github.com/allenai/allennlp/blob/master/tests/models/sniff_test.py#L3)), I get the error: 
```
~/.virt/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/.virt/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 7, in <module>
    from allennlp.commands.evaluate import Evaluate
  File "~/.virt/lib/python3.6/site-packages/allennlp/commands/evaluate.py", line 43, in <module>
    from allennlp.models.archival import load_archive
  File "~/.virt/lib/python3.6/site-packages/allennlp/models/__init__.py", line 7, in <module>
    from allennlp.models.crf_tagger import CrfTagger
  File "~/.virt/lib/python3.6/site-packages/allennlp/models/crf_tagger.py", line 15, in <module>
    from allennlp.training.metrics import SpanBasedF1Measure
  File "~/.virt/lib/python3.6/site-packages/allennlp/training/__init__.py", line 1, in <module>
    from allennlp.training.trainer import Trainer
  File "~/.virt/lib/python3.6/site-packages/allennlp/training/trainer.py", line 35, in <module>
    from allennlp.training.learning_rate_schedulers import LearningRateScheduler
  File "~/.virt/lib/python3.6/site-packages/allennlp/training/learning_rate_schedulers.py", line 38, in <module>
    "cosine": torch.optim.lr_scheduler.CosineAnnealingLR,
AttributeError: module 'torch.optim.lr_scheduler' has no attribute 'CosineAnnealingLR'
```
I didn't get this error when I was using allennlp 0.3.0; now I'm using 0.4.0. Thoughts?

**Comment by DeNeutoy** [comment]
0.4.0 requires pytorch 0.3.1 : https://github.com/allenai/allennlp/blob/master/requirements.txt#L8

**Comment by weronica** [comment]
Whoops yes I figured that out right after I posted - thanks!
