### ISSUE TITLE
Semantic role labeling prediction doesn't work

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp#1109]
The prediction example on http://allennlp.org/models throws an exception on cbe58971a15aaf6a80d3cc53b1e7c4a9ba4e089c.

```
$ echo '{"sentence": "Did Uriah honestly think he could beat the game in under three hours?"}' > examples.jsonl
$ python -m allennlp.run predict https://s3-us-west-2.amazonaws.com/allennlp/models/srl-model-2017.09.05.tar.gz examples.jsonl

/Users/michael/miniconda3/envs/allennlp/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-04-19 16:06:02,107 - INFO - allennlp.models.archival - extracting archive file /Users/michael/.allennlp/datasets/aHR0cHM6Ly9zMy11cy13ZXN0LTIuYW1hem9uYXdzLmNvbS9hbGxlbm5scC9tb2RlbHMvc3JsLW1vZGVsLTIwMTcuMDkuMDUudGFyLmd6.e53f556a3939b010393f1ed059dd0c61-7 to temp dir /var/folders/v5/tlk1sh3d0l94fcmz10vtzmyh0000gn/T/tmpgrwwn00z
2018-04-19 16:06:03,180 - INFO - allennlp.data.vocabulary - Loading token dictionary from /var/folders/v5/tlk1sh3d0l94fcmz10vtzmyh0000gn/T/tmpgrwwn00z/vocabulary.
2018-04-19 16:06:03,265 - INFO - allennlp.common.params - model.type = srl
2018-04-19 16:06:03,266 - INFO - allennlp.common.params - model.text_field_embedder.type = basic
2018-04-19 16:06:03,266 - INFO - allennlp.common.params - model.text_field_embedder.tokens.type = embedding
2018-04-19 16:06:03,266 - INFO - allennlp.common.params - model.text_field_embedder.tokens.num_embeddings = None
2018-04-19 16:06:03,266 - INFO - allennlp.common.params - model.text_field_embedder.tokens.vocab_namespace = tokens
2018-04-19 16:06:03,267 - INFO - allennlp.common.params - model.text_field_embedder.tokens.embedding_dim = 100
2018-04-19 16:06:03,267 - INFO - allennlp.common.params - model.text_field_embedder.tokens.pretrained_file = None
2018-04-19 16:06:03,267 - INFO - allennlp.common.params - model.text_field_embedder.tokens.projection_dim = None
2018-04-19 16:06:03,267 - INFO - allennlp.common.params - model.text_field_embedder.tokens.trainable = True
2018-04-19 16:06:03,268 - INFO - allennlp.common.params - model.text_field_embedder.tokens.padding_index = None
2018-04-19 16:06:03,268 - INFO - allennlp.common.params - model.text_field_embedder.tokens.max_norm = None
2018-04-19 16:06:03,268 - INFO - allennlp.common.params - model.text_field_embedder.tokens.norm_type = 2.0
2018-04-19 16:06:03,268 - INFO - allennlp.common.params - model.text_field_embedder.tokens.scale_grad_by_freq = False
2018-04-19 16:06:03,268 - INFO - allennlp.common.params - model.text_field_embedder.tokens.sparse = False
Traceback (most recent call last):
  File "/Users/michael/hack/allenai/allennlp/allennlp/common/params.py", line 94, in pop
    value = self.params.pop(key)
KeyError: 'encoder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/michael/miniconda3/envs/allennlp/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/michael/miniconda3/envs/allennlp/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/michael/hack/allenai/allennlp/allennlp/run.py", line 18, in <module>
    main(prog="python -m allennlp.run")
  File "/Users/michael/hack/allenai/allennlp/allennlp/commands/__init__.py", line 65, in main
    args.func(args)
  File "/Users/michael/hack/allenai/allennlp/allennlp/commands/predict.py", line 159, in _predict
    predictor = _get_predictor(args)
  File "/Users/michael/hack/allenai/allennlp/allennlp/commands/predict.py", line 105, in _get_predictor
    overrides=args.overrides)
  File "/Users/michael/hack/allenai/allennlp/allennlp/models/archival.py", line 149, in load_archive
    cuda_device=cuda_device)
  File "/Users/michael/hack/allenai/allennlp/allennlp/models/model.py", line 274, in load
    return cls.by_name(model_type)._load(config, serialization_dir, weights_file, cuda_device)
  File "/Users/michael/hack/allenai/allennlp/allennlp/models/model.py", line 221, in _load
    model = Model.from_params(vocab, model_params)
  File "/Users/michael/hack/allenai/allennlp/allennlp/models/model.py", line 195, in from_params
    model = cls.by_name(choice).from_params(vocab, params)
  File "/Users/michael/hack/allenai/allennlp/allennlp/models/semantic_role_labeler.py", line 209, in from_params
    encoder = Seq2SeqEncoder.from_params(params.pop("encoder"))
  File "/Users/michael/hack/allenai/allennlp/allennlp/common/params.py", line 96, in pop
    raise ConfigurationError("key \"{}\" is required at location \"{}\"".format(key, self.history))
allennlp.common.checks.ConfigurationError: 'key "encoder" is required at location "model."'
```

**Comment by schmmd** [comment]
I can investigate more later, but `git bisect` found:

```
acf21a53e7001bb6c7c3f7113c0d2805ffccceb2 is the first bad commit
commit acf21a53e7001bb6c7c3f7113c0d2805ffccceb2
Author: Sebastian Gehrmann <s.gehrmann@outlook.com>
Date:   Wed Feb 28 11:42:36 2018 -0500

    Fix #928 - Minor naming inconsistency in tutorial json files (#929)
    
    * change stacked_encoder to encoder
    
    * remove log file
    
    * new default model
```

@joelgrus any ideas? https://github.com/allenai/allennlp/pull/929

**Comment by joelgrus** [comment]
we changed the naming of some things to make them consistent. it required a new model, but I guess we forgot to update the docs

https://github.com/allenai/allennlp/pull/929

try it with srl-model-2018.02.27.tar.gz instead and see if that works.

**Comment by schmmd** [comment]
Fixed in https://github.com/allenai/allennlp-website/pull/41.

**Comment by amandalmia14** [comment]
I tried with this but still its not working, can anyone please help.

**Comment by schmmd** [comment]
Hi @amandalmia14, would you be able to open a new GitHub issue and highlight which version of AllenNLP you are using?  I briefly tried to run the SRL model (2018.02.27 and 2018.05.25) and it worked fine, so I'll need more information to reproduce the problem you are running into.

**Comment by amandalmia14** [comment]
@schmmd 
I am using allennlp==0.2.1, "pip install allennlp==0.2.1"

**Comment by schmmd** [comment]
@amandalmia14 I suggest using [the latest release](https://github.com/allenai/allennlp/releases/tag/v0.5.1).  Please open a new GitHub issue if you continue to have problems.

**Comment by amandalmia14** [comment]
@schmmd , I will try, thanks.
Sure will do it.
