### ISSUE TITLE
RecursionError in block_orthogonal

### ISSUE THREAD

**Issue by silentrob** [allenai/allennlp#1161]
Hi friends, this could very much be a user error, trying to get the SRL model working.
```
echo '{"sentence": "Did Uriah honestly think he could beat the game in under three hours?"}' > examples.jsonl
python3 -m allennlp.run predict \
    https://s3-us-west-2.amazonaws.com/allennlp/models/srl-model-2018.02.27.tar.gz \
    examples.jsonl
/Users/robellis/Library/Python/3.6/lib/python/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
2018-04-29 13:05:52,417 - INFO - allennlp.models.archival - extracting archive file /Users/robellis/.allennlp/datasets/aHR0cHM6Ly9zMy11cy13ZXN0LTIuYW1hem9uYXdzLmNvbS9hbGxlbm5scC9tb2RlbHMvc3JsLW1vZGVsLTIwMTguMDIuMjcudGFyLmd6.eaa0980c8eac98bdad7305d26c549378-4 to temp dir /var/folders/fk/71yh6cbj5hsg3lnl13ncg9t40000gp/T/tmpbmbrtnar
2018-04-29 13:05:52,922 - INFO - allennlp.data.vocabulary - Loading token dictionary from /var/folders/fk/71yh6cbj5hsg3lnl13ncg9t40000gp/T/tmpbmbrtnar/vocabulary.
2018-04-29 13:05:53,008 - INFO - allennlp.common.params - model.type = srl
2018-04-29 13:05:53,008 - INFO - allennlp.common.params - model.text_field_embedder.type = basic
2018-04-29 13:05:53,008 - INFO - allennlp.common.params - model.text_field_embedder.tokens.type = embedding
2018-04-29 13:05:53,009 - INFO - allennlp.common.params - model.text_field_embedder.tokens.num_embeddings = None
2018-04-29 13:05:53,009 - INFO - allennlp.common.params - model.text_field_embedder.tokens.vocab_namespace = tokens
2018-04-29 13:05:53,009 - INFO - allennlp.common.params - model.text_field_embedder.tokens.embedding_dim = 100
2018-04-29 13:05:53,009 - INFO - allennlp.common.params - model.text_field_embedder.tokens.pretrained_file = None
2018-04-29 13:05:53,009 - INFO - allennlp.common.params - model.text_field_embedder.tokens.projection_dim = None
2018-04-29 13:05:53,009 - INFO - allennlp.common.params - model.text_field_embedder.tokens.trainable = True
2018-04-29 13:05:53,009 - INFO - allennlp.common.params - model.text_field_embedder.tokens.padding_index = None
2018-04-29 13:05:53,009 - INFO - allennlp.common.params - model.text_field_embedder.tokens.max_norm = None
2018-04-29 13:05:53,009 - INFO - allennlp.common.params - model.text_field_embedder.tokens.norm_type = 2.0
2018-04-29 13:05:53,010 - INFO - allennlp.common.params - model.text_field_embedder.tokens.scale_grad_by_freq = False
2018-04-29 13:05:53,010 - INFO - allennlp.common.params - model.text_field_embedder.tokens.sparse = False
2018-04-29 13:05:53,089 - INFO - allennlp.common.params - model.encoder.type = alternating_lstm
2018-04-29 13:05:53,089 - INFO - allennlp.common.params - model.encoder.batch_first = True
2018-04-29 13:05:53,089 - INFO - allennlp.common.params - Converting Params object to dict; logging of default values will not occur when dictionary parameters are used subsequently.
2018-04-29 13:05:53,089 - INFO - allennlp.common.params - CURRENTLY DEFINED PARAMETERS:
2018-04-29 13:05:53,089 - INFO - allennlp.common.params - model.encoder.input_size = 200
2018-04-29 13:05:53,089 - INFO - allennlp.common.params - model.encoder.hidden_size = 300
2018-04-29 13:05:53,089 - INFO - allennlp.common.params - model.encoder.num_layers = 8
2018-04-29 13:05:53,089 - INFO - allennlp.common.params - model.encoder.recurrent_dropout_probability = 0.1
2018-04-29 13:05:53,089 - INFO - allennlp.common.params - model.encoder.use_highway = True
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/robellis/Library/Python/3.6/lib/python/site-packages/allennlp/run.py", line 18, in <module>
    main(prog="python -m allennlp.run")
  File "/Users/robellis/Library/Python/3.6/lib/python/site-packages/allennlp/commands/__init__.py", line 63, in main
    args.func(args)
  File "/Users/robellis/Library/Python/3.6/lib/python/site-packages/allennlp/commands/predict.py", line 158, in _predict
    predictor = _get_predictor(args)
  File "/Users/robellis/Library/Python/3.6/lib/python/site-packages/allennlp/commands/predict.py", line 104, in _get_predictor
    overrides=args.overrides)
  File "/Users/robellis/Library/Python/3.6/lib/python/site-packages/allennlp/models/archival.py", line 149, in load_archive
    cuda_device=cuda_device)
  File "/Users/robellis/Library/Python/3.6/lib/python/site-packages/allennlp/models/model.py", line 233, in load
    model = Model.from_params(vocab, model_params)
  File "/Users/robellis/Library/Python/3.6/lib/python/site-packages/allennlp/models/model.py", line 184, in from_params
    model = cls.by_name(choice).from_params(vocab, params)
  File "/Users/robellis/Library/Python/3.6/lib/python/site-packages/allennlp/models/semantic_role_labeler.py", line 207, in from_params
    encoder = Seq2SeqEncoder.from_params(params.pop("encoder"))
  File "/Users/robellis/Library/Python/3.6/lib/python/site-packages/allennlp/modules/seq2seq_encoders/seq2seq_encoder.py", line 33, in from_params
    return cls.by_name(choice).from_params(params)
  File "/Users/robellis/Library/Python/3.6/lib/python/site-packages/allennlp/modules/seq2seq_encoders/__init__.py", line 77, in from_params
    module = self._module_class(**params.as_dict())
  File "/Users/robellis/Library/Python/3.6/lib/python/site-packages/allennlp/modules/stacked_alternating_lstm.py", line 66, in __init__
    use_input_projection_bias=use_input_projection_bias)
  File "/Users/robellis/Library/Python/3.6/lib/python/site-packages/allennlp/modules/augmented_lstm.py", line 83, in __init__
    self.reset_parameters()
  File "/Users/robellis/Library/Python/3.6/lib/python/site-packages/allennlp/modules/augmented_lstm.py", line 87, in reset_parameters
    block_orthogonal(self.input_linearity.weight.data, [self.hidden_size, self.input_size])
  File "/Users/robellis/Library/Python/3.6/lib/python/site-packages/allennlp/nn/initializers.py", line 133, in block_orthogonal
    block_orthogonal(tensor.data, split_sizes, gain)
  File "/Users/robellis/Library/Python/3.6/lib/python/site-packages/allennlp/nn/initializers.py", line 133, in block_orthogonal
    block_orthogonal(tensor.data, split_sizes, gain)
  File "/Users/robellis/Library/Python/3.6/lib/python/site-packages/allennlp/nn/initializers.py", line 133, in block_orthogonal
    block_orthogonal(tensor.data, split_sizes, gain)
  [Previous line repeated 970 more times]
  File "/Users/robellis/Library/Python/3.6/lib/python/site-packages/allennlp/nn/initializers.py", line 132, in block_orthogonal
    if isinstance(tensor, Variable):
RecursionError: maximum recursion depth exceeded
```
Python 3.6.5
pip 10.0.1 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)
Mac OSX: 10.13.4

**Comment by silentrob** [comment]
Worked like a charm, thanks so much for the quick reply.

**Comment by babadashagua** [comment]
@joelgrus Thanks a lot! This solves my problem, too.
