### ISSUE TITLE
what's wrong with "--recover" flag?

### ISSUE THREAD

**Issue by Aphrodite-Love** [allenai/allennlp#1175]
Traceback (most recent call last):
  File "/allennlp/main.py", line 20, in <module>
    main()
  File "/allennlp/allennlp/commands/__init__.py", line 63, in main
    args.func(args)
  File "/allennlp/allennlp/commands/train.py", line 99, in train_model_from_args
    args.recover)
  File "/allennlp/allennlp/commands/train.py", line 129, in train_model_from_file
    return train_model(params, serialization_dir, file_friendly_logging, recover)
  File "/allennlp/allennlp/commands/train.py", line 291, in train_model
    metrics = trainer.train()
  File "/allennlp/allennlp/training/trainer.py", line 666, in train
    train_metrics = self._train_epoch(epoch)
  File "/allennlp/allennlp/training/trainer.py", line 460, in _train_epoch
    self._optimizer.step()
  File "/anaconda3/envs/allennlp/lib/python3.6/site-packages/torch/optim/adam.py", line 69, in step
    exp_avg.mul_(beta1).add_(1 - beta1, grad)
TypeError: add_ received an invalid combination of arguments - got (float, torch.cuda.FloatTensor), but expected one of:
 * (float value)
 * (torch.FloatTensor other)
 * (torch.SparseFloatTensor other)
 * (float value, torch.FloatTensor other)
      didn't match because some of the arguments have invalid types: (float, !torch.cuda.FloatTensor!)
 * (float value, torch.SparseFloatTensor other)
      didn't match because some of the arguments have invalid types: (float, !torch.cuda.FloatTensor!)

**Comment by joelgrus** [comment]
I believe this is the issue that was fixed by #1144, which was part of Monday's release.

are you using allennlp version 0.4.2? if not, can you upgrade?

**Comment by Aphrodite-Love** [comment]
Yes! It works on allennlp version 0.4.2! Thanks! @joelgrus
