### ISSUE TITLE
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58

### ISSUE THREAD

**Issue by negacy** [allenai/allennlp#1197]
I am training the neural coreference system on my own dataset, but it's running out of memory. I have the same error while trying to train on the OntoNotes dataset as well. Any suggestion is appreciated. Thanks in advance. 

THCudaCheck FAIL file=/pytorch/torch/lib/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "/opt/python/3.6.3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/python/3.6.3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/neha5486/git/allennlp/allennlp/run.py", line 18, in <module>
    main(prog="python -m allennlp.run")
  File "/Users/neha5486/git/allennlp/allennlp/commands/__init__.py", line 65, in main
    args.func(args)
  File "/Users/neha5486/git/allennlp/allennlp/commands/train.py", line 99, in train_model_from_args
    args.recover)
  File "/Users/neha5486/git/allennlp/allennlp/commands/train.py", line 129, in train_model_from_file
    return train_model(params, serialization_dir, file_friendly_logging, recover)
  File "/Users/neha5486/git/allennlp/allennlp/commands/train.py", line 291, in train_model
    metrics = trainer.train()
  File "/Users/neha5486/git/allennlp/allennlp/training/trainer.py", line 666, in train
    train_metrics = self._train_epoch(epoch)
  File "/Users/neha5486/git/allennlp/allennlp/training/trainer.py", line 434, in _train_epoch
    loss = self._batch_loss(batch, for_training=True)
  File "/Users/neha5486/git/allennlp/allennlp/training/trainer.py", line 371, in _batch_loss
    output_dict = self._model(**batch)
  File "/Users/neha5486/my-vitual-env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/neha5486/git/allennlp/allennlp/models/coreference_resolution/coref.py", line 228, in forward
    valid_antecedent_indices)
  File "/Users/neha5486/git/allennlp/allennlp/nn/util.py", line 831, in flattened_index_select
    flattened_selected = target.index_select(1, indices.view(-1))
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58

**Comment by schmmd** [comment]
@negacy I think the issue is just that you need a GPU with more memory.  What GPU are you using?
