### ISSUE TITLE
Error when running ELMo in multiprocessing

### ISSUE THREAD

**Issue by EastonWang** [allenai/allennlp#1242]
I'm trying to get the ELMo embeddings in parallel with training the other model and I follow the official [instructions](https://pytorch.org/docs/master/notes/multiprocessing.html) to set up the pytorch multiprocessing. Here is an example code:

```
import torch.multiprocessing as mp
from allennlp.commands.elmo import ElmoEmbedder

try:
    mp.set_start_method('spawn')
except RuntimeError:
    pass

sentences = [['First', 'sentence', '.'], ['Another', '.']]

def worker(elmo, sents):
    print(elmo.batch_to_embeddings(sents))

elmo = ElmoEmbedder(cuda_device=0)
elmo.elmo_bilm.share_memory()

worker(elmo, sentences)  # this works well

jobs = [mp.Process(target=worker, args=(elmo, sentences))]  # this reports error

for j in jobs:
    j.start()
for j in jobs:
    j.join()
```

Running the `elmo.batch_to_embeddings()` in the same process works fine, but when I tried to use multiprocessing, an error occurs. Here is the error message:

```
THCudaCheck FAIL file=torch/csrc/cuda/Module.cpp line=107 error=3 : initialization error
Process Process-1:
Traceback (most recent call last):
  File "/home/nyang/anaconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/nyang/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "test.py", line 12, in worker
    print(elmo.batch_to_embeddings(sents))
  File "/home/nyang/yizhong/venv/lib/python3.6/site-packages/allennlp/commands/elmo.py", line 171, in batch_to_embeddings
    character_ids = character_ids.cuda(device=self.cuda_device)
  File "/home/nyang/yizhong/venv/lib/python3.6/site-packages/torch/autograd/variable.py", line 298, in cuda
    return CudaTransfer.apply(self, device, async)
  File "/home/nyang/yizhong/venv/lib/python3.6/site-packages/torch/autograd/_functions/tensor.py", line 199, in forward
    return i.cuda(device, async=async)
  File "/home/nyang/yizhong/venv/lib/python3.6/site-packages/torch/_utils.py", line 61, in _cuda
    with torch.cuda.device(device):
  File "/home/nyang/yizhong/venv/lib/python3.6/site-packages/torch/cuda/__init__.py", line 207, in __enter__
    self.prev_idx = torch._C._cuda_getDevice()
RuntimeError: cuda runtime error (3) : initialization error at torch/csrc/cuda/Module.cpp:107
```

I tried for a while but still could not work it out. Can you show me any reasons for this error? Or is there any other method to do this?

**Comment by matt-peters** [comment]
I haven't tried to use multiprocessing with ELMo so unfortunately won't be of much help here.  Looking at your code, I'm guessing the error is raise because the `ElmoEmbedder ` class is initialized in the first process and doesn't get moved over to the forked process properly.  This might be due to the fact that `ElmoEmbedder` isn't a subclass of `torch.nn.Module` -- does this work if you use the `Elmo` class instead: https://github.com/allenai/allennlp/blob/master/allennlp/modules/elmo.py#L31 ? 

An alternate strategy you could try is to remove the multiprocessing component and just use separate devices for the `Elmo` class and the rest of your model.  Something like:

```
from allennlp.modules.elmo import Elmo

elmo = Elmo(...)
elmo.cuda(device=1)

model = Model(...)
model.cuda(device=0)

.....

```

This may or may not work, I haven't tried it.
