### ISSUE TITLE
When will pytorch=0.4 be supported?

### ISSUE THREAD

**Issue by Shuailong** [allenai/allennlp#1292]
When I use pytorch 0.4.0, the error message is 

```
(allennlp) ➜  ~ python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch; torch.__version__
'0.4.0'
>>> import allennlp; allennlp.__version__
'0.4.2'
>>> from allennlp.modules.elmo import Elmo
/home/lsl/miniconda3/envs/allennlp/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
>>> options_file = "https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x4096_512_2048cnn_2xhighway/elmo_2x4096_512_2048cnn_2xhighway_options.json"
>>> weight_file = "https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x4096_512_2048cnn_2xhighway/elmo_2x4096_512_2048cnn_2xhighway_weights.hdf5"
>>> elmo = Elmo(options_file, weight_file, 2, dropout=0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lsl/miniconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/modules/elmo.py", line 82, in __init__
    self._elmo_lstm = _ElmoBiLm(options_file, weight_file, requires_grad=requires_grad)
  File "/home/lsl/miniconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/modules/elmo.py", line 433, in __init__
    requires_grad=requires_grad)
  File "/home/lsl/miniconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/modules/elmo_lstm.py", line 86, in __init__
    state_projection_clip_value)
  File "/home/lsl/miniconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/modules/lstm_cell_with_projection.py", line 82, in __init__
    self.reset_parameters()
  File "/home/lsl/miniconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/modules/lstm_cell_with_projection.py", line 86, in reset_parameters
    block_orthogonal(self.input_linearity.weight.data, [self.cell_size, self.input_size])
  File "/home/lsl/miniconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/nn/initializers.py", line 133, in block_orthogonal
    block_orthogonal(tensor.data, split_sizes, gain)
  File "/home/lsl/miniconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/nn/initializers.py", line 133, in block_orthogonal
    block_orthogonal(tensor.data, split_sizes, gain)
  File "/home/lsl/miniconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/nn/initializers.py", line 133, in block_orthogonal
    block_orthogonal(tensor.data, split_sizes, gain)
  [Previous line repeated 974 more times]
  File "/home/lsl/miniconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/nn/initializers.py", line 132, in block_orthogonal
    if isinstance(tensor, Variable):
RecursionError: maximum recursion depth exceeded
```

**Comment by matt-gardner** [comment]
The plan is to merge #1126 next week.

**Comment by schmmd** [comment]
@Shuailong it's now supported on master.  We will have a release soon.

**Comment by schmmd** [comment]
@Shuailong this is merged into master, and we plan to have a release next week.
