### ISSUE TITLE
Simple server is broken

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp#1316]
```
/Users/michael/miniconda3/envs/allennlp/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/Users/michael/miniconda3/envs/allennlp/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/michael/miniconda3/envs/allennlp/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/michael/hack/allenai/allennlp/allennlp/service/server_simple.py", line 716, in <module>
    main(sys.argv[1:])
  File "/Users/michael/hack/allenai/allennlp/allennlp/service/server_simple.py", line 140, in main
    archive = load_archive(args.archive_path or 'tests/fixtures/bidaf/serialization/model.tar.gz')
  File "/Users/michael/hack/allenai/allennlp/allennlp/models/archival.py", line 106, in load_archive
    archive_file = cached_path(archive_file)
  File "/Users/michael/hack/allenai/allennlp/allennlp/common/file_utils.py", line 86, in cached_path
    raise FileNotFoundError("file {} not found".format(url_or_filename))
FileNotFoundError: file tests/fixtures/bidaf/serialization/model.tar.gz not found
```

I think https://github.com/allenai/allennlp/pull/1232 is the culprit.

**Comment by joelgrus** [comment]
the reality is that it probably shouldn't do anything if you run it without arguments

**Comment by schmmd** [comment]
@joelgrus but from the error message--it looks like it used to.  Are you suggesting that we make some of the argument required?

**Comment by joelgrus** [comment]
yes, it had some default behavior so that it would do something if you just ran it without any args, but I'm saying that I now think that was a bad idea
