### ISSUE TITLE
Training Issue: AttributeError: 'function' object has no attribute 'Variable'

### ISSUE THREAD

**Issue by dhairyadalal** [allenai/allennlp#1371]
Running pytorch 0.4.0. and installed allennlp via pip.

I'm training the allennlp model using the default bidaf train file in your training_config folder. 

Get the following error at the start of training:
```
2018-06-13 18:17:11,946 - INFO - allennlp.training.trainer - GPU 1 memory usage MB: 740
  0%|          | 0/2190 [00:00<?, ?it/s]2018-06-13 18:17:11,947 - INFO - allennlp.training.trainer - Training
/home/dhairya/.conda/envs/nlp/lib/python3.6/site-packages/allennlp/modules/encoder_base.py:93: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  num_valid = torch.sum(mask[:, 0]).int().data[0]
start_acc: 0.0573, end_acc: 0.0616, span_acc: 0.0217, em: 0.0230, f1: 0.0850, loss: 8.5062 ||:   5%|4         | 99/2190 [02:26<51:28,  1.48s/it]Traceback (most recent call last):
  File "/home/dhairya/.conda/envs/nlp/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/dhairya/.conda/envs/nlp/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dhairya/.conda/envs/nlp/lib/python3.6/site-packages/allennlp/run.py", line 18, in <module>
    main(prog="allennlp")
  File "/home/dhairya/.conda/envs/nlp/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 65, in main
    args.func(args)
  File "/home/dhairya/.conda/envs/nlp/lib/python3.6/site-packages/allennlp/commands/train.py", line 101, in train_model_from_args
    args.recover)
  File "/home/dhairya/.conda/envs/nlp/lib/python3.6/site-packages/allennlp/commands/train.py", line 131, in train_model_from_file
    return train_model(params, serialization_dir, file_friendly_logging, recover)
  File "/home/dhairya/.conda/envs/nlp/lib/python3.6/site-packages/allennlp/commands/train.py", line 296, in train_model
    metrics = trainer.train()
  File "/home/dhairya/.conda/envs/nlp/lib/python3.6/site-packages/allennlp/training/trainer.py", line 666, in train
    train_metrics = self._train_epoch(epoch)
  File "/home/dhairya/.conda/envs/nlp/lib/python3.6/site-packages/allennlp/training/trainer.py", line 489, in _train_epoch
    self._parameter_and_gradient_statistics_to_tensorboard(batch_num_total, batch_grad_norm)
  File "/home/dhairya/.conda/envs/nlp/lib/python3.6/site-packages/allennlp/training/trainer.py", line 532, in _parameter_and_gradient_statistics_to_tensorboard
    epoch)
  File "/home/dhairya/.conda/envs/nlp/lib/python3.6/site-packages/allennlp/training/trainer.py", line 116, in add_train_scalar
    self._train_log.add_scalar(name, value, global_step)
  File "/home/dhairya/.conda/envs/nlp/lib/python3.6/site-packages/tensorboardX/writer.py", line 272, in add_scalar
    self.file_writer.add_summary(scalar(tag, scalar_value), global_step)
  File "/home/dhairya/.conda/envs/nlp/lib/python3.6/site-packages/tensorboardX/summary.py", line 86, in scalar
    scalar = makenp(scalar)
  File "/home/dhairya/.conda/envs/nlp/lib/python3.6/site-packages/tensorboardX/x2num.py", line 15, in makenp
    return pytorch_np(x, modality)
  File "/home/dhairya/.conda/envs/nlp/lib/python3.6/site-packages/tensorboardX/x2num.py", line 24, in pytorch_np
    if isinstance(x, torch.autograd.variable.Variable):
AttributeError: 'function' object has no attribute 'Variable'
```
Apparently in 0.4, the classes Tensor and Variable got merged. Is there something I need to change on my end. Just using the squad DataReader and default train file to test out what training looks like.

**Comment by nelson-liu** [comment]
I think you also need to upgrade TensorboardX / the other dependencies of allennlp.

**Comment by dhairyadalal** [comment]
This can be closed. 
It looks there was another ticket with a similar issue. Apologies for not searching before posting.  I forced an update with 
       pip install -U allennlp 
which upgraded the tensorboard to 1.2x. Looks like it up and running now.

Also a heads up the it looks like the update doesn't install numpydocs, which caused the train to break. I think the package requirements need to be updated to include it.

**Comment by nelson-liu** [comment]
sorry, can you give the numpydocs traceback as well? that's a bit unusual.

**Comment by joelgrus** [comment]
it's not unusual, it's my fault, I'll need to cut a new release
