### ISSUE TITLE
Import error for allennlp when running allennlp

### ISSUE THREAD

**Issue by dileepmatha** [allenai/allennlp#1398]
Traceback (most recent call last):                                                                                                                     File "/home/dileep/anaconda3/envs/allennlp/lib/python3.6/runpy.py", line 183, in _run_module_as_main                                                   mod_name, mod_spec, code = _get_module_details(mod_name, _Error)                                                                                   File "/home/dileep/anaconda3/envs/allennlp/lib/python3.6/runpy.py", line 109, in _get_module_details                                                   __import__(pkg_name)                                                                                                                               File "/home/dileep/.local/lib/python3.6/site-packages/allennlp/__init__.py", line 11, in <module>                                                      import spacy, torch, numpy  # pylint: disable=multiple-imports                                                                                     File "/home/dileep/.local/lib/python3.6/site-packages/spacy/__init__.py", line 4, in <module>                                                          from .cli.info import info as cli_info                                                                                                             File "/home/dileep/.local/lib/python3.6/site-packages/spacy/cli/__init__.py", line 1, in <module>                                                      from .download import download                                                                                                                     File "/home/dileep/.local/lib/python3.6/site-packages/spacy/cli/download.py", line 10, in <module>                                                     from .link import link                                                                                                                             File "/home/dileep/.local/lib/python3.6/site-packages/spacy/cli/link.py", line 8, in <module>                                                          from ..compat import symlink_to, path2str                                                                                                          File "/home/dileep/.local/lib/python3.6/site-packages/spacy/compat.py", line 9, in <module>                                                            from thinc.neural.util import copy_array                                                                                                           File "/home/dileep/.local/lib/python3.6/site-packages/thinc/neural/__init__.py", line 1, in <module>                                                   from ._classes.model import Model                                                                                                                  File "/home/dileep/.local/lib/python3.6/site-packages/thinc/neural/_classes/model.py", line 12, in <module>                                            from ..train import Trainer                                                                                                                        File "/home/dileep/.local/lib/python3.6/site-packages/thinc/neural/train.py", line 3, in <module>                                                      from .optimizers import Adam, SGD, linear_decay                                                                                                  ImportError: /home/dileep/.local/lib/python3.6/site-packages/thinc/neural/optimizers.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyFPE_jbuf 
**System (please complete the following information):**
 - OS: ubuntu16.04
 - Python version:3.6.5
 - AllenNLP version: 0.5.1
 - PyTorch version: 0.4
**Additional context**

**Comment by dileepmatha** [comment]
still getting the error when importing allennlp

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~/.local/lib/python3.6/site-packages/spacy/compat.py in <module>()
     31 try:
---> 32     from thinc.neural.optimizers import Optimizer
     33 except ImportError:

~/.local/lib/python3.6/site-packages/thinc/neural/__init__.py in <module>()
----> 1 from ._classes.model import Model

~/.local/lib/python3.6/site-packages/thinc/neural/_classes/model.py in <module>()
     11 from .. import util
---> 12 from ..train import Trainer
     13 from ..ops import NumpyOps, CupyOps

~/.local/lib/python3.6/site-packages/thinc/neural/train.py in <module>()
      2 
----> 3 from .optimizers import Adam, SGD, linear_decay
      4 from .util import minibatch

ImportError: /home/dileep/.local/lib/python3.6/site-packages/thinc/neural/optimizers.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyFPE_jbuf

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-4-406e009db549> in <module>()
----> 1 import allennlp

~/.local/lib/python3.6/site-packages/allennlp/__init__.py in <module>()
      9     # On some systems this prevents the dreaded
     10     # ImportError: dlopen: cannot load any more object with static TLS
---> 11     import spacy, torch, numpy  # pylint: disable=multiple-imports
     12 
     13 except ModuleNotFoundError:

~/.local/lib/python3.6/site-packages/spacy/__init__.py in <module>()
      2 from __future__ import unicode_literals
      3 
----> 4 from .cli.info import info as cli_info
      5 from .glossary import explain
      6 from .about import __version__

~/.local/lib/python3.6/site-packages/spacy/cli/__init__.py in <module>()
----> 1 from .download import download
      2 from .info import info
      3 from .link import link
      4 from .package import package
      5 from .profile import profile

~/.local/lib/python3.6/site-packages/spacy/cli/download.py in <module>()
      8 import ujson
      9 
---> 10 from .link import link
     11 from ._messages import Messages
     12 from ..util import prints, get_package_path

~/.local/lib/python3.6/site-packages/spacy/cli/link.py in <module>()
      6 
      7 from ._messages import Messages
----> 8 from ..compat import symlink_to, path2str
      9 from ..util import prints
     10 from .. import util

~/.local/lib/python3.6/site-packages/spacy/compat.py in <module>()
     32     from thinc.neural.optimizers import Optimizer
     33 except ImportError:
---> 34     from thinc.neural.optimizers import Adam as Optimizer
     35 
     36 try:

~/.local/lib/python3.6/site-packages/thinc/neural/__init__.py in <module>()
----> 1 from ._classes.model import Model

~/.local/lib/python3.6/site-packages/thinc/neural/_classes/model.py in <module>()
     10 
     11 from .. import util
---> 12 from ..train import Trainer
     13 from ..ops import NumpyOps, CupyOps
     14 from ..mem import Memory

~/.local/lib/python3.6/site-packages/thinc/neural/train.py in <module>()
      1 from __future__ import unicode_literals, print_function
      2 
----> 3 from .optimizers import Adam, SGD, linear_decay
      4 from .util import minibatch
      5 

ImportError: /home/dileep/.local/lib/python3.6/site-packages/thinc/neural/optimizers.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyFPE_jbuf

**Comment by dileepmatha** [comment]
Still getting the error, When importing allennlp and spacy

ImportError Traceback (most recent call last)
~/.local/lib/python3.6/site-packages/spacy/compat.py in ()
31 try:
---> 32 from thinc.neural.optimizers import Optimizer
33 except ImportError:

~/.local/lib/python3.6/site-packages/thinc/neural/*init*.py in ()
----> 1 from ._classes.model import Model

~/.local/lib/python3.6/site-packages/thinc/neural/_classes/model.py in ()
11 from .. import util
---> 12 from ..train import Trainer
13 from ..ops import NumpyOps, CupyOps

~/.local/lib/python3.6/site-packages/thinc/neural/train.py in ()
2
----> 3 from .optimizers import Adam, SGD, linear_decay
4 from .util import minibatch

ImportError: /home/dileep/.local/lib/python3.6/site-packages/thinc/neural/
optimizers.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyFPE_jbuf

During handling of the above exception, another exception occurred:

ImportError Traceback (most recent call last)
in ()
----> 1 import allennlp

~/.local/lib/python3.6/site-packages/allennlp/*init*.py in ()
9 # On some systems this prevents the dreaded
10 # ImportError: dlopen: cannot load any more object with static TLS
---> 11 import spacy, torch, numpy # pylint: disable=multiple-imports
12
13 except ModuleNotFoundError:

~/.local/lib/python3.6/site-packages/spacy/*init*.py in ()
2 from *future* import unicode_literals
3
----> 4 from .cli.info import info as cli_info
5 from .glossary import explain
6 from .about import *version*

~/.local/lib/python3.6/site-packages/spacy/cli/*init*.py in ()
----> 1 from .download import download
2 from .info import info
3 from .link import link
4 from .package import package
5 from .profile import profile

~/.local/lib/python3.6/site-packages/spacy/cli/download.py in ()
8 import ujson
9
---> 10 from .link import link
11 from ._messages import Messages
12 from ..util import prints, get_package_path

~/.local/lib/python3.6/site-packages/spacy/cli/link.py in ()
6
7 from ._messages import Messages
----> 8 from ..compat import symlink_to, path2str
9 from ..util import prints
10 from .. import util

~/.local/lib/python3.6/site-packages/spacy/compat.py in ()
32 from thinc.neural.optimizers import Optimizer
33 except ImportError:
---> 34 from thinc.neural.optimizers import Adam as Optimizer
35
36 try:

~/.local/lib/python3.6/site-packages/thinc/neural/*init*.py in ()
----> 1 from ._classes.model import Model

~/.local/lib/python3.6/site-packages/thinc/neural/_classes/model.py in ()
10
11 from .. import util
---> 12 from ..train import Trainer
13 from ..ops import NumpyOps, CupyOps
14 from ..mem import Memory

~/.local/lib/python3.6/site-packages/thinc/neural/train.py in ()
1 from *future* import unicode_literals, print_function
2
----> 3 from .optimizers import Adam, SGD, linear_decay
4 from .util import minibatch
5

ImportError: /home/dileep/.local/lib/python3.6/site-packages/thinc/neural/
optimizers.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyFPE_jbuf

**Comment by nelson-liu** [comment]
pretty hard to debug without information about how specifically you set up allennlp. is it possible that you might have multiple python installations conflicting on the machine?

**Comment by dileepmatha** [comment]
anaconda

**Comment by dileepmatha** [comment]
I have done using  anaconda 

using this as the reference 

https://github.com/allenai/allennlp

**Comment by dileepmatha** [comment]
I have done using anaconda

using this as the reference

https://github.com/allenai/allennlp

**Comment by DeNeutoy** [comment]
Please re-open if you have more specific information.
