### ISSUE TITLE
Errors when training a coref model with allennlp

### ISSUE THREAD

**Issue by JieyuZhao** [allenai/allennlp#1461]
Hi,

I tried to train a coref model with allennlp. I have modified the training_config file to set the training/dev/test path. But I got some errors when the model starts to train. It said something is wrong with the "**reduce_on_plateau learning rate scheduler**". I have configured the validation_path to "data/dev.english.v4_gold_conll" and in the config file, the validation metric is  also set to "+coref_f1". The command I used to train the coref model is " allennlp train training_config/coref.json -s coref".

The error log is as following:
/net/zf2/jz4fu/Github/allennlp/allennlp/modules/token_embedders/embedding.py:91: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  torch.nn.init.xavier_uniform(self.weight.data)
/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/rnn.py:38: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.2 and num_layers=1
  "num_layers={}".format(dropout, num_layers))
/net/zf2/jz4fu/Github/allennlp/allennlp/nn/initializers.py:162: UserWarning: nn.init.xavier_normal is now deprecated in favor of nn.init.xavier_normal_.
  self._init_function(tensor, **self._kwargs)
/net/zf2/jz4fu/Github/allennlp/allennlp/nn/initializers.py:162: UserWarning: nn.init.orthogonal is now deprecated in favor of nn.init.orthogonal_.
  self._init_function(tensor, **self._kwargs)
  0%|          | 0/2802 [00:00<?, ?it/s]
/net/zf2/jz4fu/Github/allennlp/allennlp/modules/encoder_base.py:93: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  num_valid = torch.sum(mask[:, 0]).int().data[0]
Traceback (most recent call last):
  File "/zf2/jz4fu/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/zf2/jz4fu/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/net/zf2/jz4fu/Github/allennlp/allennlp/run.py", line 18, in <module>
    main(prog="python -m allennlp.run")
  File "/net/zf2/jz4fu/Github/allennlp/allennlp/commands/__init__.py", line 65, in main
    args.func(args)
  File "/net/zf2/jz4fu/Github/allennlp/allennlp/commands/train.py", line 99, in train_model_from_args
    args.recover)
  File "/net/zf2/jz4fu/Github/allennlp/allennlp/commands/train.py", line 129, in train_model_from_file
    return train_model(params, serialization_dir, file_friendly_logging, recover)
  File "/net/zf2/jz4fu/Github/allennlp/allennlp/commands/train.py", line 291, in train_model
    metrics = trainer.train()
  File "/net/zf2/jz4fu/Github/allennlp/allennlp/training/trainer.py", line 671, in train
    train_metrics = self._train_epoch(epoch)
  File "/net/zf2/jz4fu/Github/allennlp/allennlp/training/trainer.py", line 459, in _train_epoch
    self._update_learning_rate(None, batch_num_total=batch_num_total)
  File "/net/zf2/jz4fu/Github/allennlp/allennlp/training/trainer.py", line 609, in _update_learning_rate
    self._learning_rate_scheduler.step(val_metric, epoch)
  File "/net/zf2/jz4fu/Github/allennlp/allennlp/training/learning_rate_schedulers.py", line 74, in step
    raise ConfigurationError("The reduce_on_plateau learning rate scheduler requires "
allennlp.common.checks.ConfigurationError: 'The reduce_on_plateau learning rate scheduler requires a validation metric to compute the schedule and therefore must be used with a validation dataset.'

**Comment by JieyuZhao** [comment]
@DeNeutoy  Hi, it is allennlp 0.5.1.

**Comment by DeNeutoy** [comment]
Right - I think we've already fixed this. Do you mind trying the master branch?

**Comment by JieyuZhao** [comment]
Thanks! It helped.
