### ISSUE TITLE
Predict error "AttributeError: 'tuple' object has no attribute 'fields'"

### ISSUE THREAD

**Issue by handsomezebra** [allenai/allennlp#1467]
Using latest master allennlp, when I run the following predict command in allennlp-as-a-library-example, and got error as below.
```
allennlp predict \
    tests/fixtures/model.tar.gz \
    tests/fixtures/s2_papers.jsonl \
    --include-package my_library \
    --predictor paper-classifier
```
```
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/allennlp/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/user/anaconda3/envs/allennlp/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/run.py", line 18, in <module>
    main(prog="allennlp")
  File "/home/user/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 70, in main
    args.func(args)
  File "/home/user/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/predict.py", line 192, in _predict
    manager.run()
  File "/home/user/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/predict.py", line 172, in run
    for model_input, result in zip(batch_json, self._predict_json(batch_json)):
  File "/home/user/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/predict.py", line 129, in _predict_json
    results = [self._predictor.predict_json(batch_data[0])]
  File "/home/user/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/predictors/predictor.py", line 48, in predict_json
    return self.predict_instance(instance)
  File "/home/user/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/predictors/predictor.py", line 51, in predict_instance
    outputs = self._model.forward_on_instance(instance)
  File "/home/user/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/models/model.py", line 124, in forward_on_instance
    return self.forward_on_instances([instance])[0]
  File "/home/user/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/models/model.py", line 152, in forward_on_instances
    dataset = Batch(instances)
  File "/home/user/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/data/dataset.py", line 32, in __init__
    self._check_types()
  File "/home/user/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/data/dataset.py", line 40, in _check_types
    for x in self.instances]
  File "/home/user/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/data/dataset.py", line 40, in <listcomp>
    for x in self.instances]
AttributeError: 'tuple' object has no attribute 'fields'
```

**Comment by DeNeutoy** [comment]
Hi, the `allennlp-as-a-library` example code does not use the allennlp master branch. If you follow the instructions in the repo, https://github.com/allenai/allennlp-as-a-library-example/blob/master/requirements.txt you should have no issues. Let us know if not!

**Comment by handsomezebra** [comment]
But the problem is I am following this example (also same as the tutorial https://github.com/allenai/allennlp/blob/master/tutorials/getting_started/using_as_a_library_pt2.md) to write my own predictor and also getting this error. Is there any guide on how to write predictor in the new master code?

**Comment by handsomezebra** [comment]
Looks like there are some changes in the predictor API. I will check the changes and try to fix it on my side. I suggest that the tutorials and the allennlp-as-a-library can also be updated to reflect those changes. Thanks! @DeNeutoy

**Comment by muni2773** [comment]
@handsomezebra did you get this to work with Master ?

**Comment by handsomezebra** [comment]
@muni2773 Yes, just simply change the API from `def _json_to_instance(self, json_dict: JsonDict) -> Tuple[Instance, JsonDict]:` to `def _json_to_instance(self, json_dict: JsonDict) -> Instance:` and make some change to the code to only return the instance.

**Comment by muni2773** [comment]
@handsomezebra Thanks .. can you share your changes to the following

class PaperClassifierPredictor(Predictor):
    """"Predictor wrapper for the AcademicPaperClassifier"""
    @overrides
    def _json_to_instance(self, json_dict: JsonDict) -> Tuple[Instance, JsonDict]:
        title = json_dict['title']
        abstract = json_dict['paperAbstract']
        instance = self._dataset_reader.text_to_instance(title=title, abstract=abstract)

        # label_dict will be like {0: "ACL", 1: "AI", ...}
        label_dict = self._model.vocab.get_index_to_token_vocabulary('labels')
        # Convert it to list ["ACL", "AI", ...]
        all_labels = [label_dict[i] for i in range(len(label_dict))]

        return instance, {"all_labels": all_labels}

**Comment by muni2773** [comment]
actually got it .. 

def _json_to_instance(self, json_dict: JsonDict) -> Instance:
        title = json_dict['title']
        abstract = json_dict['paperAbstract']
        instance = self._dataset_reader.text_to_instance(title=title, abstract=abstract)

        # label_dict will be like {0: "ACL", 1: "AI", ...}
        label_dict = self._model.vocab.get_index_to_token_vocabulary('labels')
        # Convert it to list ["ACL", "AI", ...]
        all_labels = [label_dict[i] for i in range(len(label_dict))]

        return instance

**Comment by handsomezebra** [comment]
Yes, correct. Just noticed that with the most recent master, you also need to remove the two from_params functions to make all unit tests pass.
