### ISSUE TITLE
pyparsing error when training allennlp coref with ELMo

### ISSUE THREAD

**Issue by JieyuZhao** [allenai/allennlp#1468]
Hi, 
I am trying to train a coreference model with ELMo, but I got a **pyparsing.ParseSyntaxException**.  I use pytorch-0.4.0 and allennlp-0.5.0. Thank you!

pyparsing.ParseException: Expected {Forward: ... | {{"=" | ":" | "+="} - [Suppress:({{{"#" | "//"} - SkipTo:({Suppress:(W:(
)) | StringEnd})} | Suppress:(W:(
))})]... - ConcatenatedValueParser:([{Suppress:({[Suppress:(W:(
,))] {"#" | "//"} - SkipTo:({Suppress:(W:(
)) | StringEnd})}) | {Suppress:("include") {Re:('".*?"[ \t]*') | {{"url" | "file"} - Suppress:("(") - Re:('".*?"[ \t]*') - Suppress:(")")}}} | Re:('[ \t]*\\$\\{[^\\}]+\\}[ \t]*') | Forward: ... | Forward: ... | Re:('[+-]?(\\d*\\.\\d+|\\d+(\\.\\d+)?)([eE]\\d+)?(?=$|[ \t]*([\\$\\}\\],#\n\r]|//))') | "true" | "false" | "null" | Re:('""".*?"""') | Re:('".*?"[ \t]*') | Re:('(?:\\\\|[^\\[\\{\\s\\]\\}#,=\\$])+[ \t]*') | Suppress:({"\" - Suppress:(W:(
))})}]...)}} (at char 2932), (line:97, col:24)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/zf2/jz4fu/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/zf2/jz4fu/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/net/zf2/jz4fu/Github/allennlp/allennlp/run.py", line 18, in <module>
    main(prog="python -m allennlp.run")
  File "/net/zf2/jz4fu/Github/allennlp/allennlp/commands/__init__.py", line 65, in main
    args.func(args)
  File "/net/zf2/jz4fu/Github/allennlp/allennlp/commands/train.py", line 99, in train_model_from_args
    args.recover)
  File "/net/zf2/jz4fu/Github/allennlp/allennlp/commands/train.py", line 128, in train_model_from_file
    params = Params.from_file(parameter_filename, overrides)
  File "/net/zf2/jz4fu/Github/allennlp/allennlp/common/params.py", line 285, in from_file
    file_dict = pyhocon.ConfigFactory.parse_file(params_file)
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyhocon/config_parser.py", line 51, in parse_file
    return ConfigFactory.parse_string(content, os.path.dirname(filename), resolve)
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyhocon/config_parser.py", line 90, in parse_string
    return ConfigParser().parse(content, basedir, resolve)
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyhocon/config_parser.py", line 272, in parse
    config = config_expr.parseString(content, parseAll=True)[0]
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1632, in parseString
    raise exc
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1622, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 3395, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 3530, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 3717, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 3386, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 3717, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 3919, in parseImpl
    return super(ZeroOrMore, self).parseImpl(instring, loc, doActions)
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 3858, in parseImpl
    loc, tmptokens = self_expr_parse( instring, preloc, doActions )
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 3530, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 3717, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 3717, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 3386, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 3530, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 3386, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 3717, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 3919, in parseImpl
    return super(ZeroOrMore, self).parseImpl(instring, loc, doActions)
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 3848, in parseImpl
    loc, tokens = self_expr_parse( instring, loc, doActions, callPreParse=False )
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 3530, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 3717, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 3386, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 3717, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 3919, in parseImpl
    return super(ZeroOrMore, self).parseImpl(instring, loc, doActions)
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 3858, in parseImpl
    loc, tmptokens = self_expr_parse( instring, preloc, doActions )
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 3530, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 3717, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 3717, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/zf2/jz4fu/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 3391, in parseImpl
    raise ParseSyntaxException._from_exception(pe)
pyparsing.ParseSyntaxException: Expected {Forward: ... | {{"=" | ":" | "+="} - [Suppress:({{{"#" | "//"} - SkipTo:({Suppress:(W:(
)) | StringEnd})} | Suppress:(W:(
))})]... - ConcatenatedValueParser:([{Suppress:({[Suppress:(W:(
,))] {"#" | "//"} - SkipTo:({Suppress:(W:(
)) | StringEnd})}) | {Suppress:("include") {Re:('".*?"[ \t]*') | {{"url" | "file"} - Suppress:("(") - Re:('".*?"[ \t]*') - Suppress:(")")}}} | Re:('[ \t]*\\$\\{[^\\}]+\\}[ \t]*') | Forward: ... | Forward: ... | Re:('[+-]?(\\d*\\.\\d+|\\d+(\\.\\d+)?)([eE]\\d+)?(?=$|[ \t]*([\\$\\}\\],#\n\r]|//))') | "true" | "false" | "null" | Re:('""".*?"""') | Re:('".*?"[ \t]*') | Re:('(?:\\\\|[^\\[\\{\\s\\]\\}#,=\\$])+[ \t]*') | Suppress:({"\" - Suppress:(W:(
))})}]...)}} (at char 2932), (line:97, col:24)

**Comment by matt-gardner** [comment]
@JieyuZhao, this error is happening when `pyhocon` is trying to read your configuration file.  You have some invalid syntax in your file, apparently.  Can you include the full text of your config file?
