### ISSUE TITLE
key "args" is required at location "dataset_reader.tokenizer.word_splitter."

### ISSUE THREAD

**Issue by handsomezebra** [allenai/allennlp#1480]
**Describe the bug**
Using the latest master code, one of my models generate the following error.
```
Traceback (most recent call last):
  File "train.py", line 32, in <module>
    main()
  File "/home/user/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 70, in main
    args.func(args)
  File "/home/user/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/train.py", line 103, in train_model_from_args
    args.recover)
  File "/home/user/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/train.py", line 133, in train_model_from_file
    return train_model(params, serialization_dir, file_friendly_logging, recover)
  File "/home/user/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/train.py", line 264, in train_model
    all_datasets = datasets_from_params(params)
  File "/home/user/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/train.py", line 140, in datasets_from_params
    dataset_reader = DatasetReader.from_params(params.pop('dataset_reader'))
  File "/home/user/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/common/from_params.py", line 246, in from_params
    return subclass.from_params(params=params, **extras)
  File "/home/user/dev/my_library/dataset_readers/quora_paraphrase.py", line 95, in from_params
    tokenizer = Tokenizer.from_params(params.pop('tokenizer', {}))
  File "/home/user/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/common/from_params.py", line 246, in from_params
    return subclass.from_params(params=params, **extras)
  File "/home/user/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/common/from_params.py", line 249, in from_params
    kwargs = create_kwargs(cls, params, **extras)
  File "/home/user/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/common/from_params.py", line 148, in create_kwargs
    kwargs[name] = annotation.from_params(params=subparams, **subextras)
  File "/home/user/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/common/from_params.py", line 246, in from_params
    return subclass.from_params(params=params, **extras)
  File "/home/user/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/common/from_params.py", line 249, in from_params
    kwargs = create_kwargs(cls, params, **extras)
  File "/home/user/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/common/from_params.py", line 191, in create_kwargs
    kwargs[name] = params.pop(name)
  File "/home/user/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/common/params.py", line 160, in pop
    raise ConfigurationError("key \"{}\" is required at location \"{}\"".format(key, self.history))
allennlp.common.checks.ConfigurationError: 'key "args" is required at location "dataset_reader.tokenizer.word_splitter."'
```
The tokenizer is defined as below:
```
    "tokenizer": {
      "type": "word",
      "word_splitter": {
        "type": "just_spaces"
      }
    }
```

**System (please complete the following information):**
 - OS: Linux
 - Python version: 3.6
 - AllenNLP version: Master

**Additional context**
I believe this is related to #1191. Since neither the class JustSpacesWordSplitter or WordSplitter has __init__(), the code got args, kwargs, etc. in the signature.

**Comment by joelgrus** [comment]
yes, that's the cause, let me figure out the right fix.

thanks for finding this
