### ISSUE TITLE
allennlp tool throws locale error under OSX

### ISSUE THREAD

**Issue by DmitryKey** [allenai/allennlp#1518]
**Describe the bug**
allennlp does not start, throwing an error about unknown locale

**To Reproduce**
Steps to reproduce the behavior
1. Install python 3.6.6 with conda
2. run allennlp from command line
3. See error

```
Traceback (most recent call last):
  File "/Users/dmitry/anaconda2/envs/mypython3/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/dmitry/anaconda2/envs/mypython3/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/Users/dmitry/anaconda2/envs/mypython3/lib/python3.6/site-packages/allennlp/__init__.py", line 11, in <module>
    import spacy, torch, numpy  # pylint: disable=multiple-imports
  File "/Users/dmitry/anaconda2/envs/mypython3/lib/python3.6/site-packages/spacy/__init__.py", line 4, in <module>
    from .cli.info import info as cli_info
  File "/Users/dmitry/anaconda2/envs/mypython3/lib/python3.6/site-packages/spacy/cli/__init__.py", line 1, in <module>
    from .download import download
  File "/Users/dmitry/anaconda2/envs/mypython3/lib/python3.6/site-packages/spacy/cli/download.py", line 11, in <module>
    from .link import link
  File "/Users/dmitry/anaconda2/envs/mypython3/lib/python3.6/site-packages/spacy/cli/link.py", line 9, in <module>
    from ..util import prints
  File "/Users/dmitry/anaconda2/envs/mypython3/lib/python3.6/site-packages/spacy/util.py", line 8, in <module>
    import regex as re
  File "/Users/dmitry/anaconda2/envs/mypython3/lib/python3.6/site-packages/regex.py", line 683, in <module>
    _pattern_type = type(_compile("", 0, {}))
  File "/Users/dmitry/anaconda2/envs/mypython3/lib/python3.6/site-packages/regex.py", line 436, in _compile
    pattern_locale = _getlocale()[1]
  File "/Users/dmitry/anaconda2/envs/mypython3/lib/python3.6/locale.py", line 581, in getlocale
    return _parse_localename(localename)
  File "/Users/dmitry/anaconda2/envs/mypython3/lib/python3.6/locale.py", line 490, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8
```

**Expected behavior**
allennlp should run and print its options

**System (please complete the following information):**
 - OS: OSX
 - Python version: 3.6.6
 - AllenNLP version: 0.5.1

**Additional context**

**Comment by DmitryKey** [comment]
After setting the LC_CTYPE to "C", allennlp starts normally:

```
export LC_CTYPE="C"
locale
LANG=
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=

```

**Comment by joelgrus** [comment]
it looks like this is a spacy bug, try their fix:

https://spacy.io/usage/#unknown-locale

**Comment by DmitryKey** [comment]
thanks @joelgrus will check

With the locale change I mentioned above, one test fails:

```
==================================================== FAILURES =====================================================
___________________________ TestElmoTokenRepresentation.test_elmo_token_representation ____________________________

self = <allennlp.tests.modules.elmo_test.TestElmoTokenRepresentation testMethod=test_elmo_token_representation>

    def test_elmo_token_representation(self):
        # Load the test words and convert to char ids
        with open(os.path.join(self.elmo_fixtures_path, 'vocab_test.txt'), 'r') as fin:
>           tokens = fin.read().strip().split('\n')

tests/modules/elmo_test.py:299: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <encodings.ascii.IncrementalDecoder object at 0x1249a97b8>
input = b'good\nWhy\nemployment\ngovernment\nDon\ncare\n;\ncase\nNorth\nBush\nassassinations\nyou\ndisciplined\npress\nromance...s\nYou\nadding\nwill\ncases\nexceptions\nintelligence\ncomment\nbut\nreviewed\nIf\nits\n6X6\n&\nSea\nbig\nan\nfunction'
final = True

    def decode(self, input, final=False):
>       return codecs.ascii_decode(input, self.errors)[0]
E       UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 949: ordinal not in range(128)

../../encodings/ascii.py:26: UnicodeDecodeError
---------------------------------------------- Captured stderr call -----------------------------------------------
2018-07-23 00:14:37,429 - INFO - allennlp.common.checks - Pytorch version: 0.4.0
------------------------------------------------ Captured log call ------------------------------------------------
checks.py                   29 INFO     Pytorch version: 0.4.0
===Flaky Test Report===

test_evaluate_from_args passed 1 out of the required 1 times. Success!
test_batch_predictions_are_consistent passed 1 out of the required 1 times. Success!
test_batch_predictions_are_consistent passed 1 out of the required 1 times. Success!
test_model_can_train_save_and_load passed 1 out of the required 1 times. Success!
test_batch_predictions_are_consistent passed 1 out of the required 1 times. Success!
test_batch_predictions_are_consistent passed 1 out of the required 1 times. Success!
test_batch_predictions_are_consistent passed 1 out of the required 1 times. Success!
test_model_can_train_save_and_load passed 1 out of the required 1 times. Success!
test_elmo_no_features_can_train_save_and_load passed 1 out of the required 1 times. Success!

===End Flaky Test Report===
======================== 1 failed, 735 passed, 6 skipped, 10 deselected in 301.20 seconds =========================
2018-07-23 00:15:14,032 - INFO - allennlp.training.metrics.wikitables_accuracy - Stopped SEMPRE server
```

will keep this open for some time.

**Comment by DmitryKey** [comment]
Utility starts just fine with re-specifying locale as:
```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```

**Comment by DmitryKey** [comment]
```
============================= 736 passed, 6 skipped, 10 deselected in 160.31 seconds ==============================
```

thanks for quick help @joelgrus
