### ISSUE TITLE
Cant execute tutorial after installing allennlp recently

### ISSUE THREAD

**Issue by ghazikhani** [allenai/allennlp#1559]
Hi
I have installed allennlp in conda. About a week ago I executed the train command in the tutorial "Training and Evaluating Models" with no problems.
Today I installed allennlp again (pip install allennlp like before) after executing the same command:

allennlp train tutorials/getting_started/simple_tagger.json --serialization-dir /tmp/tutorials/getting_started

The error part is:
Traceback (most recent call last):
  File "/home/adel/miniconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/common/params.py", line 94, in pop
    value = self.params.pop(key)
KeyError: 'type'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/adel/miniconda3/envs/allennlp/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/adel/miniconda3/envs/allennlp/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/adel/miniconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/run.py", line 18, in <module>
    main(prog="allennlp")
  File "/home/adel/miniconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 70, in main
    args.func(args)
  File "/home/adel/miniconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/train.py", line 101, in train_model_from_args
    args.recover)
  File "/home/adel/miniconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/train.py", line 131, in train_model_from_file
    return train_model(params, serialization_dir, file_friendly_logging, recover)
  File "/home/adel/miniconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/train.py", line 276, in train_model
    model = Model.from_params(vocab, params.pop('model'))
  File "/home/adel/miniconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/models/model.py", line 217, in from_params
    model = cls.by_name(choice).from_params(vocab, params)
  File "/home/adel/miniconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/models/simple_tagger.py", line 145, in from_params
    text_field_embedder = TextFieldEmbedder.from_params(vocab, embedder_params)
  File "/home/adel/miniconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/modules/text_field_embedders/text_field_embedder.py", line 56, in from_params
    return cls.by_name(choice).from_params(vocab, params)
  File "/home/adel/miniconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/modules/text_field_embedders/basic_text_field_embedder.py", line 94, in from_params
    token_embedders[key] = TokenEmbedder.from_params(vocab, embedder_params)
  File "/home/adel/miniconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/modules/token_embedders/token_embedder.py", line 31, in from_params
    choice = params.pop_choice('type', cls.list_available())
  File "/home/adel/miniconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/common/params.py", line 179, in pop_choice
    value = self.pop(key, default)
  File "/home/adel/miniconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/common/params.py", line 96, in pop
    raise ConfigurationError("key \"{}\" is required at location \"{}\"".format(key, self.history))
allennlp.common.checks.ConfigurationError: 'key "type" is required at location "model.text_field_embedder.token_embedders."'

 - OS: Ubuntu 16.04
 - Python version: 3.6
 - AllenNLP version:  v0.5.1

**Comment by ghazikhani** [comment]
The problem was solved the simple_tagger.json file had changed.
This line was added "token_embedders": {
after deleting it I could execute it

**Comment by 646194454** [comment]
many thanks!
