### ISSUE TITLE
registering a new dataset reader didn't work 

### ISSUE THREAD

**Issue by iamyihwa** [allenai/allennlp#1584]
**Describe the bug**

Following the steps in the tutorial ([link](https://github.com/allenai/allennlp/blob/f6d9ba318a643e42bae597fd2b71d336aa290a1f/tutorials/getting_started/using_as_a_library_pt1.md)) didn't quite register the dataset_reader type as was expected. 

![image](https://user-images.githubusercontent.com/12494156/43779262-3aeefb80-9a58-11e8-98d8-a6b0a3580e87.png)

I have made a custon configuration file which was based on the crf_tagger.py , and wrote a custom reader file, however didn't create a separate model but reused crf_tagger model.

Screenshot of the configuration file in json below. 

![image](https://user-images.githubusercontent.com/12494156/43779723-53653bf6-9a59-11e8-821a-0ae923ab2f3a.png)
 

**To Reproduce**

1. Go to
![image](https://user-images.githubusercontent.com/12494156/43779228-213aa9b4-9a58-11e8-97ab-8f909780b704.png)
How I ran the command: 
$ allennlp train crf_es_tagger.json -s tmp/spanish-ner --include-package ner_spanish

: 2018-08-07 13:34:24,461 - INFO - allennlp.common.params - random_seed = 13370
2018-08-07 13:34:24,461 - INFO - allennlp.common.params - numpy_seed = 1337
2018-08-07 13:34:24,461 - INFO - allennlp.common.params - pytorch_seed = 133
2018-08-07 13:34:24,462 - INFO - allennlp.common.checks - Pytorch version: 0.4.0
2018-08-07 13:34:24,464 - INFO - allennlp.common.params - dataset_reader.type = conll2002
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/run.py", line 18, in <module>
    main(prog="allennlp")
  File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 70, in main
    args.func(args)
  File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/train.py", line 101, in train_model_from_args
    args.recover)
  File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/train.py", line 131, in train_model_from_file
    return train_model(params, serialization_dir, file_friendly_logging, recover)
  File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/train.py", line 262, in train_model
    all_datasets = datasets_from_params(params)
  File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/train.py", line 138, in datasets_from_params
    dataset_reader = DatasetReader.from_params(params.pop('dataset_reader'))
  File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/data/dataset_readers/dataset_reader.py", line 112, in from_params
    choice = params.pop_choice('type', cls.list_available())
  File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/common/params.py", line 183, in pop_choice
    raise ConfigurationError(message)
allennlp.common.checks.ConfigurationError: "conll2002 not in acceptable choices for dataset_reader.type: ['conll2003', 'coref', 'winobias', 'language_modeling', 'nlvr', 'ptb_trees', 'squad', 'triviaqa', 'srl', 'seq2seq', 'sequence_tagging', 'snli', 'universal_dependencies', 'sst_tokens', 'wikitables']"

**Expected behavior**
I expected that the crf_tagger model would run. 

**System (please complete the following information):**
 - OS: Ubuntu 
 - Python version: 3.6
 - AllenNLP version: "I installed from master"
 - PyTorch version: (if you installed it yourself)

**Additional context**

**Comment by matt-gardner** [comment]
It looks like you need an `__init.py__` file in the `ner_spanish` directory. Python needs those files to say that a directory is a module.

@joelgrus, if this is in fact the problem, shouldn't we be throwing some kind error about a failed import on the `--include-package` flag?

**Comment by joelgrus** [comment]
I think it's worse that that, I think that `import_submodules` is not always descending into even well-defined submodules, so I don't think Matt's fix will work (let me know if does though).

I think you'll have to either

* import the dataset reader class in `ner_spanish/__init__.py`, or
* change the call to `--include-package ner_spanish.dataset_readers` 

I'll open an issue for this, I think people have run into it before

**Comment by joelgrus** [comment]
and I don't think the error is a "failed import" per se, I think the import "succeeded" but it didn't load the file that was desired

**Comment by iamyihwa** [comment]
Hi @matt-gardner @joelgrus , thanks for quick feedback! 

1.  with regards to giving detailed path: 
I just tried  to 
```allennlp train crf_es_tagger.json -s tmp/spanish-ner --include-package ner_spanish.dataset_readers```
and got different error. 

  File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/run.py", line 18, in <module>
    main(prog="allennlp")
  File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 69, in main
    import_submodules(package_name)
  File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/common/util.py", line 274, in import_submodules
    importlib.import_module(package_name + '.' + name)
  File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/ner-spanish-project/ner_spanish/dataset_readers/conll2002.py", line 10, in <module>
    from allennlp.data.dataset_readers.dataset_utils import to_bioul
ImportError: cannot import name 'to_bioul'

2. I see about __init__.py 
I will have to check what should be the content of this file. 

3. Can I give an existing model in allennlp and custom dataset reader? 
: I guess it is the matter of path, it's just that in the example it was given together, so I wasn't sure..

**Comment by iamyihwa** [comment]
1. Tried with __init__.py  
(allennlp) ubuntu@ip-172-30-1-75:~/ner-spanish-project$ allennlp train crf_es_tagger.json -s tmp/spanish-ner --include-package ner_spanish

However get error also 
![image](https://user-images.githubusercontent.com/12494156/43781059-57d9ef58-9a5c-11e8-9455-718245f6a2d3.png)


2. tried with __init__.py + explicit name of the 

(allennlp) ubuntu@ip-172-30-1-75:~/ner-spanish-project$ allennlp train crf_es_tagger.json -s tmp/spanish-ner --include-package ner_spanish.dataset_readers
![image](https://user-images.githubusercontent.com/12494156/43781126-7d67b3d6-9a5c-11e8-819f-ea52122654b6.png)

same error as above ...

**Comment by joelgrus** [comment]
when did you install from master? that function name was changed about 3 weeks ago:

https://github.com/allenai/allennlp/pull/1497

so my suspicion is that somehow your version of allennlp is older than you think (do you have a pip installed version hanging around in your environment?)

**Comment by iamyihwa** [comment]
I have installed last week. 

I have installed using pip, as instructed in https://github.com/allenai/allennlp . . 
```pip install allennlp```

However I didn't do the step below from 
```pip install -r requirements.txt``` because I thought it was both installing allennlp. 

https://github.com/allenai/allennlp/blob/f6d9ba318a643e42bae597fd2b71d336aa290a1f/tutorials/getting_started/using_as_a_library_pt1.md


Is it not the proper way?

**Comment by joelgrus** [comment]
no, sorry, I got confused by the "installed from master" part.

that means you should be on version 0.5.1, at which point the function was called`iob1_to_bioul`

https://github.com/allenai/allennlp/blob/v0.5.1/allennlp/data/dataset_readers/dataset_utils/__init__.py

so import (and use) it that way.

(we should really do a release)

**Comment by iamyihwa** [comment]
Sorry to confuse you. I did both of them. 
(1) pip install allennlp 
(2) git clone master repository  
However (2) was just for me to look at the codes in a convenient directory. (i didn't do any installation after this part) 

Now I see that the two are of different versions .. 

My goal is to make a model that extracts  NER on Spanish language using allenNLP following the steps that you have in the paper. 
https://arxiv.org/pdf/1705.00108.pdf. 
I intend to use [crf_tagger model](https://github.com/allenai/allennlp/blob/0722d7f199ec43af791870dbe741eec3e3103c69/allennlp/models/crf_tagger.py)  and make my own datareader, since the format of the input is different. 
Any ideas? 

With regards to the error, 
after I have replaced the line to the library (from allennlp.data.dataset_readers.dataset_utils.span_utils import iob1_to_bioul) when i do allennlp train in this way, 
```allennlp train crf_es_tagger.json -s tmp/spanish-ner --include-package ner_spanish```

I still get the error as below. 

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/run.py", line 18, in <module>
    main(prog="allennlp")
  File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 70, in main
    args.func(args)
  File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/train.py", line 101, in train_model_from_args
    args.recover)
  File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/train.py", line 131, in train_model_from_file
    return train_model(params, serialization_dir, file_friendly_logging, recover)
  File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/train.py", line 262, in train_model
    all_datasets = datasets_from_params(params)
  File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/train.py", line 138, in datasets_from_params
    dataset_reader = DatasetReader.from_params(params.pop('dataset_reader'))
  File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/data/dataset_readers/dataset_reader.py", line 113, in from_params
    return cls.by_name(choice).from_params(params)
  File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/data/dataset_readers/dataset_reader.py", line 112, in from_params
    choice = params.pop_choice('type', cls.list_available())
  File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/common/params.py", line 179, in pop_choice
    value = self.pop(key, default)
  File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/common/params.py", line 96, in pop
    raise ConfigurationError("key \"{}\" is required at location \"{}\"".format(key, self.history))
allennlp.common.checks.ConfigurationError: 'key "type" is required at location "dataset_reader."'

**Comment by matt-gardner** [comment]
Ok, so that problem is because your `DatasetReader` doesn't have a `from_params` method.  We've removed the need for this method on master, relying instead on the type annotations of constructor parameters, but because you're using an older pip install, you need to include this method.  See just above [here](https://github.com/allenai/allennlp/blob/v0.5.1/tutorials/getting_started/using_as_a_library_pt1.md#step-four-write-your-model) in our tutorial for how to do this.

**Comment by iamyihwa** [comment]
hi @matt-gardner 

I got around the issue now by changing our data set to follow the format of conll2003 and to use existing reader.  I still had to change something  from the configuration file (I had to remove  "token_embedders": {  }, two lines, as was mentioned in [this link](https://github.com/allenai/allennlp/issues/1559). ) 

However I would like to know which way of installation is the standard way to do? 

pip install , or to install from master branch? 
Is there any way to figure out the versions? 

Thanks in advance.

**Comment by matt-gardner** [comment]
As with any open source library, if you want a stable, released version, you should use pip to install.  If you want bleeding-edge, possibly buggy or undocumented functionality, you should install from master.

I think we need to figure out a better way to host our documentation so that the version of the docs you're looking at is more clear.

I'm closing this issue, as it seems like your problem has been solved.  If there's still a problem, feel free to re-open it.

**Comment by iamyihwa** [comment]
Thanks @matt-gardner for your response. 

I didn't get so high accuracy using [crf_tagger.json](https://github.com/allenai/allennlp/blob/master/tutorials/getting_started/crf_tagger.json) for training NER. 

So I have used other [ner.jsonnet](https://github.com/allenai/allennlp/blob/e32f486573adfb00dfb6396742ac5f8675908e86/training_config/ner.jsonnet) and get the same error. 


```Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/common/params.py", line 94, in pop
    value = self.params.pop(key)
KeyError: 'type'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/allennlp/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ec2-user/anaconda3/envs/allennlp/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ec2-user/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/run.py", line 18, in <module>
    main(prog="allennlp")
  File "/home/ec2-user/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 70, in main
    args.func(args)
  File "/home/ec2-user/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/train.py", line 101, in train_model_from_args
    args.recover)
  File "/home/ec2-user/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/train.py", line 131, in train_model_from_file
    return train_model(params, serialization_dir, file_friendly_logging, recover)
  File "/home/ec2-user/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/train.py", line 276, in train_model
    model = Model.from_params(vocab, params.pop('model'))
  File "/home/ec2-user/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/models/model.py", line 217, in from_params
    model = cls.by_name(choice).from_params(vocab, params)
  File "/home/ec2-user/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/models/crf_tagger.py", line 180, in from_params
    text_field_embedder = TextFieldEmbedder.from_params(vocab, embedder_params)
  File "/home/ec2-user/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/modules/text_field_embedders/text_field_embedder.py", line 56, in from_params
    return cls.by_name(choice).from_params(vocab, params)
  File "/home/ec2-user/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/modules/text_field_embedders/basic_text_field_embedder.py", line 94, in from_params
    token_embedders[key] = TokenEmbedder.from_params(vocab, embedder_params)
  File "/home/ec2-user/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/modules/token_embedders/token_embedder.py", line 31, in from_params
    choice = params.pop_choice('type', cls.list_available())
  File "/home/ec2-user/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/common/params.py", line 179, in pop_choice
    value = self.pop(key, default)
  File "/home/ec2-user/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/common/params.py", line 96, in pop
    raise ConfigurationError("key \"{}\" is required at location \"{}\"".format(key, self.history))
allennlp.common.checks.ConfigurationError: 'key "type" is required at location "model.text_field_embedder.token_embedders."'```

**Comment by matt-gardner** [comment]
Do you need to remove the `token_embedders:` line like you did for `crf_tagger.json`?

**Comment by iamyihwa** [comment]
hey @matt-gardner  yes!! thanks!! I forgot that i had to do that! 
although this file I copied from the git repository .. and thinking should be the most recent version .. 

Additionally  I changed names for encoding in two places with different names (IOB1 and BIO), I checked two places conll2003.py and crf_tagger.py and allowed types were not the same. 

``` "dataset_reader": {
    "type": "conll2003",
    "tag_label": "ner",
    "coding_scheme": "IOB1",```

``` "model": {
    "type": "crf_tagger",
    "constraint_type": "BIO",
    "dropout": 0.5,
```
