### ISSUE TITLE
MultiGPU Trainer test fails

### ISSUE THREAD

**Issue by nelson-liu** [allenai/allennlp#1585]
**Describe the bug**
Trainer multigpu test fails

**To Reproduce**
Steps to reproduce the behavior
run the tests on a multigpu system.

**Expected behavior**
test passes

**System (please complete the following information):**
 - OS: Linux
 - Python version: 3.6
 - AllenNLP version: v0.5.1

**Additional context**

Here's the full traceback:

```
_____________________________ TestTrainer.test_trainer_can_run_multiple_gpu _____________________________

self = <allennlp.tests.training.trainer_test.TestTrainer testMethod=test_trainer_can_run_multiple_gpu>

    @pytest.mark.skipif(torch.cuda.device_count() < 2,
                        reason="Need multiple GPUs.")
    def test_trainer_can_run_multiple_gpu(self):
        multigpu_iterator = BasicIterator(batch_size=4)
        multigpu_iterator.index_with(self.vocab)
        trainer = Trainer(self.model, self.optimizer,
                          multigpu_iterator, self.instances, num_epochs=2,
                          cuda_device=[0, 1])
>       trainer.train()

tests/training/trainer_test.py:88:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
training/trainer.py:679: in train
    train_metrics = self._train_epoch(epoch)
training/trainer.py:463: in _train_epoch
    loss = self._batch_loss(batch, for_training=True)
training/trainer.py:396: in _batch_loss
    output_dict = self._data_parallel(batch)
training/trainer.py:387: in _data_parallel
    losses = gather([output['loss'] for output in outputs], used_device_ids[0], 0)
../torch/nn/parallel/scatter_gather.py:68: in gather
    return gather_map(outputs)
../torch/nn/parallel/scatter_gather.py:55: in gather_map
    return Gather.apply(target_device, dim, *outputs)
../torch/nn/parallel/_functions.py:54: in forward
    ctx.input_sizes = tuple(map(lambda i: i.size(ctx.dim), inputs))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

i = tensor(0.7947, device='cuda:0')

>   ctx.input_sizes = tuple(map(lambda i: i.size(ctx.dim), inputs))
E   RuntimeError: dimension specified as 0 but tensor has no dimensions

../torch/nn/parallel/_functions.py:54: RuntimeError
----------------------------------------- Captured stderr call ------------------------------------------
2018-08-07 10:12:19,024 - INFO - allennlp.common.checks - Pytorch version: 0.4.0
0it [00:00, ?it/s]2018-08-07 10:12:19,025 - INFO - allennlp.data.dataset_readers.sequence_tagging - Reading instances from lines in file at: /home/nfliu/miniconda3/envs/test/lib/python3.6/site-packages/allennlp/tests/fixtures/data/sequence_tagging.tsv
4it [00:00, 4651.29it/s]
2018-08-07 10:12:19,026 - INFO - allennlp.data.vocabulary - Fitting token dictionary from dataset.
100%|██████████| 4/4 [00:00<00:00, 70492.50it/s]
2018-08-07 10:12:19,028 - INFO - allennlp.training.trainer - WARNING: Multiple GPU support is experimental not recommended for use. In some cases it may lead to incorrect results or undefined behavior.
2018-08-07 10:12:19,029 - INFO - allennlp.training.trainer - Beginning training.
2018-08-07 10:12:19,030 - INFO - allennlp.training.trainer - Epoch 0/1
2018-08-07 10:12:19,030 - INFO - allennlp.training.trainer - Peak CPU memory usage MB: 2981.964
2018-08-07 10:12:19,115 - INFO - allennlp.training.trainer - GPU 0 memory usage MB: 1961
2018-08-07 10:12:19,117 - INFO - allennlp.training.trainer - GPU 1 memory usage MB: 10
  0%|          | 0/1 [00:00<?, ?it/s]2018-08-07 10:12:19,119 - INFO - allennlp.training.trainer - Training
------------------------------------------- Captured log call -------------------------------------------
checks.py                   29 INFO     Pytorch version: 0.4.0
sequence_tagging.py         57 INFO     Reading instances from lines in file at: /home/nfliu/miniconda3/envs/test/lib/python3.6/site-packages/allennlp/tests/fixtures/data/sequence_tagging.tsv
vocabulary.py              341 INFO     Fitting token dictionary from dataset.
trainer.py                 280 INFO     WARNING: Multiple GPU support is experimental not recommended for use. In some cases it may lead to incorrect results or undefined behavior.
trainer.py                 671 INFO     Beginning training.
trainer.py                 426 INFO     Epoch 0/1
trainer.py                 427 INFO     Peak CPU memory usage MB: 2981.964
trainer.py                 429 INFO     GPU 0 memory usage MB: 1961
trainer.py                 429 INFO     GPU 1 memory usage MB: 10
trainer.py                 452 INFO     Training
```

**Comment by lz-chen** [comment]
Hi, is the multiple GPU training supported by Allennlp now? I am currently working on a project which would benefit a lot from it. But so far I can't seem to make it work with multi GPU. 
Tried to pass a list `[0,1]` as `cuda_device`, but then the check fails:
```
2018-08-28 12:38:18,365 - INFO - allennlp.common.params - random_seed = 13370
2018-08-28 12:38:18,365 - INFO - allennlp.common.params - numpy_seed = 1337
2018-08-28 12:38:18,365 - INFO - allennlp.common.params - pytorch_seed = 133
2018-08-28 12:38:18,366 - INFO - allennlp.common.checks - Pytorch version: 0.4.1
Traceback (most recent call last):
  File "/home/liah/Documents/lc-exabel/python/exabel/nlp/topic_modeling/train_topic_model.py", line 73, in <module>
    main(args)
  File "/home/liah/Documents/lc-exabel/python/exabel/nlp/topic_modeling/train_topic_model.py", line 47, in main
    recover=args.recover)
  File "/home/liah/.virtualenvs/python-RNKCJeUC/lib/python3.6/site-packages/allennlp/commands/train.py", line 132, in train_model_from_file
    return train_model(params, serialization_dir, file_friendly_logging, recover)
  File "/home/liah/.virtualenvs/python-RNKCJeUC/lib/python3.6/site-packages/allennlp/commands/train.py", line 257, in train_model
    check_for_gpu(params.get('trainer').get('cuda_device', -1))
  File "/home/liah/.virtualenvs/python-RNKCJeUC/lib/python3.6/site-packages/allennlp/common/checks.py", line 42, in check_for_gpu
    if device_id is not None and device_id >= cuda.device_count():
TypeError: '>=' not supported between instances of 'list' and 'int'
```
However the Trainer class does accept a `Union[list, int]` as `cuda_device` when initializing, isn't it?

**Comment by matt-peters** [comment]
MultiGPU training works, but is unsupported.  Currently you need to bypass the allennlp train command and instantiate `Trainer` directly with a list of `cuda_device`.  There isn't any reason it couldn't also train from a config file with multiple GPUs but it requires fixing `check_for_gpu` (and possibly other changes).  Would you be willing to work on a PR?

**Comment by matt-peters** [comment]
FYI: there is a stale open PR #1445 that fixes the `check_for_gpu` issue.

**Comment by lz-chen** [comment]
@matt-peters Thank you for the tips! I will try that. By the way, is Allennlp going to support multi-process loading of the dataset, like `torch.utils.data.DataLoader` in PyTorch? In the `DatasetReader` I implemented, the only thing that the `_read()` function does is to read a line in the JSON file (text is already pre-processed), tokenize it and create an `Instance`, but it is still pretty slow to iterate over the whole dataset since the dataset I am working with now is huge. Any tips on how this speed can be improved?

**Comment by tingkai-zhang** [comment]
Hi,  I got the same error
```
  File "/media/F/tingkai/anaconda3/envs/torch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477ll__
    result = self.forward(*input, **kwargs)
  File "/media/F/tingkai/anaconda3/envs/torch/lib/python3.7/site-packages/torch/nn/modules/loss.py", line 862, d
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "/media/F/tingkai/anaconda3/envs/torch/lib/python3.7/site-packages/torch/nn/functional.py", line 1550, intropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/media/F/tingkai/anaconda3/envs/torch/lib/python3.7/site-packages/torch/nn/functional.py", line 1403, is
    if input.size(0) != target.size(0):
RuntimeError: dimension specified as 0 but tensor has no dimensions
```
after i change the `cuda_device` from an int to a list of int. It works fine when i assign the model when i assign it to only one gpu with anything else unchanged.
This problem happens at the end of one epoch training. That is, it occurs when the model processing the last batch of an epoch. 
It was calculating the loss of last batch and i check that the `label` i passed to the model `forward` function turns out to be None (but  the classify logits of that batch is correct ).

**Comment by matt-gardner** [comment]
@tingkai-zhang, this looks like a problem, but a different one from what's described above.  Can you open a new issue for this?

**Comment by tingkai-zhang** [comment]
OK. 
Opened #2201
