### ISSUE TITLE
Using `requires_grad=True` on ELMo throws error when calling `loss.backward()`.

### ISSUE THREAD

**Issue by zfang** [allenai/allennlp#1644]
**Describe the bug**
Using `requires_grad=True` on ELMo throws error when calling `loss.backward()`.

`loss.backward(retain_graph=True)` solves the issue, but is extremely slow. The issue is most likely caused by `ElmoLstm`.

**To Reproduce**
1. Create ELMo
```python
from allennlp.modules.elmo import Elmo

elmo = Elmo(requires_grad=True, vocab_to_cache=vocab_to_cache, ...)
```
2. Start training (`loss.backward()`, etc)
3. See error
```
RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.
```

**System (please complete the following information):**
 - OS: Ubuntu
 - Python version: 3.6
 - AllenNLP version: 0.6.0
 - PyTorch version: 0.4.0

**Comment by nelson-liu** [comment]
Hmm, can you provide a script to reproduce? I've used the flag successfully in some of my own code, and this test suggests that the `Elmo` class itself is ok:

```
In [1]: from allennlp.modules.elmo import Elmo, batch_to_ids
   ...: options_file = "https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x4096_512_2048cnn_2xhighway/elmo_2x4096_512_2048cnn_2xhighway_options.json"
   ...: weight_file = "https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x4096_512_2048cnn_2xhighway/elmo_2x4096_512_2048cnn_2xhighway_weights.hdf5"
   ...:
   ...: elmo = Elmo(options_file, weight_file, 1, dropout=0, requires_grad=True)
   ...:
   ...:

In [2]: # use batch_to_ids to convert sentences to character ids
   ...: sentences = [['First', 'sentence', '.'], ['Another', '.']]
   ...: character_ids = batch_to_ids(sentences)
   ...:
   ...: embeddings = elmo(character_ids)
   ...:
   ...:

In [3]: embeddings['elmo_representations']
Out[3]:
[tensor([[[ 0.1474, -0.1475,  0.1376,  ...,  0.0270, -0.4051, -0.0498],
          [ 0.2394,  0.0769,  0.4126,  ..., -0.1671, -0.1707,  0.3884],
          [-0.7602, -0.4944, -0.5355,  ..., -0.0803,  0.0361,  0.1128]],

         [[ 0.2603, -0.4437,  0.2726,  ..., -0.0830, -0.1522, -0.1361],
          [-0.7772, -0.4294, -0.2651,  ..., -0.0803,  0.0361,  0.1128],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]],
        grad_fn=<DropoutBackward>)]

In [4]: embeddings['elmo_representations'][0].requires_grad
Out[4]: True

In [5]: loss = embeddings['elmo_representations'][0].sum()

In [6]: loss
Out[6]: tensor(34.8682, grad_fn=<SumBackward0>)

In [7]: loss.requires_grad
Out[7]: True

In [8]: loss.backward()

In [9]: next(elmo.parameters()).grad
Out[9]:
tensor([[  0.0000,   0.0000,   0.0000,  ...,   0.0000,   0.0000,   0.0000],
        [  0.0000,   0.0000,   0.0000,  ...,   0.0000,   0.0000,   0.0000],
        [  0.0000,   0.0000,   0.0000,  ...,   0.0000,   0.0000,   0.0000],
        ...,
        [ -1.1242,   2.0102, -14.8834,  ...,  -5.2854,   8.0070,  10.8772],
        [-11.1280,  -9.7459,   6.6969,  ...,  -4.0071,   6.0466,  14.5920],
        [ -3.4111,  -8.6062,   9.1516,  ..., -14.5400, -14.5856,  13.3455]])
```

**Comment by zfang** [comment]
@DeNeutoy is right. This problem does not appear with `character_ids`.

Any suggestions? 

```python
import torch
from torch import optim
from allennlp.modules.elmo import Elmo

ELMO_OPTIONS_FILE = "https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x1024_128_2048cnn_1xhighway/elmo_2x1024_128_2048cnn_1xhighway_options.json"
ELMO_WEIGHT_FILE = "https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x1024_128_2048cnn_1xhighway/elmo_2x1024_128_2048cnn_1xhighway_weights.hdf5"

vocab_to_cache = [ '<pad>', 'hello', 'world' ]

elmo = Elmo(options_file=ELMO_OPTIONS_FILE,
            weight_file=ELMO_WEIGHT_FILE,
            num_output_representations=1,
            requires_grad=True,
            dropout=0,
            vocab_to_cache=vocab_to_cache)

'''
Tried these, did not help
del elmo._elmo_lstm._token_embedder
for p in elmo._elmo_lstm.parameters():
    p.requires_grad = False
'''

optimizer = optim.Adam(filter(lambda p: p.requires_grad, elmo.parameters()), 1e-3)

word_tensor = torch.tensor([[[1, 2]]])
loss = elmo(word_tensor, word_tensor)['elmo_representations'][0].sum()
for name, p in elmo.named_parameters():
    print(name, p.requires_grad, p.grad is None)

loss.backward()
optimizer.step()
elmo.zero_grad()

word_tensor = torch.tensor([[[2, 1]]])
loss = elmo(word_tensor, word_tensor)['elmo_representations'][0].sum()
for name, p in elmo.named_parameters():
    print(name, p.requires_grad, p.grad is None)

loss.backward() # RuntimeError
```

**Comment by DeNeutoy** [comment]
Please can you post a full stack trace?

**Comment by zfang** [comment]
I do not think the full stack trace helps, but here it is:

```
Traceback (most recent call last):
  File "script.py", line 40, in <module>
    loss.backward() # RuntimeError
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 89, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.
```

**Comment by nelson-liu** [comment]
maybe we should throw an error if `vocab_to_cache` is used with `requires_grad=True`?

**Comment by zfang** [comment]
OK if I hardcode `requires_grad=False` here then it works: https://github.com/allenai/allennlp/blob/b70e026702c590618552ab857fc6661662ab72f2/allennlp/modules/elmo.py#L499

Could we set `requires_grad=False` on `_token_embedder` when `vocab_to_cache` is not None?

**Comment by DeNeutoy** [comment]
Yep sounds good - if you could send a PR with a small test that would be great!

**Comment by zfang** [comment]
I'm not sure if I will make more effort to please everyone in https://github.com/allenai/allennlp/pull/1646, but if you want a workaround to make `Elmo` tunable with `vocab_to_cache`, here it is:
```python
elmo = Elmo(requires_grad=False, vocab_to_cache=vocab_to_cache, ...)
for p in elmo._elmo_lstm._elmo_lstm.parameters():
    p.requires_grad = True
```

This will make the `ElmoLstm` layer tunable, in addition to the `ScalarMix` layer. You can apply the same trick on `elmo._elmo_lstm._word_embedding`.

**Comment by DeNeutoy** [comment]
This behaviour is essentially ill-defined and if you really want this, you can use @zfang's code here.
