### ISSUE TITLE
When running pip-installed AllenNLP in AllenNLP source directory uses source files.

### ISSUE THREAD

**Issue by nelson-liu** [allenai/allennlp#1662]
**Describe the bug**

If i run the pip-installed AllenNLP in the allennlp source directory (e.g., if i want to train with the pip-version on one of the training configs in the source directory).

**To Reproduce**
Steps to reproduce the behavior
```
cd ~
conda create -n allennlp_pip python=3.6
source activate allennlp_pip
pip install allennlp

cd /allennlp/source/directory
allennlp train --help
```

**Expected behavior**

No crash, since it uses the pip version.

**Actual behavior**

I get an import error because it tries to import the files in the source directory, which have different requirements than the current pip installed version:

```
$ allennlp train --help
Traceback (most recent call last):
  File "/Users/nfliu/miniconda3/envs/allennlp_pip/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/nfliu/miniconda3/envs/allennlp_pip/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/nfliu/Documents/Github/allennlp/allennlp/run.py", line 15, in <module>
    from allennlp.commands import main  # pylint: disable=wrong-import-position
  File "/Users/nfliu/Documents/Github/allennlp/allennlp/commands/__init__.py", line 6, in <module>
    from allennlp.commands.configure import Configure
  File "/Users/nfliu/Documents/Github/allennlp/allennlp/commands/configure.py", line 22, in <module>
    from allennlp.common.configuration import configure, Config, render_config
  File "/Users/nfliu/Documents/Github/allennlp/allennlp/common/__init__.py", line 1, in <module>
    from allennlp.common.params import Params
  File "/Users/nfliu/Documents/Github/allennlp/allennlp/common/params.py", line 30, in <module>
    from allennlp.common.file_utils import cached_path
  File "/Users/nfliu/Documents/Github/allennlp/allennlp/common/file_utils.py", line 16, in <module>
    import boto3
ModuleNotFoundError: No module named 'boto3'
```

**System (please complete the following information):**
 - OS: OS X
 - Python version: 3.6.6
 - AllenNLP version: 0.6
 - PyTorch version: 0.4.1

cc: @schmmd / @joelgrus , any clue of what's going on here? Maybe something odd with PYTHONPATH?

**Comment by nelson-liu** [comment]
Some more context:

```
(allennlp_pip) nfliu at kilauea in ~/.../Github/allennlp on allennlp_append_to_path
$ python
Python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 11:07:29)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import allennlp
>>> allennlp.__file__
'/Users/nfliu/Documents/Github/allennlp/allennlp/__init__.py'
>>> exit()

(allennlp_pip) nfliu at kilauea in ~/.../Github/allennlp on allennlp_append_to_path
$ which allennlp
/Users/nfliu/miniconda3/envs/allennlp_pip/bin/allennlp
```

I think my gripe is that the allennlp binary is taken from the pip install, but actually importing allennlp takes it from the source install.

if i move to a directory that isn't the allennlp source root, i get:

```
$ python
iPython 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 11:07:29)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import allennlp
>>> allennlp.__file__
'/Users/nfliu/miniconda3/envs/allennlp_pip/lib/python3.6/site-packages/allennlp/__init__.py'
>>> exit()
```

**Comment by joelgrus** [comment]
I believe python always favors modules in the current directory?

the allennlp "binary" is just a script that calls python, which then favors modules in the current directory?

```bash
(allennlp-demo) ip-10-0-0-198:allennlp joelg$ which allennlp
/Users/joelg/anaconda3/envs/allennlp-demo/bin/allennlp
(allennlp-demo) ip-10-0-0-198:allennlp joelg$ cat `which allennlp`
#!/bin/sh
python -m allennlp.run "$@"
```

**Comment by schmmd** [comment]
That seems like the behavior I would expect.  See [the definition of `allennlp`](https://github.com/allenai/allennlp/blob/master/bin/allennlp).

**Comment by nelson-liu** [comment]
i see, good to know! it would be nice to have a more convenient way to run training configs with a pip-installed version of allennlp (versus cloning, moving the training_configs somewhere else, then running `allennlp train` there since you can't run it in the allennlp source directory. 

furthermore, the models page says that you can use the following command: `allennlp train training_config/bidaf.json -s output_path`, but this doesn't currently work for the pip-installed version.

**Comment by nelson-liu** [comment]
Maybe this would be easier if allennlp train could take the URL to a config file.

**Comment by joelgrus** [comment]
it should be able to already, does that not work?

**Comment by nelson-liu** [comment]
I tried the following with two configs:

```
(allennlp) nfliu at kilauea in ~/.../Github/allennlp on master
$ rm /Users/nfliu/.allennlp/datasets/48a99dfe0b9e71688138e4253616b7757aa5ec2c8112fd9f4ca7900b215e63da
(allennlp) nfliu at kilauea in ~/.../Github/allennlp on master
$ allennlp train https://github.com/allenai/allennlp/blob/master/training_config/bidaf.json -s test
2018-08-24 16:15:14,105 - INFO - allennlp.common.registrable - instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
2018-08-24 16:15:14,106 - INFO - allennlp.common.registrable - instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
2018-08-24 16:15:14,110 - INFO - allennlp.common.registrable - instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
2018-08-24 16:15:14,115 - INFO - allennlp.common.registrable - instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
2018-08-24 16:15:15,889 - INFO - allennlp.common.file_utils - https://github.com/allenai/allennlp/blob/master/training_config/bidaf.json not found in cache, downloading to /var/folders/_z/jqv3xt6d7594lny6hnr9flyc0000gn/T/tmpvosdc_an
83808B [00:00, 278431.12B/s]
2018-08-24 16:15:16,747 - INFO - allennlp.common.file_utils - copying /var/folders/_z/jqv3xt6d7594lny6hnr9flyc0000gn/T/tmpvosdc_an to cache at /Users/nfliu/.allennlp/datasets/48a99dfe0b9e71688138e4253616b7757aa5ec2c8112fd9f4ca7900b215e63da
2018-08-24 16:15:16,748 - INFO - allennlp.common.file_utils - creating metadata file for /Users/nfliu/.allennlp/datasets/48a99dfe0b9e71688138e4253616b7757aa5ec2c8112fd9f4ca7900b215e63da
2018-08-24 16:15:16,749 - INFO - allennlp.common.file_utils - removing temp file /var/folders/_z/jqv3xt6d7594lny6hnr9flyc0000gn/T/tmpvosdc_an
Traceback (most recent call last):
  File "/Users/nfliu/miniconda3/envs/allennlp/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/nfliu/miniconda3/envs/allennlp/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/nfliu/Documents/Github/allennlp/allennlp/run.py", line 18, in <module>
    main(prog="allennlp")
  File "/Users/nfliu/Documents/Github/allennlp/allennlp/commands/__init__.py", line 70, in main
    args.func(args)
  File "/Users/nfliu/Documents/Github/allennlp/allennlp/commands/train.py", line 102, in train_model_from_args
    args.recover)
  File "/Users/nfliu/Documents/Github/allennlp/allennlp/commands/train.py", line 131, in train_model_from_file
    params = Params.from_file(parameter_filename, overrides)
  File "/Users/nfliu/Documents/Github/allennlp/allennlp/common/params.py", line 362, in from_file
    file_dict = json.loads(evaluate_file(params_file, ext_vars=ext_vars))
RuntimeError: STATIC ERROR: /Users/nfliu/.allennlp/datasets/48a99dfe0b9e71688138e4253616b7757aa5ec2c8112fd9f4ca7900b215e63da:30:40: Could not lex the character code 194
```

```
(allennlp) nfliu at kilauea in ~/.../Github/allennlp on master
$ allennlp train https://github.com/allenai/allennlp/blob/master/training_config/biattentive_classification_network.json -s test
2018-08-24 16:15:55,085 - INFO - allennlp.common.registrable - instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
2018-08-24 16:15:55,088 - INFO - allennlp.common.registrable - instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
2018-08-24 16:15:55,098 - INFO - allennlp.common.registrable - instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
2018-08-24 16:15:55,108 - INFO - allennlp.common.registrable - instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
2018-08-24 16:15:57,018 - INFO - allennlp.common.file_utils - https://github.com/allenai/allennlp/blob/master/training_config/biattentive_classification_network.json not found in cache, downloading to /var/folders/_z/jqv3xt6d7594lny6hnr9flyc0000gn/T/tmphcgaig2h
76084B [00:00, 283898.67B/s]
2018-08-24 16:15:57,777 - INFO - allennlp.common.file_utils - copying /var/folders/_z/jqv3xt6d7594lny6hnr9flyc0000gn/T/tmphcgaig2h to cache at /Users/nfliu/.allennlp/datasets/0023c331cd89125ed442279e34ecf71c8c25b3d17bce128373391d84a9f6bc24
2018-08-24 16:15:57,785 - INFO - allennlp.common.file_utils - creating metadata file for /Users/nfliu/.allennlp/datasets/0023c331cd89125ed442279e34ecf71c8c25b3d17bce128373391d84a9f6bc24
2018-08-24 16:15:57,786 - INFO - allennlp.common.file_utils - removing temp file /var/folders/_z/jqv3xt6d7594lny6hnr9flyc0000gn/T/tmphcgaig2h
Traceback (most recent call last):
  File "/Users/nfliu/miniconda3/envs/allennlp/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/nfliu/miniconda3/envs/allennlp/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/nfliu/Documents/Github/allennlp/allennlp/run.py", line 18, in <module>
    main(prog="allennlp")
  File "/Users/nfliu/Documents/Github/allennlp/allennlp/commands/__init__.py", line 70, in main
    args.func(args)
  File "/Users/nfliu/Documents/Github/allennlp/allennlp/commands/train.py", line 102, in train_model_from_args
    args.recover)
  File "/Users/nfliu/Documents/Github/allennlp/allennlp/commands/train.py", line 131, in train_model_from_file
    params = Params.from_file(parameter_filename, overrides)
  File "/Users/nfliu/Documents/Github/allennlp/allennlp/common/params.py", line 362, in from_file
    file_dict = json.loads(evaluate_file(params_file, ext_vars=ext_vars))
RuntimeError: STATIC ERROR: /Users/nfliu/.allennlp/datasets/0023c331cd89125ed442279e34ecf71c8c25b3d17bce128373391d84a9f6bc24:30:69: Could not lex the character code 194
```

**Comment by joelgrus** [comment]
that's because that's the github *page* corresponding to the config file, not the config file itself.

it works if you use

```
https://raw.githubusercontent.com/allenai/allennlp/master/training_config/bidaf.json
```

**Comment by nelson-liu** [comment]
🤦‍♂️  my apologies. I think I've gotten all my questions answered, so closing this. Thanks @joelgrus and @schmmd
