### ISSUE TITLE
Bidaf issue 

### ISSUE THREAD

**Issue by Senagb** [allenai/allennlp#1693]
I am trying to train bidaf model on new dataset as you can see the dataset starts to make some epochs but after that an exception is thrown, could anyone help me please?

start_acc: 0.1035, end_acc: 0.0995, span_acc: 0.0523, em: 0.0542, f1: 0.1403, loss: 7.5451 ||: 100%|##########| 864/864 [10:08<00:00,  1.42it/s]
start_acc: 0.1753, end_acc: 0.1646, span_acc: 0.0999, em: 0.1091, f1: 0.2304, loss: 6.7823 ||: 100%|##########| 177/177 [01:12<00:00,  2.44it/s]
start_acc: 0.2255, end_acc: 0.2073, span_acc: 0.1309, em: 0.1373, f1: 0.2872, loss: 6.2950 ||: 100%|##########| 864/864 [08:54<00:00,  1.62it/s]
start_acc: 0.2821, end_acc: 0.2492, span_acc: 0.1679, em: 0.1796, f1: 0.3470, loss: 5.8827 ||: 100%|##########| 177/177 [00:52<00:00,  3.37it/s]
start_acc: 0.3052, end_acc: 0.2793, span_acc: 0.1884, em: 0.1976, f1: 0.3723, loss: 5.5747 ||:  16%|#6        | 141/864 [01:31<07:50,  1.54it/s]Traceback (most recent call last):
  File "drive/allennlp-as-a-library-example-master/new_main.py", line 35, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/allennlp/commands/__init__.py", line 70, in main
    args.func(args)
  File "/usr/local/lib/python3.6/dist-packages/allennlp/commands/train.py", line 102, in train_model_from_args
    args.recover)
  File "/usr/local/lib/python3.6/dist-packages/allennlp/commands/train.py", line 132, in train_model_from_file
    return train_model(params, serialization_dir, file_friendly_logging, recover)
  File "/usr/local/lib/python3.6/dist-packages/allennlp/commands/train.py", line 320, in train_model
    metrics = trainer.train()
  File "/usr/local/lib/python3.6/dist-packages/allennlp/training/trainer.py", line 720, in train
    train_metrics = self._train_epoch(epoch)
  File "/usr/local/lib/python3.6/dist-packages/allennlp/training/trainer.py", line 476, in _train_epoch
    for batch in train_generator_tqdm:
  File "/usr/local/lib/python3.6/dist-packages/tqdm/_tqdm.py", line 933, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.6/dist-packages/allennlp/data/iterators/data_iterator.py", line 158, in __call__
    cuda_device=cuda_device)
  File "/usr/local/lib/python3.6/dist-packages/allennlp/data/dataset.py", line 141, in as_tensor_dict
    for field, tensors in instance.as_tensor_dict(lengths_to_use, cuda_device).items():
  File "/usr/local/lib/python3.6/dist-packages/allennlp/data/instance.py", line 87, in as_tensor_dict
    cuda_device=cuda_device)
  File "/usr/local/lib/python3.6/dist-packages/allennlp/data/fields/text_field.py", line 140, in as_tensor
    desired_num_tokens, padding_lengths)
  File "/usr/local/lib/python3.6/dist-packages/allennlp/data/token_indexers/token_characters_indexer.py", line 91, in pad_token_sequence
    desired_token_length = padding_lengths['num_token_characters']
KeyError: 'num_token_characters'

**Comment by nelson-liu** [comment]
seems related to https://github.com/allenai/allennlp/issues/1591 , your dataset reader might be generating a data instance that is actually empty.

can you check your dataset and see if there are any instances where the "text" is all whitespace or the empty string?

**Comment by Senagb** [comment]
@nelson-liu thanks for the quick reply, I am using java code to ensure that the text is trimmed and if the answer text is empty then I remove this answer form the dataset and question from the dataset.
I am checking the dataset right now but I am bit confused isn't supposed that it throws this exception from the first epoch not the third one ?

**Comment by matt-gardner** [comment]
@nelson-liu, that this happens on a later epoch seems to confirm my suspicion that this is due to the _whole batch_ being empty, not just a single instance.  Still quite cryptic, though, and I'm not really sure what's going on.

@Senagb, any chance you can try to find the instance that is causing this, and provide a minimal failure case?  It seems _very_ likely that this is caused by some question or passage being empty - can you double check your data, and see if you can reproduce this with a smaller dataset size?  Having a failing test case would be really helpful in nailing down what's going on here.

**Comment by Senagb** [comment]
@matt-gardner I have checked all the questions and answers non of them are empty. Number of tokens in answer ranges from [1-21] token. 

I am not sure but if there is empty text should this exception thrown in the first epoch? 

I have checked @nelson-liu  suggestion but it didn't do the trick but I tried different values for "batch_size" [40,32,64] all but the 40 throw this exception the 40 completed normally without any error.

I will try to reproduce it with smaller test case and if I found one sure will tell you.

**Comment by Senagb** [comment]
I found some white spaces answers with control characters, I removed them and retesting right now.

**Comment by nelson-liu** [comment]
thanks for the update @Senagb  -- if that fixes them, can you confirm whether or not the _entire_ batch was these whitespace answers? or just a few instances.

**Comment by matt-gardner** [comment]
If it didn't happen on the first epoch, it _has_ to be the case that this only happens due to a particular batching, right?  I mean, those instances would have been in a batch in the first epoch, and it didn't crash.  It's only when the instances got rebatched into something particularly unlucky that something crashed.

**Comment by nelson-liu** [comment]
And I guess that's more likely to happen when you're using a bucketiterator or something, since that would tend to batch these empty things together?
