### ISSUE TITLE
CUDNN_STATUS_NOT_SUPPORTED

### ISSUE THREAD

**Issue by zpaines** [allenai/allennlp#1791]
**Describe the bug**
When running certain inputs through `elmo.embed_sentences` with a large batch size I see this error. It doesn't appear to be directly related to input size since it works for some much larger inputs with the same batch size. 

**To Reproduce**
Steps to reproduce the behavior
1. I'm using [this file](https://github.com/allenai/allennlp/files/2398377/Review001221.txt)
2. First I tokenize it with the following command:
`document_sentences = list(filter(lambda a: len(a) > 0, map(lambda s: list(filter(lambda x: re.search('[a-xA-Z]', x), s.split())), re.split("[\\n.]", t))))`
3. Then I put it into `elmo.embed_sentences` like so:
`embedding = list(elmo.embed_sentences(document_sentences, 100))`
4. I get this stack trace:
```
Traceback (most recent call last):
  File "cudnn_error.py", line 63, in <module>
    embedding = list(elmo.embed_sentences(document_sentences, 100))
  File "/home/ubuntu/anaconda/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/elmo.py", line 276, in embed_sentences
    yield from self.embed_batch(batch)
  File "/home/ubuntu/anaconda/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/elmo.py", line 244, in embed_batch
    embeddings, mask = self.batch_to_embeddings(batch)
  File "/home/ubuntu/anaconda/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/elmo.py", line 186, in batch_to_embeddings
    bilm_output = self.elmo_bilm(character_ids)
  File "/home/ubuntu/anaconda/envs/allennlp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda/envs/allennlp/lib/python3.6/site-packages/allennlp/modules/elmo.py", line 592, in forward
    token_embedding = self._token_embedder(inputs)
  File "/home/ubuntu/anaconda/envs/allennlp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda/envs/allennlp/lib/python3.6/site-packages/allennlp/modules/elmo.py", line 361, in forward
    convolved = conv(character_embedding)
  File "/home/ubuntu/anaconda/envs/allennlp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda/envs/allennlp/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 176, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.
```
**Expected behavior**
I would expect it to return embeddings like any other input. 

**System (please complete the following information):**
 - OS: Description:	Ubuntu 16.04.5 LTS
 - Python version: Python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 17:14:51) 
[GCC 7.2.0] on linux
 - AllenNLP version: Looks like 0.6.1
 - PyTorch version: 0.4.1
pip freeze output: [deps.txt](https://github.com/allenai/allennlp/files/2398402/deps.txt)
cudnn version 7102 (according to `torch.backends.cudnn.version()`)
 cuda version `7.5.17`

**Comment by nelson-liu** [comment]
Thanks for making this post! I do recall seeing this before, and it's a pytorch issue with the conv net code (see https://github.com/pytorch/pytorch/issues/4107 ).

To get around it, I just reduced the batch size --- not a permanent solution by any means, but it might work for you?

**Comment by zpaines** [comment]
Reducing the batch size does work, but it runs much slower. Currently my workaround is just to catch the error and reduce the batch size on that input until it works. Larger batch sizes trigger it on more inputs. 

Well not much you can do about it if it's a pytorch issue I guess! Thanks for the info. Hopefully it will be resolved at some point.

**Comment by nelson-liu** [comment]
yeah, hopefully soon! closing this now
