### ISSUE TITLE
Pretrained models wikitables

### ISSUE THREAD

**Issue by shwetamandhare** [allenai/allennlp#1816]
Is there any pretained models available for wikitables?

**Comment by matt-gardner** [comment]
There's one trained on just one split of the data here: https://s3-us-west-2.amazonaws.com/allennlp/models/wikitables-model-2018.09.14.tar.gz.  We don't have official evaluation numbers for this, but it definitely won't be as good as something trained on the whole data, and it's not even our best run.  It's just a placeholder model that we're using as we're building out a demo.

**Comment by matt-gardner** [comment]
See [this issue](https://github.com/allenai/allennlp/issues/1123) for some additional context on the performance of this model.  See [this tutorial](https://github.com/allenai/allennlp/blob/master/tutorials/getting_started/walk_through_allennlp/training_and_evaluating.md) for more information on training a parser.  You can use the provided [training configuration](https://github.com/allenai/allennlp/blob/master/training_config/wikitables_parser.jsonnet) for the wikitables parser and train the model, after downloading the data and changing paths appropriately.

**Comment by YoPatapon** [comment]
@matt-gardner I have downloaded the wikitables dataset, and changed the paths to the ".examples" files. But it incurred a "No instances were read" error. Must I preprocess the data with the preprocess script? And is the DPD file a must here? Because I found the DPD file download link is invalid now.

**Comment by YoPatapon** [comment]
I noticed there is a wikitablesDatasetReader class in the doc that can load the ".examples" files directly. We don's have to preprocess the data files, do we?

**Comment by YoPatapon** [comment]
@matt-gardner Hi Matt, I followed your instructions and tried to run the experiments. However, I met a new problem when loading the logical forms from the DPD files. The error message is as 

> below:2018-11-13 21:32:46,948 - INFO - allennlp.common.params - random_seed = 13370
2018-11-13 21:32:46,948 - INFO - allennlp.common.params - numpy_seed = 1337
2018-11-13 21:32:46,948 - INFO - allennlp.common.params - pytorch_seed = 133
2018-11-13 21:32:46,949 - INFO - allennlp.common.checks - Pytorch version: 0.4.1.post2
2018-11-13 21:32:46,950 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.data.dataset_readers.dataset_reader.DatasetReader'> from params {'dpd_output_directory': 'data/wikitables/h-strict-dump-combined/', 'lazy': False, 'question_token_indexers': {'tokens': {'type': 'single_id'}}, 'tables_directory': 'data/wikitables/', 'type': 'wikitables'} and extras {}
2018-11-13 21:32:46,950 - INFO - allennlp.common.params - dataset_reader.type = wikitables
2018-11-13 21:32:46,950 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.data.dataset_readers.semantic_parsing.wikitables.wikitables.WikiTablesDatasetReader'> from params {'dpd_output_directory': 'data/wikitables/h-strict-dump-combined/', 'lazy': False, 'question_token_indexers': {'tokens': {'type': 'single_id'}}, 'tables_directory': 'data/wikitables/'} and extras {}
2018-11-13 21:32:46,950 - INFO - allennlp.common.params - dataset_reader.lazy = False
2018-11-13 21:32:46,951 - INFO - allennlp.common.params - dataset_reader.tables_directory = data/wikitables/
2018-11-13 21:32:46,951 - INFO - allennlp.common.params - dataset_reader.dpd_output_directory = data/wikitables/h-strict-dump-combined/
2018-11-13 21:32:46,951 - INFO - allennlp.common.params - dataset_reader.max_dpd_logical_forms = 10
2018-11-13 21:32:46,951 - INFO - allennlp.common.params - dataset_reader.sort_dpd_logical_forms = True
2018-11-13 21:32:46,951 - INFO - allennlp.common.params - dataset_reader.max_dpd_tries = 20
2018-11-13 21:32:46,951 - INFO - allennlp.common.params - dataset_reader.keep_if_no_dpd = False
2018-11-13 21:32:46,951 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.data.token_indexers.token_indexer.TokenIndexer'> from params {'type': 'single_id'} and extras {}
2018-11-13 21:32:46,951 - INFO - allennlp.common.params - dataset_reader.question_token_indexers.tokens.type = single_id
2018-11-13 21:32:46,951 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.data.token_indexers.single_id_token_indexer.SingleIdTokenIndexer'> from params {} and extras {}
2018-11-13 21:32:46,951 - INFO - allennlp.common.params - dataset_reader.question_token_indexers.tokens.namespace = tokens
2018-11-13 21:32:46,952 - INFO - allennlp.common.params - dataset_reader.question_token_indexers.tokens.lowercase_tokens = False
2018-11-13 21:32:46,952 - INFO - allennlp.common.params - dataset_reader.question_token_indexers.tokens.start_tokens = None
2018-11-13 21:32:46,952 - INFO - allennlp.common.params - dataset_reader.question_token_indexers.tokens.end_tokens = None
2018-11-13 21:32:46,952 - INFO - allennlp.common.params - dataset_reader.table_token_indexers = <allennlp.common.params.Params object at 0x7f9e84bc4da0>
2018-11-13 21:32:46,952 - INFO - allennlp.common.params - dataset_reader.use_table_for_vocab = False
2018-11-13 21:32:46,952 - INFO - allennlp.common.params - dataset_reader.linking_feature_extractors = None
2018-11-13 21:32:46,952 - INFO - allennlp.common.params - dataset_reader.include_table_metadata = False
2018-11-13 21:32:46,952 - INFO - allennlp.common.params - dataset_reader.max_table_tokens = None
2018-11-13 21:32:46,952 - INFO - allennlp.common.params - dataset_reader.output_agendas = False
***************** <allennlp.data.dataset_readers.semantic_parsing.wikitables.wikitables.WikiTablesDatasetReader object at 0x7f9e84bc4d68>
2018-11-13 21:32:47,561 - INFO - allennlp.commands.train - Using a separate dataset reader to load validation and test data.
2018-11-13 21:32:47,561 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.data.dataset_readers.dataset_reader.DatasetReader'> from params {'dpd_output_directory': 'data/wikitables/h-strict-dump-combined/', 'keep_if_no_dpd': True, 'lazy': False, 'question_token_indexers': {'tokens': {'type': 'single_id'}}, 'tables_directory': 'data/wikitables/', 'type': 'wikitables'} and extras {}
2018-11-13 21:32:47,561 - INFO - allennlp.common.params - validation_dataset_reader.type = wikitables
2018-11-13 21:32:47,562 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.data.dataset_readers.semantic_parsing.wikitables.wikitables.WikiTablesDatasetReader'> from params {'dpd_output_directory': 'data/wikitables/h-strict-dump-combined/', 'keep_if_no_dpd': True, 'lazy': False, 'question_token_indexers': {'tokens': {'type': 'single_id'}}, 'tables_directory': 'data/wikitables/'} and extras {}
2018-11-13 21:32:47,562 - INFO - allennlp.common.params - validation_dataset_reader.lazy = False
2018-11-13 21:32:47,562 - INFO - allennlp.common.params - validation_dataset_reader.tables_directory = data/wikitables/
2018-11-13 21:32:47,562 - INFO - allennlp.common.params - validation_dataset_reader.dpd_output_directory = data/wikitables/h-strict-dump-combined/
2018-11-13 21:32:47,562 - INFO - allennlp.common.params - validation_dataset_reader.max_dpd_logical_forms = 10
2018-11-13 21:32:47,562 - INFO - allennlp.common.params - validation_dataset_reader.sort_dpd_logical_forms = True
2018-11-13 21:32:47,562 - INFO - allennlp.common.params - validation_dataset_reader.max_dpd_tries = 20
2018-11-13 21:32:47,563 - INFO - allennlp.common.params - validation_dataset_reader.keep_if_no_dpd = True
2018-11-13 21:32:47,563 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.data.token_indexers.token_indexer.TokenIndexer'> from params {'type': 'single_id'} and extras {}
2018-11-13 21:32:47,563 - INFO - allennlp.common.params - validation_dataset_reader.question_token_indexers.tokens.type = single_id
2018-11-13 21:32:47,563 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.data.token_indexers.single_id_token_indexer.SingleIdTokenIndexer'> from params {} and extras {}
2018-11-13 21:32:47,563 - INFO - allennlp.common.params - validation_dataset_reader.question_token_indexers.tokens.namespace = tokens
2018-11-13 21:32:47,563 - INFO - allennlp.common.params - validation_dataset_reader.question_token_indexers.tokens.lowercase_tokens = False
2018-11-13 21:32:47,565 - INFO - allennlp.common.params - validation_dataset_reader.question_token_indexers.tokens.start_tokens = None
2018-11-13 21:32:47,568 - INFO - allennlp.common.params - validation_dataset_reader.question_token_indexers.tokens.end_tokens = None
2018-11-13 21:32:47,568 - INFO - allennlp.common.params - validation_dataset_reader.table_token_indexers = <allennlp.common.params.Params object at 0x7f9e84bc4710>
2018-11-13 21:32:47,568 - INFO - allennlp.common.params - validation_dataset_reader.use_table_for_vocab = False
2018-11-13 21:32:47,568 - INFO - allennlp.common.params - validation_dataset_reader.linking_feature_extractors = None
2018-11-13 21:32:47,568 - INFO - allennlp.common.params - validation_dataset_reader.include_table_metadata = False
2018-11-13 21:32:47,568 - INFO - allennlp.common.params - validation_dataset_reader.max_table_tokens = None
2018-11-13 21:32:47,568 - INFO - allennlp.common.params - validation_dataset_reader.output_agendas = False
2018-11-13 21:32:47,569 - INFO - allennlp.common.params - train_data_path = data/wikitables/data/random-split-1-train.examples
2018-11-13 21:32:47,569 - INFO - allennlp.commands.train - Reading training data from data/wikitables/data/random-split-1-train.examples
0it [00:00, ?it/s]^CTraceback (most recent call last):
  File "/home/v-dozhao/anaconda3/envs/py3.7torch/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/v-dozhao/anaconda3/envs/py3.7torch/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/v-dozhao/Work/allennlp/allennlp/run.py", line 18, in <module>
    main(prog="allennlp")
  File "/home/v-dozhao/Work/allennlp/allennlp/commands/__init__.py", line 72, in main
    args.func(args)
  File "/home/v-dozhao/Work/allennlp/allennlp/commands/train.py", line 111, in train_model_from_args
    args.force)
  File "/home/v-dozhao/Work/allennlp/allennlp/commands/train.py", line 142, in train_model_from_file
    return train_model(params, serialization_dir, file_friendly_logging, recover, force)
  File "/home/v-dozhao/Work/allennlp/allennlp/commands/train.py", line 288, in train_model
    all_datasets = datasets_from_params(params)
  File "/home/v-dozhao/Work/allennlp/allennlp/commands/train.py", line 160, in datasets_from_params
    train_data = dataset_reader.read(train_data_path)
  File "/home/v-dozhao/Work/allennlp/allennlp/data/dataset_readers/dataset_reader.py", line 73, in read
    instances = [instance for instance in Tqdm.tqdm(instances)]
  File "/home/v-dozhao/Work/allennlp/allennlp/data/dataset_readers/dataset_reader.py", line 73, in <listcomp>
    instances = [instance for instance in Tqdm.tqdm(instances)]
  File "/home/v-dozhao/anaconda3/envs/py3.7torch/lib/python3.7/site-packages/tqdm/_tqdm.py", line 979, in __iter__
    for obj in iterable:
  File "/home/v-dozhao/Work/allennlp/allennlp/data/dataset_readers/semantic_parsing/wikitables/wikitables.py", line 164, in _read
    yield from self._read_examples_file(file_path)
  File "/home/v-dozhao/Work/allennlp/allennlp/data/dataset_readers/semantic_parsing/wikitables/wikitables.py", line 217, in _read_examples_file
    dpd_output=sempre_forms)
  File "/home/v-dozhao/Work/allennlp/allennlp/data/dataset_readers/semantic_parsing/wikitables/wikitables.py", line 281, in text_to_instance
    max_table_tokens=self._max_table_tokens)
  File "/home/v-dozhao/Work/allennlp/allennlp/data/fields/knowledge_graph_field.py", line 106, in __init__
    self.entity_texts = tokenizer.batch_tokenize(entity_texts)
  File "/home/v-dozhao/Work/allennlp/allennlp/data/tokenizers/word_tokenizer.py", line 66, in batch_tokenize
    batched_words = self._word_splitter.batch_split_words(texts)
  File "/home/v-dozhao/Work/allennlp/allennlp/data/tokenizers/word_splitter.py", line 150, in batch_split_words
    for tokens in self.spacy.pipe(sentences, n_threads=-1)]
  File "/home/v-dozhao/Work/allennlp/allennlp/data/tokenizers/word_splitter.py", line 149, in <listcomp>
    return [_remove_spaces(tokens)
  File "/home/v-dozhao/anaconda3/envs/py3.7torch/lib/python3.7/site-packages/spacy/language.py", line 572, in pipe
    for doc in docs:
  File "pipeline.pyx", line 433, in pipe
  File "pipeline.pyx", line 438, in spacy.pipeline.Tagger.predict
  File "/home/v-dozhao/anaconda3/envs/py3.7torch/lib/python3.7/site-packages/thinc/neural/_classes/model.py", line 161, in __call__
    return self.predict(x)
  File "/home/v-dozhao/anaconda3/envs/py3.7torch/lib/python3.7/site-packages/thinc/api.py", line 55, in predict
    X = layer(X)
  File "/home/v-dozhao/anaconda3/envs/py3.7torch/lib/python3.7/site-packages/thinc/neural/_classes/model.py", line 161, in __call__
    return self.predict(x)
  File "/home/v-dozhao/anaconda3/envs/py3.7torch/lib/python3.7/site-packages/thinc/api.py", line 293, in predict
    X = layer(layer.ops.flatten(seqs_in, pad=pad))
  File "/home/v-dozhao/anaconda3/envs/py3.7torch/lib/python3.7/site-packages/thinc/neural/_classes/model.py", line 161, in __call__
    return self.predict(x)
  File "/home/v-dozhao/anaconda3/envs/py3.7torch/lib/python3.7/site-packages/thinc/api.py", line 55, in predict
    X = layer(X)
  File "/home/v-dozhao/anaconda3/envs/py3.7torch/lib/python3.7/site-packages/thinc/neural/_classes/resnet.py", line 15, in __call__
    return X + self._layers[0](X)
  File "/home/v-dozhao/anaconda3/envs/py3.7torch/lib/python3.7/site-packages/thinc/neural/_classes/model.py", line 161, in __call__
    return self.predict(x)
  File "/home/v-dozhao/anaconda3/envs/py3.7torch/lib/python3.7/site-packages/thinc/api.py", line 55, in predict
    X = layer(X)
  File "/home/v-dozhao/anaconda3/envs/py3.7torch/lib/python3.7/site-packages/thinc/neural/_classes/model.py", line 161, in __call__
    return self.predict(x)
  File "/home/v-dozhao/anaconda3/envs/py3.7torch/lib/python3.7/site-packages/thinc/neural/_classes/layernorm.py", line 44, in predict
    X = self.child.predict(X)
  File "/home/v-dozhao/anaconda3/envs/py3.7torch/lib/python3.7/site-packages/thinc/neural/_classes/maxout.py", line 60, in predict
    X__BOP = self.ops.batch_dot(X__BI, W)
KeyboardInterrupt
[INFO/MainProcess] process shutting down


Could you please have look? Thank you so much!

**Comment by matt-gardner** [comment]
That error message is a keyboard interrupt.  What was the actual problem you ran into?

**Comment by matt-gardner** [comment]
It looks like you have different data format than we do.  I have a huge directory that has one file per example, called `nt-1.gz`, and the contents of that file is logical forms, one per line, with no header like you have.  If you have a different file format you'll have to modify [these lines](https://github.com/allenai/allennlp/blob/43243acf4e91ba471923624bd48c9c9ec72332bf/allennlp/data/dataset_readers/semantic_parsing/wikitables/wikitables.py#L189-L202) accordingly.

**Comment by YoPatapon** [comment]
I see. Can you provide a download link of your dpd files? Because the old link is invalid now.

**Comment by matt-gardner** [comment]
I don't have them anywhere that they can be publicly downloaded, and I'm not in a position to put them somewhere right now.  I'd recommend just looking at your data and modifying the code to read it properly.

**Comment by YoPatapon** [comment]
It seems like the program can run now. However, I have a few more questions. 
1) The data format of the dpd file is much different from than you have, each line that contains the logic form also contains the value and type information like:

> (derivation (formula (- (min ((reverse fb:cell.cell.number) ((reverse fb:row.row.year) (fb:row.row.league fb:cell.usl_first_division)))) (count ((reverse fb:row.row.division) (fb:type.object.type fb:type.row))))) (value (list (number 2004))) (type fb:type.number) (canonicalUtterance $ROOT:8))

I don't know what the format it is so I manually extract the logic form out using string operation. Is there a more convenient way to do such thing?

2) When the program is running, some parsing errors occurred, like:

> 4585it [38:40,  2.65it/s]2018-11-14 15:44:45,144 - ERROR - allennlp.data.dataset_readers.semantic_parsing.wikitables.wikitables - Parsing error: Encountered un-mapped name: 20, skipping logical form

> 2018-11-14 15:44:41,438 - ERROR - allennlp.data.dataset_readers.semantic_parsing.wikitables.wikitables - Parsing error: Encountered un-mapped name: 20, skipping logical form

Is this a normal situation?

**Comment by YoPatapon** [comment]
I preprocessed the wikitables dataset with the provided preprocessing script into ".jsonl" files and try to run the program. However, I met such error with the default parameter setting in the jsonnet file:

>   File "/home/v-dozhao/anaconda3/envs/py3.7torch/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/v-dozhao/anaconda3/envs/py3.7torch/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/v-dozhao/Work/allennlp/allennlp/run.py", line 18, in <module>
    main(prog="allennlp")
  File "/home/v-dozhao/Work/allennlp/allennlp/commands/__init__.py", line 72, in main
    args.func(args)
  File "/home/v-dozhao/Work/allennlp/allennlp/commands/train.py", line 111, in train_model_from_args
    args.force)
  File "/home/v-dozhao/Work/allennlp/allennlp/commands/train.py", line 142, in train_model_from_file
    return train_model(params, serialization_dir, file_friendly_logging, recover, force)
  File "/home/v-dozhao/Work/allennlp/allennlp/commands/train.py", line 352, in train_model
    metrics = trainer.train()
  File "/home/v-dozhao/Work/allennlp/allennlp/training/trainer.py", line 755, in train
    train_metrics = self._train_epoch(epoch)
  File "/home/v-dozhao/Work/allennlp/allennlp/training/trainer.py", line 495, in _train_epoch
    loss = self.batch_loss(batch, for_training=True)
  File "/home/v-dozhao/Work/allennlp/allennlp/training/trainer.py", line 430, in batch_loss
    output_dict = self.model(**batch)
  File "/home/v-dozhao/anaconda3/envs/py3.7torch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/v-dozhao/Work/allennlp/allennlp/models/semantic_parsing/wikitables/wikitables_mml_semantic_parser.py", line 199, in forward
    (target_action_sequences, target_mask))
  File "/home/v-dozhao/Work/allennlp/allennlp/state_machines/trainers/maximum_marginal_likelihood.py", line 49, in decode
    beam_search = ConstrainedBeamSearch(self._beam_size, targets, target_mask)
  File "/home/v-dozhao/Work/allennlp/allennlp/state_machines/constrained_beam_search.py", line 58, in __init__
    self._allowed_transitions = util.construct_prefix_tree(allowed_sequences, allowed_sequence_mask)
  File "/home/v-dozhao/Work/allennlp/allennlp/state_machines/util.py", line 30, in construct_prefix_tree
    assert targets.dim() == 3, "targets tensor needs to be batched!"
AttributeError: 'NoneType' object has no attribute 'dim'

I modified the batch size in the config file to 64 and I met a new error now:

>  File "/home/v-dozhao/anaconda3/envs/py3.7torch/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/v-dozhao/anaconda3/envs/py3.7torch/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/v-dozhao/Work/allennlp/allennlp/run.py", line 18, in <module>
    main(prog="allennlp")
  File "/home/v-dozhao/Work/allennlp/allennlp/commands/__init__.py", line 72, in main
    args.func(args)
  File "/home/v-dozhao/Work/allennlp/allennlp/commands/train.py", line 111, in train_model_from_args
    args.force)
  File "/home/v-dozhao/Work/allennlp/allennlp/commands/train.py", line 142, in train_model_from_file
    return train_model(params, serialization_dir, file_friendly_logging, recover, force)
  File "/home/v-dozhao/Work/allennlp/allennlp/commands/train.py", line 352, in train_model
    metrics = trainer.train()
  File "/home/v-dozhao/Work/allennlp/allennlp/training/trainer.py", line 755, in train
    train_metrics = self._train_epoch(epoch)
  File "/home/v-dozhao/Work/allennlp/allennlp/training/trainer.py", line 485, in _train_epoch
    for batch in train_generator_tqdm:
  File "/home/v-dozhao/anaconda3/envs/py3.7torch/lib/python3.7/site-packages/tqdm/_tqdm.py", line 979, in __iter__
    for obj in iterable:
  File "/home/v-dozhao/Work/allennlp/allennlp/data/iterators/data_iterator.py", line 143, in __call__
    for batch in batches:
  File "/home/v-dozhao/Work/allennlp/allennlp/data/iterators/basic_iterator.py", line 29, in _create_batches
    batch = Batch(possibly_smaller_batches)
  File "/home/v-dozhao/Work/allennlp/allennlp/data/dataset.py", line 33, in __init__
    self._check_types()
  File "/home/v-dozhao/Work/allennlp/allennlp/data/dataset.py", line 44, in _check_types
    raise ConfigurationError("You cannot construct a Batch with non-homogeneous Instances.")
allennlp.common.checks.ConfigurationError: 'You cannot construct a Batch with non-homogeneous Instances.'

Did I miss something?
