### ISSUE TITLE
Vocabulary loading includes hidden files

### ISSUE THREAD

**Issue by OyvindTafjord** [allenai/allennlp#1826]
Not exactly a bug, but when loading a vocabulary from files, it automatically loads every file in the `vocabulary` directory. This might include hidden files (such as those starting with a period in the filename) which, say, MacOS has decided to insert. It would probably be better to avoid this.

**Comment by schmmd** [comment]
@nikett  also hit this issue (excuse the l[ink into our internal Slack](https://allenai.slack.com/archives/C7J5GABEX/p1532397375000048).

**Comment by schmmd** [comment]
From @bhavanadalvi:

1. Download a model from beaker file by file
2. create a model directory with config.json, weights.th and vocabulary folder
3. create model.tar.gz from this directory
allennlp gives error while loading model.tar.gz but does not give error if I just give the path to the model directory (unzipped)

**Comment by schmmd** [comment]
I was able to repro this problem by downloading the BiDAF model, `untar`-ing it, `retar`-ing it, and trying to make a prediction.

```
allennlp predict bidaf.tar.gz mc-examples.jsonl
2018-11-01 12:49:35,330 - INFO - allennlp.common.registrable - instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
2018-11-01 12:49:35,331 - INFO - allennlp.common.registrable - instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
2018-11-01 12:49:35,332 - INFO - allennlp.common.registrable - instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
2018-11-01 12:49:35,333 - INFO - allennlp.common.registrable - instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
2018-11-01 12:49:35,639 - INFO - allennlp.models.archival - loading archive file bidaf.tar.gz
2018-11-01 12:49:35,641 - INFO - allennlp.models.archival - extracting archive file bidaf.tar.gz to temp dir /var/folders/v5/tlk1sh3d0l94fcmz10vtzmyh0000gn/T/tmpjjxrx47v
Traceback (most recent call last):
  File "/Users/michael/miniconda3/envs/allennlp/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/michael/miniconda3/envs/allennlp/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/michael/hack/allenai/allennlp/allennlp/run.py", line 18, in <module>
    main(prog="allennlp")
  File "/Users/michael/hack/allenai/allennlp/allennlp/commands/__init__.py", line 72, in main
    args.func(args)
  File "/Users/michael/hack/allenai/allennlp/allennlp/commands/predict.py", line 179, in _predict
    predictor = _get_predictor(args)
  File "/Users/michael/hack/allenai/allennlp/allennlp/commands/predict.py", line 99, in _get_predictor
    overrides=args.overrides)
  File "/Users/michael/hack/allenai/allennlp/allennlp/models/archival.py", line 141, in load_archive
    config = Params.from_file(os.path.join(serialization_dir, CONFIG_NAME), overrides)
  File "/Users/michael/hack/allenai/allennlp/allennlp/common/params.py", line 362, in from_file
    file_dict = json.loads(evaluate_file(params_file, ext_vars=ext_vars))
RuntimeError: STATIC ERROR: /var/folders/v5/tlk1sh3d0l94fcmz10vtzmyh0000gn/T/tmpjjxrx47v/config.json:1:1: Could not lex the character code 31
```

**Comment by schmmd** [comment]
Related: https://stackoverflow.com/questions/8766730/tar-command-in-mac-os-x-adding-hidden-files-why
