### ISSUE TITLE
RecursionError: maximum recursion depth exceeded in __instancecheck__

### ISSUE THREAD

**Issue by jageshmaharjan** [allenai/allennlp#1930]
**Describe the bug**
Suddenly, started to get this error from today. It was working all fine until yesterday.

**To Reproduce**
Steps to reproduce the behavior
1. Go to '...': N/A
2. Click on '....': N/A
3. Scroll down to '....' : N/A
  while running this in python 3.x console,
  `predictor = Predictor.from_path("https://s3-us-west-2.amazonaws.com/allennlp/models/bidaf-model-2017.09.15-charpad.tar.gz")`
  I got this error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/allennlp/predictors/predictor.py", line 100, in from_path
    return Predictor.from_archive(load_archive(archive_path), predictor_name)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/allennlp/models/archival.py", line 153, in load_archive
    cuda_device=cuda_device)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/allennlp/models/model.py", line 318, in load
    return cls.by_name(model_type)._load(config, serialization_dir, weights_file, cuda_device)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/allennlp/models/model.py", line 265, in _load
    model = Model.from_params(vocab=vocab, params=model_params)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/allennlp/common/from_params.py", line 246, in from_params
    return subclass.from_params(params=params, **extras)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/allennlp/common/from_params.py", line 257, in from_params
    kwargs = create_kwargs(cls, params, **extras)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/allennlp/common/from_params.py", line 113, in create_kwargs
    annotation = remove_optional(param.annotation)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/allennlp/common/from_params.py", line 81, in remove_optional
    if origin == Union and len(args) == 2 and args[1] == type(None):
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/typing.py", line 760, in __eq__
    return self._subs_tree() == other
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/typing.py", line 760, in __eq__
    return self._subs_tree() == other
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/typing.py", line 760, in __eq__
    return self._subs_tree() == other
  [Previous line repeated 242 more times]
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/typing.py", line 759, in __eq__
    if not isinstance(other, _Union):
RecursionError: maximum recursion depth exceeded in __instancecheck__

```

**Expected behavior**
should load the model

**System (please complete the following information):**
 - OS: [e.g. OSX, Linux]: Ubuntu 16.04
 - Python version: [if it's not 3.6.1 or later, that's probably your problem]: 3.6.1
 - AllenNLP version: [e.g. v0.7.0, or "I installed from master"]: default stable version `pip install allennlp`
 - PyTorch version: (if you installed it yourself): No

**Comment by matt-gardner** [comment]
Are you _sure_ that you're using python 3.6.1?  We've seen exactly this issue with 3.6.0, which was fixed in 3.6.1.  We haven't seen it with 3.6.1 or later.

**Comment by nelson-liu** [comment]
I’d add: can you give us the version of allennlp you’re using? In fixing the bug, we also added a check to the code that requires python 3.6.1 or higher.

**Comment by jageshmaharjan** [comment]
oops, the conda environment I was using appeared to be version 3.6.0 but not higher than 3.6.0. Sorry, my bad. It worked with python version 3.6.1 and above. 
Thanks @matt-gardner  and @nelson-liu .
