### ISSUE TITLE
LabelField Indexing Error

### ISSUE THREAD

**Issue by ggordonhall** [allenai/allennlp#1998]
I've written a rough class to read and index a text classification dataset so that it can be used with pretrained ELMo embeddings:

```
import pandas as pd
from allennlp.data import Instance
from allennlp.data.fields import TextField, LabelField
from allennlp.data.tokenizers import WordTokenizer
from allennlp.data.token_indexers.elmo_indexer import ELMoTokenCharactersIndexer
from allennlp.data.vocabulary import Vocabulary
from allennlp.data.dataset import Batch
from allennlp.data.dataset_readers import DatasetReader

class TabularReader(DatasetReader):
    def __init__(self, text_name, label_name, sep, batch_size):
        super().__init__(lazy=False)
        self.sep = sep
        self.text_name = text_name
        self.label_name = label_name
        self.batch_size = batch_size

        self.vocab = Vocabulary()
        self.tokeniser = WordTokenizer()
        self.token_indexers = {"character_ids": ELMoTokenCharactersIndexer()}

    def text_to_instance(self, tokens, label):
        sentence_field = TextField(tokens, self.token_indexers)
        label_field = LabelField(label=label, label_namespace="labels")
        fields = {"sentence": sentence_field, "labels": label_field}
        return Instance(fields)

    def _read(self, file_path):
        df = pd.read_csv(file_path, self.sep)
        text_col, label_col = df[self.text_name], df[self.label_name]

        instances = []
        for idx, sentence in enumerate(text_col):
            instances.append(self.text_to_instance(
                self.tokeniser.tokenize(sentence), label_col[idx]))

            if (idx + 1) % self.batch_size == 0:
                batch = Batch(instances)
                instances = []
                batch.index_instances(self.vocab)
                yield batch.as_tensor_dict()
```
However it throws a confusing OOV `KeyError` when it tries to index the `LabelField`:

```
Traceback (most recent call last):
  File "test_elmo.py", line 56, in <module>
    train_dataset = reader.read("data/train.tsv")
  File "/Users/gabrielgordon-hall/anaconda/lib/python3.6/site-packages/allennlp/data/dataset_readers/dataset_reader.py", line 73, in read
    instances = [instance for instance in Tqdm.tqdm(instances)]
  File "/Users/gabrielgordon-hall/anaconda/lib/python3.6/site-packages/allennlp/data/dataset_readers/dataset_reader.py", line 73, in <listcomp>
    instances = [instance for instance in Tqdm.tqdm(instances)]
  File "/Users/gabrielgordon-hall/anaconda/lib/python3.6/site-packages/tqdm/_tqdm.py", line 937, in __iter__
    for obj in iterable:
  File "test_elmo.py", line 47, in _read
    batch.index_instances(self.vocab)
  File "/Users/gabrielgordon-hall/anaconda/lib/python3.6/site-packages/allennlp/data/dataset.py", line 155, in index_instances
    instance.index_fields(vocab)
  File "/Users/gabrielgordon-hall/anaconda/lib/python3.6/site-packages/allennlp/data/instance.py", line 60, in index_fields
    field.index(vocab)
  File "/Users/gabrielgordon-hall/anaconda/lib/python3.6/site-packages/allennlp/data/fields/label_field.py", line 83, in index
    self._label_id = vocab.get_token_index(self.label, self._label_namespace)  # type: ignore
  File "/Users/gabrielgordon-hall/anaconda/lib/python3.6/site-packages/allennlp/data/vocabulary.py", line 591, in get_token_index
    return self._token_to_index[namespace][self._oov_token]
KeyError: '@@UNKNOWN@@'
```
Why does the `self._token_to_index` throw this error? Surely it should just add the token to the `__NamespaceDependentDefaultDict`? Or am I barking up the wrong tree?

**Comment by joelgrus** [comment]
you have to create the vocabulary (from instances, typically) before you can use it to index things -- otherwise it doesn't know what your labels / tokens are. 

In particular, neither the Vocabulary nor the indexing should live in your dataset reader.

The typical workflow looks something like

```
reader = MyDatasetReader()
instances = reader.read(my_file_path)
vocab = Vocabulary.from_instances(instances)
iterator = SomeDataIterator()
iterator.index_with(vocab)

for instance in iterator(instances):
    ...
```

but if you use our `Trainer` all of that should happen automatically.

I believe making this change should fix your problem, please re-open if it doesn't.
