### ISSUE TITLE
EVALB errors when using pip install

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp#2017]
@nelson-liu recently made [a PR to build EVALB if it doesn't exist](https://github.com/allenai/allennlp/pull/1964) so he could train the SRL model via Docker.  He succeeded in doing this from the main Dockerfile, but it still doesn't work when installing AllenNLP via pip.

EVALB is included at `/usr/local/lib/python3.6/site-packages/allennlp/tools/EVALB/` and it seems to be compiled, but the process errors out.

```
2018-11-05T23:12:22.831824463Z	rm -f evalb
2018-11-05T23:12:22.833699671Z	gcc -Wall -g -o evalb evalb.c
2018-11-05T23:12:22.972013565Z	evalb.c: In function ‘main’:
2018-11-05T23:12:22.972099997Z	evalb.c:379:22: warning: pointer targets in passing argument 1 of ‘fgets’ differ in signedness [-Wpointer-sign]
2018-11-05T23:12:22.97212103Z	     for(Line=1;fgets(buff,5000,fd1)!=NULL;Line++){
2018-11-05T23:12:22.972124759Z	                      ^
2018-11-05T23:12:22.972199025Z	In file included from evalb.c:21:0:
2018-11-05T23:12:22.97220439Z	/usr/include/stdio.h:622:14: note: expected ‘char * __restrict__’ but argument is of type ‘unsigned char *’
2018-11-05T23:12:22.97221632Z	 extern char *fgets (char *__restrict __s, int __n, FILE *__restrict __stream)
2018-11-05T23:12:22.972219117Z	              ^
2018-11-05T23:12:22.972221492Z	evalb.c:386:9: warning: pointer targets in passing argument 1 of ‘strcpy’ differ in signedness [-Wpointer-sign]
2018-11-05T23:12:22.972224103Z	  strcpy(buff1,buff);
2018-11-05T23:12:22.972226475Z	         ^
2018-11-05T23:12:22.972323105Z	In file included from evalb.c:24:0:
2018-11-05T23:12:22.972336209Z	/usr/include/string.h:129:14: note: expected ‘char * __restrict__’ but argument is of type ‘unsigned char *’
2018-11-05T23:12:22.972340073Z	 extern char *strcpy (char *__restrict __dest, const char *__restrict __src)
2018-11-05T23:12:22.972342889Z	              ^
2018-11-05T23:12:22.972345497Z	evalb.c:386:15: warning: pointer targets in passing argument 2 of ‘strcpy’ differ in signedness [-Wpointer-sign]
2018-11-05T23:12:22.972348423Z	  strcpy(buff1,buff);
2018-11-05T23:12:22.972350922Z	               ^
2018-11-05T23:12:22.972353329Z	In file included from evalb.c:24:0:
2018-11-05T23:12:22.97235596Z	/usr/include/string.h:129:14: note: expected ‘const char * __restrict__’ but argument is of type ‘unsigned char *’
2018-11-05T23:12:22.972358683Z	 extern char *strcpy (char *__restrict __dest, const char *__restrict __src)
2018-11-05T23:12:22.97236129Z	              ^
2018-11-05T23:12:22.97236375Z	evalb.c:389:11: warning: pointer targets in passing argument 1 of ‘fgets’ differ in signedness [-Wpointer-sign]
2018-11-05T23:12:22.972366852Z	  if(fgets(buff,5000,fd2)==NULL){
2018-11-05T23:12:22.972369267Z	           ^
2018-11-05T23:12:22.972371925Z	In file included from evalb.c:21:0:
2018-11-05T23:12:22.972374333Z	/usr/include/stdio.h:622:14: note: expected ‘char * __restrict__’ but argument is of type ‘unsigned char *’
2018-11-05T23:12:22.972377617Z	 extern char *fgets (char *__restrict __s, int __n, FILE *__restrict __stream)
2018-11-05T23:12:22.972380067Z	              ^
2018-11-05T23:12:22.972423646Z	evalb.c:404:14: warning: pointer targets in passing argument 1 of ‘fgets’ differ in signedness [-Wpointer-sign]
2018-11-05T23:12:22.972428396Z	     if(fgets(buff,5000,fd2)!=NULL){
2018-11-05T23:12:22.972430816Z	              ^
2018-11-05T23:12:22.972433169Z	In file included from evalb.c:21:0:
2018-11-05T23:12:22.972435539Z	/usr/include/stdio.h:622:14: note: expected ‘char * __restrict__’ but argument is of type ‘unsigned char *’
2018-11-05T23:12:22.97243808Z	 extern char *fgets (char *__restrict __s, int __n, FILE *__restrict __stream)
2018-11-05T23:12:22.972440699Z	              ^
2018-11-05T23:12:22.974330514Z	evalb.c: In function ‘read_line’:
2018-11-05T23:12:22.97434194Z	evalb.c:659:11: warning: variable ‘n’ set but not used [-Wunused-but-set-variable]
2018-11-05T23:12:22.97435082Z	     int   n;              /* temporary remembering the position */
2018-11-05T23:12:22.974354915Z	           ^
2018-11-05T23:12:22.97471461Z	evalb.c: In function ‘calc_result’:
2018-11-05T23:12:22.974724145Z	evalb.c:879:23: warning: pointer targets in passing argument 2 of ‘strncpy’ differ in signedness [-Wpointer-sign]
2018-11-05T23:12:22.974727252Z	        strncpy(my_buf,buf1+bracket1[i].buf_start,l);
2018-11-05T23:12:22.974730054Z	                       ^
2018-11-05T23:12:22.974772004Z	In file included from evalb.c:24:0:
2018-11-05T23:12:22.974779845Z	/usr/include/string.h:132:14: note: expected ‘const char * __restrict__’ but argument is of type ‘unsigned char *’
2018-11-05T23:12:22.974782984Z	 extern char *strncpy (char *__restrict __dest,
2018-11-05T23:12:22.974785658Z	              ^
2018-11-05T23:12:22.974866489Z	evalb.c:893:17: warning: pointer targets in passing argument 2 of ‘strncpy’ differ in signedness [-Wpointer-sign]
2018-11-05T23:12:22.974873456Z	  strncpy(my_buf,buf1+bracket1[i].buf_start,l);
2018-11-05T23:12:22.974876275Z	                 ^
2018-11-05T23:12:22.974878899Z	In file included from evalb.c:24:0:
2018-11-05T23:12:22.974881364Z	/usr/include/string.h:132:14: note: expected ‘const char * __restrict__’ but argument is of type ‘unsigned char *’
2018-11-05T23:12:22.974884345Z	 extern char *strncpy (char *__restrict __dest,
2018-11-05T23:12:22.974886886Z	              ^
2018-11-05T23:12:22.974992069Z	evalb.c:905:17: warning: pointer targets in passing argument 2 of ‘strncpy’ differ in signedness [-Wpointer-sign]
2018-11-05T23:12:22.974999875Z	  strncpy(my_buf,buf+bracket2[j].buf_start,l);
2018-11-05T23:12:22.975002451Z	                 ^
2018-11-05T23:12:22.975004865Z	In file included from evalb.c:24:0:
2018-11-05T23:12:22.975007242Z	/usr/include/string.h:132:14: note: expected ‘const char * __restrict__’ but argument is of type ‘unsigned char *’
2018-11-05T23:12:22.975009908Z	 extern char *strncpy (char *__restrict __dest,
2018-11-05T23:12:22.975012444Z	              ^
2018-11-05T23:12:22.975167579Z	evalb.c:933:22: warning: pointer targets in passing argument 2 of ‘strncpy’ differ in signedness [-Wpointer-sign]
2018-11-05T23:12:22.975175169Z	       strncpy(my_buf,buf1+bracket1[i].buf_start,l);
2018-11-05T23:12:22.975177902Z	                      ^
2018-11-05T23:12:22.975180615Z	In file included from evalb.c:24:0:
2018-11-05T23:12:22.975183218Z	/usr/include/string.h:132:14: note: expected ‘const char * __restrict__’ but argument is of type ‘unsigned char *’
2018-11-05T23:12:22.975186157Z	 extern char *strncpy (char *__restrict __dest,
2018-11-05T23:12:22.975188828Z	              ^
2018-11-05T23:12:23.122217168Z	Traceback (most recent call last):
2018-11-05T23:12:23.12223291Z	  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
2018-11-05T23:12:23.122245764Z	    "__main__", mod_spec)
2018-11-05T23:12:23.122248658Z	  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
2018-11-05T23:12:23.122251412Z	    exec(code, run_globals)
2018-11-05T23:12:23.12225381Z	  File "/usr/local/lib/python3.6/site-packages/allennlp/run.py", line 18, in <module>
2018-11-05T23:12:23.122256982Z	    main(prog="allennlp")
2018-11-05T23:12:23.122259481Z	  File "/usr/local/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 72, in main
2018-11-05T23:12:23.122262242Z	    args.func(args)
2018-11-05T23:12:23.122264615Z	  File "/usr/local/lib/python3.6/site-packages/allennlp/commands/train.py", line 111, in train_model_from_args
2018-11-05T23:12:23.122267368Z	    args.force)
2018-11-05T23:12:23.122269744Z	  File "/usr/local/lib/python3.6/site-packages/allennlp/commands/train.py", line 142, in train_model_from_file
2018-11-05T23:12:23.122278644Z	    return train_model(params, serialization_dir, file_friendly_logging, recover, force)
2018-11-05T23:12:23.12228115Z	  File "/usr/local/lib/python3.6/site-packages/allennlp/commands/train.py", line 351, in train_model
2018-11-05T23:12:23.122283984Z	    metrics = trainer.train()
2018-11-05T23:12:23.12228644Z	  File "/usr/local/lib/python3.6/site-packages/allennlp/training/trainer.py", line 757, in train
2018-11-05T23:12:23.122289024Z	    val_loss, num_batches = self._validation_loss()
2018-11-05T23:12:23.122291564Z	  File "/usr/local/lib/python3.6/site-packages/allennlp/training/trainer.py", line 710, in _validation_loss
2018-11-05T23:12:23.122294204Z	    loss = self.batch_loss(batch, for_training=False)
2018-11-05T23:12:23.122296722Z	  File "/usr/local/lib/python3.6/site-packages/allennlp/training/trainer.py", line 430, in batch_loss
2018-11-05T23:12:23.122299384Z	    output_dict = self.model(**batch)
2018-11-05T23:12:23.122301854Z	  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
2018-11-05T23:12:23.122304751Z	    result = self.forward(*input, **kwargs)
2018-11-05T23:12:23.12230725Z	  File "/usr/local/lib/python3.6/site-packages/allennlp/models/constituency_parser.py", line 238, in forward
2018-11-05T23:12:23.122309954Z	    self._evalb_score(predicted_trees, batch_gold_trees)
2018-11-05T23:12:23.122312324Z	  File "/usr/local/lib/python3.6/site-packages/allennlp/training/metrics/evalb_bracketing_scorer.py", line 80, in __call__
2018-11-05T23:12:23.122314927Z	    self._evalb_program_path, compile_command))
2018-11-05T23:12:23.122317998Z	allennlp.common.checks.ConfigurationError: "You must compile the EVALB scorer before using it. Run 'make' in the 'scripts/EVALB/evalb' directory or run: python -c 'from allennlp.training.metrics import EvalbBracketingScorer; EvalbBracketingScorer.compile_evalb()'"
```

I'm putting together a repro.

**Comment by schmmd** [comment]
I added some logging to troubleshoot further: https://github.com/allenai/allennlp/pull/2018

**Comment by schmmd** [comment]
The constituency parser config specified a specific path to evalb that didn't match the default.  AllenNLP compiled at the default path but looked at the specified path.

```
2018-11-07 17:42:55,305 - WARNING - allennlp.training.metrics.evalb_bracketing_scorer - EVALB not found at scripts/EVALB/evalb.  Attempting to compile it.
2018-11-07 17:42:55,306 - INFO - allennlp.training.metrics.evalb_bracketing_scorer - Compiling EVALB by running make in /usr/local/lib/python3.6/site-packages/allennlp/tools/EVALB.
...
allennlp.common.checks.ConfigurationError: "EVALB still not found at scripts/EVALB/evalb. You must compile the EVALB scorer before using it. Run 'make' in the 'scripts/EVALB/evalb' directory or run: python -c 'from allennlp.training.metrics import EvalbBracketingScorer; EvalbBracketingScorer.compile_evalb()'"
```
