### ISSUE TITLE
allennlp.common.checks.ConfigurationError: 'vocab should be None'

### ISSUE THREAD

**Issue by susht3** [allenai/allennlp#2073]
i  ensemble for dialog_qa，but i get the error:

Traceback (most recent call last):
  File "/home/susht3/local/anaconda3/envs/susht/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/susht3/local/anaconda3/envs/susht/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/susht3/local/anaconda3/envs/susht/lib/python3.6/site-packages/allennlp/run.py", line 18, in <module>
    main(prog="allennlp")
  File "/home/susht3/local/anaconda3/envs/susht/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 72, in main
    args.func(args)
  File "/home/susht3/local/anaconda3/envs/susht/lib/python3.6/site-packages/allennlp/commands/train.py", line 111, in train_model_from_args
    args.force)
  File "/home/susht3/local/anaconda3/envs/susht/lib/python3.6/site-packages/allennlp/commands/train.py", line 142, in train_model_from_file
    return train_model(params, serialization_dir, file_friendly_logging, recover, force)
  File "/home/susht3/local/anaconda3/envs/susht/lib/python3.6/site-packages/allennlp/commands/train.py", line 298, in train_model
    model = Model.from_params(vocab=vocab, params=params.pop('model'))
  File "/home/susht3/local/anaconda3/envs/susht/lib/python3.6/site-packages/allennlp/common/from_params.py", line 274, in from_params
    return subclass.from_params(params=params, **extras)
  File "/home/susht3/workspace/allen/v8_ensemble/dialog_ensemble.py", line 118, in from_params
    raise ConfigurationError("vocab should be None")
allennlp.common.checks.ConfigurationError: 'vocab should be None'

**Comment by DeNeutoy** [comment]
Unfortunately you cannot currently train an ensemble in allennlp. The ensemble class should be used to combine existing pretrained models. Also this error is being raised in code outside of the library so it's going to be hard to help.
