### ISSUE TITLE
How to evaluate on the entire dev set of wikitables?

### ISSUE THREAD

**Issue by YoPatapon** [allenai/allennlp#2086]
I trained the mml parser with the filtered logical forms and evaluated on the random-split-1-dev. The accuracy was 45.9%. I noticed the dev accuracy is only the evaluated on the portion of instances that have dpd outputs. If I want to evaluate on the entire dev set and change the field "keep_if_no_dpd" to "true". It would raise an error. So, I have two questions:

1) In the dev set of random split 1, only 1746 out of 2831 instances have dpd outputs, if we consider the entire set, the accuracy will drop significantly and not even close to the best accuracy you reported. How can I reach that accuracy?

2) How can I evaluate on the entire set without raising errors?

Below is the error message raised when "keep_if_no_dpd" is true.

> ]Traceback (most recent call last):
  File "/home/v-dozhao/anaconda3/envs/py3.6torch/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/v-dozhao/anaconda3/envs/py3.6torch/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/v-dozhao/Experiments/allennlp/allennlp/run.py", line 18, in <module>
    main(prog="allennlp")
  File "/home/v-dozhao/Experiments/allennlp/allennlp/commands/__init__.py", line 72, in main
    args.func(args)
  File "/home/v-dozhao/Experiments/allennlp/allennlp/commands/evaluate.py", line 159, in evaluate_from_args
    metrics = evaluate(model, instances, iterator, args.cuda_device)
  File "/home/v-dozhao/Experiments/allennlp/allennlp/commands/evaluate.py", line 106, in evaluate
    for batch in generator_tqdm:
  File "/home/v-dozhao/anaconda3/envs/py3.6torch/lib/python3.6/site-packages/tqdm/_tqdm.py", line 979, in __iter__
    for obj in iterable:
  File "/home/v-dozhao/Experiments/allennlp/allennlp/data/iterators/data_iterator.py", line 143, in __call__
    for batch in batches:
  File "/home/v-dozhao/Experiments/allennlp/allennlp/data/iterators/basic_iterator.py", line 29, in _create_batches
    batch = Batch(possibly_smaller_batches)
  File "/home/v-dozhao/Experiments/allennlp/allennlp/data/dataset.py", line 33, in __init__
    self._check_types()
  File "/home/v-dozhao/Experiments/allennlp/allennlp/data/dataset.py", line 44, in _check_types
    raise ConfigurationError("You cannot construct a Batch with non-homogeneous Instances.")
allennlp.common.checks.ConfigurationError: 'You cannot construct a Batch with non-homogeneous Instances.'

**System (please complete the following information):**
 - OS: Linux
 - Python version: 3.6.1
 - AllenNLP version: I installed from master
 - PyTorch version: 0.4.1

**Comment by matt-gardner** [comment]
You need to set that flag only for the validation data: https://github.com/allenai/allennlp/blob/master/training_config/wikitables_parser.jsonnet#L19

**Comment by YoPatapon** [comment]
Yes, I only set the flag for the validation data, and the error raised.
For evaluation, I modified the same field in the config file of trained model. The same error raised.

**Comment by matt-gardner** [comment]
I was trying to figure out why we never ran into this issue.  I just figured it out - we always just used batch size of 1, so we didn't have this problem.  To solve the issue, make sure that your dataset reader makes an empty list field for `target_action_sequences` even when there is no DPD output.

**Comment by matt-gardner** [comment]
Closing due to inactivity, and because we're updating the wikitables model anyway.
