### ISSUE TITLE
Can't create a predictor that depends on files_to_archive

### ISSUE THREAD

**Issue by vlthr** [allenai/allennlp#2180]
**Describe the bug**
I am trying to reconstruct a model and create a predictor from an archive as follows:
```python
archive = load_archive("./model.tar.gz")
predictor = Predictor.from_archive(archive, "textcat")
```
The model uses a DatasetReader whose tokenizer (and TokenIndexer) loads a file. I am able to include that file in `Params.files_to_archive`, and have verified that they are created in the temporary folder where the archive is extracted. 

However - if I'm understanding this correctly - since `load_archive` cleans up the temporary folder before returning, `Predictor.from_params` fails when trying to recreate the DatasetReader.

```
Traceback (most recent call last):
  ...
  File "server.py", line 36, in __init__
    predictor = Predictor.from_archive(archive, "textcat")
  File "/Users/vlthr/build/allennlp/allennlp/predictors/predictor.py", line 127, in from_archive
    dataset_reader = DatasetReader.from_params(dataset_reader_params)
  File "/Users/vlthr/build/allennlp/allennlp/common/from_params.py", line 274, in from_params
    return subclass.from_params(params=params, **extras)
  File "/Users/vlthr/build/allennlp/allennlp/common/from_params.py", line 285, in from_params
    kwargs = create_kwargs(cls, params, **extras)
  File "/Users/vlthr/build/allennlp/allennlp/common/from_params.py", line 182, in create_kwargs
    value_dict[key] = value_cls.from_params(params=value_params, **extras)
  File "/Users/vlthr/build/allennlp/allennlp/common/from_params.py", line 274, in from_params
    return subclass.from_params(params=params, **extras)
  File "./submodules/allen_utils/data/token_indexers/sentencepiece_indexer.py", line 92, in from_params
    params.add_file_to_archive("model_path")
  File "/Users/vlthr/build/allennlp/allennlp/common/params.py", line 157, in add_file_to_archive
    self.files_to_archive[f"{self.history}{name}"] = cached_path(self.get(name))
  File "/Users/vlthr/build/allennlp/allennlp/common/file_utils.py", line 103, in cached_path
    raise FileNotFoundError("file {} not found".format(url_or_filename))
FileNotFoundError: file /var/folders/_r/szy7s3dd7p7cl0gh5w99sf100000gn/T/tmptb4kzi3o/fta/dataset_reader.token_indexers.tokens.model_path not found

```

**To Reproduce**
Steps to reproduce the behavior
1. Create a model with a Tokenizer that loads a model file in its `__init__` method, and overrides `from_params` to call `params.add_file_to_archive('model_path')`
2. Train the model to create the archive
3. Run the code snippet above to load the archive and subsequently try to create a predictor from that archive

**Expected behavior**
The `Predictor.from_params` method should be able to access file resources in the archive.

**System (please complete the following information):**
 - OS: OSX
 - Python version: Python 3.6.7 :: Anaconda, Inc.
 - AllenNLP version: Installed from master (a89aeba)
 - PyTorch version: 0.4.1

**Comment by matt-gardner** [comment]
Hmm, thanks for this, looks like a pretty nasty bug we need to fix.  To rephrase what you said just a little bit: this is an issue because the piece that needs a `file_to_archive` is in the _`DatasetReader`_, not the `Model`.  The `Model` has been fully loaded by the time `load_archive()` returns, but not the `DatasetReader`.

I'm not totally certain how to fix this.  One option is to just block removal of the temp directory if the `file_to_archive` logic was triggered, and rely on the OS to clean up the disk space at some point, because it's in temporary space.

**Comment by joelgrus** [comment]
agree that this is a bad bug. 

as a workaround, I *think* it would work if you manually un-tarred the model and passed in that directory to `load_archive`, everything should still work, and since it's no longer a temp dir, it won't get deleted

**Comment by joelgrus** [comment]
possible simple solution, use `atexit` to delete the temporary directory at exit rather than in `load_archive`

https://docs.python.org/3.6/library/atexit.html

**Comment by matt-gardner** [comment]
Yeah, we use that for killing the wikitables executor server, also.  Seems alright to me.

**Comment by vlthr** [comment]
Thank you both for your help! I've submitted a pull request with a fix (using `atexit`). Please let me know if there's anything else I can do to help out.
