### ISSUE TITLE
NER predictor failing on "2 ."

### ISSUE THREAD

**Issue by lpricePARC** [allenai/allennlp#2210]
**Describe the bug**
Rather than give a prediction, the system is generating an error:

**To Reproduce**
from allennlp.predictors.predictor import Predictor
predictor = Predictor.from_path(
            "https://s3-us-west-2.amazonaws.com/allennlp/models/ner-model-2018.04.26.tar.gz")
predictor.predict("2 .")

Error
Traceback (most recent call last):
  File "/tilde/lprice/anaconda3/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/tilde/lprice/anaconda3/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/tilde/lprice/Documents/2018/rfp-ner-broken-2/DocumentUnderstanding/Lottie/ner_crf_tagger/test/test_ner_features.py", line 37, in test_simple_breaking
    nerfi.predictor.predict("2 .")
  File "/tilde/lprice/.virtualenvs/docunderstanding-ihaw4TDj/lib/python3.6/site-packages/allennlp/predictors/sentence_tagger.py", line 24, in predict
    return self.predict_json({"sentence" : sentence})
  File "/tilde/lprice/.virtualenvs/docunderstanding-ihaw4TDj/lib/python3.6/site-packages/allennlp/predictors/predictor.py", line 55, in predict_json
    return self.predict_instance(instance)
  File "/tilde/lprice/.virtualenvs/docunderstanding-ihaw4TDj/lib/python3.6/site-packages/allennlp/predictors/predictor.py", line 58, in predict_instance
    outputs = self._model.forward_on_instance(instance)
  File "/tilde/lprice/.virtualenvs/docunderstanding-ihaw4TDj/lib/python3.6/site-packages/allennlp/models/model.py", line 124, in forward_on_instance
    return self.forward_on_instances([instance])[0]
  File "/tilde/lprice/.virtualenvs/docunderstanding-ihaw4TDj/lib/python3.6/site-packages/allennlp/models/model.py", line 155, in forward_on_instances
    outputs = self.decode(self(**model_input))
  File "/tilde/lprice/.virtualenvs/docunderstanding-ihaw4TDj/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/tilde/lprice/.virtualenvs/docunderstanding-ihaw4TDj/lib/python3.6/site-packages/allennlp/models/crf_tagger.py", line 207, in forward
    embedded_text_input = self.text_field_embedder(tokens)
  File "/tilde/lprice/.virtualenvs/docunderstanding-ihaw4TDj/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/tilde/lprice/.virtualenvs/docunderstanding-ihaw4TDj/lib/python3.6/site-packages/allennlp/modules/text_field_embedders/basic_text_field_embedder.py", line 107, in forward
    token_vectors = embedder(*tensors)
  File "/tilde/lprice/.virtualenvs/docunderstanding-ihaw4TDj/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/tilde/lprice/.virtualenvs/docunderstanding-ihaw4TDj/lib/python3.6/site-packages/allennlp/modules/token_embedders/token_characters_encoder.py", line 36, in forward
    return self._dropout(self._encoder(self._embedding(token_characters), mask))
  File "/tilde/lprice/.virtualenvs/docunderstanding-ihaw4TDj/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/tilde/lprice/.virtualenvs/docunderstanding-ihaw4TDj/lib/python3.6/site-packages/allennlp/modules/time_distributed.py", line 35, in forward
    reshaped_outputs = self._module(*reshaped_inputs)
  File "/tilde/lprice/.virtualenvs/docunderstanding-ihaw4TDj/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/tilde/lprice/.virtualenvs/docunderstanding-ihaw4TDj/lib/python3.6/site-packages/allennlp/modules/seq2vec_encoders/cnn_encoder.py", line 105, in forward
    self._activation(convolution_layer(tokens)).max(dim=2)[0]
  File "/tilde/lprice/.virtualenvs/docunderstanding-ihaw4TDj/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/tilde/lprice/.virtualenvs/docunderstanding-ihaw4TDj/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 176, in forward
    self.padding, self.dilation, self.groups)
Exception: Calculated padded input size per channel: (1 x 1). Kernel size: (1 x 3). Kernel size can't be greater than actual input size at /pytorch/aten/src/THNN/generic/SpatialConvolutionMM.c:48

**Expected behavior**
I expected the predictor to generate NER labels of "O" for both tokens generated from the words "2" and "."

**System (please complete the following information):**
 - OS: Linux
 - Python version: 3.6.5 
 - AllenNLP version:  v0.7.2

**Comment by lpricePARC** [comment]
Thank you, Matt.
