### ISSUE TITLE
Checks for files break when used with globs.

### ISSUE THREAD

**Issue by brendan-ai2** [allenai/allennlp#2337]
This PR adds checks for filepaths in `train.py`: https://github.com/allenai/allennlp/pull/2308

Unfortunately, dataset readers can interpret the path string in different way. The MultiprocessDatasetReader, in particular, expects a glob.

We should revert PR #2308 and add a test that actually trains with the MultiprocessDatasetReader.

Trace:
```
Traceback (most recent call last):
  File "/home/vidurj/miniconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/vidurj/miniconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/vidurj/miniconda3/lib/python3.6/site-packages/allennlp/run.py", line 18, in <module>
    main(prog="allennlp")
  File "/home/vidurj/miniconda3/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 101, in main
    args.func(args)
  File "/home/vidurj/miniconda3/lib/python3.6/site-packages/allennlp/commands/train.py", line 111, in train_model_from_args
    args.force)
  File "/home/vidurj/miniconda3/lib/python3.6/site-packages/allennlp/commands/train.py", line 144, in train_model_from_file
    return train_model(params, serialization_dir, file_friendly_logging, recover, force)
  File "/home/vidurj/miniconda3/lib/python3.6/site-packages/allennlp/commands/train.py", line 298, in train_model
    all_datasets = datasets_from_params(params)
  File "/home/vidurj/miniconda3/lib/python3.6/site-packages/allennlp/commands/train.py", line 154, in datasets_from_params
    check_for_data_path(data_path, data_name)
  File "/home/vidurj/miniconda3/lib/python3.6/site-packages/allennlp/common/checks.py", line 75, in check_for_data_path
    data_path = cached_path(data_path) 
  File "/home/vidurj/miniconda3/lib/python3.6/site-packages/allennlp/common/file_utils.py", line 104, in cached_path
    raise FileNotFoundError("file {} not found".format(url_or_filename))
FileNotFoundError: file billion/training-monolingual.tokenized.shuffled/* not found
```

**Comment by schmmd** [comment]
Brendan reverted the PR that broke this so this is now fixed.
