### ISSUE TITLE
Training fails with KeyError exception

### ISSUE THREAD

**Issue by bianca2319** [allenai/allennlp#2407]
**System**
 - OS: Linux
 - Python version: 3.6
 - AllenNLP version: 0.8.1

**Question**
If I try to execute a training on GPU server via `allennlp train ../config/mdb_crf.json -s ../experiments/test,` the calculation stops with an KeyError exception, because the model output doesn't contain the loss element:

`2019-01-21 09:47:30,835 - INFO - allennlp.training.trainer - Training
  0%|          | 0/100 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/bianca/miner/lib/python3.6/site-packages/allennlp/training/trainer.py", line 437, in batch_loss
    loss = output_dict["loss"]
KeyError: 'loss'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/bianca/miner/lib/python3.6/site-packages/allennlp/run.py", line 18, in <module>
    main(prog="allennlp")
  File "/home/bianca/miner/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 72, in main
    args.func(args)
  File "/home/bianca/miner/lib/python3.6/site-packages/allennlp/commands/train.py", line 111, in train_model_from_args
    args.force)
  File "/home/bianca/miner/lib/python3.6/site-packages/allennlp/commands/train.py", line 144, in train_model_from_file
    return train_model(params, serialization_dir, file_friendly_logging, recover, force)
  File "/home/bianca/miner/lib/python3.6/site-packages/allennlp/commands/train.py", line 361, in train_model
    metrics = trainer.train()
  File "/home/bianca/miner/lib/python3.6/site-packages/allennlp/training/trainer.py", line 787, in train
    train_metrics = self._train_epoch(epoch)
  File "/home/bianca/miner/lib/python3.6/site-packages/allennlp/training/trainer.py", line 515, in _train_epoch
    loss = self.batch_loss(batch, for_training=True)
  File "/home/bianca/miner/lib/python3.6/site-packages/allennlp/training/trainer.py", line 442, in batch_loss
    raise RuntimeError("The model you are trying to optimize does not contain a"
RuntimeError: The model you are trying to optimize does not contain a 'loss' key in the output of model.forward(inputs).
`
All previous steps (also data loading) work correctly. Are there any ideas how to solve the problem?

**Comment by joelgrus** [comment]
your model output needs to contain a `"loss"` key with the loss in it, that's what the trainer is trying to optimize.
