### ISSUE TITLE
Resuming training on BidirectionalLanguageModel fails with pre-specified vocabulary

### ISSUE THREAD

**Issue by swabhs** [allenai/allennlp#2502]
I'm trying to train the `BidirectionalLanguageModel` using a pre-built vocabulary (based on the options in the [config](https://github.com/allenai/allennlp/blob/master/training_config/bidirectional_language_model.jsonnet#L53)). However,  if I resume a paused training using the `--recover` flag, I get the following error:

```
Traceback (most recent call last):
  File "/home/swabhas/tools/miniconda2/envs/lean/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/swabhas/tools/miniconda2/envs/lean/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/swabhas/lean-lm/allennlp/allennlp/run.py", line 18, in <module>
    main(prog="allennlp")
  File "/home/swabhas/lean-lm/allennlp/allennlp/commands/__init__.py", line 101, in main
    args.func(args)
  File "/home/swabhas/lean-lm/allennlp/allennlp/commands/train.py", line 111, in train_model_from_args
    args.force)
  File "/home/swabhas/lean-lm/allennlp/allennlp/commands/train.py", line 144, in train_model_from_file
    return train_model(params, serialization_dir, file_friendly_logging, recover, force)
  File "/home/swabhas/lean-lm/allennlp/allennlp/commands/train.py", line 363, in train_model
    params.assert_empty('base train command')
  File "/home/swabhas/lean-lm/allennlp/allennlp/common/params.py", line 367, in assert_empty
    raise ConfigurationError("Extra parameters passed to {}: {}".format(class_name, self.params))
allennlp.common.checks.ConfigurationError: "Extra parameters passed to base train command: {'vocabulary': {'directory_path': '/home/swabhas/data/language_modeling/vocab-1-billion-word-language-modeling-benchmark/'}}"
```

If I edit the config to remove the vocabulary, training resumes successfully. But it would be way more convenient to not have it fail in the first place.

**Comment by nelson-liu** [comment]
pretty sure this is fixed by https://github.com/allenai/allennlp/pull/2409 , which unfortunately hasn't made it into a pip release yet.

**Comment by brendan-ai2** [comment]
We believe this is fixed. Please reopen if not!
