### ISSUE TITLE
question on tutorial <Creating Your Own Models>

### ISSUE THREAD

**Issue by jwc19890114** [allenai/allennlp#2583]
**System (please complete the following information):**
 - OS: win10
 - Python version:3.6
 - AllenNLP version: I installed from master
 - PyTorch version: (if you installed it yourself)

**Question**
when I follow this section Creating Your Own Models, download these datasets(eng.train/eng.testa/eng.testb) from 
 NER, and redirect the pretrain dataset. 
but got the bug

>Traceback (most recent call last):
  File "c:\programdata\anaconda3\envs\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\envs\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\python36\Scripts\allennlp.exe\__main__.py", line 9, in <module>
  File "c:\programdata\anaconda3\envs\python36\lib\site-packages\allennlp\run.py", line 18, in run
    main(prog="allennlp")
  File "c:\programdata\anaconda3\envs\python36\lib\site-packages\allennlp\commands\__init__.py", line 101, in main
    args.func(args)
  File "c:\programdata\anaconda3\envs\python36\lib\site-packages\allennlp\commands\train.py", line 103, in train_model_from_args
    args.force)
  File "c:\programdata\anaconda3\envs\python36\lib\site-packages\allennlp\commands\train.py", line 136, in train_model_from_file
    return train_model(params, serialization_dir, file_friendly_logging, recover, force)
  File "c:\programdata\anaconda3\envs\python36\lib\site-packages\allennlp\commands\train.py", line 184, in train_model
    pieces = TrainerPieces.from_params(params, serialization_dir, recover)  # pylint: disable=no-member
  File "c:\programdata\anaconda3\envs\python36\lib\site-packages\allennlp\training\trainer.py", line 739, in from_params
    all_datasets = training_util.datasets_from_params(params)
  File "c:\programdata\anaconda3\envs\python36\lib\site-packages\allennlp\training\util.py", line 139, in datasets_from_params
    train_data = dataset_reader.read(train_data_path)
  File "c:\programdata\anaconda3\envs\python36\lib\site-packages\allennlp\data\dataset_readers\dataset_reader.py", line 73, in read
    instances = [instance for instance in Tqdm.tqdm(instances)]
  File "c:\programdata\anaconda3\envs\python36\lib\site-packages\allennlp\data\dataset_readers\dataset_reader.py", line 73, in <listcomp>
    instances = [instance for instance in Tqdm.tqdm(instances)]
  File "c:\programdata\anaconda3\envs\python36\lib\site-packages\tqdm\_tqdm.py", line 1022, in __iter__
    for obj in iterable:
  File "c:\programdata\anaconda3\envs\python36\lib\site-packages\allennlp\data\dataset_readers\conll2003.py", line 115, in _read
    tokens_, pos_tags, chunk_tags, ner_tags = fields
ValueError: not enough values to unpack (expected 4, got 1)

**Comment by matt-gardner** [comment]
It looks like your input data file is not in the format that dataset reader is expecting.  Can you double check that you're matching this format: https://github.com/allenai/allennlp/blob/9437b614dbc518b3b532bbaa201446dc454fc6e2/allennlp/data/dataset_readers/conll2003.py#L33-L39

**Comment by kl2806** [comment]
Closing due to inactivity, feel free to reopen if there is still an issue.
