### ISSUE TITLE
Fresh install on Ubuntu 18.04 didn't work

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp#2597]
```
$ pip3 install allennlp
$ python3 -m allennlp.run train training_config/decomposable_attention.jsonnet
 -s output_path
Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex.
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/michaels/allennlp/allennlp/run.py", line 15, in <module>
    from allennlp.commands import main  # pylint: disable=wrong-import-position
  File "/home/michaels/allennlp/allennlp/commands/__init__.py", line 8, in <module>
    from allennlp.commands.configure import Configure
  File "/home/michaels/allennlp/allennlp/commands/configure.py", line 27, in <module>
    from allennlp.service.config_explorer import make_app
  File "/home/michaels/allennlp/allennlp/service/config_explorer.py", line 24, in <module>
    from allennlp.common.configuration import configure, choices
  File "/home/michaels/allennlp/allennlp/common/configuration.py", line 17, in <module>
    from allennlp.data.dataset_readers import DatasetReader
  File "/home/michaels/allennlp/allennlp/data/__init__.py", line 1, in <module>
    from allennlp.data.dataset_readers.dataset_reader import DatasetReader
  File "/home/michaels/allennlp/allennlp/data/dataset_readers/__init__.py", line 21, in <module>
    from allennlp.data.dataset_readers.reading_comprehension import (
  File "/home/michaels/allennlp/allennlp/data/dataset_readers/reading_comprehension/__init__.py", line 8, in <modul
e>
    from allennlp.data.dataset_readers.reading_comprehension.drop import DropReader
  File "/home/michaels/allennlp/allennlp/data/dataset_readers/reading_comprehension/drop.py", line 9, in <module>
    from word2number.w2n import word_to_num
ModuleNotFoundError: No module named 'word2number'
```

**Comment by schmmd** [comment]
`pip3 install word2number` resolve the issue for me locally.

**Comment by matt-gardner** [comment]
There was a brief period where I added `word2number` in `requirements.txt` but didn't realize I also needed to add it to `setup.py`.  This should be fixed with the latest master.  If you're still seeing an issue on master, re-open this issue.

**Comment by schmmd** [comment]
@matt-gardner we should probably do a release if this is affecting 0.8.2?

**Comment by matt-gardner** [comment]
The bug was introduced [here](https://github.com/allenai/allennlp/commit/bbb67e9f5f2e804dc5f093f1f6e30ef3bbd96030), which was after the 0.8.2 release.  There is no released version that is affected by this.

**Comment by schmmd** [comment]
Well--that's totally weird because I just did `pip install allennlp`, which presumably would install 0.8.2.  I'll check.

**Comment by schmmd** [comment]
This is definitely an issue with 0.8.2 on a fresh Ubuntu machine.  I'm surprised we don't hit it in our continuous build.

**Comment by matt-gardner** [comment]
It *can't* be an issue with 0.8.2, because the dependency isn't there in 0.8.2.

**Comment by schmmd** [comment]
Ah shoot @matt-gardner -- you're probably right.  Even though I've installed `allennlp` I also cloned the repository so I have the training configurations.  I'm probably picking up the source code rather than using the installed `allennlp`.  Doh!
