### ISSUE TITLE
Memory Error for large datasets in WikiTables Semantic Parsing Allennlp

### ISSUE THREAD

**Issue by dummybot123** [allenai/allennlp#2623]
I am getting MemoryError for large datasets in WikiTables Semantic Parsing using Allennlp. I am getting the following error.

```
Traceback (most recent call last):
  File "myscript.py", line 159, in <module>
    p = predictor.predict_json(i)
  File "C:\Users\abc\Downloads\allennlp-master\allennlp-master\allennlp\predictors\predictor.py", line 55, in predict_json
    return self.predict_instance(instance)
  File "C:\Users\abc\Downloads\allennlp-master\allennlp-master\allennlp\predictors\wikitables_parser.py", line 71, in predict_instance
    outputs = self._model.forward_on_instance(instance)
  File "C:\Users\abc\Downloads\allennlp-master\allennlp-master\allennlp\models\model.py", line 124, in forward_on_instance
    return self.forward_on_instances([instance])[0]
  File "C:\Users\abc\Downloads\allennlp-master\allennlp-master\allennlp\models\model.py", line 155, in forward_on_instances
    outputs = self.decode(self(**model_input))
  File "C:\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\abc\Downloads\allennlp-master\allennlp-master\allennlp\models\semantic_parsing\wikitables\wikitables_mml_semantic_parser.py", line 176, in forward
    outputs)
  File "C:\Users\abc\Downloads\allennlp-master\allennlp-master\allennlp\models\semantic_parsing\wikitables\wikitables_semantic_parser.py", line 169, in _get_initial_rnn_and_grammar_state
    neighbor_indices = self._get_neighbor_indices(world, num_entities, encoded_table)
  File "C:\Users\abc\Downloads\allennlp-master\allennlp-master\allennlp\models\semantic_parsing\wikitables\wikitables_semantic_parser.py", line 335, in _get_neighbor_indices
    padded = pad_sequence_to_length(entity_neighbors, num_neighbors, lambda: -1)
  File "C:\Users\abc\Downloads\allennlp-master\allennlp-master\allennlp\common\util.py", line 145, in pad_sequence_to_length
    padded_sequence.append(default_value())
MemoryError
```

 - Python version: 3.6.1

**Comment by matt-gardner** [comment]
It looks like you should use this parameter to the dataset reader: https://github.com/allenai/allennlp/blob/ca998b267311c4897617853d83345143f6e27dad/allennlp/data/dataset_readers/semantic_parsing/wikitables/wikitables.py#L119-L123

**Comment by vidurj** [comment]
Please reopen the issue if this did not answer your question.
