### ISSUE TITLE
Ask for BERT baseline for DROP

### ISSUE THREAD

**Issue by ycWang9725** [allenai/allennlp#2657]
Hi,

I'm interested in DROP dataset and hope to run some baseline to see the output. But currently I have a hard time reproduce BERT baseline with the BERT implemented here: https://github.com/huggingface/pytorch-pretrained-BERT.git

So could you please add this baseline in allennlp or share me with your original implementation?

Thanks

**Comment by matt-gardner** [comment]
Hi @ycWang9725, I think @yizhongw is the right person to answer this question.  There is code for marginalizing over answer positions with a BERT model [here](https://github.com/allenai/allennlp-reading-comprehension-research/blob/master/reading_comprehension/drop_models/bert_rc_marginal.py), but I don't think that's what @yizhongw actually used to run the experiments - I believe he just used the huggingface code to train the model.  @yizhongw, do you have the code you used to train the BERT model anywhere?

**Comment by ycWang9725** [comment]
@matt-gardner Thanks for your help!
however, when I run this code, i got error like this:

`<stderr>:/opt/conda/conda-bld/pytorch_1535491974311/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [0,0,0], thread: [3,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
2019-03-31T16:33:17.607Z: [1,0]<stderr>:/opt/conda/conda-bld/pytorch_1535491974311/work/aten/src/THC/THCTensorScatterGather.cu:97[1,0]<stderr>:: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [0,0,0], thread: [4,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
2019-03-31T16:33:17.607Z: [1,0]<stderr>:THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1535491974311/work/aten/src/THC/generic/THCTensorScatterGather.cu line=68 error=59 : device-side assert triggered
2019-03-31T16:33:17.625Z: [1,0]<stderr>:Traceback (most recent call last):
2019-03-31T16:33:17.625Z: [1,0]<stderr>:  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
2019-03-31T16:33:17.626Z: [1,0]<stderr>:    "__main__", mod_spec)
2019-03-31T16:33:17.626Z: [1,0]<stderr>:  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/runpy.py", line 85, in _run_code
2019-03-31T16:33:17.626Z: [1,0]<stderr>:    exec(code, run_globals)
2019-03-31T16:33:17.626Z: [1,0]<stderr>:  File "/tmp/cache/python/lib/python3.6/site-packages/allennlp/run.py", line 21, in <module>
2019-03-31T16:33:17.626Z: [1,0]<stderr>:    run()
2019-03-31T16:33:17.626Z: [1,0]<stderr>:  File "/tmp/cache/python/lib/python3.6/site-packages/allennlp/run.py", line 18, in run
2019-03-31T16:33:17.626Z: [1,0]<stderr>:    main(prog="allennlp")
2019-03-31T16:33:17.626Z: [1,0]<stderr>:  File "/tmp/cache/python/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 101, in main
2019-03-31T16:33:17.626Z: [1,0]<stderr>:    args.func(args)
2019-03-31T16:33:17.626Z: [1,0]<stderr>:  File "/tmp/cache/python/lib/python3.6/site-packages/allennlp/commands/train.py", line 103, in train_model_from_args
2019-03-31T16:33:17.626Z: [1,0]<stderr>:    args.force)
2019-03-31T16:33:17.626Z: [1,0]<stderr>:  File "/tmp/cache/python/lib/python3.6/site-packages/allennlp/commands/train.py", line 136, in train_model_from_file
2019-03-31T16:33:17.626Z: [1,0]<stderr>:    return train_model(params, serialization_dir, file_friendly_logging, recover, force)
2019-03-31T16:33:17.626Z: [1,0]<stderr>:  File "/tmp/cache/python/lib/python3.6/site-packages/allennlp/commands/train.py", line 204, in train_model
2019-03-31T16:33:17.626Z: [1,0]<stderr>:    metrics = trainer.train()
2019-03-31T16:33:17.626Z: [1,0]<stderr>:  File "/tmp/cache/python/lib/python3.6/site-packages/allennlp/training/trainer.py", line 478, in train
2019-03-31T16:33:17.626Z: [1,0]<stderr>:    val_loss, num_batches = self._validation_loss()
2019-03-31T16:33:17.626Z: [1,0]<stderr>:  File "/tmp/cache/python/lib/python3.6/site-packages/allennlp/training/trainer.py", line 415, in _validation_loss
2019-03-31T16:33:17.626Z: [1,0]<stderr>:    loss = self.batch_loss(batch_group, for_training=False)
2019-03-31T16:33:17.626Z: [1,0]<stderr>:  File "/tmp/cache/python/lib/python3.6/site-packages/allennlp/training/trainer.py", line 247, in batch_loss
2019-03-31T16:33:17.626Z: [1,0]<stderr>:    output_dict = self.model(**batch)
2019-03-31T16:33:17.626Z: [1,0]<stderr>:  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
2019-03-31T16:33:17.626Z: [1,0]<stderr>:    result = self.forward(*input, **kwargs)
2019-03-31T16:33:17.626Z: [1,0]<stderr>:  File "/hdfs/ipgsrch/v-yuewan/drop/reading_comprehension/drop_models/bert_rc_marginal.py", line 97, in forward
2019-03-31T16:33:17.626Z: [1,0]<stderr>:    torch.gather(passage_span_start_log_probs, 1, clamped_gold_passage_span_starts)
2019-03-31T16:33:17.626Z: [1,0]<stderr>:RuntimeError: cuda runtime error (59) : device-side assert triggered at /opt/conda/conda-bld/pytorch_1535491974311/work/aten/src/THC/generic/THCTensorScatterGather.cu:68`

environment:
allennlp 0.8.2
torch 0.4.1

**Comment by yizhongw** [comment]
@ycWang9725 @matt-gardner 
Sorry for the delayed reply, since I didn't get notification for the mentions here. Yes, I just converted the DROP dataset into SQuAD format, and of course, for the train set, I abandoned those examples that cannot find a matched span in the passage. Then I used the huggingface code to do the training. I pushed the code to [my own repo](https://github.com/yizhongw/allennlp-reading-comprehension-research/tree/huggingface-bert-for-drop/reading_comprehension/huggingface_bert) just now for your reference.

The [code](https://github.com/allenai/allennlp-reading-comprehension-research/blob/master/reading_comprehension/drop_models/bert_rc_marginal.py) you pointed out here is only for testing. I planed to reimplement the BERT baseline in an AllenNLP fashion after our paper submission, and it actually worked with the `bert_base` model. But for the `bert_large` model, I encountered with some GPU memory issues, so I gave that up in the end. The error you reported here are not expected.  Maybe there are still bugs in the code, and you can print out `clamped_gold_passage_span_starts` for debugging.

**Comment by ycWang9725** [comment]
@yizhongw the code you provide huggingface bert work well! thanks very much!
for the allennlp implement, I printed "clamped_gold_passage_span_starts" and find it is sometimes lager than the length of "passage_span_start_log_probs", but don't know why.
Anyway, thanks for providing me a working version of code.
