### ISSUE TITLE
CUDA out of memory in multi-gpu server

### ISSUE THREAD

**Issue by junkyul** [allenai/allennlp#2713]
**Describe the bug**
AllenNLP raises CUDA out of memory in multi-gpu server by allocating tensors to GPU 0 when there are other GPUs available.

Currently, this error can be avoided by using CPU or changing the model (use pre-trained embedding, decrease batch size); 

**To Reproduce**
Train a model with very large embeddings or large batch size that wouldn't fit in the 
first GPU.

stderr.log
> /home/junkyul/.local/lib/python3.6/site-packages/torch/nn/modules/rnn.py:182: RuntimeWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters().
  self.num_layers, self.dropout, self.training, self.bidirectional)
accuracy: 0.0810, loss: 3.4369 ||: 100%|##########| 1/1 [00:06<00:00,  6.01s/it]
Traceback (most recent call last):
  File "/home/junkyul/.conda/envs/allennlp/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/junkyul/.conda/envs/allennlp/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/junkyul/.local/lib/python3.6/site-packages/allennlp/run.py", line 21, in <module>
    run()
  File "/home/junkyul/.local/lib/python3.6/site-packages/allennlp/run.py", line 18, in run
    main(prog="allennlp")
  File "/home/junkyul/.local/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 101, in main
    args.func(args)
  File "/home/junkyul/.local/lib/python3.6/site-packages/allennlp/commands/train.py", line 103, in train_model_from_args
    args.force)
  File "/home/junkyul/.local/lib/python3.6/site-packages/allennlp/commands/train.py", line 136, in train_model_from_file
    return train_model(params, serialization_dir, file_friendly_logging, recover, force)
  File "/home/junkyul/.local/lib/python3.6/site-packages/allennlp/commands/train.py", line 204, in train_model
    metrics = trainer.train()
  File "/home/junkyul/.local/lib/python3.6/site-packages/allennlp/training/trainer.py", line 465, in train
    train_metrics = self._train_epoch(epoch)
  File "/home/junkyul/.local/lib/python3.6/site-packages/allennlp/training/trainer.py", line 311, in _train_epoch
    loss.backward()
  File "/home/junkyul/.local/lib/python3.6/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/junkyul/.local/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/home/junkyul/.local/lib/python3.6/site-packages/torch/autograd/function.py", line 76, in apply
    return self._forward_cls.backward(self, *args)
  File "/home/junkyul/.local/lib/python3.6/site-packages/torch/nn/parallel/_functions.py", line 32, in backward
    return (None,) + ReduceAddCoalesced.apply(ctx.input_device, ctx.num_inputs, *grad_outputs)
  File "/home/junkyul/.local/lib/python3.6/site-packages/torch/nn/parallel/_functions.py", line 43, in forward
    return comm.reduce_add_coalesced(grads, destination)
  File "/home/junkyul/.local/lib/python3.6/site-packages/torch/cuda/comm.py", line 122, in reduce_add_coalesced
    flat_result = reduce_add(flat_tensors, destination)
  File "/home/junkyul/.local/lib/python3.6/site-packages/torch/cuda/comm.py", line 74, in reduce_add
    result = inp.new(device=destination).resize_as_(inp).zero_()
RuntimeError: CUDA out of memory. Tried to allocate 2.45 GiB (GPU 0; 11.91 GiB total capacity; 8.75 GiB already allocated; 1.83 GiB free; 763.56 MiB cached)

**Expected behavior**
The GPU server has additional GPU with 12 GB memory.
Since cuda_device is set to [0,1] in config file, 
expected behavior is to check the availability of CUDA memory and use the  second one.

**System (please complete the following information):**
 - OS: CentOs Linux 7
 - Python version: 3.6.7
 - AllenNLP version: v0.8.2
 - PyTorch version: 1.1.1.post2 

**Additional context**
I am not sure, but allocation of tensors to the same GPU might be forced by the model?

model parameters are shown in stdout.log
> 2019-04-12 23:06:20,988 - INFO - allennlp.common.params - evaluate_on_test = True
2019-04-12 23:07:58,812 - INFO - allennlp.common.params - vocabulary.type = None
2019-04-12 23:07:58,812 - INFO - allennlp.common.params - vocabulary.extend = False
2019-04-12 23:07:58,812 - INFO - allennlp.common.params - vocabulary.directory_path = /home/junkyul/conda/allenel/vocab_custom
2019-04-12 23:07:58,812 - INFO - allennlp.data.vocabulary - Loading Vocab from files instead of dataset.
2019-04-12 23:07:58,812 - INFO - allennlp.data.vocabulary - Loading token dictionary from /home/junkyul/conda/allenel/vocab_custom.
2019-04-12 23:08:04,163 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.models.model.Model'> from params {'coherence_embedder': {'token_embedders': {'tokens': {'embedding_dim': 100, 'sparse': True, 'type': 'embedding', 'vocab_namespace': 'coherences'}}}, 'entity_embedder': {'token_embedders': {'tokens': {'embedding_dim': 200, 'sparse': True, 'type': 'embedding', 'vocab_namespace': 'wids'}}}, 'ff_context': {'activations': 'relu', 'dropout': 0.4, 'hidden_dims': 200, 'input_dim': 200, 'num_layers': 1}, 'ff_seq2vecs': {'activations': 'relu', 'dropout': 0.4, 'hidden_dims': 100, 'input_dim': 200, 'num_layers': 1}, 'left_seq2vec': {'bidirectional': False, 'hidden_size': 100, 'input_size': 300, 'num_layers': 1, 'type': 'lstm'}, 'right_seq2vec': {'bidirectional': False, 'hidden_size': 100, 'input_size': 300, 'num_layers': 1, 'type': 'lstm'}, 'sentence_embedder': {'token_embedders': {'tokens': {'embedding_dim': 300, 'pretrained_file': '/home/junkyul/conda/glove/glove.wiki.300d.txt.gz', 'sparse': True, 'trainable': False, 'type': 'embedding', 'vocab_namespace': 'sentences'}}}, 'type': 'el_model'} and extras {'vocab': Vocabulary with namespaces:  coherences, Size: 1561684 || sentences, Size: 2196017 || types, Size: 115 || wids, Size: 614130 || Non Padded Namespaces: {'*tags', '*labels'}}
2019-04-12 23:08:04,163 - INFO - allennlp.common.params - model.type = el_model
2019-04-12 23:08:04,163 - INFO - allennlp.common.from_params - instantiating class <class 'allenel.models.el_model.EnityLinknigModel'> from params {'coherence_embedder': {'token_embedders': {'tokens': {'embedding_dim': 100, 'sparse': True, 'type': 'embedding', 'vocab_namespace': 'coherences'}}}, 'entity_embedder': {'token_embedders': {'tokens': {'embedding_dim': 200, 'sparse': True, 'type': 'embedding', 'vocab_namespace': 'wids'}}}, 'ff_context': {'activations': 'relu', 'dropout': 0.4, 'hidden_dims': 200, 'input_dim': 200, 'num_layers': 1}, 'ff_seq2vecs': {'activations': 'relu', 'dropout': 0.4, 'hidden_dims': 100, 'input_dim': 200, 'num_layers': 1}, 'left_seq2vec': {'bidirectional': False, 'hidden_size': 100, 'input_size': 300, 'num_layers': 1, 'type': 'lstm'}, 'right_seq2vec': {'bidirectional': False, 'hidden_size': 100, 'input_size': 300, 'num_layers': 1, 'type': 'lstm'}, 'sentence_embedder': {'token_embedders': {'tokens': {'embedding_dim': 300, 'pretrained_file': '/home/junkyul/conda/glove/glove.wiki.300d.txt.gz', 'sparse': True, 'trainable': False, 'type': 'embedding', 'vocab_namespace': 'sentences'}}}} and extras {'vocab': Vocabulary with namespaces:  coherences, Size: 1561684 || sentences, Size: 2196017 || types, Size: 115 || wids, Size: 614130 || Non Padded Namespaces: {'*tags', '*labels'}}
2019-04-12 23:08:04,164 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.modules.text_field_embedders.text_field_embedder.TextFieldEmbedder'> from params {'token_embedders': {'tokens': {'embedding_dim': 300, 'pretrained_file': '/home/junkyul/conda/glove/glove.wiki.300d.txt.gz', 'sparse': True, 'trainable': False, 'type': 'embedding', 'vocab_namespace': 'sentences'}}} and extras {'vocab': Vocabulary with namespaces:  coherences, Size: 1561684 || sentences, Size: 2196017 || types, Size: 115 || wids, Size: 614130 || Non Padded Namespaces: {'*tags', '*labels'}}
2019-04-12 23:08:04,164 - INFO - allennlp.common.params - model.sentence_embedder.type = basic
2019-04-12 23:08:04,164 - INFO - allennlp.common.params - model.sentence_embedder.embedder_to_indexer_map = None
2019-04-12 23:08:04,164 - INFO - allennlp.common.params - model.sentence_embedder.allow_unmatched_keys = False
2019-04-12 23:08:04,164 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.modules.token_embedders.token_embedder.TokenEmbedder'> from params {'embedding_dim': 300, 'pretrained_file': '/home/junkyul/conda/glove/glove.wiki.300d.txt.gz', 'sparse': True, 'trainable': False, 'type': 'embedding', 'vocab_namespace': 'sentences'} and extras {'vocab': Vocabulary with namespaces:  coherences, Size: 1561684 || sentences, Size: 2196017 || types, Size: 115 || wids, Size: 614130 || Non Padded Namespaces: {'*tags', '*labels'}}
2019-04-12 23:08:04,164 - INFO - allennlp.common.params - model.sentence_embedder.token_embedders.tokens.type = embedding
2019-04-12 23:08:04,165 - INFO - allennlp.common.params - model.sentence_embedder.token_embedders.tokens.num_embeddings = None
2019-04-12 23:08:04,165 - INFO - allennlp.common.params - model.sentence_embedder.token_embedders.tokens.vocab_namespace = sentences
2019-04-12 23:08:04,165 - INFO - allennlp.common.params - model.sentence_embedder.token_embedders.tokens.embedding_dim = 300
2019-04-12 23:08:04,165 - INFO - allennlp.common.params - model.sentence_embedder.token_embedders.tokens.pretrained_file = /home/junkyul/conda/glove/glove.wiki.300d.txt.gz
2019-04-12 23:08:04,165 - INFO - allennlp.common.params - model.sentence_embedder.token_embedders.tokens.projection_dim = None
2019-04-12 23:08:04,165 - INFO - allennlp.common.params - model.sentence_embedder.token_embedders.tokens.trainable = False
2019-04-12 23:08:04,165 - INFO - allennlp.common.params - model.sentence_embedder.token_embedders.tokens.padding_index = None
2019-04-12 23:08:04,165 - INFO - allennlp.common.params - model.sentence_embedder.token_embedders.tokens.max_norm = None
2019-04-12 23:08:04,165 - INFO - allennlp.common.params - model.sentence_embedder.token_embedders.tokens.norm_type = 2.0
2019-04-12 23:08:04,165 - INFO - allennlp.common.params - model.sentence_embedder.token_embedders.tokens.scale_grad_by_freq = False
2019-04-12 23:08:04,165 - INFO - allennlp.common.params - model.sentence_embedder.token_embedders.tokens.norm_type = 2.0
2019-04-12 23:08:04,165 - INFO - allennlp.common.params - model.sentence_embedder.token_embedders.tokens.scale_grad_by_freq = False
2019-04-12 23:08:04,165 - INFO - allennlp.common.params - model.sentence_embedder.token_embedders.tokens.sparse = True
2019-04-12 23:08:04,462 - INFO - allennlp.modules.token_embedders.embedding - Reading pretrained embeddings from file
2019-04-12 23:11:53,297 - INFO - allennlp.modules.token_embedders.embedding - Initializing pre-trained embedding layer
2019-04-12 23:12:23,933 - INFO - allennlp.modules.token_embedders.embedding - Pretrained embeddings were found for 2196016 out of 2196017 tokens
2019-04-12 23:12:25,212 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.modules.text_field_embedders.text_field_embedder.TextFieldEmbedder'> from params {'token_embedders': {'tokens': {'embedding_dim': 200, 'sparse': True, 'type': 'embedding', 'vocab_namespace': 'wids'}}} and extras {'vocab': Vocabulary with namespaces:  coherences, Size: 1561684 || sentences, Size: 2196017 || types, Size: 115 || wids, Size: 614130 || Non Padded Namespaces: {'*tags', '*labels'}}
2019-04-12 23:12:25,212 - INFO - allennlp.common.params - model.entity_embedder.type = basic
2019-04-12 23:12:25,213 - INFO - allennlp.common.params - model.entity_embedder.embedder_to_indexer_map = None
2019-04-12 23:12:25,213 - INFO - allennlp.common.params - model.entity_embedder.allow_unmatched_keys = False
2019-04-12 23:12:25,213 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.modules.token_embedders.token_embedder.TokenEmbedder'> from params {'embedding_dim': 200, 'sparse': True, 'type': 'embedding', 'vocab_namespace': 'wids'} and extras {'vocab': Vocabulary with namespaces:  coherences, Size: 1561684 || sentences, Size: 2196017 || types, Size: 115 || wids, Size: 614130 || Non Padded Namespaces: {'*tags', '*labels'}}
2019-04-12 23:12:25,213 - INFO - allennlp.common.params - model.entity_embedder.token_embedders.tokens.type = embedding
2019-04-12 23:12:25,213 - INFO - allennlp.common.params - model.entity_embedder.token_embedders.tokens.num_embeddings = None
2019-04-12 23:12:25,213 - INFO - allennlp.common.params - model.entity_embedder.token_embedders.tokens.vocab_namespace = wids
2019-04-12 23:12:25,213 - INFO - allennlp.common.params - model.entity_embedder.token_embedders.tokens.embedding_dim = 200
2019-04-12 23:12:25,213 - INFO - allennlp.common.params - model.entity_embedder.token_embedders.tokens.pretrained_file = None
2019-04-12 23:12:25,213 - INFO - allennlp.common.params - model.entity_embedder.token_embedders.tokens.projection_dim = None
2019-04-12 23:12:25,213 - INFO - allennlp.common.params - model.entity_embedder.token_embedders.tokens.trainable = True
2019-04-12 23:12:25,213 - INFO - allennlp.common.params - model.entity_embedder.token_embedders.tokens.padding_index = None
2019-04-12 23:12:25,213 - INFO - allennlp.common.params - model.entity_embedder.token_embedders.tokens.max_norm = None
2019-04-12 23:12:25,213 - INFO - allennlp.common.params - model.entity_embedder.token_embedders.tokens.norm_type = 2.0
2019-04-12 23:12:25,213 - INFO - allennlp.common.params - model.entity_embedder.token_embedders.tokens.scale_grad_by_freq = False
2019-04-12 23:12:25,214 - INFO - allennlp.common.params - model.entity_embedder.token_embedders.tokens.sparse = True
2019-04-12 23:12:26,176 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.modules.text_field_embedders.text_field_embedder.TextFieldEmbedder'> from params {'token_embedders': {'tokens': {'embedding_dim': 100, 'sparse': True, 'type': 'embedding', 'vocab_namespace': 'coherences'}}} and extras {'vocab': Vocabulary with namespaces:  coherences, Size: 1561684 || sentences, Size: 2196017 || types, Size: 115 || wids, Size: 614130 || Non Padded Namespaces: {'*tags', '*labels'}}
2019-04-12 23:12:26,176 - INFO - allennlp.common.params - model.coherence_embedder.type = basic
2019-04-12 23:12:26,176 - INFO - allennlp.common.params - model.coherence_embedder.embedder_to_indexer_map = None
2019-04-12 23:12:26,176 - INFO - allennlp.common.params - model.coherence_embedder.allow_unmatched_keys = False
2019-04-12 23:12:26,176 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.modules.token_embedders.token_embedder.TokenEmbedder'> from params {'embedding_dim': 100, 'sparse': True, 'type': 'embedding', 'vocab_namespace': 'coherences'} and extras {'vocab': Vocabulary with namespaces:  coherences, Size: 1561684 || sentences, Size: 2196017 || types, Size: 115 || wids, Size: 614130 || Non Padded Namespaces: {'*tags', '*labels'}}
2019-04-12 23:12:26,176 - INFO - allennlp.common.params - model.coherence_embedder.token_embedders.tokens.type = embedding
2019-04-12 23:12:26,176 - INFO - allennlp.common.params - model.coherence_embedder.token_embedders.tokens.num_embeddings = None
2019-04-12 23:12:26,177 - INFO - allennlp.common.params - model.coherence_embedder.token_embedders.tokens.vocab_namespace = coherences
2019-04-12 23:12:26,177 - INFO - allennlp.common.params - model.coherence_embedder.token_embedders.tokens.embedding_dim = 100
2019-04-12 23:12:26,177 - INFO - allennlp.common.params - model.coherence_embedder.token_embedders.tokens.pretrained_file = None
2019-04-12 23:12:26,177 - INFO - allennlp.common.params - model.coherence_embedder.token_embedders.tokens.projection_dim = None
2019-04-12 23:12:26,177 - INFO - allennlp.common.params - model.coherence_embedder.token_embedders.tokens.trainable = True
2019-04-12 23:12:26,177 - INFO - allennlp.common.params - model.coherence_embedder.token_embedders.tokens.padding_index = None
2019-04-12 23:12:26,177 - INFO - allennlp.common.params - model.coherence_embedder.token_embedders.tokens.max_norm = None
2019-04-12 23:12:26,177 - INFO - allennlp.common.params - model.coherence_embedder.token_embedders.tokens.norm_type = 2.0
2019-04-12 23:12:26,177 - INFO - allennlp.common.params - model.coherence_embedder.token_embedders.tokens.scale_grad_by_freq = False
2019-04-12 23:12:26,177 - INFO - allennlp.common.params - model.coherence_embedder.token_embedders.tokens.sparse = True
2019-04-12 23:12:27,399 - INFO - allennlp.common.params - model.word_embedding_dropout = 0.4
2019-04-12 23:12:27,399 - INFO - allennlp.common.params - model.coherence_embedding_dropout = 0.6
2019-04-12 23:12:27,399 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.modules.seq2vec_encoders.seq2vec_encoder.Seq2VecEncoder'> from params {'bidirectional': False, 'hidden_size': 100, 'input_size': 300, 'num_layers': 1, 'type': 'lstm'} and extras {'vocab': Vocabulary with namespaces:  coherences, Size: 1561684 || sentences, Size: 2196017 || types, Size: 115 || wids, Size: 614130 || Non Padded Namespaces: {'*tags', '*labels'}}
2019-04-12 23:12:27,400 - INFO - allennlp.common.params - model.left_seq2vec.type = lstm
2019-04-12 23:12:27,400 - INFO - allennlp.common.params - model.left_seq2vec.batch_first = True
2019-04-12 23:12:27,400 - INFO - allennlp.common.params - Converting Params object to dict; logging of default values will not occur when dictionary parameters are used subsequently.
2019-04-12 23:12:27,400 - INFO - allennlp.common.params - CURRENTLY DEFINED PARAMETERS:
2019-04-12 23:12:27,400 - INFO - allennlp.common.params - Converting Params object to dict; logging of default values will not occur when dictionary parameters are used subsequently.
2019-04-12 23:12:27,400 - INFO - allennlp.common.params - CURRENTLY DEFINED PARAMETERS:
2019-04-12 23:12:27,400 - INFO - allennlp.common.params - model.left_seq2vec.bidirectional = False
2019-04-12 23:12:27,400 - INFO - allennlp.common.params - model.left_seq2vec.hidden_size = 100
2019-04-12 23:12:27,400 - INFO - allennlp.common.params - model.left_seq2vec.input_size = 300
2019-04-12 23:12:27,400 - INFO - allennlp.common.params - model.left_seq2vec.num_layers = 1
2019-04-12 23:12:27,400 - INFO - allennlp.common.params - model.left_seq2vec.batch_first = True
2019-04-12 23:12:27,402 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.modules.seq2vec_encoders.seq2vec_encoder.Seq2VecEncoder'> from params {'bidirectional': False, 'hidden_size': 100, 'input_size': 300, 'num_layers': 1, 'type': 'lstm'} and extras {'vocab': Vocabulary with namespaces:  coherences, Size: 1561684 || sentences, Size: 2196017 || types, Size: 115 || wids, Size: 614130 || Non Padded Namespaces: {'*tags', '*labels'}}
2019-04-12 23:12:27,402 - INFO - allennlp.common.params - model.right_seq2vec.type = lstm
2019-04-12 23:12:27,403 - INFO - allennlp.common.params - model.right_seq2vec.batch_first = True
2019-04-12 23:12:27,403 - INFO - allennlp.common.params - Converting Params object to dict; logging of default values will not occur when dictionary parameters are used subsequently.
2019-04-12 23:12:27,403 - INFO - allennlp.common.params - CURRENTLY DEFINED PARAMETERS:
2019-04-12 23:12:27,403 - INFO - allennlp.common.params - model.right_seq2vec.bidirectional = False
2019-04-12 23:12:27,403 - INFO - allennlp.common.params - model.right_seq2vec.hidden_size = 100
2019-04-12 23:12:27,403 - INFO - allennlp.common.params - model.right_seq2vec.input_size = 300
2019-04-12 23:12:27,403 - INFO - allennlp.common.params - model.right_seq2vec.num_layers = 1
2019-04-12 23:12:27,403 - INFO - allennlp.common.params - model.right_seq2vec.batch_first = True
2019-04-12 23:12:27,405 - INFO - allennlp.common.params - model.ff_seq2vecs.input_dim = 200
2019-04-12 23:12:27,405 - INFO - allennlp.common.params - model.ff_seq2vecs.num_layers = 1
2019-04-12 23:12:27,405 - INFO - allennlp.common.params - model.ff_seq2vecs.hidden_dims = 100
2019-04-12 23:12:27,405 - INFO - allennlp.common.params - model.ff_seq2vecs.activations = relu
2019-04-12 23:12:27,405 - INFO - allennlp.common.params - model.ff_seq2vecs.dropout = 0.4
2019-04-12 23:12:27,406 - INFO - allennlp.common.params - model.ff_context.input_dim = 200
2019-04-12 23:12:27,406 - INFO - allennlp.common.params - model.ff_context.num_layers = 1
2019-04-12 23:12:27,406 - INFO - allennlp.common.params - model.ff_context.hidden_dims = 200
2019-04-12 23:12:27,406 - INFO - allennlp.common.params - model.ff_context.activations = relu
2019-04-12 23:12:27,406 - INFO - allennlp.common.params - model.ff_context.dropout = 0.4
2019-04-12 23:12:27,407 - INFO - allennlp.nn.initializers - Initializing parameters
2019-04-12 23:12:27,407 - INFO - allennlp.nn.initializers - Done initializing parameters; the following parameters are using their default initialization from their code
2019-04-12 23:12:27,408 - INFO - allennlp.nn.initializers -    coherence_embedder.token_embedder_tokens.weight
2019-04-12 23:12:27,408 - INFO - allennlp.nn.initializers -    entity_embedder.token_embedder_tokens.weight
2019-04-12 23:12:27,408 - INFO - allennlp.nn.initializers -    ff_context._linear_layers.0.bias
2019-04-12 23:12:27,408 - INFO - allennlp.nn.initializers -    ff_context._linear_layers.0.weight
2019-04-12 23:12:27,408 - INFO - allennlp.nn.initializers -    ff_seq2vecs._linear_layers.0.bias
2019-04-12 23:12:27,408 - INFO - allennlp.nn.initializers -    ff_seq2vecs._linear_layers.0.weight
2019-04-12 23:12:27,408 - INFO - allennlp.nn.initializers -    left_seq2vec._module.bias_hh_l0
2019-04-12 23:12:27,408 - INFO - allennlp.nn.initializers -    left_seq2vec._module.bias_ih_l0
2019-04-12 23:12:27,408 - INFO - allennlp.nn.initializers -    left_seq2vec._module.weight_hh_l0
2019-04-12 23:12:27,408 - INFO - allennlp.nn.initializers -    left_seq2vec._module.weight_ih_l0
2019-04-12 23:12:27,408 - INFO - allennlp.nn.initializers -    right_seq2vec._module.bias_hh_l0
2019-04-12 23:12:27,408 - INFO - allennlp.nn.initializers -    right_seq2vec._module.bias_ih_l0
2019-04-12 23:12:27,408 - INFO - allennlp.nn.initializers -    right_seq2vec._module.weight_hh_l0
2019-04-12 23:12:27,408 - INFO - allennlp.nn.initializers -    right_seq2vec._module.weight_ih_l0
2019-04-12 23:12:27,408 - INFO - allennlp.nn.initializers -    sentence_embedder.token_embedder_tokens.weight
2019-04-12 23:12:39,664 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.data.iterators.data_iterator.DataIterator'> from params {'batch_size': 1000, 'type': 'basic'} and extras {}
2019-04-12 23:12:39,664 - INFO - allennlp.common.params - iterator.type = basic
2019-04-12 23:12:39,665 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.data.iterators.basic_iterator.BasicIterator'> from params {'batch_size': 1000} and extras {}
2019-04-12 23:12:39,665 - INFO - allennlp.common.params - iterator.batch_size = 1000
2019-04-12 23:12:39,665 - INFO - allennlp.common.params - iterator.instances_per_epoch = None
2019-04-12 23:12:39,665 - INFO - allennlp.common.params - iterator.max_instances_in_memory = None
2019-04-12 23:12:39,665 - INFO - allennlp.common.params - iterator.cache_instances = False
2019-04-12 23:12:39,665 - INFO - allennlp.common.params - iterator.track_epoch = False
2019-04-12 23:12:39,665 - INFO - allennlp.common.params - iterator.maximum_samples_per_batch = None
2019-04-12 23:12:39,665 - INFO - allennlp.common.params - validation_iterator = None
2019-04-12 23:12:39,665 - INFO - allennlp.common.params - iterator.maximum_samples_per_batch = None
2019-04-12 23:12:39,665 - INFO - allennlp.common.params - validation_iterator = None
2019-04-12 23:12:39,665 - INFO - allennlp.common.params - trainer.no_grad = ()
2019-04-12 23:12:39,666 - INFO - allennlp.training.trainer - Following parameters are Frozen  (without gradient):
2019-04-12 23:12:39,666 - INFO - allennlp.training.trainer - sentence_embedder.token_embedder_tokens.weight
2019-04-12 23:12:39,666 - INFO - allennlp.training.trainer - Following parameters are Tunable (with gradient):
2019-04-12 23:12:39,666 - INFO - allennlp.training.trainer - left_seq2vec._module.weight_ih_l0
2019-04-12 23:12:39,666 - INFO - allennlp.training.trainer - left_seq2vec._module.weight_hh_l0
2019-04-12 23:12:39,666 - INFO - allennlp.training.trainer - left_seq2vec._module.bias_ih_l0
2019-04-12 23:12:39,666 - INFO - allennlp.training.trainer - left_seq2vec._module.bias_hh_l0
2019-04-12 23:12:39,666 - INFO - allennlp.training.trainer - right_seq2vec._module.weight_ih_l0
2019-04-12 23:12:39,666 - INFO - allennlp.training.trainer - right_seq2vec._module.weight_hh_l0
2019-04-12 23:12:39,666 - INFO - allennlp.training.trainer - right_seq2vec._module.bias_ih_l0
2019-04-12 23:12:39,666 - INFO - allennlp.training.trainer - right_seq2vec._module.bias_hh_l0
2019-04-12 23:12:39,666 - INFO - allennlp.training.trainer - ff_seq2vecs._linear_layers.0.weight
2019-04-12 23:12:39,666 - INFO - allennlp.training.trainer - ff_seq2vecs._linear_layers.0.bias
2019-04-12 23:12:39,666 - INFO - allennlp.training.trainer - coherence_embedder.token_embedder_tokens.weight
2019-04-12 23:12:39,666 - INFO - allennlp.training.trainer - ff_context._linear_layers.0.weight
2019-04-12 23:12:39,666 - INFO - allennlp.training.trainer - ff_context._linear_layers.0.bias
2019-04-12 23:12:39,666 - INFO - allennlp.training.trainer - entity_embedder.token_embedder_tokens.weight
2019-04-12 23:12:39,666 - INFO - allennlp.common.params - trainer.patience = None
2019-04-12 23:12:39,666 - INFO - allennlp.common.params - trainer.validation_metric = -loss
2019-04-12 23:12:39,667 - INFO - allennlp.common.params - trainer.shuffle = True
2019-04-12 23:12:39,667 - INFO - allennlp.common.params - trainer.num_epochs = 1
2019-04-12 23:12:39,667 - INFO - allennlp.common.params - trainer.cuda_device = [0, 1]
2019-04-12 23:12:39,667 - INFO - allennlp.common.params - trainer.grad_norm = None
2019-04-12 23:12:39,667 - INFO - allennlp.common.params - trainer.grad_clipping = 5
2019-04-12 23:12:39,667 - INFO - allennlp.common.params - trainer.learning_rate_scheduler = None
2019-04-12 23:12:39,667 - INFO - allennlp.common.params - trainer.momentum_scheduler = None
2019-04-12 23:12:45,797 - INFO - allennlp.common.params - trainer.optimizer.type = dense_sparse_adam
2019-04-12 23:12:45,797 - INFO - allennlp.common.params - trainer.optimizer.parameter_groups = None
2019-04-12 23:12:45,797 - INFO - allennlp.training.optimizers - Number of trainable parameters: 279376300
2019-04-12 23:12:45,800 - INFO - allennlp.common.params - trainer.optimizer.infer_type_and_cast = True
2019-04-12 23:12:45,800 - INFO - allennlp.common.params - Converting Params object to dict; logging of default values will not occur when dictionary parameters are used subsequently.
2019-04-12 23:12:45,800 - INFO - allennlp.common.params - CURRENTLY DEFINED PARAMETERS:
2019-04-12 23:12:45,800 - INFO - allennlp.common.params - trainer.optimizer.lr = 0.005
2019-04-12 23:12:45,801 - INFO - allennlp.common.params - trainer.num_serialized_models_to_keep = 20
2019-04-12 23:12:45,801 - INFO - allennlp.common.params - trainer.keep_serialized_model_every_num_seconds = None
2019-04-12 23:12:45,801 - INFO - allennlp.common.params - trainer.model_save_interval = None
2019-04-12 23:12:45,801 - INFO - allennlp.common.params - trainer.summary_interval = 100
2019-04-12 23:12:45,801 - INFO - allennlp.common.params - trainer.histogram_interval = None
2019-04-12 23:12:45,801 - INFO - allennlp.common.params - trainer.should_log_parameter_statistics = True
2019-04-12 23:12:45,801 - INFO - allennlp.common.params - trainer.should_log_learning_rate = False
2019-04-12 23:12:45,801 - INFO - allennlp.common.params - trainer.log_batch_size_period = None
2019-04-12 23:12:45,801 - WARNING - allennlp.training.trainer_base - Multiple GPU support is experimental not recommended for use. In some cases it may lead to incorrect results or undefined behavior.
2019-04-12 23:12:45,801 - WARNING - allennlp.training.trainer - You provided a validation dataset but patience was set to None, meaning that early stopping is disabled
2019-04-12 23:12:45,826 - INFO - allennlp.training.trainer - Beginning training.
2019-04-12 23:12:45,827 - INFO - allennlp.training.trainer - Epoch 0/0
2019-04-12 23:12:45,827 - INFO - allennlp.training.trainer - Peak CPU memory usage MB: 27019.9
2019-04-12 23:12:46,985 - INFO - allennlp.training.trainer - GPU 0 memory usage MB: 4175
2019-04-12 23:12:46,985 - INFO - allennlp.training.trainer - GPU 1 memory usage MB: 10
2019-04-12 23:12:46,986 - INFO - allennlp.training.trainer - GPU 2 memory usage MB: 9361
2019-04-12 23:12:46,986 - INFO - allennlp.training.trainer - GPU 3 memory usage MB: 10
2019-04-12 23:12:46,986 - INFO - allennlp.training.trainer - Training
2019-04-12 23:12:46,989 - WARNING - allennlp.data.fields.label_field - Your label namespace was 'label'. We recommend you use a namespace ending with 'labels' or 'tags', so we don't add UNK and PAD tokens by default to your vocabulary.  See documentation for `non_padded_namespaces` parameter in Vocabulary.

**Comment by matt-gardner** [comment]
Thanks @junkyul.  The way our multi-GPU code works is that we replicate the model across all GPUs, so we can process one batch per GPU.  The code then aggregates the results from all GPUs, computes gradients, and takes an optimizer step.  That is, we do _data parallel_ computation, not _model parallel_ computation.  So we can't just decide to use the memory on a separate GPU if the model doesn't fit on a single GPU in the first place.

I'm pretty sure that answers your question, but feel free to let me know if it didn't (and anyone else reading along, I'm _pretty sure_ what I said about the multi-GPU stuff was accurate, but please correct me if I'm wrong).
