### ISSUE TITLE
Not able to install allennlp 

### ISSUE THREAD

**Issue by Akshit99** [allenai/allennlp#2736]
**System:**
 - OS: ubuntu 18.04
 - Python version: 3.6.7
 - AllenNLP version: install from pip
 - PyTorch version: from pip

**Question**
Not able to install allennlp in a ubuntu instance in AWS. Error report says "Memory Error" when it start installing from .whl file. Tried to install using pip3 install allennlp

    99% |████████████████████████████████| 582.5MB 39.0MB/s eta 0:00:01
Exception                                                                                        :
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 353, in ru                                                                     n
    wb.build(autobuilding=True)
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 380, in prepare                                                                                        _files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 620, in _prepar                                                                                        e_file
    session=self.session, hashes=hashes)
  File "/usr/lib/python3/dist-packages/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/usr/lib/python3/dist-packages/pip/download.py", line 659, in unpack_htt                                                                                        p_url
    hashes)
  File "/usr/lib/python3/dist-packages/pip/download.py", line 882, in _download_                                                                                        http_url
    _download_url(resp, link, content_file, hashes)
  File "/usr/lib/python3/dist-packages/pip/download.py", line 603, in _download_                                                                                        url
    hashes.check_against_chunks(downloaded_chunks)
  File "/usr/lib/python3/dist-packages/pip/utils/hashes.py", line 46, in check_a                                                                                        gainst_chunks
    for chunk in chunks:
  File "/usr/lib/python3/dist-packages/pip/download.py", line 571, in written_ch                                                                                        unks
    for chunk in chunks:
  File "/usr/lib/python3/dist-packages/pip/utils/ui.py", line 139, in iter
    for x in it:
  File "/usr/lib/python3/dist-packages/pip/download.py", line 560, in resp_read
    decode_content=False):
  File "/usr/share/python-wheels/urllib3-1.22-py2.py3-none-any.whl/urllib3/respo                                                                                        nse.py", line 436, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/share/python-wheels/urllib3-1.22-py2.py3-none-any.whl/urllib3/respo                                                                                        nse.py", line 384, in read
    data = self._fp.read(amt)
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachec                                                                                        ontrol/filewrapper.py", line 63, in read
    self._close()
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachec                                                                                        ontrol/filewrapper.py", line 50, in _close
    self.__callback(self.__buf.getvalue())
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachec                                                                                        ontrol/controller.py", line 275, in cache_response
    self.serializer.dumps(request, response, body=body),
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachec                                                                                        ontrol/serialize.py", line 55, in dumps
    "body": _b64_encode_bytes(body),
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachec                                                                                        ontrol/serialize.py", line 12, in _b64_encode_bytes
    return base64.b64encode(b).decode("ascii")
  File "/usr/lib/python3.6/base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
MemoryError

**Comment by DeNeutoy** [comment]
It seems like your machine may have run out of memory. I would suggest checking that, as it seems like this is not a general problem with installing allennlp (from the stack trace you gave). Feel free to re-open if you run into other issues!

**Comment by AhmedAtt** [comment]
I still encounter the same problem, to be more precise, the instance I am using is t2.micro, with the same system specs that @Akshit99  have. 
I am not sure if this is relevant but I was able to pull the docker image successfully.

**Comment by AhmedAtt** [comment]
The issue is still happening when using the bigger t3.medium machine with 4GB of memory.  
specifically when downloading this file " https://files.pythonhosted.org/packages/24/19/4804aea17cd136f1705a5e98a00618cb8f6ccc375ad8bfa437408e09d058/torch-1.4.0-cp36-cp36m-manylinux1_x86_64.whl "

**Comment by kz-umesh** [comment]
I ran in exact same issue, was anyone able to fix it? @AhmedAtt ?

**Comment by AhmedAtt** [comment]
@kz-umesh I solved it by increasing the device's EBS storage to 16gb instead of the default 8gb, then the installation will run without any issues

**Comment by kz-umesh** [comment]
thanks for replying @AhmedAtt , not working for me unfortunately. I have 20 GB and 4 GB RAM, t3.medium instance on AWS.

**Comment by kz-umesh** [comment]
Worked! Installed on Ubuntu 16.04, was trying on 18.04 earlier.
