### ISSUE TITLE
WikiTables FileNotFoundException context.tsv

### ISSUE THREAD

**Issue by SandeepBhutani** [allenai/allennlp#2747]
**Describe the bug**
While Using WikiTables Started Getting **java.lang.RuntimeException: java.io.FileNotFoundException: data/tsv/context.tsv (No such file or directory)**  in **edu.stanford.nlp.sempre.tables.serialize.TableReader.parseTSV(TableReader.java:65)**   
This started happening after I enabled apex  
Exact Stacktrace:

```
java.lang.RuntimeException: java.io.FileNotFoundException: data/tsv/context.tsv (No such file or directory)
        at edu.stanford.nlp.sempre.tables.serialize.TableReader.parseTSV(TableReader.java:75)
        at edu.stanford.nlp.sempre.tables.serialize.TableReader.<init>(TableReader.java:39)
        at edu.stanford.nlp.sempre.tables.TableKnowledgeGraph.<init>(TableKnowledgeGraph.java:148)
        at edu.stanford.nlp.sempre.tables.TableKnowledgeGraph.fromRootedFilename(TableKnowledgeGraph.java:162)
        at edu.stanford.nlp.sempre.tables.TableKnowledgeGraph.fromFilename(TableKnowledgeGraph.java:174)
        at edu.stanford.nlp.sempre.tables.TableKnowledgeGraph.fromLispTree(TableKnowledgeGraph.java:181)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at edu.stanford.nlp.sempre.KnowledgeGraph.fromLispTree(KnowledgeGraph.java:27)
        at edu.stanford.nlp.sempre.ContextValue.<init>(ContextValue.java:91)
        at edu.stanford.nlp.sempre.tables.test.CustomExample.fromLispTree(CustomExample.java:63)
        at org.allenai.wikitables.Executor$$anonfun$3.apply(Executor.scala:47)
        at org.allenai.wikitables.Executor$$anonfun$3.apply(Executor.scala:38)
        at scala.collection.parallel.AugmentedIterableIterator$class.map2combiner(RemainsIterator.scala:115)
        at scala.collection.parallel.immutable.ParVector$ParVectorIterator.map2combiner(ParVector.scala:62)
        at scala.collection.parallel.ParIterableLike$Map.leaf(ParIterableLike.scala:1054)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:49)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
        at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:51)
        at scala.collection.parallel.ParIterableLike$Map.tryLeaf(ParIterableLike.scala:1051)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:152)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:443)
        at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinTask.doJoin(ForkJoinTask.java:341)
        at scala.concurrent.forkjoin.ForkJoinTask.join(ForkJoinTask.java:673)
        at scala.collection.parallel.ForkJoinTasks$WrappedTask$class.sync(Tasks.scala:378)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.sync(Tasks.scala:443)
        at scala.collection.parallel.ForkJoinTasks$class.executeAndWaitResult(Tasks.scala:426)
        at scala.collection.parallel.ForkJoinTaskSupport.executeAndWaitResult(TaskSupport.scala:56)
        at scala.collection.parallel.ExecutionContextTasks$class.executeAndWaitResult(Tasks.scala:558)
        at scala.collection.parallel.ExecutionContextTaskSupport.executeAndWaitResult(TaskSupport.scala:80)
        at scala.collection.parallel.ParIterableLike$ResultMapping.leaf(ParIterableLike.scala:958)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:49)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
        at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:51)
        at scala.collection.parallel.ParIterableLike$ResultMapping.tryLeaf(ParIterableLike.scala:953)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:152)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:443)
        at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.io.FileNotFoundException: data/tsv/context.tsv (No such file or directory)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
        at java.base/java.io.FileReader.<init>(FileReader.java:60)
        at edu.stanford.nlp.sempre.tables.serialize.TableReader.parseTSV(TableReader.java:65)
        ... 47 more
```

**System (please complete the following information):**
 - OS: [e.g. OSX, Linux] Linux
 - Python version: [if it's not 3.6.1 or later, that's probably your problem]
 - AllenNLP version: [e.g. v0.8.3, or "I installed from master"]  
 - PyTorch version: (if you installed it yourself)  

**Additional context**

**Comment by matt-gardner** [comment]
We are in the process of moving away from the SEMPRE-based WikiTables parser implementation to a better-performing one that's based on python code (see https://github.com/allenai/allennlp/pull/2637).  So, sorry, I'm going to close this as "won't fix".
