### ISSUE TITLE
"arguments are located on different GPUs" when training stacked_self_attention as encoder

### ISSUE THREAD

**Issue by JizeCao** [allenai/allennlp#2776]
Please first search our GitHub repository for similar questions.  If you don't find a similar example you can use the following template:

**System (please complete the following information):**
 - OS:  Linux
 - Python version: 3.6.5
 - AllenNLP version: "I installed from master"
 - PyTorch version: Pytorch 1.01

**Question**

I apply the ``stacked_self_attention`` module as the Seq2SeqEncoder over a sequence of embeddings and encounter the error "arguments are located on different GPUs". If I switch it to ``multi_head_attention`` or ``lstm``, then everything is fine.

Here is the whole trace:
`Traceback (most recent call last):
  File "train.py", line 156, in <module>
    output_dict = model(**batch)
  File "/home/caojize/anaconda3/envs/r2c/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/caojize/anaconda3/envs/r2c/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 143, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/caojize/anaconda3/envs/r2c/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 153, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/caojize/anaconda3/envs/r2c/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
    raise output
  File "/home/caojize/anaconda3/envs/r2c/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 59, in _worker
    output = module(*input, **kwargs)
  File "/home/caojize/anaconda3/envs/r2c/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/raid/caojize/microsoft_r2c/models/transformer/model.py", line 135, in forward
    qa_rep = self.span_encoder(qa_rep, qa_mask)
  File "/home/caojize/anaconda3/envs/r2c/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/caojize/anaconda3/envs/r2c/lib/python3.6/site-packages/allennlp/modules/time_distributed.py", line 35, in forward
    reshaped_outputs = self._module(*reshaped_inputs)
  File "/home/caojize/anaconda3/envs/r2c/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/caojize/anaconda3/envs/r2c/lib/python3.6/site-packages/allennlp/modules/seq2seq_encoders/stacked_self_attention.py", line 143, in forward
    feedforward_output = feedforward(output)
  File "/home/caojize/anaconda3/envs/r2c/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/caojize/anaconda3/envs/r2c/lib/python3.6/site-packages/allennlp/modules/feedforward.py", line 80, in forward
    output = dropout(activation(layer(output)))
  File "/home/caojize/anaconda3/envs/r2c/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/caojize/anaconda3/envs/r2c/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 67, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/caojize/anaconda3/envs/r2c/lib/python3.6/site-packages/torch/nn/functional.py", line 1354, in linear
    output = input.matmul(weight.t())
RuntimeError: arguments are located on different GPUs at /opt/conda/conda-bld/pytorch_1549628766161/work/aten/src/THC/generic/THCTensorMathBlas.cu:253`

**Comment by matt-gardner** [comment]
I _think_ the solution is that these need to be `ModuleLists`, instead of how it's currently implemented: https://github.com/allenai/allennlp/blob/3170f6f3e089062b522986ed906ef1ef1b68bf90/allennlp/modules/seq2seq_encoders/stacked_self_attention.py#L75-L78

See #2692 and #2773.

**Comment by JizeCao** [comment]
Cool! This fix my problem. Thanks!

**Comment by matt-gardner** [comment]
Reopening, because the bug needs to be fixed in the library. Care to submit a PR?

**Comment by JizeCao** [comment]
Yeah, I have submitted a PR for this, [#2780](https://github.com/allenai/allennlp/pull/2780)
