### ISSUE TITLE
Service for Named Entity Recognition

### ISSUE THREAD

**Issue by MNandu** [allenai/allennlp#2781]
- OS: [e.g. OSX, Linux]
 - Python version: [e.g. 3.6.1]
 - AllenNLP version: [e.g. v0.8.3, or "I installed from master"]
 - PyTorch version: (if you installed it yourself)

**Question**
I am trying to run Named Entity Recognition as a service.
on running the code I am getting below error:

Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex.
/usr/local/lib/python3.6/dist-packages/allennlp/data/token_indexers/token_characters_indexer.py:51: UserWarning: You are using the default value (0) of `min_padding_length`, which can cause some subtle bugs (more info see https://github.com/allenai/allennlp/issues/1954). Strongly recommend to set a value, usually the maximum size of the convolutional layer size when using CnnEncoder.
  UserWarning)
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/allennlp/service/server_simple.py", line 758, in <module>
    main(sys.argv[1:])
  File "/usr/local/lib/python3.6/dist-packages/allennlp/service/server_simple.py", line 182, in main
    predictor = _get_predictor(args)
  File "/usr/local/lib/python3.6/dist-packages/allennlp/service/server_simple.py", line 148, in _get_predictor
    return Predictor.from_archive(archive, args.predictor)
  File "/usr/local/lib/python3.6/dist-packages/allennlp/predictors/predictor.py", line 167, in from_archive
    return Predictor.by_name(predictor_name)(model, dataset_reader)
  File "/usr/local/lib/python3.6/dist-packages/allennlp/common/registrable.py", line 58, in by_name
    raise ConfigurationError("%s is not a registered name for %s" % (name, cls.__name__))
allennlp.common.checks.ConfigurationError: 'named-entity-recognition is not a registered name for Predictor'

can anyone please let me what could be the issue.
According to me named-entity-recognition is the exact name but still I am getting error

**Comment by Aki58** [comment]
name of the predictor is sentence-tagger

**Comment by MNandu** [comment]
thanks for your reply.it is working .
