### ISSUE TITLE
A problem about evaluating: RuntimeError: index out of range at...

### ISSUE THREAD

**Issue by echo-cheng** [allenai/allennlp#2832]
**System :**
 - OS: [ Linux]
 - Python version: 3.7.1
 - AllenNLP version: 0.7.1

**Question**
*  while I am evaluating the model I've trained on test dataset, the evaluate module thows a Runtime error, like this:
`2019-05-13 16:44:09,762 - INFO - allennlp.commands.evaluate - Iterating over dataset
accuracy: 0.64, accuracy3: 0.94 ||: : 2it [00:01,  1.25it/s]                                                                                                                                                Traceback (most recent call last):
  File "/home/jing/.conda/envs/py34venv/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/jing/.conda/envs/py34venv/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jing/.conda/envs/py34venv/lib/python3.7/site-packages/allennlp/run.py", line 18, in <module>
    main(prog="allennlp")
  File "/home/jing/.conda/envs/py34venv/lib/python3.7/site-packages/allennlp/commands/__init__.py", line 72, in main
    args.func(args)
  File "/home/jing/.conda/envs/py34venv/lib/python3.7/site-packages/allennlp/commands/evaluate.py", line 151, in evaluate_from_args
    metrics = evaluate(model, instances, iterator, args.cuda_device)
  File "/home/jing/.conda/envs/py34venv/lib/python3.7/site-packages/allennlp/commands/evaluate.py", line 105, in evaluate
    model(**batch)
  File "/home/jing/.conda/envs/py34venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jing/Documents/pycharmLinux/BCN_Allennlp/BCN_CoVe/biattentive_classification_network.py", line 208, in forward
    embedded_text = self._text_field_embedder(tokens)
  File "/home/jing/.conda/envs/py34venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jing/.conda/envs/py34venv/lib/python3.7/site-packages/allennlp/modules/text_field_embedders/basic_text_field_embedder.py", line 107, in forward
    token_vectors = embedder(*tensors)
  File "/home/jing/.conda/envs/py34venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jing/.conda/envs/py34venv/lib/python3.7/site-packages/allennlp/modules/token_embedders/embedding.py", line 141, in forward
    sparse=self.sparse)
  File "/home/jing/.conda/envs/py34venv/lib/python3.7/site-packages/torch/nn/functional.py", line 1110, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: index out of range at /opt/conda/conda-bld/pytorch_1535493744281/work/aten/src/TH/generic/THTensorMath.cpp:352
[INFO/MainProcess] process shutting down`

And my configuration file is:

> {
    "dataset_reader": {
        "type": "trec6",
        "lazy": true,
        "token_indexers": {
            "tokens": {
                "type": "single_id",
                "lowercase_tokens": true
            }
        }
    },
    "train_data_path": "experiments/dataset/TREC/train.txt",
    "validation_data_path": "experiments/dataset/TREC/dev.txt",
    "test_data_path": "experiments/dataset/TREC/test.txt",
    "model": {
        "type": "bcn",
        "text_field_embedder": {
            "tokens": {
                "type": "embedding",
                "embedding_dim": 300,
                "pretrained_file": "experiments/dataset/glove.840B.300d.txt",
                "trainable": false
            }
        },
        "embedding_dropout": 0.5,
        "pre_encode_feedforward": {
            "activations": ["relu"],
            "hidden_dims": 300,
            "input_dim": 300,
            "num_layers": 1
        },
        "encoder": {
            "type": "lstm",
            "bidirectional": true,
            "hidden_size": 300,
            "input_size": 300,
            "num_layers": 1
        },
        "integrator": {
            "type": "lstm",
            "bidirectional": true,
            "hidden_size": 300,
            "input_size": 1800,
            "num_layers": 1
        },
        "integrator_dropout": 0.5,
        "output_layer": {
            "input_dim": 2400,
            "num_layers": 3,
            "output_dims": [600, 300, 6],
            "pool_sizes": 4
        }
    },
    "iterator": {
        "type": "bucket",
        "batch_size": 64,
        "max_instances_in_memory": 5120,
        "sorting_keys": [["tokens", "num_tokens"]]
    },
    "trainer": {
        "cuda_device": 0,
        "num_epochs": 15,
        "optimizer": {
            "type": "adam",
            "lr": 0.002
        },
        "patience": 10,
        "validation_metric": "+accuracy"
    }
}autism

I found the tokenizer couldn't get the right token sequences of inputs on evaluating, but it could get right results on training.

For example, when I evaluate model  on a dataset, the vocabulary is[?, is, what, autism], the input is:"What is autism ?",the token result is:[3, 2,4,1]. But in fact,the correct answer is:[2, 1,3,0]. Why?

The dataset reader is:

`
 @DatasetReader.register("trec6")
 class TREC6Reader(DatasetReader):
 def__init__(self,lazy:bool=False,tokenizer:Tokenizer=None,token_indexers:Dict[str,TokenIndexer]=None) -> None:
        super().__init__(lazy)
        self._tokenizer = tokenizer or WordTokenizer()
        self.token_indexers = token_indexers or {"tokens": SingleIdTokenIndexer()}

    @overrides
    def _read(self, file_path: str):
        with open(file_path, encoding='utf8') as f:
            for line in f.readlines():
                line = line.strip('\n').strip(' ')
                if not line:
                    continue
                sample = line.split(' ', 1)
                yield self.text_to_instance(sample[1], sample[0].split(':', 1)[0])

    @overrides
    def text_to_instance(self, tokens: str, label: str = None)->Instance:
        sentence_field = TextField(self._tokenizer.tokenize(text=tokens), self.token_indexers)
        fields = {'tokens': sentence_field}
        if label:
            label_filed = LabelField(label)
            fields['label'] = label_filed
        return Instance(fields)`

**Comment by echo-cheng** [comment]
been solved.
