### ISSUE TITLE
ImportError: dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by laubonghaudoi** [allenai/allennlp#285]
I installed AllenNLP from source, and when I followed the steps on the Getting Started page to run the command `python -m allennlp.run`, it occured the following errors:
```bash

Traceback (most recent call last):
  File "/data/bo718.wang/anaconda3/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/data/bo718.wang/anaconda3/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/bo718.wang/anaconda3/lib/python3.5/site-packages/allennlp/run.py", line 10, in <module>
    from allennlp.commands import main  # pylint: disable=wrong-import-position
  File "/data/bo718.wang/anaconda3/lib/python3.5/site-packages/allennlp/commands/__init__.py", line 3, in <module>
    from allennlp.commands.serve import add_subparser as add_serve_subparser
  File "/data/bo718.wang/anaconda3/lib/python3.5/site-packages/allennlp/commands/serve.py", line 27, in <module>
    from allennlp.service import server_sanic
  File "/data/bo718.wang/anaconda3/lib/python3.5/site-packages/allennlp/service/server_sanic.py", line 19, in <module>
    from allennlp.models.archival import load_archive
  File "/data/bo718.wang/anaconda3/lib/python3.5/site-packages/allennlp/models/__init__.py", line 6, in <module>
    from allennlp.models.archival import archive_model, load_archive
  File "/data/bo718.wang/anaconda3/lib/python3.5/site-packages/allennlp/models/archival.py", line 10, in <module>
    from allennlp.models.model import Model, _DEFAULT_WEIGHTS
  File "/data/bo718.wang/anaconda3/lib/python3.5/site-packages/allennlp/models/model.py", line 12, in <module>
    from allennlp.data import Vocabulary
  File "/data/bo718.wang/anaconda3/lib/python3.5/site-packages/allennlp/data/__init__.py", line 1, in <module>
    from allennlp.data.dataset import Dataset
  File "/data/bo718.wang/anaconda3/lib/python3.5/site-packages/allennlp/data/dataset.py", line 13, in <module>
    from allennlp.data.instance import Instance
  File "/data/bo718.wang/anaconda3/lib/python3.5/site-packages/allennlp/data/instance.py", line 3, in <module>
    from allennlp.data.fields.field import DataArray, Field
  File "/data/bo718.wang/anaconda3/lib/python3.5/site-packages/allennlp/data/fields/__init__.py", line 12, in <module>
    from allennlp.data.fields.text_field import TextField
  File "/data/bo718.wang/anaconda3/lib/python3.5/site-packages/allennlp/data/fields/text_field.py", line 11, in <module>
    from allennlp.data.token_indexers.token_indexer import TokenIndexer, TokenType
  File "/data/bo718.wang/anaconda3/lib/python3.5/site-packages/allennlp/data/token_indexers/__init__.py", line 6, in <module>
    from allennlp.data.token_indexers.token_characters_indexer import TokenCharactersIndexer
  File "/data/bo718.wang/anaconda3/lib/python3.5/site-packages/allennlp/data/token_indexers/token_characters_indexer.py", line 10, in <module>
    from allennlp.data.tokenizers.character_tokenizer import CharacterTokenizer
  File "/data/bo718.wang/anaconda3/lib/python3.5/site-packages/allennlp/data/tokenizers/__init__.py", line 7, in <module>
    from allennlp.data.tokenizers.word_tokenizer import WordTokenizer
  File "/data/bo718.wang/anaconda3/lib/python3.5/site-packages/allennlp/data/tokenizers/word_tokenizer.py", line 13, in <module>
    class WordTokenizer(Tokenizer):
  File "/data/bo718.wang/anaconda3/lib/python3.5/site-packages/allennlp/data/tokenizers/word_tokenizer.py", line 39, in WordTokenizer
    word_splitter: WordSplitter = SpacyWordSplitter(),
  File "/data/bo718.wang/anaconda3/lib/python3.5/site-packages/allennlp/data/tokenizers/word_splitter.py", line 144, in __init__
    import spacy
  File "/data/bo718.wang/anaconda3/lib/python3.5/site-packages/spacy/__init__.py", line 5, in <module>
    from .deprecated import resolve_model_name
  File "/data/bo718.wang/anaconda3/lib/python3.5/site-packages/spacy/deprecated.py", line 8, in <module>
    from .cli import download
  File "/data/bo718.wang/anaconda3/lib/python3.5/site-packages/spacy/cli/__init__.py", line 5, in <module>
    from .train import train, train_config
  File "/data/bo718.wang/anaconda3/lib/python3.5/site-packages/spacy/cli/train.py", line 8, in <module>
    from ..scorer import Scorer
  File "/data/bo718.wang/anaconda3/lib/python3.5/site-packages/spacy/scorer.py", line 4, in <module>
    from .gold import tags_to_entities
ImportError: dlopen: cannot load any more object with static TLS
```
I googled the error message `dlopen: cannot load any more object with static TLS` and found that this issuse seems to be related to the import of spacy package, and changing the importing order might help. But when I looked into the source code I found nothing that can get fixed. Up to now I haven't successfully run any demo on my machine. Anybody also encountered the same problem?

**Comment by DeNeutoy** [comment]
Hi! 
It looks like you are using python 3.5 anaconda distribution. Allennlp requires python 3.6 - I don't know if this is the cause of the above problem, but you should follow the instructions for creating a python 3.6 conda environment in the readme.

**Comment by laubonghaudoi** [comment]
Thank you, but will AllenNLP support python 3.5 or python 2.7 in the future ?

**Comment by matt-gardner** [comment]
No, we won't. We use type annotations throughout the code, and we like them. Using a modern version of python is easy, using anaconda, docker or many other tools.

**Comment by laubonghaudoi** [comment]
I reinstall anaconda 4.3.1 with Python 3.6.0 (it seems that AllenNLP neither support Python 3.6.1, will you support that in the future by the way ?), but the same error still occurs when I run the command `python -m allennlp.run`.
```bash
Traceback (most recent call last):
  File "/data/bo718.wang/lau/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/data/bo718.wang/lau/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/bo718.wang/lau/anaconda3/lib/python3.6/site-packages/allennlp/run.py", line 10, in <module>
    from allennlp.commands import main  # pylint: disable=wrong-import-position
  File "/data/bo718.wang/lau/anaconda3/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 3, in <module>
    from allennlp.commands.serve import add_subparser as add_serve_subparser
  File "/data/bo718.wang/lau/anaconda3/lib/python3.6/site-packages/allennlp/commands/serve.py", line 27, in <module>
    from allennlp.service import server_sanic
  File "/data/bo718.wang/lau/anaconda3/lib/python3.6/site-packages/allennlp/service/server_sanic.py", line 20, in <module>
    from allennlp.models.archival import load_archive
  File "/data/bo718.wang/lau/anaconda3/lib/python3.6/site-packages/allennlp/models/__init__.py", line 6, in <module>
    from allennlp.models.archival import archive_model, load_archive
  File "/data/bo718.wang/lau/anaconda3/lib/python3.6/site-packages/allennlp/models/archival.py", line 10, in <module>
    from allennlp.models.model import Model, _DEFAULT_WEIGHTS
  File "/data/bo718.wang/lau/anaconda3/lib/python3.6/site-packages/allennlp/models/model.py", line 12, in <module>
    from allennlp.data import Instance, Vocabulary
  File "/data/bo718.wang/lau/anaconda3/lib/python3.6/site-packages/allennlp/data/__init__.py", line 1, in <module>
    from allennlp.data.dataset import Dataset
  File "/data/bo718.wang/lau/anaconda3/lib/python3.6/site-packages/allennlp/data/dataset.py", line 13, in <module>
    from allennlp.data.instance import Instance
  File "/data/bo718.wang/lau/anaconda3/lib/python3.6/site-packages/allennlp/data/instance.py", line 3, in <module>
    from allennlp.data.fields.field import DataArray, Field
  File "/data/bo718.wang/lau/anaconda3/lib/python3.6/site-packages/allennlp/data/fields/__init__.py", line 13, in <module>
    from allennlp.data.fields.text_field import TextField
  File "/data/bo718.wang/lau/anaconda3/lib/python3.6/site-packages/allennlp/data/fields/text_field.py", line 11, in <module>
    from allennlp.data.token_indexers.token_indexer import TokenIndexer, TokenType
  File "/data/bo718.wang/lau/anaconda3/lib/python3.6/site-packages/allennlp/data/token_indexers/__init__.py", line 6, in <module>
    from allennlp.data.token_indexers.token_characters_indexer import TokenCharactersIndexer
  File "/data/bo718.wang/lau/anaconda3/lib/python3.6/site-packages/allennlp/data/token_indexers/token_characters_indexer.py", line 10, in <module>
    from allennlp.data.tokenizers.character_tokenizer import CharacterTokenizer
  File "/data/bo718.wang/lau/anaconda3/lib/python3.6/site-packages/allennlp/data/tokenizers/__init__.py", line 7, in <module>
    from allennlp.data.tokenizers.word_tokenizer import WordTokenizer
  File "/data/bo718.wang/lau/anaconda3/lib/python3.6/site-packages/allennlp/data/tokenizers/word_tokenizer.py", line 8, in <module>
    from allennlp.data.tokenizers.word_splitter import WordSplitter, SpacyWordSplitter
  File "/data/bo718.wang/lau/anaconda3/lib/python3.6/site-packages/allennlp/data/tokenizers/word_splitter.py", line 4, in <module>
    import spacy
  File "/data/bo718.wang/lau/anaconda3/lib/python3.6/site-packages/spacy/__init__.py", line 5, in <module>
    from .deprecated import resolve_model_name
  File "/data/bo718.wang/lau/anaconda3/lib/python3.6/site-packages/spacy/deprecated.py", line 8, in <module>
    from .cli import download
  File "/data/bo718.wang/lau/anaconda3/lib/python3.6/site-packages/spacy/cli/__init__.py", line 5, in <module>
    from .train import train, train_config
  File "/data/bo718.wang/lau/anaconda3/lib/python3.6/site-packages/spacy/cli/train.py", line 8, in <module>
    from ..scorer import Scorer
  File "/data/bo718.wang/lau/anaconda3/lib/python3.6/site-packages/spacy/scorer.py", line 4, in <module>
    from .gold import tags_to_entities
ImportError: dlopen: cannot load any more object with static TLS
```
I have followed all the instructions on the Getting Started page, this issue seems unrelated to the python versioning.

**Comment by matt-gardner** [comment]
Did you install by cloning the repo? If not, can you do that, then try putting `import spacy` at the top of `allennlp/run.py`?

**Comment by matt-gardner** [comment]
And what error do you see with python 3.6.1?  I'd expect that to work.  We should be supporting python >= 3.6.

**Comment by laubonghaudoi** [comment]
The first time (the first post where I was using python 3.5) I was installing from source.  As I failed, the second time I installed Anaconda 4.4.0 with Python 3.6.1 and then installed AllenNLP with pip. When I ran `pip install allennlp` it said:
```bash
Collecting allennlp
  Downloading http://mirrors.aliyun.com/pypi/packages/60/b0/b879eaf6350952b5e6e50fb4fc27cd13edf7b956c087b6e0a97c15660a99/allennlp-0.2.0-py3-none-any.whl (255kB)
    100% |████████████████████████████████| 256kB 245kB/s
allennlp requires Python '==3.6' but the running Python is 3.6.1
```
Then I tried to install from source (running the `python setup.py install` command in the unzipped directory). The installation was successful.

To confirm that the pip installation error only occurs in python 3.6.1, I uninstalled my Anaconda 4.4.0 and reinstalled the Anaconda 4.3.1 with Python 3.6.0, and ran the command `pip install allennlp`. The installation was successful.

But in the above two cases, the error message in the first post still occured when I ran the command `python -m allennlp.run`. So I followed your instructions to add a line of `import spacy` at the top of `allennlp/run.py` , and ran `python run.py`. The error messages in the above posts occured again, exatly the same, `ImportError: dlopen: cannot load any more object with static TLS`.

**Comment by matt-gardner** [comment]
This was not just a python version issue, so that PR did not solve this.

**Comment by matt-gardner** [comment]
@laubonghaudoi, can you give the full trace for when you put the import at the top of `allennlp/run.py`?  Seems like it _has_ to be different; make sure it's the first line in the file.  If that still crashes, my guess is that there's something up with your spacy installation; maybe you already had a version installed, and something got messed up, or something?  Or maybe you're on a machine that doesn't have enough RAM, or something ([this issue](https://stackoverflow.com/questions/19268293/matlab-error-cannot-open-with-static-tls) makes me wonder if it's something to do with that)?

**Comment by laubonghaudoi** [comment]
After the successful installation of AllenNLP under Python 3.6.0，I ran the command `python -m spacy download en` and successfully installed the downloaded `en_core_web_sm-1.2.0.tar.gz` model.

 So I ran the command `python -m allennlp.run`, and it showed the following error messages:
```bash
Traceback (most recent call last):
  File "/data/bo718.wang/lau/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/data/bo718.wang/lau/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/bo718.wang/lau/anaconda3/lib/python3.6/site-packages/allennlp/run.py", line 10, in <module>
    from allennlp.commands import main  # pylint: disable=wrong-import-position
  File "/data/bo718.wang/lau/anaconda3/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 3, in <module>
    from allennlp.commands.serve import add_subparser as add_serve_subparser
  File "/data/bo718.wang/lau/anaconda3/lib/python3.6/site-packages/allennlp/commands/serve.py", line 27, in <module>
    from allennlp.service import server_sanic
  File "/data/bo718.wang/lau/anaconda3/lib/python3.6/site-packages/allennlp/service/server_sanic.py", line 20, in <module>
    from allennlp.models.archival import load_archive
  File "/data/bo718.wang/lau/anaconda3/lib/python3.6/site-packages/allennlp/models/__init__.py", line 6, in <module>
    from allennlp.models.archival import archive_model, load_archive
  File "/data/bo718.wang/lau/anaconda3/lib/python3.6/site-packages/allennlp/models/archival.py", line 10, in <module>
    from allennlp.models.model import Model, _DEFAULT_WEIGHTS
  File "/data/bo718.wang/lau/anaconda3/lib/python3.6/site-packages/allennlp/models/model.py", line 12, in <module>
    from allennlp.data import Instance, Vocabulary
  File "/data/bo718.wang/lau/anaconda3/lib/python3.6/site-packages/allennlp/data/__init__.py", line 1, in <module>
    from allennlp.data.dataset import Dataset
  File "/data/bo718.wang/lau/anaconda3/lib/python3.6/site-packages/allennlp/data/dataset.py", line 13, in <module>
    from allennlp.data.instance import Instance
  File "/data/bo718.wang/lau/anaconda3/lib/python3.6/site-packages/allennlp/data/instance.py", line 3, in <module>
    from allennlp.data.fields.field import DataArray, Field
  File "/data/bo718.wang/lau/anaconda3/lib/python3.6/site-packages/allennlp/data/fields/__init__.py", line 13, in <module>
    from allennlp.data.fields.text_field import TextField
  File "/data/bo718.wang/lau/anaconda3/lib/python3.6/site-packages/allennlp/data/fields/text_field.py", line 11, in <module>
    from allennlp.data.token_indexers.token_indexer import TokenIndexer, TokenType
  File "/data/bo718.wang/lau/anaconda3/lib/python3.6/site-packages/allennlp/data/token_indexers/__init__.py", line 6, in <module>
    from allennlp.data.token_indexers.token_characters_indexer import TokenCharactersIndexer
  File "/data/bo718.wang/lau/anaconda3/lib/python3.6/site-packages/allennlp/data/token_indexers/token_characters_indexer.py", line 10, in <module>
    from allennlp.data.tokenizers.character_tokenizer import CharacterTokenizer
  File "/data/bo718.wang/lau/anaconda3/lib/python3.6/site-packages/allennlp/data/tokenizers/__init__.py", line 7, in <module>
    from allennlp.data.tokenizers.word_tokenizer import WordTokenizer
  File "/data/bo718.wang/lau/anaconda3/lib/python3.6/site-packages/allennlp/data/tokenizers/word_tokenizer.py", line 8, in <module>
    from allennlp.data.tokenizers.word_splitter import WordSplitter, SpacyWordSplitter
  File "/data/bo718.wang/lau/anaconda3/lib/python3.6/site-packages/allennlp/data/tokenizers/word_splitter.py", line 4, in <module>
    import spacy
  File "/data/bo718.wang/lau/anaconda3/lib/python3.6/site-packages/spacy/__init__.py", line 5, in <module>
    from .deprecated import resolve_model_name
  File "/data/bo718.wang/lau/anaconda3/lib/python3.6/site-packages/spacy/deprecated.py", line 8, in <module>
    from .cli import download
  File "/data/bo718.wang/lau/anaconda3/lib/python3.6/site-packages/spacy/cli/__init__.py", line 5, in <module>
    from .train import train, train_config
  File "/data/bo718.wang/lau/anaconda3/lib/python3.6/site-packages/spacy/cli/train.py", line 8, in <module>
    from ..scorer import Scorer
  File "/data/bo718.wang/lau/anaconda3/lib/python3.6/site-packages/spacy/scorer.py", line 4, in <module>
    from .gold import tags_to_entities
ImportError: dlopen: cannot load any more object with static TLS
```
So I changed the directory to the cloned repo `~/allennlp-master/` and opened the file `allennlp/run.py` to edit. There are 14 lines in total, I put the `import spacy` line at the top and the file became like this:
```python
import spacy
#!/usr/bin/env python
import logging
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(os.path.join(__file__, os.pardir))))
logging.basicConfig(format='%(asctime)s - %(levelname)s - %(name)s - %(message)s',
                    level=logging.INFO)

from allennlp.commands import main  # pylint: disable=wrong-import-position

if __name__ == "__main__":
    main(prog="python -m allennlp.run")
```
Then I saved the change and ran `python ./allennlp/run.py`. This time it said:
```bash
Traceback (most recent call last):
  File "./allennlp/run.py", line 11, in <module>
    from allennlp.commands import main  # pylint: disable=wrong-import-position
  File "/data/bo718.wang/LauMingFei/allennlp/allennlp/commands/__init__.py", line 3, in <module>
    from allennlp.commands.serve import add_subparser as add_serve_subparser
  File "/data/bo718.wang/LauMingFei/allennlp/allennlp/commands/serve.py", line 27, in <module>
    from allennlp.service import server_sanic
  File "/data/bo718.wang/LauMingFei/allennlp/allennlp/service/server_sanic.py", line 19, in <module>
    from allennlp.common.util import JsonDict
  File "/data/bo718.wang/LauMingFei/allennlp/allennlp/common/__init__.py", line 3, in <module>
    from allennlp.common.util import JsonDict
  File "/data/bo718.wang/LauMingFei/allennlp/allennlp/common/util.py", line 9, in <module>
    import torch
  File "/data/bo718.wang/lau/anaconda3/lib/python3.6/site-packages/torch/__init__.py", line 53, in <module>
    from torch._C import *
ImportError: dlopen: cannot load any more object with static TLS
```
The error messages are different this time, I checked that the free RAM of my machine is >3GB, so it is unlikely that the crash is due to memory shortage. I used `pip list ` to check that my spacy version is 1.9.0, and everything was fine when I  `import spacy` and `spacy.load('en')` in a python console.

**Comment by matt-gardner** [comment]
Hmm...  That last trace makes me really think it's a capacity issue on your machine, especially as no one else is seeing this issue (including docker, travis, all allennlp devs, etc.).  `import allennlp` doesn't actually load anything, like `import spacy` does, so it wouldn't have triggered an issue (you need to import a submodule for the expensive things to load).  Try running this from an interpreter:

```python
>>> import spacy
>>> import torch
```

**Comment by laubonghaudoi** [comment]
I ran those two commands in a python console,  the same error popped up again. Merely importing spacy or torch doesn't trigger any error, but importing both does. So I guess it is indeed a memory shortage issue. 
I switched to another machine (laptop with Ubuntu 16.04, 8GB RAM), and retried the whole process. The installation was successful. I tested training the simple tagger and the BiDAF model, and then serving the demo, everything was fine. When testing the `semantic_role_labeler.json`, it popped up:
```bash
FileNotFoundError: file /net/efs/aristo/allennlp/srl/conll-formatted-ontonotes-5.0-12/conll-formatted-ontonotes-5.0/data/train not found
```
also when testing the `decomposable_attention.json`:
```bash
FileNotFoundError: file /snli/snli_1.0_train.jsonl not found
```
Sorry but I didn't find any guide on getting these data sets on the Tutorials page. Where can I download them ? I know this is another issue which has nothing to do with the memory shortage, I am just asking by the way.

So I think I can safely conclude that the my first machine was indeed lack of memory. This is weird because it is a remote server with much bigger RAM than my laptop. Is there any way to skip the use of spacy, or use replaceable one instead ?

**Comment by matt-gardner** [comment]
I think you need to get the CoNLL data from LDC (correct me if I'm wrong @DeNeutoy).  The SNLI data can be found [here](https://nlp.stanford.edu/projects/snli/).  Once you have the data downloaded, change the relevant paths in the config file.

Not sure what to say on the RAM issue - maybe there's some RAM limit for users on your server?  And sadly, it's not easy to skip importing spacy; it gets imported a few times by default in various parts of the codebase; you'd have to look for all of those places and modify the code.  But if you don't have enough memory to import both spacy and torch, you're probably going to have a hard time actually running anything, so I'm not sure it's worth it.

**Comment by laubonghaudoi** [comment]
But I have tested training several other large models like VGGNet on this server before, also it has several Tesla K80s. It is strange that a simple importing will cause memory shortages. Or maybe it is due to an broken installation of spacy ? I will figure it out later and I will close this issue as soon as it is cleared, even no solution is found, thank you very much for your help.

**Comment by terminator123** [comment]
did you solve the problem? i have the same problem too.
