### ISSUE TITLE
tensor dimensions do not match while tokenizing with BERT-multilingual

### ISSUE THREAD

**Issue by sbBlank** [allenai/allennlp#2851]
**System:**
 - OS: Linux (Ubuntu 16.04.4)
 - Python version: 3.6.8
 - AllenNLP version: 0.8.3

**Question**
My problem is related to #2727, but I wasn't able to resolve it given the corresponding comments. I'm experimenting with `bert-base-multilingual-cased` and found that my run failed while truncating the train_source-data. My training set consists of 3000 documents (separated by linebreaks in the .txt). Document number 2999 was the final one that was truncated, afterwards this error message occurred:

```
Traceback (most recent call last):
  File "/home/sblank/miniconda/envs/summaries/bin/allennlp", line 10, in <module>
    sys.exit(run())
  File "/home/sblank/miniconda/envs/summaries/lib/python3.6/site-packages/allennlp/run.py", line 18, in run
    main(prog="allennlp")
  File "/home/sblank/miniconda/envs/summaries/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 101, in main
    args.func(args)
  File "/home/sblank/miniconda/envs/summaries/lib/python3.6/site-packages/allennlp/commands/train.py", line 103, in train_model_from_ar
gs
    args.force)
  File "/home/sblank/miniconda/envs/summaries/lib/python3.6/site-packages/allennlp/commands/train.py", line 136, in train_model_from_fi
le
    return train_model(params, serialization_dir, file_friendly_logging, recover, force)
  File "/home/sblank/miniconda/envs/summaries/lib/python3.6/site-packages/allennlp/commands/train.py", line 204, in train_model
    metrics = trainer.train()
  File "/home/sblank/miniconda/envs/summaries/lib/python3.6/site-packages/allennlp/training/trainer.py", line 480, in train
    train_metrics = self._train_epoch(epoch)
  File "/home/sblank/miniconda/envs/summaries/lib/python3.6/site-packages/allennlp/training/trainer.py", line 322, in _train_epoch
    loss = self.batch_loss(batch_group, for_training=True)
  File "/home/sblank/miniconda/envs/summaries/lib/python3.6/site-packages/allennlp/training/trainer.py", line 263, in batch_loss
    output_dict = self.model(**batch)
  File "/home/sblank/miniconda/envs/summaries/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sblank/miniconda/envs/summaries/lib/python3.6/site-packages/allennlp/models/encoder_decoders/copynet_seq2seq.py", line 19
0, in forward
    state = self._encode(source_tokens)
  File "/home/sblank/miniconda/envs/summaries/lib/python3.6/site-packages/allennlp/models/encoder_decoders/copynet_seq2seq.py", line 30
2, in _encode
    embedded_input = self._source_embedder(source_tokens)
  File "/home/sblank/miniconda/envs/summaries/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sblank/miniconda/envs/summaries/lib/python3.6/site-packages/allennlp/modules/text_field_embedders/basic_text_field_embedd
er.py", line 125, in forward
    return torch.cat(embedded_representations, dim=-1)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 2. Got 400 and 358 in dimension 1 at /pytorch/aten/sr
c/THC/generic/THCTensorMath.cu:83
```

Here is my config:
```
{
  "dataset_reader": {
    "type": "summarization",
    "lazy": true,
    "target_namespace": "target_tokens",
    "source_tokenizer": {
      "type": "word",
      "word_splitter": {
        "type": "just_spaces"
      }
    },
    "target_tokenizer": {
      "type": "word",
      "word_splitter": {
        "type": "just_spaces"
      }
    },
    "source_token_indexers": {
      "tokens": {
        "type": "single_id",
        "namespace": "source_tokens"
      },
      "bert": {
          "type": "bert-pretrained",
          "pretrained_model": "bert-base-multilingual-cased",
          "max_pieces": 512,
          "use_starting_offsets": true,
          "do_lowercase": false,
      }
    }
  },
  "train_data_path": {
    "type": "tuple",
    "source_path": "/home/sblank/summarization/data/train_source.txt",
    "source_max_seq_leng": 400,
    "target_path": "/home/sblank/summarization/data/train_target.txt",
    "target_max_seq_leng": 100,
    "is_training": true
  },
  "validation_data_path": {
    "type": "tuple",
    "source_path": "/home/sblank/summarization/data/val_source.txt",
    "target_path": "/home/sblank/summarization/data/val_target.txt",
    "source_max_seq_leng": 400,
    "target_max_seq_leng": 100,
  },
  "model": {
    "type": "copynet_seq2seq",
    "source_embedder": {
       "allow_unmatched_keys": true,
       "embedder_to_indexer_map": {
         "tokens": ["tokens"],
         "bert": ["bert", "bert-offsets"]
       },
       "token_embedders": {
        "tokens": {
            "type": "embedding",
            "vocab_namespace": "source_tokens",
            "embedding_dim": 100,
            "trainable": true
         },
         "bert": {
           "type": "bert-pretrained",
           "pretrained_model": "bert-base-multilingual-cased",
           "requires_grad": false,
           "top_layer_only": false
         }
      }
    },
    "encoder": {
        "type": "lstm",
        "input_size": 868,
        "hidden_size": encoder_hidden,
        "bidirectional": encoder_bi,
        "num_layers": encoder_layers
    },
    "attention": {
      "type": "linear",
      "tensor_1_dim": encoder_out,
      "tensor_2_dim": encoder_out,
      "activation": "tanh"
    },
    "beam_size": 3,
    "max_decoding_steps": 100,
    "token_based_metric": "rouge"
  },
  "iterator": {
    "type": "bucket",
    "biggest_batch_first": true,
    "padding_noise": 0.1,
    "batch_size" : 32,
    "max_instances_in_memory": 12800,
    "sorting_keys": [["source_tokens", "num_tokens"]]
  },
  "validation_iterator": {
    "type": "bucket",
    "biggest_batch_first": true,
    "padding_noise": 0.1,
    "batch_size" : 32,
    "max_instances_in_memory": 1024,
    "sorting_keys": [["source_tokens", "num_tokens"]]
  },
  "trainer": {
    "optimizer": {
      "type": "adagrad",
      "lr": 0.15,
      "initial_accumulator_value": 0.1
    },
    "num_epochs": 10,
    "grad_norm": 2.0,
    "grad_clipping": 5.0,
    "patience": 3,
    "cuda_device": 0,
    "num_serialized_models_to_keep": 3,
  }
}
```

**Comment by joelgrus** [comment]
So here is the issue: the BERT model uses wordpieces and in particular truncates sequences that are longer than 512 wordpieces. What seems to be happening is that in that one example, the 400 tokens represent more than 512 wordpieces, which means that they get truncated (BERT can't cope with more than that), and then the resulting reconstructed token vectors are also truncated to 358 tokens.

Then the `TextFieldEmbedder` is trying to concatenate those two representations, but they have different lengths, so it chokes.

This is a hard problem to solve, that sliding window PR would in theory fix it (since it would get around the truncation), but it's not that close to being merged.

In the meantime here are three suboptimal solutions:

1. remove that training example from your dataset
2. reduce `source_max_seq_length` to a value that results in <512 wordpiece lengths
3. just use BERT embeddings without the single-id token embeddings

**Comment by Hyperparticle** [comment]
As @joelgrus wrote, PR #2537 should allow you to embed any length sequence without truncation. In the meantime, check out the changes in git to see if it works in your case.

**Comment by joelgrus** [comment]
that sliding window pr is now merged, that should solve your problem, let us know if it doesn't.
