### ISSUE TITLE
Error when installing AllenNLP in python:3.6.1

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp#2862]
I planned on cutting a minor release today but there was an error when installing AllenNLP in python:3.6.1.

```
$ git clean -f -d -x
$ python setup.py bdist_wheel
$ docker run --init --entrypoint bash --workdir /workdir --volume $HOME/Library/Caches/pip:/root/.cache/pip --volume $HOME/.cac
he/pip/:/root/.cache/pip --volume /Users/michaels/hack/allenai/allennlp/dist/allennlp-0.8.4_unreleased-py3-none-any.whl:/alle
nnlp-0.8.4_unreleased-py3-none-any.whl:ro -it python:3.6.1 -c 'pip install /allennlp-0.8.4_unreleased-py3-none-any.whl; allen
nlp test-install'

...

2019-05-18 03:32:33,293 - INFO - pytorch_pretrained_bert.modeling - Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sklearn/__check_build/__init__.py", line 44, in <module>
    from ._check_build import check_build  # noqa
ImportError: dlopen: cannot load any more object with static TLS

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/allennlp", line 7, in <module>
    from allennlp.run import run
  File "/usr/local/lib/python3.6/site-packages/allennlp/run.py", line 15, in <module>
    from allennlp.commands import main  # pylint: disable=wrong-import-position
  File "/usr/local/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 8, in <module>
    from allennlp.commands.configure import Configure
  File "/usr/local/lib/python3.6/site-packages/allennlp/commands/configure.py", line 27, in <module>
    from allennlp.service.config_explorer import make_app
  File "/usr/local/lib/python3.6/site-packages/allennlp/service/config_explorer.py", line 24, in <module>
    from allennlp.common.configuration import configure, choices
  File "/usr/local/lib/python3.6/site-packages/allennlp/common/configuration.py", line 20, in <module>
    from allennlp.models.model import Model
  File "/usr/local/lib/python3.6/site-packages/allennlp/models/__init__.py", line 8, in <module>
    from allennlp.models.bert_for_classification import BertForClassification
  File "/usr/local/lib/python3.6/site-packages/allennlp/models/bert_for_classification.py", line 11, in <module>
    from allennlp.training.metrics import CategoricalAccuracy
  File "/usr/local/lib/python3.6/site-packages/allennlp/training/metrics/__init__.py", line 12, in <module>
    from allennlp.training.metrics.conll_coref_scores import ConllCorefScores
  File "/usr/local/lib/python3.6/site-packages/allennlp/training/metrics/conll_coref_scores.py", line 5, in <module>
    from sklearn.utils.linear_assignment_ import linear_assignment
  File "/usr/local/lib/python3.6/site-packages/sklearn/__init__.py", line 75, in <module>
    from . import __check_build
  File "/usr/local/lib/python3.6/site-packages/sklearn/__check_build/__init__.py", line 46, in <module>
    raise_build_error(e)
  File "/usr/local/lib/python3.6/site-packages/sklearn/__check_build/__init__.py", line 41, in raise_build_error
    %s""" % (e, local_dir, ''.join(dir_content).strip(), msg))
ImportError: dlopen: cannot load any more object with static TLS
___________________________________________________________________________
Contents of /usr/local/lib/python3.6/site-packages/sklearn/__check_build:
setup.py                  __init__.py               _check_build.cpython-36m-x86_64-linux-gnu.so
__pycache__
___________________________________________________________________________
It seems that scikit-learn has not been built correctly.

If you have installed scikit-learn from source, please do not forget
to build the package before using it: run `python setup.py install` or
`make` in the source directory.

If you have used an installer, please check that it is suited for your
Python version, your operating system and your platform.
```

**Comment by schmmd** [comment]
Here is a previous fix for this issue (which worked for a while): https://github.com/allenai/allennlp/blob/master/allennlp/__init__.py#L18

**Comment by schmmd** [comment]
72de856ad74668f28322a4c6b8194ed0e9289eac is the first bad commit via git bisect

**Comment by schmmd** [comment]
@brendan-ai2 I get the same error on `v0.8.3`.

**Comment by schmmd** [comment]
This also fails for `v0.8.3` but both path on `python:3.6.8`, so we can go ahead with a release after https://github.com/allenai/allennlp-internal/pull/124.

**Comment by Aditi138** [comment]
Hello, 
I am facing a similar issue when trying to install the code based on allennlp (https://github.com/swabhs/scaffolding). How can I access this fix allenai/allennlp-internal#124., the page isn't publicly available?

**Comment by schmmd** [comment]
@Aditi138 we just bumped up from `python:3.6.1` to `python:3.6.8`.

**Comment by Aditi138** [comment]
@schmmd Thanks for the quick reply, but I am already on python:3.6.8.

**Comment by schmmd** [comment]
@Aditi138 I don't know exactly why you would be hitting this problem--but it probably has to do with a dependency conflict.

**Comment by Aditi138** [comment]
@schmmd I can try installing the libraries again, is there any particular order in which they should be installed? I am following the one mentioned in https://github.com/swabhs/scaffolding/requirement.txt. 
What dependency conflict would you be referring to?

**Comment by schmmd** [comment]
@Aditi138 unfortunately I don't know what the root cause is--although I suspect it has something to do with your dependencies.

**Comment by schmmd** [comment]
@alontalmor hit this error on some university computers running Ubuntu 14.04.  He worked around it by installing https://github.com/allenai/allennlp/blob/3a5373fd56b9f373f54847f198c9c87efaef9470/requirements.txt before installing the requirements.txt for v0.8.4.
