### ISSUE TITLE
ImportError when running example allennlp script

### ISSUE THREAD

**Issue by IHMCBrodie** [allenai/allennlp#2871]
- OS: OSX
 - Python version: 3.7.1
 - AllenNLP version: Ran pip install allennlp (so i assume installed from master)
 - PyTorch version: ran pip install allennlp

Below is the traceback I am receiving. I am trying to run a python script which only contains the example code given [here](https://allennlp.org/models), for semantic role labeling. I found this issue that was similar [6455](https://github.com/pytorch/pytorch/issues/6455), but don't know how/where to run those scripts mentioned. The only thing that I have done is `pip install allennlp` so if there are other steps that I should take be for attempting the example code from the allennlp website linked above please let me know. 

Thank you for any assistance. 

`Traceback (most recent call last):
  File "allentest.py", line 1, in <module>
    from allennlp.predictors.predictor import Predictor
  File "/miniconda3/lib/python3.7/site-packages/allennlp/__init__.py", line 18, in <module>
    import spacy, torch, numpy  # pylint: disable=multiple-imports
  File "/miniconda3/lib/python3.7/site-packages/torch/__init__.py", line 79, in <module>
    from torch._C import *
ImportError: dlopen(/miniconda3/lib/python3.7/site-packages/torch/_C.cpython-37m-darwin.so, 9): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
  Referenced from: /miniconda3/lib/python3.7/site-packages/torch/lib/libshm.dylib
  Reason: image not found`

**Comment by joelgrus** [comment]
try this, maybe?

https://github.com/pytorch/pytorch/issues/20030

**Comment by IHMCBrodie** [comment]
@joelgrus I tried the brew install libomp. Once it was installed I ran allennlp test-install. It ran fine all the way til the end then I received these errors.

`raceback (most recent call last):
  File "/miniconda3/lib/python3.7/site-packages/py/_error.py", line 66, in checked_call
    return func(*args, **kwargs)
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/miniconda3/bin/allennlp", line 11, in <module>
    sys.exit(run())
  File "/miniconda3/lib/python3.7/site-packages/allennlp/run.py", line 18, in run
    main(prog="allennlp")
  File "/miniconda3/lib/python3.7/site-packages/allennlp/commands/__init__.py", line 101, in main
    args.func(args)
  File "/miniconda3/lib/python3.7/site-packages/allennlp/commands/test_install.py", line 75, in _run_test
    exit_code = pytest.main([test_dir, '--color=no'] + pytest_k + pytest_m)
  File "/miniconda3/lib/python3.7/site-packages/_pytest/config/__init__.py", line 79, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "/miniconda3/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/miniconda3/lib/python3.7/site-packages/pluggy/manager.py", line 68, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/miniconda3/lib/python3.7/site-packages/pluggy/manager.py", line 62, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/miniconda3/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/miniconda3/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/miniconda3/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/miniconda3/lib/python3.7/site-packages/_pytest/main.py", line 242, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/miniconda3/lib/python3.7/site-packages/_pytest/main.py", line 232, in wrap_session
    session.startdir.chdir()
  File "/miniconda3/lib/python3.7/site-packages/py/_path/local.py", line 573, in chdir
    old = self.__class__()
  File "/miniconda3/lib/python3.7/site-packages/py/_path/local.py", line 154, in __init__
    self.strpath = py.error.checked_call(os.getcwd)
  File "/miniconda3/lib/python3.7/site-packages/py/_error.py", line 86, in checked_call
    raise cls("%s%r" % (func.__name__, args))
py.error.EMFILE: [Too many open files]: getcwd()`


`--- Logging error ---
Traceback (most recent call last):
  File "/miniconda3/lib/python3.7/logging/__init__.py", line 1036, in emit
    stream.write(msg)
  File "/miniconda3/lib/python3.7/site-packages/_pytest/capture.py", line 439, in write
    self.buffer.write(obj)
ValueError: I/O operation on closed file
Call stack:
  File "/miniconda3/lib/python3.7/multiprocessing/util.py", line 297, in _exit_function
    info('process shutting down')
  File "/miniconda3/lib/python3.7/multiprocessing/util.py", line 54, in info
    _logger.log(INFO, msg, *args)
Message: 'process shutting down'
Arguments: ()`

**Comment by joelgrus** [comment]
ok, now maybe try this?

https://github.com/allenai/allennlp/issues/1563#issuecomment-437413321

**Comment by joelgrus** [comment]
although actually, it sounds like it installed ok, I would try just running what you want to run. (running the tests requires opening a lot more files than normal usage.)

**Comment by IHMCBrodie** [comment]
Yep I tried that a half hour ago and now I am successfully running the script in my original comment. Quick question since I have you hear, if I something similar to the example script will it have to download all of that data each time it is run? Also for the allennlp.service.server_simple that you guys offer is there a way to access an endpoint in order to get Semantic role labeling similar to what is happening [here](https://demo.allennlp.org/semantic-role-labeling/ODEzMzEy)? So that I could easily get what parts of the sentence are associate with ARG0, ARG1 etc. Or will the output of semantic role labeling always appear like below:


`{'verbs': [{'verb': 'Did', 'description': '[V: Did] Uriah honestly think he could beat the game in under three hours ?', 'tags': ['B-V', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O']}, {'verb': 'think', 'description': 'Did [ARG0: Uriah] [ARGM-MNR: honestly] [V: think] [ARG1: he could beat the game in under three hours] ?', 'tags': ['O', 'B-ARG0', 'B-ARGM-MNR', 'B-V', 'B-ARG1', 'I-ARG1', 'I-ARG1', 'I-ARG1', 'I-ARG1', 'I-ARG1', 'I-ARG1', 'I-ARG1', 'I-ARG1', 'O']}, {'verb': 'could', 'description': 'Did Uriah honestly think he [V: could] beat the game in under three hours ?', 'tags': ['O', 'O', 'O', 'O', 'O', 'B-V', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O']}, {'verb': 'beat', 'description': 'Did Uriah honestly think [ARG0: he] [ARGM-MOD: could] [V: beat] [ARG1: the game] [ARGM-TMP: in under three hours] ?', 'tags': ['O', 'O', 'O', 'O', 'B-ARG0', 'B-ARGM-MOD', 'B-V', 'B-ARG1', 'I-ARG1', 'B-ARGM-TMP', 'I-ARGM-TMP', 'I-ARGM-TMP', 'I-ARGM-TMP', 'O']}], 'words': ['Did', 'Uriah', 'honestly', 'think', 'he', 'could', 'beat', 'the', 'game', 'in', 'under', 'three', 'hours', '?']}`

**Comment by joelgrus** [comment]
the allennlp code should cache the models it downloads, so that it downloads them the first time you run the script.

for the second question, you can run the "simple server" yourself, but the output will always look like what you pasted. (if you inspect the JSON response in the demo, it looks like that too, all of the matching args with words stuff is actually happening in the front-end of that app.)

**Comment by IHMCBrodie** [comment]
Yes to your first response I discovered that as well. 
Last question and then I think I am good to close the issue as this is becoming off topic of the original issue. I don't suppose the parse that is being used for your front end is available anywhere in the allennlp code bas?

**Comment by joelgrus** [comment]
the demo code is in a different repo, the code for the SRL visualization is here:

https://github.com/allenai/allennlp-demo/blob/master/demo/src/components/demos/SemanticRoleLabeling.js

but I don't know much about it or how helpful it will be. good luck!

**Comment by IHMCBrodie** [comment]
Thanks so much for the help!
