### ISSUE TITLE
MemoryError when trying to run SRL predictor in a docker container

### ISSUE THREAD

**Issue by toomzy** [allenai/allennlp#2951]
Hi,

I'm trying to run SRL predictor in a docker container (Windows Server 2019 host) via allennlp's "simple server", however it looks like container startup fails with following errors:

```
PS C:\Windows\system32> docker run --rm -p 8000:8000 --entrypoint="" -v $HOME/.allennlp:/root/.allennlp allennlp/allennlp:v0.8.4 python -m allennlp.service.server_simple --archive-path https://s3-us-west-2.amazonaws.com/allennlp/models/srl-model-2018.05.25.tar.gz --predictor semantic-role-labeling --field-name sentence
docker : /usr/local/lib/python3.6/site-packages/sklearn/utils/linear_assignment_.py:21: DeprecationWarning: The linear_assignment_ module is deprecated in 0.21 and will 
be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
At line:1 char:1
+ docker run --rm -p 8000:8000 --entrypoint="" -v $HOME/.allennlp:/root ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (/usr/local/lib/...gnment instead.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
  DeprecationWarning)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/allennlp/service/server_simple.py", line 758, in <module>
    main(sys.argv[1:])
  File "/usr/local/lib/python3.6/site-packages/allennlp/service/server_simple.py", line 182, in main
    predictor = _get_predictor(args)
  File "/usr/local/lib/python3.6/site-packages/allennlp/service/server_simple.py", line 146, in _get_predictor
    overrides=args.overrides)
  File "/usr/local/lib/python3.6/site-packages/allennlp/models/archival.py", line 230, in load_archive
    cuda_device=cuda_device)
  File "/usr/local/lib/python3.6/site-packages/allennlp/models/model.py", line 327, in load
    return cls.by_name(model_type)._load(config, serialization_dir, weights_file, cuda_device)
  File "/usr/local/lib/python3.6/site-packages/allennlp/models/model.py", line 265, in _load
    model = Model.from_params(vocab=vocab, params=model_params)
  File "/usr/local/lib/python3.6/site-packages/allennlp/common/from_params.py", line 365, in from_params
    return subclass.from_params(params=params, **extras)
  File "/usr/local/lib/python3.6/site-packages/allennlp/common/from_params.py", line 386, in from_params
    kwargs = create_kwargs(cls, params, **extras)
  File "/usr/local/lib/python3.6/site-packages/allennlp/common/from_params.py", line 133, in create_kwargs
    kwargs[name] = construct_arg(cls, name, annotation, param.default, params, **extras)
  File "/usr/local/lib/python3.6/site-packages/allennlp/common/from_params.py", line 229, in construct_arg
    return annotation.from_params(params=subparams, **subextras)
  File "/usr/local/lib/python3.6/site-packages/allennlp/common/from_params.py", line 365, in from_params
    return subclass.from_params(params=params, **extras)
  File "/usr/local/lib/python3.6/site-packages/allennlp/modules/text_field_embedders/basic_text_field_embedder.py", line 165, in from_params
    token_embedders[key] = TokenEmbedder.from_params(vocab=vocab, params=embedder_params)
  File "/usr/local/lib/python3.6/site-packages/allennlp/common/from_params.py", line 365, in from_params
    return subclass.from_params(params=params, **extras)
  File "/usr/local/lib/python3.6/site-packages/allennlp/modules/token_embedders/elmo_token_embedder.py", line 128, in from_params
    scalar_mix_parameters=scalar_mix_parameters)
  File "/usr/local/lib/python3.6/site-packages/allennlp/modules/token_embedders/elmo_token_embedder.py", line 65, in __init__
    scalar_mix_parameters=scalar_mix_parameters)
  File "/usr/local/lib/python3.6/site-packages/allennlp/modules/elmo.py", line 110, in __init__
    vocab_to_cache=vocab_to_cache)
  File "/usr/local/lib/python3.6/site-packages/allennlp/modules/elmo.py", line 554, in __init__
    self._elmo_lstm.load_weights(weight_file)
  File "/usr/local/lib/python3.6/site-packages/allennlp/modules/elmo_lstm.py", line 265, in load_weights
    torch_weights = tf_weights.copy()
MemoryError
```
I have no clue what does the MemoryError stand for, since the host machine does not exceed more than 15% of its RAM usage during execution.
What am I doing wrong here? Any help appreciated.

**Comment by matt-gardner** [comment]
How much RAM do you have available?  I'm afraid I'm not going to be much help in figuring this out, though...  Is anyone else good with diagnosing these memory issues?

**Comment by toomzy** [comment]
It's 20GB in total.

**Comment by DeNeutoy** [comment]
probably your docker daemon is limiting the resources individual containers it runs can use. You can check this by going: Docker > Preferences > Advanced and making the `Memory` slider larger. I think this might need to be > 4GB (I have mine set to 12GB) for the SRL model to run. Can you try that and see if it helps?

**Comment by toomzy** [comment]
I'm running docker enterprise on win server 2019 machine instead of docker desktop for windows, hence there's no GUI to make the memory change. However, I tried that by passing the `-m 12g` argument to `docker run`, still to no avail. Apparently, there really is a limit of 1GB that I simply cannot override by any means. Running `docker stats <containerID>` in parallel, I can see that the container crashes when PRIV WORKING SET reaches 1GB. Anyway, I assume this has nothing to do with allennlp image, it's the win-based docker setup that's giving me headache.

**Comment by DeNeutoy** [comment]
ugh super annoying. Sorry about that! Doesn't sound like an allennlp issue though, so i'll close this.
