### ISSUE TITLE
`predict` does not have a `cuda_device` option.

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp#303]
If you simply pass `cuda_device` to `load_archive` such as in https://github.com/schmmd/allennlp/commit/889ebd3843dbde0039dcf2ab7f2571691f0e4828 you get the following error.

```
Traceback (most recent call last):
  File "allennlp/run", line 14, in <module>
    main()
  File "/stage/allennlp/commands/__init__.py", line 27, in main
    args.func(args)
  File "/stage/allennlp/commands/predict.py", line 82, in predict
    run(predictor, input_file, output_file, not args.silent)
  File "/stage/allennlp/commands/predict.py", line 59, in run
    result = predictor.predict_json(data)
  File "/stage/allennlp/service/predictors/bidaf.py", line 26, in predict_json
    prediction = self.model.predict_span(question, passage)
  File "/stage/allennlp/models/bidaf.py", line 342, in predict_span
    output_dict = self.forward(**model_input)
  File "/stage/allennlp/models/bidaf.py", line 188, in forward
    embedded_question = self._highway_layer(self._text_field_embedder(question))
  File "/opt/conda/lib/python3.5/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/stage/allennlp/modules/text_field_embedders/basic_text_field_embedder.py", line 45, in forward
    token_vectors = embedder(tensor)
  File "/opt/conda/lib/python3.5/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/stage/allennlp/modules/token_embedders/token_characters_encoder.py", line 36, in forward
    return self._dropout(self._encoder(self._embedding(token_characters), mask))
  File "/opt/conda/lib/python3.5/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/stage/allennlp/modules/time_distributed.py", line 29, in forward
    reshaped_outputs = self._module(*reshaped_inputs)
  File "/opt/conda/lib/python3.5/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/stage/allennlp/modules/token_embedders/embedding.py", line 116, in forward
    sparse=self.sparse)
  File "/opt/conda/lib/python3.5/site-packages/torch/nn/functional.py", line 632, in embedding
    scale_grad_by_freq, sparse
  File "/opt/conda/lib/python3.5/site-packages/torch/nn/_functions/thnn/sparse.py", line 53, in forward
    output = torch.index_select(weight, 0, indices.view(-1))
TypeError: torch.index_select received an invalid combination of arguments - got (torch.cuda.FloatTensor, int, torch.LongTensor), but expected (torch.cuda.FloatTensor source, int dim, torch.cuda.LongTensor index)
```

**Comment by schmmd** [comment]
@joelgrus says this is because we are mixing GPU objects with CPU objects, and it takes a bit of whack-a-mole to figure out the root issue.

**Comment by schmmd** [comment]
https://github.com/allenai/allennlp/blame/master/allennlp/models/model.py#L114 looks a bit scary.
