### ISSUE TITLE
CUDA out of memory - BiDAF

### ISSUE THREAD

**Issue by Swathygsb** [allenai/allennlp#3045]
start_acc: 0.5084, end_acc: 0.5548, span_acc: 0.4094, em: 0.4611, f1: 0.6113, loss: 3.3881 ||:  15%|#5        | 336/2196 [03:17<18:22,  1.69it/s]Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/allennlp/bin/allennlp", line 10, in <module>
    sys.exit(run())
  File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/run.py", line 18, in run
    main(prog="allennlp")
  File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 102, in main
    args.func(args)
  File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/train.py", line 116, in train_model_from_args
    args.cache_prefix)
  File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/train.py", line 160, in train_model_from_file
    cache_directory, cache_prefix)
  File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/train.py", line 243, in train_model
    metrics = trainer.train()
  File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/training/trainer.py", line 480, in train
    train_metrics = self._train_epoch(epoch)
  File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/training/trainer.py", line 327, in _train_epoch
    loss.backward()
  File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.6/site-packages/torch/tensor.py", line 107, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.6/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA out of memory. Tried to allocate 4.41 GiB (GPU 0; 11.17 GiB total capacity; 5.05 GiB already allocated; 2.20 GiB free; 3.58 GiB cached)

**Comment by Swathygsb** [comment]
Training Data Size : 60 MB
AWS EC2 instance: p2.xlarge (has 1 Tesla k80)
Tesla k80 spec shows 24 GB RAM, but only 11.17 is shown as total capacity here

**Comment by schmmd** [comment]
@Swathygsb I don't think K80s have 24 GB of RAM.

**Comment by Swathygsb** [comment]
Does allennlp supports using the 2nd GPU, if 1st one goes out of memory.

**Comment by schmmd** [comment]
No--it's best to lower your batch size or move to a GPU with more memory.

**Comment by Swathygsb** [comment]
Thanks

**Comment by matt-gardner** [comment]
You _can_ use multiple GPUs to increase your effective batch size with data parallel computation.  But you can't easily spread your model onto multiple GPUs.
