### ISSUE TITLE
TypeError, When using GPU to run simple tagger tutorial

### ISSUE THREAD

**Issue by andy-yangz** [allenai/allennlp#308]
As title, when I want to run the simple tagger model from the tutorial, I find CPU is okay. But when I set the `cuda_device` to `0` to use GPU.
It gets TypeError as follow.
```
Traceback (most recent call last):
  File "/home/andy/.conda/envs/py36/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/andy/.conda/envs/py36/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/andy/.conda/envs/py36/lib/python3.6/site-packages/allennlp/run.py", line 13, in <module>
    main(prog="python -m allennlp.run")
  File "/home/andy/.conda/envs/py36/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 27, in main
    args.func(args)
  File "/home/andy/.conda/envs/py36/lib/python3.6/site-packages/allennlp/commands/train.py", line 97, in _train_model_from_args
    train_model_from_file(args.param_path, args.serialization_dir)
  File "/home/andy/.conda/envs/py36/lib/python3.6/site-packages/allennlp/commands/train.py", line 116, in train_model_from_file
    return train_model(params, serialization_dir)
  File "/home/andy/.conda/envs/py36/lib/python3.6/site-packages/allennlp/commands/train.py", line 184, in train_model
    trainer.train()
  File "/home/andy/.conda/envs/py36/lib/python3.6/site-packages/allennlp/training/trainer.py", line 183, in train
    self._optimizer.step()
  File "/home/andy/.conda/envs/py36/lib/python3.6/site-packages/torch/optim/adam.py", line 65, in step
    exp_avg.mul_(beta1).add_(1 - beta1, grad)
TypeError: add_ received an invalid combination of arguments - got (float, torch.cuda.FloatTensor), but expected one of:
 * (float value)
 * (torch.FloatTensor other)
 * (torch.SparseFloatTensor other)
 * (float value, torch.FloatTensor other)
      didn't match because some of the arguments have invalid types: (float, torch.cuda.FloatTensor)
 * (float value, torch.SparseFloatTensor other)
      didn't match because some of the arguments have invalid types: (float, torch.cuda.FloatTensor)
```

**Comment by matt-gardner** [comment]
I just tried this and didn't see the same error.  I used an EC2 machine with a GPU, ran the train command from the tutorial (it worked on CPU), changed the cuda device line in `simple_tagger.json`, and it worked on the GPU.  I'm not sure what advice to give you.  Do you have an up-to-date version of the code?

**Comment by matt-gardner** [comment]
I'm closing this due to inactivity, and because we can't reproduce it.  If you're still seeing this error, feel free to re-open the issue.
