### ISSUE TITLE
The wikitables demo fails against the latest commit

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp#3093]
If you change the allennlp-demo Dockerfile to FROM allennlp/commit:417a75727d4604e1da0eda461b03b29a73f0bf50 (master as of today), build, and run then wikitables it fails with the following exception:

```
$ kubectl logs allennlp-demo-bias-wikitables-parser-7ffd866cd9-mcggd --namespace=allennlp-demo model
{"message": "Starting a flask server on port 8000.", "severity": "INFO"}
{"message": "With models {'wikitables-parser': <server.demo_model.DemoModel object at 0x7f60d3e2cc88>}", "severity": "INFO"}
{"message": "loading wikitables-parser model", "severity": "INFO"}
100%|██████████| 5378797/5378797 [00:00<00:00, 49533347.32B/s]
Traceback (most recent call last):
  File "./app.py", line 432, in <module>
    models=models)
  File "./app.py", line 93, in main
    app = make_app(build_dir=f"{demo_dir}/build", demo_db=demo_db, models=models)
  File "./app.py", line 122, in make_app
    predictor = demo_model.predictor()
  File "/stage/allennlp/server/demo_model.py", line 25, in predictor
    archive = load_archive(self.archive_file)
  File "/usr/local/lib/python3.6/site-packages/allennlp/models/archival.py", line 230, in load_archive
    cuda_device=cuda_device)
  File "/usr/local/lib/python3.6/site-packages/allennlp/models/model.py", line 327, in load
    return cls.by_name(model_type)._load(config, serialization_dir, weights_file, cuda_device)
  File "/usr/local/lib/python3.6/site-packages/allennlp/models/model.py", line 276, in _load
    model.load_state_dict(model_state)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 777, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for WikiTablesMmlSemanticParser:
	Unexpected key(s) in state_dict: "_decoder_step._start_type_predictor.weight", "_decoder_step._start_type_predictor.bias". 
	size mismatch for _entity_type_encoder_embedding.weight: copying a param with shape torch.Size([4, 200]) from checkpoint, the shape in current model is torch.Size([5, 200]).
	size mismatch for _entity_type_decoder_embedding.weight: copying a param with shape torch.Size([4, 100]) from checkpoint, the shape in current model is torch.Size([5, 100]).
```

**Comment by schmmd** [comment]
I first saw this in Docker (and the k8s deployment) and later repro'd using Conda.

**Comment by schmmd** [comment]
This also fails with a1476c0414ad1e1412515c53d9e1f27b69039ead.

**Comment by matt-gardner** [comment]
I believe @pdasigi already knows about this and is working on a fix.

**Comment by pdasigi** [comment]
The demo needs to be updated, and [this PR on allennlp-demo](https://github.com/allenai/allennlp-demo/pull/247) does it. Closing this because it is not an issue with this repo.
