### ISSUE TITLE
No super class method found for `as_padded_tensor`

### ISSUE THREAD

**Issue by gunnxx** [allenai/allennlp#3104]
**System**
 - Python version: 3.6.8
 - AllenNLP version: 0.8.4

**Problem**
I tried to create my own `TokenIndexer`. When I tried to test it, I got the following error `No super class method found for "as_padded_tensor"`. My class is inherited from `TokenCharactersIndexer` which inherits from `TokenIndexer`. The error comes from
```
@overrides
def as_padded_tensor():
```

**Things I tried**
- Inherit directly from `TokenIndexer` but still got the same error.
- Remove `@overrides` decorator, but the training process is calling `as_padded_tensor` from parent class instead of my implementation. I know this because I turned certain attributes from parent class into `None` since my `as_padded_tensor` implementation doesn't need those attributes. Then, I got an error because those attributes can't be accessed by parent class implementation of `as_padded_tensor`.
- I found [this](https://github.com/allenai/allennlp/pull/3040#discussion_r301795906). So I tried to check `TokenIndexer` methods using
```
>>> from allennlp.data.token_indexers.token_indexer import TokenIndexer
>>> dir(TokenIndexer)
['__abstractmethods__', '__annotations__', '__args__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__extra__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__next_in_mro__', '__orig_bases__', '__origin__', '__parameters__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__slots__', '__str__', '__subclasshook__', '__tree_hash__', '__weakref__', '_abc_cache', '_abc_generic_negative_cache', '_abc_generic_negative_cache_version', '_abc_registry', '_gorg', '_registry', 'by_name', 'count_vocab_items', 'default_implementation', 'from_params', 'get_keys', 'get_padding_lengths', 'get_padding_token', 'get_token_min_padding_length', 'list_available', 'pad_token_sequence', 'register', 'tokens_to_indices']
```
I can't found `as_padded_tensor` but there's `pad_token_sequence`.

**Comment by matt-gardner** [comment]
Can you post a full stack trace, and preferably also the code for the token indexer that you wrote, and how you're calling it?

**Comment by gunnxx** [comment]
I solved it by changing `def as_padded_tensor()` to `def pad_token_sequence()` but still feels weird given [this](https://github.com/allenai/allennlp/pull/3040#discussion_r301795906)

Here's my implementation of my custom `token_indexer` (note that it is almost identical to [`TokenCharactersIndexer`](https://github.com/allenai/allennlp/blob/master/allennlp/data/token_indexers/token_characters_indexer.py#L16-L130))
```
from typing import Dict, List
from overrides import overrides

import itertools
import warnings

import torch
import torch.nn.functional as F

from allennlp.common.checks import ConfigurationError
from allennlp.common.util import pad_sequence_to_length
from allennlp.data.tokenizers.token import Token
from allennlp.data.token_indexers.token_indexer import TokenIndexer
from allennlp.data.vocabulary import Vocabulary
from allennlp.data.tokenizers.character_tokenizer import CharacterTokenizer


@TokenIndexer.register("bme")
class BMETokenIndexer(TokenIndexer[List[int]]):
    """
    This :class:`TokenIndexer` represents tokens as lists of transformed character indices based on BME.
    BME (Beginning-Middle-End) is described in http://noisy-text.github.io/2018/pdf/W-NUT20188.pdf.

    This class inherits :class:`~allennlp.data.token_indexers.token_characters_indexer.TokenCharactersIndexer`
    due to some similarity in implementation. Note that ``min_padding_length`` argument for parent class
    is always set to 0.

    Cancel to inherit :class:`~allennlp.data.token_indexers.token_characters_indexer.TokenCharactersIndexer`
    due to `as_padded_tensor` can't be overridden. Trying to implement from scratch but similar to
    `TokenCharactersIndexer`
    Parameters
    ----------
    namespace : ``str``, optional (default=``token_characters``)
        We will use this namespace in the :class:`Vocabulary` to map the characters in each token
        to indices.
    character_tokenizer : ``CharacterTokenizer``, optional (default=``CharacterTokenizer()``)
        We use a :class:`CharacterTokenizer` to handle splitting tokens into characters, as it has
        options for byte encoding and other things.  The default here is to instantiate a
        ``CharacterTokenizer`` with its default parameters, which uses unicode characters and
        retains casing.
    start_tokens : ``List[str]``, optional (default=``None``)
        These are prepended to the tokens provided to ``tokens_to_indices``.
    end_tokens : ``List[str]``, optional (default=``None``)
        These are appended to the tokens provided to ``tokens_to_indices``.
    token_min_padding_length : ``int``, optional (default=``0``)
        See :class:`TokenIndexer`.
    begin_size: ``int``, optional(default=``3``)
        Size of B from BME. Please refer to http://noisy-text.github.io/2018/pdf/W-NUT20188.pdf
    end_size: ``int``, optional(default=```3``)
        Size of E from BME. Please refer to http://noisy-text.github.io/2018/pdf/W-NUT20188.pdf
    """
    def __init__(self,
                 namespace: str = 'bme_token_characters',
                 character_tokenizer: CharacterTokenizer = CharacterTokenizer(),
                 start_tokens: List[str] = None,
                 end_tokens: List[str] = None,
                 token_min_padding_length: int = 0,
                 begin_size: int = 3,
                 end_size: int = 3) -> None:
        super().__init__(token_min_padding_length)
        
        major, minor, patch = map(int, torch.__version__.split('.'))
        torch_version = major + 0.1*minor

        if torch_version < 1.1:
            raise Exception("BMETokenIndexer requires pytorch version >= 1.1 because it provides \
                torch.nn.functional.one_hot. Your version is {}".format(torch.__version__))

        self._namespace = namespace
        self._character_tokenizer = character_tokenizer

        self._start_tokens = [Token(st) for st in (start_tokens or [])]
        self._end_tokens = [Token(et) for et in (end_tokens or [])]

        self._begin_size = begin_size
        self._end_size = end_size

    @overrides
    def count_vocab_items(self, token: Token, counter: Dict[str, Dict[str, int]]):
        if token.text is None:
            raise ConfigurationError('BMETokenIndexer needs a tokenizer that retains text')
        for character in self._character_tokenizer.tokenize(token.text):
            # If `text_id` is set on the character token (e.g., if we're using byte encoding), we
            # will not be using the vocab for this character.
            if getattr(character, 'text_id', None) is None:
                counter[self._namespace][character.text] += 1

    @overrides
    def tokens_to_indices(self,
                          tokens: List[Token],
                          vocabulary: Vocabulary,
                          index_name: str) -> Dict[str, List[List[int]]]:
        vocab_size = vocabulary.get_vocab_size(self._namespace)

        # Initial steps are exactly the same as super().tokens_to_indices()
        indices: List[List[int]] = []

        for token in itertools.chain(self._start_tokens, tokens, self._end_tokens):
            token_indices: List[int] = []

            if token.text is None:
                raise ConfigurationError('BMETokenIndexer needs a tokenizer that retains text')

            for character in self._character_tokenizer.tokenize(token.text):
                if getattr(character, 'text_id', None) is not None:
                    # `text_id` being set on the token means that we aren't using the vocab, we just
                    # use this id instead.
                    index = character.text_id
                else:
                    index = vocabulary.get_token_index(character.text, self._namespace)

                token_indices.append(index)

            # Generating BME (steps that are different from super().tokens_to_indices())
            B = F.one_hot(torch.tensor(self._pad(token_indices[:self._begin_size], self._begin_size, True)), num_classes=vocab_size).reshape(-1)
            M = F.one_hot(torch.tensor([0] if len(token_indices) is 0 else token_indices), num_classes=vocab_size).sum(0)
            E = F.one_hot(torch.tensor(self._pad(token_indices[-self._end_size:], self._end_size)), num_classes=vocab_size).reshape(-1)

            indices.append(torch.cat((B, M, E)).tolist())
        return {index_name: indices}

    @overrides
    def get_padding_lengths(self, tokens: List[int]) -> Dict[str, int]:
        return {}

    @overrides
    #def as_padded_tensor(self,
    def pad_token_sequence(self,
                           tokens: Dict[str, List[List[int]]],
                           desired_num_tokens: Dict[str, int],
                           padding_lengths: Dict[str, int]) -> Dict[str, torch.Tensor]:
        return {key: torch.LongTensor(pad_sequence_to_length(val, desired_num_tokens[key], lambda: [0]*(len(tokens[key][0]))))
                for key, val in tokens.items()}

    # auxillary function to pad list whose length <= N
    # with padding_index (i.e. 0) so the list has length == N
    def _pad(self, arr: List[int], N: int, prepend: bool = False) -> List[int]:
        if prepend:
            return [0]*(N-len(arr)) + arr
        return arr + [0]*(N-len(arr))
```

here's how I called it
```
{
    "train_data_path": "/home/guntara/data-gpu/guntara_workspace/informal-data/working/split.txt",

    "dataset_reader": {
        "type": "plain_reader",
        "token_indexers": {
            "rove": {
                "type": "bme"
            }
        },
        "lazy": true
    },

    "model": {
        "type": "rove_trainer",
        "text_field_embedder": {
            "rove": {
                "type": "identity"
            }
        },
        "encoder": {
            "type": "lstm",
            "input_size": 672, // jemma.data vocab
            "hidden_size": 128,
            "num_layers": 2,
            "dropout": 0.2,
            "bidirectional": true
         },
        "projection_dim": 100,
        "window_size": 3,
        "neg_sample": 5
    },

    "iterator": {
        "type": "basic",
        "batch_size": 32,
        "instances_per_epoch": 32000,
        "max_instances_in_memory": 32000
    },

    "trainer": {
        "optimizer": {
            "type": "adam",
            "lr"  : 0.001
        },
        "cuda_device": 0,
        "num_epochs": 200,
        "num_serialized_models_to_keep": 3,
        "grad_norm": 5.0,
        "grad_clipping": 5.0,
        "patience": 25
    }
}
```

and here's `plain_reader` for `dataset_reader`
```
from typing import Dict, List
from overrides import overrides

from allennlp.data.tokenizers.token import Token
from allennlp.common.file_utils import cached_path
from allennlp.data.dataset_readers.dataset_reader import DatasetReader
from allennlp.data.token_indexers.token_indexer import TokenIndexer
from allennlp.data.fields import TextField
from allennlp.data.instance import Instance

@DatasetReader.register("plain_reader")
class PlainReader(DatasetReader):
    def __init__(self,
                 token_indexers: Dict[str, TokenIndexer],
                 lazy: bool = False) -> None:
        super().__init__(lazy=lazy)
        self.token_indexers = token_indexers

    def text_to_instance(self,
                         text: List[Token]) -> Instance:
        sentence = TextField(text, self.token_indexers)
        return Instance({"sentence": sentence})

    @overrides
    def _read(self, file_path: str):
        file_path = cached_path(file_path)
        with open(file_path, 'r') as f:
            for line in f:
                yield self.text_to_instance(list(map(Token, line.strip().split())))
```

**Comment by gunnxx** [comment]
Here's the full trace of the error which I produced simply by changing `def pad_token_sequence()` back to `def as_padded_tensor()`

```
2019-08-01 13:48:23,911 - INFO - pytorch_pretrained_bert.modeling - Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .
/home/wahyuguntara/.local/lib/python3.6/site-packages/sklearn/utils/linear_assignment_.py:21: DeprecationWarning: The linear_assignment_ module is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  DeprecationWarning)
Traceback (most recent call last):
  File "/home/wahyuguntara/Documents/apps/anaconda3/envs/allennlp/bin/allennlp", line 10, in <module>
    sys.exit(run())
  File "/home/wahyuguntara/Documents/apps/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/run.py", line 18, in run
    main(prog="allennlp")
  File "/home/wahyuguntara/Documents/apps/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 101, in main
    import_submodules(package_name)
  File "/home/wahyuguntara/Documents/apps/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/common/util.py", line 334, in import_submodules
    import_submodules(subpackage)
  File "/home/wahyuguntara/Documents/apps/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/common/util.py", line 323, in import_submodules
    module = importlib.import_module(package_name)
  File "/home/wahyuguntara/Documents/apps/anaconda3/envs/allennlp/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./kata_lib/token_indexer/__init__.py", line 1, in <module>
    from kata_lib.token_indexer.bme_token_indexer import BMETokenIndexer
  File "./kata_lib/token_indexer/bme_token_indexer.py", line 19, in <module>
    class BMETokenIndexer(TokenIndexer[List[int]]):
  File "./kata_lib/token_indexer/bme_token_indexer.py", line 131, in BMETokenIndexer
    padding_lengths: Dict[str, int]) -> Dict[str, torch.Tensor]:
  File "/home/wahyuguntara/Documents/apps/anaconda3/envs/allennlp/lib/python3.6/site-packages/overrides/overrides.py", line 70, in overrides
    method.__name__)
AssertionError: No super class method found for "as_padded_tensor"
```

**Comment by DeNeutoy** [comment]
Hi,

This is because you are using the latest allennlp release, but we've merged two methods in `master`, resulting in the new `as_padded_tensor` class. What you have done is fine.
