### ISSUE TITLE
CoreferenceResolver training: CUDA out of memory

### ISSUE THREAD

**Issue by KurtMica** [allenai/allennlp#3125]
**Describe the bug**
I'm trying to train the `CoreferenceResolver` on the CoNLL-2012 data, but keep hitting an out of memory error in the first epoch on the GPUs:
```
coref_precision: 0.0080, coref_recall: 0.0007, coref_f1: 0.0011, mention_recall: 0.0671, loss: 188.1832 ||:   8%|███████▏                                                                                      | 27/351 [02:05<20:40,  3.83s/it]
Traceback (most recent call last):
  File "coref.py", line 113, in <module>
    cuda_device=devices).train()
  File "/home/user/.local/lib/python3.6/site-packages/allennlp/training/trainer.py", line 480, in train
    train_metrics = self._train_epoch(epoch)
  File "/home/user/.local/lib/python3.6/site-packages/allennlp/training/trainer.py", line 322, in _train_epoch
    loss = self.batch_loss(batch_group, for_training=True)
  File "/home/user/.local/lib/python3.6/site-packages/allennlp/training/trainer.py", line 258, in batch_loss
    output_dict = training_util.data_parallel(batch_group, self.model, self._cuda_devices)
  File "/home/user/.local/lib/python3.6/site-packages/allennlp/training/util.py", line 332, in data_parallel
    outputs = parallel_apply(replicas, inputs, moved, used_device_ids)
  File "/home/user/.local/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
    raise output
  File "/home/user/.local/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 59, in _worker
    output = module(*input, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/allennlp/models/coreference_resolution/coref.py", line 239, in forward
    valid_antecedent_offsets)
  File "/home/user/.local/lib/python3.6/site-packages/allennlp/models/coreference_resolution/coref.py", line 499, in _compute_span_pair_embeddings
    antecedent_distance_embeddings], -1)
RuntimeError: CUDA out of memory. Tried to allocate 3.68 GiB (GPU 2; 11.17 GiB total capacity; 5.55 GiB already allocated; 3.40 GiB free; 1.88 GiB cached)
```

**To Reproduce**
```python
import torch
from allennlp.common import Params
from allennlp.data import Vocabulary
from allennlp.data.dataset_readers import ConllCorefReader
from allennlp.data.dataset_readers.dataset_utils import Ontonotes
from allennlp.data.iterators import BasicIterator
from allennlp.data.token_indexers import SingleIdTokenIndexer, TokenCharactersIndexer
from allennlp.models import CoreferenceResolver
from allennlp.modules import Embedding, FeedForward
from allennlp.modules.seq2seq_encoders import PytorchSeq2SeqWrapper
from allennlp.modules.seq2vec_encoders import CnnEncoder
from allennlp.modules.text_field_embedders import BasicTextFieldEmbedder
from allennlp.modules.token_embedders import TokenCharactersEncoder
from allennlp.training import Trainer
from allennlp.training.learning_rate_schedulers import LearningRateScheduler
from torch.nn import LSTM, ReLU
from torch.optim import Adam


def read_data(directory_path):
    data = []
    for file_path in Ontonotes().dataset_path_iterator(directory_path):
        data += dataset_reader.read(file_path)
    return data


INPUT_FILE_PATH_TEMPLATE = "data/CoNLL-2012/v4/data/%s"
max_span_width = 10
dataset_reader = ConllCorefReader(max_span_width, {"tokens": SingleIdTokenIndexer(),
                                                   "token_characters": TokenCharactersIndexer()})
training_data = read_data(INPUT_FILE_PATH_TEMPLATE % "train")
validation_data = read_data(INPUT_FILE_PATH_TEMPLATE % "development")


def read_embeddings(file_path):
    with open(file_path, "r", encoding="UTF-8") as embeddings:
        embeddings_dimension = len(next(embeddings).split(" ")[1:])
        embeddings.seek(0)  # start reading from beginning again
        tokens = [embedding.split(" ")[0] for embedding in embeddings]
    vocabulary = Vocabulary(tokens_to_add={"tokens": tokens})
    embeddings = Embedding.from_params(vocabulary, Params({"embedding_dim": embeddings_dimension,
                                                           "pretrained_file": file_path,
                                                           "vocab_namespace": "tokens",
                                                           "trainable": False}))

    return embeddings, vocabulary


word_embeddings, vocabulary = read_embeddings("data/glove.840B.300d.txt")

unique_characters = list(set("".join("".join(instance["metadata"]["original_text"])
                                     for instance in training_data + validation_data)))
vocabulary._extend(tokens_to_add={"token_characters": unique_characters})
character_embeddings = TokenCharactersEncoder(embedding=Embedding(num_embeddings=vocabulary.get_vocab_size("token_characters"),
                                                                  embedding_dim=8,
                                                                  vocab_namespace="token_characters"),
                                              encoder=CnnEncoder(embedding_dim=8,
                                                                 num_filters=50,
                                                                 ngram_filter_sizes=(3, 4, 5),
                                                                 output_dim=100))

embeddings_dimension = word_embeddings.get_output_dim() + character_embeddings.get_output_dim()


encoder = PytorchSeq2SeqWrapper(LSTM(input_size=embeddings_dimension,
                                     hidden_size=200,
                                     num_layers=1,
                                     dropout=0.2,
                                     bidirectional=True,
                                     batch_first=True))

feature_size = 20
mention_scorer = FeedForward(input_dim=embeddings_dimension + encoder.get_output_dim() * 2 + feature_size,
                             num_layers=2,
                             hidden_dims=[150, 150],
                             activations=[ReLU(), ReLU()],
                             dropout=[0.2, 0.2])
antecedent_scorer = FeedForward(input_dim=mention_scorer.get_input_dim() * 3 + feature_size,
                                num_layers=2,
                                hidden_dims=[150, 150],
                                activations=[ReLU(), ReLU()],
                                dropout=[0.2, 0.2])

model = CoreferenceResolver(vocab=vocabulary,
                            text_field_embedder=BasicTextFieldEmbedder({"tokens": word_embeddings, "token_characters": character_embeddings}),
                            context_layer=encoder,
                            mention_feedforward=mention_scorer,
                            antecedent_feedforward=antecedent_scorer,
                            feature_size=feature_size,
                            max_span_width=max_span_width,
                            spans_per_word=0.4,
                            max_antecedents=250,
                            lexical_dropout=0.5)

if torch.cuda.is_available():
    devices = list(range(torch.cuda.device_count()))
    model = model.cuda(devices[0])
else:
    devices = -1

iterator = BasicIterator(batch_size=1)
iterator.index_with(vocabulary)
optimiser = Adam(model.parameters(), weight_decay=0.1)
Trainer(model=model,
        train_dataset=training_data,
        validation_dataset=validation_data,
        optimizer=optimiser,
        learning_rate_scheduler=LearningRateScheduler.from_params(optimiser,
                                                                  Params({"type": "step", "step_size": 100})),
        iterator=iterator,
        num_epochs=150,
        patience=1,
        cuda_device=devices).train()
```

**Expected behaviour**
The amount of GPU memory I have seems excessive. Is this expected or is there some memory leakage happening?

**System**
- OS: Ubuntu 18.04
- Python version: `3.6.8`
- AllenNLP version: [`0.8.4`](https://pypi.org/project/allennlp/0.8.4/)
- PyTorch version: `1.1.0`
- CUDA toolkit: [`10.1`](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=1804&target_type=debnetwork)
- GPU(s): 8×Tesla K80 (12GB memory each).

**Additional context**
I've tried restraining the iterator to use less `instances_per_epoch` to `128` & it doesn't hit the out of memory error with my setup, but with `256` the error still props up, albeit at a 3rd epoch & not the 1st. However, the performance on the validation data is horrible:
```
coref_precision: 0.0000, coref_recall: 0.0000, coref_f1: 0.0000, mention_recall: 0.1123, loss: 201.3492 ||: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:34<00:00,  2.04s/it]
```

I also followed some of the suggestions mentioned in #2569 (`max_instances_in_memory` to `128`, `batch_size` is already `1`) with the same error.

**Comment by DeNeutoy** [comment]
Hi,

The two parameters which significantly effect memory use in the coref model are:
```
spans_per_word=0.4
max_antecedents=250
```

Reducing these will affect performance, but will also use less memory. You might have trouble getting good performance on a GPU with 12GB of memory, unfortunately. Sorry about that!

**Comment by KurtMica** [comment]
> You might have trouble getting good performance on a GPU with 12GB of memory, unfortunately.
I'm making use of 8 GPUs concurrently though. Does this still not help to alleviate the memory requirements?

**Comment by marcos0318** [comment]
Hi, I also face this problem. How did you solve the out of memory issue? I have tried to minimize the spans_per_word and 
max_antecedents to really small numbers and it still does not work. I am using 2080ti GPU with 11GB memory
