### ISSUE TITLE
Reading comprehension: Resume training from a saved model in dialog_qa.py

### ISSUE THREAD

**Issue by skeshaw** [allenai/allennlp#3144]
**System**
 - OS: Linux
 - Python version: 3.6
 - AllenNLP version: Installed from master

Hi there!
I am looking to modify the script [`dialog_qa.py`](https://github.com/allenai/allennlp/blob/master/allennlp/models/reading_comprehension/dialog_qa.py), which implements a modified version of BiDAF for reading comprehension, for the [QuAC](https://quac.ai/) dataset. But before I do that, I need to make sure I can initialize my model using pre-trained weights, for example, resume training from a model which has been trained for 10 epochs.
Since I continue to use the same dataset, using the `fine-tune` command is probably not the best option. Additionally, it takes about double the time as the `train` command. I understand that using the command for [pre-trained initializer](https://allenai.github.io/allennlp-docs/api/allennlp.nn.initializers.html#allennlp.nn.initializers.PretrainedModelInitializer) should help, but it requires me to specify the names of all the relevant parameters.
I tried using the command [load_archive](https://github.com/allenai/allennlp/blob/f9e2029fec4c66c751cad05be3dfb32a47dbe643/allennlp/models/archival.py#L150) instead of using the initializer, but that leads to the code seemingly running in an endless loop.
I am certain there is a better (and probably, obvious) way to do this, but I have been unable to find one. It would be great if someone could help me out here.

**Comment by DeNeutoy** [comment]
Hi @skeshaw,

I think you can just use the `PretrainedInitializer` but don't provide the name mapping - in this case, it assumes that the parameters have identical names and the mapping should work as expected. If this doesn't work, please let us know and we will fix it such that it uses the weights names as the default mapping.


If you need to modify the model such that this is not possible, you have two options:
1. Provide the mapping manually (sorry)
2. Write your own training loop which essentially copies what happens in `allennlp train` but loads the model from the archive first. 

Hopefully you can figure out what parts to copy over from the train command.
https://github.com/allenai/allennlp/blob/master/allennlp/commands/train.py#L170

This is something we'd like to make substantially easier (writing your own training scripts)

**Comment by skeshaw** [comment]
Hi @DeNeutoy,
First of all, thanks for your response.
This is the first time I am using this library. I am not very certain what you mean; so if you could help me with an example, that would be really helpful.  
Let's say we are considering the following example adapted from the [documentation](https://allenai.github.io/allennlp-docs/api/allennlp.nn.initializers.html#allennlp.nn.initializers.PretrainedModelInitializer): 
`["linear_1.weight|linear_2.weight",  
    {  
        "type": "pretrained",  
        "weights_file_path": "best.th"  
    }]` 

Do you essentially mean that I should pass an empty string as the first element, in place of `linear_1.weight|linear_2.weight`?

**Comment by DeNeutoy** [comment]
I meant something like:

```
["*", // idea is to match all weights - you might need to scope this if you're building ontop of the model
    {
        "type": "pretrained",
        "weights_file_path": "best.th",
        "parameter_name_overrides": {}
    }
```

Hopefully this initialises the submodel with the weights from the pretrained file.

**Comment by skeshaw** [comment]
I remember trying that earlier, and again just now. Unfortunately, it does not seem to work, and fails with the following error:
```
Traceback (most recent call last): 
  File "/usr/local/bin/allennlp", line 11, in <module>
    load_entry_point('allennlp', 'console_scripts', 'allennlp')()
  File "/home/allennlp/allennlp/run.py", line 18, in run
    main(prog="allennlp")
  File "/home/allennlp/allennlp/commands/__init__.py", line 102, in main
    args.func(args)
  File "/home/allennlp/allennlp/commands/train.py", line 123, in train_model_from_args
    args.cache_prefix)
  File "/home/allennlp/allennlp/commands/train.py", line 167, in train_model_from_file
    cache_directory, cache_prefix)
  File "/home/allennlp/allennlp/commands/train.py", line 225, in train_model
    cache_prefix)
  File "/home/allennlp/allennlp/training/trainer_pieces.py", line 61, in from_params
    model = Model.from_params(vocab=vocab, params=params.pop('model'))
  File "/home/allennlp/allennlp/common/from_params.py", line 365, in from_params
    return subclass.from_params(params=params, **extras)
  File "/home/allennlp/allennlp/common/from_params.py", line 386, in from_params
    kwargs = create_kwargs(cls, params, **extras)
  File "/home/allennlp/allennlp/common/from_params.py", line 133, in create_kwargs
    kwargs[name] = construct_arg(cls, name, annotation, param.default, params, **extras)
  File "/home/allennlp/allennlp/common/from_params.py", line 229, in construct_arg
    return annotation.from_params(params=subparams, **subextras)
  File "/home/allennlp/allennlp/nn/initializers.py", line 351, in from_params
    prevent_regexes = [param[0] for param in params if is_prevent(param[1])]
  File "/home/allennlp/allennlp/nn/initializers.py", line 351, in <listcomp>
    prevent_regexes = [param[0] for param in params if is_prevent(param[1])]
IndexError: string index out of range
```

**Comment by DeNeutoy** [comment]
It's a list of initializers, so the full thing needs to look something like:

```
// inside your `model` config, assuming you have an
// `InitializerApplicator` in the constructor of your model.
"initializer": [
	["*",{
        "type": "pretrained",
        "weights_file_path": "best.th",
        "parameter_name_overrides": {}
    }]
]
```

The reason it's like this is that you might want more than one initializer.

**Comment by skeshaw** [comment]
I certainly missed the list of lists part this whole time (my bad). But this time, I made the suggested changes, and still it does not work, although does get a few steps ahead in the process.
```
2019-08-19 18:24:18,191 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.nn.initializers.Initializer'> from params {'parameter_name_overrides': {}, 'type': 'pretrained', 'weights_file_path': 'weights.th'} and extras set()
2019-08-19 18:24:18,191 - INFO - allennlp.common.params - model.initializer.0.1.type = pretrained
2019-08-19 18:24:18,192 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.nn.initializers.PretrainedModelInitializer'> from params {'parameter_name_overrides': {}, 'weights_file_path': 'weights.th'} and extras set()
2019-08-19 18:24:18,192 - INFO - allennlp.common.params - model.initializer.0.1.weights_file_path = weights.th
2019-08-19 18:24:18,192 - INFO - allennlp.common.params - model.initializer.0.1.parameter_name_overrides = {}
2019-08-19 18:24:20,893 - INFO - allennlp.common.params - model.dropout = 0.2
2019-08-19 18:24:20,893 - INFO - allennlp.common.params - model.num_context_answers = 2
2019-08-19 18:24:20,893 - INFO - allennlp.common.params - model.marker_embedding_dim = 10
2019-08-19 18:24:20,893 - INFO - allennlp.common.params - model.max_span_length = 30
2019-08-19 18:24:20,893 - INFO - allennlp.common.params - model.max_turn_length = 12
2019-08-19 18:24:20,898 - INFO - allennlp.nn.initializers - Initializing parameters
Traceback (most recent call last):
  File "/usr/local/bin/allennlp", line 11, in <module>
    load_entry_point('allennlp', 'console_scripts', 'allennlp')()
  File "/home/allennlp/allennlp/run.py", line 18, in run
    main(prog="allennlp")
  File "/home/allennlp/allennlp/commands/__init__.py", line 102, in main
    args.func(args)
  File "/home/allennlp/allennlp/commands/train.py", line 123, in train_model_from_args
    args.cache_prefix)
  File "/home/allennlp/allennlp/commands/train.py", line 167, in train_model_from_file
    cache_directory, cache_prefix)
  File "/home/allennlp/allennlp/commands/train.py", line 225, in train_model
    cache_prefix)
  File "/home/allennlp/allennlp/training/trainer_pieces.py", line 61, in from_params
    model = Model.from_params(vocab=vocab, params=params.pop('model'))
  File "/home/allennlp/allennlp/common/from_params.py", line 365, in from_params
    return subclass.from_params(params=params, **extras)
  File "/home/allennlp/allennlp/common/from_params.py", line 388, in from_params
    return cls(**kwargs)  # type: ignore
  File "/home/allennlp/allennlp/models/reading_comprehension/dialog_qa.py", line 103, in __init__
    initializer(self)
  File "/home/allennlp/allennlp/nn/initializers.py", line 301, in __call__
    if allow and re.search(initializer_regex, name):
  File "/usr/lib/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
  File "/usr/lib/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.6/sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.6/sre_parse.py", line 855, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.6/sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "/usr/lib/python3.6/sre_parse.py", line 616, in _parse
    source.tell() - here + len(this))
sre_constants.error: nothing to repeat at position 0
```

**Comment by skeshaw** [comment]
The `train` script is working fine now. Just needed to replace `*` with `.*`.
@DeNeutoy Thanks for all your help despite my constant pestering.

**Comment by DeNeutoy** [comment]
@skeshaw no problem! If you wanted to submit a PR which just adds that example to the docstring of the function, that would be great.

**Comment by skeshaw** [comment]
Yes, sure. I can do that.
