### ISSUE TITLE
Using Bert indexer with a vocabulary

### ISSUE THREAD

**Issue by OfirArviv** [allenai/allennlp#3192]
**System :**
 - OS:  Win 10 
 - Python version: . 3.6.7
 - AllenNLP version: v0.8.5
 - PyTorch version: 1.1.0

**Question**
In my Dataset reader I have a TextField which contains bert wordpiece tokenized tokens and a PretrainedBertIndexer.
I also have other fields in it (labels, Spacy tokens for pos and ners, ect) so I need to pass the Dataset reader thru a vocabulary, even thou BERT doesn't need to. 
When I do, I get the error 
> AttributeError: 'PretrainedBertIndexer' object has no attribute 'values'

Is there a way around it? maybe a way to tell the vocabulary to ignore this field?

I can think about moving the bert tokenization and indexer to the model, but not sure its not anti-pattern.

Thanks

**Comment by brendan-ai2** [comment]
Hi @OfirArviv, could you please provide a full stack trace and perhaps a sample input? We don't have enough to go off of as-is. Thanks!

**Comment by OfirArviv** [comment]
Hi, 
Sure, I thought this is as intended so I didn't go into details

This is my dataset reader:
```
class MyDatasetReader(DatasetReader):
    # Tokenizer can be thought of sas a token feature extractor. And the token indexers as
    # indexing these features. After ward we need to find a way to auto embedd them all, and to take their embeddings.
    # Maybe have it as a another part of the inputs. But that way we have 3 inputs for it, not so nice.
    # Think of other ways? Can read the github pages. There are ideas there.
    # First just implement the HTL SUDA PARSER.
    # And then maybe TUPA
    # Need to think how to support multiple tokenizers
    def __init__(self, word_tokenizer: Callable[[str], List[Token]],
                 word_indexers: Dict[str, TokenIndexer],
                 linguistic_features_tokenizer: Callable[[str], List[Token]],
                 linguistic_features_indexers: Dict[str, TokenIndexer]
                 ) -> None:
        super().__init__(lazy=False)
        self.word_tokenizer = word_tokenizer
        self.word_indexers = word_indexers
        self.linguistic_features_tokenizer = linguistic_features_tokenizer
        self.linguistic_features_indexers = linguistic_features_indexers

    @overrides
    # TODO: Add typing to 'gold_tree'
    # TODO: Think how to incorporate the filter function
    def text_to_instance(self, passage: str, dataset_label: str, lang: str, gold_tree=None,
                         filter=None) -> Instance:
        fields: Dict[str, Field] = {}

        word_tokens = self.word_tokenizer(passage)
        sentence_field = TextField(word_tokens, self.word_indexers)
        fields["tokens"] = sentence_field

        linguistic_features_tokens = self.linguistic_features_tokenizer(passage)
        linguistic_features_field = TextField(linguistic_features_tokens, self.linguistic_features_indexers)
        fields["linguistic_features"] = linguistic_features_field

        dataset_label_field = MetadataField(dataset_label)
        fields["dataset_label"] = dataset_label_field

        # TODO: Need to language embedding as well.
        lang_field = MetadataField(lang)
        fields["lang"] = lang_field

        # TODO: Collect remote tags

        if gold_tree is not None:
            gold_ucca_tree_field = MetadataField(gold_tree)
            fields["gold_ucca_tree"] = gold_ucca_tree_field

            gold_primary_tree = UCCA2tree(copy.deepcopy(gold_tree)).convert()
            gold_primary_tree_field = MetadataField(gold_primary_tree)
            fields["gold_primary_tree"] = gold_primary_tree_field

            gold_remotes_tree = gerenate_remote(gold_tree)
            gold_remotes_tree_field = MetadataField(gold_remotes_tree)
            fields["gold_remotes_tree"] = gold_remotes_tree_field

        spans: List[Field] = []
        gold_labels = []
        # TODO: Think how to add tokens only, maybe metadata?
        for start, end in enumerate_spans(linguistic_features_tokens):
            spans.append(SpanField(start, end, sentence_field))
            if gold_tree is not None:
                gold_label = str(gold_primary_tree.oracle_label(start, end + 1))
                gold_labels.append(gold_label)

        span_list_field: ListField = ListField(spans)
        fields["spans"] = span_list_field

        if gold_tree is not None:
            fields["span_labels"] = SequenceLabelField(gold_labels, span_list_field)

        return Instance(fields)

    @overrides
    def _read(self, dataset_dir: str) -> Iterator[Instance]:
        dir_name = os.path.basename(dataset_dir)
        for file in sorted(os.listdir(dataset_dir)):
            file_path = os.path.join(dataset_dir, file)
            if os.path.isdir(file_path):
                self._read(file_path)
            else:
                # TODO: In the future, I would like to pass to the text_to_instance only a string.
                #  Training data comes pre-tokenized and the text may not. Need to think about it.
                #  Also Need to think how to support reading features from file.
                #  For both issues, maybe another reader is the solution. Sound reasonable.
                passage = file2passage(file_path)
                text = " ".join([node.text for node in sorted(passage.layer("0").all, key=lambda x: x.position)])
                if "1" not in passage._layers:
                    passage = None
                lang = passage.attrib.get("lang")
                assert lang, "Attribute 'lang' is required per passage when using multilingual BERT"
                yield self.text_to_instance(text, dir_name, lang, None)
```

And this is part of my main code which use it:
```
bert_indexer = PretrainedBertIndexer(
        pretrained_model="bert-base-multilingual-cased",
        do_lowercase=False,
        truncate_long_sequences=True
    )
    
    def word_tokenizer(s: str):
        return [Token(t) for t in bert_indexer.wordpiece_tokenizer(s)]

    bert_embedder = PretrainedBertEmbedder(
        pretrained_model="bert-base-multilingual-cased",
        top_layer_only=False,
    )
    word_embedder: TextFieldEmbedder = BasicTextFieldEmbedder({"tokens": bert_embedder},
                                                              {"tokens": {"input_ids": "tokens",
                                                                          "offsets": "offset"}},
                                                              allow_unmatched_keys=True)

    def linguistic_features_tokenizer(lang: str):
        spacy_model = None
        if lang == "en":
            spacy_model = "en_core_web_sm"
        elif lang == "de":
            spacy_model = "de_core_news_sm"
        elif lang == "fr":
            spacy_model = "fr_core_news_sm"
        assert spacy_model

        return SpacyWordSplitter(language=spacy_model, pos_tags=True, parse=True, ner=True).split_words


    linguistic_features_indexers = {"deps": DepLabelIndexer(),
                                    "ner": NerTagIndexer(),
                                    "pos": PosTagIndexer()}

    linguistic_features_embedding = Embedding(num_embeddings=100 + 2,
                                              embedding_dim=5, padding_index=0)

    linguistic_features_embedder: TextFieldEmbedder = BasicTextFieldEmbedder({"deps": linguistic_features_embedding,
                                                                              "ner": linguistic_features_embedding,
                                                                              "pos": linguistic_features_embedding})

    train_ds, test_ds = (UCCADatasetReader(word_tokenizer, bert_indexer).read(folder) for folder in
                         ["C:/Users/t-ofarvi/PycharmProjects/tryout",
                          "C:/Users/t-ofarvi/PycharmProjects/tryout"])

    vocab = Vocabulary.from_instances(train_ds, max_vocab_size=100)
```

The error trace:
```
Traceback (most recent call last):
  File "C:\Users\t-ofarvi\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\192.5728.105\helpers\pydev\pydevd.py", line 2060, in <module>
    main()
  File "C:\Users\t-ofarvi\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\192.5728.105\helpers\pydev\pydevd.py", line 2054, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Users\t-ofarvi\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\192.5728.105\helpers\pydev\pydevd.py", line 1405, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "C:\Users\t-ofarvi\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\192.5728.105\helpers\pydev\pydevd.py", line 1412, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Users\t-ofarvi\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\192.5728.105\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\Users\t-ofarvi\PycharmProjects\HTL@SUDA-ucca-parser\allen.py", line 403, in <module>
    vocab = Vocabulary.from_instances(train_ds, max_vocab_size=100)
  File "C:\Users\t-ofarvi\PycharmProjects\HTL@SUDA-ucca-parser\venv\lib\site-packages\allennlp\data\vocabulary.py", line 399, in from_instances
    instance.count_vocab_items(namespace_token_counts)
  File "C:\Users\t-ofarvi\PycharmProjects\HTL@SUDA-ucca-parser\venv\lib\site-packages\allennlp\data\instance.py", line 57, in count_vocab_items
    field.count_vocab_items(counter)
  File "C:\Users\t-ofarvi\PycharmProjects\HTL@SUDA-ucca-parser\venv\lib\site-packages\allennlp\data\fields\text_field.py", line 60, in count_vocab_items
    for indexer in self._token_indexers.values():
AttributeError: 'PretrainedBertIndexer' object has no attribute 'values'
```

It seems intentional, BERT indexers doesn't need a vocabulary so it doesn't implement the function to support it. But I though the vocabulary will just ignore it.

**Comment by matt-gardner** [comment]
The problem is that you're passing something that is not a dictionary to a `TextField`.  Looks like that might be happening here: `UCCADatasetReader(word_tokenizer, bert_indexer)`.  You need `{"bert": bert_indexer}`, like you have for `linguistic_features_indexers`.

**Comment by OfirArviv** [comment]
Oh you are right! I totally missed it! Thank you very much! :)
