### ISSUE TITLE
urgent - bug in running ESIM codes 

### ISSUE THREAD

**Issue by rabeehk** [allenai/allennlp#3215]
Hi 
I need to run esim model urgently, I am getting the following errors, I appreciate your help:
I run it with allennlp train training_config/esim.jsonnet --serialization-dir  temp
thanks a lot for having a look.

(transformer36) rkarimi@vgnc006:/idiap/user/rkarimi/dev/rubi/allennlp$ allennlp train training_config/esim.jsonnet --serialization-dir  temp
2019-09-03 06:19:35,099 - INFO - pytorch_pretrained_bert.modeling - Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .
2019-09-03 06:19:37,251 - INFO - pytorch_transformers.modeling_bert - Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .
2019-09-03 06:19:37,265 - INFO - pytorch_transformers.modeling_xlnet - Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .
2019-09-03 06:19:38,399 - INFO - allennlp.common.registrable - instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
2019-09-03 06:19:38,403 - INFO - allennlp.common.registrable - instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
2019-09-03 06:19:38,405 - INFO - allennlp.common.registrable - instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
2019-09-03 06:19:38,407 - INFO - allennlp.common.registrable - instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
2019-09-03 06:19:38,665 - INFO - allennlp.common.params - random_seed = 13370
2019-09-03 06:19:38,665 - INFO - allennlp.common.params - numpy_seed = 1337
2019-09-03 06:19:38,665 - INFO - allennlp.common.params - pytorch_seed = 133
2019-09-03 06:19:38,698 - INFO - allennlp.common.checks - Pytorch version: 1.2.0
2019-09-03 06:19:38,703 - INFO - allennlp.common.params - evaluate_on_test = False
2019-09-03 06:19:38,703 - INFO - allennlp.common.params - validation_dataset_reader = None
2019-09-03 06:19:38,703 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.data.dataset_readers.dataset_reader.DatasetReader'> from params {'token_indexers': {'tokens': {'lowercase_tokens': True, 'type': 'single_id'}}, 'type': 'snli'} and extras set()
2019-09-03 06:19:38,703 - INFO - allennlp.common.params - dataset_reader.type = snli
2019-09-03 06:19:38,704 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.data.dataset_readers.snli.SnliReader'> from params {'token_indexers': {'tokens': {'lowercase_tokens': True, 'type': 'single_id'}}} and extras set()
2019-09-03 06:19:38,704 - INFO - allennlp.common.from_params - instantiating class allennlp.data.token_indexers.token_indexer.TokenIndexer from params {'lowercase_tokens': True, 'type': 'single_id'} and extras set()
2019-09-03 06:19:38,704 - INFO - allennlp.common.params - dataset_reader.token_indexers.tokens.type = single_id
2019-09-03 06:19:38,704 - INFO - allennlp.common.from_params - instantiating class allennlp.data.token_indexers.single_id_token_indexer.SingleIdTokenIndexer from params {'lowercase_tokens': True} and extras set()
2019-09-03 06:19:38,705 - INFO - allennlp.common.params - dataset_reader.token_indexers.tokens.namespace = tokens
2019-09-03 06:19:38,705 - INFO - allennlp.common.params - dataset_reader.token_indexers.tokens.lowercase_tokens = True
2019-09-03 06:19:38,705 - INFO - allennlp.common.params - dataset_reader.token_indexers.tokens.start_tokens = None
2019-09-03 06:19:38,705 - INFO - allennlp.common.params - dataset_reader.token_indexers.tokens.end_tokens = None
2019-09-03 06:19:38,705 - INFO - allennlp.common.params - dataset_reader.token_indexers.tokens.token_min_padding_length = 0
2019-09-03 06:19:38,705 - INFO - allennlp.common.params - dataset_reader.lazy = False
Traceback (most recent call last):
  File "/idiap/user/rkarimi/libs/anaconda3/envs/transformer36/bin/allennlp", line 11, in <module>
    load_entry_point('allennlp', 'console_scripts', 'allennlp')()
  File "/remote/idiap.svm/user.active/rkarimi/dev/rubi/allennlp/allennlp/run.py", line 18, in run
    main(prog="allennlp")
  File "/remote/idiap.svm/user.active/rkarimi/dev/rubi/allennlp/allennlp/commands/__init__.py", line 102, in main
    args.func(args)
  File "/remote/idiap.svm/user.active/rkarimi/dev/rubi/allennlp/allennlp/commands/train.py", line 124, in train_model_from_args
    args.cache_prefix)
  File "/remote/idiap.svm/user.active/rkarimi/dev/rubi/allennlp/allennlp/commands/train.py", line 168, in train_model_from_file
    cache_directory, cache_prefix)
  File "/remote/idiap.svm/user.active/rkarimi/dev/rubi/allennlp/allennlp/commands/train.py", line 226, in train_model
    cache_prefix)
  File "/remote/idiap.svm/user.active/rkarimi/dev/rubi/allennlp/allennlp/training/trainer_pieces.py", line 41, in from_params
    all_datasets = training_util.datasets_from_params(params, cache_directory, cache_prefix)
  File "/remote/idiap.svm/user.active/rkarimi/dev/rubi/allennlp/allennlp/training/util.py", line 165, in datasets_from_params
    dataset_reader = DatasetReader.from_params(dataset_reader_params)
  File "/remote/idiap.svm/user.active/rkarimi/dev/rubi/allennlp/allennlp/common/from_params.py", line 365, in from_params
    return subclass.from_params(params=params, **extras)
  File "/remote/idiap.svm/user.active/rkarimi/dev/rubi/allennlp/allennlp/common/from_params.py", line 388, in from_params
    return cls(**kwargs)  # type: ignore
  File "/remote/idiap.svm/user.active/rkarimi/dev/rubi/allennlp/allennlp/data/dataset_readers/snli.py", line 39, in __init__
    self._tokenizer = tokenizer or WordTokenizer()
  File "/remote/idiap.svm/user.active/rkarimi/dev/rubi/allennlp/allennlp/data/tokenizers/word_tokenizer.py", line 44, in __init__
    self._word_splitter = word_splitter or SpacyWordSplitter()
  File "/remote/idiap.svm/user.active/rkarimi/dev/rubi/allennlp/allennlp/data/tokenizers/word_splitter.py", line 173, in __init__
    self.spacy = get_spacy_model(language, pos_tags, parse, ner)
  File "/remote/idiap.svm/user.active/rkarimi/dev/rubi/allennlp/allennlp/common/util.py", line 289, in get_spacy_model
    spacy_model = spacy.load(spacy_model_name, disable=disable)
  File "/idiap/user/rkarimi/libs/anaconda3/envs/transformer36/lib/python3.6/site-packages/spacy/__init__.py", line 27, in load
    return util.load_model(name, **overrides)
  File "/idiap/user/rkarimi/libs/anaconda3/envs/transformer36/lib/python3.6/site-packages/spacy/util.py", line 134, in load_model
    return load_model_from_package(name, **overrides)
  File "/idiap/user/rkarimi/libs/anaconda3/envs/transformer36/lib/python3.6/site-packages/spacy/util.py", line 155, in load_model_from_package
    return cls.load(**overrides)
  File "/idiap/user/rkarimi/libs/anaconda3/envs/transformer36/lib/python3.6/site-packages/en_core_web_sm/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/idiap/user/rkarimi/libs/anaconda3/envs/transformer36/lib/python3.6/site-packages/spacy/util.py", line 196, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/idiap/user/rkarimi/libs/anaconda3/envs/transformer36/lib/python3.6/site-packages/spacy/util.py", line 179, in load_model_from_path
    return nlp.from_disk(model_path)
  File "/idiap/user/rkarimi/libs/anaconda3/envs/transformer36/lib/python3.6/site-packages/spacy/language.py", line 836, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/idiap/user/rkarimi/libs/anaconda3/envs/transformer36/lib/python3.6/site-packages/spacy/util.py", line 636, in from_disk
    reader(path / key)
  File "/idiap/user/rkarimi/libs/anaconda3/envs/transformer36/lib/python3.6/site-packages/spacy/language.py", line 823, in <lambda>
    p, exclude=["vocab"]
  File "tokenizer.pyx", line 391, in spacy.tokenizer.Tokenizer.from_disk
  File "tokenizer.pyx", line 437, in spacy.tokenizer.Tokenizer.from_bytes
  File "/idiap/user/rkarimi/libs/anaconda3/envs/transformer36/lib/python3.6/re.py", line 233, in compile
    return _compile(pattern, flags)
  File "/idiap/user/rkarimi/libs/anaconda3/envs/transformer36/lib/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/idiap/user/rkarimi/libs/anaconda3/envs/transformer36/lib/python3.6/sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "/idiap/user/rkarimi/libs/anaconda3/envs/transformer36/lib/python3.6/sre_parse.py", line 855, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/idiap/user/rkarimi/libs/anaconda3/envs/transformer36/lib/python3.6/sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "/idiap/user/rkarimi/libs/anaconda3/envs/transformer36/lib/python3.6/sre_parse.py", line 527, in _parse
    code1 = _class_escape(source, this)
  File "/idiap/user/rkarimi/libs/anaconda3/envs/transformer36/lib/python3.6/sre_parse.py", line 336, in _class_escape
    raise source.error('bad escape %s' % escape, len(escape))
sre_constants.error: bad escape \p at position 257

**Comment by ArrowLuo** [comment]
@rabeehk It seems scapy has something wrong itself. The following command may be useful for you.
`python -m spacy validate`
The output may be,

> ====================== Installed models (spaCy v2.1.8) ======================
> spaCy installation:
> /home/yu-intern/.conda/envs/py3yucopy/lib/python3.6/site-packages/spacy
> TYPE      NAME              MODEL             VERSION
> package   en-core-web-sm    en_core_web_sm    2.0.0   --> 2.1.0
> package   de-core-news-sm   de_core_news_sm   2.0.0   --> 2.1.0
> ============================== Install updates ==============================
> Use the following commands to update the model packages:
> python -m spacy download de_core_news_sm
> python -m spacy download en_core_web_sm

Follows its tips,
`python -m spacy download de_core_news_sm`
`python -m spacy download en_core_web_sm`

That all.

**Comment by rabeehk** [comment]
Hi
thanks, issue solved, when after running the code, I need to evaluate on the dataset, I see in the tutorial I need to use this command, so I need to pass a model.tar.gz file with the dataset:

allennlp evaluate \
    https://s3-us-west-2.amazonaws.com/allennlp/models/decomposable-attention-elmo-2018.02.19.tar.gz \
    https://s3-us-west-2.amazonaws.com/allennlp/datasets/snli/snli_1.0_test.jsonl


but in my serialization folder, there is only json and .th files, I am not sure how should be the model.tar.gz created to be able to do evaluation, and how to do evalaution on the training when you run training at the same time,
thanks.

**Comment by matt-gardner** [comment]
If there is no model file, training didn't succeed. Double check your logs, something probably crashed.

**Comment by schmmd** [comment]
@rabeehk I'm closing this issue since we resolved your original problem, but feel free to open a new issue if you've run into a separate problem.
