### ISSUE TITLE
urgent help needed: how to register the new data_reader 

### ISSUE THREAD

**Issue by juliahane** [allenai/allennlp#3251]
Hi
I defined a new data reader like snli called snli_weighted and wants to use this one,
when I run my training codes, it says this reader is not register, could you please assist me. 
thanks for your help.
Best
Julia

Traceback (most recent call last):
  File "julia/libs/anaconda3/envs/transformer36/bin/allennlp", line 11, in <module>
    load_entry_point('allennlp', 'console_scripts', 'allennlp')()
  File "julia/dev/rubi/allennlp/allennlp/run.py", line 18, in run
    main(prog="allennlp")
  File "julia/dev/rubi/allennlp/allennlp/commands/__init__.py", line 102, in main
    args.func(args)
  File "julia/dev/rubi/allennlp/allennlp/commands/train.py", line 124, in train_model_from_args
    args.cache_prefix)
  File "julia/dev/rubi/allennlp/allennlp/commands/train.py", line 168, in train_model_from_file
    cache_directory, cache_prefix)
  File "julia/dev/rubi/allennlp/allennlp/commands/train.py", line 226, in train_model
    cache_prefix)
  File "julia/dev/rubi/allennlp/allennlp/training/trainer_pieces.py", line 41, in from_params
    all_datasets = training_util.datasets_from_params(params, cache_directory, cache_prefix)
  File "julia/dev/rubi/allennlp/allennlp/training/util.py", line 165, in datasets_from_params
    dataset_reader = DatasetReader.from_params(dataset_reader_params)
  File "julia/dev/rubi/allennlp/allennlp/common/from_params.py", line 359, in from_params
    default_to_first_choice=default_to_first_choice)
  File "julia/dev/rubi/allennlp/allennlp/common/params.py", line 350, in pop_choice
    raise ConfigurationError(message)
allennlp.common.checks.ConfigurationError: "snli_weighted not in acceptable choices for dataset_reader.type: ['ccgbank', 'conll2003', 'conll2000', 'ontonotes_ner', 'coref', 'winobias', 'event2mind', 'interleaving', 'language_modeling', 'masked_language_modeling', 'next_token_lm', 'multiprocess', 'ptb_trees', 'drop', 'squad', 'quac', 'triviaqa', 'qangaroo', 'srl', 'semantic_dependencies', 'seq2seq', 'sequence_tagging', 'snli', 'universal_dependencies', 'universal_dependencies_multilang', 'sst_tokens', 'quora_paraphrase', 'atis', 'nlvr', 'wikitables', 'template_text2sql', 'grammar_based_text2sql', 'quarel', 'simple_language_modeling', 'babi', 'copynet_seq2seq', 'text_classification_json']"

**Comment by joelgrus** [comment]
when you call `allennlp train` and are using custom classes (dataset readers, models, modules, etc...) you need to pass an extra flag `--include-package my_library.my_module` with the module that your custom code is in.

**Comment by juliahane** [comment]
hi
thanks a lot, I changed it to include this flag  --include-package
dataset_readers.snli_weighted but it says that ModuleNotFoundError: No
module named 'dataset_readers'
I was wondering if you could help me
thanks
Best regards
Julia

**Comment by joelgrus** [comment]
well, the first thing to check is that your file is at (I'm assuming)

```
dataset_readers/snli_weighted.py
```

if it's there, then you might need to 

```
export PYTHONPATH=.
```

so that python looks in your current directory for modules

**Comment by juliahane** [comment]
Hi Joel
could you please assist me and give me the complete commands for this setup
please:

- lets assume we define our snli_weighted.py
in allennlp/data/dataset_readers path
- we add a esim_weighted.jsonnet in training_config folder
- and we add  a model called esim_weighted in allennlp/models

now how should be add them to the model to know about it, I really have a
few days left, and cannot
figure out how to solve the issue
thanks a lot

**Comment by joelgrus** [comment]
you'd probably be better off `pip install`-ing allennlp in a clean virtual environment and using it that way.

however, if you really want to work in the source tree, you can either --include-package with the modules as you've defined them, e.g. `--include-package allennlp.data.dataset_readers.snli_weighted`, or you can add them to the imports in  `__init__.py`, like in

https://github.com/allenai/allennlp/blob/master/allennlp/data/dataset_readers/__init__.py

in which case there's no need to use --include-package

**Comment by DeNeutoy** [comment]
Closing due to inactivity
