### ISSUE TITLE
about the error of  text classification task

### ISSUE THREAD

**Issue by jennifer1995** [allenai/allennlp#3259]
**System (please complete the following information):**
 - OS: Linux
 - Python version: 3.6.7
 - AllenNLP version: latest one

**Question**
I want to use allennlp for the text classification task, and the command is as below:
`allennlp predict model.tar.gz test.txt --predictor text_classifier --cuda-device 0 --output-file ./pred_output`

**ERROR**

```
Traceback (most recent call last):
  File "/espnet/data/Miniconda3/envs/py36arxiv/bin/allennlp", line 10, in <module>
    sys.exit(run())
  File "/espnet/data/Miniconda3/envs/py36arxiv/lib/python3.6/site-packages/allennlp/run.py", line 18, in run
    main(prog="allennlp")
  File "/espnet/data/Miniconda3/envs/py36arxiv/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 102, in main
    args.func(args)
  File "/espnet/data/Miniconda3/envs/py36arxiv/lib/python3.6/site-packages/allennlp/commands/predict.py", line 214, in _predict
    predictor = _get_predictor(args)
  File "/espnet/data/Miniconda3/envs/py36arxiv/lib/python3.6/site-packages/allennlp/commands/predict.py", line 120, in _get_predictor
    overrides=args.overrides)
  File "/espnet/data/Miniconda3/envs/py36arxiv/lib/python3.6/site-packages/allennlp/models/archival.py", line 230, in load_archive
    cuda_device=cuda_device)
  File "/espnet/data/Miniconda3/envs/py36arxiv/lib/python3.6/site-packages/allennlp/models/model.py", line 327, in load
    return cls.by_name(model_type)._load(config, serialization_dir, weights_file, cuda_device)
  File "/espnet/data/Miniconda3/envs/py36arxiv/lib/python3.6/site-packages/allennlp/common/registrable.py", line 58, in by_name
    raise ConfigurationError("%s is not a registered name for %s" % (name, cls.__name__))
allennlp.common.checks.ConfigurationError: 'text_classifier is not a registered name for Model'
```
But I think text_classifier is registered ? Thank you.

**Comment by joelgrus** [comment]
there is a `Predictor` registered as `text_classifier` but not a `Model`. The error suggests that the trained model has a config file that says `"model": {"type": "text_classifier", ...}`, which we don't have one of. Where did the trained model come from?

If that's your own `Model` class, you need to --include-package just as in training.

**Comment by schmmd** [comment]
Please follow up if you have additional questions!

**Comment by CharizardAcademy** [comment]
Is there a way to load the model.tar.gz online and do predictions? I have done:
`from allennlp.predictors.text_classifier import TextClassifierPredictor`
`predictor = TextClassifierPredictor.from_path("/checkpoints/model.tar.gz")`
and get the same error:
`ConfigurationError: 'text_classifier is not a registered name for Model'`

**Comment by CharizardAcademy** [comment]
> there is a `Predictor` registered as `text_classifier` but not a `Model`. The error suggests that the trained model has a config file that says `"model": {"type": "text_classifier", ...}`, which we don't have one of. Where did the trained model come from?
> 
> If that's your own `Model` class, you need to --include-package just as in training.

I have checked the config.json, and indeed I see `"model": {"type": "text_classifier", ...}`. I train my model with `scibert/scripts/train_allennlp_local.sh` for text classification task with customized dataset, and this is the config file I got.
