### ISSUE TITLE
'MultiprocessIterator' object has no attribute 'processes'

### ISSUE THREAD

**Issue by yongtaoge** [allenai/allennlp#3278]
**System**
 - OS: Linux
 - Python version: 3.6.1
 - AllenNLP version: installed from master
 - PyTorch version: 1.2

**Question**
* Report 'MultiprocessIterator' object has no attribute 'processes' error when using multiprocessiterator as the following code:

```
...
bucket_iterator = BucketIterator(batch_size=args.batch_size_per_gpu,
                                max_instances_in_memory=128,
                                instances_per_epoch=102400000,
                                sorting_keys=[("source_tokens", "num_tokens")])
iterator = MultiprocessIterator(bucket_iterator, num_workers=8)
iterator.index_with(vocab)
trainer = Trainer(model=model,
                  optimizer=optimizer,
                  iterator=iterator,
                  train_dataset=train_dataset,
                  validation_dataset=validation_dataset,
                  num_epochs=5,
                  learning_rate_scheduler=lr_scheduler,
                  cuda_device=CUDA_DEVICE,
                  grad_clipping=args.grad_clipping,
                  model_save_interval=1800,
                  serialization_dir=args.serialization_dir,
                  keep_serialized_model_every_num_seconds=3600,
                  should_log_learning_rate=True
                  )
...
```

**Comment by matt-gardner** [comment]
@yongtaoge, can you give a full stack trace with the error?

**Comment by yongtaoge** [comment]
@matt-gardner 
```
Traceback (most recent call last):
  File "examples/mathematic/math_reasoning.py", line 233, in <module>
    main()
  File "examples/mathematic/math_reasoning.py", line 144, in main
    iterator = MultiprocessIterator(bucket_iterator, num_workers=8)
  File "/mnt/lustre/geyongtao/allennlp/allennlp/data/iterators/multiprocess_iterator.py", line 128, in __init__
    raise ConfigurationError("cannot use instances_per_epoch with Multiprocess iterator")
allennlp.common.checks.ConfigurationError: 'cannot use instances_per_epoch with Multiprocess iterator'
Exception ignored in: <bound method MultiprocessIterator.__del__ of <allennlp.data.iterators.multiprocess_iterator.MultiprocessIterator object at 0x7fbccc287080>>
Traceback (most recent call last):
  File "/mnt/lustre/geyongtao/allennlp/allennlp/data/iterators/multiprocess_iterator.py", line 241, in __del__
    for process in self.processes:
AttributeError: 'MultiprocessIterator' object has no attribute 'processes'
srun: error: SH-IDC1-10-5-39-62: task 0: Exited with exit code 1
srun: Terminating job step 853670.0
```

**Comment by matt-gardner** [comment]
So, the full stack trace shows that the error is not what you originally posted; that's a secondary error after the first one, which was the fact that you can't use `instance_per_epoch` with the multiprocess iterator.
