### ISSUE TITLE
FileNotFoundError on loading Elmo model

### ISSUE THREAD

**Issue by anushkmittal** [allenai/allennlp#3329]
**Describe the bug**
can't seem to load elmo_token_embedder with `2x4096_512_2048cnn_2xhighway_options.json` not found. I tried manually going in the location and add that file but it's not picking that up either

**System (please complete the following information):**
 - OS: macos 10.14.4
 - Python version: 3.7
 - AllenNLP version: 0.7.0
 - PyTorch version: 0.4.1

**traceback**

```
10/06/2019 17:17:54 - INFO - allennlp.common.params -   model.text_field_embedder.token_embedders.elmo.type = elmo_token_embedder
[2019-10-06 17:17:54 -0400] [62395] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/anushkmittal/miniconda3/envs/hmtl_two/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/anushkmittal/miniconda3/envs/hmtl_two/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/anushkmittal/miniconda3/envs/hmtl_two/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/anushkmittal/miniconda3/envs/hmtl_two/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/anushkmittal/miniconda3/envs/hmtl_two/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/Users/anushkmittal/miniconda3/envs/hmtl_two/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/anushkmittal/miniconda3/envs/hmtl_two/lib/python3.7/site-packages/gunicorn/util.py", line 362, in import_app
    app = eval(obj, vars(mod))
  File "<string>", line 1, in <module>
  File "/Users/anushkmittal/downloads/hmtl/demo/server.py", line 51, in build_app
    ALL_RESOURCE = AllResource(model_name=model_name, mode=mode)
  File "/Users/anushkmittal/downloads/hmtl/demo/server.py", line 15, in __init__
    self.jmd = HMTLPredictor(model_name=model_name)
  File "/Users/anushkmittal/downloads/hmtl/demo/hmtlPredictor.py", line 129, in __init__
    model, vocab, token_indexers = load_model(model_name=model_name)
  File "/Users/anushkmittal/downloads/hmtl/demo/hmtlPredictor.py", line 115, in load_model
    model = Model.from_params(vocab=vocab, params=model_params, regularizer=None)
  File "/Users/anushkmittal/miniconda3/envs/hmtl_two/lib/python3.7/site-packages/allennlp/common/from_params.py", line 245, in from_params
    return subclass.from_params(params=params, **extras)
  File "../hmtl/models/hmtl.py", line 200, in from_params
    return cls(vocab=vocab, params=params, regularizer=regularizer)
  File "../hmtl/models/hmtl.py", line 49, in __init__
    text_field_embedder = BasicTextFieldEmbedder.from_params(vocab=vocab, params=text_field_embedder_params)
  File "/Users/anushkmittal/miniconda3/envs/hmtl_two/lib/python3.7/site-packages/allennlp/modules/text_field_embedders/basic_text_field_embedder.py", line 117, in from_params
    for name, subparams in token_embedder_params.items()
  File "/Users/anushkmittal/miniconda3/envs/hmtl_two/lib/python3.7/site-packages/allennlp/modules/text_field_embedders/basic_text_field_embedder.py", line 117, in <dictcomp>
    for name, subparams in token_embedder_params.items()
  File "/Users/anushkmittal/miniconda3/envs/hmtl_two/lib/python3.7/site-packages/allennlp/common/from_params.py", line 245, in from_params
    return subclass.from_params(params=params, **extras)
  File "/Users/anushkmittal/miniconda3/envs/hmtl_two/lib/python3.7/site-packages/allennlp/modules/token_embedders/elmo_token_embedder.py", line 98, in from_params
    params.add_file_to_archive('options_file')
  File "/Users/anushkmittal/miniconda3/envs/hmtl_two/lib/python3.7/site-packages/allennlp/common/params.py", line 157, in add_file_to_archive
    self.files_to_archive[f"{self.history}{name}"] = cached_path(self.get(name))
  File "/Users/anushkmittal/miniconda3/envs/hmtl_two/lib/python3.7/site-packages/allennlp/common/file_utils.py", line 92, in cached_path
    raise FileNotFoundError("file {} not found".format(url_or_filename))
FileNotFoundError: file ../data/elmo/2x4096_512_2048cnn_2xhighway_options.json not found
```

**Comment by anushkmittal** [comment]
nvm, i was putting data at the wrong place. it was requesting my PWD rather than in package's directory.
