### ISSUE TITLE
Issue in overrides 

### ISSUE THREAD

**Issue by dDua** [allenai/allennlp#3401]
**Describe the bug**
The same code I have been using for past week started giving the following error today 

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/overrides/overrides.py", line 165, in _get_base_class
    obj = namespace[components[0]]
KeyError: 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.6/site-packages/allennlp/run.py", line 14, in <module>
    from allennlp.commands import main  # noqa
  File "/opt/conda/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 8, in <module>
    from allennlp.commands.configure import Configure
  File "/opt/conda/lib/python3.6/site-packages/allennlp/commands/configure.py", line 26, in <module>
    from allennlp.service.config_explorer import make_app
  File "/opt/conda/lib/python3.6/site-packages/allennlp/service/config_explorer.py", line 24, in <module>
    from allennlp.common.configuration import configure, choices
  File "/opt/conda/lib/python3.6/site-packages/allennlp/common/configuration.py", line 27, in <module>
    from allennlp.data.dataset_readers import DatasetReader
  File "/opt/conda/lib/python3.6/site-packages/allennlp/data/__init__.py", line 1, in <module>
    from allennlp.data.dataset_readers.dataset_reader import DatasetReader
  File "/opt/conda/lib/python3.6/site-packages/allennlp/data/dataset_readers/__init__.py", line 10, in <module>
    from allennlp.data.dataset_readers.ccgbank import CcgBankDatasetReader
  File "/opt/conda/lib/python3.6/site-packages/allennlp/data/dataset_readers/ccgbank.py", line 9, in <module>
    from allennlp.data.dataset_readers.dataset_reader import DatasetReader
  File "/opt/conda/lib/python3.6/site-packages/allennlp/data/dataset_readers/dataset_reader.py", line 8, in <module>
    from allennlp.data.instance import Instance
  File "/opt/conda/lib/python3.6/site-packages/allennlp/data/instance.py", line 3, in <module>
    from allennlp.data.fields.field import DataArray, Field
  File "/opt/conda/lib/python3.6/site-packages/allennlp/data/fields/__init__.py", line 13, in <module>
    from allennlp.data.fields.metadata_field import MetadataField
  File "/opt/conda/lib/python3.6/site-packages/allennlp/data/fields/metadata_field.py", line 8, in <module>
    class MetadataField(Field[DataArray], Mapping[str, Any]):
  File "/opt/conda/lib/python3.6/site-packages/allennlp/data/fields/metadata_field.py", line 49, in MetadataField
    def get_padding_lengths(self) -> Dict[str, int]:
  File "/opt/conda/lib/python3.6/site-packages/overrides/overrides.py", line 58, in overrides
    for super_class in _get_base_classes(sys._getframe(2), method.__globals__):
  File "/opt/conda/lib/python3.6/site-packages/overrides/overrides.py", line 75, in _get_base_classes
    class_name_components in _get_base_class_names(frame)]
  File "/opt/conda/lib/python3.6/site-packages/overrides/overrides.py", line 75, in <listcomp>
    class_name_components in _get_base_class_names(frame)]
  File "/opt/conda/lib/python3.6/site-packages/overrides/overrides.py", line 167, in _get_base_class
    obj = getattr(namespace["__builtins__"], components[0])
AttributeError: 'dict' object has no attribute 'str'

**Additional context**
After some debugging, I think this is happening after a new release of overrides package this morning. When I uninstall version 2.1 and install version 2.0 of overrides it works fine. Perhaps specifying the version 2.0 in requirements.txt would solve the problem?

**Comment by matt-gardner** [comment]
Yes, can you please open a PR to pin the overrides version?  It'd also be useful to submit this error upstream to the overrides repo.
