### ISSUE TITLE
"arguments are located on different GPUs" error when resume training the SNLI model

### ISSUE THREAD

**Issue by luheng** [allenai/allennlp#345]
I got the following error when training an SNLI (decomposed attention) model from a previous checkpoint:
``Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "~/Workspace/allennlp/allennlp/run.py", line 13, in <module>
    main(prog="python -m allennlp.run")
  File "~/Workspace/allennlp/allennlp/commands/__init__.py", line 61, in main
    args.func(args)
  File "~/Workspace/allennlp/allennlp/commands/train.py", line 62, in _train_model_from_args
    train_model_from_file(args.param_path, args.serialization_dir)
  File "~/Workspace/allennlp/allennlp/commands/train.py", line 81, in train_model_from_file
    return train_model(params, serialization_dir)
  File "~/Workspace/allennlp/allennlp/commands/train.py", line 149, in train_model
    trainer.train()
  File "~/Workspace/allennlp/allennlp/training/trainer.py", line 183, in train
    self._optimizer.step()
  File "~/allennlp-venv/lib/python3.6/site-packages/torch/optim/adagrad.py", line 83, in step
    state['sum'].addcmul_(1, grad, grad)
RuntimeError: arguments are located on different GPUs at /pytorch/torch/lib/THC/generated/../generic/THCTensorMathPointwise.cu:533``

I used a slightly different set of hyper-parameters (with the glove 840b-300d embeddings, etc.), so I'm not sure how reproducible this error is. I'm training with a single GPU.

**Comment by DeNeutoy** [comment]
Did you change the parameter file in-between training and resuming? This shouldn't happen if you just load a model without changing the config file. 

It is related to this: https://github.com/pytorch/pytorch/issues/2021, but I thought we had fixed it in #205. I will try reproducing it tomorrow, thanks for opening the issue. If you use any other optimizer I think you should be ok.

**Comment by luheng** [comment]
Thanks for the quick reply! I just checked, the config file seems to be unchanged.

**Comment by matt-gardner** [comment]
My guess is that the issue is here:

https://github.com/allenai/allennlp/blob/b12517c78db605eda815a0468fd92c014e37821b/allennlp/training/trainer.py#L340-L343

We're loading the model state to the right cuda device, but not the trainer state, which includes the optimizer.

**Comment by jacklone** [comment]
has this error been fixed, I still get this error.
I trained the model in **gpu 1** with a small *num_epochs* in the config file, then I changed the *num_epochs* to a bigger one, and got the error. But if the *cuda_device* is set to **0**, it's ok.

```
 0%|          | 0/1 [00:00<?, ?it/s]2018-02-09 09:18:36,170 - INFO - allennlp.training.trainer - Training
Traceback (most recent call last):
  File "run.py", line 20, in <module>
    main(prog="python run.py", predictor_overrides=NoCodePredictors)
  File "/home/chenglong/deploy/allennlp/allennlp/commands/__init__.py", line 79, in main
    args.func(args)
  File "/home/chenglong/deploy/allennlp/allennlp/commands/train.py", line 93, in train_model_from_args
    train_model_from_file(args.param_path, args.serialization_dir, args.overrides, args.file_friendly_logging)
  File "/home/chenglong/deploy/allennlp/allennlp/commands/train.py", line 112, in train_model_from_file
    return train_model(params, serialization_dir, file_friendly_logging)
  File "/home/chenglong/deploy/allennlp/allennlp/commands/train.py", line 206, in train_model
    metrics = trainer.train()
  File "/home/chenglong/deploy/allennlp/allennlp/training/trainer.py", line 640, in train
    train_metrics = self._train_epoch(epoch)
  File "/home/chenglong/deploy/allennlp/allennlp/training/trainer.py", line 456, in _train_epoch
    self._optimizer.step()
  File "/home/chenglong/.conda/envs/torch/lib/python3.6/site-packages/torch/optim/adagrad.py", line 82, in step
    state['sum'].addcmul_(1, grad, grad)
RuntimeError: arguments are located on different GPUs at /pytorch/torch/lib/THC/generated/../generic/THCTensorMathPointwise.cu:587
```

**Comment by lan2720** [comment]
@jacklone the same case with you. #7405
