### ISSUE TITLE
allennlp.common.checks.ConfigurationError: 'just_spaces not in acceptable choices for dataset_reader.base_reader.tokenizer.type

### ISSUE THREAD

**Issue by acriptis** [allenai/allennlp#3454]
I'm trying to reproduce training of ELMO on transformers from this tutorial:
https://github.com/allenai/allennlp/blob/master/tutorials/how_to/training_transformer_elmo.md#training

Unfortunately when I call 
```
allennlp train training_config/bidirectional_language_model.jsonnet --serialization-dir output_path
```
I receive exception:
```
2019-11-15 14:47:00,337 - INFO - allennlp.common.registrable - instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
2019-11-15 14:47:00,338 - INFO - allennlp.common.registrable - instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
2019-11-15 14:47:00,338 - INFO - allennlp.common.registrable - instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
2019-11-15 14:47:00,338 - INFO - allennlp.common.registrable - instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
2019-11-15 14:47:00,383 - INFO - allennlp.common.params - random_seed = 13370
2019-11-15 14:47:00,383 - INFO - allennlp.common.params - numpy_seed = 1337
2019-11-15 14:47:00,384 - INFO - allennlp.common.params - pytorch_seed = 133
2019-11-15 14:47:00,406 - INFO - allennlp.common.checks - Pytorch version: 1.3.1
2019-11-15 14:47:00,406 - INFO - allennlp.common.params - evaluate_on_test = False
2019-11-15 14:47:00,407 - INFO - allennlp.common.params - validation_dataset_reader = None
2019-11-15 14:47:00,407 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.data.dataset_readers.dataset_reader.DatasetReader'> from params {'base_reader': {'end_tokens': ['</S>'], 'max_sequence_length': 400, 'start_tokens': ['<S>'], 'token_indexers': {'token_characters': {'type': 'elmo_characters'}, 'tokens': {'type': 'single_id'}}, 'tokenizer': {'type': 'just_spaces'}, 'type': 'simple_language_modeling'}, 'num_workers': 4, 'output_queue_size': 1000, 'type': 'multiprocess'} and extras set()
2019-11-15 14:47:00,407 - INFO - allennlp.common.params - dataset_reader.type = multiprocess
2019-11-15 14:47:00,407 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.data.dataset_readers.multiprocess_dataset_reader.MultiprocessDatasetReader'> from params {'base_reader': {'end_tokens': ['</S>'], 'max_sequence_length': 400, 'start_tokens': ['<S>'], 'token_indexers': {'token_characters': {'type': 'elmo_characters'}, 'tokens': {'type': 'single_id'}}, 'tokenizer': {'type': 'just_spaces'}, 'type': 'simple_language_modeling'}, 'num_workers': 4, 'output_queue_size': 1000} and extras set()
2019-11-15 14:47:00,407 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.data.dataset_readers.dataset_reader.DatasetReader'> from params {'end_tokens': ['</S>'], 'max_sequence_length': 400, 'start_tokens': ['<S>'], 'token_indexers': {'token_characters': {'type': 'elmo_characters'}, 'tokens': {'type': 'single_id'}}, 'tokenizer': {'type': 'just_spaces'}, 'type': 'simple_language_modeling'} and extras set()
2019-11-15 14:47:00,407 - INFO - allennlp.common.params - dataset_reader.base_reader.type = simple_language_modeling
2019-11-15 14:47:00,407 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.data.dataset_readers.simple_language_modeling.SimpleLanguageModelingDatasetReader'> from params {'end_tokens': ['</S>'], 'max_sequence_length': 400, 'start_tokens': ['<S>'], 'token_indexers': {'token_characters': {'type': 'elmo_characters'}, 'tokens': {'type': 'single_id'}}, 'tokenizer': {'type': 'just_spaces'}} and extras set()
2019-11-15 14:47:00,407 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.data.tokenizers.tokenizer.Tokenizer'> from params {'type': 'just_spaces'} and extras set()
2019-11-15 14:47:00,407 - INFO - allennlp.common.params - dataset_reader.base_reader.tokenizer.type = just_spaces
Traceback (most recent call last):
  File "/home/alx/Cloud/.venv3gpu/bin/allennlp", line 8, in <module>
    sys.exit(run())
  File "/home/alx/Cloud/.venv3gpu/lib/python3.6/site-packages/allennlp/run.py", line 18, in run
    main(prog="allennlp")
  File "/home/alx/Cloud/.venv3gpu/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 102, in main
    args.func(args)
  File "/home/alx/Cloud/.venv3gpu/lib/python3.6/site-packages/allennlp/commands/train.py", line 124, in train_model_from_args
    args.cache_prefix)
  File "/home/alx/Cloud/.venv3gpu/lib/python3.6/site-packages/allennlp/commands/train.py", line 168, in train_model_from_file
    cache_directory, cache_prefix)
  File "/home/alx/Cloud/.venv3gpu/lib/python3.6/site-packages/allennlp/commands/train.py", line 226, in train_model
    cache_prefix)
  File "/home/alx/Cloud/.venv3gpu/lib/python3.6/site-packages/allennlp/training/trainer_pieces.py", line 42, in from_params
    all_datasets = training_util.datasets_from_params(params, cache_directory, cache_prefix)
  File "/home/alx/Cloud/.venv3gpu/lib/python3.6/site-packages/allennlp/training/util.py", line 165, in datasets_from_params
    dataset_reader = DatasetReader.from_params(dataset_reader_params)
  File "/home/alx/Cloud/.venv3gpu/lib/python3.6/site-packages/allennlp/common/from_params.py", line 365, in from_params
    return subclass.from_params(params=params, **extras)
  File "/home/alx/Cloud/.venv3gpu/lib/python3.6/site-packages/allennlp/common/from_params.py", line 386, in from_params
    kwargs = create_kwargs(cls, params, **extras)
  File "/home/alx/Cloud/.venv3gpu/lib/python3.6/site-packages/allennlp/common/from_params.py", line 133, in create_kwargs
    kwargs[name] = construct_arg(cls, name, annotation, param.default, params, **extras)
  File "/home/alx/Cloud/.venv3gpu/lib/python3.6/site-packages/allennlp/common/from_params.py", line 229, in construct_arg
    return annotation.from_params(params=subparams, **subextras)
  File "/home/alx/Cloud/.venv3gpu/lib/python3.6/site-packages/allennlp/common/from_params.py", line 365, in from_params
    return subclass.from_params(params=params, **extras)
  File "/home/alx/Cloud/.venv3gpu/lib/python3.6/site-packages/allennlp/common/from_params.py", line 386, in from_params
    kwargs = create_kwargs(cls, params, **extras)
  File "/home/alx/Cloud/.venv3gpu/lib/python3.6/site-packages/allennlp/common/from_params.py", line 133, in create_kwargs
    kwargs[name] = construct_arg(cls, name, annotation, param.default, params, **extras)
  File "/home/alx/Cloud/.venv3gpu/lib/python3.6/site-packages/allennlp/common/from_params.py", line 229, in construct_arg
    return annotation.from_params(params=subparams, **subextras)
  File "/home/alx/Cloud/.venv3gpu/lib/python3.6/site-packages/allennlp/common/from_params.py", line 359, in from_params
    default_to_first_choice=default_to_first_choice)
  File "/home/alx/Cloud/.venv3gpu/lib/python3.6/site-packages/allennlp/common/params.py", line 363, in pop_choice
    raise ConfigurationError(message)
allennlp.common.checks.ConfigurationError: 'just_spaces not in acceptable choices for dataset_reader.base_reader.tokenizer.type: [\'word\', \'pretrained_transformer\', \'character\']. You should either use the --include-package flag to make sure the correct module is loaded, or use a fully qualified class name in your config file like {"model": "my_module.models.MyModel"} to have it imported automatically.'

```

As I understand the problem in tokenizer which specified in https://github.com/allenai/allennlp/blob/master/training_config/bidirectional_language_model.jsonnet#L11
What I should change in config or specify in cli arguments to runs the training?

**System (please complete the following information):**
 - OS: Linux
 - Python version: 3.6.8
 - AllenNLP version: 0.9.0
 - PyTorch version: 
pytorch-transformers==1.1.0
torch==1.3.1
torchvision==0.4.1

**Comment by acriptis** [comment]
I changed the type to "word" here: https://github.com/allenai/allennlp/blob/master/training_config/bidirectional_language_model.jsonnet#L11
And process has started! I hope it is correct fix.

**Comment by matt-gardner** [comment]
Can you share what version of allennlp you're using?  It looks to me like the issue is that you're using a version of the jsonnet file from master, but you're using code from a release.  We've changed how tokenizers are structured a little bit, and to use the most recent jsonnet file, you need to use the latest master.

**Comment by acriptis** [comment]
@matt-gardner, Yes, indeed, I've installed the allennlp as `pip install allennlp` and config used from master.

`allennlp==0.9.0`

**Comment by acriptis** [comment]
Is it correct to use "word" attribute there for version 0.9.0?

How to specify in the jsonnet config frequency and location for the model to be saved? (My model is trained for weekend by I don't see any `model.tar.gz` file in output directory. Only logs for tensorboard. It seems that if I push Ctrl-C i miss all results of training :-\ )

**Comment by matt-gardner** [comment]
You should probably just check out the file from version 0.9.0 - there was another layer of nesting in that version, and you should probably use the original tokenizer - using spacy to tokenize things when the original just used whitespace will give you a slightly different result.

Can you `ls` the output directory?  If it was training for a weekend and got through more than one epoch, there should definitely be something saved.

**Comment by acriptis** [comment]
@matt-gardner I've checked my config. my config differs from the https://github.com/allenai/allennlp/blob/v0.9.0/training_config/bidirectional_language_model.jsonnet with missing key 
```
"word_splitter": {
            "type": "just_spaces"
          }
```
Do you know if it fatal and I should restart process with this config values?

As well I changed `max_instances_in_memory = 10000 * NUM_GPUS,`
`"batch_size": 128 * NUM_GPUS,`, after avoiding memory errors.

I have a training dataset with 30GB of Russian texts. Is there any heuristics how to estimate time for one epoch or is it possible to grasp some info about epoch from logs?

My log of execution of `allennlp train training_config/bidirectional_language_model.jsonnet --serialization-dir output_path`
is
![191119_allennlp_training_log](https://user-images.githubusercontent.com/2207706/69128620-c8ab7d00-0abd-11ea-99d4-b5b743465fc0.png)


and content of the folder with launched ongoing results of training:
![191119_ll_results_allennlp_elmo_transformer](https://user-images.githubusercontent.com/2207706/69128918-5d15df80-0abe-11ea-8472-304e7d3c662e.png)

**Comment by matt-gardner** [comment]
I don't know which tokenization is better for your application; I'd recommend looking at the output of the tokenizer in both cases (and maybe some other options also, like a Russian-specific tokenizer), and deciding which one looks best for you.

As far as how long to make each epoch, you definitely don't want to have one epoch be one full pass through 30GB of data.  I don't have good intuitions for what to set it to, though; maybe @matt-peters or @DeNeutoy have better advice there.  The parameter you would want to set is [this one in the data iterator](https://github.com/allenai/allennlp/blob/e0f573a4d3a3ecbc1b0e10dd7fd7f48f6269e744/allennlp/data/iterators/data_iterator.py#L39-L41).

**Comment by acriptis** [comment]
@matt-gardner thanks Matt for your help!
