### ISSUE TITLE
SrlBert not reporting precision, recall, F1

### ISSUE THREAD

**Issue by beneyal** [allenai/allennlp#3472]
When training the `SrlBert` model, I'm not getting metrics such as precision, recall, and F1 during validation. I'm also not getting those metrics when using `allennlp evaluate`.

**To Reproduce**
Run the follwing code:

```python
reader = SrlReader(bert_model_name="bert-base-multilingual-cased")
instances = reader.read("conll-2012/data/test/")
vocab = Vocabulary.from_instances(instances)
bert_model = BertModel.from_pretrained("bert-base-multilingual-cased")
model = SrlBert(vocab, bert_model)
iterator = BucketIterator(sorting_keys=[("tokens", "num_tokens")], batch_size=80)
iterator.index_with(vocab)
optimizer = torch.optim.Adam(model.parameters())
trainer = Trainer(model=model,
                  optimizer=optimizer,
                  iterator=iterator,
                  train_dataset=instances,
                  validation_dataset=instances,
                  cuda_device=-1)
trainer.train()
```

**Expected behavior**
I expect to see the metrics mentioned above.

**System (please complete the following information):**
 - OS: Ubuntu 18.04.3
 - Python version: 3.7.5
 - AllenNLP version: v0.9.0
 - PyTorch version: 1.3.1

**Comment by DeNeutoy** [comment]
I think this is probably because the path for the SRL perl script evaluation is wrong... I'm not sure what it resolves to if the entry point isn't running `allennlp`. 

https://github.com/allenai/allennlp/blob/master/allennlp/training/metrics/srl_eval_scorer.py#L17

**Comment by beneyal** [comment]
I'm also not getting those metrics when using `allennlp train`. Could it be that my validation dataset is too small? Or my results so bad that I'm getting zeros?

**Comment by DeNeutoy** [comment]
oh, so it prints them out but they are zero?

**Comment by beneyal** [comment]
Yeah. I'm getting this line:
```
precision-overall: 0.0000, recall-overall: 0.0000, f1-measure-overall: 0.0000, loss: <some loss>
```
in both training and validation. The metrics just stay at zero. I know they're supposed to be zero during training, but it's weird they stay zero during validation...

**Comment by nelson-liu** [comment]
what happens if you `allennlp evaluate https://s3-us-west-2.amazonaws.com/allennlp/models/bert-base-srl-2019.06.17.tar.gz <data path here>`?

**Comment by beneyal** [comment]
When I'm running `allennlp evaluate https://s3-us-west-2.amazonaws.com/allennlp/models/bert-base-srl-2019.06.17.tar.gz conll-2012/data/train/data/english/annotations/bc/cctv/` (`conll-2012` folder is where my OntoNotes 5.0 in CoNLL format is located), I'm getting a `KeyError: '@@UNKNOWN@@'`.

**Comment by DeNeutoy** [comment]
What is the loss in your example? Is it non-zero? Can you post the full stack trace for that `KeyError`?

**Comment by beneyal** [comment]
In my example, the loss is indeed non-zero, only the metrics are zero.

The stack trace for the `KeyError`:

```
2019-11-23 01:10:53,154 - INFO - allennlp.common.registrable - instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
2019-11-23 01:10:53,154 - INFO - allennlp.common.registrable - instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
2019-11-23 01:10:53,155 - INFO - allennlp.common.registrable - instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
2019-11-23 01:10:53,156 - INFO - allennlp.common.registrable - instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
2019-11-23 01:10:54,420 - INFO - allennlp.models.archival - loading archive file https://s3-us-west-2.amazonaws.com/allennlp/models/bert-base-srl-2019.06.17.tar.gz from cache at /home/bene/.allennlp/cache/9dd222683455607bdfd06f69485202fd5b4c6ca3a62233a49ee143ef58870efe.51b0dcc803dcadb028739a76e83f068d9ef84f66fc895192a3445a92e034350b
2019-11-23 01:10:54,422 - INFO - allennlp.models.archival - extracting archive file /home/bene/.allennlp/cache/9dd222683455607bdfd06f69485202fd5b4c6ca3a62233a49ee143ef58870efe.51b0dcc803dcadb028739a76e83f068d9ef84f66fc895192a3445a92e034350b to temp dir /tmp/tmpo4wwy4xk
2019-11-23 01:10:57,705 - INFO - allennlp.common.registrable - instantiating registered subclass srl_bert of <class 'allennlp.models.model.Model'>
2019-11-23 01:10:57,706 - INFO - allennlp.common.registrable - instantiating registered subclass default of <class 'allennlp.data.vocabulary.Vocabulary'>
2019-11-23 01:10:57,706 - INFO - allennlp.data.vocabulary - Loading token dictionary from /tmp/tmpo4wwy4xk/vocabulary.
2019-11-23 01:10:57,706 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.models.model.Model'> from params {'bert_model': 'bert-base-uncased', 'embedding_dropout': 0.1, 'type': 'srl_bert'} and extras {'vocab'}
2019-11-23 01:10:57,706 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.models.srl_bert.SrlBert'> from params {'bert_model': 'bert-base-uncased', 'embedding_dropout': 0.1} and extras {'vocab'}
2019-11-23 01:10:58,516 - INFO - pytorch_pretrained_bert.modeling - loading archive file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased.tar.gz from cache at /home/bene/.pytorch_pretrained_bert/9c41111e2de84547a463fd39217199738d1e3deb72d4fec4399e6e241983c6f0.ae3cef932725ca7a30cdcb93fc6e09150a55e2a130ec7af63975a16c153ae2ba
2019-11-23 01:10:58,516 - INFO - pytorch_pretrained_bert.modeling - extracting archive file /home/bene/.pytorch_pretrained_bert/9c41111e2de84547a463fd39217199738d1e3deb72d4fec4399e6e241983c6f0.ae3cef932725ca7a30cdcb93fc6e09150a55e2a130ec7af63975a16c153ae2ba to temp dir /tmp/tmpmbljc_p5
2019-11-23 01:11:01,775 - INFO - pytorch_pretrained_bert.modeling - Model config {
  "attention_probs_dropout_prob": 0.1,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "type_vocab_size": 2,
  "vocab_size": 30522
}

2019-11-23 01:11:03,439 - INFO - allennlp.common.checks - Pytorch version: 1.3.1
2019-11-23 01:11:03,440 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.data.dataset_readers.dataset_reader.DatasetReader'> from params {'bert_model_name': 'bert-base-uncased', 'type': 'srl'} and extras set()
2019-11-23 01:11:03,440 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.data.dataset_readers.semantic_role_labeling.SrlReader'> from params {'bert_model_name': 'bert-base-uncased'} and extras set()
2019-11-23 01:11:04,148 - INFO - pytorch_pretrained_bert.tokenization - loading vocabulary file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-vocab.txt from cache at /home/bene/.pytorch_pretrained_bert/26bc1ad6c0ac742e9b52263248f6d0f00068293b33709fae12320c0e35ccfbbb.542ce4285a40d23a559526243235df47c5f75c197f04f37d1a0c124c32c9a084
2019-11-23 01:11:04,178 - INFO - allennlp.commands.evaluate - Reading evaluation data from conll-2012/data/train/data/english/annotations/bc/cctv
0it [00:00, ?it/s]2019-11-23 01:11:04,180 - INFO - allennlp.data.dataset_readers.semantic_role_labeling - Reading SRL instances from dataset files at: conll-2012/data/train/data/english/annotations/bc/cctv
2019-11-23 01:11:04,180 - INFO - allennlp.data.dataset_readers.dataset_utils.ontonotes - Reading CONLL sentences from dataset files at: conll-2012/data/train/data/english/annotations/bc/cctv
3644it [00:01, 3564.58it/s]
2019-11-23 01:11:05,201 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.data.iterators.data_iterator.DataIterator'> from params {'batch_size': 32, 'sorting_keys': [['tokens', 'num_tokens']], 'type': 'bucket'} and extras set()
2019-11-23 01:11:05,201 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.data.iterators.bucket_iterator.BucketIterator'> from params {'batch_size': 32, 'sorting_keys': [['tokens', 'num_tokens']]} and extras set()
2019-11-23 01:11:05,202 - INFO - allennlp.training.util - Iterating over dataset
  0%|                                                                                                                | 0/114 [00:00<?, ?it/s]2019-11-23 01:11:05,204 - ERROR - allennlp.data.vocabulary - Namespace: labels
2019-11-23 01:11:05,204 - ERROR - allennlp.data.vocabulary - Token: B-ARG1(R-ARG2
Traceback (most recent call last):
  File "/home/bene/miniconda3/envs/allennlp/bin/allennlp", line 8, in <module>
    sys.exit(run())
  File "/home/bene/miniconda3/envs/allennlp/lib/python3.7/site-packages/allennlp/run.py", line 18, in run
    main(prog="allennlp")
  File "/home/bene/miniconda3/envs/allennlp/lib/python3.7/site-packages/allennlp/commands/__init__.py", line 102, in main
    args.func(args)
  File "/home/bene/miniconda3/envs/allennlp/lib/python3.7/site-packages/allennlp/commands/evaluate.py", line 161, in evaluate_from_args
    metrics = evaluate(model, instances, iterator, args.cuda_device, args.batch_weight_key)
  File "/home/bene/miniconda3/envs/allennlp/lib/python3.7/site-packages/allennlp/training/util.py", line 391, in evaluate
    for batch in generator_tqdm:
  File "/home/bene/miniconda3/envs/allennlp/lib/python3.7/site-packages/tqdm/std.py", line 1091, in __iter__
    for obj in iterable:
  File "/home/bene/miniconda3/envs/allennlp/lib/python3.7/site-packages/allennlp/data/iterators/data_iterator.py", line 143, in __call__
    for batch in batches:
  File "/home/bene/miniconda3/envs/allennlp/lib/python3.7/site-packages/allennlp/data/iterators/bucket_iterator.py", line 124, in _create_batches
    self._padding_noise)
  File "/home/bene/miniconda3/envs/allennlp/lib/python3.7/site-packages/allennlp/data/iterators/bucket_iterator.py", line 30, in sort_by_padding
    instance.index_fields(vocab)
  File "/home/bene/miniconda3/envs/allennlp/lib/python3.7/site-packages/allennlp/data/instance.py", line 72, in index_fields
    field.index(vocab)
  File "/home/bene/miniconda3/envs/allennlp/lib/python3.7/site-packages/allennlp/data/fields/sequence_label_field.py", line 100, in index
    for label in self.labels]
  File "/home/bene/miniconda3/envs/allennlp/lib/python3.7/site-packages/allennlp/data/fields/sequence_label_field.py", line 100, in <listcomp>
    for label in self.labels]
  File "/home/bene/miniconda3/envs/allennlp/lib/python3.7/site-packages/allennlp/data/vocabulary.py", line 637, in get_token_index
    return self._token_to_index[namespace][self._oov_token]
KeyError: '@@UNKNOWN@@'
2019-11-23 01:11:05,206 - INFO - allennlp.models.archival - removing temporary unarchived model dir at /tmp/tmpo4wwy4xk
```

**Comment by DeNeutoy** [comment]
looks like the dataset reader has a bug in for whatever data you are using, as this is not a valid label:
B-ARG1(R-ARG2

**Comment by beneyal** [comment]
Weird, because I can use `allennlp.data.dataset_readers.semantic_role_labeling.SrlReader` just fine to read the contents of the same directory:

```
In [1]: from allennlp.data.dataset_readers.semantic_role_labeling import SrlReader                                                           

In [2]: reader = SrlReader(bert_model_name="bert-base-multilingual-cased")                                                                   
The pre-trained model you are loading is a cased model but you have not set `do_lower_case` to False. We are setting `do_lower_case=False` for you but you may want to check this behavior.

In [3]: instances = reader.read("conll-2012/data/train/data/english/annotations/bc/cctv/")                                                   
3644it [00:01, 3074.48it/s]

In [4]: len(instances)                                                                                                                       
Out[4]: 3644
```

**Comment by DeNeutoy** [comment]
Yes - but look at that label. Just because the reader doesn't crash, it doesn't mean it is working correctly. I'd recommend you try to figure out where that label is coming from and correct it - probably by adding in some checks within the SRL reader itself, or just by searching for the token in the set of files you are trying to load.

**Comment by beneyal** [comment]
OK, so I recreated the dataset using the OntoNotes instructions instead of the CoNLL 2012 instructions and now the mode is evaluating. I definitely see the metrics: F1 is 1.00 and loss is 0.00.
