### ISSUE TITLE
AttributeError: 'PretrainedBertIndexer' object has no attribute 'wordpiece_tokenizer'?

### ISSUE THREAD

**Issue by yyHaker** [allenai/allennlp#3480]
**Describe the bug**
I want to use Bert to fine-tuning SNLI tasks, my dataset reader is as [snli_bert.py](https://github.com/yyHaker/AllenNLPNeedsMoreLove/blob/master/src/data_loader/snli_bert.py), and my config file is as [snli_bert.jsonnet](https://github.com/yyHaker/AllenNLPNeedsMoreLove/blob/master/src/config_file/snli_bert.jsonnet), I just run [train.py](https://github.com/yyHaker/AllenNLPNeedsMoreLove/blob/master/src/train.py) to train the model, however I encounter following errors: 
```
10it [00:23,  2.31s/it]
  0%|          | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/users4/yle/.vscode-server/extensions/ms-python.python-2019.11.50794/pythonFiles/ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "/users4/yle/.vscode-server/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 432, in main
    run()
  File "/users4/yle/.vscode-server/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/users4/yle/anaconda3/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/users4/yle/anaconda3/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/users4/yle/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/users4/yle/EKMRC/src/train.py", line 24, in <module>
    model = train_model(params, serialization_dir, force=True, cache_directory="temp/snli/bert")
  File "/users4/yle/anaconda3/lib/python3.6/site-packages/allennlp/commands/train.py", line 252, in train_model
    metrics = trainer.train()
  File "/users4/yle/anaconda3/lib/python3.6/site-packages/allennlp/training/trainer.py", line 478, in train
    train_metrics = self._train_epoch(epoch)
  File "/users4/yle/anaconda3/lib/python3.6/site-packages/allennlp/training/trainer.py", line 313, in _train_epoch
    for batch_group in train_generator_tqdm:
  File "/users4/yle/anaconda3/lib/python3.6/site-packages/tqdm/std.py", line 1081, in __iter__
    for obj in iterable:
  File "/users4/yle/anaconda3/lib/python3.6/site-packages/allennlp/common/util.py", line 104, in <lambda>
    return iter(lambda: list(islice(iterator, 0, group_size)), [])
  File "/users4/yle/anaconda3/lib/python3.6/site-packages/allennlp/data/iterators/data_iterator.py", line 143, in __call__
    for batch in batches:
  File "/users4/yle/anaconda3/lib/python3.6/site-packages/allennlp/data/iterators/bucket_iterator.py", line 124, in _create_batches
    self._padding_noise)
  File "/users4/yle/anaconda3/lib/python3.6/site-packages/allennlp/data/iterators/bucket_iterator.py", line 30, in sort_by_padding
    instance.index_fields(vocab)
  File "/users4/yle/anaconda3/lib/python3.6/site-packages/allennlp/data/instance.py", line 72, in index_fields
    field.index(vocab)
  File "/users4/yle/anaconda3/lib/python3.6/site-packages/allennlp/data/fields/text_field.py", line 70, in index
    token_indices = indexer.tokens_to_indices(self.tokens, vocab, indexer_name)
  File "/users4/yle/anaconda3/lib/python3.6/site-packages/allennlp/data/token_indexers/wordpiece_indexer.py", line 152, in tokens_to_indices
    for token in text]
  File "/users4/yle/anaconda3/lib/python3.6/site-packages/allennlp/data/token_indexers/wordpiece_indexer.py", line 152, in <listcomp>
    for token in text]
AttributeError: 'PretrainedBertIndexer' object has no attribute 'wordpiece_tokenizer'
  0%|          | 0/1 [00:17<?, ?it/s]
```

What's wrong with it? I am very confusing about 'PretrainedBertIndexer' object did have attribute 'wordpiece_tokenizer', why this will happen?

**System (please complete the following information):**
 - OS: [ Linux]
 - Python version: [3.6.5]
 - AllenNLP version: [v0.9.0]
 - PyTorch version: (1.2.0)

**Comment by brendan-ai2** [comment]
Hi @yyHaker, we're going to be cleaning up our API for version 1.0 here (see https://github.com/allenai/allennlp/issues?q=is%3Aissue+is%3Aopen+transformer+milestone%3A1.0.0), so while it's possible this is a bug on our side, we're not able to invest much time now. If you could provide a minimal reproduction of the bug, we might be able to give advice for a quick fix, however. Sorry for the trouble.

**Comment by maksym-del** [comment]
@yyHaker you use "pretrained_transformer" tokenizer and "bert_predtrained" indexer.

You should either use both "pretrained_transformer" indexer and tokenizer, or both "bert_predtrained" indexer and tokenizer.

**Comment by STayinloves** [comment]
I encounter a similar problem after enabling cached instances. It's probably not related to using both indexer and tokenizer under the same name because `PretrainedBertIndexer` should have the attribute `wordpiece_tokenizer`.

**Comment by DeNeutoy** [comment]
closing due to inactivity
