### ISSUE TITLE
Fields with None type inside?

### ISSUE THREAD

**Issue by aligholami** [allenai/allennlp#3488]
Hi. What happens if we have a testing scenario where `labels` have a value of `None` in the official example `academic_paper_classification`? Is there any DataField that can keep None values inside? 

I am implementing this model for a simple comment classification task and I have the following `text_to_instance` method:
```
def text_to_instance(self, x: str, y: np.ndarray = None) -> Instance:
    """
    Converts x, y with type string, numpy array to AllenNLP compatible TextField and Numpy arrays.
    :param x: comment with string type.
    :param y: classes that the comment belongs to; a multi-hot vector of type numpy array. (if train==true)
    :return: data encoded in the AllenNLP data format.
    """
    x_tokenized = self._tokenizer.tokenize(x)
    comment_field = TextField(x_tokenized, self._token_indexers)

    fields = {'comment': comment_field}

    if self.train:
        fields['label'] = ArrayField(array=y)
    else:
        fields['label'] = None

    return Instance(fields)
```
For the training data, since there are indeed labels available, there will be no problem. However, when assigning the None values to the `fields['label']` during the test time, I face the following error:

```
Traceback (most recent call last):
  File "/local-scratch/anaconda3/envs/TCC/bin/allennlp", line 8, in <module>
    sys.exit(run())
  File "/local-scratch/anaconda3/envs/TCC/lib/python3.7/site-packages/allennlp/run.py", line 18, in run
    main(prog="allennlp")
  File "/local-scratch/anaconda3/envs/TCC/lib/python3.7/site-packages/allennlp/commands/__init__.py", line 102, in main
    args.func(args)
  File "/local-scratch/anaconda3/envs/TCC/lib/python3.7/site-packages/allennlp/commands/train.py", line 124, in train_model_from_args
    args.cache_prefix)
  File "/local-scratch/anaconda3/envs/TCC/lib/python3.7/site-packages/allennlp/commands/train.py", line 168, in train_model_from_file
    cache_directory, cache_prefix)
  File "/local-scratch/anaconda3/envs/TCC/lib/python3.7/site-packages/allennlp/commands/train.py", line 226, in train_model
    cache_prefix)
  File "/local-scratch/anaconda3/envs/TCC/lib/python3.7/site-packages/allennlp/training/trainer_pieces.py", line 61, in from_params
    (instance for key, dataset in all_datasets.items()
  File "/local-scratch/anaconda3/envs/TCC/lib/python3.7/site-packages/allennlp/data/vocabulary.py", line 487, in from_params
    min_pretrained_embeddings=min_pretrained_embeddings)
  File "/local-scratch/anaconda3/envs/TCC/lib/python3.7/site-packages/allennlp/data/vocabulary.py", line 399, in from_instances
    instance.count_vocab_items(namespace_token_counts)
  File "/local-scratch/anaconda3/envs/TCC/lib/python3.7/site-packages/allennlp/data/instance.py", line 57, in count_vocab_items
    field.count_vocab_items(counter)
AttributeError: 'NoneType' object has no attribute 'count_vocab_items
```

I wonder if there is a way to handle this scenario on test samples, where a part of data (labels)  is missing.

**Comment by aligholami** [comment]
I think I should consider using `predictors` for my test data. Is that correct?

**Comment by brendan-ai2** [comment]
Hi @aligholami, I believe you can just leave `fields['label']` unset for the test case. The corresponding keyword argument passed to `Model.forward` will be `None` in that case. Predictors are a different issue. They can be helpful for building a demo of your system, for instance, but they're not needed if you're just evaluating some metrics.

**Comment by aligholami** [comment]
@brendan-ai2 Got it! Thanks!
