### ISSUE TITLE
Getting error while predicting POS tags of Bodo Text

### ISSUE THREAD

**Issue by sanjibnarzary** [allenai/allennlp#3584]
**Describe the bug**
I was experimenting for Bodo PoS tagging task. Everything works fine during training as well as evaluation. However, while predicting POS tags using the following commands the errors appear. I am using 3rd GPU out of the 4 available as allennlp is supporting only 1 GPU.

`allennlp predict /tmp/bodo_pos/simple_tagger/model.tar.gz input.txt`

The input.tx is as given
```
बे समाव हालुवाफोरा जेब्लाबो साग्रिद जायो ।
अखा हाब्लानो आलि थेनो थांनो नांगौ जायो ।
सोराब दारिया आबाद मावनायफोरा अखा नेनानै आबाद मावो ।
अखा अखा गैयाब्लानो नायदावनानै थानो नांगौ जायो ।
```

```
2020-01-03 22:31:32,952 - INFO - transformers.file_utils - PyTorch version 1.3.1 available.
2020-01-03 22:31:33,235 - INFO - pytorch_pretrained_bert.modeling - Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .
2020-01-03 22:31:33,665 - INFO - allennlp.models.archival - loading archive file /tmp/bodo_pos/simple_tagger/model.tar.gz
2020-01-03 22:31:33,665 - INFO - allennlp.models.archival - extracting archive file /tmp/bodo_pos/simple_tagger/model.tar.gz to temp dir /tmp/tmptm6vcboy
2020-01-03 22:31:33,836 - INFO - allennlp.data.vocabulary - Loading token dictionary from /tmp/tmptm6vcboy/vocabulary.
2020-01-03 22:31:33,888 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.models.model.Model'> from params {'encoder': {'bidirectional': True, 'dropout': 0.5, 'hidden_size': 100, 'input_size': 100, 'num_layers': 2, 'type': 'lstm'}, 'text_field_embedder': {'token_embedders': {'token_characters': {'dropout': 0.2, 'embedding': {'embedding_dim': 8}, 'encoder': {'embedding_dim': 8, 'ngram_filter_sizes': [5], 'num_filters': 50, 'type': 'cnn'}, 'type': 'character_encoding'}, 'tokens': {'embedding_dim': 50, 'type': 'embedding'}}}, 'type': 'simple_tagger'} and extras {'vocab'}
2020-01-03 22:31:33,889 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.models.simple_tagger.SimpleTagger'> from params {'encoder': {'bidirectional': True, 'dropout': 0.5, 'hidden_size': 100, 'input_size': 100, 'num_layers': 2, 'type': 'lstm'}, 'text_field_embedder': {'token_embedders': {'token_characters': {'dropout': 0.2, 'embedding': {'embedding_dim': 8}, 'encoder': {'embedding_dim': 8, 'ngram_filter_sizes': [5], 'num_filters': 50, 'type': 'cnn'}, 'type': 'character_encoding'}, 'tokens': {'embedding_dim': 50, 'type': 'embedding'}}}} and extras {'vocab'}
2020-01-03 22:31:33,889 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.modules.text_field_embedders.text_field_embedder.TextFieldEmbedder'> from params {'token_embedders': {'token_characters': {'dropout': 0.2, 'embedding': {'embedding_dim': 8}, 'encoder': {'embedding_dim': 8, 'ngram_filter_sizes': [5], 'num_filters': 50, 'type': 'cnn'}, 'type': 'character_encoding'}, 'tokens': {'embedding_dim': 50, 'type': 'embedding'}}} and extras {'vocab'}
2020-01-03 22:31:33,889 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.modules.token_embedders.token_embedder.TokenEmbedder'> from params {'dropout': 0.2, 'embedding': {'embedding_dim': 8}, 'encoder': {'embedding_dim': 8, 'ngram_filter_sizes': [5], 'num_filters': 50, 'type': 'cnn'}, 'type': 'character_encoding'} and extras {'vocab'}
2020-01-03 22:31:33,890 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.modules.seq2vec_encoders.seq2vec_encoder.Seq2VecEncoder'> from params {'embedding_dim': 8, 'ngram_filter_sizes': [5], 'num_filters': 50, 'type': 'cnn'} and extras set()
2020-01-03 22:31:33,890 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.modules.seq2vec_encoders.cnn_encoder.CnnEncoder'> from params {'embedding_dim': 8, 'ngram_filter_sizes': [5], 'num_filters': 50} and extras set()
2020-01-03 22:31:33,891 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.modules.token_embedders.token_embedder.TokenEmbedder'> from params {'embedding_dim': 50, 'type': 'embedding'} and extras {'vocab'}
2020-01-03 22:31:33,916 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.modules.seq2seq_encoders.seq2seq_encoder.Seq2SeqEncoder'> from params {'bidirectional': True, 'dropout': 0.5, 'hidden_size': 100, 'input_size': 100, 'num_layers': 2, 'type': 'lstm'} and extras {'vocab'}
2020-01-03 22:31:34,118 - INFO - allennlp.common.checks - Pytorch version: 1.3.1
2020-01-03 22:31:34,118 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.data.dataset_readers.dataset_reader.DatasetReader'> from params {'token_indexers': {'token_characters': {'type': 'characters'}, 'tokens': {'lowercase_tokens': True, 'type': 'single_id'}}, 'type': 'sequence_tagging', 'word_tag_delimiter': '/'} and extras set()
2020-01-03 22:31:34,119 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.data.dataset_readers.sequence_tagging.SequenceTaggingDatasetReader'> from params {'token_indexers': {'token_characters': {'type': 'characters'}, 'tokens': {'lowercase_tokens': True, 'type': 'single_id'}}, 'word_tag_delimiter': '/'} and extras set()
2020-01-03 22:31:34,119 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.data.token_indexers.token_indexer.TokenIndexer'> from params {'type': 'characters'} and extras set()
2020-01-03 22:31:34,119 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.data.token_indexers.token_characters_indexer.TokenCharactersIndexer'> from params {} and extras set()
/home/sn/Experiments/allennlp/allennlp/allennlp/data/token_indexers/token_characters_indexer.py:59: UserWarning: You are using the default value (0) of `min_padding_length`, which can cause some subtle bugs (more info see https://github.com/allenai/allennlp/issues/1954). Strongly recommend to set a value, usually the maximum size of the convolutional layer size when using CnnEncoder.
  UserWarning,
2020-01-03 22:31:34,120 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.data.token_indexers.token_indexer.TokenIndexer'> from params {'lowercase_tokens': True, 'type': 'single_id'} and extras set()
2020-01-03 22:31:34,120 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.data.token_indexers.single_id_token_indexer.SingleIdTokenIndexer'> from params {'lowercase_tokens': True} and extras set()
2020-01-03 22:31:34,120 - INFO - allennlp.commands.evaluate - Reading evaluation data from input.txt
0it [00:00, ?it/s]2020-01-03 22:31:34,121 - INFO - allennlp.data.dataset_readers.sequence_tagging - Reading instances from lines in file at: input.txt
Traceback (most recent call last):
  File "/home/sn/anaconda3/envs/allennlp/bin/allennlp", line 11, in <module>
    load_entry_point('allennlp', 'console_scripts', 'allennlp')()
  File "/home/sn/Experiments/allennlp/allennlp/allennlp/run.py", line 18, in run
    main(prog="allennlp")
  File "/home/sn/Experiments/allennlp/allennlp/allennlp/commands/__init__.py", line 117, in main
    args.func(args)
  File "/home/sn/Experiments/allennlp/allennlp/allennlp/commands/evaluate.py", line 167, in evaluate_from_args
    instances = dataset_reader.read(evaluation_data_path)
  File "/home/sn/Experiments/allennlp/allennlp/allennlp/data/dataset_readers/dataset_reader.py", line 145, in read
    instances = [instance for instance in Tqdm.tqdm(instances)]
  File "/home/sn/Experiments/allennlp/allennlp/allennlp/data/dataset_readers/dataset_reader.py", line 145, in <listcomp>
    instances = [instance for instance in Tqdm.tqdm(instances)]
  File "/home/sn/anaconda3/envs/allennlp/lib/python3.7/site-packages/tqdm/std.py", line 1104, in __iter__
    for obj in iterable:
File "/home/sn/Experiments/allennlp/allennlp/allennlp/data/dataset_readers/sequence_tagging.py", line 72, in _read
    tokens = [Token(token) for token, tag in tokens_and_tags]
  File "/home/sn/Experiments/allennlp/allennlp/allennlp/data/dataset_readers/sequence_tagging.py", line 72, in <listcomp>
    tokens = [Token(token) for token, tag in tokens_and_tags]
ValueError: not enough values to unpack (expected 2, got 1)
2020-01-03 22:31:34,122 - INFO - allennlp.models.archival - removing temporary unarchived model dir at /tmp/tmptm6vcboy
0it [00:00, ?it/s]
```
**To Reproduce**
Steps to reproduce the behavior
1. Go to 'clone repo'
2. Use this config simple_tagger.json
```
{
  "dataset_reader": {
    "type": "sequence_tagging",
    "word_tag_delimiter": "/",
    "token_indexers": {
      "tokens": {
        "type": "single_id",
        "lowercase_tokens": true
      },
      "token_characters": {
        "type": "characters"
      }
    }
  },
  "train_data_path": "http://get.alayaran.com/bodo_data/bodo_pos/training_small.pos.brx",
  "validation_data_path": "http://get.alayaran.com/bodo_data/bodo_pos/dev_small.pos.brx",
  "model": {
    "type": "simple_tagger",
    "text_field_embedder": {
      "token_embedders": {
        "tokens": {
            "type": "embedding",
            "embedding_dim": 50
        },
        "token_characters": {
            "type": "character_encoding",
            "embedding": {
            "embedding_dim": 8
            },
            "encoder": {
            "type": "cnn",
            "embedding_dim": 8,
            "num_filters": 50,
            "ngram_filter_sizes": [
                5
            ]
            },
            "dropout": 0.2
        }
      }
    },
    "encoder": {
      "type": "lstm",
      "input_size": 100,
      "hidden_size": 100,
      "num_layers": 2,
      "dropout": 0.5,
      "bidirectional": true
    }
  },
  "iterator": {
    "type": "basic",
    "batch_size": 32
  },
  "trainer": {
    "optimizer": "adam",
    "num_epochs": 40,
    "patience": 10,
    "cuda_device": 2
  }
}
```
3. Train and evaluate
4. use the input.txt for prediction

**Expected behavior**
The experiment is fine when used with the english dataset. However it did not work for Bodo. Bodo uses Devanagiri script.

**System (please complete the following information):**
 - OS: [e.g. OSX, Linux] Linux/Ubuntu
 - Python version: [if it's not 3.6.1 or later, that's probably your problem] 3.7
 - AllenNLP version: [e.g. v0.9.0, or "I installed from master"] master
 - PyTorch version: (if you installed it yourself)

**Additional context**
Machine: NVIDIA DGX Station with 4 Tesla GPU

**Comment by schmmd** [comment]
You need to pass a DatasetReader that can parse your particular input format.

https://github.com/allenai/allennlp/blob/master/allennlp/commands/predict.py#L100

**Comment by sanjibnarzary** [comment]
please enlighten more, as it is giving the same error after passing those parameters

**Comment by sanjibnarzary** [comment]
It's too rude that you are closing my issue without giving proper a solution. Atleast you could have open the issue so that others can view. BTW thanks, I will never use allenNLP. Unstar+Unfork. Going to huggingface.

**Comment by schmmd** [comment]
@sanjibnarzary sorry we don't mean to be rude, but we do rather aggressively manage our issues.  I missed your follow up but I also don't have enough details to give a meaningful reply.

Closing an issue doesn't make it invisible--it just flags it as being addressed by us.  Anyone can search and find a closed issue.  We're happy to help you out further, but we need more details about the exact code you're running and the exact stack trace.
