### ISSUE TITLE
Error when loading dependency-predictor: biaffine-dependency-parser-ptb-2018.08.23.tar.gz

### ISSUE THREAD

**Issue by Sxx1995** [allenai/allennlp#3641]
```
Traceback (most recent call last):
  File "/home/sxx/Desktop/allenNLPtest/test.py", line 2, in <module>
    predictor = Predictor.from_path("/home/sxx/Desktop/biaffine-dependency-parser-ud-2018.08.23.tar.gz")
  File "/home/sxx/Desktop/allennlp-master/allennlp/predictors/predictor.py", line 267, in from_path
    load_archive(archive_path, cuda_device=cuda_device),
  File "/home/sxx/Desktop/allennlp-master/allennlp/models/archival.py", line 243, in load_archive
    cuda_device=cuda_device,
  File "/home/sxx/Desktop/allennlp-master/allennlp/models/model.py", line 330, in load
    return model_class._load(config, serialization_dir, weights_file, cuda_device)
  File "/home/sxx/Desktop/allennlp-master/allennlp/models/model.py", line 267, in _load
    model = Model.from_params(vocab=vocab, params=model_params)
  File "/home/sxx/Desktop/allennlp-master/allennlp/common/from_params.py", line 435, in from_params
    **extras,
  File "/home/sxx/Desktop/allennlp-master/allennlp/common/from_params.py", line 463, in from_params
    kwargs = create_kwargs(constructor_to_inspect, cls, params, **extras)
  File "/home/sxx/Desktop/allennlp-master/allennlp/common/from_params.py", line 167, in create_kwargs
    cls.__name__, param_name, annotation, param.default, params, **extras
  File "/home/sxx/Desktop/allennlp-master/allennlp/common/from_params.py", line 265, in construct_arg
    return annotation.from_params(params=subparams, **subextras)
  File "/home/sxx/Desktop/allennlp-master/allennlp/common/from_params.py", line 435, in from_params
    **extras,
  File "/home/sxx/Desktop/allennlp-master/allennlp/common/from_params.py", line 463, in from_params
    kwargs = create_kwargs(constructor_to_inspect, cls, params, **extras)
  File "/home/sxx/Desktop/allennlp-master/allennlp/common/from_params.py", line 170, in create_kwargs
    params.assert_empty(cls.__name__)
  File "/home/sxx/Desktop/allennlp-master/allennlp/common/params.py", line 462, in assert_empty
    "Extra parameters passed to {}: {}".format(class_name, self.params)
allennlp.common.checks.ConfigurationError: "Extra parameters passed to BasicTextFieldEmbedder: {'tokens': {'embedding_dim': 100, 'sparse': True, 'trainable': True, 'type': 'embedding'}}"

Process finished with exit code 1
```

**Comment by schmmd** [comment]
I was able to reproduce the same error with the following command (copied from the demo):

```
echo '{"sentence": "If I bring 10 dollars tomorrow, can you buy me lunch?"}' | \ 
                           allennlp predict https://s3-us-west-2.amazonaws.com/allennlp/models/biaffine-dependency-parser-ptb-2018.08.23.tar.gz -
```

**Comment by matt-gardner** [comment]
This is a known issue, hopefully to be fixed today: https://github.com/allenai/allennlp-hub/issues/12. Closing this one in favor of the already-existing issue.
