### ISSUE TITLE
Running the Event2Mind config with elmo throws an exception:RuntimeError: index out of range: Tried to access index 101 out of table with 1 rows. at ../aten/src/TH/generic/THTensorEvenMoreMath.cpp:418

### ISSUE THREAD

**Issue by Alenush** [allenai/allennlp#3673]
Try to train event2mind model with elmo using this config:
```
{
  "dataset_reader": {
    "type": "event2mind",
    "source_tokenizer": {
      "type": "word",
      "word_splitter": {
        "type": "spacy"
      }
    },
    "source_token_indexers": {
      "tokens": {
        "type": "single_id",
        "lowercase_tokens": true
      },
      "elmo": {
        "type": "elmo_characters"
     }
    }
  },
  "vocabulary": {
  },
  "train_data_path": "./dataset/test_train.csv",
  "validation_data_path": "./dataset/test_val.csv",
  "model": {
    "type": "event2mind",
    "source_embedder": {
      "allow_unmatched_keys": true,
      "token_embedders": {
        "elmo":{
            "type": "elmo_token_embedder",
            "options_file": "./options.json",
            "weight_file": "./model.hdf5",
            "do_layer_norm": false,
            "dropout": 0.0
        }
      }
    },
    "embedding_dropout": 0.2,
    "encoder": {
      "type": "gru",
      "input_size": 1024,
      "hidden_size": 300,
      "num_layers": 1,
      "bidirectional": true
    },
    "max_decoding_steps": 10,
    "target_namespace": "source_tokens"
  },
  "iterator": {
    "type": "bucket",
    "padding_noise": 0.0,
    "batch_size" : 64,
    "sorting_keys": [["source", "num_tokens"]]
  },
  "trainer": {
    "num_epochs": 20,
    "patience": 10,
    "cuda_device": -1,
    "optimizer": {
      "type": "adam"
    },
    "validation_metric": "+xintent"
  }
}
```

Get RuntimeError: index out of range
Can't understand what's going wrong. 

System (please complete the following information):

OS: Mac 10.14.6
Python version: 3.7.0
AllenNLP version: 0.8.2
Torch version: torch==1.3.1

Stack trace:

```
2020-01-24 10:49:57,400 - INFO - allennlp.training.trainer - Training
  0%|          | 0/10 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/a17299693/Documents/sberbank/event2mind/venv/lib/python3.7/site-packages/allennlp/run.py", line 18, in <module>
    main(prog="allennlp")
  File "/Users/a17299693/Documents/sberbank/event2mind/venv/lib/python3.7/site-packages/allennlp/commands/__init__.py", line 72, in main
    args.func(args)
  File "/Users/a17299693/Documents/sberbank/event2mind/venv/lib/python3.7/site-packages/allennlp/commands/train.py", line 111, in train_model_from_args
    args.force)
  File "/Users/a17299693/Documents/sberbank/event2mind/venv/lib/python3.7/site-packages/allennlp/commands/train.py", line 144, in train_model_from_file
    return train_model(params, serialization_dir, file_friendly_logging, recover, force)
  File "/Users/a17299693/Documents/sberbank/event2mind/venv/lib/python3.7/site-packages/allennlp/commands/train.py", line 361, in train_model
    metrics = trainer.train()
  File "/Users/a17299693/Documents/sberbank/event2mind/venv/lib/python3.7/site-packages/allennlp/training/trainer.py", line 787, in train
    train_metrics = self._train_epoch(epoch)
  File "/Users/a17299693/Documents/sberbank/event2mind/venv/lib/python3.7/site-packages/allennlp/training/trainer.py", line 515, in _train_epoch
    loss = self.batch_loss(batch, for_training=True)
  File "/Users/a17299693/Documents/sberbank/event2mind/venv/lib/python3.7/site-packages/allennlp/training/trainer.py", line 434, in batch_loss
    output_dict = self.model(**batch)
  File "/Users/a17299693/Documents/sberbank/event2mind/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/a17299693/Documents/sberbank/event2mind/venv/lib/python3.7/site-packages/allennlp/models/event2mind.py", line 180, in forward
    output_projection_layer=state.output_projection_layer
  File "/Users/a17299693/Documents/sberbank/event2mind/venv/lib/python3.7/site-packages/allennlp/models/event2mind.py", line 237, in greedy_search
    decoder_input = target_embedder(input_choices)
  File "/Users/a17299693/Documents/sberbank/event2mind/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/a17299693/Documents/sberbank/event2mind/venv/lib/python3.7/site-packages/allennlp/modules/token_embedders/embedding.py", line 131, in forward
    sparse=self.sparse)
  File "/Users/a17299693/Documents/sberbank/event2mind/venv/lib/python3.7/site-packages/torch/nn/functional.py", line 1484, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: index out of range: Tried to access index 101 out of table with 1 rows. at ../aten/src/TH/generic/THTensorEvenMoreMath.cpp:418
```

**Comment by DeNeutoy** [comment]
As the issue description asks, please provide the entire stack trace otherwise it's unlikely we can help you

**Comment by Alenush** [comment]
> As the issue description asks, please provide the entire stack trace otherwise it's unlikely we can help you

2020-01-24 10:49:57,400 - INFO - allennlp.training.trainer - Training
  0%|          | 0/10 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/a17299693/Documents/sberbank/event2mind/venv/lib/python3.7/site-packages/allennlp/run.py", line 18, in <module>
    main(prog="allennlp")
  File "/Users/a17299693/Documents/sberbank/event2mind/venv/lib/python3.7/site-packages/allennlp/commands/__init__.py", line 72, in main
    args.func(args)
  File "/Users/a17299693/Documents/sberbank/event2mind/venv/lib/python3.7/site-packages/allennlp/commands/train.py", line 111, in train_model_from_args
    args.force)
  File "/Users/a17299693/Documents/sberbank/event2mind/venv/lib/python3.7/site-packages/allennlp/commands/train.py", line 144, in train_model_from_file
    return train_model(params, serialization_dir, file_friendly_logging, recover, force)
  File "/Users/a17299693/Documents/sberbank/event2mind/venv/lib/python3.7/site-packages/allennlp/commands/train.py", line 361, in train_model
    metrics = trainer.train()
  File "/Users/a17299693/Documents/sberbank/event2mind/venv/lib/python3.7/site-packages/allennlp/training/trainer.py", line 787, in train
    train_metrics = self._train_epoch(epoch)
  File "/Users/a17299693/Documents/sberbank/event2mind/venv/lib/python3.7/site-packages/allennlp/training/trainer.py", line 515, in _train_epoch
    loss = self.batch_loss(batch, for_training=True)
  File "/Users/a17299693/Documents/sberbank/event2mind/venv/lib/python3.7/site-packages/allennlp/training/trainer.py", line 434, in batch_loss
    output_dict = self.model(**batch)
  File "/Users/a17299693/Documents/sberbank/event2mind/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/a17299693/Documents/sberbank/event2mind/venv/lib/python3.7/site-packages/allennlp/models/event2mind.py", line 180, in forward
    output_projection_layer=state.output_projection_layer
  File "/Users/a17299693/Documents/sberbank/event2mind/venv/lib/python3.7/site-packages/allennlp/models/event2mind.py", line 237, in greedy_search
    decoder_input = target_embedder(input_choices)
  File "/Users/a17299693/Documents/sberbank/event2mind/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/a17299693/Documents/sberbank/event2mind/venv/lib/python3.7/site-packages/allennlp/modules/token_embedders/embedding.py", line 131, in forward
    sparse=self.sparse)
  File "/Users/a17299693/Documents/sberbank/event2mind/venv/lib/python3.7/site-packages/torch/nn/functional.py", line 1484, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: index out of range: Tried to access index 2 out of table with 1 rows. at ../aten/src/TH/generic/THTensorEvenMoreMath.cpp:418

Access indexes can be different but I always get this Error. 

Run it all via config with the commands provided in Demo:
```
allennlp dry-run -o '{"dataset_reader": {"dummy_instances_for_vocab_generation": true}} {"vocabulary": {"min_count": {"source_tokens": 2}}}' event2mind_elmo.json --serialization-dir vocab_output_path_elmo
allennlp train -o '{"vocabulary": {"directory_path": "vocab_output_path_elmo/vocabulary/"}}' event2mind_elmo.json --serialization-dir output_path_elmo
```
I tried with and without dry-run, still the same

**Comment by DeNeutoy** [comment]
Hi @Alenush,

ELMo cannot be used as a decoder in a sequence to sequence model such as event2mind. I would suggest you also add the `target_token_indexers` and `embedders` to your configuration, for instance an LSTM decoder should work fine.

**Comment by DeNeutoy** [comment]
Closing due to inactivity
