### ISSUE TITLE
Continue training on different data

### ISSUE THREAD

**Issue by vin-ivar** [allenai/allennlp#3761]
**System (please complete the following information):**
 - OS: Linux
 - Python version: 3.6.8
 - AllenNLP version: v0.9.0
 - PyTorch version: v1.2.0

**Question**
Is there any easy way to (sequentially) train on multiple datasets? The documentation says I shouldn't use `recover` - "For continuing training a model on new data, see `Model.from_archive`.", but `Model.from_archive` doesn't actually have any information about how I do this.

I assume this is not what AllenNLP refers to as fine-tuning, by the way - I'm fitting a dependency parser on top of a BERT encoder. Running `fine_tune_model` throws an out-of-vocab error for unknown tokens. Am I right in assuming that what I am looking for is indeed just training?

**Comment by matt-gardner** [comment]
Are you writing your own training script, or using our commands?  It looks like you're writing your own script (this detail is important for what I recommend you do).  Also, can you give the specific error that you're seeing?  If you're just using BERT, you shouldn't be computing a vocabulary anyway, so my first thought at what was going on here is probably wrong.  We need more detail to be able to help you.

**Comment by vin-ivar** [comment]
I'm writing my own training script, here's what it looks like:

```
config = Params.from_file(args.config, ext_vars={'train_path': args.train, 'val_path': args.val_train})
model = train_model(config, args.save, force=True)

finetune_config = Params.from_file(args.config, ext_vars={'train_path': args.finetune, 'val_path': args.val_finetune})
model = fine_tune_model(model, finetune_config, args.save + '_ft')
```

Here's the full dump from the error, it looks it's trying to look up the default unknown identifier in BERT's vocab:

```
Traceback (most recent call last):
  File "/Users/vinit/dev/bert-lang-distance/dep-parse/runner.py", line 60, in <module>
    main()
  File "/Users/vinit/dev/bert-lang-distance/dep-parse/runner.py", line 35, in main
    model = fine_tune_model(model, finetune_config, os.path.join(args.save, 'ft'))
  File "/Users/vinit/.miniconda3/miniconda3/envs/nlp/lib/python3.6/site-packages/allennlp/commands/fine_tune.py", line 318, in fine_tune_model
    metrics = trainer.train()
  File "/Users/vinit/.miniconda3/miniconda3/envs/nlp/lib/python3.6/site-packages/allennlp/training/trainer.py", line 478, in train
    train_metrics = self._train_epoch(epoch)
  File "/Users/vinit/.miniconda3/miniconda3/envs/nlp/lib/python3.6/site-packages/allennlp/training/trainer.py", line 313, in _train_epoch
    for batch_group in train_generator_tqdm:
  File "/Users/vinit/.miniconda3/miniconda3/envs/nlp/lib/python3.6/site-packages/tqdm/_tqdm.py", line 1022, in __iter__
    for obj in iterable:
  File "/Users/vinit/.miniconda3/miniconda3/envs/nlp/lib/python3.6/site-packages/allennlp/common/util.py", line 104, in <lambda>
    return iter(lambda: list(islice(iterator, 0, group_size)), [])
  File "/Users/vinit/.miniconda3/miniconda3/envs/nlp/lib/python3.6/site-packages/allennlp/data/iterators/data_iterator.py", line 143, in __call__
    for batch in batches:
  File "/Users/vinit/.miniconda3/miniconda3/envs/nlp/lib/python3.6/site-packages/allennlp/data/iterators/bucket_iterator.py", line 124, in _create_batches
    self._padding_noise)
  File "/Users/vinit/.miniconda3/miniconda3/envs/nlp/lib/python3.6/site-packages/allennlp/data/iterators/bucket_iterator.py", line 30, in sort_by_padding
    instance.index_fields(vocab)
  File "/Users/vinit/.miniconda3/miniconda3/envs/nlp/lib/python3.6/site-packages/allennlp/data/instance.py", line 72, in index_fields
    field.index(vocab)
  File "/Users/vinit/.miniconda3/miniconda3/envs/nlp/lib/python3.6/site-packages/allennlp/data/fields/sequence_label_field.py", line 100, in index
    for label in self.labels]
  File "/Users/vinit/.miniconda3/miniconda3/envs/nlp/lib/python3.6/site-packages/allennlp/data/fields/sequence_label_field.py", line 100, in <listcomp>
    for label in self.labels]
  File "/Users/vinit/.miniconda3/miniconda3/envs/nlp/lib/python3.6/site-packages/allennlp/data/vocabulary.py", line 637, in get_token_index
    return self._token_to_index[namespace][self._oov_token]
KeyError: '@@UNKNOWN@@'
```

**Comment by matt-gardner** [comment]
Do you have labels in your new test data that don't show up in your original data?  It looks like that's what's causing the problem.  There are some hacky ways to handle this, which I can tell you about if you need it once you confirm that that's the problem.  It'd help, though, if you could give me an intuitive description of how you want the model to handle the new labels that it sees during fine tuning.

**Comment by vin-ivar** [comment]
Hmm that's actually not entirely implausible, I'd been running this on a subset of the full data so it's possible there's labels in val that don't show up in training. 

To be clear, when you say new test data/original data, you mean the validation and training portions in the fine-tuning step, right?

**Comment by vin-ivar** [comment]
Okay, yeah, that makes sense - setting `extend_vocab` throws a size mismatch error, so this is probably what's happening.

Is there an easy way to build my label vocab on both datasets?

**Comment by matt-gardner** [comment]
You have two reasonable options.  I think the first is probably better, but either should work:

1. Override this method in your model: https://github.com/allenai/allennlp/blob/49e8be84645bc61ec97ee990f70687630d61adb5/allennlp/models/model.py#L341-L366

to look something like this:
```python
def extend_embedder_vocab(self, ...):
    super().extend_embedder_vocab()
    self.extend_linear_layer()
```
and `extend_linear_layer` does roughly what's done here, but for your top classification layer: https://github.com/allenai/allennlp/blob/49e8be84645bc61ec97ee990f70687630d61adb5/allennlp/modules/token_embedders/embedding.py#L255-L269

This would be the cleanest, and most extensible, thing to do.  And if you pull that `extend_linear_layer` out into a utility function, we'd love to have it as a contribution upstream, so that others who run into this can have an easier solution, also.

2. Use `dry-run` on the full data to compute a vocabulary, and use `from_files` as your vocabulary type.  Well, actually, in 0.9, I believe you use the `directory_path` parameter instead of `from_files` type, but the idea is the same.  If you want to do this option, and you have trouble figuring it out, let us know.  This is definitely faster, if you just want to solve this problem and move on, though it's much less flexible in the future.  Just depends on what you see yourself doing going forward.

**Comment by vin-ivar** [comment]
Okay, solution #1 looks good to me - my final layer's bilinear, but it's the same principle. 

I'll pull it out into a util function in a bit - where should something like this go, and how generic should I make it? I'm thinking of having the arguments be a) the layer to extend and b) the new vocab size.

**Comment by matt-gardner** [comment]
I agree with those arguments; you probably have to make some assumptions about the shape of the weights, so it can't handle any arbitrary layer. I would say make it as general as is reasonable, but I'm not sure how general that is without seeing code.

As for where it goes, `nn.util` is currently our catch-all place for things like this, so probably there.
