### ISSUE TITLE
gan_callback_trainer_test does not seem to be working.

### ISSUE THREAD

**Issue by c4n** [allenai/allennlp#3810]
**Describe the bug**
KeyError: 'train_data'
During handling of the above exception, another exception occurred:
allennlp.common.checks.ConfigurationError: key "train_data" is required at location ""
**To Reproduce**
Steps to reproduce the behavior
`python -m allennlp.tests.training.gan_callback_trainer_test`

**Expected behavior**
```
Traceback (most recent call last):
  File "/home/datamind/allennlp/allennlp/common/params.py", line 243, in pop
    value = self.params.pop(key)
KeyError: 'train_data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/datamind/anaconda3/envs/can_env/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/datamind/anaconda3/envs/can_env/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/datamind/allennlp/allennlp/tests/training/gan_callback_trainer_test.py", line 343, in <module>
    trainer = TrainerBase.from_params(params=params, serialization_dir=serialization_dir)
  File "/home/datamind/allennlp/allennlp/common/from_params.py", line 555, in from_params
    **extras,
  File "/home/datamind/allennlp/allennlp/common/from_params.py", line 583, in from_params
    kwargs = create_kwargs(constructor_to_inspect, cls, params, **extras)
  File "/home/datamind/allennlp/allennlp/common/from_params.py", line 188, in create_kwargs
    cls.__name__, param_name, annotation, param.default, params, **extras
  File "/home/datamind/allennlp/allennlp/common/from_params.py", line 287, in pop_and_construct_arg
    popped_params = params.pop(name, default) if default != _NO_DEFAULT else params.pop(name)
  File "/home/datamind/allennlp/allennlp/common/params.py", line 245, in pop
    raise ConfigurationError(f'key "{key}" is required at location "{self.history}"')
allennlp.common.checks.ConfigurationError: key "train_data" is required at location ""
(can_env) datamind@cuxhamo:~/allennlp$ python -m allennlp.tests.training.gan_callback_trainer_test /tmp
Traceback (most recent call last):
  File "/home/datamind/allennlp/allennlp/common/params.py", line 243, in pop
    value = self.params.pop(key)
KeyError: 'train_data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/datamind/anaconda3/envs/can_env/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/datamind/anaconda3/envs/can_env/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/datamind/allennlp/allennlp/tests/training/gan_callback_trainer_test.py", line 343, in <module>
    trainer = TrainerBase.from_params(params=params, serialization_dir=serialization_dir)
  File "/home/datamind/allennlp/allennlp/common/from_params.py", line 555, in from_params
    **extras,
  File "/home/datamind/allennlp/allennlp/common/from_params.py", line 583, in from_params
    kwargs = create_kwargs(constructor_to_inspect, cls, params, **extras)
  File "/home/datamind/allennlp/allennlp/common/from_params.py", line 188, in create_kwargs
    cls.__name__, param_name, annotation, param.default, params, **extras
  File "/home/datamind/allennlp/allennlp/common/from_params.py", line 287, in pop_and_construct_arg
    popped_params = params.pop(name, default) if default != _NO_DEFAULT else params.pop(name)
  File "/home/datamind/allennlp/allennlp/common/params.py", line 245, in pop
    raise ConfigurationError(f'key "{key}" is required at location "{self.history}"')
allennlp.common.checks.ConfigurationError: key "train_data" is required at location ""
(can_env) datamind@cuxhamo:~/allennlp$ python -m allennlp.tests.training.gan_callback_trainer_test
Traceback (most recent call last):
  File "/home/datamind/allennlp/allennlp/common/params.py", line 243, in pop
    value = self.params.pop(key)
KeyError: 'train_data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/datamind/anaconda3/envs/can_env/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/datamind/anaconda3/envs/can_env/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/datamind/allennlp/allennlp/tests/training/gan_callback_trainer_test.py", line 343, in <module>
    trainer = TrainerBase.from_params(params=params, serialization_dir=serialization_dir)
  File "/home/datamind/allennlp/allennlp/common/from_params.py", line 555, in from_params
    **extras,
  File "/home/datamind/allennlp/allennlp/common/from_params.py", line 583, in from_params
    kwargs = create_kwargs(constructor_to_inspect, cls, params, **extras)
  File "/home/datamind/allennlp/allennlp/common/from_params.py", line 188, in create_kwargs
    cls.__name__, param_name, annotation, param.default, params, **extras
  File "/home/datamind/allennlp/allennlp/common/from_params.py", line 287, in pop_and_construct_arg
    popped_params = params.pop(name, default) if default != _NO_DEFAULT else params.pop(name)
  File "/home/datamind/allennlp/allennlp/common/params.py", line 245, in pop
    raise ConfigurationError(f'key "{key}" is required at location "{self.history}"')
allennlp.common.checks.ConfigurationError: key "train_data" is required at location ""
```

**System (please complete the following information):**
 - OS: ubuntu 16.04
 - Python version: 3.7.3
 - AllenNLP version:  installed from master

**Comment by DeNeutoy** [comment]
We fixed this by deleting it :)
