### ISSUE TITLE
A ListField of text LabelField fails when padded

### ISSUE THREAD

**Issue by nafitzgerald** [allenai/allennlp#382]
The following code results in an error:

```
>>> from allennlp.data.fields import LabelField, ListField
>>> text_field = ListField([LabelField("bleh")])
>>> text_field.as_array({'num_fields':2})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nfitz/git_repos/allennlp/allennlp/data/fields/list_field.py", line 61, in as_array
    self.field_list[0].empty_field)
  File "/home/nfitz/git_repos/allennlp/allennlp/common/util.py", line 92, in pad_sequence_to_length
    padded_sequence.append(default_value())
  File "/home/nfitz/git_repos/allennlp/allennlp/data/fields/label_field.py", line 81, in empty_field
    return LabelField(0, self._label_namespace)
  File "/home/nfitz/git_repos/allennlp/allennlp/data/fields/label_field.py", line 59, in __init__
    "Found label: {} with type: {}.".format(label, type(label)))
allennlp.common.checks.ConfigurationError: "LabelFields must be passed a string label if skip_indexing=False. Found label: 0 with type: <class 'int'>."
```

**Comment by matt-gardner** [comment]
Yeah, good point.  Kenton's change to `LabelField` in his coref PR fixes part of this - it changes the value to -1 if it's padded.  But you also need to add `skip_indexing=True`.  Care to add a simple test for this, and submit a PR?

**Comment by nafitzgerald** [comment]
Will do.
