### ISSUE TITLE
Better error message for old config files

### ISSUE THREAD

**Issue by ianupright** [allenai/allennlp#3849]
I'm using a very recent git version:

a066c15e83c261e9e677bde3ada85ff35a72a94c

I'm having trouble with params on several models.  I tried the ner_elmo and coref models and get the following error.  However, some models like the non-elmo ner model work fine.  Params is a list object instead of a Params object, and lists obviously do not respond to pop(name, default).
I'm on Python version 3.7.6 on Ubuntu.

2020-02-25 15:04:02,928 - INFO - allennlp.common.params - random_seed = 13370
2020-02-25 15:04:02,929 - INFO - allennlp.common.params - numpy_seed = 1337
2020-02-25 15:04:02,929 - INFO - allennlp.common.params - pytorch_seed = 133
2020-02-25 15:04:02,958 - INFO - allennlp.common.checks - Pytorch version: 1.4.0
2020-02-25 15:04:02,959 - INFO - allennlp.common.params - type = default
2020-02-25 15:04:02,961 - INFO - allennlp.common.params - dataset_reader.type = conll2003
2020-02-25 15:04:02,962 - INFO - allennlp.common.params - dataset_reader.lazy = False
2020-02-25 15:04:02,962 - INFO - allennlp.common.params - dataset_reader.cache_directory = None
2020-02-25 15:04:02,962 - INFO - allennlp.common.params - dataset_reader.max_instances = None
2020-02-25 15:04:02,963 - INFO - allennlp.common.params - dataset_reader.token_indexers.elmo.type = elmo_characters
2020-02-25 15:04:02,964 - INFO - allennlp.common.params - dataset_reader.token_indexers.elmo.namespace = elmo_characters
2020-02-25 15:04:02,964 - INFO - allennlp.common.params - dataset_reader.token_indexers.elmo.tokens_to_add = None
2020-02-25 15:04:02,964 - INFO - allennlp.common.params - dataset_reader.token_indexers.elmo.token_min_padding_length = 0
2020-02-25 15:04:02,965 - INFO - allennlp.common.params - dataset_reader.token_indexers.token_characters.type = characters
2020-02-25 15:04:02,965 - INFO - allennlp.common.params - dataset_reader.token_indexers.token_characters.namespace = token_characters
2020-02-25 15:04:02,966 - INFO - allennlp.common.params - dataset_reader.token_indexers.token_characters.character_tokenizer = <allennlp.data.tokenizers.character_tokenizer.CharacterTokenizer object at 0x7fcc3f2e7f90>
2020-02-25 15:04:02,966 - INFO - allennlp.common.params - dataset_reader.token_indexers.token_characters.start_tokens = None
2020-02-25 15:04:02,966 - INFO - allennlp.common.params - dataset_reader.token_indexers.token_characters.end_tokens = None
2020-02-25 15:04:02,966 - INFO - allennlp.common.params - dataset_reader.token_indexers.token_characters.min_padding_length = 3
2020-02-25 15:04:02,967 - INFO - allennlp.common.params - dataset_reader.token_indexers.token_characters.token_min_padding_length = 0
2020-02-25 15:04:02,967 - INFO - allennlp.common.params - dataset_reader.token_indexers.tokens.type = single_id
2020-02-25 15:04:02,968 - INFO - allennlp.common.params - dataset_reader.token_indexers.tokens.namespace = tokens
2020-02-25 15:04:02,968 - INFO - allennlp.common.params - dataset_reader.token_indexers.tokens.lowercase_tokens = True
2020-02-25 15:04:02,968 - INFO - allennlp.common.params - dataset_reader.token_indexers.tokens.start_tokens = None
2020-02-25 15:04:02,969 - INFO - allennlp.common.params - dataset_reader.token_indexers.tokens.end_tokens = None
2020-02-25 15:04:02,969 - INFO - allennlp.common.params - dataset_reader.token_indexers.tokens.feature_name = text
2020-02-25 15:04:02,969 - INFO - allennlp.common.params - dataset_reader.token_indexers.tokens.default_value = THIS IS A REALLY UNLIKELY VALUE THAT HAS TO BE A STRING
2020-02-25 15:04:02,969 - INFO - allennlp.common.params - dataset_reader.token_indexers.tokens.token_min_padding_length = 0
2020-02-25 15:04:02,970 - INFO - allennlp.common.params - dataset_reader.tag_label = ner
2020-02-25 15:04:02,970 - INFO - allennlp.common.params - dataset_reader.feature_labels = ()
2020-02-25 15:04:02,970 - INFO - allennlp.common.params - dataset_reader.coding_scheme = BIOUL
2020-02-25 15:04:02,971 - INFO - allennlp.common.params - dataset_reader.label_namespace = labels
2020-02-25 15:04:02,971 - INFO - allennlp.common.params - train_data_path = /usr/local/ner/train.txt
2020-02-25 15:04:02,972 - INFO - allennlp.common.params - iterator.type = basic
2020-02-25 15:04:02,973 - INFO - allennlp.common.params - iterator.batch_size = 64
2020-02-25 15:04:02,973 - INFO - allennlp.common.params - iterator.instances_per_epoch = None
2020-02-25 15:04:02,974 - INFO - allennlp.common.params - iterator.max_instances_in_memory = None
2020-02-25 15:04:02,974 - INFO - allennlp.common.params - iterator.cache_instances = False
2020-02-25 15:04:02,974 - INFO - allennlp.common.params - iterator.track_epoch = False
2020-02-25 15:04:02,974 - INFO - allennlp.common.params - iterator.maximum_samples_per_batch = None
2020-02-25 15:04:02,975 - INFO - allennlp.common.params - vocabulary = None
2020-02-25 15:04:02,975 - INFO - allennlp.common.params - datasets_for_vocab_creation = None
2020-02-25 15:04:02,975 - INFO - allennlp.common.params - validation_dataset_reader = None
2020-02-25 15:04:02,976 - INFO - allennlp.common.params - validation_data_path = /usr/local/ner/dev.txt
2020-02-25 15:04:02,976 - INFO - allennlp.common.params - validation_iterator = None
2020-02-25 15:04:02,976 - INFO - allennlp.common.params - test_data_path = None
2020-02-25 15:04:02,976 - INFO - allennlp.common.params - evaluate_on_test = False
2020-02-25 15:04:02,977 - INFO - allennlp.training.util - Reading training data from /usr/local/ner/train.txt
2020-02-25 15:04:02,978 - INFO - allennlp.data.dataset_readers.conll2003 - Reading instances from lines in file at: /usr/local/ner/train.txt
14041it [00:06, 2152.04it/s]
2020-02-25 15:04:09,502 - INFO - allennlp.training.util - Reading validation data from /usr/local/ner/dev.txt
2020-02-25 15:04:09,503 - INFO - allennlp.data.dataset_readers.conll2003 - Reading instances from lines in file at: /usr/local/ner/dev.txt
3250it [00:01, 2198.86it/s]
2020-02-25 15:04:10,981 - INFO - allennlp.data.vocabulary - Fitting token dictionary from dataset.
17291it [00:10, 1694.11it/s]
2020-02-25 15:04:21,343 - INFO - allennlp.common.params - model.type = crf_tagger
Traceback (most recent call last):
  File "/usr/local/share/development/pycharm/plugins/python-ce/helpers/pydev/pydevd.py", line 1434, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/usr/local/share/development/pycharm-community-2019.3.1/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/usr/local/share/development/allennlp/allennlp/__main__.py", line 22, in <module>
    run()
  File "/usr/local/share/development/allennlp/allennlp/__main__.py", line 18, in run
    main(prog="allennlp")
  File "/usr/local/share/development/allennlp/allennlp/commands/__init__.py", line 93, in main
    args.func(args)
  File "/usr/local/share/development/allennlp/allennlp/commands/train.py", line 144, in train_model_from_args
    dry_run=args.dry_run,
  File "/usr/local/share/development/allennlp/allennlp/commands/train.py", line 203, in train_model_from_file
    dry_run=dry_run,
  File "/usr/local/share/development/allennlp/allennlp/commands/train.py", line 266, in train_model
    dry_run=dry_run,
  File "/usr/local/share/development/allennlp/allennlp/commands/train.py", line 450, in _train_worker
    batch_weight_key=batch_weight_key,
  File "/usr/local/share/development/allennlp/allennlp/common/from_params.py", line 582, in from_params
    **extras,
  File "/usr/local/share/development/allennlp/allennlp/common/from_params.py", line 612, in from_params
    return constructor_to_call(**kwargs)  # type: ignore
  File "/usr/local/share/development/allennlp/allennlp/commands/train.py", line 652, in from_partial_objects
    model_ = model.construct(vocab=vocabulary_)
  File "/usr/local/share/development/allennlp/allennlp/common/lazy.py", line 29, in construct
    return self._constructor(**kwargs)
  File "/usr/local/share/development/allennlp/allennlp/common/from_params.py", line 467, in constructor
    return value_cls.from_params(params=deepcopy(popped_params), **constructor_extras)
  File "/usr/local/share/development/allennlp/allennlp/common/from_params.py", line 582, in from_params
    **extras,
  File "/usr/local/share/development/allennlp/allennlp/common/from_params.py", line 610, in from_params
    kwargs = create_kwargs(constructor_to_inspect, cls, params, **extras)
  File "/usr/local/share/development/allennlp/allennlp/common/from_params.py", line 201, in create_kwargs
    cls.__name__, param_name, annotation, param.default, params, **extras
  File "/usr/local/share/development/allennlp/allennlp/common/from_params.py", line 307, in pop_and_construct_arg
    return construct_arg(class_name, name, popped_params, annotation, default, **extras)
  File "/usr/local/share/development/allennlp/allennlp/common/from_params.py", line 342, in construct_arg
    return annotation.from_params(params=popped_params, **subextras)
  File "/usr/local/share/development/allennlp/allennlp/common/from_params.py", line 610, in from_params
    kwargs = create_kwargs(constructor_to_inspect, cls, params, **extras)
  File "/usr/local/share/development/allennlp/allennlp/common/from_params.py", line 201, in create_kwargs
    cls.__name__, param_name, annotation, param.default, params, **extras
  File "/usr/local/share/development/allennlp/allennlp/common/from_params.py", line 300, in pop_and_construct_arg
    popped_params = params.pop(name, default) if default != _NO_DEFAULT else params.pop(name)
TypeError: pop() takes at most 1 argument (2 given)

**Comment by DeNeutoy** [comment]
Hi @ianupright,

This is from the changes to the `regularizer` config parameter:

Regularization now needs another key in a config file. Instead of specifying regularization as 
`"regularizer": [[regex1, regularizer_params], [regex2, regularizer_params]]`

, it now must be specified as 

`"regularizer": {"regexes": [[regex1, regularizer_params], [regex2, regularizer_params]]}`.

I ran into this the other day and it's a pretty terrible error, we will fix this before the final 1.0 release. Thanks for raising!

**Comment by ianupright** [comment]
Thanks..  In coref there is:

    "initializer": [
        [".*linear_layers.*weight", {"type": "xavier_normal"}],
        [".*scorer._module.weight", {"type": "xavier_normal"}],
        ["_distance_embedding.weight", {"type": "xavier_normal"}],
        ["_span_width_embedding.weight", {"type": "xavier_normal"}],
        ["_context_layer._module.weight_ih.*", {"type": "xavier_normal"}],
        ["_context_layer._module.weight_hh.*", {"type": "orthogonal"}]
    ],

I tried adding extra keys there but it comes back with:

allennlp.common.checks.ConfigurationError: Extra parameters passed to InitializerApplicator: {'.*linear_layers.*weight': {'type': 'xavier_normal'}, '.*scorer._module.weight': {'type': 'xavier_normal'}, '_context_layer._module.weight_hh.*': {'type': 'orthogonal'}, '_context_layer._module.weight_ih.*': {'type': 'xavier_normal'}, '_distance_embedding.weight': {'type': 'xavier_normal'}, '_span_width_embedding.weight': {'type': 'xavier_normal'}}

Any ideas?

Thanks

**Comment by ianupright** [comment]
Also, I'm not sure if this parameter issue is related, but specifying:
"num_serialized_models_to_keep" in trainer also seems to cause an error.

**Comment by matt-gardner** [comment]
See the config file changes mentioned here: https://github.com/allenai/allennlp/releases/tag/v1.0-prerelease.  All of these changes are listed there.  Your more recent initialization error is because you're not specifying the parameters right.  Check the format in the release notes; you've got a dictionary in there that should be a list.

**Comment by ianupright** [comment]
Thanks very much @matt-gardner, didn't know about those notes!
