### ISSUE TITLE
Error while evaluation of trained model on test data using allennlp evaluate

### ISSUE THREAD

**Issue by kaushikepi** [allenai/allennlp#3927]
```
!allennlp evaluate  --output-file /content/drive/My\ Drive/allennlp_tutorial/output \
                    --weights-file /content/drive/My\ Drive/allennlp_tutorial/ner_elmo/best.th  \
                    --cuda-device 0 \
                    --overrides /content/drive/My\ Drive/allennlp_tutorial/configs/train_ner_lstm.jsonnet \
                   /content/drive/My\ Drive/allennlp_tutorial/ner_elmo/model.tar.gz \
                   /content/drive/My\ Drive/allennlp_tutorial/data/ner_data_test.txt
```

```
2020-03-09 12:46:13,729 - INFO - transformers.file_utils - PyTorch version 1.4.0 available.
2020-03-09 12:46:16,390 - INFO - allennlp.models.archival - loading archive file /content/drive/My Drive/allennlp_tutorial/ner_elmo/model.tar.gz
2020-03-09 12:46:16,391 - INFO - allennlp.models.archival - extracting archive file /content/drive/My Drive/allennlp_tutorial/ner_elmo/model.tar.gz to temp dir /tmp/tmpns9rmzy2
Traceback (most recent call last):
  File "/usr/local/bin/allennlp", line 11, in <module>
    load_entry_point('allennlp', 'console_scripts', 'allennlp')()
  File "/content/allennlp/allennlp/__main__.py", line 18, in run
    main(prog="allennlp")
  File "/content/allennlp/allennlp/commands/__init__.py", line 93, in main
    args.func(args)
  File "/content/allennlp/allennlp/commands/evaluate.py", line 146, in evaluate_from_args
    archive = load_archive(args.archive_file, args.cuda_device, args.overrides, args.weights_file)
  File "/content/allennlp/allennlp/models/archival.py", line 171, in load_archive
    config = Params.from_file(os.path.join(serialization_dir, CONFIG_NAME), overrides)
  File "/content/allennlp/allennlp/common/params.py", line 480, in from_file
    overrides_dict = parse_overrides(params_overrides)
  File "/content/allennlp/allennlp/common/params.py", line 181, in parse_overrides
    return unflatten(json.loads(evaluate_snippet("", serialized_overrides, ext_vars=ext_vars)))
RuntimeError: STATIC ERROR: 1:1: not a unary operator: /

2020-03-09 12:46:20,366 - INFO - allennlp.models.archival - removing temporary unarchived model dir at /tmp/tmpns9rmzy2
```

**Comment by kernelmachine** [comment]
I sometimes get that error when I have malformed comments in my config file. According to JSONNET specification,

"Comments are either single line comments, beginning with a # or a //, or block comments beginning with /* and terminating at the first */ encountered within the comment."

Do your comments in this file follow the specifications?

**Comment by schmmd** [comment]
@kaushikepi let us know if you have additional questions!
