### ISSUE TITLE
training stopped due to input must be tensor error

### ISSUE THREAD

**Issue by manoffocus** [allenai/allennlp#3955]
2020-03-17 12:38:24,538 - INFO - allennlp.training.trainer - Peak CPU memory usage MB: 0.0
2020-03-17 12:38:24,540 - INFO - allennlp.training.trainer - Training
  0%|                                                                                                                                                                                      | 0/10 [00:00<?, ?it/s]tensor(8.3174, grad_fn=<AddBackward0>)
...............................
start_acc: 0.0000, end_acc: 0.0000, span_acc: 0.0000, em: 0.0000, f1: 0.1624, loss: 8.3174 ||:  10%|#######9                                                                       | 1/10 [00:19<02:55, 19.50s/it]tensor(3.8143, grad_fn=<AddBackward0>)
...............................
start_acc: 0.1125, end_acc: 0.2250, span_acc: 0.0625, em: 0.0625, f1: 0.2661, loss: 6.0659 ||:  20%|###############8                                                               | 2/10 [00:24<02:01, 15.13s/it]0.0
...............................
Traceback (most recent call last):
  File "c:\users\user\anaconda3\envs\allennlp\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\user\anaconda3\envs\allennlp\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\anaconda3\envs\allennlp\Scripts\allennlp.exe\__main__.py", line 7, in <module>
  File "c:\users\user\anaconda3\envs\allennlp\lib\site-packages\allennlp\run.py", line 18, in run
    main(prog="allennlp")
  File "c:\users\user\anaconda3\envs\allennlp\lib\site-packages\allennlp\commands\__init__.py", line 102, in main
    args.func(args)
  File "c:\users\user\anaconda3\envs\allennlp\lib\site-packages\allennlp\commands\train.py", line 124, in train_model_from_args
    args.cache_prefix)
  File "c:\users\user\anaconda3\envs\allennlp\lib\site-packages\allennlp\commands\train.py", line 168, in train_model_from_file
    cache_directory, cache_prefix)
  File "c:\users\user\anaconda3\envs\allennlp\lib\site-packages\allennlp\commands\train.py", line 252, in train_model
    metrics = trainer.train()
  File "c:\users\user\anaconda3\envs\allennlp\lib\site-packages\allennlp\training\trainer.py", line 482, in train
    train_metrics = self._train_epoch(epoch)
  File "c:\users\user\anaconda3\envs\allennlp\lib\site-packages\allennlp\training\trainer.py", line 327, in _train_epoch
    if torch.isnan(loss):
**TypeError: isnan(): argument 'input' (position 1) must be Tensor, not float**
start_acc: 0.1125, end_acc: 0.2250, span_acc: 0.0625, em: 0.0625, f1: 0.2661, loss: 6.0659 ||:  20%|###############8                                                               | 2/10 [00:50<03:21, 25.17s/it]

please do help me out from this error
Here is the code it is getting error

loss = self.batch_loss(batch_group, for_training=True)
            print(loss)
            print("...............................")
            if torch.isnan(loss):
                   raise ValueError("nan loss encountered")

**Comment by matt-gardner** [comment]
If you look at your output, you can see that for the first two batches, the `print(loss)` line prints a tensor, then on the third batch the loss is printed out as `0.0`.  Why is `trainer.batch_loss()` returning 0 there?  My guess is this is some problem in your model code, not something that I can diagnose on my end.

**Comment by matt-gardner** [comment]
Closing due to inactivity, and because I may have already answered the issue.  Feel free to keep commenting or open a new issue if you still have questions.
