### ISSUE TITLE
Error when training allennlp for NER task using ELMO

### ISSUE THREAD

**Issue by saharghannay** [allenai/allennlp#3988]
Hi I get this error when trying to train allennlp for NER task using ELMO. 
do you have an idea please how can I solve this problem. 

```
2020-03-26 11:30:41,416 - INFO - allennlp.nn.initializers -    text_field_embedder.token_embedder_token_characters._encoder._module.conv_layer_0.weight
2020-03-26 11:30:41,416 - INFO - allennlp.nn.initializers -    text_field_embedder.token_embedder_tokens.weight
2020-03-26 11:30:41,418 - WARNING - root - vocabulary serialization directory /vol/usersiles1/ghannay/HIPE2/checkpoint/vocabulary is not empty
Traceback (most recent call last):
  File "miniconda2/envs/condpy36/lib/python3.6/site-packages/allennlp/common/params.py", line 258, in pop
    value = self.params.pop(key)
KeyError: 'iterator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "miniconda2/envs/condpy36/bin/allennlp", line 10, in <module>
    sys.exit(run())
  File "miniconda2/envs/condpy36/lib/python3.6/site-packages/allennlp/run.py", line 18, in run
    main(prog="allennlp")
  File "miniconda2/envs/condpy36/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 102, in main
    args.func(args)
  File "miniconda2/envs/condpy36/lib/python3.6/site-packages/allennlp/commands/train.py", line 124, in train_model_from_args
    args.cache_prefix)
  File "miniconda2/envs/condpy36/lib/python3.6/site-packages/allennlp/commands/train.py", line 168, in train_model_from_file
    cache_directory, cache_prefix)
  File "miniconda2/envs/condpy36/lib/python3.6/site-packages/allennlp/commands/train.py", line 226, in train_model
    cache_prefix)
  File "miniconda2/envs/condpy36/lib/python3.6/site-packages/allennlp/training/trainer_pieces.py", line 74, in from_params
    iterator = DataIterator.from_params(params.pop("iterator"))
  File "miniconda2/envs/condpy36/lib/python3.6/site-packages/allennlp/common/params.py", line 260, in pop
    raise ConfigurationError("key \"{}\" is required at location \"{}\"".format(key, self.history))
allennlp.common.checks.ConfigurationError: 'key "iterator" is required at location ""'
```

**Comment by schmmd** [comment]
@saharghannay we can't help you unless we know what version of AllenNLP you are using, the exact configuration you are using, and the command you are running.

**Comment by saharghannay** [comment]
Hi, I am using this version 0.9.0, installed with pip.

**Comment by schmmd** [comment]
@saharghannay what configuration are you using and what command are you running?

**Comment by saharghannay** [comment]
I am using this command " allennlp train ner_elmo.jsonnet -s checkpoint"
and this config file : https://github.com/allenai/allennlp/blob/master/training_config/ner_elmo.jsonnet

**Comment by schmmd** [comment]
We've made significant changes between 0.9.0 and master.  I would guess you're hitting an incompatibility between the two versions.  We're going to have a release candidate out int he next couple of weeks to reduce this occurrence.

In the meantime, I recommend using a training configuration from the same version of AllenNLP that you are using: https://github.com/allenai/allennlp/tree/v0.9.0/training_config.

**Comment by saharghannay** [comment]
Ok thank you,
