### ISSUE TITLE
RuntimeError: index out of range: Tried to access index 32730 out of table with 28995 rows. at /tmp/pip-req-build-ufslq_a9/aten/src/TH/generic/THTensorEvenMoreMath.cpp:418 

### ISSUE THREAD

**Issue by manelAffi** [allenai/allennlp#4005]
**System (please complete the following information):**
 OS: Linux
Python version: 3.7.6
AllenNLP version: 0.9.0

Hi,
I'm trying to train crf-tagger model on ontonotes dataset for named entity recognition task. I'm using ELmo and Bert as word embedding.
```
{
"dataset_reader": {
"type": "ontonotes_ner",
"coding_scheme": "BIOUL",
"token_indexers": {
"tokens": {
"type": "single_id",
"lowercase_tokens": true
},
"token_characters": {
"type": "characters",
"min_padding_length": 3
},
"elmo": {
"type": "elmo_characters"
},
}
},

"train_data_path": "XXXXXX",
"validation_data_path": "XXXXXX",

"model": {
"type": "crf_tagger",
"label_encoding": "BIOUL",
"dropout": 0.5,
"include_start_end_transitions": false,
"text_field_embedder": {
 "allow_unmatched_keys": true,
  "tokens": {
                "type": "bert-pretrained",
                "pretrained_model": "bert-base-cased"
            },
    "elmo":{
        "type": "elmo_token_embedder",
    "options_file": "https://allennlp.s3.amazonaws.com/models/elmo/2x4096_512_2048cnn_2xhighway/elmo_2x4096_512_2048cnn_2xhighway_options.json",
    "weight_file": "https://allennlp.s3.amazonaws.com/models/elmo/2x4096_512_2048cnn_2xhighway/elmo_2x4096_512_2048cnn_2xhighway_weights.hdf5",
        "do_layer_norm": false,
        "dropout": 0.0
    }
 
},
.....
}
```
But a I am getting this error:
`**RuntimeError: index out of range: Tried to access index 32730 out of table with 28995 rows. at /tmp/pip-req-build-ufslq_a9/aten/src/TH/generic/THTensorEvenMoreMath.cpp:418**`

**Here is the full stack trace:**

```
Traceback (most recent call last): File "/home/mrim/affim/anaconda3/envs/allennlp/bin/allennlp", line 8, in <module> sys.exit(run()) File "/home/mrim/affim/anaconda3/envs/allennlp/lib/python3.7/site-packages/allennlp/run.py", line 18, in run main(prog="allennlp") File "/home/mrim/affim/anaconda3/envs/allennlp/lib/python3.7/site-packages/allennlp/commands/__init__.py", line 102, in main args.func(args) File "/home/mrim/affim/anaconda3/envs/allennlp/lib/python3.7/site-packages/allennlp/commands/train.py", line 124, in train_model_from_args args.cache_prefix) File "/home/mrim/affim/anaconda3/envs/allennlp/lib/python3.7/site-packages/allennlp/commands/train.py", line 168, in train_model_from_file cache_directory, cache_prefix) File "/home/mrim/affim/anaconda3/envs/allennlp/lib/python3.7/site-packages/allennlp/commands/train.py", line 252, in train_model metrics = trainer.train() File "/home/mrim/affim/anaconda3/envs/allennlp/lib/python3.7/site-packages/allennlp/training/trainer.py", line 478, in train train_metrics = self._train_epoch(epoch) File "/home/mrim/affim/anaconda3/envs/allennlp/lib/python3.7/site-packages/allennlp/training/trainer.py", line 320, in _train_epoch loss = self.batch_loss(batch_group, for_training=True) File "/home/mrim/affim/anaconda3/envs/allennlp/lib/python3.7/site-packages/allennlp/training/trainer.py", line 261, in batch_loss output_dict = self.model(**batch) File "/home/mrim/affim/anaconda3/envs/allennlp/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__ result = self.forward(*input, **kwargs) File "/home/mrim/affim/anaconda3/envs/allennlp/lib/python3.7/site-packages/allennlp/models/crf_tagger.py", line 182, in forward embedded_text_input = self.text_field_embedder(tokens) File "/home/mrim/affim/anaconda3/envs/allennlp/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__ result = self.forward(*input, **kwargs) File "/home/mrim/affim/anaconda3/envs/allennlp/lib/python3.7/site-packages/allennlp/modules/text_field_embedders/basic_text_field_embedder.py", line 132, in forward token_vectors = embedder(*tensors, **forward_params_values) File "/home/mrim/affim/anaconda3/envs/allennlp/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__ result = self.forward(*input, **kwargs) File "/home/mrim/affim/anaconda3/envs/allennlp/lib/python3.7/site-packages/allennlp/modules/token_embedders/bert_token_embedder.py", line 175, in forward attention_mask=util.combine_initial_dims(input_mask)) File "/home/mrim/affim/anaconda3/envs/allennlp/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__ result = self.forward(*input, **kwargs) File "/home/mrim/affim/anaconda3/envs/allennlp/lib/python3.7/site-packages/pytorch_pretrained_bert/modeling.py", line 730, in forward embedding_output = self.embeddings(input_ids, token_type_ids) File "/home/mrim/affim/anaconda3/envs/allennlp/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__ result = self.forward(*input, **kwargs) File "/home/mrim/affim/anaconda3/envs/allennlp/lib/python3.7/site-packages/pytorch_pretrained_bert/modeling.py", line 267, in forward words_embeddings = self.word_embeddings(input_ids) File "/home/mrim/affim/anaconda3/envs/allennlp/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__ result = self.forward(*input, **kwargs) File "/home/mrim/affim/anaconda3/envs/allennlp/lib/python3.7/site-packages/torch/nn/modules/sparse.py", line 114, in forward self.norm_type, self.scale_grad_by_freq, self.sparse) File "/home/mrim/affim/anaconda3/envs/allennlp/lib/python3.7/site-packages/torch/nn/functional.py", line 1484, in embedding return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse) RuntimeError: index out of range: Tried to access index 32730 out of table with 28995 rows. at /tmp/pip-req-build-ufslq_a9/aten/src/TH/generic/THTensorEvenMoreMath.cpp:418 
```

**Question**
is there any idea How to overcome this issue?

**Comment by dirkgr** [comment]
I can barely see anything here because the formatting is broken, but the problem here is likely that you are using a different vocabulary from the one that the model was trained with. ELMo and BERT have different vocabularies, and they are not interchangeable.

**Comment by manelAffi** [comment]
Hi @dirkgr.
thank you for your response.
Here, I'm trying to train crf-tagger model on ontonotes dataset english version. I have train the same model on conll2003 english version and it works without any problem.
Here is the full code of json file
 `{

  "dataset_reader": {
    "type": "ontonotes_ner",
    "coding_scheme": "BIOUL",
    "token_indexers": {
      "tokens": {
        "type": "single_id",
        "lowercase_tokens": true
      },
      "token_characters": {
        "type": "characters",
        "min_padding_length": 3
      },
      "elmo": {
        "type": "elmo_characters"
     },
"bert": {
          "type": "bert-pretrained",
          "pretrained_model": "bert-base-cased",

          "do_lowercase": false,
          "use_starting_offsets": true
      },
    }
  },
 "train_data_path": "XXXXXXXX",
    "validation_data_path": "XXXXXXX",
  
  "model": {
    "type": "crf_tagger",

    "label_encoding": "BIOUL",
    "dropout": 0.5,
    "include_start_end_transitions": false,
    "text_field_embedder": {

            "allow_unmatched_keys": true,
      
       "tokens": {
                    "type": "bert-pretrained",
                    "pretrained_model": "bert-base-cased"
                },
        "elmo":{
            "type": "elmo_token_embedder",
        "options_file": "https://allennlp.s3.amazonaws.com/models/elmo/2x4096_512_2048cnn_2xhighway/elmo_2x4096_512_2048cnn_2xhighway_options.json",
        "weight_file": "https://allennlp.s3.amazonaws.com/models/elmo/2x4096_512_2048cnn_2xhighway/elmo_2x4096_512_2048cnn_2xhighway_weights.hdf5",
            "do_layer_norm": false,
            "dropout": 0.0
        }
     
    },
    "encoder": {
      "type": "lstm",
      "input_size": 1792,
      "hidden_size": 200,
      "num_layers": 2,
      "dropout": 0.5,
      "bidirectional": true
    },
    "regularizer": [
      [
        "scalar_parameters",
        {
          "type": "l2",
          "alpha": 0.1
        }
      ]
    ]
  },
  "iterator": {
    "type": "basic",
    "batch_size": 32
  },
  "trainer": {
    "optimizer": {
        "type": "adam",
        "lr": 0.0001
    },
    "validation_metric": "+f1-measure-overall",
    "num_serialized_models_to_keep": 3,
    "num_epochs": 30,
    "grad_norm": 5.0,
    "patience": 25,
    "cuda_device": -1
  }
}
`

**Comment by dirkgr** [comment]
You have to use the `"bert-pretrained"` indexer instead of `"single_id"`. I don't know if that's the only issue, but try it and see how far you get!
