### ISSUE TITLE
unable to train my model

### ISSUE THREAD

**Issue by ud2195** [allenai/allennlp#4014]
Allennlp version: 0.9.0
python version: 3.6.9

on running the command  '!allennlp train /content/records.json -s /content/allen_models' i get the following error 

```
2020-04-03 12:51:55,618 - INFO - pytorch_pretrained_bert.modeling - Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .
2020-04-03 12:51:56,144 - INFO - pytorch_transformers.modeling_bert - Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .
2020-04-03 12:51:56,148 - INFO - pytorch_transformers.modeling_xlnet - Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .
2020-04-03 12:51:56,581 - INFO - allennlp.common.registrable - instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
2020-04-03 12:51:56,582 - INFO - allennlp.common.registrable - instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
2020-04-03 12:51:56,582 - INFO - allennlp.common.registrable - instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
2020-04-03 12:51:56,584 - INFO - allennlp.common.registrable - instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
2020-04-03 12:51:58,779 - INFO - allennlp.common.params - random_seed = 13370
2020-04-03 12:51:58,779 - INFO - allennlp.common.params - numpy_seed = 1337
2020-04-03 12:51:58,779 - INFO - allennlp.common.params - pytorch_seed = 133
2020-04-03 12:51:58,798 - INFO - allennlp.common.checks - Pytorch version: 1.4.0
Traceback (most recent call last):
  File "/usr/local/bin/allennlp", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.6/dist-packages/allennlp/run.py", line 18, in run
    main(prog="allennlp")
  File "/usr/local/lib/python3.6/dist-packages/allennlp/commands/__init__.py", line 102, in main
    args.func(args)
  File "/usr/local/lib/python3.6/dist-packages/allennlp/commands/train.py", line 124, in train_model_from_args
    args.cache_prefix)
  File "/usr/local/lib/python3.6/dist-packages/allennlp/commands/train.py", line 168, in train_model_from_file
    cache_directory, cache_prefix)
  File "/usr/local/lib/python3.6/dist-packages/allennlp/commands/train.py", line 211, in train_model
    cuda_device = params.params.get('trainer').get('cuda_device', -1)
AttributeError: 'NoneType' object has no attribute 'get'
```

Any help will be appreciated

**Comment by dirkgr** [comment]
Can you post your model config, the `records.json` file?

**Comment by dirkgr** [comment]
I'm sorry, but that's not how this works. The json file you specify describes the model you want to train, not the data you want to train on. I recommend you start by reading some of the Getting Started guide (https://github.com/allenai/allennlp/blob/master/tutorials/tagger/README.md), especially the section on "[using config files](https://github.com/allenai/allennlp/blob/master/tutorials/tagger/README.md#using-config-files)". Good luck!
