### ISSUE TITLE
Unable to run sentiment analysis model

### ISSUE THREAD

**Issue by balaji288** [allenai/allennlp#4015]
When I try to run the sentiment analysis RoBERTa model get a configuration error. I tried running both on command line and in python as a lib. Get the same error :

Command I run: 

echo '{"sentence": "a very well-made, funny and entertaining picture."}' | \
allennlp predict https://storage.googleapis.com/allennlp-public-models/sst-roberta-large-2020.02.17.tar.gz -

Error:

```
2020-04-03 11:14:54,054 - INFO - allennlp.common.params - model.text_field_embedder.token_embedders.tokens.type = pretrained_transformer_mismatched
Traceback (most recent call last):
  File "//anaconda3/envs/py37/bin/allennlp", line 8, in <module>
    sys.exit(run())
  File "//anaconda3/envs/py37/lib/python3.7/site-packages/allennlp/run.py", line 18, in run
    main(prog="allennlp")
  File "//anaconda3/envs/py37/lib/python3.7/site-packages/allennlp/commands/__init__.py", line 102, in main
    args.func(args)
  File "//anaconda3/envs/py37/lib/python3.7/site-packages/allennlp/commands/predict.py", line 214, in _predict
    predictor = _get_predictor(args)
  File "//anaconda3/envs/py37/lib/python3.7/site-packages/allennlp/commands/predict.py", line 120, in _get_predictor
    overrides=args.overrides)
  File "//anaconda3/envs/py37/lib/python3.7/site-packages/allennlp/models/archival.py", line 230, in load_archive
    cuda_device=cuda_device)
  File "//anaconda3/envs/py37/lib/python3.7/site-packages/allennlp/models/model.py", line 327, in load
    return cls.by_name(model_type)._load(config, serialization_dir, weights_file, cuda_device)
  File "//anaconda3/envs/py37/lib/python3.7/site-packages/allennlp/models/model.py", line 265, in _load
    model = Model.from_params(vocab=vocab, params=model_params)
  File "//anaconda3/envs/py37/lib/python3.7/site-packages/allennlp/common/from_params.py", line 365, in from_params
    return subclass.from_params(params=params, **extras)
  File "//anaconda3/envs/py37/lib/python3.7/site-packages/allennlp/common/from_params.py", line 386, in from_params
    kwargs = create_kwargs(cls, params, **extras)
  File "//anaconda3/envs/py37/lib/python3.7/site-packages/allennlp/common/from_params.py", line 133, in create_kwargs
    kwargs[name] = construct_arg(cls, name, annotation, param.default, params, **extras)
  File "//anaconda3/envs/py37/lib/python3.7/site-packages/allennlp/common/from_params.py", line 229, in construct_arg
    return annotation.from_params(params=subparams, **subextras)
  File "//anaconda3/envs/py37/lib/python3.7/site-packages/allennlp/common/from_params.py", line 365, in from_params
    return subclass.from_params(params=params, **extras)
  File "//anaconda3/envs/py37/lib/python3.7/site-packages/allennlp/modules/text_field_embedders/basic_text_field_embedder.py", line 160, in from_params
    for name, subparams in token_embedder_params.items()
  File "//anaconda3/envs/py37/lib/python3.7/site-packages/allennlp/modules/text_field_embedders/basic_text_field_embedder.py", line 160, in <dictcomp>
    for name, subparams in token_embedder_params.items()
  File "//anaconda3/envs/py37/lib/python3.7/site-packages/allennlp/common/from_params.py", line 359, in from_params
    default_to_first_choice=default_to_first_choice)
  File "//anaconda3/envs/py37/lib/python3.7/site-packages/allennlp/common/params.py", line 363, in pop_choice
    raise ConfigurationError(message)
allennlp.common.checks.ConfigurationError: 'pretrained_transformer_mismatched not in acceptable choices for model.text_field_embedder.token_embedders.tokens.type: [\'embedding\', \'character_encoding\', \'elmo_token_embedder\', \'elmo_token_embedder_multilang\', \'openai_transformer_embedder\', \'bert-pretrained\', \'language_model_token_embedder\', \'bidirectional_lm_token_embedder\', \'bag_of_word_counts\', \'pass_through\', \'pretrained_transformer\']. You should either use the --include-package flag to make sure the correct module is loaded, or use a fully qualified class name in your config file like {"model": "my_module.models.MyModel"} to have it imported automatically.'
```

**Comment by dirkgr** [comment]
I assume you are running the latest `master`? I am in the middle of a big push of fixing a bunch of these models. I will update this issue when it's done. In the meantime, can you try it with version 0.9 of allennlp?

**Comment by balaji288** [comment]
Thanks for the quick response. I got the error when I ran it with 0.9 version of Allennlp.


Thanks 
Regards
Balaji

**Comment by matt-gardner** [comment]
That model is incompatible with 0.9.  Any model you see with a 2020 date on it will almost certainly be incompatible with 0.9.  If you want to use that model, you need to use master (and in some cases, depending on when the model was made, it might also be incompatible with master; we're working on updating everything to account for breaking changes we've made for the 1.0 release).

**Comment by balaji288** [comment]
thanks for the update. I tried to run the model with master and it worked fine. I will use the master till the official 1.0 release. Thank @matt-gardner  and @dirkgr for quick response and resolution.
