### ISSUE TITLE
Error while evaluation of trained model on ontonotes test dataset:  'No instances were read from the given filepath '

### ISSUE THREAD

**Issue by manelAffi** [allenai/allennlp#4069]
**System (please complete the following information):**
- OS: Linux
- Python version: 3.7.7
- AllenNLP version: 0.9.0
- PyTorch version: 1.4.0

**Question**

Hi,
 I have train crf-tagger model on ontotnotes 5.0 English dataset for named entity recognition task. I have obtain  CoNLL-formatted OntoNotes 5.0 by using :
- OntoNotes 5.0 from LDC (thru email)
- CoNLL-formatted OntoNotes 5.0 scripts from [http://conll.cemantix.org/2012/data.html ](http://conll.cemantix.org/2012/data.html) .

Trying to evaluate the obtained model by using the following commande,

`allennlp evaluate  "/path/to/model.tar.gz"  "/home/mrim/affim/conll-2012/v9/data/test/data/english/"`

I'm getting this error:
```
allennlp.common.checks.ConfigurationError: 'No instances were read from the given filepath /home/mrim/affim/conll-2012/v9/data/test/data/english/. Is the path correct?'
2020-04-15 12:49:35,663 - INFO - allennlp.models.archival - removing temporary unarchived model dir at /tmp/tmp3_2nd8dc
```
Here is the full stack trace:
```
Traceback (most recent call last):
  File "/home/mrim/affim/anaconda3/envs/allennlp/bin/allennlp", line 8, in <module>
    sys.exit(run())
  File "/home/mrim/affim/anaconda3/envs/allennlp/lib/python3.7/site-packages/allennlp/run.py", line 18, in run
    main(prog="allennlp")
  File "/home/mrim/affim/anaconda3/envs/allennlp/lib/python3.7/site-packages/allennlp/commands/__init__.py", line 102, in main
    args.func(args)
  File "/home/mrim/affim/anaconda3/envs/allennlp/lib/python3.7/site-packages/allennlp/commands/evaluate.py", line 146, in evaluate_from_args
    instances = dataset_reader.read(evaluation_data_path)
  File "/home/mrim/affim/anaconda3/envs/allennlp/lib/python3.7/site-packages/allennlp/data/dataset_readers/dataset_reader.py", line 137, in read
    "Is the path correct?".format(file_path))
allennlp.common.checks.ConfigurationError: 'No instances were read from the given filepath /home/mrim/affim/conll-2012/v9/data/test/data/english/. Is the path correct?'
2020-04-15 12:49:35,663 - INFO - allennlp.models.archival - removing temporary unarchived model dir at /tmp/tmp3_2nd8dc
```
**Question** 
Is there any idea what should be the problem?
NB: I checked the english test folder and I found the conll files which are not empty.

**Comment by schmmd** [comment]
I'm not quite sure but there's a script `scripts/compile_coref_data.sh` in AllenNLP that you might need to use to get the data in the right format.  This is just a guess though--I'm not sure.

**Comment by manelAffi** [comment]
@schmmd thank you for your response.
 It's just missing the gold key folder "conll-2012-test-key.tar.gz" [downloaded from [](http://conll.cemantix.org/2012/data.html) for the test data. I added it before converting the skeleton files to conll files and the problem was solved.
