### ISSUE TITLE
`allennlp predict` fails for the Bidaf model

### ISSUE THREAD

**Issue by dirkgr** [allenai/allennlp#4094]
```
echo '{"passage": "The Matrix is a 1999 science fiction action film written and directed by The Wachowskis, starring Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss, Hugo Weaving, and Joe Pantoliano.", "question": "Who stars in The Matrix?"}' | allennlp predict --include-package allennlp_models https://storage.googleapis.com/allennlp-public-models/bidaf-elmo-model-2020.03.19.tar.gz -
```

fails with

```
Traceback (most recent call last):
  File "/Users/dirkg/anaconda3/envs/allennlp-models/bin/allennlp", line 11, in <module>
    load_entry_point('allennlp', 'console_scripts', 'allennlp')()
  File "/Users/dirkg/Documents/allennlp/allennlp/__main__.py", line 19, in run
    main(prog="allennlp")
  File "/Users/dirkg/Documents/allennlp/allennlp/commands/__init__.py", line 93, in main
    args.func(args)
  File "/Users/dirkg/Documents/allennlp/allennlp/commands/predict.py", line 255, in _predict
    manager.run()
  File "/Users/dirkg/Documents/allennlp/allennlp/commands/predict.py", line 229, in run
    for model_input_json, result in zip(batch_json, self._predict_json(batch_json)):
  File "/Users/dirkg/Documents/allennlp/allennlp/commands/predict.py", line 175, in _predict_json
    results = [self._predictor.predict_json(batch_data[0])]
  File "/Users/dirkg/Documents/allennlp/allennlp/predictors/predictor.py", line 65, in predict_json
    instance = self._json_to_instance(inputs)
  File "/Users/dirkg/Documents/allennlp/allennlp/predictors/predictor.py", line 213, in _json_to_instance
    raise NotImplementedError
```

**Comment by dirkgr** [comment]
Note to self: Also update this in the demo

**Comment by dirkgr** [comment]
This was auto-closed, but I haven't updated the demo yet.

**Comment by peterhanlon** [comment]
Hi Dirk, I'm experiencing the NotImplementedError problem highlighted above. Do you have any pointers or guidance around what I need to change to get it to work. I've tried rc1 as per the demo on the website and rc3 both of which fail. Any pointers would be much appreciated

Pete

**Comment by matt-gardner** [comment]
I don't think the fix has made it into a release yet, it was fixed after rc3.

**Comment by peterhanlon** [comment]
Is there a way to download the models if I download 1.0.0rc4.dev20200513? If not is there a rough date for rc4? Loving your work by the way, just keen to play with it :)

**Comment by schmmd** [comment]
@peterhanlon rc4 should be out soon (this week maybe?) but you should be able to use the existing model with a master clone of AllenNLP.  Let us know if that does or doesn't work!

**Comment by peterhanlon** [comment]
Will give it a go, thanks :)

**Comment by dirkgr** [comment]
I just confirmed that it works with the latest master.
