### ISSUE TITLE
tqdm exceptions while training SNLI

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp#420]
The exception does not abort the execution of the training.

This exception only appears when `no_tqdm` is `False` in the configuration.

```
time allennlp/run train training_config/decomposable_attention.json -s da-output
2017-10-19 21:15:05,231 - WARNING - root - run is deprecated, please use run.py
2017-10-19 21:15:05,275 - INFO - allennlp.common.params - random_seed = 13370
2017-10-19 21:15:05,275 - INFO - allennlp.common.params - numpy_seed = 1337
2017-10-19 21:15:05,275 - INFO - allennlp.common.params - pytorch_seed = 133
2017-10-19 21:15:05,275 - INFO - allennlp.common.checks - Pytorch version: 0.2.0_3
2017-10-19 21:15:05,276 - INFO - allennlp.common.params - dataset_reader.type = snli
2017-10-19 21:15:05,276 - INFO - allennlp.common.params - dataset_reader.tokenizer.type = word
2017-10-19 21:15:05,276 - INFO - allennlp.common.params - dataset_reader.tokenizer.word_splitter.type = spacy
2017-10-19 21:15:05,276 - INFO - allennlp.common.params - dataset_reader.tokenizer.word_splitter.language = en
2017-10-19 21:15:05,276 - INFO - allennlp.common.params - dataset_reader.tokenizer.word_splitter.pos_tags = False
2017-10-19 21:15:05,277 - INFO - allennlp.common.params - dataset_reader.tokenizer.word_splitter.parse = False
2017-10-19 21:15:05,277 - INFO - allennlp.common.params - dataset_reader.tokenizer.word_splitter.ner = False
2017-10-19 21:15:07,296 - INFO - allennlp.common.params - dataset_reader.tokenizer.word_filter.type = pass_through
2017-10-19 21:15:07,296 - INFO - allennlp.common.params - dataset_reader.tokenizer.word_stemmer.type = pass_through
2017-10-19 21:15:07,296 - INFO - allennlp.common.params - dataset_reader.tokenizer.start_tokens = None
2017-10-19 21:15:07,296 - INFO - allennlp.common.params - dataset_reader.tokenizer.end_tokens = ['@@NULL@@']
2017-10-19 21:15:07,297 - INFO - allennlp.common.params - dataset_reader.token_indexers.tokens.type = single_id
2017-10-19 21:15:07,297 - INFO - allennlp.common.params - dataset_reader.token_indexers.tokens.namespace = tokens
2017-10-19 21:15:07,297 - INFO - allennlp.common.params - dataset_reader.token_indexers.tokens.lowercase_tokens = True
2017-10-19 21:15:07,297 - INFO - allennlp.common.params - train_data_path = https://s3-us-west-2.amazonaws.com/allennlp/datasets/snli/snli_1.0_train.jsonl
2017-10-19 21:15:07,297 - INFO - allennlp.commands.train - Reading training data from https://s3-us-west-2.amazonaws.com/allennlp/datasets/snli/snli_1.0_train.jsonl
2017-10-19 21:15:07,335 - INFO - allennlp.common.file_utils - https://s3-us-west-2.amazonaws.com/allennlp/datasets/snli/snli_1.0_train.jsonl not found in cache, downloading to /tmp/tmp95s3b8j0
 99%|#########8| 482572288/487457790 [00:08<00:00, 58975318.85B/s]2017-10-19 21:15:19,160 - INFO - allennlp.common.file_utils - copying /tmp/tmp95s3b8j0 to cache at /home/michaels/.allennlp/datasets/aHR0cHM6Ly9zMy11cy13ZXN0LTIuYW1hem9uYXdzLmNvbS9hbGxlbm5scC9kYXRhc2V0cy9zbmxpL3NubGlfMS4wX3RyYWluLmpzb25s."a7f17fd005c0398a28926bcc6c8af08b-59"
2017-10-19 21:15:19,594 - INFO - allennlp.common.file_utils - removing temp file /tmp/tmp95s3b8j0
2017-10-19 21:15:19,594 - INFO - allennlp.data.dataset_readers.snli - Reading SNLI instances from jsonl dataset at: /home/michaels/.allennlp/datasets/aHR0cHM6Ly9zMy11cy13ZXN0LTIuYW1hem9uYXdzLmNvbS9hbGxlbm5scC9kYXRhc2V0cy9zbmxpL3NubGlfMS4wX3RyYWluLmpzb25s."a7f17fd005c0398a28926bcc6c8af08b-59"
100%|##########| 487457790/487457790 [00:20<00:00, 24242390.05B/s]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/michaels/miniconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/michaels/miniconda3/lib/python3.6/site-packages/tqdm/_tqdm.py", line 144, in run
    for instance in self.tqdm_cls._instances:
  File "/home/michaels/miniconda3/lib/python3.6/_weakrefset.py", line 60, in __iter__
    for itemref in self.data:
RuntimeError: Set changed size during iteration
```

**Comment by matt-gardner** [comment]
This is weird, because `no_tqdm` should only matter during training, and it doesn't look like you've gotten that far yet.  Do you know what line causes this error?

**Comment by schmmd** [comment]
Extra weird.  @matt-gardner I can look into it myself--sorry forgot self-asign.

**Comment by schmmd** [comment]
No no quiero TQDM demasiado.  I put in several `print` statements and found that the loop was hanging after the last command, and before the first command.  I think the fix here is to have a global option for disabling TQDM everywhere in a training execution.

**Comment by matt-gardner** [comment]
I find it really unlikely that tqdm is the culprit here.  You say this only happens with a clear cache - if you use local file paths instead of s3 URLs, does it still hang?  Maybe the issue is actually with our caching logic.

**Comment by schmmd** [comment]
I find it surprising, but I'm quite sure it's TQDM.

1.  The code hangs on the line that is conducting the for loop.
2.  I can repeatedly trigger the hang, but there is no hang if I remove TQDM.

There is no caching logic within the loop where it hangs.  Rather, the input is a file handle to an open file.

**Comment by matt-gardner** [comment]
This is while loading training data?  Does replacing the filename with a path instead of an S3 URL still hang?

**Comment by schmmd** [comment]
ah, @matt-gardner -- my last two comments were meant issue https://github.com/allenai/allennlp/issues/425, not here.

**Comment by schmmd** [comment]
I'm closing this issue as it may have been fixed by related PRs.  I'll re-open if it re-occurs.
