### ISSUE TITLE
How can I use SCI-BERT Sci-Vocab for Text-Entailment ?

### ISSUE THREAD

**Issue by codehunk628** [allenai/allennlp#4208]
I want to use SCI-Bert Vocab for Text-Entailment task. How can I use it with allennlp Roberta-SNLI model.

**Comment by matt-gardner** [comment]
You're going to have to retrain the model to do this.  Basically all you need to do is replace the "roberta-large" transformer name in the [roberta-snli config file](https://github.com/allenai/allennlp-models/blob/36020d55b37d8c2c50b843e845a45b85b257a67a/training_config/nli/snli_roberta.jsonnet#L1) with whatever scibert model you want to use.

**Comment by codehunk628** [comment]
thank you @matt-gardner .
I tried but its giving unicode decoding error
the error summary is :
 File "/content/drive/My Drive/Practice-Notebooks/Modl/allennlp/allennlp/common/from_params.py", line 287, in pop_and_construct_arg
    return construct_arg(class_name, name, popped_params, annotation, default, **extras)
  File "/content/drive/My Drive/Practice-Notebooks/Modl/allennlp/allennlp/common/from_params.py", line 321, in construct_arg
    return annotation.from_params(params=popped_params, **subextras)
  File "/content/drive/My Drive/Practice-Notebooks/Modl/allennlp/allennlp/common/from_params.py", line 580, in from_params
    **extras,
  File "/content/drive/My Drive/Practice-Notebooks/Modl/allennlp/allennlp/common/from_params.py", line 611, in from_params
    return constructor_to_call(**kwargs)  # type: ignore
  File "/content/drive/My Drive/Practice-Notebooks/Modl/allennlp/allennlp/data/tokenizers/pretrained_transformer_tokenizer.py", line 84, in __init__
    self.tokenizer = AutoTokenizer.from_pretrained(model_name, **tokenizer_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/transformers/tokenization_auto.py", line 186, in from_pretrained
    config = AutoConfig.from_pretrained(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/transformers/configuration_auto.py", line 187, in from_pretrained
    pretrained_model_name_or_path, pretrained_config_archive_map=ALL_PRETRAINED_CONFIG_ARCHIVE_MAP, **kwargs
  File "/usr/local/lib/python3.6/dist-packages/transformers/configuration_utils.py", line 252, in get_config_dict
    config_dict = cls._dict_from_json_file(resolved_config_file)
  File "/usr/local/lib/python3.6/dist-packages/transformers/configuration_utils.py", line 344, in _dict_from_json_file
    text = reader.read()
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 229888: invalid start byte

![image](https://user-images.githubusercontent.com/51091425/81466208-4fc7eb00-91ed-11ea-9287-e7c6981f0686.png)

**Comment by matt-gardner** [comment]
That failure is coming from hugging face code. I'm afraid we're not going to be able to debug it; you might open an issue on the transformers library. For that, just run the command `AutoTokenizer.from_pretrained` with whatever name you were using, and show them the failure.

**Comment by codehunk628** [comment]
@matt-gardner 
I guess that issue is resolved.
But now i am getting input size mismatch.
could you help me with this as to why this is so?

ERROR LOG is as :
2020-05-10 10:45:14,020 - INFO - allennlp.training.trainer - Beginning training.
2020-05-10 10:45:14,020 - INFO - allennlp.training.trainer - Epoch 0/9
2020-05-10 10:45:14,020 - INFO - allennlp.training.trainer - Peak CPU memory usage MB: 5493.272
2020-05-10 10:45:14,128 - INFO - allennlp.training.trainer - GPU 0 memory usage MB: 10
2020-05-10 10:45:14,130 - INFO - allennlp.training.trainer - Training
  0%|          | 0/17168 [00:00<?, ?it/s]2020-05-10 10:45:14,131 - INFO - allennlp.data.samplers.bucket_batch_sampler - No sorting keys given; trying to guess a good one
2020-05-10 10:45:14,152 - INFO - allennlp.data.samplers.bucket_batch_sampler - Using ['tokens'] as the sorting keys
Traceback (most recent call last):
  File "/usr/local/bin/allennlp", line 11, in <module>
    load_entry_point('allennlp', 'console_scripts', 'allennlp')()
  File "/content/drive/My Drive/Practice-Notebooks/Modl/allennlp/allennlp/__main__.py", line 19, in run
    main(prog="allennlp")
  File "/content/drive/My Drive/Practice-Notebooks/Modl/allennlp/allennlp/commands/__init__.py", line 92, in main
    args.func(args)
  File "/content/drive/My Drive/Practice-Notebooks/Modl/allennlp/allennlp/commands/train.py", line 144, in train_model_from_args
    dry_run=args.dry_run,
  File "/content/drive/My Drive/Practice-Notebooks/Modl/allennlp/allennlp/commands/train.py", line 203, in train_model_from_file
    dry_run=dry_run,
  File "/content/drive/My Drive/Practice-Notebooks/Modl/allennlp/allennlp/commands/train.py", line 266, in train_model
    dry_run=dry_run,
  File "/content/drive/My Drive/Practice-Notebooks/Modl/allennlp/allennlp/commands/train.py", line 463, in _train_worker
    metrics = train_loop.run()
  File "/content/drive/My Drive/Practice-Notebooks/Modl/allennlp/allennlp/commands/train.py", line 525, in run
    return self.trainer.train()
  File "/content/drive/My Drive/Practice-Notebooks/Modl/allennlp/allennlp/training/trainer.py", line 732, in train
    train_metrics = self._train_epoch(epoch)
  File "/content/drive/My Drive/Practice-Notebooks/Modl/allennlp/allennlp/training/trainer.py", line 500, in _train_epoch
    batch_outputs = self.batch_outputs(batch, for_training=True)
  File "/content/drive/My Drive/Practice-Notebooks/Modl/allennlp/allennlp/training/trainer.py", line 406, in batch_outputs
    output_dict = self._pytorch_model(**batch)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/drive/My Drive/Practice-Notebooks/Modl/allennlp/allennlp/models/basic_classifier.py", line 133, in forward
    embedded_text = self._feedforward(embedded_text)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/drive/My Drive/Practice-Notebooks/Modl/allennlp/allennlp/modules/feedforward.py", line 107, in forward
    output = dropout(activation(layer(output)))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 1610, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: size mismatch, m1: [32 x 768], m2: [1024 x 1024] at /pytorch/aten/src/TH/generic/THTensorMath.cpp:41
  0%|          | 0/17168 [00:36<?, ?it/s]

**Comment by codehunk628** [comment]
Thank You @matt-gardner 
It was hidden dimension which is different for both (for roberta-1024 and for scibert-768).
I have changed that and Its working.
