### ISSUE TITLE
Docker images do not contain allennlp-models

### ISSUE THREAD

**Issue by JaapHaitsma** [allenai/allennlp#4217]
**Describe the bug**
Trying to run this command:
```
echo '{"sentence": "Did Uriah honestly think he could beat The Legend of Zelda in under three hours?"}' | \
allennlp predict https://storage.googleapis.com/allennlp-public-models/ner-model-2020.02.10.tar.gz -
```
as described on the usage tab of https://demo.allennlp.org/named-entity-recognition

in the official docker image but it returns 

```
Traceback (most recent call last):
  File "/usr/local/bin/allennlp", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.6/site-packages/allennlp/__main__.py", line 19, in run
    main(prog="allennlp")
  File "/usr/local/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 93, in main
    args.func(args)
  File "/usr/local/lib/python3.6/site-packages/allennlp/commands/predict.py", line 240, in _predict
    predictor = _get_predictor(args)
  File "/usr/local/lib/python3.6/site-packages/allennlp/commands/predict.py", line 141, in _get_predictor
    overrides=args.overrides,
  File "/usr/local/lib/python3.6/site-packages/allennlp/models/archival.py", line 197, in load_archive
    opt_level=opt_level,
  File "/usr/local/lib/python3.6/site-packages/allennlp/models/model.py", line 386, in load
    model_class: Type[Model] = cls.by_name(model_type)  # type: ignore
  File "/usr/local/lib/python3.6/site-packages/allennlp/common/registrable.py", line 137, in by_name
    subclass, constructor = cls.resolve_class_name(name)
  File "/usr/local/lib/python3.6/site-packages/allennlp/common/registrable.py", line 185, in resolve_class_name
    f"{name} is not a registered name for {cls.__name__}. "
allennlp.common.checks.ConfigurationError: crf_tagger is not a registered name for Model. You probably need to use the --include-package flag to load your custom code. Alternatively, you can specify your choices using fully-qualified paths, e.g. {"model": "my_module.models.MyModel"} in which case they will be automatically imported correctly.
2020-05-10 13:46:41,806 - INFO - allennlp.models.archival - removing temporary unarchived model dir at /tmp/tmpcuvikhcv
```

**To Reproduce**
Steps to reproduce the behavior
1.  Run `docker run --rm -it -v $HOME/.allennlp:/root/.allennlp --entrypoint /bin/bash allennlp/allennlp:v1.0.0rc3`
2. Then in bash shell run 
```
echo '{"sentence": "Did Uriah honestly think he could beat The Legend of Zelda in under three hours?"}' | \
allennlp predict https://storage.googleapis.com/allennlp-public-models/ner-model-2020.02.10.tar.gz -

```

**Expected behavior**
It should run without errors

**System (please complete the following information):**
 - Docker

**Comment by JaapHaitsma** [comment]
NOTE the command does not work when I install allennlp on my local machine

**Comment by JaapHaitsma** [comment]
It works with an older model locally when I run

`echo '{"sentence": "Did Uriah honestly think he could beat The Legend of Zelda in under three hours?"}' | allennlp predict https://s3-us-west-2.amazonaws.com/allennlp/models/ner-model-2018.12.18.tar.gz -`

but in the docker container it does not work and gives this output

```
Traceback (most recent call last):
  File "/usr/local/bin/allennlp", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.6/site-packages/allennlp/__main__.py", line 19, in run
    main(prog="allennlp")
  File "/usr/local/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 93, in main
    args.func(args)
  File "/usr/local/lib/python3.6/site-packages/allennlp/commands/predict.py", line 240, in _predict
    predictor = _get_predictor(args)
  File "/usr/local/lib/python3.6/site-packages/allennlp/commands/predict.py", line 141, in _get_predictor
    overrides=args.overrides,
  File "/usr/local/lib/python3.6/site-packages/allennlp/models/archival.py", line 197, in load_archive
    opt_level=opt_level,
  File "/usr/local/lib/python3.6/site-packages/allennlp/models/model.py", line 386, in load
    model_class: Type[Model] = cls.by_name(model_type)  # type: ignore
  File "/usr/local/lib/python3.6/site-packages/allennlp/common/registrable.py", line 137, in by_name
    subclass, constructor = cls.resolve_class_name(name)
  File "/usr/local/lib/python3.6/site-packages/allennlp/common/registrable.py", line 185, in resolve_class_name
    f"{name} is not a registered name for {cls.__name__}. "
allennlp.common.checks.ConfigurationError: crf_tagger is not a registered name for Model. You probably need to use the --include-package flag to load your custom code. Alternatively, you can specify your choices using fully-qualified paths, e.g. {"model": "my_module.models.MyModel"} in which case they will be automatically imported correctly.
2020-05-10 19:49:06,780 - INFO - allennlp.models.archival - removing temporary unarchived model dir at /tmp/tmpmh2wo5p5
```

**Comment by matt-gardner** [comment]
What docker image are you using?

The problem here is that for that command to work, you must also have `allennlp-models` installed.  It's apparently not installed in whatever docker image you're using.

**Comment by epwalsh** [comment]
Yea, currently the images `allennlp/allennlp` and `allennlp/commit` do not come with `allennlp-models` installed.

**Comment by JaapHaitsma** [comment]
So what should I do then if I want to use the docker container?

**Comment by epwalsh** [comment]
The best thing to do would be to build your own image using the `allennlp` image as the base, installing `allennlp-models` and anything else you need on top of that. So you could start with something like this for your Dockerfile:

```dockerfile
FROM allennlp/allennlp:v1.0.0rc3
RUN pip install allennlp-models==1.0.0rc3
```

Then build and run with

```bash
docker build -t my-allennlp .
docker run --rm -it -v $HOME/.allennlp:/root/.allennlp --entrypoint /bin/bash my-allennlp
```

**Comment by JaapHaitsma** [comment]
Thanks @epwalsh  , I built the docker image but it still does not work.
Output:

```
jaaps-mbp:nlp jaap$ docker run --rm -it -v $HOME/.allennlp:/root/.allennlp --entrypoint /bin/bash my-allennlp:latest
root@f8ad8459dd2f:/stage/allennlp# echo '{"sentence": "Did Uriah honestly think he could beat The Legend of Zelda in under three hours?"}' | allennlp predict https://s3-us-west-2.amazonaws.com/allennlp/models/ner-model-2018.12.18.tar.gz -
2020-05-11 18:02:44,698 - INFO - transformers.file_utils - PyTorch version 1.5.0 available.
2020-05-11 18:02:48,111 - INFO - allennlp.models.archival - loading archive file https://s3-us-west-2.amazonaws.com/allennlp/models/ner-model-2018.12.18.tar.gz from cache at /root/.allennlp/cache/dc56159eaf93301e109b0d62eaa7ecb57492ec567faa2dbcd8eb8fcf4c899f65.d3e3999ea2d388798ef52ce82e6b6d2c00dd8e292a74d1f0e9c7f17993aed55d
2020-05-11 18:02:48,115 - INFO - allennlp.models.archival - extracting archive file /root/.allennlp/cache/dc56159eaf93301e109b0d62eaa7ecb57492ec567faa2dbcd8eb8fcf4c899f65.d3e3999ea2d388798ef52ce82e6b6d2c00dd8e292a74d1f0e9c7f17993aed55d to temp dir /tmp/tmpvd1na138
2020-05-11 18:02:57,600 - INFO - allennlp.common.params - type = from_instances
2020-05-11 18:02:57,600 - INFO - allennlp.data.vocabulary - Loading token dictionary from /tmp/tmpvd1na138/vocabulary.
2020-05-11 18:02:57,635 - INFO - allennlp.common.params - model.type = crf_tagger
Traceback (most recent call last):
  File "/usr/local/bin/allennlp", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.6/site-packages/allennlp/__main__.py", line 19, in run
    main(prog="allennlp")
  File "/usr/local/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 93, in main
    args.func(args)
  File "/usr/local/lib/python3.6/site-packages/allennlp/commands/predict.py", line 240, in _predict
    predictor = _get_predictor(args)
  File "/usr/local/lib/python3.6/site-packages/allennlp/commands/predict.py", line 141, in _get_predictor
    overrides=args.overrides,
  File "/usr/local/lib/python3.6/site-packages/allennlp/models/archival.py", line 197, in load_archive
    opt_level=opt_level,
  File "/usr/local/lib/python3.6/site-packages/allennlp/models/model.py", line 387, in load
    return model_class._load(config, serialization_dir, weights_file, cuda_device, opt_level)
  File "/usr/local/lib/python3.6/site-packages/allennlp/models/model.py", line 290, in _load
    model = Model.from_params(vocab=vocab, params=model_params)
  File "/usr/local/lib/python3.6/site-packages/allennlp/common/from_params.py", line 552, in from_params
    **extras,
  File "/usr/local/lib/python3.6/site-packages/allennlp/common/from_params.py", line 580, in from_params
    kwargs = create_kwargs(constructor_to_inspect, cls, params, **extras)
  File "/usr/local/lib/python3.6/site-packages/allennlp/common/from_params.py", line 164, in create_kwargs
    cls.__name__, param_name, annotation, param.default, params, **extras
  File "/usr/local/lib/python3.6/site-packages/allennlp/common/from_params.py", line 270, in pop_and_construct_arg
    return construct_arg(class_name, name, popped_params, annotation, default, **extras)
  File "/usr/local/lib/python3.6/site-packages/allennlp/common/from_params.py", line 304, in construct_arg
    return annotation.from_params(params=popped_params, **subextras)
  File "/usr/local/lib/python3.6/site-packages/allennlp/common/from_params.py", line 516, in from_params
    "from_params was passed a `params` object that was not a `Params`. This probably "
allennlp.common.checks.ConfigurationError: from_params was passed a `params` object that was not a `Params`. This probably indicates malformed parameters in a configuration file, where something that should have been a dictionary was actually a list, or something else. This happened when constructing an object of type <class 'allennlp.nn.regularizers.regularizer_applicator.RegularizerApplicator'>.
2020-05-11 18:02:57,651 - INFO - allennlp.models.archival - removing temporary unarchived model dir at /tmp/tmpvd1na138
root@f8ad8459dd2f:/stage/allennlp# 
```

**Comment by epwalsh** [comment]
Ah, I think this model was trained on an older version of AllenNLP. Try just running this image:

```
docker run --rm -it -v $HOME/.allennlp:/root/.allennlp --entrypoint=/bin/bash allennlp/commit:ff0d44a5e21d5e6256c73b5b9f216a87c5743f91
```

**Comment by epwalsh** [comment]
We're in the midst of updating the demos, so a bunch of things (including a lot of the usage examples, like this one) might be out-of-date.

**Comment by JaapHaitsma** [comment]
> Ah, I think this model was trained on an older version of AllenNLP. Try just running this image:
> 
> ```
> docker run --rm -it -v $HOME/.allennlp:/root/.allennlp --entrypoint=/bin/bash allennlp/commit:ff0d44a5e21d5e6256c73b5b9f216a87c5743f91
> ```
Thanks this worked but it is very annoying that there is not a self explaining error message that the model is not compatible with later versions of AllenNLP.
