### ISSUE TITLE
allennlp.common.checks.ConfigurationError: from_params was passed a `params` object that was not a `Params`.

### ISSUE THREAD

**Issue by wly-thu** [allenai/allennlp#4247]
When I was testing with the pre training model, this problem occurred. I checked it for a long time and didn't solve it. Can you help me?

```
allennlp predict \
>     https://allennlp.s3.amazonaws.com/models/ner-model-2018.04.26.tar.gz \
>     ner-examples.jsonl
2020-05-16 17:17:08,547 - INFO - transformers.file_utils - PyTorch version 1.5.0 available.
/data/wangly/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pandas/compat/__init__.py:85: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)
/data/wangly/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pandas/compat/__init__.py:85: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)
2020-05-16 17:17:12,627 - INFO - allennlp.models.archival - loading archive file https://allennlp.s3.amazonaws.com/models/ner-model-2018.04.26.tar.gz from cache at /data/wangly/.allennlp/cache/1445dee89770da04626248ae552c3a5eeb2cee69c7d0f46851c0d87d1c6f5a3b.e99d2b8f9e4678754c0c699dca2570b805b77d0f5bb921d8a2bff15b09367f0d
2020-05-16 17:17:12,629 - INFO - allennlp.models.archival - extracting archive file /data/wangly/.allennlp/cache/1445dee89770da04626248ae552c3a5eeb2cee69c7d0f46851c0d87d1c6f5a3b.e99d2b8f9e4678754c0c699dca2570b805b77d0f5bb921d8a2bff15b09367f0d to temp dir /tmp/tmp9wjx6p7c
2020-05-16 17:17:20,305 - INFO - allennlp.common.params - type = from_instances
2020-05-16 17:17:20,306 - INFO - allennlp.data.vocabulary - Loading token dictionary from /tmp/tmp9wjx6p7c/vocabulary.
2020-05-16 17:17:20,335 - INFO - allennlp.common.params - model.type = crf_tagger
Traceback (most recent call last):
  File "/data/wangly/.pyenv/versions/3.6.8/bin/allennlp", line 8, in <module>
    sys.exit(run())
  File "/data/wangly/.pyenv/versions/3.6.8/lib/python3.6/site-packages/allennlp/__main__.py", line 19, in run
    main(prog="allennlp")
  File "/data/wangly/.pyenv/versions/3.6.8/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 92, in main
    args.func(args)
  File "/data/wangly/.pyenv/versions/3.6.8/lib/python3.6/site-packages/allennlp/commands/predict.py", line 240, in _predict
    predictor = _get_predictor(args)
  File "/data/wangly/.pyenv/versions/3.6.8/lib/python3.6/site-packages/allennlp/commands/predict.py", line 141, in _get_predictor
    overrides=args.overrides,
  File "/data/wangly/.pyenv/versions/3.6.8/lib/python3.6/site-packages/allennlp/models/archival.py", line 197, in load_archive
    opt_level=opt_level,
  File "/data/wangly/.pyenv/versions/3.6.8/lib/python3.6/site-packages/allennlp/models/model.py", line 394, in load
    return model_class._load(config, serialization_dir, weights_file, cuda_device, opt_level)
  File "/data/wangly/.pyenv/versions/3.6.8/lib/python3.6/site-packages/allennlp/models/model.py", line 291, in _load
    model = Model.from_params(vocab=vocab, params=model_params)
  File "/data/wangly/.pyenv/versions/3.6.8/lib/python3.6/site-packages/allennlp/common/from_params.py", line 580, in from_params
    **extras,
  File "/data/wangly/.pyenv/versions/3.6.8/lib/python3.6/site-packages/allennlp/common/from_params.py", line 609, in from_params
    kwargs = create_kwargs(constructor_to_inspect, cls, params, **extras)
  File "/data/wangly/.pyenv/versions/3.6.8/lib/python3.6/site-packages/allennlp/common/from_params.py", line 181, in create_kwargs
    cls.__name__, param_name, annotation, param.default, params, **extras
  File "/data/wangly/.pyenv/versions/3.6.8/lib/python3.6/site-packages/allennlp/common/from_params.py", line 287, in pop_and_construct_arg
    return construct_arg(class_name, name, popped_params, annotation, default, **extras)
  File "/data/wangly/.pyenv/versions/3.6.8/lib/python3.6/site-packages/allennlp/common/from_params.py", line 321, in construct_arg
    return annotation.from_params(params=popped_params, **subextras)
  File "/data/wangly/.pyenv/versions/3.6.8/lib/python3.6/site-packages/allennlp/common/from_params.py", line 533, in from_params
    "from_params was passed a `params` object that was not a `Params`. This probably "
allennlp.common.checks.ConfigurationError: from_params was passed a `params` object that was not a `Params`. This probably indicates malformed parameters in a configuration file, where something that should have been a dictionary was actually a list, or something else. This happened when constructing an object of type <class 'allennlp.nn.regularizers.regularizer_applicator.RegularizerApplicator'>.
2020-05-16 17:17:20,338 - INFO - allennlp.models.archival - removing temporary unarchived model dir at /tmp/tmp9wjx6p7c
allennlp.common.checks.ConfigurationError: from_params was passed a `params` object that was not a `Params`.
```

**Comment by dirkgr** [comment]
That version of the model is very old. Where did you find it?

The latest one is https://storage.googleapis.com/allennlp-public-models/ner-model-2020.02.10.tar.gz.

**Comment by dirkgr** [comment]
That's a different model. The latest SRL model is https://storage.googleapis.com/allennlp-public-models/structured-prediction-srl-bert.2020.12.15.tar.gz.

I really want to know where you find those old links. Is there a place that we are forgetting to update?

**Comment by devdolapo** [comment]
Hello @dirkgr , I make use of this latest model, and I get this error

RuntimeError: The size of tensor a (1213) must match the size of tensor b (512) at non-singleton dimension 1

**Comment by dirkgr** [comment]
Can you show the complete command line you used?

Is this just the GitHub issue where everyone lands that runs an old model with new code?
