### ISSUE TITLE
List index out of range, training crf_tagger

### ISSUE THREAD

**Issue by Sneriko** [allenai/allennlp#4278]
Hi!

I'm new to AllenNLP and I'm trying to train the crf_tagger on a Swedish dataset called SUC3.0. I've converted this dataset to IOB1 format, and I'm using Swedish BERT embeddings, but when I train with the following config I get the error reported in the error log.

configFile:

{
  "data_loader": "allennlp.data.dataloader.DataLoader",
  "dataset_reader": {
    "type": "conll2003",
    "tag_label": "ner",
    "token_indexers": {
      "bert": {
          "type": "pretrained_transformer_mismatched",
          "model_name": "KB/bert-base-swedish-cased-ner"
      },
      "token_characters": {
        "type": "characters",
        "min_padding_length": 3
      }
    }
  },
  "train_data_path": "Data/Datasets/ner/SUC3testCONLL2003",
  "validation_data_path": "Data/Datasets/ner/SUC3testCONLL2003",
  "test_data_path": "Data/Datasets/ner/SUC3testCONLL2003",
  "model": {
    "type": "crf_tagger",
    "label_encoding": "IOB1",
    "constrain_crf_decoding": true,
    "calculate_span_f1": true,
    "dropout": 0.5,
    "include_start_end_transitions": false,
    "text_field_embedder": {
        "token_embedders": {
            "bert": {
                "type": "pretrained_transformer_mismatched",
                "model_name": "KB/bert-base-swedish-cased-ner"
            },
            "token_characters": {
                "type": "character_encoding",
                "embedding": {
                    "embedding_dim": 16
                },
                "encoder": {
                    "type": "cnn",
                    "embedding_dim": 16,
                    "num_filters": 128,
                    "ngram_filter_sizes": [3],
                    "conv_layer_activation": "relu"
                }
            }
        }
    },
    "encoder": {
        "type": "lstm",
        "input_size": 896,
        "hidden_size": 200,
        "num_layers": 2,
        "dropout": 0.5,
        "bidirectional": true
    }
  },
  "trainer": {
    "optimizer": {
        "type": "adam",
        "lr": 0.001
    },
    "validation_metric": "+f1-measure-overall",
    "num_epochs": 75,
    "grad_norm": 5.0,
    "patience": 25,
    "cuda_device": -1
  }
}

error log:

0it [00:00, ?it/s]
1643it [00:00, 16427.70it/s]
2966it [00:00, 15315.96it/s]
4640it [00:00, 15138.51it/s]
7427it [00:00, 15592.09it/s]
10717it [00:00, 18513.83it/s]
12528it [00:00, 16503.18it/s]
15419it [00:00, 18940.11it/s]
17321it [00:00, 17451.23it/s]

0it [00:00, ?it/s]
2737it [00:00, 27350.98it/s]
3882it [00:00, 12210.97it/s]
6827it [00:00, 14811.45it/s]
9978it [00:00, 17611.02it/s]
11902it [00:00, 12617.64it/s]
14969it [00:00, 15322.66it/s]
17321it [00:00, 18160.96it/s]

0it [00:00, ?it/s]
2559it [00:00, 6867.43it/s]
5552it [00:00, 8932.22it/s]
8397it [00:00, 11246.45it/s]
11827it [00:00, 14086.42it/s]
13964it [00:01, 9559.94it/s] 
16643it [00:01, 11845.02it/s]
17321it [00:01, 14620.30it/s]

0it [00:00, ?it/s]
1297it [00:00, 12965.93it/s]
2629it [00:00, 13068.33it/s]
4069it [00:00, 13440.87it/s]
6050it [00:00, 14872.45it/s]
7497it [00:00, 14746.57it/s]
9269it [00:00, 15526.86it/s]
11532it [00:00, 17138.10it/s]
13505it [00:00, 17838.56it/s]
15275it [00:00, 17063.83it/s]
16979it [00:01, 15981.36it/s]
18651it [00:01, 16195.16it/s]
20280it [00:01, 15528.02it/s]
21961it [00:01, 15890.07it/s]
23641it [00:01, 16152.50it/s]
25265it [00:01, 16069.90it/s]
27122it [00:01, 16745.93it/s]
29265it [00:01, 17920.78it/s]
31232it [00:01, 18411.47it/s]
33099it [00:01, 17252.30it/s]
34857it [00:02, 16704.73it/s]
36554it [00:02, 16452.15it/s]
38219it [00:02, 15552.72it/s]
40214it [00:02, 16651.26it/s]
41918it [00:02, 16055.40it/s]
43607it [00:02, 16296.74it/s]
45854it [00:02, 17760.19it/s]
47921it [00:02, 18541.55it/s]
49823it [00:02, 17669.39it/s]
51632it [00:03, 16596.40it/s]
51963it [00:03, 16795.84it/s]

  0%|          | 0/17321 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/sneriko/PycharmProjects/SpacySwedishModel/venv/bin/allennlp", line 11, in <module>
    load_entry_point('allennlp', 'console_scripts', 'allennlp')()
  File "/home/sneriko/PycharmProjects/SpacySwedishModel/allennlp/allennlp/__main__.py", line 19, in run
    main(prog="allennlp")
  File "/home/sneriko/PycharmProjects/SpacySwedishModel/allennlp/allennlp/commands/__init__.py", line 92, in main
    args.func(args)
  File "/home/sneriko/PycharmProjects/SpacySwedishModel/allennlp/allennlp/commands/train.py", line 112, in train_model_from_args
    dry_run=args.dry_run,
  File "/home/sneriko/PycharmProjects/SpacySwedishModel/allennlp/allennlp/commands/train.py", line 171, in train_model_from_file
    dry_run=dry_run,
  File "/home/sneriko/PycharmProjects/SpacySwedishModel/allennlp/allennlp/commands/train.py", line 234, in train_model
    dry_run=dry_run,
  File "/home/sneriko/PycharmProjects/SpacySwedishModel/allennlp/allennlp/commands/train.py", line 431, in _train_worker
    metrics = train_loop.run()
  File "/home/sneriko/PycharmProjects/SpacySwedishModel/allennlp/allennlp/commands/train.py", line 493, in run
    return self.trainer.train()
  File "/home/sneriko/PycharmProjects/SpacySwedishModel/allennlp/allennlp/training/trainer.py", line 732, in train
    train_metrics = self._train_epoch(epoch)
  File "/home/sneriko/PycharmProjects/SpacySwedishModel/allennlp/allennlp/training/trainer.py", line 500, in _train_epoch
    batch_outputs = self.batch_outputs(batch, for_training=True)
  File "/home/sneriko/PycharmProjects/SpacySwedishModel/allennlp/allennlp/training/trainer.py", line 406, in batch_outputs
    output_dict = self._pytorch_model(**batch)
  File "/home/sneriko/PycharmProjects/SpacySwedishModel/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sneriko/PycharmProjects/SpacySwedishModel/Models/allennlp-models/allennlp_models/ner/crf_tagger.py", line 207, in forward
    embedded_text_input = self.text_field_embedder(tokens)
  File "/home/sneriko/PycharmProjects/SpacySwedishModel/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sneriko/PycharmProjects/SpacySwedishModel/allennlp/allennlp/modules/text_field_embedders/basic_text_field_embedder.py", line 84, in forward
    token_vectors = embedder(list(tensors.values())[0], **forward_params_values)
  File "/home/sneriko/PycharmProjects/SpacySwedishModel/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sneriko/PycharmProjects/SpacySwedishModel/allennlp/allennlp/modules/token_embedders/token_characters_encoder.py", line 37, in forward
    return self._dropout(self._encoder(self._embedding(token_characters), mask))
  File "/home/sneriko/PycharmProjects/SpacySwedishModel/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sneriko/PycharmProjects/SpacySwedishModel/allennlp/allennlp/modules/time_distributed.py", line 52, in forward
    reshaped_outputs = self._module(*reshaped_inputs, **reshaped_kwargs)
  File "/home/sneriko/PycharmProjects/SpacySwedishModel/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sneriko/PycharmProjects/SpacySwedishModel/allennlp/allennlp/modules/token_embedders/embedding.py", line 198, in forward
    sparse=self.sparse,
  File "/home/sneriko/PycharmProjects/SpacySwedishModel/venv/lib/python3.7/site-packages/torch/nn/functional.py", line 1724, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self
  0%|          | 0/17321 [00:00<?, ?it/s]

Does anyone have any idea why I get this error? Like I said, it's the first time I try to train an AllenNLP model, so I might be making some stupid error.

**Comment by pvcastro** [comment]
Hi @Sneriko 
Which allennlp version are you using?
Try updating your config to this, according to [https://github.com/allenai/allennlp/releases/](https://github.com/allenai/allennlp/releases/):

> The TokenCharactersEncoder now requires you to specify the vocab_namespace for the underlying embedder. It used to default to "token_characters", matching the TokenCharactersIndexer default, but making that work required some custom magic that wasn't worth the complexity. So instead of "token_characters": {"type": "character_encoding", "embedding": {"embedding_dim": 25}, "encoder": {...}}, you need to change this to: "token_characters": {"type": "character_encoding", "embedding": {"embedding_dim": 25, "vocab_namespace": "token_characters"}, "encoder": {...}}

**Comment by Sneriko** [comment]
thank you very much for the reply, it worked nicely!

**Comment by pvcastro** [comment]
No problem.
Which versions of pytorch and allennlp are you running @Sneriko ?

**Comment by epwalsh** [comment]
Sounds like this is resolved? Please re-open if it isn't
