### ISSUE TITLE
Sentiment evaluate command fails on AllenNLP RC5

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp#4320]
This code snippet is available on our demo.

```
allennlp evaluate \
>     https://storage.googleapis.com/allennlp-public-models/sst-2-basic-classifier-glove-2019.06.27.tar.gz \
>     https://s3-us-west-2.amazonaws.com/allennlp/datasets/sst/dev.txt
2020-06-04 11:40:50,162 - INFO - transformers.file_utils - PyTorch version 1.5.0 available.
2020-06-04 11:40:50,817 - INFO - allennlp.models.archival - loading archive file https://storage.googleapis.com/allennlp-public-models/sst-2-basic-classifier-glove-2019.06.27.tar.gz from cache at /home/michaels/.allennlp/cache/020023ed51a1aa767d7d2c0fac738b3ac0784eb6db2702ec0e35b3611284a767.bb12d8472ca5c5337beb9ee41ef6ee16ac89136ba0e49091654fb76a9ea7f44f
2020-06-04 11:40:50,818 - INFO - allennlp.models.archival - extracting archive file /home/michaels/.allennlp/cache/020023ed51a1aa767d7d2c0fac738b3ac0784eb6db2702ec0e35b3611284a767.bb12d8472ca5c5337beb9ee41ef6ee16ac89136ba0e49091654fb76a9ea7f44f to temp dir /tmp/tmpzc_b8ch9
2020-06-04 11:40:51,089 - INFO - allennlp.data.vocabulary - Loading token dictionary from /tmp/tmpzc_b8ch9/vocabulary.
2020-06-04 11:40:51,279 - INFO - allennlp.common.checks - Pytorch version: 1.5.0
2020-06-04 11:40:51,280 - INFO - allennlp.commands.evaluate - Reading evaluation data from https://s3-us-west-2.amazonaws.com/allennlp/datasets/sst/dev.txt
0it [00:00, ?it/s]2020-06-04 11:40:51,350 - INFO - allennlp.common.file_utils - https://s3-us-west-2.amazonaws.com/allennlp/datasets/sst/dev.txt not found in cache, downloading to /tmp/tmpmb5jiyiq
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 280825/280825 [00:00<00:00, 5887943.44B/s]
2020-06-04 11:40:51,490 - INFO - allennlp.common.file_utils - copying /tmp/tmpmb5jiyiq to cache at /home/michaels/.allennlp/cache/a7f3236709afd54d8a52df413be2892c0fd15416570a33228b65ee62d354ef82.45cca2e5ec407e60a4e09e08a8be4e1d8457b9a63fa3e2a9c236e7475e92b5cf
2020-06-04 11:40:51,491 - INFO - allennlp.common.file_utils - creating metadata file for /home/michaels/.allennlp/cache/a7f3236709afd54d8a52df413be2892c0fd15416570a33228b65ee62d354ef82.45cca2e5ec407e60a4e09e08a8be4e1d8457b9a63fa3e2a9c236e7475e92b5cf
2020-06-04 11:40:51,491 - INFO - allennlp.common.file_utils - removing temp file /tmp/tmpmb5jiyiq
2020-06-04 11:40:51,491 - INFO - allennlp_models.classification.dataset_readers.stanford_sentiment_tree_bank - Reading instances from lines in file at: https://s3-us-west-2.amazonaws.com/allennlp/datasets/sst/dev.txt
872it [00:00, 2535.57it/s]
Traceback (most recent call last):
  File "/home/michaels/miniconda2/envs/allennlp-rc5/lib/python3.7/site-packages/allennlp/common/params.py", line 237, in pop
    value = self.params.pop(key)
KeyError: 'data_loader'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/michaels/miniconda2/envs/allennlp-rc5/bin/allennlp", line 8, in <module>
    sys.exit(run())
  File "/home/michaels/miniconda2/envs/allennlp-rc5/lib/python3.7/site-packages/allennlp/__main__.py", line 19, in run
    main(prog="allennlp")
  File "/home/michaels/miniconda2/envs/allennlp-rc5/lib/python3.7/site-packages/allennlp/commands/__init__.py", line 92, in main
    args.func(args)
  File "/home/michaels/miniconda2/envs/allennlp-rc5/lib/python3.7/site-packages/allennlp/commands/evaluate.py", line 136, in evaluate_from_args
    data_loader_params = config.pop("data_loader")
  File "/home/michaels/miniconda2/envs/allennlp-rc5/lib/python3.7/site-packages/allennlp/common/params.py", line 242, in pop
    raise ConfigurationError(msg)
allennlp.common.checks.ConfigurationError: key "data_loader" is required
2020-06-04 11:40:51,624 - INFO - allennlp.models.archival - removing temporary unarchived model dir at /tmp/tmpzc_b8ch9
```

**Comment by dirkgr** [comment]
`sst-2-basic-classifier-glove-2019.06.27.tar.gz` is quite old and should not be in the demo. We should use a newer RoBERTa-based one.

I tried the latest RoBERTa based on that's online, and it fails with the same error.

I can probably just update the model config, but I wanted to make sure this still trains properly anyways, so I started a training run on allennlp-server3, and it that gives me a reasonable score, we'll make that the model in the demo.

**Comment by dirkgr** [comment]
It looks like the demo has both a RoBERTa based one and an LSTM. So now I'm updating both.
