### ISSUE TITLE
Can't run allennlp-server in 1.0.0 rc6

### ISSUE THREAD

**Issue by YKX-A** [allenai/allennlp#4345]
environment
```
allennlp                       1.0.0rc6
allennlp-models                1.0.0rc6
allennlp-reading-comprehension 0.0.1-unreleased
allennlp-server                1.0.0-unreleased    
```

My target is to run a **simple server (web demo)**, like [this](https://github.com/YKX-A/allennlp_0.9.1_bk/blob/master/docs/tutorials/getting_started/predicting_paper_venues/predicting_paper_venues_pt2.md#running-a-web-demo). Following the installing guide on https://github.com/allenai/allennlp-server, **I can't see `configure ` and `serve` in `allennlp` command.**
```
➜ allennlp
2020-06-09 13:20:34,347 - INFO - transformers.file_utils - PyTorch version 1.5.0 available.
usage: allennlp [-h] [--version]  ...

Run AllenNLP

optional arguments:
  -h, --help     show this help message and exit
  --version      show program's version number and exit

Commands:

    evaluate     Evaluate the specified model + dataset.
    find-lr      Find a learning rate range.
    predict      Use a trained model to make predictions.
    print-results
                 Print results from allennlp serialization directories to the
                 console.
    test-install
                 Test AllenNLP installation.
    train        Train a model.
```

I try another approach:
```
➜ python allennlp_server/commands/server_simple.py
Traceback (most recent call last):
  File "allennlp_server/commands/server_simple.py", line 168, in <module>
    class SimpleServer(Subcommand):
  File "/Users/ykx/anaconda3/envs/allennlp_server2/lib/python3.7/site-packages/allennlp/commands/subcommand.py", line 40, in add_name_to_reverse_registry
    subclass = super_register_fn(subclass)
  File "/Users/ykx/anaconda3/envs/allennlp_server2/lib/python3.7/site-packages/allennlp/common/registrable.py", line 123, in add_subclass_to_registry
    raise ConfigurationError(message)
allennlp.common.checks.ConfigurationError: Cannot register serve as Subcommand; name already in use for SimpleServer
```
So, is there any matched `allennlp` and`annennlp-serve` version that I can run, or any other approach I can finish the demo?
Thanks for your suggestions.

**Comment by schmmd** [comment]
Closing, as we believe this is fixed.
