### ISSUE TITLE
allennlp.commands.elmo doesn't exists anymore

### ISSUE THREAD

**Issue by Dastgheyb** [allenai/allennlp#4384]
Hi :)
last weak my code works on the colab. but now after I install allennlp I get an error on the following line.
`from allennlp.commands.elmo import ElmoEmbedder`
and the error is : ModuleNotFoundError: No module named 'allennlp.commands.elmo'
I searched this repository for ElmoEmbedder but none found.

**Comment by schmmd** [comment]
We removed this command in v1.0.  If you want to use the `elmo` command then you need to check out v0.9.0.  We removed this command because `elmo` is becoming a bit old and we didn't think it made sense to continue supporting it as a top-level command.

What are you trying to do specifically?  You might still be able to accomplish your goals in 1.0, but I'm not sure exactly what you're trying to do.

**Comment by Dastgheyb** [comment]
I am just playing with the code which I took from https://github.com/ohyicong/glove_elmo/blob/master/main.py and using the output of this code for another network that I have created.

**Comment by Dastgheyb** [comment]
> We removed the `elmo` command in v1.0. If you want to use the `elmo` command then you need to check out v0.9.0. We removed this command because `elmo` is becoming a bit old and we didn't think it made sense to continue supporting it as a top-level command.

version 0.9.0 worked fine. thx.

**Comment by mchari** [comment]
Hi,
  How can I get the embed_sentence() functionality in v1.0 ?

Thanks!

**Comment by schmmd** [comment]
That functionality does not exist in 1.0, although you could copy the code that provided this into your code without too much work.  See https://github.com/allenai/allennlp/blob/v0.9.0/allennlp/commands/elmo.py#L213.

**Comment by mchari** [comment]
Great ! I'll give it a try.

My real goal is to get sentence embeddings in a bilm-tf environment, where I have incrementally trained an Elmo model.

**Comment by TITC** [comment]
> > We removed the `elmo` command in v1.0. If you want to use the `elmo` command then you need to check out v0.9.0. We removed this command because `elmo` is becoming a bit old and we didn't think it made sense to continue supporting it as a top-level command.
> 
> version 0.9.0 worked fine. thx.

version 0.9.0 not work for me,  any advice is welcome
```
Traceback (most recent call last):
  File "/content/sow-reap-paraphrasing/processing/get_elmo_embeds.py", line 1, in <module>
    from allennlp.commands.elmo import ElmoEmbedder
  File "/usr/local/lib/python3.7/dist-packages/allennlp/commands/__init__.py", line 8, in <module>
    from allennlp.commands.configure import Configure
  File "/usr/local/lib/python3.7/dist-packages/allennlp/commands/configure.py", line 26, in <module>
    from allennlp.service.config_explorer import make_app
  File "/usr/local/lib/python3.7/dist-packages/allennlp/service/config_explorer.py", line 24, in <module>
    from allennlp.common.configuration import configure, choices
  File "/usr/local/lib/python3.7/dist-packages/allennlp/common/configuration.py", line 17, in <module>
    from allennlp.data.dataset_readers import DatasetReader
  File "/usr/local/lib/python3.7/dist-packages/allennlp/data/__init__.py", line 1, in <module>
    from allennlp.data.dataset_readers.dataset_reader import DatasetReader
  File "/usr/local/lib/python3.7/dist-packages/allennlp/data/dataset_readers/__init__.py", line 10, in <module>
    from allennlp.data.dataset_readers.ccgbank import CcgBankDatasetReader
  File "/usr/local/lib/python3.7/dist-packages/allennlp/data/dataset_readers/ccgbank.py", line 9, in <module>
    from allennlp.data.dataset_readers.dataset_reader import DatasetReader
  File "/usr/local/lib/python3.7/dist-packages/allennlp/data/dataset_readers/dataset_reader.py", line 8, in <module>
    from allennlp.data.instance import Instance
  File "/usr/local/lib/python3.7/dist-packages/allennlp/data/instance.py", line 3, in <module>
    from allennlp.data.fields.field import DataArray, Field
  File "/usr/local/lib/python3.7/dist-packages/allennlp/data/fields/__init__.py", line 7, in <module>
    from allennlp.data.fields.array_field import ArrayField
  File "/usr/local/lib/python3.7/dist-packages/allennlp/data/fields/array_field.py", line 10, in <module>
    class ArrayField(Field[numpy.ndarray]):
  File "/usr/local/lib/python3.7/dist-packages/allennlp/data/fields/array_field.py", line 50, in ArrayField
    @overrides
  File "/usr/local/lib/python3.7/dist-packages/overrides/overrides.py", line 88, in overrides
    return _overrides(method, check_signature, check_at_runtime)
  File "/usr/local/lib/python3.7/dist-packages/overrides/overrides.py", line 114, in _overrides
    _validate_method(method, super_class, check_signature)
  File "/usr/local/lib/python3.7/dist-packages/overrides/overrides.py", line 135, in _validate_method
    ensure_signature_is_compatible(super_method, method, is_static)
  File "/usr/local/lib/python3.7/dist-packages/overrides/signature.py", line 93, in ensure_signature_is_compatible
    ensure_return_type_compatibility(super_type_hints, sub_type_hints, method_name)
  File "/usr/local/lib/python3.7/dist-packages/overrides/signature.py", line 288, in ensure_return_type_compatibility
    f"{method_name}: return type `{sub_return}` is not a `{super_return}`."
TypeError: ArrayField.empty_field: return type `None` is not a `<class 'allennlp.data.fields.field.Field'>`.
```
