### ISSUE TITLE
allennlp.common.checks.ConfigurationError: key "token_embedders" is required at location "model.text_field_embedder."

### ISSUE THREAD

**Issue by 563017732** [allenai/allennlp#4442]
**Describe the bug**

I0706 10:33:02.516595 140677189486400 archival.py:171] extracting archive file /home/jiawen/.allennlp/cache/60c14844468543e4329ce7e8d3444fa1f9f7057b4b0de5b3f4a597eb57113d32.73aa20bab6336a582588814d8458d040b59536ca1f60b6a769a2da61c7aa3c9a to temp dir /tmp/tmp15lrx2nb
I0706 10:33:06.706750 140677189486400 params.py:247] type = from_instances
I0706 10:33:06.706835 140677189486400 vocabulary.py:323] Loading token dictionary from /tmp/tmp15lrx2nb/vocabulary.
I0706 10:33:06.706987 140677189486400 filelock.py:274] Lock 140674091466936 acquired on /tmp/tmp15lrx2nb/vocabulary/.lock
I0706 10:33:06.707335 140677189486400 filelock.py:318] Lock 140674091466936 released on /tmp/tmp15lrx2nb/vocabulary/.lock
I0706 10:33:06.707670 140677189486400 params.py:247] model.type = constituency_parser
I0706 10:33:06.707974 140677189486400 params.py:247] model.regularizer = None
I0706 10:33:06.708117 140677189486400 params.py:247] model.text_field_embedder.type = basic
Traceback (most recent call last):
  File "/home/jiawen/anaconda3/envs/esim/lib/python3.6/site-packages/allennlp/common/params.py", line 237, in pop
    value = self.params.pop(key)
KeyError: 'token_embedders'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/scripts/athene/pipeline.py", line 193, in <module>
    document_retrieval(logger, args.mode)
  File "src/scripts/athene/pipeline.py", line 163, in document_retrieval
    Config.document_add_claim, Config.document_parallel)
  File "/home/jiawen/Documents/Code/Code/fact_checking/ESIM/src/athene/retrieval/document/docment_retrieval.py", line 194, in main
    method = Doc_Retrieval(database_path=db_file, add_claim=add_claim, k_wiki_results=k_wiki)
  File "/home/jiawen/Documents/Code/Code/fact_checking/ESIM/src/athene/retrieval/document/docment_retrieval.py", line 47, in __init__
    self.predictor = Predictor.from_path("https://s3-us-west-2.amazonaws.com/allennlp/models/elmo-constituency-parser-2018.03.14.tar.gz")
  File "/home/jiawen/anaconda3/envs/esim/lib/python3.6/site-packages/allennlp/predictors/predictor.py", line 275, in from_path
    load_archive(archive_path, cuda_device=cuda_device),
  File "/home/jiawen/anaconda3/envs/esim/lib/python3.6/site-packages/allennlp/models/archival.py", line 197, in load_archive
    opt_level=opt_level,
  File "/home/jiawen/anaconda3/envs/esim/lib/python3.6/site-packages/allennlp/models/model.py", line 398, in load
    return model_class._load(config, serialization_dir, weights_file, cuda_device, opt_level)
  File "/home/jiawen/anaconda3/envs/esim/lib/python3.6/site-packages/allennlp/models/model.py", line 295, in _load
    model = Model.from_params(vocab=vocab, params=model_params)
  File "/home/jiawen/anaconda3/envs/esim/lib/python3.6/site-packages/allennlp/common/from_params.py", line 580, in from_params
    **extras,
  File "/home/jiawen/anaconda3/envs/esim/lib/python3.6/site-packages/allennlp/common/from_params.py", line 609, in from_params
    kwargs = create_kwargs(constructor_to_inspect, cls, params, **extras)
  File "/home/jiawen/anaconda3/envs/esim/lib/python3.6/site-packages/allennlp/common/from_params.py", line 181, in create_kwargs
    cls.__name__, param_name, annotation, param.default, params, **extras
  File "/home/jiawen/anaconda3/envs/esim/lib/python3.6/site-packages/allennlp/common/from_params.py", line 287, in pop_and_construct_arg
    return construct_arg(class_name, name, popped_params, annotation, default, **extras)
  File "/home/jiawen/anaconda3/envs/esim/lib/python3.6/site-packages/allennlp/common/from_params.py", line 321, in construct_arg
    return annotation.from_params(params=popped_params, **subextras)
  File "/home/jiawen/anaconda3/envs/esim/lib/python3.6/site-packages/allennlp/common/from_params.py", line 580, in from_params
    **extras,
  File "/home/jiawen/anaconda3/envs/esim/lib/python3.6/site-packages/allennlp/common/from_params.py", line 609, in from_params
    kwargs = create_kwargs(constructor_to_inspect, cls, params, **extras)
  File "/home/jiawen/anaconda3/envs/esim/lib/python3.6/site-packages/allennlp/common/from_params.py", line 181, in create_kwargs
    cls.__name__, param_name, annotation, param.default, params, **extras
  File "/home/jiawen/anaconda3/envs/esim/lib/python3.6/site-packages/allennlp/common/from_params.py", line 280, in pop_and_construct_arg
    popped_params = params.pop(name, default) if default != _NO_DEFAULT else params.pop(name)
  File "/home/jiawen/anaconda3/envs/esim/lib/python3.6/site-packages/allennlp/common/params.py", line 242, in pop
    raise ConfigurationError(msg)
allennlp.common.checks.ConfigurationError: key "token_embedders" is required at location "model.text_field_embedder."
I0706 10:33:06.710113 140677189486400 archival.py:205] removing temporary unarchived model dir at /tmp/tmp15lrx2nb

**Comment by matt-gardner** [comment]
You're using an old model that is not compatible with allennlp 1.0.  An updated model can be found here: https://storage.googleapis.com/allennlp-public-models/elmo-constituency-parser-2020.02.10.tar.gz.

**Comment by 563017732** [comment]
> You're using an old model that is not compatible with allennlp 1.0. An updated model can be found here: https://storage.googleapis.com/allennlp-public-models/elmo-constituency-parser-2020.02.10.tar.gz.

Thank you so much, it works.
