### ISSUE TITLE
Missing 'allennlp.data.fields.production_rule_field' in allennlp-1.0.0

### ISSUE THREAD

**Issue by madcpt** [allenai/allennlp#4452]
## Checklist

- [x] I have verified that the issue exists against the `master` branch of AllenNLP.
- [x] I have read the relevant section in the [contribution guide](https://github.com/allenai/allennlp/blob/master/CONTRIBUTING.md#bug-fixes-and-new-features) on reporting bugs.
- [x] I have checked the [issues list](https://github.com/allenai/allennlp/issues) for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/allenai/allennlp/pulls) for existing proposed fixes.
- [x] I have checked the [CHANGELOG](https://github.com/allenai/allennlp/blob/master/CHANGELOG.md) and the [commit log](https://github.com/allenai/allennlp/commits/master) to find out if the bug was already fixed in the master branch.
- [x] I have included in the "Description" section below a traceback from any exceptions related to this bug.
- [x] I have included in the "Related issues or possible duplicates" section beloew all related issues and possible duplicate issues (If there are none, check this box anyway).
- [x] I have included in the "Environment" section below the name of the operating system and Python version that I was using when I discovered this bug.
- [x] I have included in the "Environment" section below the output of `pip freeze`.
- [x] I have included in the "Steps to reproduce" section below a minimally reproducible example.

## Description

<details>
<summary><b>Python traceback:</b></summary>
<p>

```
Traceback (most recent call last):
  File "/home/zihan/.local/bin/allennlp", line 11, in <module>
    sys.exit(run())
  File "/home/zihan/.local/lib/python3.6/site-packages/allennlp/__main__.py", line 19, in run
    main(prog="allennlp")
  File "/home/zihan/.local/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 91, in main
    import_module_and_submodules(package_name)
  File "/home/zihan/.local/lib/python3.6/site-packages/allennlp/common/util.py", line 340, in import_module_and_submodules
    module = importlib.import_module(package_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/mnt/d/projects/spider-schema-gnn-global/dataset_readers/spider.py", line 10, in <module>
    from allennlp.data.fields.production_rule_field import ProductionRuleField
ModuleNotFoundError: No module named 'allennlp.data.fields.production_rule_field'
```

</p>
</details>

## Related issues or possible duplicates

- None

## Environment

OS: Linux

Python version: 3.6.1

<details>
<summary><b>Output of <code>pip freeze</code>:</b></summary>
<p>

```
allennlp (1.0.0)
asn1crypto (0.24.0)
attrs (17.4.0)
Automat (0.6.0)
beautifulsoup4 (4.9.1)
blinker (1.4)
blis (0.4.1)
boto3 (1.14.18)
botocore (1.17.18)
catalogue (1.0.0)
certifi (2020.6.20)
chardet (3.0.4)
cheroot (8.3.0)
CherryPy (18.6.0)
click (7.1.2)
cloud-init (19.4)
colorama (0.3.7)
command-not-found (0.3)
configobj (5.0.6)
constantly (15.1.0)
contextvars (2.4)
cryptography (2.1.4)
cymem (2.0.3)
dataclasses (0.7)
decorator (4.4.2)
dill (0.3.2)
distro-info (0.18ubuntu0.18.04.1)
docutils (0.15.2)
docx (0.2.4)
en-core-web-sm (2.0.0)
feedparser (5.2.1)
filelock (3.0.12)
flake8 (3.8.3)
future (0.18.2)
h5py (2.10.0)
httplib2 (0.9.2)
hyperlink (17.3.1)
idna (2.10)
immutables (0.14)
importlib-metadata (1.7.0)
importlib-resources (3.0.0)
incremental (16.10.1)
isodate (0.6.0)
jaraco.classes (3.1.0)
jaraco.collections (3.0.0)
jaraco.functools (3.0.1)
jaraco.text (3.2.0)
Jinja2 (2.10)
jmespath (0.10.0)
joblib (0.16.0)
jsonpatch (1.16)
jsonpickle (1.4.1)
jsonpointer (1.10)
jsonschema (2.6.0)
keyring (10.6.0)
keyrings.alt (3.0)
language-selector (0.1)
lxml (4.5.1)
MarkupSafe (1.0)
mccabe (0.6.1)
more-itertools (8.4.0)
murmurhash (1.0.2)
netifaces (0.10.4)
networkx (2.4)
nltk (3.5)
numpy (1.19.0)
oauthlib (2.0.6)
ordered-set (4.0.2)
overrides (3.1.0)
packaging (20.4)
PAM (0.4.2)
pandas (1.0.5)
pattern3 (3.0.0)
pdfminer.six (20200517)
pdfminer3k (1.3.4)
Pillow (7.2.0)
pip (9.0.1)
plac (1.1.3)
ply (3.11)
plyfile (0.7.2)
portend (2.6)
preshed (3.0.2)
protobuf (3.12.2)
pyasn1 (0.4.2)
pyasn1-modules (0.2.1)
pycodestyle (2.6.0)
pycrypto (2.6.1)
pycryptodome (3.9.8)
pydantic (1.5.1)
pyflakes (2.2.0)
pygobject (3.26.1)
PyJWT (1.5.3)
pyOpenSSL (17.5.0)
pyparsing (2.4.7)
pyserial (3.4)
python-apt (1.6.5+ubuntu0.2)
python-dateutil (2.8.1)
python-debian (0.1.32)
pytz (2020.1)
pyxdg (0.25)
PyYAML (3.12)
rdflib (5.0.0)
regex (2020.6.8)
requests (2.24.0)
requests-unixsocket (0.1.5)
s3transfer (0.3.3)
sacremoses (0.0.43)
scikit-learn (0.23.1)
scipy (1.5.1)
SecretStorage (2.3.1)
sentencepiece (0.1.91)
service-identity (16.0.0)
setuptools (49.1.0)
simplejson (3.17.0)
six (1.15.0)
sortedcontainers (2.2.2)
soupsieve (2.0.1)
spacy (3.0.0a0)
srsly (2.2.0)
ssh-import-id (5.7)
systemd-python (234)
tempora (3.0.0)
tensorboardX (2.1)
thinc (8.0.0a11)
threadpoolctl (2.1.0)
tokenizers (0.8.1rc1)
torch (1.5.0+cpu)
torch-cluster (1.3.0)
torch-geometric (1.2.1)
torch-scatter (1.2.0)
torch-sparse (0.4.3)
tqdm (4.47.0)
transformers (3.0.2)
Twisted (17.9.0)
typer (0.3.0)
typing-extensions (3.7.4.2)
ufw (0.36)
unattended-upgrades (0.1)
urllib3 (1.25.9)
wasabi (0.7.0)
wheel (0.30.0)
zc.lockfile (2.0)
zipp (3.1.0)
zope.interface (4.3.2)
```

</p>
</details>

## Steps to reproduce

<details>
<summary><b>Example source:</b></summary>
<p>

```
```

</p>
</details>

**Comment by madcpt** [comment]
Finally, I found the explanations here #3625, so this is not a bug.
Looking forward to `allennlp_semparse`!

**Comment by matt-gardner** [comment]
Not sure what you meant by "looking forward", but just in case you didn't know, that repo is available here: https://github.com/allenai/allennlp-semparse.

**Comment by madcpt** [comment]
Really nice work! I thought `allennlp-semparse` would become a sub-module of `allennlp`, did not realize it is a separated package.
