### ISSUE TITLE
not support python3.8

### ISSUE THREAD

**Issue by linpan** [allenai/allennlp#4464]
bug: 
 Downloading http://mirrors.aliyun.com/pypi/packages/c6/27/07b57d22496ed6c98b247e578712122402487f5c265ec70a747900f97060/gluonnlp-0.9.1.tar.gz (252 kB)
     |████████████████████████████████| 252 kB 317 kB/s 
    ERROR: Command errored out with exit status 1:
     command: /Users/rct/.pyenv/versions/3.8-dev/envs/env-3.8/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/9_/vtg8g16x3ln1lw6yw96rqst80000gn/T/pip-install-lev8or49/gluonnlp/setup.py'"'"'; __file__='"'"'/private/var/folders/9_/vtg8g16x3ln1lw6yw96rqst80000gn/T/pip-install-lev8or49/gluonnlp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/9_/vtg8g16x3ln1lw6yw96rqst80000gn/T/pip-pip-egg-info-z2950nce
         cwd: /private/var/folders/9_/vtg8g16x3ln1lw6yw96rqst80000gn/T/pip-install-lev8or49/gluonnlp/
    Complete output (34 lines):
    WARNING: The wheel package is not available.
    WARNING: The repository located at mirrors.aliyun.com is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host mirrors.aliyun.com'.
    ERROR: Could not find a version that satisfies the requirement cython (from versions: none)
    ERROR: No matching distribution found for cython
    Traceback (most recent call last):
      File "/Users/rct/.pyenv/versions/3.8-dev/envs/env-3.8/lib/python3.8/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/Users/rct/.pyenv/versions/3.8-dev/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/Users/rct/.pyenv/versions/3.8-dev/envs/env-3.8/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/9_/vtg8g16x3ln1lw6yw96rqst80000gn/T/tmptdb_jxqw', '--quiet', 'cython']' returned non-zero exit status 1.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/9_/vtg8g16x3ln1lw6yw96rqst80000gn/T/pip-install-lev8or49/gluonnlp/setup.py", line 37, in <module>
        setup(
      File "/Users/rct/.pyenv/versions/3.8-dev/envs/env-3.8/lib/python3.8/site-packages/setuptools/__init__.py", line 143, in setup
        _install_setup_requires(attrs)
      File "/Users/rct/.pyenv/versions/3.8-dev/envs/env-3.8/lib/python3.8/site-packages/setuptools/__init__.py", line 138, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/Users/rct/.pyenv/versions/3.8-dev/envs/env-3.8/lib/python3.8/site-packages/setuptools/dist.py", line 695, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/Users/rct/.pyenv/versions/3.8-dev/envs/env-3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 781, in resolve
        dist = best[req.key] = env.best_match(
      File "/Users/rct/.pyenv/versions/3.8-dev/envs/env-3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1066, in best_match
        return self.obtain(req, installer)
      File "/Users/rct/.pyenv/versions/3.8-dev/envs/env-3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1078, in obtain
        return installer(requirement)
      File "/Users/rct/.pyenv/versions/3.8-dev/envs/env-3.8/lib/python3.8/site-packages/setuptools/dist.py", line 754, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/Users/rct/.pyenv/versions/3.8-dev/envs/env-3.8/lib/python3.8/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e))
    distutils.errors.DistutilsError: Command '['/Users/rct/.pyenv/versions/3.8-dev/envs/env-3.8/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/9_/vtg8g16x3ln1lw6yw96rqst80000gn/T/tmptdb_jxqw', '--quiet', 'cython']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by bratao** [comment]
I think you sent to the wrong project. The error you have is related to the gluonnlp

**Comment by dirkgr** [comment]
OP didn't bother even formatting the input to be readable. I'm closing this. Feel free to reopen if there is a real problem.
