### ISSUE TITLE
Iterators ➔ DataLoaders v1.0 upgrade: key "sampler" is required at location data_loader.batch_sampler

### ISSUE THREAD

**Issue by iamsaurabhc** [allenai/allennlp#4520]
## Checklist

- [ x] I have verified that the issue exists against the `master` branch of AllenNLP.
- [ x] I have read the relevant section in the [contribution guide](https://github.com/allenai/allennlp/blob/master/CONTRIBUTING.md#bug-fixes-and-new-features) on reporting bugs.
- [ x] I have checked the [issues list](https://github.com/allenai/allennlp/issues) for similar or identical bug reports.
- [x ] I have checked the [pull requests list](https://github.com/allenai/allennlp/pulls) for existing proposed fixes.
- [ x] I have checked the [CHANGELOG](https://github.com/allenai/allennlp/blob/master/CHANGELOG.md) and the [commit log](https://github.com/allenai/allennlp/commits/master) to find out if the bug was already fixed in the master branch.
- [ ] I have included in the "Description" section below a traceback from any exceptions related to this bug.
- [ x] I have included in the "Related issues or possible duplicates" section beloew all related issues and possible duplicate issues (If there are none, check this box anyway).
- [ ] I have included in the "Environment" section below the name of the operating system and Python version that I was using when I discovered this bug.
- [ ] I have included in the "Environment" section below the output of `pip freeze`.
- [ ] I have included in the "Steps to reproduce" section below a minimally reproducible example.

## Description

<details>
<summary><b>Python traceback:</b></summary>
<p>

```
'!! Traceback (most recent call last):\n!!   File "/home/saurabh/botml/allennlp/lib/python3.7/site-packages/allennlp/common/params.py", line 237, in pop\n    value = self.params.pop(key)\n!! KeyError: \'sampler\'\n!! \nDuring handling of the above exception, another exception occurred:\n\n!! Traceback (most recent call last):\n!!   File "/home/saurabh/botml/botml/common/sherlock.py", line 43, in wrap\n    status.result = func(*args, **kwargs)\n!!   File "/home/saurabh/botml/botml/botai/api.py", line 104, in train\n    model = allentrain.train_model(params, ser_file)\n!!   File "/home/saurabh/botml/allennlp/lib/python3.7/site-packages/allennlp/commands/train.py", line 230, in train_model\n    dry_run=dry_run,\n!!   File "/home/saurabh/botml/allennlp/lib/python3.7/site-packages/allennlp/commands/train.py", line 418, in _train_worker\n    params=params, serialization_dir=serialization_dir, local_rank=process_rank,\n!!   File "/home/saurabh/botml/allennlp/lib/python3.7/site-packages/allennlp/common/from_params.py", line 580, in from_params\n    **extras,\n!!   File "/home/saurabh/botml/allennlp/lib/python3.7/site-packages/allennlp/common/from_params.py", line 611, in from_params\n    return constructor_to_call(**kwargs)  # type: ignore\n!!   File "/home/saurabh/botml/allennlp/lib/python3.7/site-packages/allennlp/commands/train.py", line 646, in from_partial_objects\n    data_loader_ = data_loader.construct(dataset=datasets["train"])\n!!   File "/home/saurabh/botml/allennlp/lib/python3.7/site-packages/allennlp/common/lazy.py", line 46, in construct\n    return self._constructor(**kwargs)\n!!   File "/home/saurabh/botml/allennlp/lib/python3.7/site-packages/allennlp/common/from_params.py", line 446, in constructor\n    return value_cls.from_params(params=deepcopy(popped_params), **constructor_extras)\n!!   File "/home/saurabh/botml/allennlp/lib/python3.7/site-packages/allennlp/common/from_params.py", line 580, in from_params\n    **extras,\n!!   File "/home/saurabh/botml/allennlp/lib/python3.7/site-packages/allennlp/common/from_params.py", line 611, in from_params\n    return constructor_to_call(**kwargs)  # type: ignore\n!!   File "/home/saurabh/botml/allennlp/lib/python3.7/site-packages/allennlp/data/dataloader.py", line 127, in from_partial_objects\n    batch_sampler_ = batch_sampler.construct(data_source=dataset)\n!!   File "/home/saurabh/botml/allennlp/lib/python3.7/site-packages/allennlp/common/lazy.py", line 46, in construct\n    return self._constructor(**kwargs)\n!!   File "/home/saurabh/botml/allennlp/lib/python3.7/site-packages/allennlp/common/from_params.py", line 446, in constructor\n    return value_cls.from_params(params=deepcopy(popped_params), **constructor_extras)\n!!   File "/home/saurabh/botml/allennlp/lib/python3.7/site-packages/allennlp/common/from_params.py", line 580, in from_params\n    **extras,\n!!   File "/home/saurabh/botml/allennlp/lib/python3.7/site-packages/allennlp/common/from_params.py", line 609, in from_params\n    kwargs = create_kwargs(constructor_to_inspect, cls, params, **extras)\n!!   File "/home/saurabh/botml/allennlp/lib/python3.7/site-packages/allennlp/common/from_params.py", line 181, in create_kwargs\n    cls.__name__, param_name, annotation, param.default, params, **extras\n!!   File "/home/saurabh/botml/allennlp/lib/python3.7/site-packages/allennlp/common/from_params.py", line 280, in pop_and_construct_arg\n    popped_params = params.pop(name, default) if default != _NO_DEFAULT else params.pop(name)\n!!   File "/home/saurabh/botml/allennlp/lib/python3.7/site-packages/allennlp/common/params.py", line 242, in pop\n    raise ConfigurationError(msg)\n!! allennlp.common.checks.ConfigurationError: key "sampler" is required at location "data_loader.batch_sampler."\n'
```

</p>
</details>

## Related issues or possible duplicates

- None

## Environment

OS: Ubuntu 18.04

Python version: 3.7.8

<details>
<summary><b>Output of <code>pip freeze</code>:</b></summary>
<p>

```
aiohttp==3.4.4
allennlp==1.0.0
allennlp-models==1.0.0
APScheduler==3.6.3
astroid==2.1.0
async-timeout==3.0.1
attrs==19.3.0
azure-common==1.1.25
azure-cosmosdb-nspkg==2.0.2
azure-cosmosdb-table==1.0.3
azure-nspkg==3.0.2
azure-storage==0.34.3
azure-storage-common==1.1.0
azure-storage-nspkg==3.1.0
beautifulsoup4==4.9.0
blis==0.4.1
-e git+finons@vs-ssh.visualstudio.com:v3/finons/BMML/botml@cdfaae98ee6019ee90171079d8f3694796cc1bd4#egg=botml
boto==2.49.0
boto3==1.14.28
botocore==1.17.28
breadability==0.1.20
catalogue==1.0.0
certifi==2020.6.20
cffi==1.14.0
chardet==3.0.4
click==7.1.2
conllu==3.0
coverage==4.5.1
cryptography==3.0
cssselect==1.1.0
cymem==2.0.3
Cython==0.29.16
dill==0.2.7.1
docopt==0.6.2
docutils==0.15.2
en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.5/en_core_web_sm-2.2.5.tar.gz
feedfinder2==0.0.4
feedparser==5.2.1
filelock==3.0.12
Flask==1.0.2
Flask-Cors==3.0.8
future==0.18.2
futures==3.1.1
gensim==3.8.2
gevent==1.5.0
greenlet==0.4.16
h5py==2.10.0
html5lib==1.0.1
idna==2.6
importlib-metadata==1.7.0
isort==4.3.21
itsdangerous==1.1.0
jieba3k==0.35.1
Jinja2==2.11.2
jmespath==0.10.0
joblib==0.11
jsonnet==0.16.0
jsonpickle==1.4.1
lazy-object-proxy==1.5.1
lightgbm==2.0.4
lxml==4.5.0
MarkupSafe==1.1.1
mccabe==0.6.1
more-itertools==8.4.0
multidict==4.7.6
murmurhash==1.0.2
newspaper3k==0.2.8
nltk==3.5
nose==1.3.7
numpy==1.18.3
overrides==3.0.0
packaging==20.4
pandas==1.0.3
Pillow==7.2.0
pkg-resources==0.0.0
plac==1.1.3
pluggy==0.13.1
preshed==3.0.2
protobuf==3.12.2
psutil==5.7.0
py==1.9.0
py-rouge==1.1
pycparser==2.20
pylint==2.4.4
pymongo==3.10.1
pyparsing==2.4.7
pytest==5.4.1
pytest-cov==2.8.1
python-dateutil==2.8.1
pytz==2017.3
PyYAML==5.3.1
regex==2020.7.14
requests==2.18.4
requests-file==1.5.1
s3transfer==0.3.3
sacremoses==0.0.43
scikit-learn==0.20.3
scipy==1.4.1
sentencepiece==0.1.91
six==1.15.0
slackclient==1.2.1
smart-open==2.1.0
soupsieve==2.0.1
spacy==2.2.4
srsly==1.0.2
sumy==0.7.0
tensorboardX==2.1
thinc==7.4.0
tinysegmenter==0.3
tldextract==2.2.2
tokenizers==0.7.0
torch==1.5.0
tqdm==4.45.0
transformers==2.11.0
tzlocal==2.1
urllib3==1.22
wasabi==0.7.1
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==0.57.0
Werkzeug==1.0.1
word2number==1.1
wordninja==0.1.5
wrapt==1.12.1
yarl==1.4.2
zipp==3.1.0
```

</p>
</details>

## Steps to reproduce

<details>
<summary><b>Example source:</b></summary>
<p>

```
# Updating from older version to v1.0
Updated config : 
"data_loader": {
        "batch_sampler": {
        "type": "basic",
        "batch_size": 32
        }
    }
Previous config: 
"iterator": {
        "type": "basic",
        "batch_size": 32
    }
```

</p>
</details>

**Comment by matt-gardner** [comment]
We some some more context to help you.  Where did you run into this?  I'm guessing you were following something on the guide.  There was a bug there that was updated yesterday.  See [this page](https://guide.allennlp.org/next-steps#1) for the proper config.

**Comment by matt-gardner** [comment]
I'm guessing that the problem arose from outdated instructions in the guide, which has now been fixed.  Please feel free to comment if I got that wrong, or if there is some other issue here.

**Comment by iamsaurabhc** [comment]
> We some some more context to help you. Where did you run into this? I'm guessing you were following something on the guide. There was a bug there that was updated yesterday. See [this page](https://guide.allennlp.org/next-steps#1) for the proper config.

Thanks Matt, this issue has been resolved through the documentation! :+1:
