### ISSUE TITLE
The default value of `cuda_device`  of the class `GradientDescentTrainer` in allennlp/training/trainer.py

### ISSUE THREAD

**Issue by sysulx** [allenai/allennlp#4569]
On the line 274 of the file [allennlp/training/trainer.py](https://github.com/allenai/allennlp/blob/master/allennlp/training/trainer.py) it says the the default value of `cuda_device`  in the class `GradientDescentTrainer` is `-1`, `cuda_device : int, optional (default = -1)`,  but actually, the default value is `None`, (on line 361: `cuda_device: Optional[Union[int, torch.device]] = None`),  a small bug?

so when I try to use cpu to train a model and don't set the value of `cuda_device`, just using the default value of `GradientDescentTrainer`:
``` python 
trainer = GradientDescentTrainer(
        model=model,
        serialization_dir=serialization_dir,
        data_loader=train_loader,
        validation_data_loader=dev_loader,
        num_epochs=5,
        optimizer=optimizer,
    )
trainer.train()
```
I get this error:
``` 
Traceback (most recent call last):
  File "train.py", line 172, in <module>
    run_training_loop()
  File "train.py", line 132, in run_training_loop
    trainer.train()
  File "/data/nlp/.allennlp/allennlp/training/trainer.py", line 846, in train
    train_metrics = self._train_epoch(epoch)
  File "/data/nlp/.allennlp/allennlp/training/trainer.py", line 568, in _train_epoch
    batch_outputs = self.batch_outputs(batch, for_training=True)
  File "/data/nlp/.allennlp/allennlp/training/trainer.py", line 458, in batch_outputs
    output_dict = self._pytorch_model(**batch)
  File "/home/nlp/data/.anaconda3/envs/allennlp/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "train.py", line 60, in forward
    embedded_text = self.embedder(text)
  File "/home/nlp/data/.anaconda3/envs/allennlp/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/nlp/.allennlp/allennlp/modules/text_field_embedders/basic_text_field_embedder.py", line 84, in forward
    token_vectors = embedder(list(tensors.values())[0], **forward_params_values)
  File "/home/nlp/data/.anaconda3/envs/allennlp/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/nlp/.allennlp/allennlp/modules/token_embedders/embedding.py", line 202, in forward
    sparse=self.sparse,
  File "/home/nlp/data/.anaconda3/envs/allennlp/lib/python3.7/site-packages/torch/nn/functional.py", line 1814, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected object of device type cuda but got device type cpu for argument #1 'self' in call to _th_index_select
```

I think the reason is that in the class `Trainer`, it set the cuda_device to `cuda:0` if the `cuda_device` is `None` and the meachine have some gpus(from line 56 to line 62 of the file _allennlp/training/trainer.py_). so if you make a new `GradientDescentTrainer` object to train a model without setting the value of `cuda_device`, it may occur this error.

so the default value  of `cuda_device` in the class `GradientDescentTrainer` should be `-1`?

**Comment by epwalsh** [comment]
Hi @sysulx, so first of all the documentation is out-of-date. It should say that it defaults to the first cuda device that is available, if there is one. If you want to train on CPU you need to explicitly set `cuda_device = -1` in the trainer.

Would you be interested in making a PR to fix the docstring?

**Comment by sysulx** [comment]
ok, I see, I feel very excited! I am very glad to make a contribution to allennlp, but I'm sorry, now I only know a litte about the git (I think I'm a novice), so I need some time to learn how to use git to make a PR. and this is my first time to make a issue in github, but I feel good. 
thanks @epwalsh

**Comment by epwalsh** [comment]
Great! And if you haven’t seen it already, please have a look at the CONTRIBUTING.md document. You might find it helpful with getting started.
