### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute 'keys' when using ComposedSeq2Seq

### ISSUE THREAD

**Issue by izaskr** [allenai/allennlp#4691]
## Checklist

- [x] I have verified that the issue exists against the `master` branch of AllenNLP.
- [x] I have read the relevant section in the [contribution guide](https://github.com/allenai/allennlp/blob/master/CONTRIBUTING.md#bug-fixes-and-new-features) on reporting bugs.
- [x] I have checked the [issues list](https://github.com/allenai/allennlp/issues) for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/allenai/allennlp/pulls) for existing proposed fixes.
- [x] I have checked the [CHANGELOG](https://github.com/allenai/allennlp/blob/master/CHANGELOG.md) and the [commit log](https://github.com/allenai/allennlp/commits/master) to find out if the bug was already fixed in the master branch.
- [x] I have included in the "Description" section below a traceback from any exceptions related to this bug.
- [x] I have included in the "Related issues or possible duplicates" section beloew all related issues and possible duplicate issues (If there are none, check this box anyway).
- [x] I have included in the "Environment" section below the name of the operating system and Python version that I was using when I discovered this bug.
- [x] I have included in the "Environment" section below the output of `pip freeze`.
- [x] I have included in the "Steps to reproduce" section below a minimally reproducible example.

## Description

<details>
<summary><b>Python traceback:</b></summary>
<p>

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/CE/skr/anaconda3/lib/python3.6/site-packages/allennlp/training/trainer.py", line 867, in train
    train_metrics = self._train_epoch(epoch)
  File "/home/CE/skr/anaconda3/lib/python3.6/site-packages/allennlp/training/trainer.py", line 589, in _train_epoch
    batch_outputs = self.batch_outputs(batch, for_training=True)
  File "/home/CE/skr/anaconda3/lib/python3.6/site-packages/allennlp/training/trainer.py", line 479, in batch_outputs
    output_dict = self._pytorch_model(**batch)
  File "/home/CE/skr/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/CE/skr/anaconda3/lib/python3.6/site-packages/allennlp_models/generation/models/composed_seq2seq.py", line 121, in forward
    return self._decoder(state, target_tokens)
  File "/home/CE/skr/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/CE/skr/anaconda3/lib/python3.6/site-packages/allennlp_models/generation/modules/seq_decoders/auto_regressive.py", line 416, in forward
    output_dict = self._forward_loss(state_forward_loss, target_tokens)
  File "/home/CE/skr/anaconda3/lib/python3.6/site-packages/allennlp_models/generation/modules/seq_decoders/auto_regressive.py", line 161, in _forward_loss
    target_embedding = self.target_embedder(targets)
  File "/home/CE/skr/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/CE/skr/anaconda3/lib/python3.6/site-packages/allennlp/modules/text_field_embedders/basic_text_field_embedder.py", line 56, in forward
    if self._token_embedders.keys() != text_field_input.keys():
AttributeError: 'Tensor' object has no attribute 'keys'
```

</p>
</details>

## Related issues or possible duplicates

- None

## Environment

OS: Linux

Python version: 3.6.5

<details>
<summary><b>Output of <code>pip freeze</code>:</b></summary>
<p>

```
alabaster==0.7.10
allennlp==1.1.0
allennlp-models==1.1.0
anaconda-client==1.6.14
anaconda-navigator==1.8.7
anaconda-project==0.8.2
asn1crypto==0.24.0
astroid==1.6.3
astropy==3.0.2
attrs==18.1.0
Babel==2.5.3
backcall==0.1.0
backports.shutil-get-terminal-size==1.0.0
beautifulsoup4==4.6.0
bitarray==0.8.1
bkcharts==0.2
blaze==0.11.3
bleach==2.1.3
blis==0.4.1
bokeh==0.12.16
boto==2.48.0
boto3==1.15.6
botocore==1.18.6
Bottleneck==1.2.1
catalogue==1.0.0
certifi==2018.4.16
cffi==1.11.5
chardet==3.0.4
click==6.7
cloudpickle==0.5.3
clyent==1.2.2
colorama==0.3.9
conda==4.5.4
conda-build==3.10.5
conda-verify==2.0.0
conllu==4.1
contextlib2==0.5.5
cryptography==2.2.2
cycler==0.10.0
cymem==2.0.3
Cython==0.28.2
cytoolz==0.9.0.1
dask==0.17.5
dataclasses==0.7
datashape==0.5.4
decorator==4.3.0
distributed==1.21.8
docutils==0.14
en-core-web-sm==2.3.1
entrypoints==0.2.3
et-xmlfile==1.0.1
fastcache==1.0.2
filelock==3.0.4
Flask==1.0.2
Flask-Cors==3.0.4
ftfy==5.8
future==0.18.2
gevent==1.3.0
glob2==0.6
gmpy2==2.0.8
greenlet==0.4.13
h5py==2.7.1
heapdict==1.0.0
html5lib==1.0.1
idna==2.6
imageio==2.3.0
imagesize==1.0.0
importlib-metadata==2.0.0
ipykernel==4.8.2
ipython==6.4.0
ipython-genutils==0.2.0
ipywidgets==7.2.1
isort==4.3.4
itsdangerous==0.24
jdcal==1.4
jedi==0.12.0
Jinja2==2.10
jmespath==0.10.0
joblib==0.16.0
jsonnet==0.16.0
jsonpickle==1.4.1
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.2.3
jupyter-console==5.2.0
jupyter-core==4.4.0
jupyterlab==0.32.1
jupyterlab-launcher==0.10.5
kiwisolver==1.0.1
lazy-object-proxy==1.3.1
llvmlite==0.23.1
locket==0.2.0
lxml==4.2.1
MarkupSafe==1.0
matplotlib==2.2.2
mccabe==0.6.1
mistune==0.8.3
mkl-fft==1.0.0
mkl-random==1.0.1
more-itertools==4.1.0
mpmath==1.0.0
msgpack-python==0.5.6
multipledispatch==0.5.0
murmurhash==1.0.2
navigator-updater==0.2.1
nbconvert==5.3.1
nbformat==4.4.0
networkx==2.1
nltk==3.3
nose==1.3.7
notebook==5.5.0
numba==0.38.0
numexpr==2.6.5
numpy==1.14.3
numpydoc==0.8.0
odo==0.5.1
olefile==0.45.1
openpyxl==2.5.3
overrides==3.1.0
packaging==17.1
pandas==0.23.0
pandocfilters==1.4.2
parso==0.2.0
partd==0.3.8
path.py==11.0.1
pathlib2==2.3.2
patsy==0.5.0
pep8==1.7.1
pexpect==4.5.0
pickleshare==0.7.4
Pillow==5.1.0
pkginfo==1.4.2
plac==1.1.3
pluggy==0.6.0
ply==3.11
preshed==3.0.2
prompt-toolkit==1.0.15
protobuf==3.13.0
psutil==5.4.5
ptyprocess==0.5.2
py==1.5.3
py-rouge==1.1
pycodestyle==2.4.0
pycosat==0.6.3
pycparser==2.18
pycrypto==2.6.1
pycurl==7.43.0.1
pyflakes==1.6.0
Pygments==2.2.0
pylint==1.8.4
pyodbc==4.0.23
pyOpenSSL==18.0.0
pyparsing==2.2.0
PySocks==1.6.8
pytest==3.5.1
pytest-arraydiff==0.2
pytest-astropy==0.3.0
pytest-doctestplus==0.1.3
pytest-openfiles==0.3.0
pytest-remotedata==0.2.1
python-dateutil==2.7.3
pytz==2018.4
PyWavelets==0.5.2
PyYAML==3.12
pyzmq==17.0.0
QtAwesome==0.4.4
qtconsole==4.3.1
QtPy==1.4.1
regex==2020.9.27
requests==2.18.4
rope==0.10.7
ruamel-yaml==0.15.35
s3transfer==0.3.3
sacremoses==0.0.43
scikit-image==0.13.1
scikit-learn==0.19.1
scipy==1.1.0
seaborn==0.8.1
Send2Trash==1.5.0
sentencepiece==0.1.91
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.11.0
snowballstemmer==1.2.1
sortedcollections==0.6.1
sortedcontainers==1.5.10
spacy==2.3.2
Sphinx==1.7.4
sphinxcontrib-websupport==1.0.1
spyder==3.2.8
SQLAlchemy==1.2.7
srsly==1.0.2
statsmodels==0.9.0
sympy==1.1.1
tables==3.4.3
tblib==1.3.2
tensorboardX==2.1
terminado==0.8.1
testpath==0.3.1
thinc==7.4.1
tokenizers==0.8.1rc1
toolz==0.9.0
torch==1.6.0
torchtext==0.7.0
tornado==5.0.2
tqdm==4.49.0
traitlets==4.3.2
transformers==3.0.2
typing==3.6.4
unicodecsv==0.14.1
Unidecode==1.1.1
urllib3==1.22
wasabi==0.8.0
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.14.1
widgetsnbextension==3.2.1
word2number==1.1
wrapt==1.10.11
xlrd==1.1.0
XlsxWriter==1.0.4
xlwt==1.3.0
zict==0.1.3
zipp==3.2.0

```

</p>
</details>

## Steps to reproduce

<details>
<summary><b>Example source:</b></summary>
<p>

```
reader = Seq2SeqDatasetReader(source_tokenizer=WhitespaceTokenizer(),
		target_tokenizer=WhitespaceTokenizer(), 
		source_token_indexers={'tokens': SingleIdTokenIndexer()}, 
		target_token_indexers={'tokens': SingleIdTokenIndexer(namespace='target_tokens')})

train_dataset = reader.read(train_path)
validation_dataset = reader.read(val_path)
test_dataset = reader.read(test_path)
vocab = Vocabulary.from_instances(train_dataset + validation_dataset, min_count={'tokens': 1, 'target_tokens': 1})

train_dataset.index_with(vocab)
validation_dataset.index_with(vocab)

SRC_EMBEDDING_DIM = 128
TG_EMBEDDING_DIM = 128
HIDDEN_DIM = 512
enc_layers = 3
dec_layers = 3
enc_heads = 2
dec_heads = 2
ff_dim = 512
proj_dim = 128
enc_dropout = 0.2
dec_dropout = 0.2
max_decoding_steps = 40
beam = 3
CUDA_DEVICE = 0

src_embedding = Embedding(num_embeddings=vocab.get_vocab_size('tokens'),
                             embedding_dim=SRC_EMBEDDING_DIM)
source_embedder = BasicTextFieldEmbedder({"tokens": src_embedding})

trg_embedding = Embedding(num_embeddings=vocab.get_vocab_size('target_tokens'),
                             embedding_dim=TG_EMBEDDING_DIM)
target_embedder = BasicTextFieldEmbedder({"target_tokens": trg_embedding})

encoder = StackedSelfAttentionEncoder(input_dim=SRC_EMBEDDING_DIM, hidden_dim=HIDDEN_DIM,
                                      projection_dim=proj_dim, feedforward_hidden_dim=ff_dim, num_layers=enc_layers,
                                      num_attention_heads=enc_heads, dropout_prob=enc_dropout, use_positional_encoding=True)

decoder_net = StackedSelfAttentionDecoderNet(decoding_dim=TG_EMBEDDING_DIM, target_embedding_dim=TG_EMBEDDING_DIM,
                                             feedforward_hidden_dim=128, num_layers=dec_layers,                                             num_attention_heads=dec_heads, use_positional_encoding=True, dropout_prob=dec_dropout)

decoder = AutoRegressiveSeqDecoder(vocab=vocab, decoder_net=decoder_net, max_decoding_steps=max_decoding_steps,
                                target_embedder=target_embedder, target_namespace='target_tokens', beam_size=beam)

model = ComposedSeq2Seq(vocab=vocab, source_text_embedder=source_embedder,
                        encoder=encoder, decoder=decoder)

model = model.cuda(CUDA_DEVICE)

optimizer = optim.Adam(model.parameters(), lr=0.0005)

train_data_loader = PyTorchDataLoader(train_dataset,batch_sampler=BucketBatchSampler(train_dataset,batch_size=16))
dev_data_loader = PyTorchDataLoader(validation_dataset,batch_sampler=BucketBatchSampler(validation_dataset,batch_size=16))

trainer = GradientDescentTrainer(model=model, optimizer=optimizer,data_loader=train_data_loader,
                                 validation_data_loader=dev_data_loader,num_epochs=3)

trainer.train()
```

</p>
</details>
I'm using the ComposedSeq2Seq class. The error is raised also when I replace the Transformer encoder with an LSTM, and the same with the decoder. I suspect the error is connected to the data loader or iterator.

**Comment by ichiroex** [comment]
I'm in the same situation. Has anyone solved this issue?

**Comment by ichiroex** [comment]
@izaskr 
I've solved the issue. I think it is necessary to pass an Embedding object as target_embedder as below. 
Please see the documentation for AutoRegressiveSeqDecoder. It requires an Embedding object for target_embedder, not a TextFieldEmbedder object.
https://docs.allennlp.org/models/master/models/generation/modules/seq_decoders/auto_regressive/

decoder = AutoRegressiveSeqDecoder(
　vocab=vocab, decoder_net=decoder_net, max_decoding_steps=max_decoding_steps,
　target_embedder=**trg_embedding**, target_namespace='target_tokens', beam_size=beam)
