### ISSUE TITLE
run coreference resolution demo error.

### ISSUE THREAD

**Issue by baiziyuandyufei** [allenai/allennlp#4813]
## Checklist

- [x] I have verified that the issue exists against the `master` branch of AllenNLP.
- [x] I have read the relevant section in the [contribution guide](https://github.com/allenai/allennlp/blob/master/CONTRIBUTING.md#bug-fixes-and-new-features) on reporting bugs.
- [x] I have checked the [issues list](https://github.com/allenai/allennlp/issues) for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/allenai/allennlp/pulls) for existing proposed fixes.
- [x] I have checked the [CHANGELOG](https://github.com/allenai/allennlp/blob/master/CHANGELOG.md) and the [commit log](https://github.com/allenai/allennlp/commits/master) to find out if the bug was already fixed in the master branch.
- [x] I have included in the "Description" section below a traceback from any exceptions related to this bug.
- [x] I have included in the "Related issues or possible duplicates" section beloew all related issues and possible duplicate issues (If there are none, check this box anyway).
- [x] I have included in the "Environment" section below the name of the operating system and Python version that I was using when I discovered this bug.
- [x] I have included in the "Environment" section below the output of `pip freeze`.
- [x] I have included in the "Steps to reproduce" section below a minimally reproducible example.

## Description

@ZhaofengWu when I run the demo [Coreference Resolution Demo](https://demo.allennlp.org/coreference-resolution/MjU2NjExMA== ), I got the error below.

<details>
<summary><b>Python traceback:</b></summary>
<p>

```
Traceback (most recent call last):
  File "coref-demo.py", line 4, in <module>
    predictor = Predictor.from_path("./coref-spanbert-large.tar.gz")
  File "/Users/username/git_code/2020-coref/allennlp/allennlp/predictors/predictor.py", line 323, in from_path
    load_archive(archive_path, cuda_device=cuda_device, overrides=overrides),
  File "/Users/username/git_code/2020-coref/allennlp/allennlp/models/archival.py", line 202, in load_archive
    config = Params.from_file(os.path.join(serialization_dir, CONFIG_NAME), overrides)
  File "/Users/username/git_code/2020-coref/allennlp/allennlp/common/params.py", line 485, in from_file
    params_file = cached_path(params_file)
  File "/Users/username/git_code/2020-coref/allennlp/allennlp/common/file_utils.py", line 202, in cached_path
    raise FileNotFoundError(f"file {url_or_filename} not found")
FileNotFoundError: file /var/folders/_v/t8wzr_fj2gj83msgwd4t179c0000gn/T/tmp1f1z5a6w/config.json not found
```

</p>
</details>

## Related issues or possible duplicates

- None

## Environment

OS: OS X

Python version: 3.8.5

<details>
<summary><b>Output of <code>pip freeze</code>:</b></summary>
<p>

```
% pip freeze
-e git+https://github.com/allenai/allennlp.git@f353c6ce326affc07a7ea359611c22b103934144#egg=allennlp
allennlp-models==1.2.2
appdirs==1.4.4
attrs==20.3.0
black==20.8b1
bleach==3.2.1
blis==0.4.1
boto3==1.16.23
botocore==1.19.23
catalogue==1.0.0
certifi==2020.6.20
chardet==3.0.4
click==7.1.2
codecov==2.1.10
colorama==0.4.4
conllu==4.2.1
coverage==5.3
cycler==0.10.0
cymem==2.0.4
dataclasses==0.6
docutils==0.16
filelock==3.0.12
flake8==3.8.4
flaky==3.7.0
ftfy==5.8
future==0.18.2
h5py==3.1.0
idna==2.10
importlib-metadata==3.0.0
iniconfig==1.1.1
Jinja2==2.11.2
jmespath==0.10.0
joblib==0.17.0
jsonnet==0.17.0
jsonpickle==1.4.1
keyring==21.5.0
kiwisolver==1.3.1
livereload==2.6.3
lunr==0.5.8
Markdown==3.3.3
markdown-include==0.6.0
MarkupSafe==1.1.1
matplotlib==3.3.3
mccabe==0.6.1
mkdocs==1.1.2
mkdocs-material==6.1.6
mkdocs-material-extensions==1.0.1
murmurhash==1.0.4
mypy==0.790
mypy-extensions==0.4.3
nltk==3.5
nr.collections==0.0.1
nr.databind.core==0.0.16
nr.databind.json==0.0.13
nr.interface==0.0.3
nr.metaclass==0.0.5
nr.parsing.date==0.4.2
nr.pylang.utils==0.0.3
nr.stream==0.0.4
nr.utils.re==0.1.0
numpy==1.19.4
overrides==3.1.0
packaging==20.4
pathspec==0.8.1
pathtools==0.1.2
Pillow==8.0.1
pkginfo==1.6.1
plac==1.1.3
pluggy==0.13.1
preshed==3.0.4
protobuf==3.14.0
py==1.9.0
py-cpuinfo==7.0.0
py-rouge==1.1
pycodestyle==2.6.0
pydoc-markdown @ git+https://github.com/NiklasRosenstein/pydoc-markdown.git@f0bf8af1db4f11581c19d206d4ed1ab34b4854c1
pyflakes==2.2.0
Pygments==2.7.2
pymdown-extensions==8.0.1
pyparsing==2.4.7
pytest==6.1.2
pytest-benchmark==3.2.3
pytest-cov==2.10.1
python-dateutil==2.8.1
PyYAML==5.3.1
readme-renderer==28.0
regex==2020.11.13
requests==2.25.0
requests-toolbelt==0.9.1
responses==0.12.1
rfc3986==1.4.0
ruamel.yaml==0.16.12
ruamel.yaml.clib==0.2.2
s3transfer==0.3.3
sacremoses==0.0.43
scikit-learn==0.23.2
scipy==1.5.4
sentencepiece==0.1.91
six==1.15.0
spacy==2.3.2
srsly==1.0.4
tensorboardX==2.1
thinc==7.4.1
threadpoolctl==2.1.0
tokenizers==0.9.3
toml==0.10.2
torch==1.7.0
tornado==6.1
tqdm==4.53.0
transformers==3.5.1
twine==3.2.0
typed-ast==1.4.1
typing-extensions==3.7.4.3
urllib3==1.25.11
wasabi==0.8.0
watchdog==0.10.4
wcwidth==0.2.5
webencodings==0.5.1
word2number==1.1
zipp==3.4.0
```

</p>
</details>

## Steps to reproduce

<details>
<summary><b>Example source:</b></summary>
<p>

```
from allennlp.predictors.predictor import Predictor
import allennlp_models.coref
# predictor = Predictor.from_path("https://storage.googleapis.com/allennlp-public-models/coref-spanbert-large-2020.02.27.tar.gz")
predictor = Predictor.from_path("./coref-spanbert-large.tar.gz")
predictor.predict(
  document="The woman reading a newspaper sat on the bench with her dog."
)
```

</p>
</details>

**Comment by baiziyuandyufei** [comment]
@ZhaofengWu I seem to know the reason. the code download the "spanbert-large-cased" model failed.

**Comment by baiziyuandyufei** [comment]
@ZhaofengWu After download the "spanbert-large-cased" model, and modify the "coref-spanbert-large" model's config file, then everything is OK. The transformer cached model is too bad. The modified config file is below:
```
{
    "dataset_reader": {
        "type": "coref",
        "max_sentences": 110,
        "max_span_width": 30,
        "token_indexers": {
            "tokens": {
                "type": "pretrained_transformer_mismatched",
                "max_length": 512,
                "model_name": "/Users/yufei/Downloads/SpanBERT/spanbert-large-cased"
            }
        }
    },
    "iterator": {
        "type": "bucket",
        "batch_size": 1,
        "sorting_keys": [
            [
                "text",
                "tokens___token_ids"
            ]
        ]
    },
    "model": {
        "type": "coref",
        "antecedent_feedforward": {
            "activations": "relu",
            "dropout": 0.3,
            "hidden_dims": 1500,
            "input_dim": 9296,
            "num_layers": 2
        },
        "coarse_to_fine": true,
        "context_layer": {
            "type": "pass_through",
            "input_dim": 1024
        },
        "feature_size": 20,
        "inference_order": 2,
        "initializer": {
            "regexes": [
                [
                    ".*_span_updating_gated_sum.*weight",
                    {
                        "type": "xavier_normal"
                    }
                ],
                [
                    ".*linear_layers.*weight",
                    {
                        "type": "xavier_normal"
                    }
                ],
                [
                    ".*scorer.*weight",
                    {
                        "type": "xavier_normal"
                    }
                ],
                [
                    "_distance_embedding.weight",
                    {
                        "type": "xavier_normal"
                    }
                ],
                [
                    "_span_width_embedding.weight",
                    {
                        "type": "xavier_normal"
                    }
                ],
                [
                    "_context_layer._module.weight_ih.*",
                    {
                        "type": "xavier_normal"
                    }
                ],
                [
                    "_context_layer._module.weight_hh.*",
                    {
                        "type": "orthogonal"
                    }
                ]
            ]
        },
        "max_antecedents": 50,
        "max_span_width": 30,
        "mention_feedforward": {
            "activations": "relu",
            "dropout": 0.3,
            "hidden_dims": 1500,
            "input_dim": 3092,
            "num_layers": 2
        },
        "spans_per_word": 0.4,
        "text_field_embedder": {
            "token_embedders": {
                "tokens": {
                    "type": "pretrained_transformer_mismatched",
                    "max_length": 512,
                    "model_name": "/Users/yufei/Downloads/SpanBERT/spanbert-large-cased"
                }
            }
        }
    },
    "train_data_path": "/net/nfs2.corp/allennlp/zhaofengw/data/conll12/train.english.v4_gold_conll",
    "validation_data_path": "/net/nfs2.corp/allennlp/zhaofengw/data/conll12/dev.english.v4_gold_conll",
    "test_data_path": "/net/nfs2.corp/allennlp/zhaofengw/data/conll12/test.english.v4_gold_conll",
    "trainer": {
        "cuda_device": 0,
        "learning_rate_scheduler": {
            "type": "slanted_triangular",
            "cut_frac": 0.06
        },
        "num_epochs": 40,
        "optimizer": {
            "type": "huggingface_adamw",
            "lr": 0.0003,
            "parameter_groups": [
                [
                    [
                        ".*transformer.*"
                    ],
                    {
                        "lr": 1e-05
                    }
                ]
            ]
        },
        "patience": 10,
        "validation_metric": "+coref_f1"
    },
    "validation_dataset_reader": {
        "type": "coref",
        "max_span_width": 30,
        "token_indexers": {
            "tokens": {
                "type": "pretrained_transformer_mismatched",
                "max_length": 512,
                "model_name": "/Users/yufei/Downloads/SpanBERT/spanbert-large-cased"
            }
        }
    }
}%   
```
