### ISSUE TITLE
ViLBERT demo not working: vqav2 not in acceptable choices for dataset_reader.type when loading model

### ISSUE THREAD

**Issue by yonatanbitton** [allenai/allennlp#4875]
Hey

I want to try to ViLBERT demo:
https://demo.allennlp.org/visual-question-answering

I cannot install the repo from the link you provided: 
`pip install git+git://github.com/allenai/allennlp.git@0b20f80c1ea700766fe53d2eaf1c28de764f9710`, 
because I receieve: 
```python
(CondaEnv) a483e75eac4c:ChallangerCocoAlign yonatab$ pip install git+git://github.com/allenai/allennlp.git@0b20f80c1ea700766fe53d2eaf1c28de764f9710
Collecting git+git://github.com/allenai/allennlp.git@0b20f80c1ea700766fe53d2eaf1c28de764f9710
  Cloning git://github.com/allenai/allennlp.git (to revision 0b20f80c1ea700766fe53d2eaf1c28de764f9710) to /private/var/folders/sp/0n98h0kn4w7dq4xhl02ljk4n6r2n52/T/pip-req-build-sc0vamlj
  Running command git clone -q git://github.com/allenai/allennlp.git /private/var/folders/sp/0n98h0kn4w7dq4xhl02ljk4n6r2n52/T/pip-req-build-sc0vamlj
  Running command git checkout -q 0b20f80c1ea700766fe53d2eaf1c28de764f9710
  fatal: reference is not a tree: 0b20f80c1ea700766fe53d2eaf1c28de764f9710
ERROR: Command errored out with exit status 128: git checkout -q 0b20f80c1ea700766fe53d2eaf1c28de764f9710 Check the logs for full command output.
```

So I installed allennlp with pip. 

When this command runs: 
`predictor = Predictor.from_path("https://storage.googleapis.com/allennlp-public-models/vilbert-vqa-2020.10.01.tar.gz")
`
I receieve the following stacktrace:

Traceback (most recent call last):
 ```python
 File "/Users/yonatab/PycharmProjects/ChallangerCocoAlign/vilbert_allen.py", line 4, in <module>
    predictor = Predictor.from_path(pred_p)
  File "/Users/yonatab/opt/anaconda3/envs/CondaEnv/lib/python3.7/site-packages/allennlp/predictors/predictor.py", line 354, in from_path
    load_archive(archive_path, cuda_device=cuda_device, overrides=overrides),
  File "/Users/yonatab/opt/anaconda3/envs/CondaEnv/lib/python3.7/site-packages/allennlp/models/archival.py", line 206, in load_archive
    config.duplicate(), serialization_dir
  File "/Users/yonatab/opt/anaconda3/envs/CondaEnv/lib/python3.7/site-packages/allennlp/models/archival.py", line 232, in _load_dataset_readers
    dataset_reader_params, serialization_dir=serialization_dir
  File "/Users/yonatab/opt/anaconda3/envs/CondaEnv/lib/python3.7/site-packages/allennlp/common/from_params.py", line 581, in from_params
    default_to_first_choice=default_to_first_choice,
  File "/Users/yonatab/opt/anaconda3/envs/CondaEnv/lib/python3.7/site-packages/allennlp/common/params.py", line 352, in pop_choice
    raise ConfigurationError(message)
allennlp.common.checks.ConfigurationError: vqav2 not in acceptable choices for dataset_reader.type: ['conll2003', 'interleaving', 'sequence_tagging', 'sharded', 'babi', 'text_classification_json']. You should either use the --include-package flag to make sure the correct module is loaded, or use a fully qualified class name in your config file like {"model": "my_module.models.MyModel"} to have it imported automatically.
```

I've tried installing allennlp from source, using the **vision** branch: 
https://github.com/allenai/allennlp/tree/vision

I've also tried to download the model and loading from local path, getting the same problem.

How can I solve it?

**Comment by epwalsh** [comment]
Hey @yonatanbitton, sorry about that. That commit SHA was squashed in a PR merge and so no longer exists, and the latest release of AllenNLP doesn't yet support this vision stuff. Try installing from this commit instead: 7aa7e0e9537cc1e3f854e11b276c6d7063d02edc.
