### ISSUE TITLE
allennlp evaluate on naqanet error - key 'dataloader' is required

### ISSUE THREAD

**Issue by halnegheimish** [allenai/allennlp#4942]
Hi, I followed instructions on the demo website to run the command evaluate https://demo.allennlp.org/reading-comprehension/naqanet

namely:

`allennlp evaluate naqanet-2020.02.19.tar.gz drop_dataset/drop_dataset_dev.json`

On both allennlp & allennlp-models versions 1.0.0 and 2.0.0, but both result in the following error (this is V2). Please advise on how to rectify it, thank you. 

```[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.
2021-01-28 21:22:10,514 - ERROR - allennlp.common.plugins - Plugin allennlp_models could not be loaded: No module named 'nltk.translate.meteor_score'
2021-01-28 21:22:10,518 - INFO - allennlp.models.archival - loading archive file naqanet-2020.02.19.tar.gz
2021-01-28 21:22:10,519 - INFO - allennlp.models.archival - extracting archive file naqanet-2020.02.19.tar.gz to temp dir /tmp/tmpjsaf5m7m
2021-01-28 21:22:11,501 - INFO - allennlp.data.vocabulary - Loading token dictionary from /tmp/tmpjsaf5m7m/vocabulary.
2021-01-28 21:22:12,271 - INFO - allennlp.models.archival - removing temporary unarchived model dir at /tmp/tmpjsaf5m7m
2021-01-28 21:22:12,336 - INFO - allennlp.common.checks - Pytorch version: 1.7.0+cu101
2021-01-28 21:22:12,337 - INFO - allennlp.commands.evaluate - Reading evaluation data from drop_dataset/drop_dataset_dev.json
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/allennlp/common/params.py", line 238, in pop
    value = self.params.pop(key)
KeyError: 'data_loader'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/allennlp", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.6/dist-packages/allennlp/__main__.py", line 34, in run
    main(prog="allennlp")
  File "/usr/local/lib/python3.6/dist-packages/allennlp/commands/__init__.py", line 119, in main
    args.func(args)
  File "/usr/local/lib/python3.6/dist-packages/allennlp/commands/evaluate.py", line 140, in evaluate_from_args
    data_loader_params = config.pop("data_loader")
  File "/usr/local/lib/python3.6/dist-packages/allennlp/common/params.py", line 243, in pop
    raise ConfigurationError(msg)
allennlp.common.checks.ConfigurationError: key "data_loader" is required
```

**Comment by AkshitaB** [comment]
@halnegheimish This certainly fails in v2.0 right now, but it shouldn't fail for v1.0. Can you post the exact error for v1.0?

**Comment by halnegheimish** [comment]
Sure, please see below, that's using allennlp 1.0.0 and allennlp-models 1.0.0

```
2021-01-29 13:40:21,959 - INFO - transformers.file_utils - PyTorch version 1.5.1 available.
2021-01-29 13:40:22.111225: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2021-01-29 13:40:23,649 - INFO - transformers.file_utils - TensorFlow version 2.4.1 available.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.
2021-01-29 13:40:26,884 - INFO - allennlp.models.archival - loading archive file naqanet-2020.02.19.tar.gz
2021-01-29 13:40:26,884 - INFO - allennlp.models.archival - extracting archive file naqanet-2020.02.19.tar.gz to temp dir /tmp/tmp5s0hzv35
2021-01-29 13:40:27,396 - INFO - allennlp.data.vocabulary - Loading token dictionary from /tmp/tmp5s0hzv35/vocabulary.
2021-01-29 13:40:27,398 - INFO - filelock - Lock 139843595373592 acquired on /tmp/tmp5s0hzv35/vocabulary/.lock
2021-01-29 13:40:27,432 - INFO - filelock - Lock 139843595373592 released on /tmp/tmp5s0hzv35/vocabulary/.lock
2021-01-29 13:40:27,609 - INFO - allennlp.common.checks - Pytorch version: 1.5.1
2021-01-29 13:40:28,071 - INFO - allennlp.commands.evaluate - Reading evaluation data from drop_dataset/drop_dataset_dev.json
0it [00:00, ?it/s]2021-01-29 13:40:28,071 - INFO - allennlp_models.rc.dataset_readers.drop - Reading file at drop_dataset/drop_dataset_dev.json
2021-01-29 13:40:28,303 - INFO - allennlp_models.rc.dataset_readers.drop - Reading the dataset
9529it [00:13, 550.54it/s]2021-01-29 13:40:41,284 - INFO - allennlp_models.rc.dataset_readers.drop - Skipped 0 questions, kept 9536 questions.
9536it [00:13, 721.55it/s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/allennlp/common/params.py", line 237, in pop
    value = self.params.pop(key)
KeyError: 'data_loader'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/allennlp", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.6/dist-packages/allennlp/__main__.py", line 19, in run
    main(prog="allennlp")
  File "/usr/local/lib/python3.6/dist-packages/allennlp/commands/__init__.py", line 92, in main
    args.func(args)
  File "/usr/local/lib/python3.6/dist-packages/allennlp/commands/evaluate.py", line 136, in evaluate_from_args
    data_loader_params = config.pop("data_loader")
  File "/usr/local/lib/python3.6/dist-packages/allennlp/common/params.py", line 242, in pop
    raise ConfigurationError(msg)
allennlp.common.checks.ConfigurationError: key "data_loader" is required
2021-01-29 13:40:41,288 - INFO - allennlp.models.archival - removing temporary unarchived model dir at /tmp/tmp5s0hzv35
```

**Comment by AkshitaB** [comment]
@halnegheimish This should work with AllenNLP 2.0 and the latest model: `naqanet-2021.02.26.tar.gz` . Let us know if you are still facing the error.

**Comment by AkshitaB** [comment]
Closing.
