### ISSUE TITLE
KeyError: 'elmo'

### ISSUE THREAD

**Issue by manelAffi** [allenai/allennlp#5006]
System:
OS: linux 
Python version: 3.7 
AllenNLP version: 0.9.0 
PyTorch version: 1.7.2
Question:
I'm trying to train crf-tagger model for named entity recognition task on CoNLL 2003 dataset using BERT and elmo embeddings.I got the following error message:

**KeyError: 'elmo'**

**_here is the config file code:_**
```
{

  "dataset_reader": {
    "type": "conll2003",
    "tag_label": "ner",
    "coding_scheme": "BIOUL",
    "token_indexers": {
      "tokens": {
        "type": "single_id"

              },
        "elmo": {
        "type": "elmo_characters"
          } ,
"bert": {
         "type": "bert-pretrained",
        "pretrained_model":"bert-base-cased",
        "do_lowercase": false,
"use_starting_offsets": true
      }

    }
  },
"train_data_path": "########",
    "validation_data_path": "#########",
  
  "model": {
    "type": "crf_tagger",
    "label_encoding": "BIOUL",
    "dropout": 0.5,
    "include_start_end_transitions": false,
    "text_field_embedder": {
"allow_unmatched_keys": true,

      "embedder_to_indexer_map": {
                "bert": ["bert", "bert-offsets"],
                "token_characters": ["token_characters"],
            }, 

       "bert": {
                    "type": "bert-pretrained",
                    "pretrained_model": "bert-base-cased"
                },


        "elmo":{
            "type": "elmo_token_embedder",
        "options_file": "https://allennlp.s3.amazonaws.com/models/elmo/2x4096_512_2048cnn_2xhighway/elmo_2x4096_512_2048cnn_2xhighway_options.json",
        "weight_file": "https://allennlp.s3.amazonaws.com/models/elmo/2x4096_512_2048cnn_2xhighway/elmo_2x4096_512_2048cnn_2xhighway_weights.hdf5",
            "do_layer_norm": false,
            "dropout": 0.0
        }
     
             
    },
    "encoder": {
      "type": "lstm",
      "input_size": 1792,
      "hidden_size": 200,
      "num_layers": 2,
      "dropout": 0.5,
      "bidirectional": true
    },
    "regularizer": [
      [
        "scalar_parameters",
        {
          "type": "l2",
          "alpha": 0.1
        }
      ]
    ]
  },
  "iterator": {
    "type": "basic",
    "batch_size": 64
  },
  "trainer": {
    "optimizer": {
        "type": "adam",
        "lr": 0.0001
    },
    "validation_metric": "+f1-measure-overall",
    "num_serialized_models_to_keep": 3,
    "num_epochs": 200,
    "grad_norm": 5.0,

    "cuda_device": -1
  }
}
```
Is there any idea what should be the problem?

**Comment by AkshitaB** [comment]
@manelAffi Can you post the entire traceback? Also, make sure that the `bert-pretrained`, `elmo`, etc. are registered modules, otherwise, you'll get a `ConfigurationError` like this:

```
allennlp.common.checks.ConfigurationError: bert-pretrained not in acceptable choices for dataset_reader.token_indexers.bert.type: ['single_id', 'characters', 'elmo_characters', 'spacy', 'pretrained_transformer', 'pretrained_transformer_mismatched']. You should either use the --include-package flag to make sure the correct module is loaded, or use a fully qualified class name in your config file like {"model": "my_module.models.MyModel"} to have it imported automatically.
```

**Comment by manelAffi** [comment]
@AkshitaB thanks for your replay.
I have successfully trained elmo as well as bert with crf-tagger but when I try to combine them I get **"KeyError: 'elmo'"** error.

**Here is the full traceback:**
```
Traceback (most recent call last):
  File "/home/mrim/affim/anaconda3/envs/allennlp/bin/allennlp", line 8, in <module>
    sys.exit(run())
  File "/home/mrim/affim/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/run.py", line 18, in run
    main(prog="allennlp")
  File "/home/mrim/affim/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 102, in main
    args.func(args)
  File "/home/mrim/affim/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/train.py", line 124, in train_model_from_args
    args.cache_prefix)
  File "/home/mrim/affim/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/train.py", line 168, in train_model_from_file
    cache_directory, cache_prefix)
  File "/home/mrim/affim/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/train.py", line 252, in train_model
    metrics = trainer.train()
  File "/home/mrim/affim/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/training/trainer.py", line 478, in train
    train_metrics = self._train_epoch(epoch)
  File "/home/mrim/affim/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/training/trainer.py", line 320, in _train_epoch
    loss = self.batch_loss(batch_group, for_training=True)
  File "/home/mrim/affim/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/training/trainer.py", line 261, in batch_loss
    output_dict = self.model(**batch)
  File "/home/mrim/affim/anaconda3/envs/allennlp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mrim/affim/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/models/crf_tagger.py", line 182, in forward
    embedded_text_input = self.text_field_embedder(tokens)
  File "/home/mrim/affim/anaconda3/envs/allennlp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mrim/affim/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/modules/text_field_embedders/basic_text_field_embedder.py", line 113, in forward
    indexer_map = self._embedder_to_indexer_map[key]
KeyError: 'elmo'
```
