### ISSUE TITLE
Open Information Extraction Training fails with "status code 404"

### ISSUE THREAD

**Issue by MM-Vianai** [allenai/allennlp#5028]
## Checklist

- [x] I have verified that the issue exists against the `master` branch of AllenNLP.
- [x] I have read the relevant section in the [contribution guide](https://github.com/allenai/allennlp/blob/master/CONTRIBUTING.md#bug-fixes-and-new-features) on reporting bugs.
- [x] I have checked the [issues list](https://github.com/allenai/allennlp/issues) for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/allenai/allennlp/pulls) for existing proposed fixes.
- [x] I have checked the [CHANGELOG](https://github.com/allenai/allennlp/blob/master/CHANGELOG.md) and the [commit log](https://github.com/allenai/allennlp/commits/master) to find out if the bug was already fixed in the master branch.
- [x] I have included in the "Description" section below a traceback from any exceptions related to this bug.
- [x] I have included in the "Related issues or possible duplicates" section beloew all related issues and possible duplicate issues (If there are none, check this box anyway).
- [x] I have included in the "Environment" section below the name of the operating system and Python version that I was using when I discovered this bug.
- [x] I have included in the "Environment" section below the output of `pip freeze`.
- [x] I have included in the "Steps to reproduce" section below a minimally reproducible example.

## Description

running the command 

$ allennlp train \\
        https://raw.githubusercontent.com/allenai/allennlp-models/main/training_config/structured-prediction/srl.jsonnet \\
        -s /path/to/output

from [Model Usage](https://demo.allennlp.org/open-information-extraction) results in the following error message 

OSError: HEAD request failed for url https://raw.githubusercontent.com/allenai/allennlp-models/main/training_config/structured-prediction/srl.jsonnet with status code 404

<details>
<summary><b>Python traceback:</b></summary>
<p>

```
2021-02-28 17:49:16,852 - INFO - transformers.file_utils - PyTorch version 1.5.1 available.
Traceback (most recent call last):
  File "/Users/mmir/Desktop/Explorations/allennlp_openie/venv/bin/allennlp", line 8, in <module>
    sys.exit(run())
  File "/Users/mmir/Desktop/Explorations/allennlp_openie/venv/lib/python3.7/site-packages/allennlp/__main__.py", line 19, in run
    main(prog="allennlp")
  File "/Users/mmir/Desktop/Explorations/allennlp_openie/venv/lib/python3.7/site-packages/allennlp/commands/__init__.py", line 92, in main
    args.func(args)
  File "/Users/mmir/Desktop/Explorations/allennlp_openie/venv/lib/python3.7/site-packages/allennlp/commands/train.py", line 112, in train_model_from_args
    dry_run=args.dry_run,
  File "/Users/mmir/Desktop/Explorations/allennlp_openie/venv/lib/python3.7/site-packages/allennlp/commands/train.py", line 162, in train_model_from_file
    params = Params.from_file(parameter_filename, overrides)
  File "/Users/mmir/Desktop/Explorations/allennlp_openie/venv/lib/python3.7/site-packages/allennlp/common/params.py", line 487, in from_file
    params_file = cached_path(params_file)
  File "/Users/mmir/Desktop/Explorations/allennlp_openie/venv/lib/python3.7/site-packages/allennlp/common/file_utils.py", line 105, in cached_path
    return get_from_cache(url_or_filename, cache_dir)
  File "/Users/mmir/Desktop/Explorations/allennlp_openie/venv/lib/python3.7/site-packages/allennlp/common/file_utils.py", line 301, in get_from_cache
    etag = _http_etag(url)
  File "/Users/mmir/Desktop/Explorations/allennlp_openie/venv/lib/python3.7/site-packages/allennlp/common/file_utils.py", line 211, in _http_etag
    "HEAD request failed for url {} with status code {}".format(url, response.status_code)
OSError: HEAD request failed for url https://raw.githubusercontent.com/allenai/allennlp-models/main/training_config/structured-prediction/srl.jsonnet with status code 404
```

</p>
</details>

## Related issues or possible duplicates

- None

## Environment

OS: macOS 10.15.4

Python version: 3.7.6

<details>
<summary><b>Output of <code>pip freeze</code>:</b></summary>
<p>

```
allennlp==1.0.0
allennlp-models==1.0.0
attrs==20.3.0
blis==0.4.1
boto3==1.17.14
botocore==1.20.14
cached-property==1.5.2
catalogue==1.0.0
certifi==2020.12.5
chardet==4.0.0
click==7.1.2
conllu==3.0
cymem==2.0.5
en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.5/en_core_web_sm-2.2.5.tar.gz
filelock==3.0.12
future==0.18.2
h5py==3.1.0
idna==2.10
importlib-metadata==3.5.0
iniconfig==1.1.1
jmespath==0.10.0
joblib==1.0.1
jsonnet==0.17.0
jsonpickle==2.0.0
murmurhash==1.0.5
nltk==3.5
numpy==1.20.1
overrides==3.0.0
packaging==20.9
plac==1.1.3
pluggy==0.13.1
preshed==3.0.5
protobuf==3.15.1
py==1.10.0
py-rouge==1.1
pyparsing==2.4.7
pytest==6.2.2
python-dateutil==2.8.1
regex==2020.11.13
requests==2.25.1
s3transfer==0.3.4
sacremoses==0.0.43
scikit-learn==0.24.1
scipy==1.6.1
sentencepiece==0.1.95
six==1.15.0
spacy==2.2.4
srsly==1.0.5
tensorboardX==2.1
thinc==7.4.0
threadpoolctl==2.1.0
tokenizers==0.7.0
toml==0.10.2
torch==1.5.1
tqdm==4.57.0
transformers==2.11.0
typing-extensions==3.7.4.3
urllib3==1.26.3
wasabi==0.8.2
word2number==1.1
zipp==3.4.0
```

</p>
</details>

## Steps to reproduce

<details>
<summary><b>Example source:</b></summary>
<p>

```

$ pip install allennlp==1.0.0 allennlp-models==1.0.0
$ allennlp train \
        https://raw.githubusercontent.com/allenai/allennlp-models/main/training_config/structured-prediction/srl.jsonnet \
        -s /path/to/output
```

</p>
</details>

**Comment by leo-liuzy** [comment]
I tried to use this [link](https://github.com/allenai/allennlp-models/blob/main/training_config/structured_prediction/srl.jsonnet) to get the file, but receive this error message:
```
RuntimeError: STATIC ERROR: /Users/leoliu/.allennlp/cache/a08203d7b31ac6c3f7d12ebac7c21025cd88c8483bea831b4d92edd9f6d8595e.8e0aa165b3935f2590041040a7f88e0e5cb3a4a40693947926c6bd114af92148:52:46: Could not lex the character code 194
```

### Traceback
```
Traceback (most recent call last):
  File "/Users/leoliu/anaconda3/envs/allennlp/bin/allennlp", line 33, in <module>
    sys.exit(load_entry_point('allennlp', 'console_scripts', 'allennlp')())
  File "/Users/leoliu/My/proj/allennlp/allennlp/__main__.py", line 34, in run
    main(prog="allennlp")
  File "/Users/leoliu/My/proj/allennlp/allennlp/commands/__init__.py", line 119, in main
    args.func(args)
  File "/Users/leoliu/My/proj/allennlp/allennlp/commands/train.py", line 119, in train_model_from_args
    file_friendly_logging=args.file_friendly_logging,
  File "/Users/leoliu/My/proj/allennlp/allennlp/commands/train.py", line 169, in train_model_from_file
    params = Params.from_file(parameter_filename, overrides)
  File "/Users/leoliu/My/proj/allennlp/allennlp/common/params.py", line 488, in from_file
    file_dict = json.loads(evaluate_file(params_file, ext_vars=ext_vars))
```

**Comment by leo-liuzy** [comment]
The correct file is: `https://raw.githubusercontent.com/allenai/allennlp-models/main/training_config/structured_prediction/srl.jsonnet`

**Comment by leo-liuzy** [comment]
We are also noticing you are not using open IE jsonnet, which we realize was lost on our site. Looking for it.

**Comment by MM-Vianai** [comment]
@leo-liuzy Using the url you provided results in the following error. Also how may I use openIE jsonnet?

`$ allennlp train \
https://raw.githubusercontent.com/allenai/allennlp-models/main/training_config/structured_prediction/srl.jsonnet \
-s /path/to/output
`

Traceback

`File "/Users/mmir/Desktop/Explorations/allennlp_openie/venv/bin/allennlp", line 8, in <module>
    sys.exit(run())
  File "/Users/mmir/Desktop/Explorations/allennlp_openie/venv/lib/python3.7/site-packages/allennlp/__main__.py", line 19, in run
    main(prog="allennlp")
  File "/Users/mmir/Desktop/Explorations/allennlp_openie/venv/lib/python3.7/site-packages/allennlp/commands/__init__.py", line 92, in main
    args.func(args)
  File "/Users/mmir/Desktop/Explorations/allennlp_openie/venv/lib/python3.7/site-packages/allennlp/commands/train.py", line 112, in train_model_from_args
    dry_run=args.dry_run,
  File "/Users/mmir/Desktop/Explorations/allennlp_openie/venv/lib/python3.7/site-packages/allennlp/commands/train.py", line 162, in train_model_from_file
    params = Params.from_file(parameter_filename, overrides)
  File "/Users/mmir/Desktop/Explorations/allennlp_openie/venv/lib/python3.7/site-packages/allennlp/common/params.py", line 490, in from_file
    file_dict = json.loads(evaluate_file(params_file, ext_vars=ext_vars))
RuntimeError: RUNTIME ERROR: undefined external variable: SRL_TRAIN_DATA_PATH
	/Users/mmir/.allennlp/cache/7b66931f5d59f453cfd47c36459b2280831af2055c07e0efe1786436e2ee62bb.9c0f0ee8efad943aed3f073eb8dd550d7f94b8a37d9fbbbe131467f98134958a:5:22-55	object <anonymous>
	During manifestation`

**Comment by leo-liuzy** [comment]
It seems you need to specify path to your training dataset as environment variable
```
export SRL_TRAIN_DATA_PATH="xxx"
export SRL_VALIDATION_DATA_PATH="xxx"
// Command

```

**Comment by MM-Vianai** [comment]
@leo-liuzy Thank you for the reply. Getting the proper training set has been a challenge for me so far. 

Following the link on the bottom of [Model Usage/Training section](https://demo.allennlp.org/open-information-extraction) redirects me to [this repo](https://github.com/gabrielStanovsky/oie-benchmark) with instructions on how to convert QA-SRL annotations to Open-IE so that we obtain the right data to finally run the training command provided on under Model Usage. However, following the instructions to get the base data in order to convert to openIE format is an erroneous process (some scripts seem to be outdated)

Are the train and test data in openie format available anywhere to be used?
