### ISSUE TITLE
Run older SRL model with latest allennlp (v2.1.0)

### ISSUE THREAD

**Issue by philinew** [allenai/allennlp#5047]
Using the latest version of allennlp (v2.1.0), I am trying to use a SRL model from 2018:

```
from allennlp.models.archival import load_archive

from allennlp_models.structured_prediction.predictors.srl import SemanticRoleLabelerPredictor

srl_model_path = "https://s3-us-west-2.amazonaws.com/allennlp/models/srl-model-2018.05.25.tar.gz"

predictor = SemanticRoleLabelerPredictor.from_archive(load_archive(srl_model_path), "semantic_role_labeling")

```
However, I get this error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/philine/Desktop/allen_test/venv/lib/python3.8/site-packages/allennlp/models/archival.py", line 208, in load_archive
    model = _load_model(config.duplicate(), weights_path, serialization_dir, cuda_device)
  File "/Users/philine/Desktop/allen_test/venv/lib/python3.8/site-packages/allennlp/models/archival.py", line 242, in _load_model
    return Model.load(
  File "/Users/philine/Desktop/allen_test/venv/lib/python3.8/site-packages/allennlp/models/model.py", line 406, in load
    return model_class._load(config, serialization_dir, weights_file, cuda_device)
  File "/Users/philine/Desktop/allen_test/venv/lib/python3.8/site-packages/allennlp/models/model.py", line 304, in _load
    model = Model.from_params(
  File "/Users/philine/Desktop/allen_test/venv/lib/python3.8/site-packages/allennlp/common/from_params.py", line 600, in from_params
    return retyped_subclass.from_params(
  File "/Users/philine/Desktop/allen_test/venv/lib/python3.8/site-packages/allennlp/common/from_params.py", line 632, in from_params
    kwargs = create_kwargs(constructor_to_inspect, cls, params, **extras)
  File "/Users/philine/Desktop/allen_test/venv/lib/python3.8/site-packages/allennlp/common/from_params.py", line 199, in create_kwargs
    constructed_arg = pop_and_construct_arg(
  File "/Users/philine/Desktop/allen_test/venv/lib/python3.8/site-packages/allennlp/common/from_params.py", line 307, in pop_and_construct_arg
    return construct_arg(class_name, name, popped_params, annotation, default, **extras)
  File "/Users/philine/Desktop/allen_test/venv/lib/python3.8/site-packages/allennlp/common/from_params.py", line 341, in construct_arg
    return annotation.from_params(params=popped_params, **subextras)
  File "/Users/philine/Desktop/allen_test/venv/lib/python3.8/site-packages/allennlp/common/from_params.py", line 556, in from_params
    raise ConfigurationError(
allennlp.common.checks.ConfigurationError: from_params was passed a `params` object that was not a `Params`. This probably indicates malformed parameters in a configuration file, where something that should have been a dictionary was actually a list, or something else. This happened when constructing an object of type <class 'allennlp.nn.regularizers.regularizer_applicator.RegularizerApplicator'>.
```

(How) Can I use the old model with the latest version of the allennlp?

Edit: the exact same code works like a charm if I use this model:
https://storage.googleapis.com/allennlp-public-models/openie-model.2020.03.26.tar.gz

**Comment by dirkgr** [comment]
One reason we update the models is when they are no longer compatible with new code. Why do you need to run the 2018 version?

Did you try running it on the 1.5 version of AllenNLP?

**Comment by philinew** [comment]
Thanks. The 2018 model seems to perform better on our corpus.

Just checked, I get the same error with allennlp==1.5.0. So the conclusion then is that, to use newer versions of allennlp, we'll have to switch the model..?

**Comment by dirkgr** [comment]
Can you fine-tune on your corpus? There should not have been any real changes in the model since 2018, but things move around over time. You change an unrelated line of code and now random numbers are consumed in a different order, so the model initialization is different, pytorch fixes some bug that affected numbers, maybe we fixed a bug in the trainer, etc. A lot of things can happen in three years.

If you have the original corpus to train on, you could try some hyperparameters and see if you can get better numbers that way. It's quite easy to train this. I'd be happy to walk you through it.

**Comment by philinew** [comment]
We'll have to think it through. Thanks for your help.
