### ISSUE TITLE
When using AllenNLP DEMO 'Semantic Role Labeling',it doesn't work.

### ISSUE THREAD

**Issue by gaozhiguang** [allenai/allennlp#5060]
**My code is as same as the demo:**
from allennlp.predictors.predictor import Predictor
import allennlp_models.tagging

predictor = Predictor.from_path("https://storage.googleapis.com/allennlp-public-models/structured-prediction-srl-bert.2020.12.15.tar.gz")
predictor.predict(
    sentence="Did Uriah honestly think he could beat the game in under three hours?."
)
**But this bug happens:**
Traceback (most recent call last):
  File "/home/zggao/anaconda3/envs/test-coreference-resolution/bin/allennlp", line 8, in <module>
    sys.exit(run())
  File "/home/zggao/anaconda3/envs/test-coreference-resolution/lib/python3.6/site-packages/allennlp/__main__.py", line 19, in run
    main(prog="allennlp")
  File "/home/zggao/anaconda3/envs/test-coreference-resolution/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 92, in main
    args.func(args)
  File "/home/zggao/anaconda3/envs/test-coreference-resolution/lib/python3.6/site-packages/allennlp/commands/predict.py", line 197, in _predict
    predictor = _get_predictor(args)
  File "/home/zggao/anaconda3/envs/test-coreference-resolution/lib/python3.6/site-packages/allennlp/commands/predict.py", line 98, in _get_predictor
    overrides=args.overrides,
  File "/home/zggao/anaconda3/envs/test-coreference-resolution/lib/python3.6/site-packages/allennlp/models/archival.py", line 197, in load_archive
    opt_level=opt_level,
  File "/home/zggao/anaconda3/envs/test-coreference-resolution/lib/python3.6/site-packages/allennlp/models/model.py", line 398, in load
    return model_class._load(config, serialization_dir, weights_file, cuda_device, opt_level)
  File "/home/zggao/anaconda3/envs/test-coreference-resolution/lib/python3.6/site-packages/allennlp/models/model.py", line 337, in _load
    model.load_state_dict(model_state)
  File "/home/zggao/anaconda3/envs/test-coreference-resolution/lib/python3.6/site-packages/torch/nn/modules/module.py", line 847, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for SrlBert:
	Unexpected key(s) in state_dict: "bert_model.embeddings.position_ids".

I don't know why,is it the version problem?

**Comment by gaozhiguang** [comment]
Sorry to interrupte, i have fixed my problem when i browse the issues, if anyone meets the same problem , please check [https://github.com/allenai/allennlp/issues/5022](url)
