### ISSUE TITLE
Vocabulary `from_files` requires write access when given directory

### ISSUE THREAD

**Issue by sanjayss34** [allenai/allennlp#5063]
When I pass a read-only vocabulary directory to `from_files`, I get the following traceback:
```
2021-03-18T22:40:18.307655908Z	Traceback (most recent call last):
2021-03-18T22:40:18.3076591Z	  File "/usr/local/bin/allennlp", line 8, in <module>
2021-03-18T22:40:18.30766227Z	    sys.exit(run())
2021-03-18T22:40:18.30766478Z	  File "/usr/local/lib/python3.6/site-packages/allennlp/__main__.py", line 34, in run
2021-03-18T22:40:18.30766752Z	    main(prog="allennlp")
2021-03-18T22:40:18.30767Z	  File "/usr/local/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 118, in main
2021-03-18T22:40:18.307672925Z	    args.func(args)
2021-03-18T22:40:18.30767535Z	  File "/usr/local/lib/python3.6/site-packages/allennlp/commands/train.py", line 119, in train_model_from_args
2021-03-18T22:40:18.307678128Z	    file_friendly_logging=args.file_friendly_logging,
2021-03-18T22:40:18.307687325Z	  File "/usr/local/lib/python3.6/site-packages/allennlp/commands/train.py", line 178, in train_model_from_file
2021-03-18T22:40:18.307689857Z	    file_friendly_logging=file_friendly_logging,
2021-03-18T22:40:18.307692128Z	  File "/usr/local/lib/python3.6/site-packages/allennlp/commands/train.py", line 242, in train_model
2021-03-18T22:40:18.307694787Z	    file_friendly_logging=file_friendly_logging,
2021-03-18T22:40:18.307697151Z	  File "/usr/local/lib/python3.6/site-packages/allennlp/commands/train.py", line 456, in _train_worker
2021-03-18T22:40:18.307700284Z	    local_rank=process_rank,
2021-03-18T22:40:18.307702593Z	  File "/usr/local/lib/python3.6/site-packages/allennlp/common/from_params.py", line 601, in from_params
2021-03-18T22:40:18.307705144Z	    **extras,
2021-03-18T22:40:18.307707439Z	  File "/usr/local/lib/python3.6/site-packages/allennlp/common/from_params.py", line 631, in from_params
2021-03-18T22:40:18.307709877Z	    return constructor_to_call(**kwargs)  # type: ignore
2021-03-18T22:40:18.307712187Z	  File "/usr/local/lib/python3.6/site-packages/allennlp/commands/train.py", line 670, in from_partial_objects
2021-03-18T22:40:18.307714762Z	    vocabulary_ = vocabulary.construct(instances=instance_generator)
2021-03-18T22:40:18.307717138Z	  File "/usr/local/lib/python3.6/site-packages/allennlp/common/lazy.py", line 58, in construct
2021-03-18T22:40:18.307720077Z	    return self._constructor(**kwargs)
2021-03-18T22:40:18.307722737Z	  File "/usr/local/lib/python3.6/site-packages/allennlp/common/from_params.py", line 467, in constructor
2021-03-18T22:40:18.307725476Z	    return value_cls.from_params(params=deepcopy(popped_params), **constructor_extras)
2021-03-18T22:40:18.307728026Z	  File "/usr/local/lib/python3.6/site-packages/allennlp/common/from_params.py", line 601, in from_params
2021-03-18T22:40:18.307730479Z	    **extras,
2021-03-18T22:40:18.30773889Z	  File "/usr/local/lib/python3.6/site-packages/allennlp/common/from_params.py", line 631, in from_params
2021-03-18T22:40:18.307742365Z	    return constructor_to_call(**kwargs)  # type: ignore
2021-03-18T22:40:18.307744785Z	  File "/usr/local/lib/python3.6/site-packages/allennlp/data/vocabulary.py", line 341, in from_files
2021-03-18T22:40:18.307747631Z	    with FileLock(os.path.join(directory, ".lock")):
2021-03-18T22:40:18.30775018Z	  File "/usr/local/lib/python3.6/site-packages/filelock.py", line 323, in __enter__
2021-03-18T22:40:18.307752936Z	    self.acquire()
2021-03-18T22:40:18.30775527Z	  File "/usr/local/lib/python3.6/site-packages/filelock.py", line 271, in acquire
2021-03-18T22:40:18.307757825Z	    self._acquire()
2021-03-18T22:40:18.307760053Z	  File "/usr/local/lib/python3.6/site-packages/filelock.py", line 384, in _acquire
2021-03-18T22:40:18.307762593Z	    fd = os.open(self._lock_file, open_mode)
2021-03-18T22:40:18.307764903Z	OSError: [Errno 30] Read-only file system: '/vocabulary/.lock'
```

**Comment by sanjayss34** [comment]
Closing because this issue is fixed in the latest version by https://github.com/allenai/allennlp/commit/1d21c759e289751754b7f82fd68b7c9951b34e60 (thanks @epwalsh for telling me)
