### ISSUE TITLE
Dataset for training openIE

### ISSUE THREAD

**Issue by MM-Vianai** [allenai/allennlp#5112]
Following the instructions on [demo page](https://demo.allennlp.org/open-information-extraction) I am trying to train the model using the provided command under model usage / training.

after following instructions on [oie-benchmark repo](https://github.com/gabrielStanovsky/oie-benchmark) I set environment variables in the config file as follows:
export SRL_TRAIN_DATA_PATH="oie-benchmark/oie_corpus/train.oie"
export SRL_VALIDATION_DATA_PATH="oie-benchmark/oie_corpus/test.oie"

and run the training command provided on allennlp demo:

`allennlp train https://raw.githubusercontent.com/allenai/allennlp-models/main/training_config/structured_prediction/srl.jsonnet -s output`

However, I get the following error:

`allennlp.common.checks.ConfigurationError: No embeddings of correct dimension found; you probably misspecified your embedding_dim parameter, or didn't pre-populate your Vocabulary`

are train.oie and test.oie correct dataset to be used?

[this old issue](https://github.com/allenai/allennlp/issues/3484) is somewhat similar but the problem was never resolved and it got closed.

**Comment by AkshitaB** [comment]
@gabrielStanovsky This was probably a while ago for you; do you remember if any pre-processing was done on the OIE dataset for the model?

**Comment by gabrielStanovsky** [comment]
I haven't encountered this error before, @MM-Vianai , can you check if this issue is relevant and whether the solution there is helpful?

https://github.com/gabrielStanovsky/oie-benchmark/issues/18

**Comment by MM-Vianai** [comment]
@gabrielStanovsky Thank you for the reply. Unfortunately that issue was not similar to my problem. 

To clarify the error, this is what I have been trying (am i missing something?):
Follwoing [demo-page](https://demo.allennlp.org/open-information-extraction) I install allennlp:

`pip install allennlp==2.1.0 allennlp-models==2.1.0`

To prepare for running the training command I followed [oie-benchmark](https://github.com/gabrielStanovsky/oie-benchmark) instructions to produce train.oie and test.oie  using ./create_oie_corpus.sh 
Then I set the environment variables as follows:

```
export SRL_TRAIN_DATA_PATH="oie-benchmark/oie_corpus/train.oie"
export SRL_VALIDATION_DATA_PATH="oie-benchmark/oie_corpus/test.oie"
```

Then, I ran the training command:
```
allennlp train https://raw.githubusercontent.com/allenai/allennlp-models/main/training_config/structured_prediction/srl.jsonnet -s output
```
but this produces an error. I am including the complete error below. 

I have also tried this with the data snapshot provided in  in the oie-benchmark but same error happened. 

before the error I see some logs indicating that srl instances and CONLL sentence are being read from the same file:
```
allennlp_models.structured_prediction.dataset_readers.srl - Reading SRL instances from dataset files at: oie-benchmark/oie_corpus/train.oie
2021-04-24 14:59:04,695 - INFO - allennlp_models.common.ontonotes - Reading CONLL sentences from dataset files at: oie-benchmark/oie_corpus/train.oie
```

and this is the full stack trace of the error :

```
2021-04-24 14:59:04,702 - INFO - allennlp.modules.token_embedders.embedding - Reading pretrained embeddings from file
2021-04-24 14:59:04,943 - INFO - allennlp.common.file_utils - cache of https://allennlp.s3.amazonaws.com/datasets/glove/glove.6B.100d.txt.gz is up-to-date
400000it [00:02, 150228.14it/s]
2021-04-24 14:59:07,610 - CRITICAL - root - Uncaught exception
Traceback (most recent call last):
  File "/Users/mmir/Desktop/openie/venv/bin/allennlp", line 8, in <module>
    sys.exit(run())
  File "/Users/mmir/Desktop/openie/venv/lib/python3.7/site-packages/allennlp/__main__.py", line 34, in run
    main(prog="allennlp")
  File "/Users/mmir/Desktop/openie/venv/lib/python3.7/site-packages/allennlp/commands/__init__.py", line 119, in main
    args.func(args)
  File "/Users/mmir/Desktop/openie/venv/lib/python3.7/site-packages/allennlp/commands/train.py", line 119, in train_model_from_args
    file_friendly_logging=args.file_friendly_logging,
  File "/Users/mmir/Desktop/openie/venv/lib/python3.7/site-packages/allennlp/commands/train.py", line 178, in train_model_from_file
    file_friendly_logging=file_friendly_logging,
  File "/Users/mmir/Desktop/openie/venv/lib/python3.7/site-packages/allennlp/commands/train.py", line 242, in train_model
    file_friendly_logging=file_friendly_logging,
  File "/Users/mmir/Desktop/openie/venv/lib/python3.7/site-packages/allennlp/commands/train.py", line 456, in _train_worker
    local_rank=process_rank,
  File "/Users/mmir/Desktop/openie/venv/lib/python3.7/site-packages/allennlp/common/from_params.py", line 604, in from_params
    **extras,
  File "/Users/mmir/Desktop/openie/venv/lib/python3.7/site-packages/allennlp/common/from_params.py", line 634, in from_params
    return constructor_to_call(**kwargs)  # type: ignore
  File "/Users/mmir/Desktop/openie/venv/lib/python3.7/site-packages/allennlp/commands/train.py", line 712, in from_partial_objects
    model_ = model.construct(vocab=vocabulary_, serialization_dir=serialization_dir)
  File "/Users/mmir/Desktop/openie/venv/lib/python3.7/site-packages/allennlp/common/lazy.py", line 62, in construct
    return self._constructor(**kwargs)
  File "/Users/mmir/Desktop/openie/venv/lib/python3.7/site-packages/allennlp/common/from_params.py", line 470, in constructor
    return value_cls.from_params(params=deepcopy(popped_params), **constructor_extras)
  File "/Users/mmir/Desktop/openie/venv/lib/python3.7/site-packages/allennlp/common/from_params.py", line 604, in from_params
    **extras,
  File "/Users/mmir/Desktop/openie/venv/lib/python3.7/site-packages/allennlp/common/from_params.py", line 632, in from_params
    kwargs = create_kwargs(constructor_to_inspect, cls, params, **extras)
  File "/Users/mmir/Desktop/openie/venv/lib/python3.7/site-packages/allennlp/common/from_params.py", line 200, in create_kwargs
    cls.__name__, param_name, annotation, param.default, params, **extras
  File "/Users/mmir/Desktop/openie/venv/lib/python3.7/site-packages/allennlp/common/from_params.py", line 307, in pop_and_construct_arg
    return construct_arg(class_name, name, popped_params, annotation, default, **extras)
  File "/Users/mmir/Desktop/openie/venv/lib/python3.7/site-packages/allennlp/common/from_params.py", line 341, in construct_arg
    return annotation.from_params(params=popped_params, **subextras)
  File "/Users/mmir/Desktop/openie/venv/lib/python3.7/site-packages/allennlp/common/from_params.py", line 604, in from_params
    **extras,
  File "/Users/mmir/Desktop/openie/venv/lib/python3.7/site-packages/allennlp/common/from_params.py", line 632, in from_params
    kwargs = create_kwargs(constructor_to_inspect, cls, params, **extras)
  File "/Users/mmir/Desktop/openie/venv/lib/python3.7/site-packages/allennlp/common/from_params.py", line 200, in create_kwargs
    cls.__name__, param_name, annotation, param.default, params, **extras
  File "/Users/mmir/Desktop/openie/venv/lib/python3.7/site-packages/allennlp/common/from_params.py", line 307, in pop_and_construct_arg
    return construct_arg(class_name, name, popped_params, annotation, default, **extras)
  File "/Users/mmir/Desktop/openie/venv/lib/python3.7/site-packages/allennlp/common/from_params.py", line 391, in construct_arg
    **extras,
  File "/Users/mmir/Desktop/openie/venv/lib/python3.7/site-packages/allennlp/common/from_params.py", line 341, in construct_arg
    return annotation.from_params(params=popped_params, **subextras)
  File "/Users/mmir/Desktop/openie/venv/lib/python3.7/site-packages/allennlp/common/from_params.py", line 604, in from_params
    **extras,
  File "/Users/mmir/Desktop/openie/venv/lib/python3.7/site-packages/allennlp/common/from_params.py", line 634, in from_params
    return constructor_to_call(**kwargs)  # type: ignore
  File "/Users/mmir/Desktop/openie/venv/lib/python3.7/site-packages/allennlp/modules/token_embedders/embedding.py", line 156, in __init__
    pretrained_file, embedding_dim, vocab, vocab_namespace
  File "/Users/mmir/Desktop/openie/venv/lib/python3.7/site-packages/allennlp/modules/token_embedders/embedding.py", line 370, in _read_pretrained_embeddings_file
    return _read_embeddings_from_text_file(file_uri, embedding_dim, vocab, namespace)
  File "/Users/mmir/Desktop/openie/venv/lib/python3.7/site-packages/allennlp/modules/token_embedders/embedding.py", line 418, in _read_embeddings_from_text_file
    "No embeddings of correct dimension found; you probably "
allennlp.common.checks.ConfigurationError: No embeddings of correct dimension found; you probably misspecified your embedding_dim parameter, or didn't pre-populate your Vocabulary
```

**Comment by MM-Vianai** [comment]
@AkshitaB the issue is being closed however the original problem remains unsolved. Can this be opened again?
