### ISSUE TITLE
Input, output and indices must be on the current device

### ISSUE THREAD

**Issue by david-waterworth** [allenai/allennlp#5186]
Reading the documentation for the Trainer "If you are training your model using GPUs, your model should already be on the correct device. (If you are using our train command this will be handled for you.)" - https://docs.allennlp.org/main/api/training/trainer/

When I run the tutorial (https://github.com/allenai/allennlp-guide/blob/master/quick_start/train.py) the trainer throws `Input, output and indices must be on the current device`.

The issue appears to be that the data is copied to the gpu but the model isn't. I may be misreading the documentation - the quote above (for the model argument) seems to conflict with the default value for the cuda_device argument (-1 i.e. cpu).

But if this is the case shouldn't the data be loaded to the cpu not gpu?

Edit: Note the documentation implies the default for the trainer argument `cuda_device` is -1 (cpu) but in fact it is None (which resutls in the `Trainer` super class automatically detecting the presence of cuda and setting it to 0. But the constructor of `GradientDescentTrainer` contains the following:

        # I am not calling move_to_gpu here, because if the model is
        # not already on the GPU then the optimizer is going to be wrong.
        self.model = model

So it seems to be deliberate to require that the model already be on the gpu. But is this case the code in Trainer:

        if cuda_device is None:
            from torch import cuda

            if cuda.device_count() > 0:
                cuda_device = 0
            else:
                cuda_device = -1

        self.cuda_device = int_to_device(cuda_device)

Results in self.cuda_device='cuda' regardless of the location of the model (since cuda_device is None by default) . So the documentation appears incorrect and device management isn't handled by the Trainer. It's this code that results in the data loader moving the tensors to device 0.

So it seems you have to either pass `device = -1` to the trainer if the model is on the cpu, or device = None (or 0) if it's on the gpu. 

## Checklist

- [ ] I have verified that the issue exists against the `main` branch of AllenNLP.
- [ x] I have read the relevant section in the [contribution guide](https://github.com/allenai/allennlp/blob/main/CONTRIBUTING.md#bug-fixes-and-new-features) on reporting bugs.
- [ x] I have checked the [issues list](https://github.com/allenai/allennlp/issues) for similar or identical bug reports.
- [ x] I have checked the [pull requests list](https://github.com/allenai/allennlp/pulls) for existing proposed fixes.
- [ x] I have checked the [CHANGELOG](https://github.com/allenai/allennlp/blob/main/CHANGELOG.md) and the [commit log](https://github.com/allenai/allennlp/commits/main) to find out if the bug was already fixed in the main branch.
- [ x] I have included in the "Description" section below a traceback from any exceptions related to this bug.
- [ ] I have included in the "Related issues or possible duplicates" section beloew all related issues and possible duplicate issues (If there are none, check this box anyway).
- [ x] I have included in the "Environment" section below the name of the operating system and Python version that I was using when I discovered this bug.
- [x ] I have included in the "Environment" section below the output of `pip freeze`.
- [ x] I have included in the "Steps to reproduce" section below a minimally reproducible example.

## Description

The quickstart (https://github.com/allenai/allennlp-guide/blob/master/quick_start/train.py) fails out of the box since the data and model aren't being loaded to the same device. This appers contrary to the train documentation which implies this is handled automatically.

<details>
<summary><b>Python traceback:</b></summary>
<p>

```
Traceback (most recent call last):
  File "/home/david/.pyenv/versions/3.7.6/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/david/.pyenv/versions/3.7.6/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/david/.vscode/extensions/ms-python.python-2021.4.765268190/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/david/.vscode/extensions/ms-python.python-2021.4.765268190/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/home/david/.vscode/extensions/ms-python.python-2021.4.765268190/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/home/david/.pyenv/versions/3.7.6/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/david/.pyenv/versions/3.7.6/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/david/.pyenv/versions/3.7.6/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/david/dev/allennlp-guide/quick_start/train.py", line 160, in <module>
    run_training_loop()
  File "/home/david/dev/allennlp-guide/quick_start/train.py", line 154, in run_training_loop
    trainer.train()
  File "/home/david/.pyenv/versions/3.7.6/envs/allennlp/lib/python3.7/site-packages/allennlp/training/trainer.py", line 740, in train
    metrics, epoch = self._try_train()
  File "/home/david/.pyenv/versions/3.7.6/envs/allennlp/lib/python3.7/site-packages/allennlp/training/trainer.py", line 772, in _try_train
    train_metrics = self._train_epoch(epoch)
  File "/home/david/.pyenv/versions/3.7.6/envs/allennlp/lib/python3.7/site-packages/allennlp/training/trainer.py", line 506, in _train_epoch
    batch_outputs = self.batch_outputs(batch, for_training=True)
  File "/home/david/.pyenv/versions/3.7.6/envs/allennlp/lib/python3.7/site-packages/allennlp/training/trainer.py", line 391, in batch_outputs
    output_dict = self._pytorch_model(**batch)
  File "/home/david/.pyenv/versions/3.7.6/envs/allennlp/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/david/dev/allennlp-guide/quick_start/train.py", line 68, in forward
    embedded_text = self.embedder(text)
  File "/home/david/.pyenv/versions/3.7.6/envs/allennlp/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/david/.pyenv/versions/3.7.6/envs/allennlp/lib/python3.7/site-packages/allennlp/modules/text_field_embedders/basic_text_field_embedder.py", line 99, in forward
    token_vectors = embedder(list(tensors.values())[0], **forward_params_values)
  File "/home/david/.pyenv/versions/3.7.6/envs/allennlp/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/david/.pyenv/versions/3.7.6/envs/allennlp/lib/python3.7/site-packages/allennlp/modules/token_embedders/embedding.py", line 203, in forward
    sparse=self.sparse,
  File "/home/david/.pyenv/versions/3.7.6/envs/allennlp/lib/python3.7/site-packages/torch/nn/functional.py", line 1916, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Input, output and indices must be on the current device
```

</p>
</details>

## Related issues or possible duplicates

- None

## Environment

OS: Linux (ubuntu 20.04)

Python version: 3.7.6

<details>
<summary><b>Output of <code>pip freeze</code>:</b></summary>
<p>

```
allennlp==2.4.0
attrs==21.1.0
blis==0.7.4
boto3==1.17.68
botocore==1.20.68
cached-property==1.5.2
catalogue==2.0.4
certifi==2020.12.5
chardet==4.0.0
click==7.1.2
configparser==5.0.2
cymem==2.0.5
docker-pycreds==0.4.0
filelock==3.0.12
gitdb==4.0.7
GitPython==3.1.14
h5py==3.2.1
huggingface-hub==0.0.8
idna==2.10
importlib-metadata==4.0.1
iniconfig==1.1.1
Jinja2==2.11.3
jmespath==0.10.0
joblib==1.0.1
jsonnet==0.17.0
lmdb==1.2.1
MarkupSafe==1.1.1
more-itertools==8.7.0
murmurhash==1.0.5
nltk==3.6.2
numpy==1.20.2
overrides==3.1.0
packaging==20.9
pathtools==0.1.2
pathy==0.5.2
Pillow==8.2.0
pluggy==0.13.1
preshed==3.0.5
promise==2.3
protobuf==3.15.8
psutil==5.8.0
py==1.10.0
pydantic==1.7.3
pyparsing==2.4.7
pytest==6.2.4
python-dateutil==2.8.1
PyYAML==5.4.1
regex==2021.4.4
requests==2.25.1
s3transfer==0.4.2
sacremoses==0.0.45
scikit-learn==0.24.2
scipy==1.6.3
sentencepiece==0.1.95
sentry-sdk==1.1.0
shortuuid==1.0.1
six==1.16.0
smart-open==3.0.0
smmap==4.0.0
spacy==3.0.6
spacy-legacy==3.0.5
srsly==2.4.1
subprocess32==3.5.4
tensorboardX==2.2
thinc==8.0.3
threadpoolctl==2.1.0
tokenizers==0.10.2
toml==0.10.2
torch==1.8.1+cu111
torchaudio==0.8.1
torchvision==0.9.1+cu111
tqdm==4.60.0
transformers==4.5.1
typer==0.3.2
typing-extensions==3.10.0.0
urllib3==1.26.4
wandb==0.10.29
wasabi==0.8.2
zipp==3.4.1
```

</p>
</details>

## Steps to reproduce

Run example source (note, my machine has two gpu's)
<details>
<summary><b>Example source:</b></summary>
<p>

https://github.com/allenai/allennlp-guide/blob/master/quick_start/train.py

</p>
</details>

**Comment by epwalsh** [comment]
Thanks @david-waterworth, the docstring for `cuda_device` is indeed out-of-date. This PR addresses that: https://github.com/allenai/allennlp/pull/5188. I'll follow up with another PR to update the guide.
