### ISSUE TITLE
KeyError: 'Using PretrainedTransformerIndexer but field text_id is not set for the following token: [CLS]'

### ISSUE THREAD

**Issue by rkoystart** [allenai/allennlp#5196]
I recently updated my allennlp version from 0.9.0 to 1.0.0. After this update when i run th following script 

sample.py

```
import logging
import os
import pathlib
import glob

import torch
from allennlp.data.token_indexers.pretrained_transformer_indexer import (
    PretrainedTransformerIndexer,
)
from allennlp.data.vocabulary import Vocabulary
from allennlp.modules.text_field_embedders import BasicTextFieldEmbedder
from allennlp.modules.token_embedders.pretrained_transformer_embedder import (
    PretrainedTransformerEmbedder,
)

from predictor import SamplePredictor
from dataset_reader import SampleDatasetReader
from models import SampleSequenceTagging

def main():
    token_indexer = PretrainedTransformerIndexer(
            "bert-base-uncased")
    token_indexer = {"tokens": token_indexer}

    dataset_reader = SampleDatasetReader(token_indexer)
            # output_size = len(dataset_reader.tag2index.keys()) + 1

    vocab = Vocabulary.from_files("Downloads//level_1/vocabulary", oov_token="no label")
    output_size =  vocab.get_vocab_size("labels")

    print("output_size is: ",output_size)
    bert_model = PretrainedTransformerEmbedder("bert-base-uncased")
    bert_model = BasicTextFieldEmbedder({"tokens": bert_model})
            # bert_model =  BertModel.from_pretrained("bert-base-uncased")

    model = SampleSequenceTagging(bert_model, output_size, vocab)

    with open(os.path.join("Downloads/level_1/", "best.th"), "rb") as reader:
        model.load_state_dict(
                    torch.load(reader, map_location=torch.device("cpu"))
                )

    model.eval()
    model = SamplePredictor(model, dataset_reader)

    output =  model.predict("The failure of Discloser to enforce its rights under this Agreement at any time for any period shall not be construed as a waiver of such rights.  Unless expressly provided otherwise, each right and remedy in this Agreement is in addition to any other right or remedy, at law or in equity, and the exercise of one right or remedy will not be deemed a waiver of any other right or remedy.")
    print("output is : ",output)

if __name__ == "__main__":
    main()

```

i am getting the following error

```
Traceback (most recent call last):
  File "sample.py", line 53, in <module>
    main()
  File "sample.py", line 49, in main
    output =  model.predict("The failure of Discloser to enforce its rights under this Agreement at any time for any period shall not be construed as a waiver of such rights.  Unless expressly provided otherwise, each right and remedy in this Agreement is in addition to any other right or remedy, at law or in equity, and the exercise of one right or remedy will not be deemed a waiver of any other right or remedy.")
  File "/home/rkoy/predictor/predictor.py", line 15, in predict
    labels = self._predict_sentence(sentence.text)
  File "/home/rkoy/predictor/predictor.py", line 50, in _predict_sentence
    output = self.predict_json({"sentence": sentence})
  File "/home/rkoy/predictor/predictor.py", line 124, in predict_json
    return self.predict_instance(instance)
  File "/home/rkoy/anaconda3/envs/level_1_and_2/lib/python3.8/site-packages/allennlp/predictors/predictor.py", line 182, in predict_instance
    outputs = self._model.forward_on_instance(instance)
  File "/home/rkoy/anaconda3/envs/level_1_and_2/lib/python3.8/site-packages/allennlp/models/model.py", line 146, in forward_on_instance
    return self.forward_on_instances([instance])[0]
  File "/home/rkoy/anaconda3/envs/level_1_and_2/lib/python3.8/site-packages/allennlp/models/model.py", line 170, in forward_on_instances
    dataset.index_instances(self.vocab)
  File "/home/rkoy/anaconda3/envs/level_1_and_2/lib/python3.8/site-packages/allennlp/data/batch.py", line 159, in index_instances
    instance.index_fields(vocab)
  File "/home/rkoy/anaconda3/envs/level_1_and_2/lib/python3.8/site-packages/allennlp/data/instance.py", line 75, in index_fields
    field.index(vocab)
  File "/home/rkoy/anaconda3/envs/level_1_and_2/lib/python3.8/site-packages/allennlp/data/fields/text_field.py", line 68, in index
    self._indexed_tokens[indexer_name] = indexer.tokens_to_indices(self.tokens, vocab)
  File "/home/rkoyanaconda3/envs/level_1_and_2/lib/python3.8/site-packages/allennlp/data/token_indexers/pretrained_transformer_indexer.py", line 95, in tokens_to_indices
    indices, type_ids = self._extract_token_and_type_ids(tokens)
  File "/home/rkoy/anaconda3/envs/level_1_and_2/lib/python3.8/site-packages/allennlp/data/token_indexers/pretrained_transformer_indexer.py", line 137, in _extract_token_and_type_ids
    raise KeyError(
KeyError: 'Using PretrainedTransformerIndexer but field text_id is not set for the following token: [CLS]'

```
Can anyone let me know , where i am making a mistake or missed out any things.
I am not getting any error when in run in allennlp 0.9.0 , i am getting an error when i run in allennlp 1.0.0
Thanks in advance!!!

**Comment by epwalsh** [comment]
Can you post the code for your custom predictor, model, and dataset reader? Otherwise I won't be able to reproduce.
