### ISSUE TITLE
'from allennlp.commands.elmo import ElmoEmbedder' not work even in 0.9.0

### ISSUE THREAD

**Issue by TITC** [allenai/allennlp#5203]
> > We removed the `elmo` command in v1.0. If you want to use the `elmo` command then you need to check out v0.9.0. We removed this command because `elmo` is becoming a bit old and we didn't think it made sense to continue supporting it as a top-level command.
> 
> version 0.9.0 worked fine. thx.

version 0.9.0 not work for me,  any advice is welcome
```
Traceback (most recent call last):
  File "/content/sow-reap-paraphrasing/processing/get_elmo_embeds.py", line 1, in <module>
    from allennlp.commands.elmo import ElmoEmbedder
  File "/usr/local/lib/python3.7/dist-packages/allennlp/commands/__init__.py", line 8, in <module>
    from allennlp.commands.configure import Configure
  File "/usr/local/lib/python3.7/dist-packages/allennlp/commands/configure.py", line 26, in <module>
    from allennlp.service.config_explorer import make_app
  File "/usr/local/lib/python3.7/dist-packages/allennlp/service/config_explorer.py", line 24, in <module>
    from allennlp.common.configuration import configure, choices
  File "/usr/local/lib/python3.7/dist-packages/allennlp/common/configuration.py", line 17, in <module>
    from allennlp.data.dataset_readers import DatasetReader
  File "/usr/local/lib/python3.7/dist-packages/allennlp/data/__init__.py", line 1, in <module>
    from allennlp.data.dataset_readers.dataset_reader import DatasetReader
  File "/usr/local/lib/python3.7/dist-packages/allennlp/data/dataset_readers/__init__.py", line 10, in <module>
    from allennlp.data.dataset_readers.ccgbank import CcgBankDatasetReader
  File "/usr/local/lib/python3.7/dist-packages/allennlp/data/dataset_readers/ccgbank.py", line 9, in <module>
    from allennlp.data.dataset_readers.dataset_reader import DatasetReader
  File "/usr/local/lib/python3.7/dist-packages/allennlp/data/dataset_readers/dataset_reader.py", line 8, in <module>
    from allennlp.data.instance import Instance
  File "/usr/local/lib/python3.7/dist-packages/allennlp/data/instance.py", line 3, in <module>
    from allennlp.data.fields.field import DataArray, Field
  File "/usr/local/lib/python3.7/dist-packages/allennlp/data/fields/__init__.py", line 7, in <module>
    from allennlp.data.fields.array_field import ArrayField
  File "/usr/local/lib/python3.7/dist-packages/allennlp/data/fields/array_field.py", line 10, in <module>
    class ArrayField(Field[numpy.ndarray]):
  File "/usr/local/lib/python3.7/dist-packages/allennlp/data/fields/array_field.py", line 50, in ArrayField
    @overrides
  File "/usr/local/lib/python3.7/dist-packages/overrides/overrides.py", line 88, in overrides
    return _overrides(method, check_signature, check_at_runtime)
  File "/usr/local/lib/python3.7/dist-packages/overrides/overrides.py", line 114, in _overrides
    _validate_method(method, super_class, check_signature)
  File "/usr/local/lib/python3.7/dist-packages/overrides/overrides.py", line 135, in _validate_method
    ensure_signature_is_compatible(super_method, method, is_static)
  File "/usr/local/lib/python3.7/dist-packages/overrides/signature.py", line 93, in ensure_signature_is_compatible
    ensure_return_type_compatibility(super_type_hints, sub_type_hints, method_name)
  File "/usr/local/lib/python3.7/dist-packages/overrides/signature.py", line 288, in ensure_return_type_compatibility
    f"{method_name}: return type `{sub_return}` is not a `{super_return}`."
TypeError: ArrayField.empty_field: return type `None` is not a `<class 'allennlp.data.fields.field.Field'>`.
```

_Originally posted by @TITC in https://github.com/allenai/allennlp/issues/4384#issuecomment-841781842_

**Comment by Qi-HuT** [comment]
Did you solve the problem?

**Comment by TITC** [comment]
> Did you solve the problem?

no

**Comment by AkshitaB** [comment]
@TITC  It appears to be because the latest `overrides` package breaks the older versions of allennlp (please see https://github.com/allenai/allennlp/issues/5197). 

If you must use allennlp `0.9.0`, as per a workaround suggested on that issue, can you try downgrading the version of `overrides` to `3.1.0`?

**Comment by TITC** [comment]
> @TITC It appears to be because the latest `overrides` package breaks the older versions of allennlp (please see #5197).
> 
> As per a workaround suggested on that issue, can you try downgrading the version of `overrides` to `3.1.0`?

It works, great! Thanks for your kindly help.
