### ISSUE TITLE
TypeError: ArrayField.empty_field: return type `None` is not a `<class 'allennlp.data.fields.field.Field'>

### ISSUE THREAD

**Issue by kaloon2009** [allenai/allennlp#5217]
I used Colab for my project. 
I installed  _allennlp==0.9.0_
When I import _from allennlp.predictors.predictor import Predictor_

I get a error as below: 

    ---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-20-f25591a9ae36> in <module>()
      2 nlp = spacy.load("en_core_web_sm")
      3 
----> 4 from allennlp.predictors.predictor import Predictor
      5 predictor = Predictor.from_path("https://s3-us-west-2.amazonaws.com/allennlp/models/elmo-constituency-parser-2018.03.14.tar.gz")

12 frames
/usr/local/lib/python3.7/dist-packages/allennlp/predictors/__init__.py in <module>()
      7 a ``Predictor`` that wraps it.
      8 """
----> 9 from allennlp.predictors.predictor import Predictor
     10 from allennlp.predictors.atis_parser import AtisParserPredictor
     11 from allennlp.predictors.biaffine_dependency_parser import BiaffineDependencyParserPredictor

/usr/local/lib/python3.7/dist-packages/allennlp/predictors/predictor.py in <module>()
     10 from allennlp.common.checks import ConfigurationError
     11 from allennlp.common.util import JsonDict, sanitize
---> 12 from allennlp.data import DatasetReader, Instance
     13 from allennlp.data.dataset import Batch
     14 from allennlp.models import Model

/usr/local/lib/python3.7/dist-packages/allennlp/data/__init__.py in <module>()
      2 from allennlp.data.fields.field import DataArray, Field
      3 from allennlp.data.instance import Instance
----> 4 from allennlp.data.iterators.data_iterator import DataIterator
      5 from allennlp.data.token_indexers.token_indexer import TokenIndexer, TokenType
      6 from allennlp.data.tokenizers.token import Token

/usr/local/lib/python3.7/dist-packages/allennlp/data/iterators/__init__.py in <module>()
      4 """
      5 
----> 6 from allennlp.data.iterators.data_iterator import DataIterator
      7 from allennlp.data.iterators.basic_iterator import BasicIterator
      8 from allennlp.data.iterators.bucket_iterator import BucketIterator

/usr/local/lib/python3.7/dist-packages/allennlp/data/iterators/data_iterator.py in <module>()
     11 from allennlp.common.util import is_lazy, lazy_groups_of, ensure_list
     12 from allennlp.data.dataset import Batch
---> 13 from allennlp.data.fields import MetadataField
     14 from allennlp.data.instance import Instance
     15 from allennlp.data.vocabulary import Vocabulary

/usr/local/lib/python3.7/dist-packages/allennlp/data/fields/__init__.py in <module>()
      5 
      6 from allennlp.data.fields.field import Field
----> 7 from allennlp.data.fields.array_field import ArrayField
      8 from allennlp.data.fields.adjacency_field import AdjacencyField
      9 from allennlp.data.fields.index_field import IndexField

/usr/local/lib/python3.7/dist-packages/allennlp/data/fields/array_field.py in <module>()
      8 
      9 
---> 10 class ArrayField(Field[numpy.ndarray]):
     11     """
     12     A class representing an array, which could have arbitrary dimensions.

/usr/local/lib/python3.7/dist-packages/allennlp/data/fields/array_field.py in ArrayField()
     48         return tensor
     49 
---> 50     @overrides
     51     def empty_field(self):  # pylint: disable=no-self-use
     52         # Pass the padding_value, so that any outer field, e.g., `ListField[ArrayField]` uses the

/usr/local/lib/python3.7/dist-packages/overrides/overrides.py in overrides(method, check_signature, check_at_runtime)
     86     """
     87     if method is not None:
---> 88         return _overrides(method, check_signature, check_at_runtime)
     89     else:
     90         return functools.partial(

/usr/local/lib/python3.7/dist-packages/overrides/overrides.py in _overrides(method, check_signature, check_at_runtime)
    112                 return wrapper  # type: ignore
    113             else:
--> 114                 _validate_method(method, super_class, check_signature)
    115                 return method
    116     raise TypeError(f"{method.__qualname__}: No super class method found")

/usr/local/lib/python3.7/dist-packages/overrides/overrides.py in _validate_method(method, super_class, check_signature)
    133         and not isinstance(super_method, property)
    134     ):
--> 135         ensure_signature_is_compatible(super_method, method, is_static)
    136 
    137 

/usr/local/lib/python3.7/dist-packages/overrides/signature.py in ensure_signature_is_compatible(super_callable, sub_callable, is_static)
     91 
     92     if super_type_hints is not None and sub_type_hints is not None:
---> 93         ensure_return_type_compatibility(super_type_hints, sub_type_hints, method_name)
     94         ensure_all_kwargs_defined_in_sub(
     95             super_sig, sub_sig, super_type_hints, sub_type_hints, is_static, method_name

/usr/local/lib/python3.7/dist-packages/overrides/signature.py in ensure_return_type_compatibility(super_type_hints, sub_type_hints, method_name)
    286     if not _issubtype(sub_return, super_return) and super_return is not None:
    287         raise TypeError(
--> 288             f"{method_name}: return type `{sub_return}` is not a `{super_return}`."
    289         )

TypeError: ArrayField.empty_field: return type `None` is not a `<class 'allennlp.data.fields.field.Field'>`.

Please help!

**Comment by AkshitaB** [comment]
@kaloon2009 It appears to be because the latest `overrides` package breaks the older versions of allennlp (please see https://github.com/allenai/allennlp/issues/5197). 

If you must use allennlp `0.9.0`, as per a workaround suggested on that issue, can you try downgrading the version of `overrides` to `3.1.0`? 

Otherwise, try upgrading to newer versions of allennlp.

**Comment by kaloon2009** [comment]
Thanks @AkshitaB  I upgrade it to the last version by runing "_pip install allennlp_" 
Now, I faced another error : 


     ---------------------------------------------------------------------------
ConfigurationError                        Traceback (most recent call last)
<ipython-input-8-f25591a9ae36> in <module>()
      3 
      4 from allennlp.predictors.predictor import Predictor
----> 5 predictor = Predictor.from_path("https://s3-us-west-2.amazonaws.com/allennlp/models/elmo-constituency-parser-2018.03.14.tar.gz")

4 frames
/usr/local/lib/python3.7/dist-packages/allennlp/predictors/predictor.py in from_path(cls, archive_path, predictor_name, cuda_device, dataset_reader_to_load, frozen, import_plugins, overrides)
    360             plugins.import_plugins()
    361         return Predictor.from_archive(
--> 362             load_archive(archive_path, cuda_device=cuda_device, overrides=overrides),
    363             predictor_name,
    364             dataset_reader_to_load=dataset_reader_to_load,

/usr/local/lib/python3.7/dist-packages/allennlp/models/archival.py in load_archive(archive_file, cuda_device, overrides, weights_file)
    203         # Instantiate model and dataset readers. Use a duplicate of the config, as it will get consumed.
    204         dataset_reader, validation_dataset_reader = _load_dataset_readers(
--> 205             config.duplicate(), serialization_dir
    206         )
    207         model = _load_model(config.duplicate(), weights_path, serialization_dir, cuda_device)

/usr/local/lib/python3.7/dist-packages/allennlp/models/archival.py in _load_dataset_readers(config, serialization_dir)
    229 
    230     dataset_reader = DatasetReader.from_params(
--> 231         dataset_reader_params, serialization_dir=serialization_dir
    232     )
    233     validation_dataset_reader = DatasetReader.from_params(

/usr/local/lib/python3.7/dist-packages/allennlp/common/from_params.py in from_params(cls, params, constructor_to_call, constructor_to_inspect, **extras)
    571                 "type",
    572                 choices=as_registrable.list_available(),
--> 573                 default_to_first_choice=default_to_first_choice,
    574             )
    575             subclass, constructor_name = as_registrable.resolve_class_name(choice)

/usr/local/lib/python3.7/dist-packages/allennlp/common/params.py in pop_choice(self, key, choices, default_to_first_choice, allow_class_names)
    350                 """{"model": "my_module.models.MyModel"} to have it imported automatically."""
    351             )
--> 352             raise ConfigurationError(message)
    353         return value
    354 

ConfigurationError: ptb_trees not in acceptable choices for dataset_reader.type: ['babi', 'conll2003', 'interleaving', 'multitask', 'multitask_shim', 'sequence_tagging', 'sharded', 'text_classification_json']. You should either use the --include-package flag to make sure the correct module is loaded, or use a fully qualified class name in your config file like {"model": "my_module.models.MyModel"} to have it imported automatically

**Comment by AkshitaB** [comment]
@kaloon2009 You will also need to install the corresponding version of `allennlp-models`. You can refer to [this](https://demo.allennlp.org/constituency-parsing) for examples on usage.

**Comment by kaloon2009** [comment]
Thanks @AkshitaB 
It's working now by installing the _allennlp-models_

I was following an old guideline for allennlp. That why I got an error

**Comment by AkshitaB** [comment]
@kaloon2009 Perfect!

**Comment by vishwajeet19128** [comment]
I installed allennp version 0.6.0 which was required for torch version 0.4.1. but while running the command it is showing the same error. I also installed allennlp-models version 1.0.0 but its still showing same error.
I am trying to reproduce the results of following repo : https://github.com/vishwajeet19128/semeval2019-hyperpartisan-bertha-von-suttner
error : 
Traceback (most recent call last):                                                                                           File "Preprocessing/line2elmo2.py", line 24, in <module>                                                                     from allennlp.commands.elmo import ElmoEmbedder                                                                          File "/home/vishwajeet19128/model1/venv/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 6, in <module>      from allennlp.commands.configure import Configure                                                                        File "/home/vishwajeet19128/model1/venv/lib/python3.6/site-packages/allennlp/commands/configure.py", line 22, in <module>                                                                                                                               from allennlp.common.configuration import configure, Config, render_config                                               File "/home/vishwajeet19128/model1/venv/lib/python3.6/site-packages/allennlp/common/configuration.py", line 17, in <module>                                                                                                                             from allennlp.data.dataset_readers import DatasetReader                                                                  File "/home/vishwajeet19128/model1/venv/lib/python3.6/site-packages/allennlp/data/__init__.py", line 1, in <module>          from allennlp.data.dataset_readers.dataset_reader import DatasetReader                                                   File "/home/vishwajeet19128/model1/venv/lib/python3.6/site-packages/allennlp/data/dataset_readers/__init__.py", line 10, in <module>                                                                                                                    from allennlp.data.dataset_readers.ccgbank import CcgBankDatasetReader                                                   File "/home/vishwajeet19128/model1/venv/lib/python3.6/site-packages/allennlp/data/dataset_readers/ccgbank.py", line 8, in <module>                                                                                                                      from allennlp.data.dataset_readers.dataset_reader import DatasetReader                                                   File "/home/vishwajeet19128/model1/venv/lib/python3.6/site-packages/allennlp/data/dataset_readers/dataset_reader.py", line 4, in <module>                                                                                                               from allennlp.data.instance import Instance                                                                              File "/home/vishwajeet19128/model1/venv/lib/python3.6/site-packages/allennlp/data/instance.py", line 3, in <module>          from allennlp.data.fields.field import DataArray, Field                                                                  File "/home/vishwajeet19128/model1/venv/lib/python3.6/site-packages/allennlp/data/fields/__init__.py", line 7, in <module>                                                                                                                              from allennlp.data.fields.array_field import ArrayField                                                                  File "/home/vishwajeet19128/model1/venv/lib/python3.6/site-packages/allennlp/data/fields/array_field.py", line 10, in <module>                                                                                                                          class ArrayField(Field[numpy.ndarray]):                                                                                  File "/home/vishwajeet19128/model1/venv/lib/python3.6/site-packages/allennlp/data/fields/array_field.py", line 44, in ArrayField                                                                                                                        @overrides                                                                                                               File "/home/vishwajeet19128/model1/venv/lib/python3.6/site-packages/overrides/overrides.py", line 88, in overrides           return _overrides(method, check_signature, check_at_runtime)                                                             File "/home/vishwajeet19128/model1/venv/lib/python3.6/site-packages/overrides/overrides.py", line 114, in _overrides         _validate_method(method, super_class, check_signature)                                                                   File "/home/vishwajeet19128/model1/venv/lib/python3.6/site-packages/overrides/overrides.py", line 135, in _validate_method                                                                                                                              ensure_signature_is_compatible(super_method, method, is_static)                                                          File "/home/vishwajeet19128/model1/venv/lib/python3.6/site-packages/overrides/signature.py", line 93, in ensure_signature_is_compatible                                                                                                                 ensure_return_type_compatibility(super_type_hints, sub_type_hints, method_name)                                          File "/home/vishwajeet19128/model1/venv/lib/python3.6/site-packages/overrides/signature.py", line 288, in ensure_return_type_compatibility                                                                                                              f"{method_name}: return type `{sub_return}` is not a `{super_return}`."                                                TypeError: ArrayField.empty_field: return type `None` is not a `allennlp.data.fields.field.Field`
