### ISSUE TITLE
gpu_memory_mb

### ISSUE THREAD

**Issue by ICanFlyGFC** [allenai/allennlp#5364]
## Description

<details>
I use allennlp 0.9.0 and run my code without GPU.
I also use "cuda_device": -1
but:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/allennlp/common/util.py", line 378, in gpu_memory_mb
    encoding='utf-8')
  File "/usr/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['nvidia-smi', '--query-gpu=memory.used', '--format=csv,nounits,noheader']' returned non-zero exit status 9.
2021-08-18 09:42:41,987 - INFO - allennlp.training.trainer - Training
  0%|          | 0/110 [00:00<?, ?it/s]^C

thanks
<summary><b>Python traceback:</b></summary>
<p>

```
```

</p>
</details>

</details>

**Comment by ICanFlyGFC** [comment]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/allennlp/common/util.py", line 378, in gpu_memory_mb
    encoding='utf-8')
  File "/usr/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['nvidia-smi', '--query-gpu=memory.used', '--format=csv,nounits,noheader']' returned non-zero exit status 9.
2021-08-18 09:42:41,987 - INFO - allennlp.training.trainer - Training
  0%|          | 0/110 [00:00<?, ?it/s]^C

**Comment by ICanFlyGFC** [comment]
I  already use "cuda_device": -1,

**Comment by AkshitaB** [comment]
@ICanFlyGFC Hi, is there a reason why you're using the `0.9.0` version? Can you try using latest allennlp version?

**Comment by dirkgr** [comment]
I think in version 0.9 you have to specify no CUDA device at all.
