### ISSUE TITLE
Possibility of a memory leak on gpu when using multi-process dataloader and executing `allennlp train` in a subprocess.

### ISSUE THREAD

**Issue by dhruvdcoder** [allenai/allennlp#5369]
I post this as a question because I am not sure if something like this can happen. However, if you deem that something like this can, I can come up with a minimal reproducible example.

## Context

I use [wandb sweeps](https://docs.wandb.ai/guides/sweeps/quickstart) to tune the parameters of my model. The wandb client creates a sweep "agent" which communicates with the wandb server and receives hyperparameters which are then used to execute `allennlp train` with parameter overrides. The sweep agent executes `allennlp train` in a subprocess. Lets call one such execution as a 'run'. Different hyperparameter settings are tried serially by the agent by executing runs serially. Sometimes, the wandb server asks the sweep agent to end an ongoing run. The sweep agent does so by calling `.terminate()` on the `allennlp train` subprocess. Note that the `finally` blocks in the multiprocess dataloader will not be executed when `allennlp train` receives a SIGTERM ([ref](https://stackoverflow.com/questions/49262379/does-finally-always-execute-in-python)).

## Problem

As I understand the 'multiprocess' dataloader is the default now. For smaller datasets, I do not set the `num_workers` and hence, the dataloader does not spawn any children processes. In this scenario, a single sweep agent runs hundreds of runs without any issue.

However, with larger datasets, when I set `num_workers=5`, all the runs after the first runs started by an agent fail due to CUDA memory exhaustion. On closer inspection, I observed that when an agent stops a run and starts the next run, the gpu memory of the first run is not released and the second run only has the leftover memory to use and hence fails. Moreover, I also see that the number of processes related to sweep agent increase with time--meaning that the termination of runs might be leaving zombie processes. 

Do you think that this could be a valid explanation of my issue with using multiprocess dataloader with wandb sweep? If so what further information would I need to fix this issue? One thing, I can think of is adding a signal handler for SIGTERM and have it generate a `KeyboardInterrupt` as that will ensure that all the `finally` blocks are executed.

**Comment by epwalsh** [comment]
> Moreover, I also see that the number of processes related to sweep agent increase with time--meaning that the termination of runs might be leaving zombie processes.

It sounds like the data loading workers are sticking around even after their parent training process is killed? The `daemon=True` argument here is supposed to prevent that from happening, but maybe it doesn't work the same when the original process is itself a subprocess 🤔

https://github.com/allenai/allennlp/blob/13de38d17dd5a1c67e5327328c01837c6e40f87d/allennlp/data/data_loaders/multiprocess_data_loader.py#L446

**Comment by epwalsh** [comment]
But catching SIGTERM seems like a good idea anyway. Can you give that a try?

**Comment by dhruvdcoder** [comment]
I have tried several things but no matter what I try, the children processes (children of `allennlp train`) do not seem to terminate. I am using the following script to launch the training run as a subprocess. This is how [wandb agent](https://github.com/wandb/client/blob/5cb3f50f64cb4ee5ec7389a7e8db8d6787d48108/wandb/wandb_agent.py#L30) starts a training run.

```
import subprocess
import os
import time

popen = subprocess.Popen(['allennlp', 'train', 'temp.json', '-s', 'temp_', '-f'], preexec_fn=os.setpgrp)

 for i in range(20): # Let the run go on for long enough to load the data and start training
    time.sleep(10)
    res = popen.poll()
    if res is None:
       print(f"step {i}")
       continue
 print("About to terminmate the main subprocess")
 popen.terminate()
 time.sleep(100)
 print("sending kill")
 popen.kill()

# wait for the run's subprocess to exit.
popen.wait()

```
Things tried:

1. I have tried installing a SIGTERM handler that raises a KeyboardInterrupt at two places:  in `commands/train.py` and in `multiprocess_dataloader.py` after the workers are created but neither of them seem to help.
https://github.com/allenai/allennlp/blob/5dc80a650090c700bd4fc158f46257170fe3e8cb/allennlp/data/data_loaders/multiprocess_data_loader.py#L450

```
import signal

def handle_signal(sig, frame):
    logger.info(f"Script recieved signal: {sig}")
    logger.info("raising SIGINT")
    raise KeyboardInterrupt

signal.signal(signal.SIGTERM, handle_signal)
```

2. Tried all the things mentioned in the comments for multiprocess dataloader, i.e., trying all methods for creating children, setting the number of threads to 0 for all multithreaded modules, but nothing changes.

3. I also tried comparing the code with pytorch's multiprocess dataloader. For the comments it seems like they have explicitly tried to care of the case when the dataloader itself is a subprocess. https://github.com/pytorch/pytorch/blob/master/torch/utils/data/dataloader.py#L657
I was not able to identify the exact component was responsible for this, but there might be hints in their code to fix this issue.

Thanks.

**Comment by dhruvdcoder** [comment]
All right, the only thing that has worked is the following combination 
1. Install SIGTERM handler before the creation of workers. Simply adding it in the `commands/train.py` works.
2. Call `queue.cancel_join_thread()` in the workers, i.e. first line of `_instance_worker` and `_batch_worker`.

Ref:
https://docs.python.org/3/library/multiprocessing.html#multiprocessing.Queue.cancel_join_thread

**Comment by epwalsh** [comment]
@dhruvdcoder thanks for all the details. Based on your code snippets I created a minimal reproducible example in this gist: https://gist.github.com/epwalsh/e43b8af900d01534cbf921ab52bc0d67.

This confirms that installing the SIGTERM handler will work (although if the main process is unexpectedly killed for other reasons, we'll probably still have an issue with zombie child processes, and I couldn't find a solution for that yet). I don't think `queue.cancel_join_thread()` is necessary. Can you confirm?

As for

> This creates another issue, since the sigterm handlers are inherited by the workers, when the main process calls worker.terminate() as part of the usual call to _join_workers() on each worker, the worker shutdown by raising KeyboardInterrupt. This works fine but prints a lot of error messages (one per worker).

This is probably fine. But we could also catch these specific errors in the workers and avoid printing the tracebacks in that case.

**Comment by dhruvdcoder** [comment]
Thank you @epwalsh, this indeed works as expected. The `queue.cancel_join_thread()` is not required.

> This is probably fine. But we could also catch these specific errors in the workers and avoid printing the tracebacks in that case.

I think this is happening because `worker.terminate()` is being called as part of the usual closing down of the workers. The `_join_workers` is reaching the `terminate` call more often than we suspect or expect. Essentially, I see a bunch of tracebacks after every training and validation epoch (attached below), making the log almost impossible to parse. I have tried to catch the SigtermInterrupt in workers and putting (None, "end worker") on the queue. However, after doing this the control never comes back to the consumer process and it hangs. 

```
    self._target(*self._args, **self._kwargs)                                                                                                                                                                                                                         [138/1936]
  File "/cm/shared/apps/python/3.8.2-2004/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/nfs/scratch1/unkuser/score_based_learning/spb/.venv/lib/python3.8/site-packages/allennlp/commands/train.py", line 41, in handle_sigterm
    raise SigTermInterrupt
  File "/mnt/nfs/scratch1/unkuser/score_based_learning/spb/.venv/lib/python3.8/site-packages/allennlp/commands/train.py", line 41, in handle_sigterm
    raise SigTermInterrupt
allennlp.commands.train.SigTermInterrupt
allennlp.commands.train.SigTermInterrupt
Traceback (most recent call last):
  File "/cm/shared/apps/python/3.8.2-2004/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/cm/shared/apps/python/3.8.2-2004/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/nfs/scratch1/unkuser/score_based_learning/spb/.venv/lib/python3.8/site-packages/allennlp/data/data_loaders/multiprocess_data_loader.py", line 513, in _batch_worker
    queue.join()
  File "/cm/shared/apps/python/3.8.2-2004/lib/python3.8/multiprocessing/queues.py", line 326, in join
    self._cond.wait()
  File "/cm/shared/apps/python/3.8.2-2004/lib/python3.8/multiprocessing/synchronize.py", line 268, in wait
    self._lock.acquire()
  File "/mnt/nfs/scratch1/unkuser/score_based_learning/spb/.venv/lib/python3.8/site-packages/allennlp/commands/train.py", line 41, in handle_sigterm
    raise SigTermInterrupt
allennlp.commands.train.SigTermInterrupt
MAP: 0.9392, fixed_f1: 0.8421, relaxed_f1: 0.7807, batch_inner_loss: 0.0000, inner_loss: 0.0000, loss: 2.5732 ||: : 1835it [13:49,  2.21it/s]
2021-08-24 19:35:25,964 - INFO - spb.training.trainer.gradient_descent_minimax_trainer - Validating
0it [00:00, ?it/s]step 66
MAP: 0.8204, fixed_f1: 0.7034, relaxed_f1: 0.6651, batch_loss: 2.0757, loss: 6.0412 ||: : 6472it [01:54, 73.88it/s]step 67
MAP: 0.8221, fixed_f1: 0.7045, relaxed_f1: 0.6661, batch_loss: 3.5373, loss: 6.0089 ||: : 7389it [02:06, 69.83it/s]Process ForkProcess-40:
Process ForkProcess-42:
MAP: 0.8221, fixed_f1: 0.7046, relaxed_f1: 0.6662, batch_loss: 1.2101, loss: 6.0065 ||: : 7393it [02:06, 58.59it/s]
2021-08-24 19:37:32,144 - INFO - allennlp.training.callbacks.console_logger -                        Training |  Validation
2021-08-24 19:37:32,145 - INFO - allennlp.training.callbacks.console_logger - MAP                |     0.939  |     0.822
2021-08-24 19:37:32,145 - INFO - allennlp.training.callbacks.console_logger - fixed_f1           |     0.842  |     0.705
2021-08-24 19:37:32,145 - INFO - allennlp.training.callbacks.console_logger - gpu_0_memory_MB    |  2411.483  |       N/A
2021-08-24 19:37:32,145 - INFO - allennlp.training.callbacks.console_logger - inner_loss         |     0.000  |       N/A
2021-08-24 19:37:32,145 - INFO - allennlp.training.callbacks.console_logger - loss               |     2.573  |     6.006
2021-08-24 19:37:32,145 - INFO - allennlp.training.callbacks.console_logger - relaxed_f1         |     0.781  |     0.666
2021-08-24 19:37:32,146 - INFO - allennlp.training.callbacks.console_logger - worker_0_memory_MB |  2900.180  |       N/A
Traceback (most recent call last):
  File "/cm/shared/apps/python/3.8.2-2004/lib/python3.8/multiprocessing/util.py", line 277, in _run_finalizers
    finalizer()
  File "/cm/shared/apps/python/3.8.2-2004/lib/python3.8/multiprocessing/util.py", line 201, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/cm/shared/apps/python/3.8.2-2004/lib/python3.8/multiprocessing/queues.py", line 200, in _finalize_close
    @staticmethod
  File "/mnt/nfs/scratch1/unkuser/score_based_learning/spb/.venv/lib/python3.8/site-packages/allennlp/commands/train.py", line 41, in handle_sigterm
    raise SigTermInterrupt
allennlp.commands.train.SigTermInterrupt
Traceback (most recent call last):
  File "/cm/shared/apps/python/3.8.2-2004/lib/python3.8/multiprocessing/process.py", line 318, in _bootstrap
    util._exit_function()
  File "/cm/shared/apps/python/3.8.2-2004/lib/python3.8/multiprocessing/util.py", line 311, in _exit_function
    _run_finalizers(0)
  File "/cm/shared/apps/python/3.8.2-2004/lib/python3.8/multiprocessing/util.py", line 245, in _run_finalizers
    def _run_finalizers(minpriority=None):
  File "/mnt/nfs/scratch1/unkuser/score_based_learning/spb/.venv/lib/python3.8/site-packages/allennlp/commands/train.py", line 41, in handle_sigterm
    raise SigTermInterrupt
allennlp.commands.train.SigTermInterrupt
Traceback (most recent call last):
  File "/cm/shared/apps/python/3.8.2-2004/lib/python3.8/multiprocessing/process.py", line 318, in _bootstrap
    util._exit_function()
  File "/cm/shared/apps/python/3.8.2-2004/lib/python3.8/multiprocessing/util.py", line 311, in _exit_function
    _run_finalizers(0)
  File "/cm/shared/apps/python/3.8.2-2004/lib/python3.8/multiprocessing/util.py", line 245, in _run_finalizers
    def _run_finalizers(minpriority=None):
  File "/mnt/nfs/scratch1/unkuser/score_based_learning/spb/.venv/lib/python3.8/site-packages/allennlp/commands/train.py", line 41, in handle_sigterm
    raise SigTermInterrupt
allennlp.commands.train.SigTermInterrupt
2021-08-24 19:37:42,589 - INFO - spb.training.trainer.gradient_descent_minimax_trainer - Epoch duration: 0:16:06.468372
2021-08-24 19:37:42,589 - INFO - spb.training.trainer.gradient_descent_minimax_trainer - Estimated training time remaining: 3 days, 6:06:36
2021-08-24 19:37:42,589 - INFO - spb.training.trainer.gradient_descent_minimax_trainer - Epoch 7/299
```
