### ISSUE TITLE
from ._check_build import check_build # noqa ImportError: dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by cyilu** [allenai/allennlp#5417]
## Checklist

- [x] I have verified that the issue exists against the `main` branch of AllenNLP.
- [x] I have read the relevant section in the [contribution guide](https://github.com/allenai/allennlp/blob/main/CONTRIBUTING.md#bug-fixes-and-new-features) on reporting bugs.
- [x] I have checked the [issues list](https://github.com/allenai/allennlp/issues) for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/allenai/allennlp/pulls) for existing proposed fixes.
- [x] I have checked the [CHANGELOG](https://github.com/allenai/allennlp/blob/main/CHANGELOG.md) and the [commit log](https://github.com/allenai/allennlp/commits/main) to find out if the bug was already fixed in the main branch.
- [x] I have included in the "Description" section below a traceback from any exceptions related to this bug.
- [x] I have included in the "Related issues or possible duplicates" section beloew all related issues and possible duplicate issues (If there are none, check this box anyway).
- [x] I have included in the "Environment" section below the name of the operating system and Python version that I was using when I discovered this bug.
- [x] I have included in the "Environment" section below the output of `pip freeze`.
- [x] I have included in the "Steps to reproduce" section below a minimally reproducible example.

## Description

After I finish `pip install allennlp`, then run `allennlp test-install` or `from allennlp.commands.elmo import ElmoEmbedder`, I meet this problem.

<details>
<summary><b>Python traceback:</b></summary>
<p>

```
>>> from allennlp.commands.elmo import ElmoEmbedder
Traceback (most recent call last):
  File "/home/nls3/anaconda2/envs/allennlp38_tmp/lib/python3.8/site-packages/sklearn/__check_build/__init__.py", line 44, in <module>
    from ._check_build import check_build  # noqa
ImportError: dlopen: cannot load any more object with static TLS

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nls3/anaconda2/envs/allennlp38_tmp/lib/python3.8/site-packages/allennlp/commands/__init__.py", line 9, in <module>
    from allennlp.commands.build_vocab import BuildVocab
  File "/home/nls3/anaconda2/envs/allennlp38_tmp/lib/python3.8/site-packages/allennlp/commands/build_vocab.py", line 17, in <module>
    from allennlp.training.util import make_vocab_from_params
  File "/home/nls3/anaconda2/envs/allennlp38_tmp/lib/python3.8/site-packages/allennlp/training/__init__.py", line 2, in <module>
    from allennlp.training.no_op_trainer import NoOpTrainer
  File "/home/nls3/anaconda2/envs/allennlp38_tmp/lib/python3.8/site-packages/allennlp/training/no_op_trainer.py", line 6, in <module>
    from allennlp.models import Model
  File "/home/nls3/anaconda2/envs/allennlp38_tmp/lib/python3.8/site-packages/allennlp/models/__init__.py", line 6, in <module>
    from allennlp.models.model import Model
  File "/home/nls3/anaconda2/envs/allennlp38_tmp/lib/python3.8/site-packages/allennlp/models/model.py", line 18, in <module>
    from allennlp.data import Instance, Vocabulary
  File "/home/nls3/anaconda2/envs/allennlp38_tmp/lib/python3.8/site-packages/allennlp/data/__init__.py", line 1, in <module>
    from allennlp.data.data_loaders import (
  File "/home/nls3/anaconda2/envs/allennlp38_tmp/lib/python3.8/site-packages/allennlp/data/data_loaders/__init__.py", line 2, in <module>
    from allennlp.data.data_loaders.multiprocess_data_loader import MultiProcessDataLoader, WorkerError
  File "/home/nls3/anaconda2/envs/allennlp38_tmp/lib/python3.8/site-packages/allennlp/data/data_loaders/multiprocess_data_loader.py", line 19, in <module>
    from allennlp.data.data_loaders.data_collator import DataCollator, DefaultDataCollator
  File "/home/nls3/anaconda2/envs/allennlp38_tmp/lib/python3.8/site-packages/allennlp/data/data_loaders/data_collator.py", line 3, in <module>
    from transformers.data.data_collator import DataCollatorForLanguageModeling
  File "/home/nls3/anaconda2/envs/allennlp38_tmp/lib/python3.8/site-packages/transformers/data/__init__.py", line 19, in <module>
    from .metrics import glue_compute_metrics, xnli_compute_metrics
  File "/home/nls3/anaconda2/envs/allennlp38_tmp/lib/python3.8/site-packages/transformers/data/metrics/__init__.py", line 22, in <module>
    if is_sklearn_available():
  File "/home/nls3/anaconda2/envs/allennlp38_tmp/lib/python3.8/site-packages/transformers/file_utils.py", line 307, in is_sklearn_available
    return importlib.util.find_spec("sklearn.metrics") and importlib.util.find_spec("scipy.stats")
  File "/home/nls3/anaconda2/envs/allennlp38_tmp/lib/python3.8/importlib/util.py", line 94, in find_spec
    parent = __import__(parent_name, fromlist=['__path__'])
  File "/home/nls3/anaconda2/envs/allennlp38_tmp/lib/python3.8/site-packages/sklearn/__init__.py", line 81, in <module>
    from . import __check_build  # noqa: F401
  File "/home/nls3/anaconda2/envs/allennlp38_tmp/lib/python3.8/site-packages/sklearn/__check_build/__init__.py", line 46, in <module>
    raise_build_error(e)
  File "/home/nls3/anaconda2/envs/allennlp38_tmp/lib/python3.8/site-packages/sklearn/__check_build/__init__.py", line 31, in raise_build_error
    raise ImportError("""%s
ImportError: dlopen: cannot load any more object with static TLS
___________________________________________________________________________
Contents of /home/nls3/anaconda2/envs/allennlp38_tmp/lib/python3.8/site-packages/sklearn/__check_build:
setup.py                  _check_build.cpython-38-x86_64-linux-gnu.so__init__.py
__pycache__
___________________________________________________________________________
It seems that scikit-learn has not been built correctly.

If you have installed scikit-learn from source, please do not forget
to build the package before using it: run `python setup.py install` or
`make` in the source directory.

If you have used an installer, please check that it is suited for your
Python version, your operating system and your platform.
```

</p>
</details>

## Related issues or possible duplicates

- https://github.com/allenai/allennlp/issues/285

## Environment

OS: Linux GPU1 4.2.0-27-generic #32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Python version: 3.8.11

<details>
<summary><b>Output of <code>pip freeze</code>:</b></summary>
<p>

```
aiohttp==3.7.4.post0
allennlp==2.7.0
argon2-cffi==21.1.0
async-timeout==3.0.1
attrs==21.2.0
backcall==0.2.0
backports.csv==1.0.7
base58==2.1.0
beautifulsoup4==4.10.0
bleach==4.1.0
blis==0.7.4
boto3==1.18.45
botocore==1.21.45
cachetools==4.2.2
catalogue==2.0.6
certifi==2021.5.30
cffi==1.14.6
chardet==4.0.0
charset-normalizer==2.0.6
checklist==0.0.11
cheroot==8.5.2
CherryPy==18.6.1
click==8.0.1
configparser==5.0.2
cryptography==3.4.8
cymem==2.0.5
datasets==1.12.1
debugpy==1.4.3
decorator==5.1.0
defusedxml==0.7.1
dill==0.3.4
docker-pycreds==0.4.0
entrypoints==0.3
fairscale==0.4.0
feedparser==6.0.8
filelock==3.0.12
fsspec==2021.8.1
future==0.18.2
gitdb==4.0.7
GitPython==3.1.24
google-api-core==2.0.1
google-auth==2.1.0
google-cloud-core==2.0.0
google-cloud-storage==1.42.2
google-crc32c==1.2.0
google-resumable-media==2.0.3
googleapis-common-protos==1.53.0
h5py==3.4.0
huggingface-hub==0.0.17
idna==3.2
iniconfig==1.1.1
ipykernel==6.4.1
ipython==7.27.0
ipython-genutils==0.2.0
ipywidgets==7.6.5
iso-639==0.4.5
jaraco.classes==3.2.1
jaraco.collections==3.4.0
jaraco.functools==3.3.0
jaraco.text==3.5.1
jedi==0.18.0
Jinja2==3.0.1
jmespath==0.10.0
joblib==1.0.1
jsonnet==0.17.0
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==7.0.3
jupyter-console==6.4.0
jupyter-core==4.8.1
jupyterlab-pygments==0.1.2
jupyterlab-widgets==1.0.2
lmdb==1.2.1
lxml==4.6.3
MarkupSafe==2.0.1
matplotlib-inline==0.1.3
mistune==0.8.4
more-itertools==8.10.0
multidict==5.1.0
multiprocess==0.70.12.2
munch==2.5.0
murmurhash==1.0.5
nbclient==0.5.4
nbconvert==6.1.0
nbformat==5.1.3
nest-asyncio==1.5.1
nltk==3.6.3
notebook==6.4.4
numpy==1.21.2
overrides==3.1.0
packaging==21.0
pandas==1.3.3
pandocfilters==1.5.0
parso==0.8.2
pathtools==0.1.2
pathy==0.6.0
patternfork-nosql==3.6
pdfminer.six==20201018
pexpect==4.8.0
pickleshare==0.7.5
Pillow==8.3.2
pluggy==1.0.0
portend==2.7.1
preshed==3.0.5
prometheus-client==0.11.0
promise==2.3
prompt-toolkit==3.0.20
protobuf==3.18.0
psutil==5.8.0
ptyprocess==0.7.0
py==1.10.0
pyarrow==5.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
pydantic==1.8.2
Pygments==2.10.0
pyparsing==2.4.7
pyrsistent==0.18.0
pytest==6.2.5
python-dateutil==2.8.2
python-docx==0.8.11
pytz==2021.1
PyYAML==5.4.1
pyzmq==22.3.0
qtconsole==5.1.1
QtPy==1.11.1
regex==2021.8.28
requests==2.26.0
rsa==4.7.2
s3transfer==0.5.0
sacremoses==0.0.45
scikit-learn==0.24.2
scipy==1.7.1
Send2Trash==1.8.0
sentencepiece==0.1.96
sentry-sdk==1.4.0
sgmllib3k==1.0.0
shortuuid==1.0.1
six==1.16.0
smart-open==5.2.1
smmap==4.0.0
sortedcontainers==2.4.0
soupsieve==2.2.1
spacy==3.1.3
spacy-legacy==3.0.8
sqlitedict==1.7.0
srsly==2.4.1
subprocess32==3.5.4
tempora==4.1.1
tensorboardX==2.4
termcolor==1.1.0
terminado==0.12.1
testpath==0.5.0
thinc==8.0.10
threadpoolctl==2.2.0
tokenizers==0.10.3
toml==0.10.2
torch==1.9.1
torchvision==0.10.1
tornado==6.1
tqdm==4.62.3
traitlets==5.1.0
transformers==4.5.1
typer==0.4.0
typing-extensions==3.10.0.2
urllib3==1.26.6
wandb==0.12.2
wasabi==0.8.2
wcwidth==0.2.5
webencodings==0.5.1
widgetsnbextension==3.5.1
xxhash==2.0.2
yarl==1.6.3
yaspin==2.1.0
zc.lockfile==2.0
```

</p>
</details>

## Steps to reproduce

<details>
<summary><b>Example source:</b></summary>
<p>

After finishing `pip install allennlp`, then run  `allennlp test-install` or `from allennlp.commands.elmo import ElmoEmbedder`.
```
```

</p>
</details>

**Comment by epwalsh** [comment]
Hi, I'm a little confused because `allennlp.commands.elmo` was removed a while ago (long before version 2.7). Are you sure you have 2.7 installed? Can you try a clean install again to make sure?

The only elmo stuff still left is `allennlp.modules.token_embedders.elmo_token_embedder`. And it looks like you're using Ubuntu 14.04, which is pretty old. It's possible that newer version of torch/sklearn/numpy don't work well on that.
