### ISSUE TITLE
`from_files_and_instances` is not registered in vocabulary.py

### ISSUE THREAD

**Issue by guopeiming** [allenai/allennlp#5431]
## Checklist

- [x] I have verified that the issue exists against the `main` branch of AllenNLP.
- [x] I have read the relevant section in the [contribution guide](https://github.com/allenai/allennlp/blob/main/CONTRIBUTING.md#bug-fixes-and-new-features) on reporting bugs.
- [x] I have checked the [issues list](https://github.com/allenai/allennlp/issues) for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/allenai/allennlp/pulls) for existing proposed fixes.
- [x] I have checked the [CHANGELOG](https://github.com/allenai/allennlp/blob/main/CHANGELOG.md) and the [commit log](https://github.com/allenai/allennlp/commits/main) to find out if the bug was already fixed in the main branch.
- [x] I have included in the "Description" section below a traceback from any exceptions related to this bug.
- [x] I have included in the "Related issues or possible duplicates" section beloew all related issues and possible duplicate issues (If there are none, check this box anyway).
- [x] I have included in the "Environment" section below the name of the operating system and Python version that I was using when I discovered this bug.
- [x] I have included in the "Environment" section below the output of `pip freeze`.
- [x] I have included in the "Steps to reproduce" section below a minimally reproducible example.

## Description

`from_files_and_instances` is a `@classmethod` constructor in class of `Vocabulary`, but it is not registered.
When I want to init the vocabulary by this method from model archive file, allennlp raises the exceptions below.
It should be registered like the other classmethods of `from_instances`, `from_files`, `from_pretrained_transformer`, etc in [`vocabulary.py`](https://github.com/allenai/allennlp/blob/main/allennlp/data/vocabulary.py).

So I think there is a line of code missing at the end of `vocabulary.py`:
`Vocabulary.register("from_files_and_instances", constructor="from_files_and_instances")(Vocabulary)`

This is a small bug and it is easy to fix it. And we just need to add this line of code to the file.
If you agree with my modification, it is my honor to make a PR to add this line of code.

<details>
<summary><b>Python traceback:</b></summary>
<p>

```
Traceback (most recent call last):
  File "/home/admin/miniconda3/envs/allen/bin/allennlp", line 8, in <module>
    sys.exit(run())
  File "/home/admin/miniconda3/envs/allen/lib/python3.8/site-packages/allennlp/__main__.py", line 46, in run
    main(prog="allennlp")
  File "/home/admin/miniconda3/envs/allen/lib/python3.8/site-packages/allennlp/commands/__init__.py", line 122, in main
    args.func(args)
  File "/home/admin/miniconda3/envs/allen/lib/python3.8/site-packages/allennlp/commands/train.py", line 112, in train_model_from_args
    train_model_from_file(
  File "/home/admin/miniconda3/envs/allen/lib/python3.8/site-packages/allennlp/commands/train.py", line 178, in train_model_from_file
    return train_model(
  File "/home/admin/miniconda3/envs/allen/lib/python3.8/site-packages/allennlp/commands/train.py", line 254, in train_model
    model = _train_worker(
  File "/home/admin/miniconda3/envs/allen/lib/python3.8/site-packages/allennlp/commands/train.py", line 490, in _train_worker
    train_loop = TrainModel.from_params(
  File "/home/admin/miniconda3/envs/allen/lib/python3.8/site-packages/allennlp/common/from_params.py", line 652, in from_params
    return retyped_subclass.from_params(
  File "/home/admin/miniconda3/envs/allen/lib/python3.8/site-packages/allennlp/common/from_params.py", line 686, in from_params
    return constructor_to_call(**kwargs)  # type: ignore
  File "/home/admin/miniconda3/envs/allen/lib/python3.8/site-packages/allennlp/commands/train.py", line 764, in from_partial_objects
    vocabulary_ = vocabulary.construct(instances=instance_generator)
  File "/home/admin/miniconda3/envs/allen/lib/python3.8/site-packages/allennlp/common/lazy.py", line 82, in construct
    return self.constructor(**contructor_kwargs)
  File "/home/admin/miniconda3/envs/allen/lib/python3.8/site-packages/allennlp/common/lazy.py", line 66, in constructor_to_use
    return self._constructor.from_params(  # type: ignore[union-attr]
  File "/home/admin/miniconda3/envs/allen/lib/python3.8/site-packages/allennlp/common/from_params.py", line 633, in from_params
    choice = params.pop_choice(
  File "/home/admin/miniconda3/envs/allen/lib/python3.8/site-packages/allennlp/common/params.py", line 352, in pop_choice
    raise ConfigurationError(message)
allennlp.common.checks.ConfigurationError: from_files_and_instances not in acceptable choices for vocabulary.type: ['from_instances', 'from_pretrained_transformer', 'from_pretrained_transformer_and_instances', 'from_files', 'extend', 'empty']. You should either use the --include-package flag to make sure the correct module is loaded, or use a fully qualified class name in your config file like {"model": "my_module.models.MyModel"} to have it imported automatically.
```

</p>
</details>

## Related issues or possible duplicates

- None

## Environment

OS: Linux ubuntu 18.04

Python version: 3.8.11

<details>
<summary><b>Output of <code>pip freeze</code>:</b></summary>
<p>

```
aiohttp==3.7.4.post0
allennlp==2.7.0
allennlp-models==2.7.0
argon2-cffi==21.1.0
async-timeout==3.0.1
attrs==21.2.0
backcall==0.2.0
backports.csv==1.0.7
base58==2.1.0
beautifulsoup4==4.10.0
bleach==4.1.0
blessings==1.7
blis==0.7.4
boto3==1.18.47
botocore==1.21.48
cachetools==4.2.2
catalogue==2.0.6
certifi==2021.5.30
cffi==1.14.6
chardet==4.0.0
charset-normalizer==2.0.6
checklist==0.0.11
cheroot==8.5.2
CherryPy==18.6.1
click==8.0.1
configparser==5.0.2
conllu==4.4.1
cryptography==3.4.8
cymem==2.0.5
datasets==1.12.1
debugpy==1.4.3
decorator==5.1.0
defusedxml==0.7.1
dill==0.3.4
docker-pycreds==0.4.0
entrypoints==0.3
fairscale==0.4.0
feedparser==6.0.8
filelock==3.0.12
flake8==3.9.2
fsspec==2021.9.0
ftfy==6.0.3
future==0.18.2
gitdb==4.0.7
GitPython==3.1.24
google-api-core==2.0.1
google-auth==2.1.0
google-cloud-core==2.0.0
google-cloud-storage==1.42.2
google-crc32c==1.2.0
google-resumable-media==2.0.3
googleapis-common-protos==1.53.0
gpustat==0.6.0
h5py==3.4.0
huggingface-hub==0.0.17
idna==3.2
iniconfig==1.1.1
ipykernel==6.4.1
ipython==7.27.0
ipython-genutils==0.2.0
ipywidgets==7.6.5
iso-639==0.4.5
jaraco.classes==3.2.1
jaraco.collections==3.4.0
jaraco.functools==3.3.0
jaraco.text==3.5.1
jedi==0.18.0
Jinja2==3.0.1
jmespath==0.10.0
joblib==1.0.1
jsonnet==0.17.0
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==7.0.3
jupyter-console==6.4.0
jupyter-core==4.8.1
jupyterlab-pygments==0.1.2
jupyterlab-widgets==1.0.2
lmdb==1.2.1
lxml==4.6.3
MarkupSafe==2.0.1
matplotlib-inline==0.1.3
mccabe==0.6.1
mistune==0.8.4
more-itertools==8.10.0
multidict==5.1.0
multiprocess==0.70.12.2
munch==2.5.0
murmurhash==1.0.5
nbclient==0.5.4
nbconvert==6.2.0
nbformat==5.1.3
nest-asyncio==1.5.1
nltk==3.6.3
notebook==6.4.4
numpy==1.21.2
nvidia-ml-py3==7.352.0
opustools==1.2.1
overrides==3.1.0
packaging==21.0
pandas==1.3.3
pandocfilters==1.5.0
parso==0.8.2
pathtools==0.1.2
pathy==0.6.0
patternfork-nosql==3.6
pdfminer.six==20201018
pexpect==4.8.0
pickleshare==0.7.5
Pillow==8.3.2
pluggy==1.0.0
portend==2.7.1
preshed==3.0.5
prometheus-client==0.11.0
promise==2.3
prompt-toolkit==3.0.20
protobuf==3.18.0
psutil==5.8.0
ptyprocess==0.7.0
py==1.10.0
py-rouge==1.1
pyarrow==5.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycodestyle==2.7.0
pycparser==2.20
pydantic==1.8.2
pyflakes==2.3.1
Pygments==2.10.0
pyparsing==2.4.7
pyrsistent==0.18.0
pytest==6.2.5
python-dateutil==2.8.2
python-docx==0.8.11
pytz==2021.1
PyYAML==5.4.1
pyzmq==22.3.0
qtconsole==5.1.1
QtPy==1.11.2
regex==2021.8.28
requests==2.26.0
rsa==4.7.2
s3transfer==0.5.0
sacremoses==0.0.45
scikit-learn==1.0
scipy==1.7.1
Send2Trash==1.8.0
sentencepiece==0.1.96
sentry-sdk==1.4.1
sgmllib3k==1.0.0
shortuuid==1.0.1
six==1.16.0
smart-open==5.2.1
smmap==4.0.0
sortedcontainers==2.4.0
soupsieve==2.2.1
spacy==3.1.3
spacy-legacy==3.0.8
sqlitedict==1.7.0
srsly==2.4.1
subprocess32==3.5.4
tempora==4.1.1
tensorboardX==2.4
termcolor==1.1.0
terminado==0.12.1
testpath==0.5.0
thinc==8.0.10
threadpoolctl==2.2.0
tokenizers==0.10.3
toml==0.10.2
torch==1.9.1
torchvision==0.10.1
tornado==6.1
tqdm==4.62.3
traitlets==5.1.0
transformers==4.5.1
typer==0.4.0
typing-extensions==3.10.0.2
urllib3==1.26.7
wandb==0.12.2
wasabi==0.8.2
wcwidth==0.2.5
webencodings==0.5.1
widgetsnbextension==3.5.1
word2number==1.1
xxhash==2.0.2
yarl==1.6.3
yaspin==2.1.0
zc.lockfile==2.0
```

</p>
</details>

## Steps to reproduce

You can reproduce the bug by adding the code below to any train configuration files.
Addition, `directory` is the path of `Vocabulary` file that was serialized either using `save_to_files` or inside a model archive file.
<details>
<summary><b>Example source:</b></summary>
<p>

```
"vocabulary": {
    "type": "from_files_and_instances",
    "directory": /path/to/serialized/vocabulary/file,
},
```

</p>
</details>

**Comment by guopeiming** [comment]
@AkshitaB Oh, they are different names. I did not find it before.
The other classmethod names and their registered names are the same, but `from_files_and_instances`. It is confusing.
I think that it is better to clarify the different names and give an example like [`from_pretrained_transformer_and_instances`](https://docs.allennlp.org/main/api/data/vocabulary/#from_pretrained_transformer_and_instances) in the docs.

**Comment by guopeiming** [comment]
@AkshitaB you can close this issue now.
