### ISSUE TITLE
Assertion error when keep_most_recent_by_count = 0 and moving_average = None

### ISSUE THREAD

**Issue by ksteimel** [allenai/allennlp#5444]
## Checklist

- [x] I have verified that the issue exists against the `main` branch of AllenNLP.
- [x] I have read the relevant section in the [contribution guide](https://github.com/allenai/allennlp/blob/main/CONTRIBUTING.md#bug-fixes-and-new-features) on reporting bugs.
- [x] I have checked the [issues list](https://github.com/allenai/allennlp/issues) for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/allenai/allennlp/pulls) for existing proposed fixes.
- [x] I have checked the [CHANGELOG](https://github.com/allenai/allennlp/blob/main/CHANGELOG.md) and the [commit log](https://github.com/allenai/allennlp/commits/main) to find out if the bug was already fixed in the main branch.
- [x] I have included in the "Description" section below a traceback from any exceptions related to this bug.
- [x] I have included in the "Related issues or possible duplicates" section below all related issues and possible duplicate issues (If there are none, check this box anyway).
- [x] I have included in the "Environment" section below the name of the operating system and Python version that I was using when I discovered this bug.
- [x] I have included in the "Environment" section below the output of `pip freeze`.
- [x] I have included in the "Steps to reproduce" section below a minimally reproducible example.

## Description

When training a model using a config with `keep_most_recent_by_count` set to `0` and `moving_average` set to `None`, the `GradientDescentTrainer` throws an assertion error just before trying to copy the model state checkpoint. This worked on allennlp version 2.4 (when the parameter was `num_serialized_models_to_keep`). However on 2.7 and main this error is thrown. Changing either of these (e.g. using a moving average or setting `keep_most_recent_by_count` to a non-zero value), prevents this error from being raised.

<details>
<summary><b>Python traceback:</b></summary>
<p>

```
accuracy: 0.7500, accuracy3: 1.0000, batch_loss: 0.6267, loss: 0.6267 ||: 100%|##########| 1/1 [00:00<00:00, 332.56it/s]
2021-10-22 11:13:32,397 - INFO - allennlp.training.callbacks.console_logger -                        Training |  Validation
2021-10-22 11:13:32,397 - INFO - allennlp.training.callbacks.console_logger - accuracy           |     0.750  |     0.750
2021-10-22 11:13:32,397 - INFO - allennlp.training.callbacks.console_logger - accuracy3          |     1.000  |     1.000
2021-10-22 11:13:32,397 - INFO - allennlp.training.callbacks.console_logger - loss               |     0.627  |     0.627
2021-10-22 11:13:32,397 - INFO - allennlp.training.callbacks.console_logger - worker_0_memory_MB |   432.031  |       N/A
2021-10-22 11:13:32,401 - CRITICAL - root - Uncaught exception
Traceback (most recent call last):
  File "/usr/local/homebrew/Caskroom/miniconda/base/envs/ets_nlp_allennlp_models/bin/allennlp", line 33, in <module>
    sys.exit(load_entry_point('allennlp', 'console_scripts', 'allennlp')())
  File "/Users/ksteimel/Documents/Projects/allennlp/allennlp/__main__.py", line 46, in run
    main(prog="allennlp")
  File "/Users/ksteimel/Documents/Projects/allennlp/allennlp/commands/__init__.py", line 123, in main
    args.func(args)
  File "/Users/ksteimel/Documents/Projects/allennlp/allennlp/commands/train.py", line 112, in train_model_from_args
    train_model_from_file(
  File "/Users/ksteimel/Documents/Projects/allennlp/allennlp/commands/train.py", line 178, in train_model_from_file
    return train_model(
  File "/Users/ksteimel/Documents/Projects/allennlp/allennlp/commands/train.py", line 254, in train_model
    model = _train_worker(
  File "/Users/ksteimel/Documents/Projects/allennlp/allennlp/commands/train.py", line 504, in _train_worker
    metrics = train_loop.run()
  File "/Users/ksteimel/Documents/Projects/allennlp/allennlp/commands/train.py", line 577, in run
    return self.trainer.train()
  File "/Users/ksteimel/Documents/Projects/allennlp/allennlp/training/gradient_descent_trainer.py", line 769, in train
    metrics, epoch = self._try_train()
  File "/Users/ksteimel/Documents/Projects/allennlp/allennlp/training/gradient_descent_trainer.py", line 912, in _try_train
    assert last_checkpoint is not None
AssertionError
```

</p>
</details>

## Related issues or possible duplicates

- None

## Environment

OS: MacOS 11

Python version: 3.8.12

<details>
<summary><b>Output of <code>pip freeze</code>:</b></summary>
<p>

```
appnope==0.1.2
argon2-cffi==21.1.0
async-timeout==3.0.1
attrs @ file:///home/conda/feedstock_root/build_artifacts/attrs_1620387926260/work
backcall==0.2.0
backports.csv==1.0.7
base58==2.1.0
beautifulsoup4==4.10.0
bleach==4.1.0
blis==0.7.4
boto3 @ file:///home/conda/feedstock_root/build_artifacts/boto3_1634782393307/work
botocore @ file:///home/conda/feedstock_root/build_artifacts/botocore_1634773831616/work
brotlipy==0.7.0
cached-property @ file:///home/conda/feedstock_root/build_artifacts/cached_property_1615209429212/work
cachetools==4.2.4
catalogue==2.0.6
certifi==2021.10.8
cffi @ file:///Users/runner/miniforge3/conda-bld/cffi_1631636289798/work
chardet @ file:///Users/runner/miniforge3/conda-bld/chardet_1610093477312/work
charset-normalizer @ file:///home/conda/feedstock_root/build_artifacts/charset-normalizer_1626371162869/work
checklist==0.0.11
cheroot==8.5.2
CherryPy==18.6.1
click==7.1.2
colorama @ file:///home/conda/feedstock_root/build_artifacts/colorama_1602866480661/work
configparser==5.0.2
coverage @ file:///Users/runner/miniforge3/conda-bld/coverage_1634003959650/work
cryptography @ file:///Users/runner/miniforge3/conda-bld/cryptography_1634230528229/work
cymem==2.0.5
dataclasses==0.6
datasets==1.14.0
debugpy==1.5.1
decorator==5.1.0
defusedxml==0.7.1
dill==0.3.4
docker-pycreds==0.4.0
en-core-web-sm @ file:///home/conda/feedstock_root/build_artifacts/spacy-model-en_core_web_1626140665752/work/sm
entrypoints==0.3
fairscale==0.4.0
feedparser==6.0.8
filelock @ file:///home/conda/feedstock_root/build_artifacts/filelock_1589994591731/work
fsspec==2021.10.1
future==0.18.2
gitdb==4.0.7
GitPython==3.1.24
google-api-core==2.1.1
google-auth==2.3.0
google-cloud-core==2.1.0
google-cloud-storage==1.42.3
google-crc32c==1.3.0
google-resumable-media==2.0.3
googleapis-common-protos==1.53.0
h5py @ file:///Users/runner/miniforge3/conda-bld/h5py_1631559921610/work
huggingface-hub==0.0.19
idna @ file:///home/conda/feedstock_root/build_artifacts/idna_1609836280497/work
importlib-metadata @ file:///Users/runner/miniforge3/conda-bld/importlib-metadata_1630267509190/work
iniconfig @ file:///home/conda/feedstock_root/build_artifacts/iniconfig_1603384189793/work
ipykernel==6.4.2
ipython==7.28.0
ipython-genutils==0.2.0
ipywidgets==7.6.5
iso-639==0.4.5
jaraco.classes==3.2.1
jaraco.collections==3.4.0
jaraco.functools==3.3.0
jaraco.text==3.5.1
jedi==0.18.0
Jinja2==3.0.2
jmespath @ file:///home/conda/feedstock_root/build_artifacts/jmespath_1589369830981/work
joblib @ file:///home/conda/feedstock_root/build_artifacts/joblib_1633637554808/work
jsonnet @ file:///Users/runner/miniforge3/conda-bld/jsonnet_1606064694325/work
jsonpickle @ file:///home/conda/feedstock_root/build_artifacts/jsonpickle_1618250231429/work
jsonschema==4.1.2
jupyter==1.0.0
jupyter-client==7.0.6
jupyter-console==6.4.0
jupyter-core==4.8.1
jupyterlab-pygments==0.1.2
jupyterlab-widgets==1.0.2
lmdb @ file:///Users/runner/miniforge3/conda-bld/python-lmdb_1615637368298/work
loguru @ file:///Users/runner/miniforge3/conda-bld/loguru_1618589874299/work
lxml @ file:///Users/runner/miniforge3/conda-bld/lxml_1616532325069/work
MarkupSafe==2.0.1
matplotlib-inline==0.1.3
mistune==0.8.4
more-itertools @ file:///home/conda/feedstock_root/build_artifacts/more-itertools_1631893103191/work
multidict==5.2.0
multiprocess==0.70.12.2
munch==2.5.0
murmurhash==1.0.5
mypy @ file:///Users/runner/miniforge3/conda-bld/mypy_1624396887604/work
mypy-extensions @ file:///Users/runner/miniforge3/conda-bld/mypy_extensions_1610127398887/work
nbclient==0.5.4
nbconvert==6.2.0
nbformat==5.1.3
nest-asyncio==1.5.1
nltk @ file:///home/conda/feedstock_root/build_artifacts/nltk_1633955089856/work
notebook==6.4.5
numpy @ file:///Users/runner/miniforge3/conda-bld/numpy_1634853074130/work
olefile @ file:///home/conda/feedstock_root/build_artifacts/olefile_1602866521163/work
overrides @ file:///home/conda/feedstock_root/build_artifacts/overrides_1592431494961/work
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1625323647219/work
pandas==1.3.4
pandocfilters==1.5.0
parso==0.8.2
pathtools==0.1.2
pathy==0.6.0
patternfork-nosql==3.6
pdfminer.six==20211012
pexpect==4.8.0
pickleshare==0.7.5
Pillow @ file:///Users/runner/miniforge3/conda-bld/pillow_1630696729270/work
plac==1.1.3
pluggy @ file:///Users/runner/miniforge3/conda-bld/pluggy_1631522705346/work
portend==3.0.0
preshed==3.0.5
prometheus-client==0.11.0
promise==2.3
prompt-toolkit==3.0.21
protobuf==3.18.1
psutil @ file:///Users/runner/miniforge3/conda-bld/psutil_1618863837648/work
ptyprocess==0.7.0
py @ file:///home/conda/feedstock_root/build_artifacts/py_1607783655754/work
pyarrow==5.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser @ file:///home/conda/feedstock_root/build_artifacts/pycparser_1593275161868/work
pydantic==1.8.2
Pygments==2.10.0
pyOpenSSL @ file:///home/conda/feedstock_root/build_artifacts/pyopenssl_1633192417276/work
pyparsing==2.4.7
pyrsistent==0.18.0
PySocks @ file:///Users/runner/miniforge3/conda-bld/pysocks_1610291493748/work
pytest==6.2.5
pytest-cov @ file:///home/conda/feedstock_root/build_artifacts/pytest-cov_1633356845954/work
python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1626286286081/work
python-docx==0.8.11
pytz @ file:///home/conda/feedstock_root/build_artifacts/pytz_1633452062248/work
PyYAML==6.0
pyzmq==22.3.0
qtconsole==5.1.1
QtPy==1.11.2
regex @ file:///Users/runner/miniforge3/conda-bld/regex_1634800923165/work
requests @ file:///home/conda/feedstock_root/build_artifacts/requests_1626393743643/work
rsa==4.7.2
s3transfer @ file:///home/conda/feedstock_root/build_artifacts/s3transfer_1626384238958/work
sacremoses @ file:///home/conda/feedstock_root/build_artifacts/sacremoses_1588857588528/work
scikit-learn @ file:///Users/runner/miniforge3/conda-bld/scikit-learn_1632611439190/work
scipy @ file:///Users/runner/miniforge3/conda-bld/scipy_1628206458939/work
Send2Trash==1.8.0
sentencepiece==0.1.96
sentry-sdk==1.4.3
sgmllib3k==1.0.0
shortuuid==1.0.1
six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
smart-open==5.2.1
smmap==4.0.0
soupsieve==2.2.1
spacy==3.1.0
spacy-legacy==3.0.8
sqlitedict==1.7.0
srsly==2.4.2
subprocess32==3.5.4
tempora==4.1.2
tensorboardX @ file:///home/conda/feedstock_root/build_artifacts/tensorboardx_1628560643999/work
termcolor==1.1.0
terminado==0.12.1
testpath==0.5.0
thinc==8.0.11
threadpoolctl @ file:///home/conda/feedstock_root/build_artifacts/threadpoolctl_1633102299089/work
tokenizers==0.10.3
toml @ file:///home/conda/feedstock_root/build_artifacts/toml_1604308577558/work
tomli @ file:///home/conda/feedstock_root/build_artifacts/tomli_1628264172148/work
torch==1.7.0
torchvision==0.8.1
tornado==6.1
tqdm @ file:///home/conda/feedstock_root/build_artifacts/tqdm_1632160078689/work
traitlets==5.1.0
transformers==4.11.3
typer==0.3.2
typing-extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1632313171031/work
urllib3 @ file:///home/conda/feedstock_root/build_artifacts/urllib3_1632350318291/work
wandb==0.12.5
wasabi==0.8.2
wcwidth==0.2.5
webencodings==0.5.1
widgetsnbextension==3.5.1
xxhash==2.0.2
yarl==1.7.0
yaspin==2.1.0
zc.lockfile==2.0
zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1633302054558/work
```

</p>
</details>

## Steps to reproduce

<details>
<summary><b>Example source:</b></summary>
<p>

This is a modified version of [simple_tagger/experiment.json](https://github.com/allenai/allennlp/blob/main/test_fixtures/simple_tagger/experiment.json) that causes this error.
```
{
  "dataset_reader":{"type":"sequence_tagging"},
  "train_data_path": "test_fixtures/data/sequence_tagging.tsv",
  "validation_data_path": "test_fixtures/data/sequence_tagging.tsv",
  "model": {
    "type": "simple_tagger",
    "text_field_embedder": {
      "token_embedders": {
        "tokens": {
            "type": "embedding",
            "projection_dim": 2,
            "pretrained_file": "test_fixtures/embeddings/glove.6B.100d.sample.txt.gz",
            "embedding_dim": 100,
            "trainable": true
        }
      }
    },
    "encoder": {
      "type": "lstm",
      "input_size": 2,
      "hidden_size": 4,
      "num_layers": 1
    }
  },
  "data_loader": {
      "batch_sampler": {
        "type": "bucket",
        "sorting_keys": ["tokens"],
        "padding_noise": 0.0,
        "batch_size" : 80
    }
},
  "trainer": {
    "num_epochs": 1,
    "grad_norm": 1.0,
    "patience": 500,
    "cuda_device": -1,
    "checkpointer": {
        "keep_most_recent_by_count": 0
    },
    "moving_average": null,
    "optimizer": {
      "type": "adadelta",
      "lr": 0.000001,
      "rho": 0.95
    }
  }
}
```

</p>
</details>

**Comment by ksteimel** [comment]
I don't want any `model_state_epoch_2.th` and `training_state_epoch_2.th` files left when the training process is complete. If set to 1, there is only one set of these left behind, if set to two there are two sets of these. I have been using `num_serialized_models_to_keep` to prevent these files from lingering after training finishes.

**Comment by ksteimel** [comment]
Yeah I guess I could do that. It just seems strange that this used to be possible but no longer is.
