### ISSUE TITLE
Not able to load coref-spanbert-large-2021.03.10.tar.gz on a non internet system

### ISSUE THREAD

**Issue by avinashpaul** [allenai/allennlp#5456]
```
from allennlp.predictors import Predictor
import os
path1 = '/opt/triniti4/pretrained_models/context_expansion/coref-spanbert-large-2021.03.10.tar.gz'
coref_model = Predictor.from_path(path1)


Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/allennlp/predictors/predictor.py", line 362, in from_path
    load_archive(archive_path, cuda_device=cuda_device, overrides=overrides),
  File "/usr/local/lib/python3.8/dist-packages/allennlp/models/archival.py", line 205, in load_archive
    dataset_reader, validation_dataset_reader = _load_dataset_readers(
  File "/usr/local/lib/python3.8/dist-packages/allennlp/models/archival.py", line 231, in _load_dataset_readers
    dataset_reader = DatasetReader.from_params(
  File "/usr/local/lib/python3.8/dist-packages/allennlp/common/from_params.py", line 589, in from_params
    return retyped_subclass.from_params(
  File "/usr/local/lib/python3.8/dist-packages/allennlp/common/from_params.py", line 621, in from_params
    kwargs = create_kwargs(constructor_to_inspect, cls, params, **extras)
  File "/usr/local/lib/python3.8/dist-packages/allennlp/common/from_params.py", line 199, in create_kwargs
    constructed_arg = pop_and_construct_arg(
  File "/usr/local/lib/python3.8/dist-packages/allennlp/common/from_params.py", line 307, in pop_and_construct_arg
    return construct_arg(class_name, name, popped_params, annotation, default, **extras)
  File "/usr/local/lib/python3.8/dist-packages/allennlp/common/from_params.py", line 385, in construct_arg
    value_dict[key] = construct_arg(
  File "/usr/local/lib/python3.8/dist-packages/allennlp/common/from_params.py", line 341, in construct_arg
    return annotation.from_params(params=popped_params, **subextras)
  File "/usr/local/lib/python3.8/dist-packages/allennlp/common/from_params.py", line 589, in from_params
    return retyped_subclass.from_params(
  File "/usr/local/lib/python3.8/dist-packages/allennlp/common/from_params.py", line 623, in from_params
    return constructor_to_call(**kwargs)  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/allennlp/data/token_indexers/pretrained_transformer_mismatched_indexer.py", line 58, in __init__
    self._matched_indexer = PretrainedTransformerIndexer(
  File "/usr/local/lib/python3.8/dist-packages/allennlp/data/token_indexers/pretrained_transformer_indexer.py", line 57, in __init__
    self._allennlp_tokenizer = PretrainedTransformerTokenizer(
  File "/usr/local/lib/python3.8/dist-packages/allennlp/data/tokenizers/pretrained_transformer_tokenizer.py", line 70, in __init__
    self.tokenizer = cached_transformers.get_tokenizer(
  File "/usr/local/lib/python3.8/dist-packages/allennlp/common/cached_transformers.py", line 108, in get_tokenizer
    tokenizer = transformers.AutoTokenizer.from_pretrained(
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/auto/tokenization_auto.py", line 378, in from_pretrained
    return tokenizer_class_fast.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/tokenization_utils_base.py", line 1774, in from_pretrained
    resolved_vocab_files[file_id] = cached_path(
  File "/usr/local/lib/python3.8/dist-packages/transformers/file_utils.py", line 1077, in cached_path
    output_path = get_from_cache(
  File "/usr/local/lib/python3.8/dist-packages/transformers/file_utils.py", line 1263, in get_from_cache
    raise ValueError(
ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on.
>>>
```

**Comment by epwalsh** [comment]
Hey @avinashpaul, to avoid `PretrainedTransformerTokenizer` from downloading it's vocab and config from HuggingFace, you'll need to have a copy of those files locally. Then just change the [`model_name`](https://github.com/allenai/allennlp/blob/4f9030f5a0081dee6e2ccdde7af5930752f58c17/allennlp/data/tokenizers/pretrained_transformer_tokenizer.py#L37) parameter to the path of the local directory where you put those files.

**Comment by avinashpaul** [comment]
sure will try and update here
