### ISSUE TITLE
EncoderBase pack padded sequence error

### ISSUE THREAD

**Issue by nickmagginas** [allenai/allennlp#5480]
## Checklist

- [ x ] I have verified that the issue exists against the `main` branch of AllenNLP.
- [ x ] I have read the relevant section in the [contribution guide](https://github.com/allenai/allennlp/blob/main/CONTRIBUTING.md#bug-fixes-and-new-features) on reporting bugs.
- [ x ] I have checked the [issues list](https://github.com/allenai/allennlp/issues) for similar or identical bug reports.
- [ x ] I have checked the [pull requests list](https://github.com/allenai/allennlp/pulls) for existing proposed fixes.
- [ x ] I have checked the [CHANGELOG](https://github.com/allenai/allennlp/blob/main/CHANGELOG.md) and the [commit log](https://github.com/allenai/allennlp/commits/main) to find out if the bug was already fixed in the main branch.
- [ x ] I have included in the "Description" section below a traceback from any exceptions related to this bug.
- [ x ] I have included in the "Related issues or possible duplicates" section beloew all related issues and possible duplicate issues (If there are none, check this box anyway).
- [ x ] I have included in the "Environment" section below the name of the operating system and Python version that I was using when I discovered this bug.
- [ x ] I have included in the "Environment" section below the output of `pip freeze`.
- [ x ] I have included in the "Steps to reproduce" section below a minimally reproducible example.

## Description

The ```sort_and_run_forward``` method of ```_EncoderBase``` in ```modules/encoder_base.py``` determines if a sample in a batch is valid in line 99: 

```python
num_valid = torch.sum(mask[:, 0]).int().item()
```
The mask is of shape B x S where B is batch size and S is sequence length. If the first item in the sequence of a sample is a pad token then the sample is deemed non valid. However, when we wish to mask sequences and observe the outputs of the model as for example in Lime replacing token_ids with 0 (pad token_id) will cause a traceback if all sequences in a batch start with zero. A batch for example containing ```[["[PAD]", "good", "[PAD]"], ["[PAD]", "bad", "flick"]]``` will fail. 

Ideally the batch above would be valid to pass through the model.   
 

<details>
<summary><b>Python traceback:</b></summary>
<p>

```
Traceback (most recent call last):
  File "/home/nick/dev/magnex/src/evaluation/captum_interface/captum_interface.py", line 190, in <module>
    intepret_predictions(
  File "/home/nick/dev/magnex/src/evaluation/captum_interface/captum_interface.py", line 173, in intepret_predictions
    next(method_attributions)
  File "/home/nick/dev/magnex/src/evaluation/captum_interface/captum_interface.py", line 113, in explain_instances
    batch_attributions = initialized_interpeter.attribute(
  File "/home/nick/.miniconda/envs/magnex/lib/python3.9/site-packages/captum/log/__init__.py", line 35, in wrapper
    return func(*args, **kwargs)
  File "/home/nick/.miniconda/envs/magnex/lib/python3.9/site-packages/captum/attr/_core/lime.py", line 1053, in attribute
    return self._attribute_kwargs(
  File "/home/nick/.miniconda/envs/magnex/lib/python3.9/site-packages/captum/attr/_core/lime.py", line 1164, in _attribute_kwargs
    coefs = super().attribute.__wrapped__(
  File "/home/nick/.miniconda/envs/magnex/lib/python3.9/site-packages/captum/attr/_core/lime.py", line 479, in attribute
    model_out = self._evaluate_batch(
  File "/home/nick/.miniconda/envs/magnex/lib/python3.9/site-packages/captum/attr/_core/lime.py", line 535, in _evaluate_batch
    model_out = _run_forward(
  File "/home/nick/.miniconda/envs/magnex/lib/python3.9/site-packages/captum/_utils/common.py", line 456, in _run_forward
    output = forward_func(
  File "/home/nick/dev/magnex/src/evaluation/captum_interface/captum_interface.py", line 105, in _forward_func
    model_output = model.forward(**complete_model_input)
  File "/home/nick/.miniconda/envs/magnex/lib/python3.9/site-packages/allennlp/models/basic_classifier.py", line 128, in forward
    embedded_text = self._seq2vec_encoder(embedded_text, mask=mask)
  File "/home/nick/.miniconda/envs/magnex/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/nick/.miniconda/envs/magnex/lib/python3.9/site-packages/allennlp/modules/seq2vec_encoders/pytorch_seq2vec_wrapper.py", line 80, in forward
    ) = self.sort_and_run_forward(self._module, inputs, mask, hidden_state)
  File "/home/nick/.miniconda/envs/magnex/lib/python3.9/site-packages/allennlp/modules/encoder_base.py", line 110, in sort_and_run_forward
    packed_sequence_input = pack_padded_sequence(
  File "/home/nick/.miniconda/envs/magnex/lib/python3.9/site-packages/torch/nn/utils/rnn.py", line 249, in pack_padded_sequence
    _VF._pack_padded_sequence(input, lengths, batch_first)
RuntimeError: Cannot pack empty tensors.
```

</p>
</details>

## Related issues or possible duplicates

- None

## Environment

OS: Linux ( Arch Linux x86_64  kernel: 5.14.15-arch1-1)

Python version: 3.9.7

<details>
<summary><b>Output of <code>pip freeze</code>:</b></summary>
<p>

```
aiohttp==3.8.0
aiosignal==1.2.0
allennlp==2.8.0
allennlp-models==2.8.0
appdirs==1.4.4
argon2-cffi==21.1.0
async-timeout==4.0.1
attrs @ file:///tmp/build/80754af9/attrs_1620827162558/work
backcall==0.2.0
backports.csv==1.0.7
base58==2.1.1
beautifulsoup4 @ file:///tmp/build/80754af9/beautifulsoup4_1631874778482/work
black==19.10b0
bleach==4.1.0
blis==0.7.5
boto3==1.20.3
botocore==1.23.3
brotlipy==0.7.0
cached-path==0.3.2
cachetools==4.2.4
captum==0.4.1
catalogue==2.0.6
certifi==2021.10.8
cffi==1.15.0
chardet @ file:///tmp/build/80754af9/chardet_1607706775000/work
charset-normalizer==2.0.7
checklist==0.0.11
cheroot==8.5.2
CherryPy==18.6.1
click==8.0.3
conda==4.10.3
conda-build==3.21.6
conda-package-handling @ file:///tmp/build/80754af9/conda-package-handling_1618262147379/work
configparser==5.1.0
conllu==4.4.1
cryptography @ file:///tmp/build/80754af9/cryptography_1635366129652/work
cycler==0.11.0
cymem==2.0.6
datasets==1.15.1
debugpy==1.5.1
decorator==5.1.0
defusedxml==0.7.1
dill==0.3.4
docker-pycreds==0.4.0
entrypoints==0.3
fairscale==0.4.0
feedparser==6.0.8
filelock==3.3.2
fonttools==4.28.1
frozenlist==1.2.0
fsspec==2021.11.0
ftfy==6.0.3
future==0.18.2
gitdb==4.0.9
GitPython==3.1.24
glob2 @ file:///home/linux1/recipes/ci/glob2_1610991677669/work
google-api-core==2.2.2
google-auth==2.3.3
google-cloud-core==2.2.1
google-cloud-storage==1.42.3
google-crc32c==1.3.0
google-resumable-media==2.1.0
googleapis-common-protos==1.53.0
h5py==3.5.0
huggingface-hub==0.1.2
idna==3.3
iniconfig==1.1.1
ipykernel==6.5.0
ipython==7.29.0
ipython-genutils==0.2.0
ipywidgets==7.6.5
iso-639==0.4.5
jaraco.classes==3.2.1
jaraco.collections==3.4.0
jaraco.functools==3.4.0
jaraco.text==3.6.0
jedi==0.18.0
Jinja2==3.0.3
jmespath==0.10.0
joblib==1.1.0
jsonnet==0.17.0
jsonschema==4.2.1
jupyter==1.0.0
jupyter-client==7.0.6
jupyter-console==6.4.0
jupyter-core==4.9.1
jupyterlab-pygments==0.1.2
jupyterlab-widgets==1.0.2
kiwisolver==1.3.2
libarchive-c @ file:///tmp/build/80754af9/python-libarchive-c_1617780486945/work
lmdb==1.2.1
lxml==4.6.4
MarkupSafe @ file:///tmp/build/80754af9/markupsafe_1621523467000/work
matplotlib==3.5.0
matplotlib-inline==0.1.3
mistune==0.8.4
more-itertools==8.11.0
multidict==5.2.0
multiprocess==0.70.12.2
munch==2.5.0
murmurhash==1.0.6
mypy==0.910
mypy-extensions==0.4.3
nbclient==0.5.5
nbconvert==6.2.0
nbformat==5.1.3
nest-asyncio==1.5.1
nltk==3.6.3
notebook==6.4.5
numpy==1.21.4
overrides==3.1.0
packaging==21.2
pandas==1.3.4
pandocfilters==1.5.0
parso==0.8.2
pathspec==0.7.0
pathtools==0.1.2
pathy==0.6.1
patternfork-nosql==3.6
pdfminer.six==20211012
pexpect==4.8.0
pickleshare==0.7.5
Pillow==8.4.0
pkginfo==1.7.1
pluggy==1.0.0
portend==3.0.0
preshed==3.0.6
prometheus-client==0.12.0
promise==2.3
prompt-toolkit==3.0.22
protobuf==3.19.1
psutil @ file:///tmp/build/80754af9/psutil_1612297992929/work
ptyprocess==0.7.0
py==1.11.0
py-rouge==1.1
pyarrow==6.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycosat==0.6.3
pycparser @ file:///tmp/build/80754af9/pycparser_1636541352034/work
pydantic==1.8.2
Pygments==2.10.0
pyOpenSSL @ file:///tmp/build/80754af9/pyopenssl_1635333100036/work
pyparsing==2.4.7
pyrsistent==0.18.0
PySocks @ file:///tmp/build/80754af9/pysocks_1605305812635/work
pytest==6.2.5
python-dateutil==2.8.2
python-docx==0.8.11
pytz==2021.3
PyYAML==6.0
pyzmq==22.3.0
qtconsole==5.2.0
QtPy==1.11.2
regex==2021.11.10
requests @ file:///tmp/build/80754af9/requests_1629994808627/work
rsa==4.7.2
ruamel-yaml-conda @ file:///tmp/build/80754af9/ruamel_yaml_1616016711199/work
s3transfer==0.5.0
sacremoses==0.0.46
scikit-learn==1.0.1
scipy==1.7.2
Send2Trash==1.8.0
sentencepiece==0.1.96
sentry-sdk==1.4.3
setuptools-scm==6.3.2
sgmllib3k==1.0.0
shortuuid==1.0.8
six @ file:///tmp/build/80754af9/six_1623709665295/work
smart-open==5.2.1
smmap==5.0.0
soupsieve @ file:///tmp/build/80754af9/soupsieve_1636706018808/work
spacy==3.1.4
spacy-legacy==3.0.8
sqlitedict==1.7.0
srsly==2.4.2
subprocess32==3.5.4
tempora==4.1.2
tensorboardX==2.4
termcolor==1.1.0
terminado==0.12.1
testpath==0.5.0
thinc==8.0.13
threadpoolctl==3.0.0
tokenizers==0.10.3
toml @ file:///tmp/build/80754af9/toml_1616166611790/work
tomli==1.2.2
torch==1.10.0
torchvision==0.11.1
tornado==6.1
tqdm @ file:///tmp/build/80754af9/tqdm_1635330843403/work
traitlets==5.1.1
transformers==4.12.3
typed-ast @ file:///tmp/build/80754af9/typed-ast_1624953673314/work
typer==0.4.0
typing-extensions @ file:///tmp/build/80754af9/typing_extensions_1631814937681/work
urllib3==1.26.7
wandb==0.12.6
wasabi==0.8.2
wcwidth==0.2.5
webencodings==0.5.1
widgetsnbextension==3.5.2
word2number==1.1
xxhash==2.0.2
yarl==1.7.2
yaspin==2.1.0
zc.lockfile==2.0
```

</p>
</details>

## Steps to reproduce

<details>
<summary><b>Example source:</b></summary>
<p>

```python
from allennlp.data.fields.text_field import TextFieldTensors
from allennlp.models.archival import load_archive
from allennlp.data.batch import Batch
from allennlp.common.util import import_module_and_submodules
import torch

import_module_and_submodules("allennlp_models")

archive = load_archive(
    "https://storage.googleapis.com/allennlp-public-models/basic_stanford_sentiment_treebank-2020.06.09.tar.gz"
)

instances = archive.dataset_reader.read(
    "https://allennlp.s3.amazonaws.com/datasets/sst/test.txt"
)

sample_instance = next(instances)

dummy_batch = Batch([sample_instance])

archive.dataset_reader.apply_token_indexers(sample_instance)
dummy_batch.index_instances(archive.model.vocab)

tensor_dict = dummy_batch.as_tensor_dict()

working_mask = torch.Tensor([[1, 0]])
non_working_mask = torch.Tensor([[0, 1]])


def mask_tokens(
    text_field_tensors: TextFieldTensors, mask: torch.Tensor
) -> TextFieldTensors:

    """Mask some token ids based on mask"""
    return {
        key: {
            _key: torch.where(mask == 1, _value, torch.zeros_like(_value))
            for _key, _value in value.items()
        }
        for key, value in text_field_tensors.items()
    }


working_masked_input = mask_tokens(tensor_dict["tokens"], working_mask)  # type: ignore
working_model_output = archive.model.forward(**{"tokens": working_masked_input})

non_working_masked_input = mask_tokens(tensor_dict["tokens"], non_working_mask)  # type: ignore
non_working_model_output = archive.model.forward(**{"tokens": non_working_masked_input})
```

</p>
</details>

**Comment by epwalsh** [comment]
Thanks for bringing this, @nickmagginas! I see your point, but I still think this is a good check to have in general. So I think the best way forward would be to add a flag that disables this check. Would you like to make a PR for that?

**Comment by nickmagginas** [comment]
Yep I will try to get to this from Monday. I remember when I wrote a diff changing the check to only filter samples which only contained [PAD] I run into some problems. I will update the issue if I encounter them as I go about implementing the flag.
