### ISSUE TITLE
`FBetaMultiLabelMeasure` can't process input dimension greater than 2

### ISSUE THREAD

**Issue by Zessay** [allenai/allennlp#5500]
The parameters' description of `__call__` function of `FBetaMultiLabelMeasure` is as following: 
```python
        # Parameters
        predictions : `torch.Tensor`, required.
            A tensor of predictions of shape (batch_size, ..., num_classes).
        gold_labels : `torch.Tensor`, required.
            A tensor of boolean labels of shape (batch_size, ..., num_classes). It must be the same
            shape as the `predictions`.
        mask : `torch.BoolTensor`, optional (default = `None`).
            A masking tensor the same size as `gold_labels`.
```
It means the `predictions` and other parameters with dimension greater than 2, e.g. `(batch_size, seq_len, num_classes)`, should be valid. Actually, the codes from lien 118 to 124 limit the input's dimension should be 2, because the dimension of `class_indices` is always 2.

```python
        class_indices = (
            torch.arange(num_classes, device=predictions.device)
            .unsqueeze(0)
            .repeat(gold_labels.size(0), 1)
        )
        true_positives = (gold_labels * threshold_predictions).bool() & mask & pred_mask
        true_positives_bins = class_indices[true_positives]
``` 

If the input's dimension is greater than 2, it will raise error.
```shell
Traceback (most recent call last):
  File "/xxx/tests/test_fbeta.py", line 23, in <module>
    print(metric(predictions,
  File "/xxx/anaconda3/envs/solutions/lib/python3.8/site-packages/allennlp/training/metrics/fbeta_multi_label_measure.py", line 123, in __call__
    true_positives_bins = class_indices[true_positives]
IndexError: too many indices for tensor of dimension 2
```

I think, if wants to limit the dimension of input to 2, it would be better to fix the `parameter discription` to avoid misunderstanding. If multi-dimension is permitted, maybe can `view` the input in the beginning.

**Comment by dirkgr** [comment]
You are right. I put a fix at #5501.
