### ISSUE TITLE
allennlp 2.9 conda-forge mac m1 chip fairscale ImportError: cannot import name 'ProcessGroup' from 'torch.distributed' 

### ISSUE THREAD

**Issue by RoyLiberman** [allenai/allennlp#5569]
Failed to evaluate model with error on macbook air with m1 chip, using recently released conda-forge  allennlp osx-arm64  v2.9.0

```
Traceback (most recent call last):
    from allennlp.training.util import evaluate
  File "env/lib/python3.8/site-packages/allennlp/training/__init__.py", line 2, in <module>
    from allennlp.training.no_op_trainer import NoOpTrainer
  File "env/lib/python3.8/site-packages/allennlp/training/no_op_trainer.py", line 6, in <module>
    from allennlp.models import Model
  File "env/lib/python3.8/site-packages/allennlp/models/__init__.py", line 6, in <module>
    from allennlp.models.model import Model
  File env/lib/python3.8/site-packages/allennlp/models/model.py", line 22, in <module>
    from allennlp.nn.parallel import DdpAccelerator
  File "env/lib/python3.8/site-packages/allennlp/nn/parallel/__init__.py", line 7, in <module>
    from allennlp.nn.parallel.fairscale_fsdp_accelerator import (
  File "env/lib/python3.8/site-packages/allennlp/nn/parallel/fairscale_fsdp_accelerator.py", line 4, in <module>
    from fairscale.nn import FullyShardedDataParallel as FS_FSDP
  File "env/lib/python3.8/site-packages/fairscale/__init__.py", line 12, in <module>
    from . import nn
  File "env/lib/python3.8/site-packages/fairscale/nn/__init__.py", line 9, in <module>
    from .data_parallel import FullyShardedDataParallel, ShardedDataParallel
  File "env/lib/python3.8/site-packages/fairscale/nn/data_parallel/__init__.py", line 8, in <module>
    from .fully_sharded_data_parallel import FullyShardedDataParallel, OffloadConfig, TrainingState, auto_wrap_bn
  File "env/lib/python3.8/site-packages/fairscale/nn/data_parallel/fully_sharded_data_parallel.py", line 38, in <module>
    from torch.distributed import ProcessGroup
ImportError: cannot import name 'ProcessGroup' from 'torch.distributed' (env/lib/python3.8/site-packages/torch/distributed/__init__.py)
```

**Comment by dirkgr** [comment]
I think something is wrong with your torch installation.

But I also don't think torch supports GPUs on Macs at all, let alone on the M1 chip. So that whole setup will never work. You can't do distributed training on Macs. Torch just doesn't have the capability for that.

**Comment by h-vetinari** [comment]
Yeah, `torch.distributed` is tricky in general. Would be good if the code (in allennlp/fairscale/etc.) could fail gracefully if imports from `torch.distributed` fail.

**Comment by h-vetinari** [comment]
PS. For issues regarding conda-forge, I'll see it more quickly if you raise it here: https://github.com/conda-forge/allennlp-feedstock
