### ISSUE TITLE
TypeError: '_NamespacePath' object is not subscriptable

### ISSUE THREAD

**Issue by leisurehippo** [allenai/allennlp#5677]
```
Traceback (most recent call last):
  File "xx/env/model_serving_python/bin/allennlp", line 8, in <module>
    sys.exit(run())
  File "xx/env/model_serving_python/lib/python3.7/site-packages/allennlp/run.py", line 18, in run
    main(prog="allennlp")
  File "xx/env/model_serving_python/lib/python3.7/site-packages/allennlp/commands/__init__.py", line 101, in main
    import_submodules(package_name)
  File "xx/env/model_serving_python/lib/python3.7/site-packages/allennlp/common/util.py", line 325, in import_submodules
    path_string = '' if not path else path[0]
TypeError: '_NamespacePath' object is not subscriptable
```

**Comment by epwalsh** [comment]
Hi, can you provide some more context? What did you run that led to this stacktrace? Which version of AllenNLP are you using?
