### ISSUE TITLE
Support for alternating_highway_lstm_cuda stacked encoder in SRL

### ISSUE THREAD

**Issue by swabhs** [allenai/allennlp#643]
Is the default version now built on the cuda kernel which was recently added?

**Comment by DeNeutoy** [comment]
Hi Swabha - it should still be supported. What error are you seeing? The default version still does not use the CUDA version, because 1) it is difficult to distribute and  2) it's hard to make it work on machines without GPUs.

**Comment by swabhs** [comment]
Hi Mark,

Looks like I might have been doing something wrong (perhaps I was pointing to a missing cuda driver), because I'm able to get it running now. Apologies for the confusion!

**Comment by swabhs** [comment]
I was able to reproduce the problem - hence am reopening the issue. It seems like the gpu device associated with the alternating_highway_lstm_cuda model has been hard coded as 0. Hence the model runs just fine if gpu 0 is available, but crashes with the following error if not (even as I change the cuda_device in the training_config):

```
CUDA Error: an illegal memory access was encountered highway_lstm_kernel.cu 495
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1512386481460/work/torch/lib/THC/THCGeneral.c line=844 error=77 : an illegal memory access was encountered
Traceback (most recent call last):
  File "/home/swabha/miniconda2/envs/allennlp/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/swabha/miniconda2/envs/allennlp/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/swabha/open-sesame-deeper/allennlp/run.py", line 13, in <module>
    main(prog="python -m allennlp.run")
  File "/home/swabha/open-sesame-deeper/allennlp/commands/__init__.py", line 77, in main
    args.func(args)
  File "/home/swabha/open-sesame-deeper/allennlp/commands/train.py", line 73, in train_model_from_args
    train_model_from_file(args.param_path, args.serialization_dir)
  File "/home/swabha/open-sesame-deeper/allennlp/commands/train.py", line 89, in train_model_from_file
    return train_model(params, serialization_dir)
  File "/home/swabha/open-sesame-deeper/allennlp/commands/train.py", line 178, in train_model
    trainer.train()
  File "/home/swabha/open-sesame-deeper/allennlp/training/trainer.py", line 374, in train
    train_metrics = self._train_epoch(epoch)
  File "/home/swabha/open-sesame-deeper/allennlp/training/trainer.py", line 223, in _train_epoch
    loss = self._batch_loss(batch, for_training=True)
  File "/home/swabha/open-sesame-deeper/allennlp/training/trainer.py", line 176, in _batch_loss
    output_dict = self._model(**batch)
  File "/home/swabha/miniconda2/envs/allennlp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/swabha/open-sesame-deeper/allennlp/models/semantic_role_labeler.py", line 131, in forward
    encoded_text = self.stacked_encoder(embedded_text_with_verb_indicator, mask)
  File "/home/swabha/miniconda2/envs/allennlp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/swabha/open-sesame-deeper/allennlp/modules/seq2seq_encoders/pytorch_seq2seq_wrapper.py", line 77, in forward
    self.sort_and_run_forward(self._module, inputs, mask, hidden_state)
  File "/home/swabha/open-sesame-deeper/allennlp/modules/encoder_base.py", line 117, in sort_and_run_forward
    module_output, final_states = module(packed_sequence_input, initial_states)
  File "/home/swabha/miniconda2/envs/allennlp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/swabha/open-sesame-deeper/allennlp/modules/alternating_highway_lstm.py", line 260, in forward
    output = pack_padded_sequence(output, lengths, batch_first=True)
  File "/home/swabha/miniconda2/envs/allennlp/lib/python3.6/site-packages/torch/nn/utils/rnn.py", line 76, in pack_padded_sequence
    return PackedSequence(torch.cat(steps), batch_sizes)
RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /opt/conda/conda-bld/pytorch_1512386481460/work/torch/lib/THC/THCGeneral.c
:844
```

**Comment by swabhs** [comment]
I am able to temporarily work around this by setting
`torch.cuda.set_device(self._cuda_device)` in trainer.py right after https://github.com/allenai/allennlp/blob/master/allennlp/training/trainer.py#L141

**Comment by DeNeutoy** [comment]
That seems like a sensible fix. One other thing you can do is use `CUDA_VISIBLE_DEVICES=3 /command/to/run/your/script` which will limit the available GPUs for a particular process. I'm going to close this, as we won't be fixing this - hopefully we'll either replace the use of this with something better, or I have been working on a more stable version which uses more native pytorch bindings, which we'll release if we can make it as fast as this. Thanks for raising the issue though!

**Comment by swabhs** [comment]
Ah so setting the flag ```CUDA_VISIBLE_DEVICES``` unfortunately does not work either, I tried that too. Thanks for looking into alternatives for this issue!
