### ISSUE TITLE
Trained seq2seq fails to evaluate. 

### ISSUE THREAD

**Issue by LeoLiu1998** [allenai/allennlp#784]
Hi, after I trained the simple_seq2seq model; it prints out errors after indexing the dev set

```
2018-02-05 16:03:05,500 - INFO - allennlp.data.dataset - Indexing dataset
100%|████████████████████████████████████████████| 24568/24568 [00:08<00:00, 2912.27it/s]
2018-02-05 16:03:13,937 - INFO - allennlp.commands.evaluate - Iterating over dataset
  0%|                                                            | 0/768 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/Users/leoliu/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/leoliu/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/leoliu/allennlp/allennlp/run.py", line 13, in <module>
    main(prog="python -m allennlp.run")
  File "/Users/leoliu/allennlp/allennlp/commands/__init__.py", line 70, in main
    args.func(args)
  File "/Users/leoliu/allennlp/allennlp/commands/evaluate.py", line 111, in evaluate_from_args
    metrics = evaluate(model, dataset, iterator, args.cuda_device)
  File "/Users/leoliu/allennlp/allennlp/commands/evaluate.py", line 79, in evaluate
    for batch in generator_tqdm:
  File "/Users/leoliu/anaconda3/lib/python3.6/site-packages/tqdm/_tqdm.py", line 955, in __iter__
    for obj in iterable:
  File "/Users/leoliu/allennlp/allennlp/data/iterators/data_iterator.py", line 44, in __call__
    yield from self._yield_one_epoch(dataset, shuffle)
  File "/Users/leoliu/allennlp/allennlp/data/iterators/data_iterator.py", line 55, in _yield_one_epoch
    grouped_instances = self._create_batches(dataset, shuffle)
  File "/Users/leoliu/allennlp/allennlp/data/iterators/bucket_iterator.py", line 69, in _create_batches
    self._padding_noise)
  File "/Users/leoliu/allennlp/allennlp/data/iterators/bucket_iterator.py", line 96, in _sort_dataset_by_padding
    padding_lengths = cast(Dict[str, Dict[str, float]], instance.get_padding_lengths())
  File "/Users/leoliu/allennlp/allennlp/data/instance.py", line 51, in get_padding_lengths
    lengths[field_name] = field.get_padding_lengths()
  File "/Users/leoliu/allennlp/allennlp/data/fields/text_field.py", line 74, in get_padding_lengths
    for key in token_lengths[0].keys():
IndexError: list index out of range

```

I am not sure what's going on, and I am not sure whether this error is related to the fact that I made a mistake of making **target_namespace** to be **target_tokens**, which should have been "source_tokens" (if I want to limit the vocabulary set to the source vocab)

**Comment by matt-gardner** [comment]
You're getting this error because you're (1) using a really old version of allennlp, and (2) you have a `TextField` with no tokens in it.  Because you're using a seq2seq model, this _probably_ means that you have an instance that has an empty source or an empty target - that's about the only way you can get this error, unless you've changed the `DatasetReader`.

**Comment by matt-gardner** [comment]
Yeah, you'll need to write that yourself. There's now a tutorial on how to do it that should be helpful: https://github.com/allenai/allennlp/blob/master/tutorials/getting_started/making_predictions_and_creating_a_demo.md.

**Comment by schmmd** [comment]
Please re-open if you have more questions.
