### ISSUE TITLE
FileNotFoundError when trying to save model using elmo

### ISSUE THREAD

**Issue by sebastianGehrmann** [allenai/allennlp#838]
I am following the tutorial here https://github.com/allenai/allennlp/blob/master/tutorials/how_to/elmo.md to extend the simple_tagger.json with elmo embeddings. 
The training runs without a problem, but when the script is writing the model, it encounters a filenotfounderror: 

```
2018-02-13 12:27:59,233 - INFO - allennlp.models.archival - archiving weights and vocabulary to trained_model_elmo_180213/model.tar.gz
Traceback (most recent call last):
  File "/n/home09/sgehrmann/.conda/envs/my_root3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/n/home09/sgehrmann/.conda/envs/my_root3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/n/home09/sgehrmann/.conda/envs/my_root3/lib/python3.6/site-packages/allennlp-0.3.1_unreleased-py3.6.egg/allennlp/run.py", line 18, in <module>
    main(prog="python -m allennlp.run")
  File "/n/home09/sgehrmann/.conda/envs/my_root3/lib/python3.6/site-packages/allennlp-0.3.1_unreleased-py3.6.egg/allennlp/commands/__init__.py", line 79, in main
    args.func(args)
  File "/n/home09/sgehrmann/.conda/envs/my_root3/lib/python3.6/site-packages/allennlp-0.3.1_unreleased-py3.6.egg/allennlp/commands/train.py", line 93, in train_model_from_args
    train_model_from_file(args.param_path, args.serialization_dir, args.overrides, args.file_friendly_logging)
  File "/n/home09/sgehrmann/.conda/envs/my_root3/lib/python3.6/site-packages/allennlp-0.3.1_unreleased-py3.6.egg/allennlp/commands/train.py", line 112, in train_model_from_file
    return train_model(params, serialization_dir, file_friendly_logging)
  File "/n/home09/sgehrmann/.conda/envs/my_root3/lib/python3.6/site-packages/allennlp-0.3.1_unreleased-py3.6.egg/allennlp/commands/train.py", line 209, in train_model
    archive_model(serialization_dir, files_to_archive=params.files_to_archive)
  File "/n/home09/sgehrmann/.conda/envs/my_root3/lib/python3.6/site-packages/allennlp-0.3.1_unreleased-py3.6.egg/allennlp/models/archival.py", line 84, in archive_model
    archive.add(filename, arcname=f"fta/{key}")
  File "/n/home09/sgehrmann/.conda/envs/my_root3/lib/python3.6/tarfile.py", line 1933, in add
    tarinfo = self.gettarinfo(name, arcname)
  File "/n/home09/sgehrmann/.conda/envs/my_root3/lib/python3.6/tarfile.py", line 1802, in gettarinfo
    statres = os.lstat(name)
FileNotFoundError: [Errno 2] No such file or directory: 'https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x4096_512_2048cnn_2xhighway/elmo_2x4096_512_2048cnn_2xhighway_options.json'
```

The model.tar.gz is still being written so file, so I tried to predict regardless of the error, which runs into the following error: 

```
Traceback (most recent call last):
  File "/n/home09/sgehrmann/.conda/envs/my_root3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/n/home09/sgehrmann/.conda/envs/my_root3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/n/home09/sgehrmann/.conda/envs/my_root3/lib/python3.6/site-packages/allennlp-0.3.1_unreleased-py3.6.egg/allennlp/run.py", line 18, in <module>
    main(prog="python -m allennlp.run")
  File "/n/home09/sgehrmann/.conda/envs/my_root3/lib/python3.6/site-packages/allennlp-0.3.1_unreleased-py3.6.egg/allennlp/commands/__init__.py", line 79, in main
    args.func(args)
  File "/n/home09/sgehrmann/.conda/envs/my_root3/lib/python3.6/site-packages/allennlp-0.3.1_unreleased-py3.6.egg/allennlp/commands/predict.py", line 150, in predict_inner
    predictor = _get_predictor(args, predictors)
  File "/n/home09/sgehrmann/.conda/envs/my_root3/lib/python3.6/site-packages/allennlp-0.3.1_unreleased-py3.6.egg/allennlp/commands/predict.py", line 92, in _get_predictor
    archive = load_archive(args.archive_file, cuda_device=args.cuda_device, overrides=args.overrides)
  File "/n/home09/sgehrmann/.conda/envs/my_root3/lib/python3.6/site-packages/allennlp-0.3.1_unreleased-py3.6.egg/allennlp/models/archival.py", line 139, in load_archive
    cuda_device=cuda_device)
  File "/n/home09/sgehrmann/.conda/envs/my_root3/lib/python3.6/site-packages/allennlp-0.3.1_unreleased-py3.6.egg/allennlp/models/model.py", line 233, in load
    model = Model.from_params(vocab, model_params)
  File "/n/home09/sgehrmann/.conda/envs/my_root3/lib/python3.6/site-packages/allennlp-0.3.1_unreleased-py3.6.egg/allennlp/models/model.py", line 184, in from_params
    model = cls.by_name(choice).from_params(vocab, params)
  File "/n/home09/sgehrmann/.conda/envs/my_root3/lib/python3.6/site-packages/allennlp-0.3.1_unreleased-py3.6.egg/allennlp/models/simple_tagger.py", line 145, in from_params
    text_field_embedder = TextFieldEmbedder.from_params(vocab, embedder_params)
  File "/n/home09/sgehrmann/.conda/envs/my_root3/lib/python3.6/site-packages/allennlp-0.3.1_unreleased-py3.6.egg/allennlp/modules/text_field_embedders/text_field_embedder.py", line 42, in from_params
    return cls.by_name(choice).from_params(vocab, params)
  File "/n/home09/sgehrmann/.conda/envs/my_root3/lib/python3.6/site-packages/allennlp-0.3.1_unreleased-py3.6.egg/allennlp/modules/text_field_embedders/basic_text_field_embedder.py", line 59, in from_params
    token_embedders[key] = TokenEmbedder.from_params(vocab, embedder_params)
  File "/n/home09/sgehrmann/.conda/envs/my_root3/lib/python3.6/site-packages/allennlp-0.3.1_unreleased-py3.6.egg/allennlp/modules/token_embedders/token_embedder.py", line 32, in from_params
    return cls.by_name(choice).from_params(vocab, params)
  File "/n/home09/sgehrmann/.conda/envs/my_root3/lib/python3.6/site-packages/allennlp-0.3.1_unreleased-py3.6.egg/allennlp/modules/token_embedders/elmo_token_embedder.py", line 75, in from_params
    return cls(options_file, weight_file, do_layer_norm, dropout, requires_grad=requires_grad)
  File "/n/home09/sgehrmann/.conda/envs/my_root3/lib/python3.6/site-packages/allennlp-0.3.1_unreleased-py3.6.egg/allennlp/modules/token_embedders/elmo_token_embedder.py", line 44, in __init__
    requires_grad=requires_grad)
  File "/n/home09/sgehrmann/.conda/envs/my_root3/lib/python3.6/site-packages/allennlp-0.3.1_unreleased-py3.6.egg/allennlp/modules/elmo.py", line 67, in __init__
    self._elmo_lstm = _ElmoBiLm(options_file, weight_file, requires_grad=requires_grad)
  File "/n/home09/sgehrmann/.conda/envs/my_root3/lib/python3.6/site-packages/allennlp-0.3.1_unreleased-py3.6.egg/allennlp/modules/elmo.py", line 403, in __init__
    self._token_embedder = _ElmoCharacterEncoder(options_file, weight_file, requires_grad=requires_grad)
  File "/n/home09/sgehrmann/.conda/envs/my_root3/lib/python3.6/site-packages/allennlp-0.3.1_unreleased-py3.6.egg/allennlp/modules/elmo.py", line 189, in __init__
    with open(cached_path(options_file), 'r') as fin:
  File "/n/home09/sgehrmann/.conda/envs/my_root3/lib/python3.6/site-packages/allennlp-0.3.1_unreleased-py3.6.egg/allennlp/common/file_utils.py", line 76, in cached_path
    raise FileNotFoundError("file {} not found".format(url_or_filename))
FileNotFoundError: file /tmp/tmpe3scsv3h/fta/model.text_field_embedder.elmo.options_file not found
```

(this is running the latest version of allenlp with pytorch 0.3.0)

**Comment by matt-peters** [comment]
This looks like a problem with the archival process when saving a file retrieved via http.

As a work around until we can fix this, try downloading the two ELMo related files to local disk then modifying the configuration file to use them instead of the http versions.

**Comment by sebastianGehrmann** [comment]
Thanks @matt-peters your workaround works. Seems to indeed be related to the remote file location.

**Comment by schmmd** [comment]
Re-opening so I figure out the root cause.  I'm glad the work-around worked in the short term!

**Comment by anushkmittal** [comment]
i am not 100% sure if this is related, but I am experiencing the same issue

```
INFO - allennlp.common.params -   model.text_field_embedder.token_embedders.elmo.type = elmo_token_embedder
[2019-10-06 16:07:31 -0400] [59110] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/anushkmittal/miniconda3/envs/hmtl_two/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/anushkmittal/miniconda3/envs/hmtl_two/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/anushkmittal/miniconda3/envs/hmtl_two/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/anushkmittal/miniconda3/envs/hmtl_two/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/anushkmittal/miniconda3/envs/hmtl_two/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/Users/anushkmittal/miniconda3/envs/hmtl_two/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/anushkmittal/miniconda3/envs/hmtl_two/lib/python3.7/site-packages/gunicorn/util.py", line 362, in import_app
    app = eval(obj, vars(mod))
  File "<string>", line 1, in <module>
  File "/Users/anushkmittal/downloads/hmtl/demo/server.py", line 51, in build_app
    ALL_RESOURCE = AllResource(model_name=model_name, mode=mode)
  File "/Users/anushkmittal/downloads/hmtl/demo/server.py", line 15, in __init__
    self.jmd = HMTLPredictor(model_name=model_name)
  File "/Users/anushkmittal/downloads/hmtl/demo/hmtlPredictor.py", line 129, in __init__
    model, vocab, token_indexers = load_model(model_name=model_name)
  File "/Users/anushkmittal/downloads/hmtl/demo/hmtlPredictor.py", line 115, in load_model
    model = Model.from_params(vocab=vocab, params=model_params, regularizer=None)
  File "/Users/anushkmittal/miniconda3/envs/hmtl_two/lib/python3.7/site-packages/allennlp/common/from_params.py", line 245, in from_params
    return subclass.from_params(params=params, **extras)
  File "../hmtl/models/hmtl.py", line 200, in from_params
    return cls(vocab=vocab, params=params, regularizer=regularizer)
  File "../hmtl/models/hmtl.py", line 49, in __init__
    text_field_embedder = BasicTextFieldEmbedder.from_params(vocab=vocab, params=text_field_embedder_params)
  File "/Users/anushkmittal/miniconda3/envs/hmtl_two/lib/python3.7/site-packages/allennlp/modules/text_field_embedders/basic_text_field_embedder.py", line 117, in from_params
    for name, subparams in token_embedder_params.items()
  File "/Users/anushkmittal/miniconda3/envs/hmtl_two/lib/python3.7/site-packages/allennlp/modules/text_field_embedders/basic_text_field_embedder.py", line 117, in <dictcomp>
    for name, subparams in token_embedder_params.items()
  File "/Users/anushkmittal/miniconda3/envs/hmtl_two/lib/python3.7/site-packages/allennlp/common/from_params.py", line 245, in from_params
    return subclass.from_params(params=params, **extras)
  File "/Users/anushkmittal/miniconda3/envs/hmtl_two/lib/python3.7/site-packages/allennlp/modules/token_embedders/elmo_token_embedder.py", line 98, in from_params
    params.add_file_to_archive('options_file')
  File "/Users/anushkmittal/miniconda3/envs/hmtl_two/lib/python3.7/site-packages/allennlp/common/params.py", line 157, in add_file_to_archive
    self.files_to_archive[f"{self.history}{name}"] = cached_path(self.get(name))
  File "/Users/anushkmittal/miniconda3/envs/hmtl_two/lib/python3.7/site-packages/allennlp/common/file_utils.py", line 92, in cached_path
    raise FileNotFoundError("file {} not found".format(url_or_filename))
FileNotFoundError: file ../data/elmo/2x4096_512_2048cnn_2xhighway_options.json not found
```

**Comment by schmmd** [comment]
@anushkmittal can you open a new issue with a complete repro?  Please do cross-link this issue.
