### ISSUE TITLE
GPU Memory Exhausted while using Elmo

### ISSUE THREAD

**Issue by rajasagashe** [allenai/allennlp#860]
Hello, I'm training the wikitables_semantic_parser with Elmo representations and am running out of gpu memory. I also don't have cudnn installed(since i don't have root access) and am running with the cudnn backend disabled. Here's the full stack trace:

```
2018-02-15 12:29:10,275 - INFO - allennlp.training.trainer - Epoch 0/19
2018-02-15 12:29:10,275 - INFO - allennlp.training.trainer - Peak CPU memory usage MB: 13889.476
2018-02-15 12:29:10,552 - INFO - allennlp.training.trainer - GPU 0 memory usage MB: 0
2018-02-15 12:29:10,552 - INFO - allennlp.training.trainer - GPU 1 memory usage MB: 673
2018-02-15 12:29:10,553 - INFO - allennlp.training.trainer - GPU 2 memory usage MB: 0
  0%|          | 0/6886 [00:00<?, ?it/s]2018-02-15 12:29:10,554 - INFO - allennlp.training.trainer - Training
parse_acc: 0.00, loss: 13.04 ||:  14%|#4        | 975/6886 [08:46<53:09,  1.85it/s]THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1512386481460/work/torch/lib/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "anaconda3/envs/allennlp/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "anaconda3/envs/allennlp/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "allennlp/allennlp/run.py", line 18, in <module>
    main(prog="python -m allennlp.run")
  File "allennlp/allennlp/commands/__init__.py", line 81, in main
    args.func(args)
  File "allennlp/allennlp/commands/train.py", line 107, in train_model_from_args
    train_model_from_file(args.param_path, args.serialization_dir, args.overrides, args.file_friendly_logging)
  File "allennlp/allennlp/commands/train.py", line 126, in train_model_from_file
    return train_model(params, serialization_dir, file_friendly_logging)
  File "allennlp/allennlp/commands/train.py", line 220, in train_model
    metrics = trainer.train()
  File "allennlp/allennlp/training/trainer.py", line 642, in train
    train_metrics = self._train_epoch(epoch)
  File "allennlp/allennlp/training/trainer.py", line 432, in _train_epoch
    loss = self._batch_loss(batch, for_training=True)
  File "allennlp/allennlp/training/trainer.py", line 369, in _batch_loss
    output_dict = self._model(**batch)
  File "anaconda3/envs/allennlp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "allennlp/allennlp/models/encoder_decoders/wikitables_semantic_parser.py", line 183, in forward
    table_mask = util.get_text_field_mask(table_text, num_wrapping_dims=1).float()
  File "anaconda3/envs/allennlp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "allennlp/allennlp/modules/text_field_embedders/basic_text_field_embedder.py", line 52, in forward
    token_vectors = embedder(tensor)
  File "anaconda3/envs/allennlp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "allennlp/allennlp/modules/time_distributed.py", line 35, in forward
    reshaped_outputs = self._module(*reshaped_inputs)
  File "anaconda3/envs/allennlp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "allennlp/allennlp/modules/token_embedders/elmo_token_embedder.py", line 62, in forward
    elmo_output = self._elmo(inputs)
  File "anaconda3/envs/allennlp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "allennlp/allennlp/modules/elmo.py", line 103, in forward
    bilm_output = self._elmo_lstm(reshaped_inputs)
  File "anaconda3/envs/allennlp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "allennlp/allennlp/modules/elmo.py", line 441, in forward
    token_embedding = self._token_embedder(inputs)
  File "anaconda3/envs/allennlp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "allennlp/allennlp/modules/elmo.py", line 262, in forward
    convolved, _ = torch.max(convolved, dim=-1)
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1512386481460/work/torch/lib/THC/generic/THCStorage.cu:58
```

**Comment by matt-peters** [comment]
How much GPU memory was your model using before adding ELMo?  If it is was near the total GPU memory you will need to lower your batch size as the ELMo weights and layer activations all require additional memory.

**Comment by rajasagashe** [comment]
It was using 5gb on a batch size of 1, and my gpu has 12gb.

**Comment by matt-peters** [comment]
I don't think ELMo would require that much additional memory, unless your sequences are very long.  How long are your sequences?

Other potential reasons for running out of memory:

* Something about running without cuDNN is causing the memory issue. The exception is being raised in the convolutions so perhaps this is the reason.  I've never tried to run without cuDNN so can't verify things work properly in that case.
* There is something else in your network that is strongly dependent on the ELMo layer dimension.  Does adding the 1024 ELMo vectors cause other layers in your network to greatly increase in size?

**Comment by matt-gardner** [comment]
The ELMo code is running over something of shape `(1, num_entities, num_entity_tokens, num_token_characters)`, where `num_entities` might be quite large for some tables (it's basically one "entity" per cell in the table).  So, after you do all of the time distributing, the effective batch size that gets to the elmo code might be pretty high.  @rajasagashe, can you print out the shape of the tensor before it goes into elmo?

**Comment by rajasagashe** [comment]
I have cudnn now and it returns this error at the same line as the trace above
` RuntimeError: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-con
tiguous input.`

You're right, it looks pretty big right before it fails. Here is the output over 3 calls of forward, the last is where it fails. The two sizes printed are for the 2 tensors in table_text. The first is the token embedding the second is elmo.
```
torch.Size([1, 37, 7])
elmo torch.Size([1, 37, 7, 50])
parse_acc: 0.00, loss: 12.98 ||:  14%|#4        | 974/6886 [06:14<37:56,  2.60it/s]tokens
torch.Size([1, 26, 4])
elmo torch.Size([1, 26, 4, 50])
parse_acc: 0.00, loss: 12.98 ||:  14%|#4        | 975/6886 [06:15<37:55,  2.60it/s]tokens
torch.Size([1, 752, 72])
elmo torch.Size([1, 752, 72, 50])
```

**Comment by matt-peters** [comment]
That's an effective batch size of 752 * 72 = 54144 tokens.  That's probably too large.

**Comment by matt-gardner** [comment]
@rajasagashe, probably the best way to fix this is to truncate the table entity text.  There's not really any reason to embed a 72 word table cell - the first 5-10 words is almost certainly sufficient for anything we're doing in the parser.

@matt-peters, @DeNeutoy, is it worth thinking about a way to split up large batches like this internal to the elmo code, and putting it back together after the vectors are computed?  The batch size here is 752, with 72 words per batch element - you could imagine splitting it into batches of size 64 or something, running elmo in a loop over those batches, then grouping them again.  Not sure it's worth the additional complexity, but I don't know of another way to handle this case if we really don't want to trim down our sentence length.

**Comment by schmmd** [comment]
@DeNeutoy votes "no".

**Comment by schmmd** [comment]
Closing for now, as we're unlikely to do this.
