### ISSUE TITLE
Key error when calling predict command on trained model

### ISSUE THREAD

**Issue by kearnsw** [allenai/allennlp#881]
When loading model using the predict command: `python -m allennlp.run predict models/cnn-elmo-no-glove-600/model.tar.gz ../data/test/test.jsonl --include-package sc --predictor sentence-classifier` a key error is thrown. 

There is no issue calling evaluate on the data and `@@UNKNOWN@@` is in the vocabulary/tokens.txt file. Below is the traceback of the error: 
```
Traceback (most recent call last):
  File "/home/kearnsw/packages/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/kearnsw/packages/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/kearnsw/packages/allennlp/allennlp/run.py", line 18, in <module>
    main(prog="python -m allennlp.run")
  File "/home/kearnsw/packages/allennlp/allennlp/commands/__init__.py", line 81, in main
    args.func(args)
  File "/home/kearnsw/packages/allennlp/allennlp/commands/predict.py", line 182, in predict_inner
    _run(predictor, input_file, output_file, args.batch_size, not args.silent, args.cuda_device)
  File "/home/kearnsw/packages/allennlp/allennlp/commands/predict.py", line 153, in _run
    _run_predictor(batch_json_data)
  File "/home/kearnsw/packages/allennlp/allennlp/commands/predict.py", line 131, in _run_predictor
    result = predictor.predict_json(batch_data[0], cuda_device)
  File "/home/kearnsw/packages/allennlp/allennlp/service/predictors/predictor.py", line 36, in predict_json
    outputs = self._model.forward_on_instance(instance, cuda_device)
  File "/home/kearnsw/packages/allennlp/allennlp/models/model.py", line 120, in forward_on_instance
    return self.forward_on_instances([instance], cuda_device)[0]
  File "/home/kearnsw/packages/allennlp/allennlp/models/model.py", line 136, in forward_on_instances
    dataset.index_instances(self.vocab)
  File "/home/kearnsw/packages/allennlp/allennlp/data/dataset.py", line 163, in index_instances
    instance.index_fields(vocab)
  File "/home/kearnsw/packages/allennlp/allennlp/data/instance.py", line 50, in index_fields
    field.index(vocab)
  File "/home/kearnsw/packages/allennlp/allennlp/data/fields/label_field.py", line 83, in index
    self._label_id = vocab.get_token_index(self.label, self._label_namespace)  # type: ignore
  File "/home/kearnsw/packages/allennlp/allennlp/data/vocabulary.py", line 405, in get_token_index
    return self._token_to_index[namespace][self._oov_token]
KeyError: '@@UNKNOWN@@'

```

**Comment by joelgrus** [comment]
from the stack trace it looks like the problem is in `label_field`, which suggests that the problem is an unknown _label_ (that is, a label in your test set that wasn't in the training set). (Unless you have some other label field in your model, in which case it might be that one instead.)

You're using your own `Predictor`, it looks like? Does your `_json_to_instance` involve the label somehow?

**Comment by kearnsw** [comment]
Thanks, that's exactly the case. I added a check for labels outside the label namespace within the predictor and that solves the problem.

**Comment by samareshyadav55** [comment]
Hi kearnsw, I am facing a Similar issue, want to know how you solved it.

**Comment by mina1460** [comment]
@samareshyadav55 hey samar, I am facing the exact problem. Did you manage to solve it?
