### ISSUE TITLE
KeyError during model prediction

### ISSUE THREAD

**Issue by christos-c** [allenai/allennlp#901]
I tried running the following instructions for the [coreference resolution models](http://allennlp.org/models):
```
echo '{"document": "The woman reading a newspaper sat on the bench with her dog."}' > examples.jsonl
python -m allennlp.run predict \
    https://s3-us-west-2.amazonaws.com/allennlp/models/coref-model-2017.11.09.tar.gz \
    examples.jsonl
```
and I get the following error:
```
2018-02-20 17:31:46,344 - INFO - allennlp.nn.initializers -    _text_field_embedder.token_embedder_tokens.weight
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/stage/allennlp/allennlp/run.py", line 18, in <module>
    main(prog="python -m allennlp.run")
  File "/stage/allennlp/allennlp/commands/__init__.py", line 67, in main
    args.func(args)
  File "/stage/allennlp/allennlp/commands/predict.py", line 172, in predict_inner
    predictor = _get_predictor(args, predictors)
  File "/stage/allennlp/allennlp/commands/predict.py", line 114, in _get_predictor
    overrides=args.overrides)
  File "/stage/allennlp/allennlp/models/archival.py", line 149, in load_archive
    cuda_device=cuda_device)
  File "/stage/allennlp/allennlp/models/model.py", line 235, in load
    model.load_state_dict(model_state)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 522, in load_state_dict
    .format(name))
KeyError: 'unexpected key "_mention_feedforward._module._linear_layers.0.weight" in state_dict'
```

I tried this both using the docker installation (`docker run -p 8000:8000 -it --rm allennlp/allennlp`)
and the [installation from source](https://github.com/allenai/allennlp/blob/v0.3.0/tutorials/getting_started/installation.md#installing-from-source). 

I also tried with the latest PyTorch (0.3.1) and the recommended (0.2.0).

**Comment by DeNeutoy** [comment]
Ah sorry, that's my fault - I need to update the model on the website. This is the correct model for the current state of the repo:
https://s3-us-west-2.amazonaws.com/allennlp/models/coref-model-2018.02.05.tar.gz

**Comment by christos-c** [comment]
Thanks for your quick response @DeNeutoy. I changed the model file, but now I get this error:
```
2018-02-20 20:11:20,049 - INFO - allennlp.common.params - dataset_reader.lazy = False
Traceback (most recent call last):
  File "/Users/chrchrs/anaconda3/envs/allennlp/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/chrchrs/anaconda3/envs/allennlp/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/chrchrs/research/software/allennlp/allennlp/run.py", line 18, in <module>
    main(prog="python -m allennlp.run")
  File "/Users/chrchrs/research/software/allennlp/allennlp/commands/__init__.py", line 67, in main
    args.func(args)
  File "/Users/chrchrs/research/software/allennlp/allennlp/commands/predict.py", line 191, in predict_inner
    args.cuda_device)
  File "/Users/chrchrs/research/software/allennlp/allennlp/commands/predict.py", line 157, in _run
    _run_predictor(batch_json_data)
  File "/Users/chrchrs/research/software/allennlp/allennlp/commands/predict.py", line 135, in _run_predictor
    result = predictor.predict_json(batch_data[0], cuda_device)
  File "/Users/chrchrs/research/software/allennlp/allennlp/service/predictors/predictor.py", line 36, in predict_json
    outputs = self._model.forward_on_instance(instance, cuda_device)
  File "/Users/chrchrs/research/software/allennlp/allennlp/models/model.py", line 120, in forward_on_instance
    return self.forward_on_instances([instance], cuda_device)[0]
  File "/Users/chrchrs/research/software/allennlp/allennlp/models/model.py", line 138, in forward_on_instances
    outputs = self.decode(self(**model_input))
  File "/Users/chrchrs/anaconda3/envs/allennlp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/chrchrs/research/software/allennlp/allennlp/models/coreference_resolution/coref.py", line 175, in forward
    attended_span_embeddings = self._attentive_span_extractor(text_embeddings, spans)
  File "/Users/chrchrs/anaconda3/envs/allennlp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/chrchrs/research/software/allennlp/allennlp/modules/span_extractors/self_attentive_span_extractor.py", line 63, in forward
    max_batch_span_width = int(span_widths.max().data) + 1
TypeError: int() argument must be a string, a bytes-like object or a number, not 'torch.LongTensor'
```

(I am using the source-installed version of allennlp)

**Comment by matt-gardner** [comment]
I'm pretty sure this is because you're using pytorch 0.2.  If you upgrade back to 0.3 or 0.3.1 (if you're using the current master), that should work.

**Comment by christos-c** [comment]
Thanks @matt-gardner, that worked! In that case, I suggest updating the [instructions here](https://github.com/allenai/allennlp/blob/v0.3.0/tutorials/getting_started/installation.md#installing-using-pip): "You'll also need to install PyTorch 0.2, following the appropriate instructions for your platform from their website."

**Comment by matt-gardner** [comment]
You're looking at the tutorial for version 0.3, but using code from master - the tutorial on master has already been updated.  We need to figure out a better way to manage tutorial versions, though, I think...

But I'm glad it's working for you!
