### ISSUE TITLE
Issues with "predict" mode:  question_text = json_dict["question"]

### ISSUE THREAD

**Issue by danyaljj** [allenai/allennlp#910]
I have a model with which I can evaluate a dataset successfully: 
```
python3.6 -m allennlp.run evaluate     /Users/daniel/Dropbox/bidaf_train/bidaf-fine-tuned-iter\=5-learning-rate\=0_002/model.tar.gz     --evaluation-data-file /Users/daniel/Desktop/test_all_RemediaOnly_squadFormat_try3.json
```

But the same model and input file have issues when doing predictions: 

```
python3.6 -m allennlp.run predict  /Users/daniel/Dropbox/bidaf_train/bidaf-fine-tuned-iter\=5-learning-rate\=0_002/model.tar.gz /Users/daniel/Desktop/test_all_RemediaOnly_squadFormat_try3.json 
```
The error is: 
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/daniel/ideaProjects/allennlp/allennlp/run.py", line 18, in <module>
    main(prog="python -m allennlp.run")
  File "/Users/daniel/ideaProjects/allennlp/allennlp/commands/__init__.py", line 65, in main
    args.func(args)
  File "/Users/daniel/ideaProjects/allennlp/allennlp/commands/predict.py", line 191, in predict_inner
    args.cuda_device)
  File "/Users/daniel/ideaProjects/allennlp/allennlp/commands/predict.py", line 157, in _run
    _run_predictor(batch_json_data)
  File "/Users/daniel/ideaProjects/allennlp/allennlp/commands/predict.py", line 135, in _run_predictor
    result = predictor.predict_json(batch_data[0], cuda_device)
  File "/Users/daniel/ideaProjects/allennlp/allennlp/service/predictors/predictor.py", line 35, in predict_json
    instance, return_dict = self._json_to_instance(inputs)
  File "/Users/daniel/ideaProjects/allennlp/allennlp/service/predictors/bidaf.py", line 19, in _json_to_instance
    question_text = json_dict["question"]
KeyError: 'question'
```
Btw here is the input json if you wanna take a look at it: 
https://codebeautify.org/jsonviewer/cb9ca205

-----------
The full log: 
```
huntsman-ve503-0125:allennlp daniel$ python3.6 -m allennlp.run predict  /Users/daniel/Dropbox/bidaf_train/bidaf-fine-tuned-iter\=5-learning-rate\=0_002/model.tar.gz /Users/daniel/Desktop/test_all_RemediaOnly_squadFormat_try3.json 
/usr/local/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-02-21 15:50:38,699 - INFO - allennlp.models.archival - extracting archive file /Users/daniel/Dropbox/bidaf_train/bidaf-fine-tuned-iter=5-learning-rate=0_002/model.tar.gz to temp dir /var/folders/g9/72x1k9_s6sjgm_h5z_g4dwc80000gn/T/tmplcmxwix0
2018-02-21 15:50:40,024 - INFO - allennlp.data.vocabulary - Loading token dictionary from /var/folders/g9/72x1k9_s6sjgm_h5z_g4dwc80000gn/T/tmplcmxwix0/vocabulary.
2018-02-21 15:50:40,533 - INFO - allennlp.common.params - model.type = bidaf
2018-02-21 15:50:40,534 - INFO - allennlp.common.params - model.text_field_embedder.type = basic
2018-02-21 15:50:40,534 - INFO - allennlp.common.params - model.text_field_embedder.tokens.type = embedding
2018-02-21 15:50:40,534 - INFO - allennlp.common.params - model.text_field_embedder.tokens.num_embeddings = None
2018-02-21 15:50:40,535 - INFO - allennlp.common.params - model.text_field_embedder.tokens.vocab_namespace = tokens
2018-02-21 15:50:40,535 - INFO - allennlp.common.params - model.text_field_embedder.tokens.embedding_dim = 100
2018-02-21 15:50:40,535 - INFO - allennlp.common.params - model.text_field_embedder.tokens.pretrained_file = None
2018-02-21 15:50:40,535 - INFO - allennlp.common.params - model.text_field_embedder.tokens.projection_dim = None
2018-02-21 15:50:40,536 - INFO - allennlp.common.params - model.text_field_embedder.tokens.trainable = False
2018-02-21 15:50:40,536 - INFO - allennlp.common.params - model.text_field_embedder.tokens.padding_index = None
2018-02-21 15:50:40,536 - INFO - allennlp.common.params - model.text_field_embedder.tokens.max_norm = None
2018-02-21 15:50:40,536 - INFO - allennlp.common.params - model.text_field_embedder.tokens.norm_type = 2.0
2018-02-21 15:50:40,536 - INFO - allennlp.common.params - model.text_field_embedder.tokens.scale_grad_by_freq = False
2018-02-21 15:50:40,536 - INFO - allennlp.common.params - model.text_field_embedder.tokens.sparse = False
2018-02-21 15:50:42,116 - INFO - allennlp.common.params - model.text_field_embedder.token_characters.type = character_encoding
2018-02-21 15:50:42,117 - INFO - allennlp.common.params - model.text_field_embedder.token_characters.embedding.num_embeddings = 262
2018-02-21 15:50:42,118 - INFO - allennlp.common.params - model.text_field_embedder.token_characters.embedding.vocab_namespace = token_characters
2018-02-21 15:50:42,118 - INFO - allennlp.common.params - model.text_field_embedder.token_characters.embedding.embedding_dim = 16
2018-02-21 15:50:42,119 - INFO - allennlp.common.params - model.text_field_embedder.token_characters.embedding.pretrained_file = None
2018-02-21 15:50:42,120 - INFO - allennlp.common.params - model.text_field_embedder.token_characters.embedding.projection_dim = None
2018-02-21 15:50:42,128 - INFO - allennlp.common.params - model.text_field_embedder.token_characters.embedding.trainable = True
2018-02-21 15:50:42,129 - INFO - allennlp.common.params - model.text_field_embedder.token_characters.embedding.padding_index = None
2018-02-21 15:50:42,129 - INFO - allennlp.common.params - model.text_field_embedder.token_characters.embedding.max_norm = None
2018-02-21 15:50:42,129 - INFO - allennlp.common.params - model.text_field_embedder.token_characters.embedding.norm_type = 2.0
2018-02-21 15:50:42,131 - INFO - allennlp.common.params - model.text_field_embedder.token_characters.embedding.scale_grad_by_freq = False
2018-02-21 15:50:42,131 - INFO - allennlp.common.params - model.text_field_embedder.token_characters.embedding.sparse = False
2018-02-21 15:50:42,132 - INFO - allennlp.common.params - model.text_field_embedder.token_characters.encoder.type = cnn
2018-02-21 15:50:42,132 - INFO - allennlp.common.params - model.text_field_embedder.token_characters.encoder.embedding_dim = 16
2018-02-21 15:50:42,132 - INFO - allennlp.common.params - model.text_field_embedder.token_characters.encoder.output_dim = None
2018-02-21 15:50:42,133 - INFO - allennlp.common.params - model.text_field_embedder.token_characters.encoder.num_filters = 100
2018-02-21 15:50:42,133 - INFO - allennlp.common.params - model.text_field_embedder.token_characters.encoder.conv_layer_activation = relu
2018-02-21 15:50:42,135 - INFO - allennlp.common.params - model.text_field_embedder.token_characters.encoder.ngram_filter_sizes = [5]
2018-02-21 15:50:42,141 - INFO - allennlp.common.params - model.text_field_embedder.token_characters.dropout = 0.2
2018-02-21 15:50:42,141 - INFO - allennlp.common.params - model.num_highway_layers = 2
2018-02-21 15:50:42,142 - INFO - allennlp.common.params - model.phrase_layer.type = lstm
2018-02-21 15:50:42,143 - INFO - allennlp.common.params - model.phrase_layer.batch_first = True
2018-02-21 15:50:42,143 - INFO - allennlp.common.params - Converting Params object to dict; logging of default values will not occur when dictionary parameters are used subsequently.
2018-02-21 15:50:42,144 - INFO - allennlp.common.params - CURRENTLY DEFINED PARAMETERS: 
2018-02-21 15:50:42,145 - INFO - allennlp.common.params - model.phrase_layer.bidirectional = True
2018-02-21 15:50:42,145 - INFO - allennlp.common.params - model.phrase_layer.input_size = 200
2018-02-21 15:50:42,145 - INFO - allennlp.common.params - model.phrase_layer.hidden_size = 100
2018-02-21 15:50:42,145 - INFO - allennlp.common.params - model.phrase_layer.num_layers = 1
2018-02-21 15:50:42,145 - INFO - allennlp.common.params - model.phrase_layer.dropout = 0.2
2018-02-21 15:50:42,146 - INFO - allennlp.common.params - model.phrase_layer.batch_first = True
2018-02-21 15:50:42,156 - INFO - allennlp.common.params - model.similarity_function.type = linear
2018-02-21 15:50:42,156 - INFO - allennlp.common.params - model.similarity_function.tensor_1_dim = 200
2018-02-21 15:50:42,157 - INFO - allennlp.common.params - model.similarity_function.tensor_2_dim = 200
2018-02-21 15:50:42,157 - INFO - allennlp.common.params - model.similarity_function.combination = x,y,x*y
2018-02-21 15:50:42,157 - INFO - allennlp.common.params - model.similarity_function.activation = linear
2018-02-21 15:50:42,184 - INFO - allennlp.common.params - model.modeling_layer.type = lstm
2018-02-21 15:50:42,185 - INFO - allennlp.common.params - model.modeling_layer.batch_first = True
2018-02-21 15:50:42,190 - INFO - allennlp.common.params - Converting Params object to dict; logging of default values will not occur when dictionary parameters are used subsequently.
2018-02-21 15:50:42,190 - INFO - allennlp.common.params - CURRENTLY DEFINED PARAMETERS: 
2018-02-21 15:50:42,192 - INFO - allennlp.common.params - model.modeling_layer.bidirectional = True
2018-02-21 15:50:42,192 - INFO - allennlp.common.params - model.modeling_layer.input_size = 800
2018-02-21 15:50:42,192 - INFO - allennlp.common.params - model.modeling_layer.hidden_size = 100
2018-02-21 15:50:42,195 - INFO - allennlp.common.params - model.modeling_layer.num_layers = 2
2018-02-21 15:50:42,196 - INFO - allennlp.common.params - model.modeling_layer.dropout = 0.2
2018-02-21 15:50:42,196 - INFO - allennlp.common.params - model.modeling_layer.batch_first = True
2018-02-21 15:50:42,215 - INFO - allennlp.common.params - model.span_end_encoder.type = lstm
2018-02-21 15:50:42,215 - INFO - allennlp.common.params - model.span_end_encoder.batch_first = True
2018-02-21 15:50:42,215 - INFO - allennlp.common.params - Converting Params object to dict; logging of default values will not occur when dictionary parameters are used subsequently.
2018-02-21 15:50:42,215 - INFO - allennlp.common.params - CURRENTLY DEFINED PARAMETERS: 
2018-02-21 15:50:42,216 - INFO - allennlp.common.params - model.span_end_encoder.bidirectional = True
2018-02-21 15:50:42,216 - INFO - allennlp.common.params - model.span_end_encoder.input_size = 1400
2018-02-21 15:50:42,216 - INFO - allennlp.common.params - model.span_end_encoder.hidden_size = 100
2018-02-21 15:50:42,216 - INFO - allennlp.common.params - model.span_end_encoder.num_layers = 1
2018-02-21 15:50:42,216 - INFO - allennlp.common.params - model.span_end_encoder.dropout = 0.2
2018-02-21 15:50:42,216 - INFO - allennlp.common.params - model.span_end_encoder.batch_first = True
2018-02-21 15:50:42,249 - INFO - allennlp.common.params - model.dropout = 0.2
2018-02-21 15:50:42,249 - INFO - allennlp.common.params - model.initializer = []
2018-02-21 15:50:42,250 - INFO - allennlp.common.params - model.regularizer = []
2018-02-21 15:50:42,250 - INFO - allennlp.common.params - model.mask_lstms = True
2018-02-21 15:50:42,259 - INFO - allennlp.nn.initializers - Initializing parameters
2018-02-21 15:50:42,260 - INFO - allennlp.nn.initializers - Done initializing parameters; the following parameters are using their default initialization from their code
2018-02-21 15:50:42,260 - INFO - allennlp.nn.initializers -    _highway_layer._module._layers.0.bias
2018-02-21 15:50:42,260 - INFO - allennlp.nn.initializers -    _highway_layer._module._layers.0.weight
2018-02-21 15:50:42,261 - INFO - allennlp.nn.initializers -    _highway_layer._module._layers.1.bias
2018-02-21 15:50:42,261 - INFO - allennlp.nn.initializers -    _highway_layer._module._layers.1.weight
2018-02-21 15:50:42,261 - INFO - allennlp.nn.initializers -    _matrix_attention._similarity_function._bias
2018-02-21 15:50:42,262 - INFO - allennlp.nn.initializers -    _matrix_attention._similarity_function._weight_vector
2018-02-21 15:50:42,262 - INFO - allennlp.nn.initializers -    _modeling_layer._module.bias_hh_l0
2018-02-21 15:50:42,262 - INFO - allennlp.nn.initializers -    _modeling_layer._module.bias_hh_l0_reverse
2018-02-21 15:50:42,262 - INFO - allennlp.nn.initializers -    _modeling_layer._module.bias_hh_l1
2018-02-21 15:50:42,262 - INFO - allennlp.nn.initializers -    _modeling_layer._module.bias_hh_l1_reverse
2018-02-21 15:50:42,263 - INFO - allennlp.nn.initializers -    _modeling_layer._module.bias_ih_l0
2018-02-21 15:50:42,263 - INFO - allennlp.nn.initializers -    _modeling_layer._module.bias_ih_l0_reverse
2018-02-21 15:50:42,263 - INFO - allennlp.nn.initializers -    _modeling_layer._module.bias_ih_l1
2018-02-21 15:50:42,263 - INFO - allennlp.nn.initializers -    _modeling_layer._module.bias_ih_l1_reverse
2018-02-21 15:50:42,263 - INFO - allennlp.nn.initializers -    _modeling_layer._module.weight_hh_l0
2018-02-21 15:50:42,263 - INFO - allennlp.nn.initializers -    _modeling_layer._module.weight_hh_l0_reverse
2018-02-21 15:50:42,264 - INFO - allennlp.nn.initializers -    _modeling_layer._module.weight_hh_l1
2018-02-21 15:50:42,264 - INFO - allennlp.nn.initializers -    _modeling_layer._module.weight_hh_l1_reverse
2018-02-21 15:50:42,264 - INFO - allennlp.nn.initializers -    _modeling_layer._module.weight_ih_l0
2018-02-21 15:50:42,264 - INFO - allennlp.nn.initializers -    _modeling_layer._module.weight_ih_l0_reverse
2018-02-21 15:50:42,264 - INFO - allennlp.nn.initializers -    _modeling_layer._module.weight_ih_l1
2018-02-21 15:50:42,264 - INFO - allennlp.nn.initializers -    _modeling_layer._module.weight_ih_l1_reverse
2018-02-21 15:50:42,264 - INFO - allennlp.nn.initializers -    _phrase_layer._module.bias_hh_l0
2018-02-21 15:50:42,264 - INFO - allennlp.nn.initializers -    _phrase_layer._module.bias_hh_l0_reverse
2018-02-21 15:50:42,264 - INFO - allennlp.nn.initializers -    _phrase_layer._module.bias_ih_l0
2018-02-21 15:50:42,265 - INFO - allennlp.nn.initializers -    _phrase_layer._module.bias_ih_l0_reverse
2018-02-21 15:50:42,265 - INFO - allennlp.nn.initializers -    _phrase_layer._module.weight_hh_l0
2018-02-21 15:50:42,265 - INFO - allennlp.nn.initializers -    _phrase_layer._module.weight_hh_l0_reverse
2018-02-21 15:50:42,265 - INFO - allennlp.nn.initializers -    _phrase_layer._module.weight_ih_l0
2018-02-21 15:50:42,265 - INFO - allennlp.nn.initializers -    _phrase_layer._module.weight_ih_l0_reverse
2018-02-21 15:50:42,265 - INFO - allennlp.nn.initializers -    _span_end_encoder._module.bias_hh_l0
2018-02-21 15:50:42,265 - INFO - allennlp.nn.initializers -    _span_end_encoder._module.bias_hh_l0_reverse
2018-02-21 15:50:42,265 - INFO - allennlp.nn.initializers -    _span_end_encoder._module.bias_ih_l0
2018-02-21 15:50:42,265 - INFO - allennlp.nn.initializers -    _span_end_encoder._module.bias_ih_l0_reverse
2018-02-21 15:50:42,266 - INFO - allennlp.nn.initializers -    _span_end_encoder._module.weight_hh_l0
2018-02-21 15:50:42,266 - INFO - allennlp.nn.initializers -    _span_end_encoder._module.weight_hh_l0_reverse
2018-02-21 15:50:42,266 - INFO - allennlp.nn.initializers -    _span_end_encoder._module.weight_ih_l0
2018-02-21 15:50:42,266 - INFO - allennlp.nn.initializers -    _span_end_encoder._module.weight_ih_l0_reverse
2018-02-21 15:50:42,266 - INFO - allennlp.nn.initializers -    _span_end_predictor._module.bias
2018-02-21 15:50:42,266 - INFO - allennlp.nn.initializers -    _span_end_predictor._module.weight
2018-02-21 15:50:42,266 - INFO - allennlp.nn.initializers -    _span_start_predictor._module.bias
2018-02-21 15:50:42,266 - INFO - allennlp.nn.initializers -    _span_start_predictor._module.weight
2018-02-21 15:50:42,266 - INFO - allennlp.nn.initializers -    _text_field_embedder.token_embedder_token_characters._embedding._module.weight
2018-02-21 15:50:42,266 - INFO - allennlp.nn.initializers -    _text_field_embedder.token_embedder_token_characters._encoder._module.conv_layer_0.bias
2018-02-21 15:50:42,267 - INFO - allennlp.nn.initializers -    _text_field_embedder.token_embedder_token_characters._encoder._module.conv_layer_0.weight
2018-02-21 15:50:42,267 - INFO - allennlp.nn.initializers -    _text_field_embedder.token_embedder_tokens.weight
2018-02-21 15:50:42,473 - INFO - allennlp.common.params - dataset_reader.type = squad
2018-02-21 15:50:42,474 - INFO - allennlp.common.params - dataset_reader.tokenizer.type = word
2018-02-21 15:50:42,474 - INFO - allennlp.common.params - dataset_reader.tokenizer.word_splitter.type = spacy
2018-02-21 15:50:42,474 - INFO - allennlp.common.params - dataset_reader.tokenizer.word_splitter.language = en_core_web_sm
2018-02-21 15:50:42,474 - INFO - allennlp.common.params - dataset_reader.tokenizer.word_splitter.pos_tags = False
2018-02-21 15:50:42,475 - INFO - allennlp.common.params - dataset_reader.tokenizer.word_splitter.parse = False
2018-02-21 15:50:42,475 - INFO - allennlp.common.params - dataset_reader.tokenizer.word_splitter.ner = False
2018-02-21 15:50:44,306 - INFO - allennlp.common.params - dataset_reader.tokenizer.word_filter.type = pass_through
2018-02-21 15:50:44,307 - INFO - allennlp.common.params - dataset_reader.tokenizer.word_stemmer.type = pass_through
2018-02-21 15:50:44,307 - INFO - allennlp.common.params - dataset_reader.tokenizer.start_tokens = None
2018-02-21 15:50:44,307 - INFO - allennlp.common.params - dataset_reader.tokenizer.end_tokens = None
2018-02-21 15:50:44,307 - INFO - allennlp.common.params - dataset_reader.token_indexers.tokens.type = single_id
2018-02-21 15:50:44,307 - INFO - allennlp.common.params - dataset_reader.token_indexers.tokens.namespace = tokens
2018-02-21 15:50:44,308 - INFO - allennlp.common.params - dataset_reader.token_indexers.tokens.lowercase_tokens = True
2018-02-21 15:50:44,308 - INFO - allennlp.common.params - dataset_reader.token_indexers.token_characters.type = characters
2018-02-21 15:50:44,308 - INFO - allennlp.common.params - dataset_reader.token_indexers.token_characters.namespace = token_characters
2018-02-21 15:50:44,308 - INFO - allennlp.common.params - dataset_reader.token_indexers.token_characters.character_tokenizer.byte_encoding = utf-8
2018-02-21 15:50:44,308 - INFO - allennlp.common.params - dataset_reader.token_indexers.token_characters.character_tokenizer.lowercase_characters = False
2018-02-21 15:50:44,309 - INFO - allennlp.common.params - dataset_reader.token_indexers.token_characters.character_tokenizer.start_tokens = [259]
2018-02-21 15:50:44,309 - INFO - allennlp.common.params - dataset_reader.token_indexers.token_characters.character_tokenizer.end_tokens = [260, 0, 0, 0, 0, 0]
2018-02-21 15:50:44,309 - INFO - allennlp.common.params - dataset_reader.lazy = False
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/daniel/ideaProjects/allennlp/allennlp/run.py", line 18, in <module>
    main(prog="python -m allennlp.run")
  File "/Users/daniel/ideaProjects/allennlp/allennlp/commands/__init__.py", line 65, in main
    args.func(args)
  File "/Users/daniel/ideaProjects/allennlp/allennlp/commands/predict.py", line 191, in predict_inner
    args.cuda_device)
  File "/Users/daniel/ideaProjects/allennlp/allennlp/commands/predict.py", line 157, in _run
    _run_predictor(batch_json_data)
  File "/Users/daniel/ideaProjects/allennlp/allennlp/commands/predict.py", line 135, in _run_predictor
    result = predictor.predict_json(batch_data[0], cuda_device)
  File "/Users/daniel/ideaProjects/allennlp/allennlp/service/predictors/predictor.py", line 35, in predict_json
    instance, return_dict = self._json_to_instance(inputs)
  File "/Users/daniel/ideaProjects/allennlp/allennlp/service/predictors/bidaf.py", line 19, in _json_to_instance
    question_text = json_dict["question"]
KeyError: 'question'
```

**Comment by joelgrus** [comment]
for `predict` the input file should be in "json lines" format. that is, each line should be a JSON blob representing a single instance
