### ISSUE TITLE
Using GPU for textual entailment prediction fails

### ISSUE THREAD

**Issue by vishnumenon** [allenai/allennlp#919]
I tried to use GPU when doing an entailment prediction, i.e. by running:
```
decomposableAttentionPredictor = DEFAULT_MODELS['textual-entailment'].predictor()
decomposableAttentionPredictor.predict_json({'hypothesis': '...', 'premise': '...'}, 0)
```

and received the following error: 

```
Traceback (most recent call last):
  File "brain.py", line 30, in <module>
    decomposableAttentionPredictor.predict_json({'hypothesis': 'init', 'premise': 'init'}, 0)
  File "/home/me/anaconda3/lib/python3.6/site-packages/allennlp/service/predictors/predictor.py", line 36, in predict_json
    outputs = self._model.forward_on_instance(instance, cuda_device)
  File "/home/me/anaconda3/lib/python3.6/site-packages/allennlp/models/model.py", line 120, in forward_on_instance
    return self.forward_on_instances([instance], cuda_device)[0]
  File "/home/me/anaconda3/lib/python3.6/site-packages/allennlp/models/model.py", line 138, in forward_on_instances
    outputs = self.decode(self(**model_input))
  File "/home/me/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/me/anaconda3/lib/python3.6/site-packages/allennlp/models/decomposable_attention.py", line 123, in forward
    embedded_premise = self._text_field_embedder(premise)
  File "/home/me/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/me/anaconda3/lib/python3.6/site-packages/allennlp/modules/text_field_embedders/basic_text_field_embedder.py", line 52, in forward
    token_vectors = embedder(tensor)
  File "/home/me/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/me/anaconda3/lib/python3.6/site-packages/allennlp/modules/token_embedders/elmo_token_embedder.py", line 62, in forward
    elmo_output = self._elmo(inputs)
  File "/home/me/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/me/anaconda3/lib/python3.6/site-packages/allennlp/modules/elmo.py", line 103, in forward
    bilm_output = self._elmo_lstm(reshaped_inputs)
  File "/home/me/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/me/anaconda3/lib/python3.6/site-packages/allennlp/modules/elmo.py", line 441, in forward
    token_embedding = self._token_embedder(inputs)
  File "/home/me/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/me/anaconda3/lib/python3.6/site-packages/allennlp/modules/elmo.py", line 243, in forward
    self._char_embedding_weights
  File "/home/me/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 923, in embedding
    scale_grad_by_freq, sparse
  File "/home/me/anaconda3/lib/python3.6/site-packages/torch/nn/_functions/thnn/sparse.py", line 59, in forward
    output = torch.index_select(weight, 0, indices.view(-1))
TypeError: torch.index_select received an invalid combination of arguments - got (torch.FloatTensor, int, torch.cuda.LongTensor), but expected (torch.FloatTensor source, int dim, torch.LongTensor index)
```

I imagine it's just a matter of adding a .cpu() but I wasn't sure if there's anything else that needs to be changed -- or am I doing something wrong?

**Comment by matt-gardner** [comment]
The `cuda_device` parameter that's passed to `predict_json` only affects what device the _input tensors_ get created on.  It doesn't affect where the model lives.  You are calling `predict_json` programmatically, instead of with our command line tools, and you've probably forgotten to call `model.cuda(cuda_device)` on the model that you've passed to that predictor.

That should fix your particular issue, but to fix this for future users, we should do one of the following:

1. Improve the documentation for `Predictor.predict_json`, `Model.forward_on_instance`, and anywhere else that's relevant, saying that the `cuda_device` flag there only affects the input tensors, not the model, and the model device needs to match.
2. If the input tensors need to match the device the model is on, and we're calling `forward_on_instance` _from the model_, shouldn't we already know what device to use for creating input tensors?  Why do we need the `cuda_device` argument for these methods at all?  Seems like it should be easy to remove it.

**Comment by vishnumenon** [comment]
Thanks, that was definitely the problem. Is there an easy way to move an instance of DemoModel onto the gpu? Or should I just write my own class to replace DemoModel that calls load_archive with a gpu specified?

**Comment by matt-gardner** [comment]
Why do you have a `DemoModel` object?  I'm pretty sure that class is only used for running demo.allennlp.org.  If you're wanting to just make a `Predictor` and a web demo, you can do that by following [this tutorial](https://github.com/allenai/allennlp/blob/master/tutorials/getting_started/making_predictions_and_creating_a_demo.md).

**Comment by vishnumenon** [comment]
Fair enough, I was using DemoModel because I'd just wanted to use one of the pre-trained models and it seemed like the easiest approach. I'll make my own from the tutorial, thanks.

**Comment by matt-gardner** [comment]
Oh, sorry, I just looked at the code a bit more, and the simple server mentioned in that tutorial also uses the `DemoModel` class.  Looks like there's no way that you can currently run demos on GPUs.  Do you really want to do that?

**Comment by matt-gardner** [comment]
If you just want to make predictions from the command line, you can do that with our command line tools and our pre-trained models without much trouble - the tutorials should show you how to do that, and if they don't, please feel free to ask questions, and we'll fix them.

If you want to make predictions using our pretrained models and a `Predictor` class that instantiate in your own code, that's fine too, and you can do it just by instantiated a model yourself and passing it to the predictor (you can do this by calling `load_archive()` yourself and pulling out the model that's loaded).  You don't need a `DemoModel` for this, just a `Model`.  `DemoModel` is only used when serving web demos.

**Comment by vishnumenon** [comment]
The latter option sounds like it should work for me, I'll give it a try and let you know if anything goes wrong. Thanks for the help!
