### ISSUE TITLE
Issue with training crf tagger on Power8 system

### ISSUE THREAD

**Issue by jateeq** [allenai/allennlp#937]
I've been able to install AllenNLP on an x86 system and train the available crf tagger without issues. Moving to a Power8 system I've been able to install AllenNLP but on training I get the following ImportError. 

```
$ python -m allennlp.run train crf_tagger.json -s test
/home/jawad/anaconda3_minsky/envs/allennlp/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/home/jawad/anaconda3_minsky/envs/allennlp/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/jawad/anaconda3_minsky/envs/allennlp/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jawad/dev/allennlp/allennlp/run.py", line 15, in <module>
    from allennlp.commands import main  # pylint: disable=wrong-import-position
  File "/home/jawad/dev/allennlp/allennlp/commands/__init__.py", line 6, in <module>
    from allennlp.commands.elmo import Elmo
  File "/home/jawad/dev/allennlp/allennlp/commands/elmo.py", line 59, in <module>
    from allennlp.modules.elmo import _ElmoBiLm
  File "/home/jawad/dev/allennlp/allennlp/modules/__init__.py", line 14, in <module>
    from allennlp.modules.seq2seq_encoders import Seq2SeqEncoder
  File "/home/jawad/dev/allennlp/allennlp/modules/seq2seq_encoders/__init__.py", line 89, in <module>
    from allennlp.modules.alternating_highway_lstm import AlternatingHighwayLSTM
  File "/home/jawad/dev/allennlp/allennlp/modules/alternating_highway_lstm.py", line 10, in <module>
    from allennlp.custom_extensions._ext import highway_lstm_layer
  File "/home/jawad/dev/allennlp/allennlp/custom_extensions/_ext/highway_lstm_layer/__init__.py", line 3, in <module>
    from ._highway_lstm_layer import lib as _lib, ffi as _ffi
ImportError: /home/jawad/dev/allennlp/allennlp/custom_extensions/_ext/highway_lstm_layer/_highway_lstm_layer.so: cannot open shared object file: No such file or directory
```

My Environment:
- Operating System: Ubuntu 16.04.3 LTS on Power8 (little endian)
- Python Version Used: Python 3.6.2 |Anaconda, Inc.|
- AllenNLP Version Used: Master from 02/28/2018 (commit starting with dcd648)

Do I need to build differently for ppc64le?

**Comment by DeNeutoy** [comment]
Hello - sorry, the `try except` block here is not relaxed enough: https://github.com/allenai/allennlp/blob/master/allennlp/modules/seq2seq_encoders/__init__.py#L91

I will open a PR to fix this now, but in the immediate short term, if you have cloned allennlp, is:

```
cd /home/jawad/dev/allennlp/allennlp/custom_extensions/
bash make.sh
```
This assumes that a GPU is available on your machine. Alternatively you could just remove the attempted import in the seq2seq_encoders `__init__.py`.

**Comment by jateeq** [comment]
@DeNeutoy 
I commented out the try except block for now and it works. Thanks!

I tried building the highway lstm but I got the following error, so went with method above.

```
Building kernel for following target architectures:
-gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61
Compiling kernel
make.sh: line 40: /usr/local/cuda/bin/nvcc: No such file or directory
generating /tmp/tmpbk_a51g0/_highway_lstm_layer.c
setting the current directory to '/tmp/tmpbk_a51g0'
running build_ext
building '_highway_lstm_layer' extension
creating home
creating home/jawad
creating home/jawad/dev
creating home/jawad/dev/allennlp
creating home/jawad/dev/allennlp/allennlp
creating home/jawad/dev/allennlp/allennlp/custom_extensions
creating home/jawad/dev/allennlp/allennlp/custom_extensions/src
gcc -pthread -B /home/jawad/anaconda3_minsky/envs/allennlp/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/jawad/anaconda3_minsky/envs/allennlp/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/jawad/anaconda3_minsky/envs/allennlp/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/jawad/anaconda3_minsky/envs/allennlp/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/home/jawad/anaconda3_minsky/envs/allennlp/include/python3.6m -c _highway_lstm_layer.c -o ./_highway_lstm_layer.o
In file included from /home/jawad/anaconda3_minsky/envs/allennlp/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC/THC.h:4:0,
                 from _highway_lstm_layer.c:483:
/home/jawad/anaconda3_minsky/envs/allennlp/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC/THCGeneral.h:10:18: fatal error: cuda.h: No such file or directory
compilation terminated.
Traceback (most recent call last):
  File "/home/jawad/anaconda3_minsky/envs/allennlp/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/home/jawad/anaconda3_minsky/envs/allennlp/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/home/jawad/anaconda3_minsky/envs/allennlp/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/home/jawad/anaconda3_minsky/envs/allennlp/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jawad/anaconda3_minsky/envs/allennlp/lib/python3.6/site-packages/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/home/jawad/anaconda3_minsky/envs/allennlp/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/jawad/anaconda3_minsky/envs/allennlp/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/jawad/anaconda3_minsky/envs/allennlp/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/jawad/anaconda3_minsky/envs/allennlp/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/jawad/anaconda3_minsky/envs/allennlp/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/home/jawad/anaconda3_minsky/envs/allennlp/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/home/jawad/anaconda3_minsky/envs/allennlp/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 29, in <module>
    ffi.build()
  File "/home/jawad/anaconda3_minsky/envs/allennlp/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 186, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/jawad/anaconda3_minsky/envs/allennlp/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 109, in _build_extension
    ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/jawad/anaconda3_minsky/envs/allennlp/lib/python3.6/site-packages/cffi/api.py", line 690, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/jawad/anaconda3_minsky/envs/allennlp/lib/python3.6/site-packages/cffi/recompiler.py", line 1513, in recompile
    compiler_verbose, debug)
  File "/home/jawad/anaconda3_minsky/envs/allennlp/lib/python3.6/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/jawad/anaconda3_minsky/envs/allennlp/lib/python3.6/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'gcc' failed with exit status 1
```

Jawad
