### ISSUE TITLE
Tensorboard problem again?

### ISSUE THREAD

**Issue by LeoLiu1998** [allenai/allennlp#943]
I am not sure if this error is due to my configuration or the allennlp. 
After I test the trained `simple_seq2seq` model, I decided to use beam search decoding, so I copy and change the decoding method in the simple_seq2seq model. To test my program, I rename the model registration to be `WebQABase`, and also change the config file in **model.tar.gz**(decompress, change configure file, and compress again). However, after I entered 

`~/hyak-package/WebQA > python -m allennlp.run predict WebQA/result/model.tar.gz WebQA/prediction/prediction.jsonl  --include-package WebQA --predictor baseline > WebQA/baseline_prediction.txt `

The terminal give me an error message:
```
/Users/leoliu/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/Users/leoliu/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/leoliu/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/leoliu/allennlp/allennlp/run.py", line 15, in <module>
    from allennlp.commands import main  # pylint: disable=wrong-import-position
  File "/Users/leoliu/allennlp/allennlp/commands/__init__.py", line 7, in <module>
    from allennlp.commands.evaluate import Evaluate
  File "/Users/leoliu/allennlp/allennlp/commands/evaluate.py", line 43, in <module>
    from allennlp.models.archival import load_archive
  File "/Users/leoliu/allennlp/allennlp/models/__init__.py", line 7, in <module>
    from allennlp.models.crf_tagger import CrfTagger
  File "/Users/leoliu/allennlp/allennlp/models/crf_tagger.py", line 15, in <module>
    from allennlp.training.metrics import SpanBasedF1Measure
  File "/Users/leoliu/allennlp/allennlp/training/__init__.py", line 1, in <module>
    from allennlp.training.trainer import Trainer
  File "/Users/leoliu/allennlp/allennlp/training/trainer.py", line 24, in <module>
    from tensorboardX import SummaryWriter
  File "/Users/leoliu/anaconda3/lib/python3.6/site-packages/tensorboardX/__init__.py", line 4, in <module>
    from .writer import FileWriter, SummaryWriter
  File "/Users/leoliu/anaconda3/lib/python3.6/site-packages/tensorboardX/writer.py", line 28, in <module>
    from .summary import scalar, histogram, image, audio, text
  File "/Users/leoliu/anaconda3/lib/python3.6/site-packages/tensorboardX/summary.py", line 47, in <module>
    from .src.tensor_pb2 import TensorProto
  File "/Users/leoliu/anaconda3/lib/python3.6/site-packages/tensorboardX/src/tensor_pb2.py", line 155, in <module>
    _TENSORPROTO.fields_by_name['resource_handle_val'].message_type = tensorboard_dot_src_dot_resource__handle__pb2._RESOURCEHANDLEPROTO
AttributeError: module 'tensorboard.src.resource_handle_pb2' has no attribute '_RESOURCEHANDLEPROTO'
```

**Comment by DeNeutoy** [comment]
Is your environment clean? It seems likely that this is a problem with having another tensorboard install in your env which is clashing with what `tensorboardX` needs.

**Comment by LeoLiu1998** [comment]
Yeah, that's the problem. Thanks!
