### ISSUE TITLE
Constituency Parsing CMD Error (from trained model)

### ISSUE THREAD

**Issue by yanaiela** [allenai/allennlp#994]
Hey,

I wanted to try out the constituency parser using the Elmo embedding.
I followed the package installation process, with no problems and then tried to use the trained model using [this example](http://allennlp.org/models) but encountered the following exception:

> Traceback (most recent call last):
  File "/home/nlp/lazary/anaconda2/envs/allennlp/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/nlp/lazary/anaconda2/envs/allennlp/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/nlp/lazary/anaconda2/envs/allennlp/lib/python3.6/site-packages/allennlp/run.py", line 18, in <module>
    main(prog="python -m allennlp.run")
  File "/home/nlp/lazary/anaconda2/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 67, in main
    args.func(args)
  File "/home/nlp/lazary/anaconda2/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/predict.py", line 172, in predict_inner
    predictor = _get_predictor(args, predictors)
  File "/home/nlp/lazary/anaconda2/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/predict.py", line 114, in _get_predictor
    overrides=args.overrides)
  File "/home/nlp/lazary/anaconda2/envs/allennlp/lib/python3.6/site-packages/allennlp/models/archival.py", line 149, in load_archive
    cuda_device=cuda_device)
  File "/home/nlp/lazary/anaconda2/envs/allennlp/lib/python3.6/site-packages/allennlp/models/model.py", line 233, in load
    model = Model.from_params(vocab, model_params)
  File "/home/nlp/lazary/anaconda2/envs/allennlp/lib/python3.6/site-packages/allennlp/models/model.py", line 184, in from_params
    model = cls.by_name(choice).from_params(vocab, params)
  File "/home/nlp/lazary/anaconda2/envs/allennlp/lib/python3.6/site-packages/allennlp/models/constituency_parser.py", line 431, in from_params
    params.assert_empty(cls.__name__)
  File "/home/nlp/lazary/anaconda2/envs/allennlp/lib/python3.6/site-packages/allennlp/common/params.py", line 246, in assert_empty
    raise ConfigurationError("Extra parameters passed to {}: {}".format(class_name, self.params))
allennlp.common.checks.ConfigurationError: "Extra parameters passed to SpanConstituencyParser: ConfigTree([('pos_tag_embedding', ConfigTree([('embedding_dim', 50), ('vocab_namespace', 'pos')]))])"

For a sanity check, I also tried the NER classifier and it worked without any issues.

**Comment by DeNeutoy** [comment]
Hello! The current form of the constituency parsing model is not in the latest pip release. Please try installing by cloning the repo and running `python setup.py install` or by pip installing from the current `master` commit.

**Comment by yanaiela** [comment]
Hi Mark, thanks for the response.

Unfortunately, still no luck, even with the manual installation.
I'm getting the following error this time:

> Traceback (most recent call last):
  File "/home/nlp/lazary/anaconda2/envs/allennlp/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/nlp/lazary/anaconda2/envs/allennlp/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/nlp/lazary/anaconda2/envs/allennlp/lib/python3.6/site-packages/allennlp-0.4.1_unreleased-py3.6.egg/allennlp/run.py", line 18, in <module>
    main(prog="python -m allennlp.run")
  File "/home/nlp/lazary/anaconda2/envs/allennlp/lib/python3.6/site-packages/allennlp-0.4.1_unreleased-py3.6.egg/allennlp/commands/__init__.py", line 73, in main
    args.func(args)
  File "/home/nlp/lazary/anaconda2/envs/allennlp/lib/python3.6/site-packages/allennlp-0.4.1_unreleased-py3.6.egg/allennlp/commands/predict.py", line 161, in predict_inner
    predictor = _get_predictor(args, predictors)
  File "/home/nlp/lazary/anaconda2/envs/allennlp/lib/python3.6/site-packages/allennlp-0.4.1_unreleased-py3.6.egg/allennlp/commands/predict.py", line 116, in _get_predictor
    raise ConfigurationError("no known predictor for model type {}".format(model_type))
allennlp.common.checks.ConfigurationError: 'no known predictor for model type constituency_parser'

**Comment by matt-gardner** [comment]
This is because we haven't added the parser predictor here:

https://github.com/allenai/allennlp/blob/0c532d50ac52bca48bf9906864daf6735d5d02de/allennlp/commands/predict.py#L53-L60

We will get this fixed soon, but until then, you can just pass the flag `--predictor=constituency-parser`, and it should work.

**Comment by matt-gardner** [comment]
I'm re-opening this so we remember to make the fix.

**Comment by yanaiela** [comment]
oh sorry,

thanks for the help!

**Comment by matt-gardner** [comment]
We just need to add a line to the block that I quoted above, that maps the model name (`'constituency_parser'`, found [here](https://github.com/allenai/allennlp/blob/0c532d50ac52bca48bf9906864daf6735d5d02de/allennlp/models/constituency_parser.py#L44)) to the predictor name (`'constituency-parser'`, found [here](https://github.com/allenai/allennlp/blob/0c532d50ac52bca48bf9906864daf6735d5d02de/allennlp/service/predictors/constituency_parser.py#L60)).
